package com.okinc.assets.backend.api.model;

import com.google.api.client.googleapis.media.MediaHttpDownloader;
import com.huawei.hms.push.constant.RemoteMessageConst;
import com.okinc.p2p.api.OtcExtraKeys;
import java.util.List;
import kotlin.Unit;
import kotlin.jvm.internal.Intrinsics;
import kotlinx.serialization.KSerializer;
import kotlinx.serialization.UnknownFieldException;
import kotlinx.serialization.builtins.BuiltinSerializersKt;
import kotlinx.serialization.descriptors.SerialDescriptor;
import kotlinx.serialization.encoding.CompositeDecoder;
import kotlinx.serialization.encoding.CompositeEncoder;
import kotlinx.serialization.encoding.Decoder;
import kotlinx.serialization.encoding.Encoder;
import kotlinx.serialization.internal.BooleanSerializer;
import kotlinx.serialization.internal.GeneratedSerializer;
import kotlinx.serialization.internal.IntSerializer;
import kotlinx.serialization.internal.LongSerializer;
import kotlinx.serialization.internal.PluginGeneratedSerialDescriptor;
import kotlinx.serialization.internal.SerializationConstructorMarker;
import kotlinx.serialization.internal.StringSerializer;
import org.jetbrains.annotations.NotNull;

/* JADX INFO: loaded from: classes3.dex */
public final /* synthetic */ class ChainData$$serializer implements GeneratedSerializer<ChainData> {
    public static final int $stable;
    public static final ChainData$$serializer INSTANCE;
    private static final SerialDescriptor descriptor;

    /* JADX DEBUG: Don't trust debug lines info. Lines numbers was adjusted: min line is 0 */
    private ChainData$$serializer() {
    }

    /* JADX DEBUG: Don't trust debug lines info. Lines numbers was adjusted: min line is 0 */
    @Override // kotlinx.serialization.KSerializer, kotlinx.serialization.SerializationStrategy, kotlinx.serialization.DeserializationStrategy
    public final SerialDescriptor getDescriptor() {
        return descriptor;
    }

    static {
        ChainData$$serializer chainData$$serializer = new ChainData$$serializer();
        INSTANCE = chainData$$serializer;
        $stable = 8;
        PluginGeneratedSerialDescriptor pluginGeneratedSerialDescriptor = new PluginGeneratedSerialDescriptor("com.okinc.assets.backend.api.model.ChainData", chainData$$serializer, 40);
        pluginGeneratedSerialDescriptor.addElement("contractAddress", true);
        pluginGeneratedSerialDescriptor.addElement("desc", true);
        pluginGeneratedSerialDescriptor.addElement("estimatedOpenTime", true);
        pluginGeneratedSerialDescriptor.addElement("name", true);
        pluginGeneratedSerialDescriptor.addElement(OtcExtraKeys.TRADING_TERMS, true);
        pluginGeneratedSerialDescriptor.addElement("status", true);
        pluginGeneratedSerialDescriptor.addElement("subCurrencyId", true);
        pluginGeneratedSerialDescriptor.addElement("type", true);
        pluginGeneratedSerialDescriptor.addElement("updateKyc", true);
        pluginGeneratedSerialDescriptor.addElement("singleMax", true);
        pluginGeneratedSerialDescriptor.addElement("singleMin", true);
        pluginGeneratedSerialDescriptor.addElement("dailyMax", true);
        pluginGeneratedSerialDescriptor.addElement("singleMaxValuation", true);
        pluginGeneratedSerialDescriptor.addElement("singleMinValuation", true);
        pluginGeneratedSerialDescriptor.addElement("dailyMaxValuation", true);
        pluginGeneratedSerialDescriptor.addElement("congested", true);
        pluginGeneratedSerialDescriptor.addElement("estimatedArrivalTime", true);
        pluginGeneratedSerialDescriptor.addElement("gasFee", true);
        pluginGeneratedSerialDescriptor.addElement("usdGasFee", true);
        pluginGeneratedSerialDescriptor.addElement("gasFeeSymbol", true);
        pluginGeneratedSerialDescriptor.addElement("usdGasFeeSymbol", true);
        pluginGeneratedSerialDescriptor.addElement("validAddress", true);
        pluginGeneratedSerialDescriptor.addElement("needTag", true);
        pluginGeneratedSerialDescriptor.addElement("networkType", true);
        pluginGeneratedSerialDescriptor.addElement("arrivalType", true);
        pluginGeneratedSerialDescriptor.addElement("confirmNum", true);
        pluginGeneratedSerialDescriptor.addElement("minDeposit", true);
        pluginGeneratedSerialDescriptor.addElement(RemoteMessageConst.Notification.ICON, true);
        pluginGeneratedSerialDescriptor.addElement("networkIcon", true);
        pluginGeneratedSerialDescriptor.addElement("networkName", true);
        pluginGeneratedSerialDescriptor.addElement("estimatedDepositCreditedTime", true);
        pluginGeneratedSerialDescriptor.addElement("supportType", true);
        pluginGeneratedSerialDescriptor.addElement("mintedCoinName", true);
        pluginGeneratedSerialDescriptor.addElement("mintedCoinId", true);
        pluginGeneratedSerialDescriptor.addElement("gasAirdropTagEnabled", true);
        pluginGeneratedSerialDescriptor.addElement("freeWithdrawFeeTagEnabled", true);
        pluginGeneratedSerialDescriptor.addElement("contracts", true);
        pluginGeneratedSerialDescriptor.addElement("lstCurrencyName", true);
        pluginGeneratedSerialDescriptor.addElement("chainId", true);
        pluginGeneratedSerialDescriptor.addElement("switchAddressType", true);
        descriptor = pluginGeneratedSerialDescriptor;
    }

    @Override // kotlinx.serialization.internal.GeneratedSerializer
    public final KSerializer<?>[] childSerializers() {
        KSerializer[] kSerializerArr = ChainData.$childSerializers;
        StringSerializer stringSerializer = StringSerializer.INSTANCE;
        BooleanSerializer booleanSerializer = BooleanSerializer.INSTANCE;
        IntSerializer intSerializer = IntSerializer.INSTANCE;
        return new KSerializer[]{BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), LongSerializer.INSTANCE, BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), booleanSerializer, intSerializer, intSerializer, booleanSerializer, BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), booleanSerializer, intSerializer, BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), booleanSerializer, booleanSerializer, intSerializer, intSerializer, intSerializer, BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(intSerializer), BuiltinSerializersKt.getNullable(intSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(intSerializer), BuiltinSerializersKt.getNullable(booleanSerializer), BuiltinSerializersKt.getNullable(booleanSerializer), BuiltinSerializersKt.getNullable(kSerializerArr[36]), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(intSerializer), BuiltinSerializersKt.getNullable(intSerializer)};
    }

    /* JADX DEBUG: Method merged with bridge method: deserialize(Lkotlinx/serialization/encoding/Decoder;)Ljava/lang/Object; */
    @Override // kotlinx.serialization.DeserializationStrategy
    public final ChainData deserialize(@NotNull Decoder decoder) {
        int i;
        String str;
        Integer num;
        Integer num2;
        Integer num3;
        Boolean bool;
        Boolean bool2;
        List list;
        String str2;
        Integer num4;
        String str3;
        int i2;
        String str4;
        String str5;
        boolean z;
        String str6;
        boolean z2;
        String str7;
        String str8;
        String str9;
        String str10;
        String str11;
        String str12;
        String str13;
        String str14;
        Integer num5;
        int i3;
        String str15;
        String str16;
        String str17;
        boolean z3;
        boolean z4;
        String str18;
        String str19;
        int i4;
        long j;
        int i5;
        int i6;
        int i7;
        int i8;
        String str20;
        boolean z5;
        KSerializer[] kSerializerArr;
        int i9;
        String str21;
        Integer num6;
        String str22;
        String str23;
        String str24;
        String str25;
        String str26;
        String str27;
        String str28;
        String str29;
        String str30;
        String str31;
        String str32;
        String str33;
        int i10;
        String str34;
        int iDecodeIntElement;
        String str35;
        Integer num7;
        String str36;
        int i11;
        Boolean bool3;
        int i12;
        Intrinsics.checkNotNullParameter(decoder, "");
        SerialDescriptor serialDescriptor = descriptor;
        CompositeDecoder compositeDecoderBeginStructure = decoder.beginStructure(serialDescriptor);
        KSerializer[] kSerializerArr2 = ChainData.$childSerializers;
        if (compositeDecoderBeginStructure.decodeSequentially()) {
            StringSerializer stringSerializer = StringSerializer.INSTANCE;
            String str37 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 0, stringSerializer, null);
            String str38 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 1, stringSerializer, null);
            long jDecodeLongElement = compositeDecoderBeginStructure.decodeLongElement(serialDescriptor, 2);
            String str39 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 3, stringSerializer, null);
            String str40 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 4, stringSerializer, null);
            boolean zDecodeBooleanElement = compositeDecoderBeginStructure.decodeBooleanElement(serialDescriptor, 5);
            int iDecodeIntElement2 = compositeDecoderBeginStructure.decodeIntElement(serialDescriptor, 6);
            int iDecodeIntElement3 = compositeDecoderBeginStructure.decodeIntElement(serialDescriptor, 7);
            boolean zDecodeBooleanElement2 = compositeDecoderBeginStructure.decodeBooleanElement(serialDescriptor, 8);
            String str41 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 9, stringSerializer, null);
            String str42 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 10, stringSerializer, null);
            String str43 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 11, stringSerializer, null);
            String str44 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 12, stringSerializer, null);
            String str45 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 13, stringSerializer, null);
            String str46 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 14, stringSerializer, null);
            boolean zDecodeBooleanElement3 = compositeDecoderBeginStructure.decodeBooleanElement(serialDescriptor, 15);
            int iDecodeIntElement4 = compositeDecoderBeginStructure.decodeIntElement(serialDescriptor, 16);
            String str47 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 17, stringSerializer, null);
            String str48 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 18, stringSerializer, null);
            String str49 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 19, stringSerializer, null);
            String str50 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 20, stringSerializer, null);
            boolean zDecodeBooleanElement4 = compositeDecoderBeginStructure.decodeBooleanElement(serialDescriptor, 21);
            boolean zDecodeBooleanElement5 = compositeDecoderBeginStructure.decodeBooleanElement(serialDescriptor, 22);
            int iDecodeIntElement5 = compositeDecoderBeginStructure.decodeIntElement(serialDescriptor, 23);
            int iDecodeIntElement6 = compositeDecoderBeginStructure.decodeIntElement(serialDescriptor, 24);
            int iDecodeIntElement7 = compositeDecoderBeginStructure.decodeIntElement(serialDescriptor, 25);
            String str51 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 26, stringSerializer, null);
            String str52 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 27, stringSerializer, null);
            String str53 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 28, stringSerializer, null);
            String str54 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 29, stringSerializer, null);
            IntSerializer intSerializer = IntSerializer.INSTANCE;
            Integer num8 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 30, intSerializer, null);
            Integer num9 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 31, intSerializer, null);
            String str55 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 32, stringSerializer, null);
            Integer num10 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 33, intSerializer, null);
            BooleanSerializer booleanSerializer = BooleanSerializer.INSTANCE;
            Boolean bool4 = (Boolean) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 34, booleanSerializer, null);
            Boolean bool5 = (Boolean) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 35, booleanSerializer, null);
            List list2 = (List) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 36, kSerializerArr2[36], null);
            String str56 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 37, stringSerializer, null);
            Integer num11 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 38, intSerializer, null);
            num4 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 39, intSerializer, null);
            str2 = str56;
            bool = bool5;
            num = num11;
            list = list2;
            str4 = str55;
            str11 = str51;
            i = iDecodeIntElement7;
            str = str37;
            str12 = str52;
            str13 = str53;
            str14 = str54;
            num5 = num8;
            num2 = num9;
            num3 = num10;
            bool2 = bool4;
            str3 = str48;
            i2 = 255;
            z2 = zDecodeBooleanElement3;
            z4 = zDecodeBooleanElement2;
            i4 = iDecodeIntElement4;
            str15 = str46;
            str16 = str47;
            j = jDecodeLongElement;
            str10 = str50;
            z3 = zDecodeBooleanElement5;
            i5 = iDecodeIntElement6;
            z = zDecodeBooleanElement4;
            i3 = -1;
            str5 = str38;
            str8 = str42;
            i7 = iDecodeIntElement3;
            i8 = iDecodeIntElement2;
            str19 = str43;
            str17 = str45;
            str6 = str39;
            str9 = str49;
            z5 = zDecodeBooleanElement;
            str7 = str41;
            str20 = str44;
            str18 = str40;
            i6 = iDecodeIntElement5;
        } else {
            int i13 = 0;
            Boolean bool6 = null;
            boolean zDecodeBooleanElement6 = false;
            boolean zDecodeBooleanElement7 = false;
            boolean zDecodeBooleanElement8 = false;
            boolean zDecodeBooleanElement9 = false;
            boolean zDecodeBooleanElement10 = false;
            int i14 = 0;
            i = 0;
            int iDecodeIntElement8 = 0;
            int iDecodeIntElement9 = 0;
            String str57 = null;
            Integer num12 = null;
            Integer num13 = null;
            Integer num14 = null;
            Boolean bool7 = null;
            List list3 = null;
            String str58 = null;
            Integer num15 = null;
            String str59 = null;
            Integer num16 = null;
            String str60 = null;
            String str61 = null;
            String str62 = null;
            String str63 = null;
            String str64 = null;
            String str65 = null;
            String str66 = null;
            String str67 = null;
            String str68 = null;
            String str69 = null;
            String str70 = null;
            String str71 = null;
            String str72 = null;
            String str73 = null;
            String str74 = null;
            String str75 = null;
            String str76 = null;
            boolean z6 = true;
            long jDecodeLongElement2 = 0;
            int i15 = 0;
            int iDecodeIntElement10 = 0;
            int iDecodeIntElement11 = 0;
            while (z6) {
                String str77 = str59;
                int iDecodeElementIndex = compositeDecoderBeginStructure.decodeElementIndex(serialDescriptor);
                switch (iDecodeElementIndex) {
                    case -1:
                        kSerializerArr = kSerializerArr2;
                        i9 = i13;
                        str21 = str57;
                        num6 = num16;
                        str22 = str64;
                        str23 = str65;
                        str24 = str66;
                        str25 = str67;
                        str26 = str68;
                        str27 = str69;
                        str28 = str70;
                        str29 = str71;
                        str30 = str72;
                        str31 = str73;
                        str32 = str76;
                        Unit unit = Unit.INSTANCE;
                        z6 = false;
                        str35 = str23;
                        str76 = str32;
                        i13 = i9;
                        str59 = str77;
                        num16 = num6;
                        str65 = str35;
                        str64 = str22;
                        str57 = str21;
                        str66 = str24;
                        str67 = str25;
                        str73 = str31;
                        str72 = str30;
                        str71 = str29;
                        str70 = str28;
                        str69 = str27;
                        str68 = str26;
                        kSerializerArr2 = kSerializerArr;
                        break;
                    case 0:
                        kSerializerArr = kSerializerArr2;
                        i9 = i13;
                        str21 = str57;
                        num6 = num16;
                        str22 = str64;
                        str23 = str65;
                        str24 = str66;
                        str25 = str67;
                        str26 = str68;
                        str27 = str69;
                        str28 = str70;
                        str29 = str71;
                        str30 = str72;
                        str32 = str76;
                        str31 = str73;
                        str75 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 0, StringSerializer.INSTANCE, str75);
                        i15 |= 1;
                        Unit unit2 = Unit.INSTANCE;
                        str35 = str23;
                        str76 = str32;
                        i13 = i9;
                        str59 = str77;
                        num16 = num6;
                        str65 = str35;
                        str64 = str22;
                        str57 = str21;
                        str66 = str24;
                        str67 = str25;
                        str73 = str31;
                        str72 = str30;
                        str71 = str29;
                        str70 = str28;
                        str69 = str27;
                        str68 = str26;
                        kSerializerArr2 = kSerializerArr;
                        break;
                    case 1:
                        kSerializerArr = kSerializerArr2;
                        i9 = i13;
                        str21 = str57;
                        num6 = num16;
                        str22 = str64;
                        str23 = str65;
                        str24 = str66;
                        str25 = str67;
                        str26 = str68;
                        str27 = str69;
                        str28 = str70;
                        str29 = str71;
                        str32 = str76;
                        str30 = str72;
                        str73 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 1, StringSerializer.INSTANCE, str73);
                        i15 |= 2;
                        Unit unit3 = Unit.INSTANCE;
                        str31 = str73;
                        str35 = str23;
                        str76 = str32;
                        i13 = i9;
                        str59 = str77;
                        num16 = num6;
                        str65 = str35;
                        str64 = str22;
                        str57 = str21;
                        str66 = str24;
                        str67 = str25;
                        str73 = str31;
                        str72 = str30;
                        str71 = str29;
                        str70 = str28;
                        str69 = str27;
                        str68 = str26;
                        kSerializerArr2 = kSerializerArr;
                        break;
                    case 2:
                        kSerializerArr = kSerializerArr2;
                        i9 = i13;
                        str21 = str57;
                        num6 = num16;
                        str22 = str64;
                        str23 = str65;
                        str24 = str66;
                        str25 = str67;
                        str26 = str68;
                        str27 = str69;
                        str28 = str70;
                        str29 = str71;
                        str32 = str76;
                        jDecodeLongElement2 = compositeDecoderBeginStructure.decodeLongElement(serialDescriptor, 2);
                        i15 |= 4;
                        Unit unit4 = Unit.INSTANCE;
                        str30 = str72;
                        str31 = str73;
                        str35 = str23;
                        str76 = str32;
                        i13 = i9;
                        str59 = str77;
                        num16 = num6;
                        str65 = str35;
                        str64 = str22;
                        str57 = str21;
                        str66 = str24;
                        str67 = str25;
                        str73 = str31;
                        str72 = str30;
                        str71 = str29;
                        str70 = str28;
                        str69 = str27;
                        str68 = str26;
                        kSerializerArr2 = kSerializerArr;
                        break;
                    case 3:
                        kSerializerArr = kSerializerArr2;
                        i9 = i13;
                        str21 = str57;
                        num6 = num16;
                        str22 = str64;
                        str23 = str65;
                        str24 = str66;
                        str25 = str67;
                        str26 = str68;
                        str27 = str69;
                        str28 = str70;
                        str32 = str76;
                        str29 = str71;
                        str72 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 3, StringSerializer.INSTANCE, str72);
                        Unit unit5 = Unit.INSTANCE;
                        i15 |= 8;
                        str30 = str72;
                        str31 = str73;
                        str35 = str23;
                        str76 = str32;
                        i13 = i9;
                        str59 = str77;
                        num16 = num6;
                        str65 = str35;
                        str64 = str22;
                        str57 = str21;
                        str66 = str24;
                        str67 = str25;
                        str73 = str31;
                        str72 = str30;
                        str71 = str29;
                        str70 = str28;
                        str69 = str27;
                        str68 = str26;
                        kSerializerArr2 = kSerializerArr;
                        break;
                    case 4:
                        kSerializerArr = kSerializerArr2;
                        i9 = i13;
                        str21 = str57;
                        num6 = num16;
                        str22 = str64;
                        str23 = str65;
                        str24 = str66;
                        str25 = str67;
                        str26 = str68;
                        str27 = str69;
                        str32 = str76;
                        str28 = str70;
                        str71 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 4, StringSerializer.INSTANCE, str71);
                        i15 |= 16;
                        Unit unit6 = Unit.INSTANCE;
                        str29 = str71;
                        str30 = str72;
                        str31 = str73;
                        str35 = str23;
                        str76 = str32;
                        i13 = i9;
                        str59 = str77;
                        num16 = num6;
                        str65 = str35;
                        str64 = str22;
                        str57 = str21;
                        str66 = str24;
                        str67 = str25;
                        str73 = str31;
                        str72 = str30;
                        str71 = str29;
                        str70 = str28;
                        str69 = str27;
                        str68 = str26;
                        kSerializerArr2 = kSerializerArr;
                        break;
                    case 5:
                        kSerializerArr = kSerializerArr2;
                        i9 = i13;
                        str21 = str57;
                        num6 = num16;
                        str22 = str64;
                        str23 = str65;
                        str24 = str66;
                        str25 = str67;
                        str26 = str68;
                        str27 = str69;
                        str32 = str76;
                        zDecodeBooleanElement9 = compositeDecoderBeginStructure.decodeBooleanElement(serialDescriptor, 5);
                        i15 |= 32;
                        Unit unit7 = Unit.INSTANCE;
                        str28 = str70;
                        str29 = str71;
                        str30 = str72;
                        str31 = str73;
                        str35 = str23;
                        str76 = str32;
                        i13 = i9;
                        str59 = str77;
                        num16 = num6;
                        str65 = str35;
                        str64 = str22;
                        str57 = str21;
                        str66 = str24;
                        str67 = str25;
                        str73 = str31;
                        str72 = str30;
                        str71 = str29;
                        str70 = str28;
                        str69 = str27;
                        str68 = str26;
                        kSerializerArr2 = kSerializerArr;
                        break;
                    case 6:
                        kSerializerArr = kSerializerArr2;
                        i9 = i13;
                        str21 = str57;
                        num6 = num16;
                        str22 = str64;
                        str23 = str65;
                        str24 = str66;
                        str25 = str67;
                        str26 = str68;
                        str27 = str69;
                        str32 = str76;
                        iDecodeIntElement9 = compositeDecoderBeginStructure.decodeIntElement(serialDescriptor, 6);
                        i15 |= 64;
                        Unit unit8 = Unit.INSTANCE;
                        str28 = str70;
                        str29 = str71;
                        str30 = str72;
                        str31 = str73;
                        str35 = str23;
                        str76 = str32;
                        i13 = i9;
                        str59 = str77;
                        num16 = num6;
                        str65 = str35;
                        str64 = str22;
                        str57 = str21;
                        str66 = str24;
                        str67 = str25;
                        str73 = str31;
                        str72 = str30;
                        str71 = str29;
                        str70 = str28;
                        str69 = str27;
                        str68 = str26;
                        kSerializerArr2 = kSerializerArr;
                        break;
                    case 7:
                        kSerializerArr = kSerializerArr2;
                        i9 = i13;
                        str21 = str57;
                        num6 = num16;
                        str22 = str64;
                        str23 = str65;
                        str24 = str66;
                        str25 = str67;
                        str26 = str68;
                        str27 = str69;
                        str32 = str76;
                        iDecodeIntElement8 = compositeDecoderBeginStructure.decodeIntElement(serialDescriptor, 7);
                        i15 |= 128;
                        Unit unit9 = Unit.INSTANCE;
                        str28 = str70;
                        str29 = str71;
                        str30 = str72;
                        str31 = str73;
                        str35 = str23;
                        str76 = str32;
                        i13 = i9;
                        str59 = str77;
                        num16 = num6;
                        str65 = str35;
                        str64 = str22;
                        str57 = str21;
                        str66 = str24;
                        str67 = str25;
                        str73 = str31;
                        str72 = str30;
                        str71 = str29;
                        str70 = str28;
                        str69 = str27;
                        str68 = str26;
                        kSerializerArr2 = kSerializerArr;
                        break;
                    case 8:
                        kSerializerArr = kSerializerArr2;
                        i9 = i13;
                        str21 = str57;
                        num6 = num16;
                        str22 = str64;
                        str23 = str65;
                        str24 = str66;
                        str25 = str67;
                        str26 = str68;
                        str27 = str69;
                        str32 = str76;
                        zDecodeBooleanElement8 = compositeDecoderBeginStructure.decodeBooleanElement(serialDescriptor, 8);
                        i15 |= 256;
                        Unit unit10 = Unit.INSTANCE;
                        str28 = str70;
                        str29 = str71;
                        str30 = str72;
                        str31 = str73;
                        str35 = str23;
                        str76 = str32;
                        i13 = i9;
                        str59 = str77;
                        num16 = num6;
                        str65 = str35;
                        str64 = str22;
                        str57 = str21;
                        str66 = str24;
                        str67 = str25;
                        str73 = str31;
                        str72 = str30;
                        str71 = str29;
                        str70 = str28;
                        str69 = str27;
                        str68 = str26;
                        kSerializerArr2 = kSerializerArr;
                        break;
                    case 9:
                        kSerializerArr = kSerializerArr2;
                        i9 = i13;
                        str21 = str57;
                        num6 = num16;
                        str22 = str64;
                        str23 = str65;
                        str24 = str66;
                        str25 = str67;
                        str26 = str68;
                        str32 = str76;
                        str27 = str69;
                        str70 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 9, StringSerializer.INSTANCE, str70);
                        Unit unit11 = Unit.INSTANCE;
                        i15 |= 512;
                        str28 = str70;
                        str29 = str71;
                        str30 = str72;
                        str31 = str73;
                        str35 = str23;
                        str76 = str32;
                        i13 = i9;
                        str59 = str77;
                        num16 = num6;
                        str65 = str35;
                        str64 = str22;
                        str57 = str21;
                        str66 = str24;
                        str67 = str25;
                        str73 = str31;
                        str72 = str30;
                        str71 = str29;
                        str70 = str28;
                        str69 = str27;
                        str68 = str26;
                        kSerializerArr2 = kSerializerArr;
                        break;
                    case 10:
                        kSerializerArr = kSerializerArr2;
                        i9 = i13;
                        str21 = str57;
                        num6 = num16;
                        str22 = str64;
                        str23 = str65;
                        str24 = str66;
                        str25 = str67;
                        str32 = str76;
                        str26 = str68;
                        str69 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 10, StringSerializer.INSTANCE, str69);
                        i15 |= 1024;
                        Unit unit12 = Unit.INSTANCE;
                        str27 = str69;
                        str28 = str70;
                        str29 = str71;
                        str30 = str72;
                        str31 = str73;
                        str35 = str23;
                        str76 = str32;
                        i13 = i9;
                        str59 = str77;
                        num16 = num6;
                        str65 = str35;
                        str64 = str22;
                        str57 = str21;
                        str66 = str24;
                        str67 = str25;
                        str73 = str31;
                        str72 = str30;
                        str71 = str29;
                        str70 = str28;
                        str69 = str27;
                        str68 = str26;
                        kSerializerArr2 = kSerializerArr;
                        break;
                    case 11:
                        kSerializerArr = kSerializerArr2;
                        i9 = i13;
                        str21 = str57;
                        num6 = num16;
                        str22 = str64;
                        str23 = str65;
                        str24 = str66;
                        str32 = str76;
                        str25 = str67;
                        str68 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 11, StringSerializer.INSTANCE, str68);
                        i15 |= 2048;
                        Unit unit13 = Unit.INSTANCE;
                        str26 = str68;
                        str27 = str69;
                        str28 = str70;
                        str29 = str71;
                        str30 = str72;
                        str31 = str73;
                        str35 = str23;
                        str76 = str32;
                        i13 = i9;
                        str59 = str77;
                        num16 = num6;
                        str65 = str35;
                        str64 = str22;
                        str57 = str21;
                        str66 = str24;
                        str67 = str25;
                        str73 = str31;
                        str72 = str30;
                        str71 = str29;
                        str70 = str28;
                        str69 = str27;
                        str68 = str26;
                        kSerializerArr2 = kSerializerArr;
                        break;
                    case 12:
                        kSerializerArr = kSerializerArr2;
                        i9 = i13;
                        str21 = str57;
                        num6 = num16;
                        str22 = str64;
                        str23 = str65;
                        str32 = str76;
                        str24 = str66;
                        str67 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 12, StringSerializer.INSTANCE, str67);
                        i15 |= 4096;
                        Unit unit14 = Unit.INSTANCE;
                        str25 = str67;
                        str26 = str68;
                        str27 = str69;
                        str28 = str70;
                        str29 = str71;
                        str30 = str72;
                        str31 = str73;
                        str35 = str23;
                        str76 = str32;
                        i13 = i9;
                        str59 = str77;
                        num16 = num6;
                        str65 = str35;
                        str64 = str22;
                        str57 = str21;
                        str66 = str24;
                        str67 = str25;
                        str73 = str31;
                        str72 = str30;
                        str71 = str29;
                        str70 = str28;
                        str69 = str27;
                        str68 = str26;
                        kSerializerArr2 = kSerializerArr;
                        break;
                    case 13:
                        kSerializerArr = kSerializerArr2;
                        i9 = i13;
                        num6 = num16;
                        str22 = str64;
                        str23 = str65;
                        str32 = str76;
                        str21 = str57;
                        str66 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 13, StringSerializer.INSTANCE, str66);
                        i15 |= 8192;
                        Unit unit15 = Unit.INSTANCE;
                        str24 = str66;
                        str25 = str67;
                        str26 = str68;
                        str27 = str69;
                        str28 = str70;
                        str29 = str71;
                        str30 = str72;
                        str31 = str73;
                        str35 = str23;
                        str76 = str32;
                        i13 = i9;
                        str59 = str77;
                        num16 = num6;
                        str65 = str35;
                        str64 = str22;
                        str57 = str21;
                        str66 = str24;
                        str67 = str25;
                        str73 = str31;
                        str72 = str30;
                        str71 = str29;
                        str70 = str28;
                        str69 = str27;
                        str68 = str26;
                        kSerializerArr2 = kSerializerArr;
                        break;
                    case 14:
                        kSerializerArr = kSerializerArr2;
                        i9 = i13;
                        num6 = num16;
                        str32 = str76;
                        str22 = str64;
                        str65 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 14, StringSerializer.INSTANCE, str65);
                        i15 |= 16384;
                        Unit unit16 = Unit.INSTANCE;
                        str21 = str57;
                        str23 = str65;
                        str24 = str66;
                        str25 = str67;
                        str26 = str68;
                        str27 = str69;
                        str28 = str70;
                        str29 = str71;
                        str30 = str72;
                        str31 = str73;
                        str35 = str23;
                        str76 = str32;
                        i13 = i9;
                        str59 = str77;
                        num16 = num6;
                        str65 = str35;
                        str64 = str22;
                        str57 = str21;
                        str66 = str24;
                        str67 = str25;
                        str73 = str31;
                        str72 = str30;
                        str71 = str29;
                        str70 = str28;
                        str69 = str27;
                        str68 = str26;
                        kSerializerArr2 = kSerializerArr;
                        break;
                    case 15:
                        kSerializerArr = kSerializerArr2;
                        i9 = i13;
                        num6 = num16;
                        str32 = str76;
                        zDecodeBooleanElement10 = compositeDecoderBeginStructure.decodeBooleanElement(serialDescriptor, 15);
                        int i16 = i15 | 32768;
                        Unit unit17 = Unit.INSTANCE;
                        str33 = str64;
                        i10 = i16;
                        iDecodeIntElement = i14;
                        String str78 = str33;
                        i15 = i10;
                        str34 = str78;
                        str22 = str34;
                        str21 = str57;
                        i14 = iDecodeIntElement;
                        str23 = str65;
                        str24 = str66;
                        str25 = str67;
                        str26 = str68;
                        str27 = str69;
                        str28 = str70;
                        str29 = str71;
                        str30 = str72;
                        str31 = str73;
                        str35 = str23;
                        str76 = str32;
                        i13 = i9;
                        str59 = str77;
                        num16 = num6;
                        str65 = str35;
                        str64 = str22;
                        str57 = str21;
                        str66 = str24;
                        str67 = str25;
                        str73 = str31;
                        str72 = str30;
                        str71 = str29;
                        str70 = str28;
                        str69 = str27;
                        str68 = str26;
                        kSerializerArr2 = kSerializerArr;
                        break;
                    case 16:
                        kSerializerArr = kSerializerArr2;
                        i9 = i13;
                        num6 = num16;
                        str34 = str64;
                        str32 = str76;
                        iDecodeIntElement = compositeDecoderBeginStructure.decodeIntElement(serialDescriptor, 16);
                        i15 |= 65536;
                        Unit unit18 = Unit.INSTANCE;
                        str22 = str34;
                        str21 = str57;
                        i14 = iDecodeIntElement;
                        str23 = str65;
                        str24 = str66;
                        str25 = str67;
                        str26 = str68;
                        str27 = str69;
                        str28 = str70;
                        str29 = str71;
                        str30 = str72;
                        str31 = str73;
                        str35 = str23;
                        str76 = str32;
                        i13 = i9;
                        str59 = str77;
                        num16 = num6;
                        str65 = str35;
                        str64 = str22;
                        str57 = str21;
                        str66 = str24;
                        str67 = str25;
                        str73 = str31;
                        str72 = str30;
                        str71 = str29;
                        str70 = str28;
                        str69 = str27;
                        str68 = str26;
                        kSerializerArr2 = kSerializerArr;
                        break;
                    case 17:
                        kSerializerArr = kSerializerArr2;
                        num6 = num16;
                        str32 = str76;
                        i9 = i13;
                        String str79 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 17, StringSerializer.INSTANCE, str64);
                        i10 = 131072 | i15;
                        Unit unit19 = Unit.INSTANCE;
                        str33 = str79;
                        iDecodeIntElement = i14;
                        String str782 = str33;
                        i15 = i10;
                        str34 = str782;
                        str22 = str34;
                        str21 = str57;
                        i14 = iDecodeIntElement;
                        str23 = str65;
                        str24 = str66;
                        str25 = str67;
                        str26 = str68;
                        str27 = str69;
                        str28 = str70;
                        str29 = str71;
                        str30 = str72;
                        str31 = str73;
                        str35 = str23;
                        str76 = str32;
                        i13 = i9;
                        str59 = str77;
                        num16 = num6;
                        str65 = str35;
                        str64 = str22;
                        str57 = str21;
                        str66 = str24;
                        str67 = str25;
                        str73 = str31;
                        str72 = str30;
                        str71 = str29;
                        str70 = str28;
                        str69 = str27;
                        str68 = str26;
                        kSerializerArr2 = kSerializerArr;
                        break;
                    case 18:
                        kSerializerArr = kSerializerArr2;
                        Integer num17 = num16;
                        String str80 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 18, StringSerializer.INSTANCE, str76);
                        i15 |= 262144;
                        Unit unit20 = Unit.INSTANCE;
                        str21 = str57;
                        str76 = str80;
                        str22 = str64;
                        str35 = str65;
                        str24 = str66;
                        str25 = str67;
                        str26 = str68;
                        str27 = str69;
                        str28 = str70;
                        str29 = str71;
                        str30 = str72;
                        str31 = str73;
                        str59 = str77;
                        num16 = num17;
                        str65 = str35;
                        str64 = str22;
                        str57 = str21;
                        str66 = str24;
                        str67 = str25;
                        str73 = str31;
                        str72 = str30;
                        str71 = str29;
                        str70 = str28;
                        str69 = str27;
                        str68 = str26;
                        kSerializerArr2 = kSerializerArr;
                        break;
                    case 19:
                        kSerializerArr = kSerializerArr2;
                        num7 = num16;
                        String str81 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 19, StringSerializer.INSTANCE, str60);
                        i15 |= 524288;
                        Unit unit21 = Unit.INSTANCE;
                        str60 = str81;
                        bool3 = bool7;
                        i12 = i;
                        str59 = str77;
                        num16 = num7;
                        str21 = str57;
                        i = i12;
                        str22 = str64;
                        str24 = str66;
                        str25 = str67;
                        str26 = str68;
                        str27 = str69;
                        str28 = str70;
                        str29 = str71;
                        str30 = str72;
                        str31 = str73;
                        bool7 = bool3;
                        str35 = str65;
                        str65 = str35;
                        str64 = str22;
                        str57 = str21;
                        str66 = str24;
                        str67 = str25;
                        str73 = str31;
                        str72 = str30;
                        str71 = str29;
                        str70 = str28;
                        str69 = str27;
                        str68 = str26;
                        kSerializerArr2 = kSerializerArr;
                        break;
                    case 20:
                        kSerializerArr = kSerializerArr2;
                        num7 = num16;
                        String str82 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 20, StringSerializer.INSTANCE, str61);
                        i15 |= 1048576;
                        Unit unit22 = Unit.INSTANCE;
                        str61 = str82;
                        bool3 = bool7;
                        i12 = i;
                        str59 = str77;
                        num16 = num7;
                        str21 = str57;
                        i = i12;
                        str22 = str64;
                        str24 = str66;
                        str25 = str67;
                        str26 = str68;
                        str27 = str69;
                        str28 = str70;
                        str29 = str71;
                        str30 = str72;
                        str31 = str73;
                        bool7 = bool3;
                        str35 = str65;
                        str65 = str35;
                        str64 = str22;
                        str57 = str21;
                        str66 = str24;
                        str67 = str25;
                        str73 = str31;
                        str72 = str30;
                        str71 = str29;
                        str70 = str28;
                        str69 = str27;
                        str68 = str26;
                        kSerializerArr2 = kSerializerArr;
                        break;
                    case 21:
                        kSerializerArr = kSerializerArr2;
                        num7 = num16;
                        str36 = str62;
                        zDecodeBooleanElement7 = compositeDecoderBeginStructure.decodeBooleanElement(serialDescriptor, 21);
                        i11 = 2097152;
                        i15 |= i11;
                        Unit unit23 = Unit.INSTANCE;
                        str62 = str36;
                        bool3 = bool7;
                        i12 = i;
                        str59 = str77;
                        num16 = num7;
                        str21 = str57;
                        i = i12;
                        str22 = str64;
                        str24 = str66;
                        str25 = str67;
                        str26 = str68;
                        str27 = str69;
                        str28 = str70;
                        str29 = str71;
                        str30 = str72;
                        str31 = str73;
                        bool7 = bool3;
                        str35 = str65;
                        str65 = str35;
                        str64 = str22;
                        str57 = str21;
                        str66 = str24;
                        str67 = str25;
                        str73 = str31;
                        str72 = str30;
                        str71 = str29;
                        str70 = str28;
                        str69 = str27;
                        str68 = str26;
                        kSerializerArr2 = kSerializerArr;
                        break;
                    case 22:
                        kSerializerArr = kSerializerArr2;
                        num7 = num16;
                        str36 = str62;
                        zDecodeBooleanElement6 = compositeDecoderBeginStructure.decodeBooleanElement(serialDescriptor, 22);
                        i11 = 4194304;
                        i15 |= i11;
                        Unit unit232 = Unit.INSTANCE;
                        str62 = str36;
                        bool3 = bool7;
                        i12 = i;
                        str59 = str77;
                        num16 = num7;
                        str21 = str57;
                        i = i12;
                        str22 = str64;
                        str24 = str66;
                        str25 = str67;
                        str26 = str68;
                        str27 = str69;
                        str28 = str70;
                        str29 = str71;
                        str30 = str72;
                        str31 = str73;
                        bool7 = bool3;
                        str35 = str65;
                        str65 = str35;
                        str64 = str22;
                        str57 = str21;
                        str66 = str24;
                        str67 = str25;
                        str73 = str31;
                        str72 = str30;
                        str71 = str29;
                        str70 = str28;
                        str69 = str27;
                        str68 = str26;
                        kSerializerArr2 = kSerializerArr;
                        break;
                    case 23:
                        kSerializerArr = kSerializerArr2;
                        num7 = num16;
                        str36 = str62;
                        iDecodeIntElement11 = compositeDecoderBeginStructure.decodeIntElement(serialDescriptor, 23);
                        i11 = 8388608;
                        i15 |= i11;
                        Unit unit2322 = Unit.INSTANCE;
                        str62 = str36;
                        bool3 = bool7;
                        i12 = i;
                        str59 = str77;
                        num16 = num7;
                        str21 = str57;
                        i = i12;
                        str22 = str64;
                        str24 = str66;
                        str25 = str67;
                        str26 = str68;
                        str27 = str69;
                        str28 = str70;
                        str29 = str71;
                        str30 = str72;
                        str31 = str73;
                        bool7 = bool3;
                        str35 = str65;
                        str65 = str35;
                        str64 = str22;
                        str57 = str21;
                        str66 = str24;
                        str67 = str25;
                        str73 = str31;
                        str72 = str30;
                        str71 = str29;
                        str70 = str28;
                        str69 = str27;
                        str68 = str26;
                        kSerializerArr2 = kSerializerArr;
                        break;
                    case 24:
                        kSerializerArr = kSerializerArr2;
                        num7 = num16;
                        str36 = str62;
                        iDecodeIntElement10 = compositeDecoderBeginStructure.decodeIntElement(serialDescriptor, 24);
                        i11 = 16777216;
                        i15 |= i11;
                        Unit unit23222 = Unit.INSTANCE;
                        str62 = str36;
                        bool3 = bool7;
                        i12 = i;
                        str59 = str77;
                        num16 = num7;
                        str21 = str57;
                        i = i12;
                        str22 = str64;
                        str24 = str66;
                        str25 = str67;
                        str26 = str68;
                        str27 = str69;
                        str28 = str70;
                        str29 = str71;
                        str30 = str72;
                        str31 = str73;
                        bool7 = bool3;
                        str35 = str65;
                        str65 = str35;
                        str64 = str22;
                        str57 = str21;
                        str66 = str24;
                        str67 = str25;
                        str73 = str31;
                        str72 = str30;
                        str71 = str29;
                        str70 = str28;
                        str69 = str27;
                        str68 = str26;
                        kSerializerArr2 = kSerializerArr;
                        break;
                    case 25:
                        kSerializerArr = kSerializerArr2;
                        num7 = num16;
                        str36 = str62;
                        int iDecodeIntElement12 = compositeDecoderBeginStructure.decodeIntElement(serialDescriptor, 25);
                        i11 = MediaHttpDownloader.MAXIMUM_CHUNK_SIZE;
                        i = iDecodeIntElement12;
                        i15 |= i11;
                        Unit unit232222 = Unit.INSTANCE;
                        str62 = str36;
                        bool3 = bool7;
                        i12 = i;
                        str59 = str77;
                        num16 = num7;
                        str21 = str57;
                        i = i12;
                        str22 = str64;
                        str24 = str66;
                        str25 = str67;
                        str26 = str68;
                        str27 = str69;
                        str28 = str70;
                        str29 = str71;
                        str30 = str72;
                        str31 = str73;
                        bool7 = bool3;
                        str35 = str65;
                        str65 = str35;
                        str64 = str22;
                        str57 = str21;
                        str66 = str24;
                        str67 = str25;
                        str73 = str31;
                        str72 = str30;
                        str71 = str29;
                        str70 = str28;
                        str69 = str27;
                        str68 = str26;
                        kSerializerArr2 = kSerializerArr;
                        break;
                    case 26:
                        kSerializerArr = kSerializerArr2;
                        num7 = num16;
                        str36 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 26, StringSerializer.INSTANCE, str62);
                        i15 |= 67108864;
                        Unit unit2322222 = Unit.INSTANCE;
                        str62 = str36;
                        bool3 = bool7;
                        i12 = i;
                        str59 = str77;
                        num16 = num7;
                        str21 = str57;
                        i = i12;
                        str22 = str64;
                        str24 = str66;
                        str25 = str67;
                        str26 = str68;
                        str27 = str69;
                        str28 = str70;
                        str29 = str71;
                        str30 = str72;
                        str31 = str73;
                        bool7 = bool3;
                        str35 = str65;
                        str65 = str35;
                        str64 = str22;
                        str57 = str21;
                        str66 = str24;
                        str67 = str25;
                        str73 = str31;
                        str72 = str30;
                        str71 = str29;
                        str70 = str28;
                        str69 = str27;
                        str68 = str26;
                        kSerializerArr2 = kSerializerArr;
                        break;
                    case 27:
                        kSerializerArr = kSerializerArr2;
                        num7 = num16;
                        String str83 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 27, StringSerializer.INSTANCE, str63);
                        i15 |= 134217728;
                        Unit unit24 = Unit.INSTANCE;
                        bool3 = bool7;
                        str63 = str83;
                        i12 = i;
                        str59 = str77;
                        num16 = num7;
                        str21 = str57;
                        i = i12;
                        str22 = str64;
                        str24 = str66;
                        str25 = str67;
                        str26 = str68;
                        str27 = str69;
                        str28 = str70;
                        str29 = str71;
                        str30 = str72;
                        str31 = str73;
                        bool7 = bool3;
                        str35 = str65;
                        str65 = str35;
                        str64 = str22;
                        str57 = str21;
                        str66 = str24;
                        str67 = str25;
                        str73 = str31;
                        str72 = str30;
                        str71 = str29;
                        str70 = str28;
                        str69 = str27;
                        str68 = str26;
                        kSerializerArr2 = kSerializerArr;
                        break;
                    case 28:
                        kSerializerArr = kSerializerArr2;
                        num7 = num16;
                        str74 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 28, StringSerializer.INSTANCE, str74);
                        i15 |= 268435456;
                        Unit unit25 = Unit.INSTANCE;
                        bool3 = bool7;
                        i12 = i;
                        str59 = str77;
                        num16 = num7;
                        str21 = str57;
                        i = i12;
                        str22 = str64;
                        str24 = str66;
                        str25 = str67;
                        str26 = str68;
                        str27 = str69;
                        str28 = str70;
                        str29 = str71;
                        str30 = str72;
                        str31 = str73;
                        bool7 = bool3;
                        str35 = str65;
                        str65 = str35;
                        str64 = str22;
                        str57 = str21;
                        str66 = str24;
                        str67 = str25;
                        str73 = str31;
                        str72 = str30;
                        str71 = str29;
                        str70 = str28;
                        str69 = str27;
                        str68 = str26;
                        kSerializerArr2 = kSerializerArr;
                        break;
                    case 29:
                        kSerializerArr = kSerializerArr2;
                        num7 = num16;
                        str59 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 29, StringSerializer.INSTANCE, str77);
                        i15 |= 536870912;
                        Unit unit26 = Unit.INSTANCE;
                        bool3 = bool7;
                        i12 = i;
                        num16 = num7;
                        str21 = str57;
                        i = i12;
                        str22 = str64;
                        str24 = str66;
                        str25 = str67;
                        str26 = str68;
                        str27 = str69;
                        str28 = str70;
                        str29 = str71;
                        str30 = str72;
                        str31 = str73;
                        bool7 = bool3;
                        str35 = str65;
                        str65 = str35;
                        str64 = str22;
                        str57 = str21;
                        str66 = str24;
                        str67 = str25;
                        str73 = str31;
                        str72 = str30;
                        str71 = str29;
                        str70 = str28;
                        str69 = str27;
                        str68 = str26;
                        kSerializerArr2 = kSerializerArr;
                        break;
                    case 30:
                        kSerializerArr = kSerializerArr2;
                        num16 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 30, IntSerializer.INSTANCE, num16);
                        i15 |= 1073741824;
                        Unit unit27 = Unit.INSTANCE;
                        bool3 = bool7;
                        i12 = i;
                        str59 = str77;
                        str21 = str57;
                        i = i12;
                        str22 = str64;
                        str24 = str66;
                        str25 = str67;
                        str26 = str68;
                        str27 = str69;
                        str28 = str70;
                        str29 = str71;
                        str30 = str72;
                        str31 = str73;
                        bool7 = bool3;
                        str35 = str65;
                        str65 = str35;
                        str64 = str22;
                        str57 = str21;
                        str66 = str24;
                        str67 = str25;
                        str73 = str31;
                        str72 = str30;
                        str71 = str29;
                        str70 = str28;
                        str69 = str27;
                        str68 = str26;
                        kSerializerArr2 = kSerializerArr;
                        break;
                    case 31:
                        num7 = num16;
                        num13 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 31, IntSerializer.INSTANCE, num13);
                        i15 |= Integer.MIN_VALUE;
                        Unit unit28 = Unit.INSTANCE;
                        kSerializerArr = kSerializerArr2;
                        bool3 = bool7;
                        i12 = i;
                        str59 = str77;
                        num16 = num7;
                        str21 = str57;
                        i = i12;
                        str22 = str64;
                        str24 = str66;
                        str25 = str67;
                        str26 = str68;
                        str27 = str69;
                        str28 = str70;
                        str29 = str71;
                        str30 = str72;
                        str31 = str73;
                        bool7 = bool3;
                        str35 = str65;
                        str65 = str35;
                        str64 = str22;
                        str57 = str21;
                        str66 = str24;
                        str67 = str25;
                        str73 = str31;
                        str72 = str30;
                        str71 = str29;
                        str70 = str28;
                        str69 = str27;
                        str68 = str26;
                        kSerializerArr2 = kSerializerArr;
                        break;
                    case 32:
                        num7 = num16;
                        str57 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 32, StringSerializer.INSTANCE, str57);
                        i13 |= 1;
                        Unit unit282 = Unit.INSTANCE;
                        kSerializerArr = kSerializerArr2;
                        bool3 = bool7;
                        i12 = i;
                        str59 = str77;
                        num16 = num7;
                        str21 = str57;
                        i = i12;
                        str22 = str64;
                        str24 = str66;
                        str25 = str67;
                        str26 = str68;
                        str27 = str69;
                        str28 = str70;
                        str29 = str71;
                        str30 = str72;
                        str31 = str73;
                        bool7 = bool3;
                        str35 = str65;
                        str65 = str35;
                        str64 = str22;
                        str57 = str21;
                        str66 = str24;
                        str67 = str25;
                        str73 = str31;
                        str72 = str30;
                        str71 = str29;
                        str70 = str28;
                        str69 = str27;
                        str68 = str26;
                        kSerializerArr2 = kSerializerArr;
                        break;
                    case 33:
                        num7 = num16;
                        num14 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 33, IntSerializer.INSTANCE, num14);
                        i13 |= 2;
                        Unit unit2822 = Unit.INSTANCE;
                        kSerializerArr = kSerializerArr2;
                        bool3 = bool7;
                        i12 = i;
                        str59 = str77;
                        num16 = num7;
                        str21 = str57;
                        i = i12;
                        str22 = str64;
                        str24 = str66;
                        str25 = str67;
                        str26 = str68;
                        str27 = str69;
                        str28 = str70;
                        str29 = str71;
                        str30 = str72;
                        str31 = str73;
                        bool7 = bool3;
                        str35 = str65;
                        str65 = str35;
                        str64 = str22;
                        str57 = str21;
                        str66 = str24;
                        str67 = str25;
                        str73 = str31;
                        str72 = str30;
                        str71 = str29;
                        str70 = str28;
                        str69 = str27;
                        str68 = str26;
                        kSerializerArr2 = kSerializerArr;
                        break;
                    case 34:
                        num7 = num16;
                        bool7 = (Boolean) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 34, BooleanSerializer.INSTANCE, bool7);
                        i13 |= 4;
                        Unit unit28222 = Unit.INSTANCE;
                        kSerializerArr = kSerializerArr2;
                        bool3 = bool7;
                        i12 = i;
                        str59 = str77;
                        num16 = num7;
                        str21 = str57;
                        i = i12;
                        str22 = str64;
                        str24 = str66;
                        str25 = str67;
                        str26 = str68;
                        str27 = str69;
                        str28 = str70;
                        str29 = str71;
                        str30 = str72;
                        str31 = str73;
                        bool7 = bool3;
                        str35 = str65;
                        str65 = str35;
                        str64 = str22;
                        str57 = str21;
                        str66 = str24;
                        str67 = str25;
                        str73 = str31;
                        str72 = str30;
                        str71 = str29;
                        str70 = str28;
                        str69 = str27;
                        str68 = str26;
                        kSerializerArr2 = kSerializerArr;
                        break;
                    case 35:
                        num7 = num16;
                        bool6 = (Boolean) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 35, BooleanSerializer.INSTANCE, bool6);
                        i13 |= 8;
                        Unit unit282222 = Unit.INSTANCE;
                        kSerializerArr = kSerializerArr2;
                        bool3 = bool7;
                        i12 = i;
                        str59 = str77;
                        num16 = num7;
                        str21 = str57;
                        i = i12;
                        str22 = str64;
                        str24 = str66;
                        str25 = str67;
                        str26 = str68;
                        str27 = str69;
                        str28 = str70;
                        str29 = str71;
                        str30 = str72;
                        str31 = str73;
                        bool7 = bool3;
                        str35 = str65;
                        str65 = str35;
                        str64 = str22;
                        str57 = str21;
                        str66 = str24;
                        str67 = str25;
                        str73 = str31;
                        str72 = str30;
                        str71 = str29;
                        str70 = str28;
                        str69 = str27;
                        str68 = str26;
                        kSerializerArr2 = kSerializerArr;
                        break;
                    case 36:
                        num7 = num16;
                        list3 = (List) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 36, kSerializerArr2[36], list3);
                        i13 |= 16;
                        Unit unit2822222 = Unit.INSTANCE;
                        kSerializerArr = kSerializerArr2;
                        bool3 = bool7;
                        i12 = i;
                        str59 = str77;
                        num16 = num7;
                        str21 = str57;
                        i = i12;
                        str22 = str64;
                        str24 = str66;
                        str25 = str67;
                        str26 = str68;
                        str27 = str69;
                        str28 = str70;
                        str29 = str71;
                        str30 = str72;
                        str31 = str73;
                        bool7 = bool3;
                        str35 = str65;
                        str65 = str35;
                        str64 = str22;
                        str57 = str21;
                        str66 = str24;
                        str67 = str25;
                        str73 = str31;
                        str72 = str30;
                        str71 = str29;
                        str70 = str28;
                        str69 = str27;
                        str68 = str26;
                        kSerializerArr2 = kSerializerArr;
                        break;
                    case 37:
                        num7 = num16;
                        str58 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 37, StringSerializer.INSTANCE, str58);
                        i13 |= 32;
                        Unit unit28222222 = Unit.INSTANCE;
                        kSerializerArr = kSerializerArr2;
                        bool3 = bool7;
                        i12 = i;
                        str59 = str77;
                        num16 = num7;
                        str21 = str57;
                        i = i12;
                        str22 = str64;
                        str24 = str66;
                        str25 = str67;
                        str26 = str68;
                        str27 = str69;
                        str28 = str70;
                        str29 = str71;
                        str30 = str72;
                        str31 = str73;
                        bool7 = bool3;
                        str35 = str65;
                        str65 = str35;
                        str64 = str22;
                        str57 = str21;
                        str66 = str24;
                        str67 = str25;
                        str73 = str31;
                        str72 = str30;
                        str71 = str29;
                        str70 = str28;
                        str69 = str27;
                        str68 = str26;
                        kSerializerArr2 = kSerializerArr;
                        break;
                    case 38:
                        num7 = num16;
                        num12 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 38, IntSerializer.INSTANCE, num12);
                        i13 |= 64;
                        Unit unit282222222 = Unit.INSTANCE;
                        kSerializerArr = kSerializerArr2;
                        bool3 = bool7;
                        i12 = i;
                        str59 = str77;
                        num16 = num7;
                        str21 = str57;
                        i = i12;
                        str22 = str64;
                        str24 = str66;
                        str25 = str67;
                        str26 = str68;
                        str27 = str69;
                        str28 = str70;
                        str29 = str71;
                        str30 = str72;
                        str31 = str73;
                        bool7 = bool3;
                        str35 = str65;
                        str65 = str35;
                        str64 = str22;
                        str57 = str21;
                        str66 = str24;
                        str67 = str25;
                        str73 = str31;
                        str72 = str30;
                        str71 = str29;
                        str70 = str28;
                        str69 = str27;
                        str68 = str26;
                        kSerializerArr2 = kSerializerArr;
                        break;
                    case 39:
                        num7 = num16;
                        num15 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 39, IntSerializer.INSTANCE, num15);
                        i13 |= 128;
                        Unit unit2822222222 = Unit.INSTANCE;
                        kSerializerArr = kSerializerArr2;
                        bool3 = bool7;
                        i12 = i;
                        str59 = str77;
                        num16 = num7;
                        str21 = str57;
                        i = i12;
                        str22 = str64;
                        str24 = str66;
                        str25 = str67;
                        str26 = str68;
                        str27 = str69;
                        str28 = str70;
                        str29 = str71;
                        str30 = str72;
                        str31 = str73;
                        bool7 = bool3;
                        str35 = str65;
                        str65 = str35;
                        str64 = str22;
                        str57 = str21;
                        str66 = str24;
                        str67 = str25;
                        str73 = str31;
                        str72 = str30;
                        str71 = str29;
                        str70 = str28;
                        str69 = str27;
                        str68 = str26;
                        kSerializerArr2 = kSerializerArr;
                        break;
                    default:
                        throw new UnknownFieldException(iDecodeElementIndex);
                }
            }
            String str84 = str59;
            String str85 = str64;
            String str86 = str65;
            String str87 = str66;
            String str88 = str67;
            String str89 = str68;
            String str90 = str69;
            String str91 = str70;
            String str92 = str71;
            String str93 = str72;
            String str94 = str73;
            str = str75;
            num = num12;
            num2 = num13;
            num3 = num14;
            bool = bool6;
            bool2 = bool7;
            list = list3;
            str2 = str58;
            num4 = num15;
            str3 = str76;
            i2 = i13;
            str4 = str57;
            str5 = str94;
            z = zDecodeBooleanElement7;
            str6 = str93;
            z2 = zDecodeBooleanElement10;
            str7 = str91;
            str8 = str90;
            str9 = str60;
            str10 = str61;
            str11 = str62;
            str12 = str63;
            str13 = str74;
            str14 = str84;
            num5 = num16;
            i3 = i15;
            str15 = str86;
            str16 = str85;
            str17 = str87;
            z3 = zDecodeBooleanElement6;
            z4 = zDecodeBooleanElement8;
            str18 = str92;
            str19 = str89;
            i4 = i14;
            j = jDecodeLongElement2;
            i5 = iDecodeIntElement10;
            i6 = iDecodeIntElement11;
            i7 = iDecodeIntElement8;
            i8 = iDecodeIntElement9;
            boolean z7 = zDecodeBooleanElement9;
            str20 = str88;
            z5 = z7;
        }
        compositeDecoderBeginStructure.endStructure(serialDescriptor);
        return new ChainData(i3, i2, str, str5, j, str6, str18, z5, i8, i7, z4, str7, str8, str19, str20, str17, str15, z2, i4, str16, str3, str9, str10, z, z3, i6, i5, i, str11, str12, str13, str14, num5, num2, str4, num3, bool2, bool, list, str2, num, num4, (SerializationConstructorMarker) null);
    }

    /* JADX DEBUG: Method merged with bridge method: serialize(Lkotlinx/serialization/encoding/Encoder;Ljava/lang/Object;)V */
    @Override // kotlinx.serialization.SerializationStrategy
    public final void serialize(@NotNull Encoder encoder, @NotNull ChainData chainData) {
        Intrinsics.checkNotNullParameter(encoder, "");
        Intrinsics.checkNotNullParameter(chainData, "");
        SerialDescriptor serialDescriptor = descriptor;
        CompositeEncoder compositeEncoderBeginStructure = encoder.beginStructure(serialDescriptor);
        ChainData.write$Self$OKAssets_assets_pro_api(chainData, compositeEncoderBeginStructure, serialDescriptor);
        compositeEncoderBeginStructure.endStructure(serialDescriptor);
    }
}
