package uniffi.user;

import com.sun.jna.Structure;
import kotlin.jvm.internal.DefaultConstructorMarker;
import kotlin.jvm.internal.Intrinsics;
import org.jetbrains.annotations.NotNull;
import uniffi.UniffiCallbackInterfaceClone;
import uniffi.UniffiCallbackInterfaceFree;

/* JADX INFO: loaded from: classes14.dex */
@Structure.FieldOrder({"uniffiFree", "uniffiClone", "getSiteCode", "setEntityId", "getEntityId", "getJsonSiteCode", "switchSiteCode", "isSwitchDomainSiteCode", "setSimulatedSiteCode", "getSimulatedSiteCode", "getRegion", "setRegion"})
public class UniffiVTableCallbackInterfaceCoreEntityManagerForeignHandling extends Structure {
    public static final int $stable = 8;
    public UniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod2 getEntityId;
    public UniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod3 getJsonSiteCode;
    public UniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod8 getRegion;
    public UniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod7 getSimulatedSiteCode;
    public UniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod0 getSiteCode;
    public UniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod5 isSwitchDomainSiteCode;
    public UniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod1 setEntityId;
    public UniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod9 setRegion;
    public UniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod6 setSimulatedSiteCode;
    public UniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod4 switchSiteCode;
    public UniffiCallbackInterfaceClone uniffiClone;
    public UniffiCallbackInterfaceFree uniffiFree;

    /* JADX DEBUG: Don't trust debug lines info. Lines numbers was adjusted: min line is 0 */
    public UniffiVTableCallbackInterfaceCoreEntityManagerForeignHandling() {
        this(null, null, null, null, null, null, null, null, null, null, null, null, 4095, null);
    }

    /* JADX DEBUG: Can't inline method, not implemented redirect type for insn: 0x0078: CONSTRUCTOR 
  (wrap:uniffi.UniffiCallbackInterfaceFree:?: TERNARY null = ((wrap:int:0x0002: ARITH (r26v0 int) & (1 int) A[WRAPPED]) != (0 int)) ? (null uniffi.UniffiCallbackInterfaceFree) : (r14v0 uniffi.UniffiCallbackInterfaceFree))
  (wrap:uniffi.UniffiCallbackInterfaceClone:?: TERNARY null = ((wrap:int:0x000a: ARITH (r26v0 int) & (2 int) A[WRAPPED]) != (0 int)) ? (null uniffi.UniffiCallbackInterfaceClone) : (r15v0 uniffi.UniffiCallbackInterfaceClone))
  (wrap:uniffi.user.UniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod0:?: TERNARY null = ((wrap:int:0x0011: ARITH (r26v0 int) & (4 int) A[WRAPPED]) != (0 int)) ? (null uniffi.user.UniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod0) : (r16v0 uniffi.user.UniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod0))
  (wrap:uniffi.user.UniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod1:?: TERNARY null = ((wrap:int:0x0019: ARITH (r26v0 int) & (8 int) A[WRAPPED]) != (0 int)) ? (null uniffi.user.UniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod1) : (r17v0 uniffi.user.UniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod1))
  (wrap:uniffi.user.UniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod2:?: TERNARY null = ((wrap:int:0x0021: ARITH (r26v0 int) & (16 int) A[WRAPPED]) != (0 int)) ? (null uniffi.user.UniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod2) : (r18v0 uniffi.user.UniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod2))
  (wrap:uniffi.user.UniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod3:?: TERNARY null = ((wrap:int:0x0029: ARITH (r26v0 int) & (32 int) A[WRAPPED]) != (0 int)) ? (null uniffi.user.UniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod3) : (r19v0 uniffi.user.UniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod3))
  (wrap:uniffi.user.UniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod4:?: TERNARY null = ((wrap:int:0x0031: ARITH (r26v0 int) & (64 int) A[WRAPPED]) != (0 int)) ? (null uniffi.user.UniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod4) : (r20v0 uniffi.user.UniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod4))
  (wrap:uniffi.user.UniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod5:?: TERNARY null = ((wrap:int:0x0039: ARITH (r26v0 int) & (128 int) A[WRAPPED]) != (0 int)) ? (null uniffi.user.UniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod5) : (r21v0 uniffi.user.UniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod5))
  (wrap:uniffi.user.UniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod6:?: TERNARY null = ((wrap:int:0x0041: ARITH (r26v0 int) & (256 int) A[WRAPPED]) != (0 int)) ? (null uniffi.user.UniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod6) : (r22v0 uniffi.user.UniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod6))
  (wrap:uniffi.user.UniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod7:?: TERNARY null = ((wrap:int:0x0049: ARITH (r26v0 int) & (512 int) A[WRAPPED]) != (0 int)) ? (null uniffi.user.UniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod7) : (r23v0 uniffi.user.UniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod7))
  (wrap:uniffi.user.UniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod8:?: TERNARY null = ((wrap:int:0x0051: ARITH (r26v0 int) & (1024 int) A[WRAPPED]) != (0 int)) ? (null uniffi.user.UniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod8) : (r24v0 uniffi.user.UniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod8))
  (wrap:uniffi.user.UniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod9:?: TERNARY null = ((wrap:int:0x0059: ARITH (r26v0 int) & (2048 int) A[WRAPPED]) == (0 int)) ? (r25v0 uniffi.user.UniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod9) : (null uniffi.user.UniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod9))
 A[MD:(uniffi.UniffiCallbackInterfaceFree, uniffi.UniffiCallbackInterfaceClone, uniffi.user.UniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod0, uniffi.user.UniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod1, uniffi.user.UniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod2, uniffi.user.UniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod3, uniffi.user.UniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod4, uniffi.user.UniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod5, uniffi.user.UniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod6, uniffi.user.UniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod7, uniffi.user.UniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod8, uniffi.user.UniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod9):void (m)] (LINE:229) call: uniffi.user.UniffiVTableCallbackInterfaceCoreEntityManagerForeignHandling.<init>(uniffi.UniffiCallbackInterfaceFree, uniffi.UniffiCallbackInterfaceClone, uniffi.user.UniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod0, uniffi.user.UniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod1, uniffi.user.UniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod2, uniffi.user.UniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod3, uniffi.user.UniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod4, uniffi.user.UniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod5, uniffi.user.UniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod6, uniffi.user.UniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod7, uniffi.user.UniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod8, uniffi.user.UniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod9):void type: THIS */
    public /* synthetic */ UniffiVTableCallbackInterfaceCoreEntityManagerForeignHandling(UniffiCallbackInterfaceFree uniffiCallbackInterfaceFree, UniffiCallbackInterfaceClone uniffiCallbackInterfaceClone, UniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod0 uniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod0, UniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod1 uniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod1, UniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod2 uniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod2, UniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod3 uniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod3, UniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod4 uniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod4, UniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod5 uniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod5, UniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod6 uniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod6, UniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod7 uniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod7, UniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod8 uniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod8, UniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod9 uniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod9, int i, DefaultConstructorMarker defaultConstructorMarker) {
        this((i & 1) != 0 ? null : uniffiCallbackInterfaceFree, (i & 2) != 0 ? null : uniffiCallbackInterfaceClone, (i & 4) != 0 ? null : uniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod0, (i & 8) != 0 ? null : uniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod1, (i & 16) != 0 ? null : uniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod2, (i & 32) != 0 ? null : uniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod3, (i & 64) != 0 ? null : uniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod4, (i & 128) != 0 ? null : uniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod5, (i & 256) != 0 ? null : uniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod6, (i & 512) != 0 ? null : uniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod7, (i & 1024) != 0 ? null : uniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod8, (i & 2048) == 0 ? uniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod9 : null);
    }

    public static final class UniffiByValue extends UniffiVTableCallbackInterfaceCoreEntityManagerForeignHandling implements Structure.ByValue {
        public static final int $stable = 0;

        /* JADX DEBUG: Don't trust debug lines info. Lines numbers was adjusted: min line is 0 */
        public UniffiByValue() {
            this(null, null, null, null, null, null, null, null, null, null, null, null, 4095, null);
        }

        /* JADX DEBUG: Can't inline method, not implemented redirect type for insn: 0x0078: CONSTRUCTOR 
  (wrap:uniffi.UniffiCallbackInterfaceFree:?: TERNARY null = ((wrap:int:0x0002: ARITH (r26v0 int) & (1 int) A[WRAPPED]) != (0 int)) ? (null uniffi.UniffiCallbackInterfaceFree) : (r14v0 uniffi.UniffiCallbackInterfaceFree))
  (wrap:uniffi.UniffiCallbackInterfaceClone:?: TERNARY null = ((wrap:int:0x000a: ARITH (r26v0 int) & (2 int) A[WRAPPED]) != (0 int)) ? (null uniffi.UniffiCallbackInterfaceClone) : (r15v0 uniffi.UniffiCallbackInterfaceClone))
  (wrap:uniffi.user.UniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod0:?: TERNARY null = ((wrap:int:0x0011: ARITH (r26v0 int) & (4 int) A[WRAPPED]) != (0 int)) ? (null uniffi.user.UniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod0) : (r16v0 uniffi.user.UniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod0))
  (wrap:uniffi.user.UniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod1:?: TERNARY null = ((wrap:int:0x0019: ARITH (r26v0 int) & (8 int) A[WRAPPED]) != (0 int)) ? (null uniffi.user.UniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod1) : (r17v0 uniffi.user.UniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod1))
  (wrap:uniffi.user.UniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod2:?: TERNARY null = ((wrap:int:0x0021: ARITH (r26v0 int) & (16 int) A[WRAPPED]) != (0 int)) ? (null uniffi.user.UniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod2) : (r18v0 uniffi.user.UniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod2))
  (wrap:uniffi.user.UniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod3:?: TERNARY null = ((wrap:int:0x0029: ARITH (r26v0 int) & (32 int) A[WRAPPED]) != (0 int)) ? (null uniffi.user.UniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod3) : (r19v0 uniffi.user.UniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod3))
  (wrap:uniffi.user.UniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod4:?: TERNARY null = ((wrap:int:0x0031: ARITH (r26v0 int) & (64 int) A[WRAPPED]) != (0 int)) ? (null uniffi.user.UniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod4) : (r20v0 uniffi.user.UniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod4))
  (wrap:uniffi.user.UniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod5:?: TERNARY null = ((wrap:int:0x0039: ARITH (r26v0 int) & (128 int) A[WRAPPED]) != (0 int)) ? (null uniffi.user.UniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod5) : (r21v0 uniffi.user.UniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod5))
  (wrap:uniffi.user.UniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod6:?: TERNARY null = ((wrap:int:0x0041: ARITH (r26v0 int) & (256 int) A[WRAPPED]) != (0 int)) ? (null uniffi.user.UniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod6) : (r22v0 uniffi.user.UniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod6))
  (wrap:uniffi.user.UniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod7:?: TERNARY null = ((wrap:int:0x0049: ARITH (r26v0 int) & (512 int) A[WRAPPED]) != (0 int)) ? (null uniffi.user.UniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod7) : (r23v0 uniffi.user.UniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod7))
  (wrap:uniffi.user.UniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod8:?: TERNARY null = ((wrap:int:0x0051: ARITH (r26v0 int) & (1024 int) A[WRAPPED]) != (0 int)) ? (null uniffi.user.UniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod8) : (r24v0 uniffi.user.UniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod8))
  (wrap:uniffi.user.UniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod9:?: TERNARY null = ((wrap:int:0x0059: ARITH (r26v0 int) & (2048 int) A[WRAPPED]) == (0 int)) ? (r25v0 uniffi.user.UniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod9) : (null uniffi.user.UniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod9))
 A[MD:(uniffi.UniffiCallbackInterfaceFree, uniffi.UniffiCallbackInterfaceClone, uniffi.user.UniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod0, uniffi.user.UniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod1, uniffi.user.UniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod2, uniffi.user.UniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod3, uniffi.user.UniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod4, uniffi.user.UniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod5, uniffi.user.UniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod6, uniffi.user.UniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod7, uniffi.user.UniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod8, uniffi.user.UniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod9):void (m)] (LINE:243) call: uniffi.user.UniffiVTableCallbackInterfaceCoreEntityManagerForeignHandling.UniffiByValue.<init>(uniffi.UniffiCallbackInterfaceFree, uniffi.UniffiCallbackInterfaceClone, uniffi.user.UniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod0, uniffi.user.UniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod1, uniffi.user.UniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod2, uniffi.user.UniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod3, uniffi.user.UniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod4, uniffi.user.UniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod5, uniffi.user.UniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod6, uniffi.user.UniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod7, uniffi.user.UniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod8, uniffi.user.UniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod9):void type: THIS */
        public /* synthetic */ UniffiByValue(UniffiCallbackInterfaceFree uniffiCallbackInterfaceFree, UniffiCallbackInterfaceClone uniffiCallbackInterfaceClone, UniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod0 uniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod0, UniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod1 uniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod1, UniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod2 uniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod2, UniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod3 uniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod3, UniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod4 uniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod4, UniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod5 uniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod5, UniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod6 uniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod6, UniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod7 uniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod7, UniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod8 uniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod8, UniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod9 uniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod9, int i, DefaultConstructorMarker defaultConstructorMarker) {
            this((i & 1) != 0 ? null : uniffiCallbackInterfaceFree, (i & 2) != 0 ? null : uniffiCallbackInterfaceClone, (i & 4) != 0 ? null : uniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod0, (i & 8) != 0 ? null : uniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod1, (i & 16) != 0 ? null : uniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod2, (i & 32) != 0 ? null : uniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod3, (i & 64) != 0 ? null : uniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod4, (i & 128) != 0 ? null : uniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod5, (i & 256) != 0 ? null : uniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod6, (i & 512) != 0 ? null : uniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod7, (i & 1024) != 0 ? null : uniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod8, (i & 2048) == 0 ? uniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod9 : null);
        }

        public UniffiByValue(UniffiCallbackInterfaceFree uniffiCallbackInterfaceFree, UniffiCallbackInterfaceClone uniffiCallbackInterfaceClone, UniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod0 uniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod0, UniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod1 uniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod1, UniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod2 uniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod2, UniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod3 uniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod3, UniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod4 uniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod4, UniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod5 uniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod5, UniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod6 uniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod6, UniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod7 uniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod7, UniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod8 uniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod8, UniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod9 uniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod9) {
            super(uniffiCallbackInterfaceFree, uniffiCallbackInterfaceClone, uniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod0, uniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod1, uniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod2, uniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod3, uniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod4, uniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod5, uniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod6, uniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod7, uniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod8, uniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod9);
        }
    }

    public UniffiVTableCallbackInterfaceCoreEntityManagerForeignHandling(UniffiCallbackInterfaceFree uniffiCallbackInterfaceFree, UniffiCallbackInterfaceClone uniffiCallbackInterfaceClone, UniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod0 uniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod0, UniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod1 uniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod1, UniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod2 uniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod2, UniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod3 uniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod3, UniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod4 uniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod4, UniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod5 uniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod5, UniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod6 uniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod6, UniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod7 uniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod7, UniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod8 uniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod8, UniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod9 uniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod9) {
        this.uniffiFree = uniffiCallbackInterfaceFree;
        this.uniffiClone = uniffiCallbackInterfaceClone;
        this.getSiteCode = uniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod0;
        this.setEntityId = uniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod1;
        this.getEntityId = uniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod2;
        this.getJsonSiteCode = uniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod3;
        this.switchSiteCode = uniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod4;
        this.isSwitchDomainSiteCode = uniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod5;
        this.setSimulatedSiteCode = uniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod6;
        this.getSimulatedSiteCode = uniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod7;
        this.getRegion = uniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod8;
        this.setRegion = uniffiCallbackInterfaceCoreEntityManagerForeignHandlingMethod9;
    }

    public final void uniffiSetValue$OKCore_deploy(@NotNull UniffiVTableCallbackInterfaceCoreEntityManagerForeignHandling uniffiVTableCallbackInterfaceCoreEntityManagerForeignHandling) {
        Intrinsics.checkNotNullParameter(uniffiVTableCallbackInterfaceCoreEntityManagerForeignHandling, "");
        this.uniffiFree = uniffiVTableCallbackInterfaceCoreEntityManagerForeignHandling.uniffiFree;
        this.uniffiClone = uniffiVTableCallbackInterfaceCoreEntityManagerForeignHandling.uniffiClone;
        this.getSiteCode = uniffiVTableCallbackInterfaceCoreEntityManagerForeignHandling.getSiteCode;
        this.setEntityId = uniffiVTableCallbackInterfaceCoreEntityManagerForeignHandling.setEntityId;
        this.getEntityId = uniffiVTableCallbackInterfaceCoreEntityManagerForeignHandling.getEntityId;
        this.getJsonSiteCode = uniffiVTableCallbackInterfaceCoreEntityManagerForeignHandling.getJsonSiteCode;
        this.switchSiteCode = uniffiVTableCallbackInterfaceCoreEntityManagerForeignHandling.switchSiteCode;
        this.isSwitchDomainSiteCode = uniffiVTableCallbackInterfaceCoreEntityManagerForeignHandling.isSwitchDomainSiteCode;
        this.setSimulatedSiteCode = uniffiVTableCallbackInterfaceCoreEntityManagerForeignHandling.setSimulatedSiteCode;
        this.getSimulatedSiteCode = uniffiVTableCallbackInterfaceCoreEntityManagerForeignHandling.getSimulatedSiteCode;
        this.getRegion = uniffiVTableCallbackInterfaceCoreEntityManagerForeignHandling.getRegion;
        this.setRegion = uniffiVTableCallbackInterfaceCoreEntityManagerForeignHandling.setRegion;
    }
}
