package o;

import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.databinding.ViewDataBinding;
import com.okinc.buysell.ui.transaction.buysell.view.UnifiedOrderDetailBodyTwoStepInfoView;

/* JADX INFO: renamed from: o.lxh, reason: case insensitive filesystem */
/* JADX INFO: loaded from: classes7.dex */
public abstract class AbstractC31606lxh extends ViewDataBinding {
    public final ConstraintLayout AEQbTJ;
    public final ConstraintLayout AYXKKw;
    public final android.widget.LinearLayout AhwBna;
    public final android.widget.ImageView AkhnZx;
    public final ConstraintLayout AuCTel;
    public final ConstraintLayout AuCTelauCTel;
    public final ConstraintLayout AubY;
    public final android.widget.LinearLayout AwvSrB;
    public final android.widget.TextView AxsJAY;
    public final android.widget.TextView AxsJAYaxsJAY;
    public final android.widget.TextView AxsJAYsNCnLh;
    public final UnifiedOrderDetailBodyTwoStepInfoView DAIeex;
    public final android.widget.ImageView DTwDnp;
    public final android.view.View DarRvM;
    public final android.widget.ImageView DbNXlk;
    public final android.widget.LinearLayout EZpvd;
    public final android.widget.LinearLayout KWHzl;
    public final android.view.View ODWQjV;
    public final ConstraintLayout OLrzqt;
    public final android.widget.ImageView ORxRYg;
    public final android.widget.ImageView OcIXYQ;
    public final android.view.View OqFWZa;
    public final android.widget.TextView QKVWgx;
    public final android.widget.TextView QKudOq;
    public final android.widget.TextView QOLQEE;
    public final android.widget.TextView QUSxYX;
    public final android.widget.TextView QVAiDq;
    public final android.widget.TextView QbewEr;
    public final android.widget.TextView QfsBiF;
    public final android.widget.TextView RJOkX;
    public final android.widget.TextView RcXXUw;
    public final android.widget.TextView RlQdEF;
    public final android.widget.TextView UeEOUB;
    public final android.widget.TextView aKErDB;
    public final android.widget.TextView accept;
    public final android.widget.LinearLayout copydefault;
    public final android.widget.TextView dNCPSb;
    public final android.widget.LinearLayout djBIcL;
    public final android.widget.TextView djSkpj;
    public final android.widget.TextView dvKsVJ;
    public final android.widget.TextView dxcTrN;
    public final ConstraintLayout ejfBZ;
    public final ConstraintLayout fARcdN;
    public final android.widget.TextView fFgQHt;
    public final AbstractC31607lxi fIwbmz;
    public final ConstraintLayout fJNWhG;
    public final android.widget.TextView fZBcTu;
    public final android.widget.ImageView fetchVPNInfo;
    public final android.widget.TextView finit;
    public final android.widget.TextView flVtFt;
    public final android.widget.TextView fvQaOB;
    public final android.widget.ImageView gEmmrt;
    public final android.widget.TextView gGvvIC;
    public final ConstraintLayout gHZMYf;
    public final android.widget.TextView gasjUx;
    public final ConstraintLayout getFieldNames;
    public final ConstraintLayout getNewProxyInstance;
    public final android.widget.TextView giSNqX;
    public final android.widget.TextView gkJEwt;
    public final ConstraintLayout hDKMBd;
    public final android.widget.TextView hUfVAv;
    public final C57635ymD iRxXKY;
    public final android.widget.TextView iZzfmt;
    public final android.widget.ImageView isConnected;
    public final ConstraintLayout iwGUEr;
    public final ConstraintLayout sSMYrx;
    public final ConstraintLayout uzCIH;
    public final android.widget.ImageView valueOf;
    public final ConstraintLayout values;
    public final ConstraintLayout wlaJM;
    public final ConstraintLayout zLjUOn;
    public final ConstraintLayout zsXlph;
    public final android.widget.ImageView zuBGHE;

    public AbstractC31606lxh(java.lang.Object obj, android.view.View view, int i, ConstraintLayout constraintLayout, ConstraintLayout constraintLayout2, android.widget.LinearLayout linearLayout, android.widget.LinearLayout linearLayout2, android.widget.LinearLayout linearLayout3, android.widget.LinearLayout linearLayout4, ConstraintLayout constraintLayout3, android.widget.ImageView imageView, android.widget.ImageView imageView2, android.widget.LinearLayout linearLayout5, ConstraintLayout constraintLayout4, android.widget.ImageView imageView3, android.widget.ImageView imageView4, android.widget.ImageView imageView5, android.widget.ImageView imageView6, ConstraintLayout constraintLayout5, ConstraintLayout constraintLayout6, ConstraintLayout constraintLayout7, ConstraintLayout constraintLayout8, AbstractC31607lxi abstractC31607lxi, ConstraintLayout constraintLayout9, ConstraintLayout constraintLayout10, ConstraintLayout constraintLayout11, ConstraintLayout constraintLayout12, ConstraintLayout constraintLayout13, ConstraintLayout constraintLayout14, ConstraintLayout constraintLayout15, ConstraintLayout constraintLayout16, ConstraintLayout constraintLayout17, ConstraintLayout constraintLayout18, ConstraintLayout constraintLayout19, android.widget.LinearLayout linearLayout6, android.widget.TextView textView, android.widget.ImageView imageView7, ConstraintLayout constraintLayout20, android.widget.TextView textView2, android.widget.TextView textView3, android.widget.ImageView imageView8, android.widget.ImageView imageView9, android.widget.ImageView imageView10, android.widget.TextView textView4, android.widget.TextView textView5, android.widget.TextView textView6, android.widget.TextView textView7, android.widget.TextView textView8, android.widget.TextView textView9, android.widget.TextView textView10, android.widget.TextView textView11, android.widget.TextView textView12, android.widget.TextView textView13, android.widget.TextView textView14, android.widget.TextView textView15, android.widget.TextView textView16, android.widget.TextView textView17, android.widget.TextView textView18, android.widget.TextView textView19, android.widget.TextView textView20, android.widget.TextView textView21, android.widget.TextView textView22, android.widget.TextView textView23, android.widget.TextView textView24, android.widget.TextView textView25, android.widget.TextView textView26, C57635ymD c57635ymD, android.widget.TextView textView27, android.widget.TextView textView28, android.widget.TextView textView29, android.widget.TextView textView30, android.widget.TextView textView31, UnifiedOrderDetailBodyTwoStepInfoView unifiedOrderDetailBodyTwoStepInfoView, android.view.View view2, android.view.View view3, android.view.View view4) {
        super(obj, view, i);
        this.OLrzqt = constraintLayout;
        this.AEQbTJ = constraintLayout2;
        this.copydefault = linearLayout;
        this.EZpvd = linearLayout2;
        this.KWHzl = linearLayout3;
        this.AhwBna = linearLayout4;
        this.AYXKKw = constraintLayout3;
        this.valueOf = imageView;
        this.gEmmrt = imageView2;
        this.djBIcL = linearLayout5;
        this.values = constraintLayout4;
        this.DbNXlk = imageView3;
        this.fetchVPNInfo = imageView4;
        this.isConnected = imageView5;
        this.AkhnZx = imageView6;
        this.ejfBZ = constraintLayout5;
        this.AuCTel = constraintLayout6;
        this.fARcdN = constraintLayout7;
        this.fJNWhG = constraintLayout8;
        this.fIwbmz = abstractC31607lxi;
        this.uzCIH = constraintLayout9;
        this.getFieldNames = constraintLayout10;
        this.getNewProxyInstance = constraintLayout11;
        this.iwGUEr = constraintLayout12;
        this.hDKMBd = constraintLayout13;
        this.AuCTelauCTel = constraintLayout14;
        this.wlaJM = constraintLayout15;
        this.zsXlph = constraintLayout16;
        this.AubY = constraintLayout17;
        this.zLjUOn = constraintLayout18;
        this.gHZMYf = constraintLayout19;
        this.AwvSrB = linearLayout6;
        this.AxsJAY = textView;
        this.zuBGHE = imageView7;
        this.sSMYrx = constraintLayout20;
        this.QKVWgx = textView2;
        this.QOLQEE = textView3;
        this.DTwDnp = imageView8;
        this.OcIXYQ = imageView9;
        this.ORxRYg = imageView10;
        this.QUSxYX = textView4;
        this.QfsBiF = textView5;
        this.RJOkX = textView6;
        this.QVAiDq = textView7;
        this.QbewEr = textView8;
        this.djSkpj = textView9;
        this.RcXXUw = textView10;
        this.aKErDB = textView11;
        this.dNCPSb = textView12;
        this.UeEOUB = textView13;
        this.fFgQHt = textView14;
        this.fZBcTu = textView15;
        this.dxcTrN = textView16;
        this.dvKsVJ = textView17;
        this.finit = textView18;
        this.giSNqX = textView19;
        this.fvQaOB = textView20;
        this.flVtFt = textView21;
        this.gasjUx = textView22;
        this.gGvvIC = textView23;
        this.AxsJAYaxsJAY = textView24;
        this.gkJEwt = textView25;
        this.hUfVAv = textView26;
        this.iRxXKY = c57635ymD;
        this.iZzfmt = textView27;
        this.QKudOq = textView28;
        this.accept = textView29;
        this.AxsJAYsNCnLh = textView30;
        this.RlQdEF = textView31;
        this.DAIeex = unifiedOrderDetailBodyTwoStepInfoView;
        this.ODWQjV = view2;
        this.DarRvM = view3;
        this.OqFWZa = view4;
    }
}
