package o;

import com.okinc.business.defi.biz.core.error.WalletImportError;
import com.okinc.unify_trade.biz.ArbitrageTotalPnlInfo;
import com.okinc.unify_trade.biz.DcaTriggerParam;
import com.okinc.unify_trade.biz.EntrySignalOrderAmtParam;
import com.okinc.unify_trade.biz.ExitSignalOrderAmtParam;
import com.okinc.unify_trade.biz.ExtendedBusinessInfo;
import com.okinc.unify_trade.biz.FundingFeeApyItem;
import com.okinc.unify_trade.biz.RecurringListItem;
import com.okinc.unify_trade.biz.SignParamItem;
import com.okinc.unify_trade.biz.SmartArbListItem;
import com.okinc.unify_trade.biz.SmartPortfolioListItem;
import com.okinc.unify_trade.biz.StrategyDetailsResponse;
import com.okinc.unify_trade.biz.StrategyProfitResponse;
import com.okinc.unify_trade.biz.TacticsVoucherInfo;
import com.okinc.unify_trade.biz.TrailingConfig;
import com.okinc.unify_trade.biz.bot.SmartEarnParam;
import com.okinc.unify_trade.biz.bot.TpSlTriggerParamReqResp;
import com.okinc.unify_trade.biz.subscribe.StrategyHistoryListResp;
import com.okinc.unify_trade.biz.subscribe.StrategyPendingListResp;
import com.okinc.unify_trade.biz.subscribe.StrategyPendingListRespExt;
import com.okinc.unify_trade.bot.constant.SubArbitrageType4Remote;
import kotlin.collections.CollectionsKt___CollectionsKt;
import kotlin.jvm.internal.DefaultConstructorMarker;
import kotlin.jvm.internal.Intrinsics;
import kotlin.text.StringsKt__StringsKt;
import org.jetbrains.annotations.NotNull;

/* JADX INFO: renamed from: o.xsW, reason: case insensitive filesystem */
/* JADX INFO: loaded from: classes19.dex */
public final class C55891xsW {
    public static final C55891xsW AEQbTJ = new C55891xsW();

    private C55891xsW() {
    }

    public final StrategyPendingListResp KWHzl(@NotNull StrategyDetailsResponse strategyDetailsResponse) {
        java.lang.Boolean boolZLjUOn;
        Intrinsics.checkNotNullParameter(strategyDetailsResponse, "");
        java.lang.String instType = strategyDetailsResponse.getInstType();
        java.lang.String instId = strategyDetailsResponse.getInstId();
        java.lang.String ccy = strategyDetailsResponse.getCcy();
        java.lang.String ordId = strategyDetailsResponse.getOrdId();
        java.lang.String algoId = strategyDetailsResponse.getAlgoId();
        java.lang.String ordType = strategyDetailsResponse.getOrdType();
        java.lang.String tdMode = strategyDetailsResponse.getTdMode();
        java.lang.String lever = strategyDetailsResponse.getLever();
        java.lang.String state = strategyDetailsResponse.getState();
        java.lang.String triggerTime = strategyDetailsResponse.getTriggerTime();
        java.lang.String cTime = strategyDetailsResponse.getCTime();
        java.lang.String pxVar = strategyDetailsResponse.getPxVar();
        java.lang.String pxSpread = strategyDetailsResponse.getPxSpread();
        java.lang.String szLimit = strategyDetailsResponse.getSzLimit();
        java.lang.String pxLimit = strategyDetailsResponse.getPxLimit();
        java.lang.String actualSz = strategyDetailsResponse.getActualSz();
        java.lang.String totalCycleProfit = strategyDetailsResponse.getTotalCycleProfit();
        java.lang.String arbitragePnl = strategyDetailsResponse.getArbitragePnl();
        java.lang.String arbitrageProfitRate = strategyDetailsResponse.getArbitrageProfitRate();
        java.lang.String str = arbitrageProfitRate == null ? "" : arbitrageProfitRate;
        java.lang.String totalCycleProfitRate = strategyDetailsResponse.getTotalCycleProfitRate();
        java.lang.String sz = strategyDetailsResponse.getSz();
        java.lang.String side = strategyDetailsResponse.getSide();
        java.lang.String posSide = strategyDetailsResponse.getPosSide();
        java.lang.String timeInterval = strategyDetailsResponse.getTimeInterval();
        java.lang.String maxPx = strategyDetailsResponse.getMaxPx();
        java.lang.String minPx = strategyDetailsResponse.getMinPx();
        java.lang.String gridNum = strategyDetailsResponse.getGridNum();
        java.lang.String runType = strategyDetailsResponse.getRunType();
        java.lang.String runPx = strategyDetailsResponse.getRunPx();
        java.lang.String quoteSz = strategyDetailsResponse.getQuoteSz();
        java.lang.String baseSz = strategyDetailsResponse.getBaseSz();
        java.lang.String tpRatio = strategyDetailsResponse.getTpRatio();
        java.lang.String slRatio = strategyDetailsResponse.getSlRatio();
        java.lang.String tradeNum = strategyDetailsResponse.getTradeNum();
        java.lang.String totalPnl = strategyDetailsResponse.getTotalPnl();
        java.lang.String pnlRatio = strategyDetailsResponse.getPnlRatio();
        java.lang.String arbApy = strategyDetailsResponse.getArbApy();
        java.lang.String investment = strategyDetailsResponse.getInvestment();
        java.lang.String cancelType = strategyDetailsResponse.getCancelType();
        java.lang.String stopResult = strategyDetailsResponse.getStopResult();
        java.lang.String profitNum = strategyDetailsResponse.getProfitNum();
        java.lang.String avgDailyArbitrageNum = strategyDetailsResponse.getAvgDailyArbitrageNum();
        java.lang.String arbitrageNum = strategyDetailsResponse.getArbitrageNum();
        java.lang.String uTime = strategyDetailsResponse.getUTime();
        java.lang.String direction = strategyDetailsResponse.getDirection();
        boolean basePos = strategyDetailsResponse.getBasePos();
        java.lang.String actualLever = strategyDetailsResponse.getActualLever();
        java.lang.String actualMarginSz = strategyDetailsResponse.getActualMarginSz();
        java.lang.String extraMarginSz = strategyDetailsResponse.getExtraMarginSz();
        java.lang.String availEq = strategyDetailsResponse.getAvailEq();
        java.lang.String liqPx = strategyDetailsResponse.getLiqPx();
        java.lang.String floatProfit = strategyDetailsResponse.getFloatProfit();
        java.lang.String floatProfitInSourceCcy = strategyDetailsResponse.getFloatProfitInSourceCcy();
        java.lang.String floatProfitRate = strategyDetailsResponse.getFloatProfitRate();
        java.lang.String arbitrageApy = strategyDetailsResponse.getArbitrageApy();
        java.lang.String eq = strategyDetailsResponse.getEq();
        java.lang.String gridProfit = strategyDetailsResponse.getGridProfit();
        java.lang.String gridProfitInSourceCcy = strategyDetailsResponse.getGridProfitInSourceCcy();
        java.lang.String gridProfitRate = strategyDetailsResponse.getGridProfitRate();
        java.lang.String algoOrdType = strategyDetailsResponse.getAlgoOrdType();
        java.lang.String stgyName = strategyDetailsResponse.getStgyName();
        java.lang.String amt = strategyDetailsResponse.getAmt();
        java.util.ArrayList<RecurringListItem> recurringList = strategyDetailsResponse.getRecurringList();
        java.lang.String period = strategyDetailsResponse.getPeriod();
        java.lang.String recurringDay = strategyDetailsResponse.getRecurringDay();
        java.lang.String nextInvestTime = strategyDetailsResponse.getNextInvestTime();
        java.lang.String str2 = nextInvestTime == null ? "" : nextInvestTime;
        java.lang.String recurringHour = strategyDetailsResponse.getRecurringHour();
        java.lang.String investCcy = strategyDetailsResponse.getInvestCcy();
        java.lang.String recurringTime = strategyDetailsResponse.getRecurringTime();
        java.lang.String cycles = strategyDetailsResponse.getCycles();
        java.lang.String investAmt = strategyDetailsResponse.getInvestAmt();
        java.lang.String duration = strategyDetailsResponse.getDuration();
        java.lang.String investType = strategyDetailsResponse.getInvestType();
        java.util.ArrayList<SmartPortfolioListItem> portfolioList = strategyDetailsResponse.getPortfolioList();
        java.lang.String balType = strategyDetailsResponse.getBalType();
        java.lang.String deltaRatio = strategyDetailsResponse.getDeltaRatio();
        java.lang.String interval = strategyDetailsResponse.getInterval();
        java.lang.String balNum = strategyDetailsResponse.getBalNum();
        java.lang.String maxSafetyOrds = strategyDetailsResponse.getMaxSafetyOrds();
        java.lang.String fillSafetyOrds = strategyDetailsResponse.getFillSafetyOrds();
        java.lang.String avgPx = strategyDetailsResponse.getAvgPx();
        java.lang.String tpPx = strategyDetailsResponse.getTpPx();
        java.lang.String slPx = strategyDetailsResponse.getSlPx();
        java.lang.String slMode = strategyDetailsResponse.getSlMode();
        java.lang.String completedCycles = strategyDetailsResponse.getCompletedCycles();
        java.lang.String pxSteps = strategyDetailsResponse.getPxSteps();
        java.lang.String pxStepsMult = strategyDetailsResponse.getPxStepsMult();
        java.lang.String volMult = strategyDetailsResponse.getVolMult();
        java.lang.String tpPct = strategyDetailsResponse.getTpPct();
        java.lang.String slPct = strategyDetailsResponse.getSlPct();
        java.lang.String investmentCcy = strategyDetailsResponse.getInvestmentCcy();
        java.lang.String investmentAmt = strategyDetailsResponse.getInvestmentAmt();
        java.lang.String maxBotUsage = strategyDetailsResponse.getMaxBotUsage();
        java.util.ArrayList<SignParamItem> signParams = strategyDetailsResponse.getSignParams();
        java.lang.String profit = strategyDetailsResponse.getProfit();
        java.util.List<DcaTriggerParam> triggerParams = strategyDetailsResponse.getTriggerParams();
        java.lang.String sourceAlgoId = strategyDetailsResponse.getSourceAlgoId();
        java.lang.String stopType = strategyDetailsResponse.getStopType();
        java.lang.String initPx = strategyDetailsResponse.getInitPx();
        java.lang.String perGridProfitRatio = strategyDetailsResponse.getPerGridProfitRatio();
        java.lang.String tpPriceRange = strategyDetailsResponse.getTpPriceRange();
        boolean reserveFunds = strategyDetailsResponse.getReserveFunds();
        TrailingConfig trailingUpConfig = strategyDetailsResponse.getTrailingUpConfig();
        TrailingConfig trailingDownConfig = strategyDetailsResponse.getTrailingDownConfig();
        java.lang.String trailingDownFund = strategyDetailsResponse.getTrailingDownFund();
        java.lang.String gridStatus = strategyDetailsResponse.getGridStatus();
        java.lang.String lmtOrderNumber = strategyDetailsResponse.getLmtOrderNumber();
        java.lang.String aggressiveness = strategyDetailsResponse.getAggressiveness();
        java.lang.String profitSharingRatio = strategyDetailsResponse.getProfitSharingRatio();
        java.lang.String copyType = strategyDetailsResponse.getCopyType();
        java.lang.String mktCap = strategyDetailsResponse.getMktCap();
        java.util.List<java.lang.String> instIds = strategyDetailsResponse.getInstIds();
        java.util.ArrayList arrayList = instIds != null ? new java.util.ArrayList(instIds) : null;
        java.lang.String totalAmt = strategyDetailsResponse.getTotalAmt();
        java.lang.String signalChanId = strategyDetailsResponse.getSignalChanId();
        java.lang.String signalChanName = strategyDetailsResponse.getSignalChanName();
        java.lang.String floatingPnl = strategyDetailsResponse.getFloatingPnl();
        java.lang.String availableMargin = strategyDetailsResponse.getAvailableMargin();
        java.lang.String totalPnlRatio = strategyDetailsResponse.getTotalPnlRatio();
        java.lang.String signalCount = strategyDetailsResponse.getSignalCount();
        java.lang.String reduce_only = strategyDetailsResponse.getReduce_only();
        java.lang.String symbolsNumber = strategyDetailsResponse.getSymbolsNumber();
        java.lang.String sourceCcy = strategyDetailsResponse.getSourceCcy();
        java.lang.String sourceCcySz = strategyDetailsResponse.getSourceCcySz();
        boolean outOfRange = strategyDetailsResponse.getOutOfRange();
        boolean autoMarginReloadSwitch = strategyDetailsResponse.getAutoMarginReloadSwitch();
        java.lang.String autoMarginReloadMaxAmount = strategyDetailsResponse.getAutoMarginReloadMaxAmount();
        ExtendedBusinessInfo extendedBusinessInfo = strategyDetailsResponse.getExtendedBusinessInfo();
        java.lang.String arbPnl = strategyDetailsResponse.getArbPnl();
        java.lang.String instFamily = strategyDetailsResponse.getInstFamily();
        java.lang.String fundingFeeRatio = strategyDetailsResponse.getFundingFeeRatio();
        java.lang.String fundingFeeTime = strategyDetailsResponse.getFundingFeeTime();
        java.util.ArrayList<SmartArbListItem> arbList = strategyDetailsResponse.getArbList();
        java.lang.String perMinProfitRate = strategyDetailsResponse.getPerMinProfitRate();
        java.lang.String perMaxProfitRate = strategyDetailsResponse.getPerMaxProfitRate();
        java.lang.String curQuoteSz = strategyDetailsResponse.getCurQuoteSz();
        java.lang.String curBaseSz = strategyDetailsResponse.getCurBaseSz();
        java.lang.String pnlRatioInSourceCcy = strategyDetailsResponse.getPnlRatioInSourceCcy();
        java.lang.String totalPnlInSourceCcy = strategyDetailsResponse.getTotalPnlInSourceCcy();
        java.lang.Boolean boolIsTradeBorrowMode = strategyDetailsResponse.isTradeBorrowMode();
        java.lang.String lastPrice = strategyDetailsResponse.getLastPrice();
        java.lang.String str3 = lastPrice == null ? "" : lastPrice;
        java.util.List<java.lang.Integer> strategyTags = strategyDetailsResponse.getStrategyTags();
        java.lang.String maturedApy = strategyDetailsResponse.getMaturedApy();
        EntrySignalOrderAmtParam signalOrderAmtParam = strategyDetailsResponse.getSignalOrderAmtParam();
        ExitSignalOrderAmtParam signalBotOrderStopParam = strategyDetailsResponse.getSignalBotOrderStopParam();
        TacticsVoucherInfo voucherInfo = strategyDetailsResponse.getVoucherInfo();
        java.util.ArrayList<java.lang.String> forbidden = strategyDetailsResponse.getForbidden();
        java.util.ArrayList<java.lang.String> hiddenFeatures = strategyDetailsResponse.getHiddenFeatures();
        java.lang.String dcdState = strategyDetailsResponse.getDcdState();
        java.lang.String str4 = dcdState == null ? "" : dcdState;
        java.lang.String notional = strategyDetailsResponse.getNotional();
        java.lang.String str5 = notional == null ? "" : notional;
        java.lang.String notionalCcy = strategyDetailsResponse.getNotionalCcy();
        java.lang.String str6 = notionalCcy == null ? "" : notionalCcy;
        java.lang.String cycle = strategyDetailsResponse.getCycle();
        java.lang.String str7 = cycle == null ? "" : cycle;
        java.lang.String currencyBal = strategyDetailsResponse.getCurrencyBal();
        java.lang.String str8 = currencyBal == null ? "" : currencyBal;
        java.lang.String alternateCurrency = strategyDetailsResponse.getAlternateCurrency();
        java.lang.String str9 = alternateCurrency == null ? "" : alternateCurrency;
        java.lang.String avgCost = strategyDetailsResponse.getAvgCost();
        java.lang.String str10 = avgCost == null ? "" : avgCost;
        java.lang.String coinPnl = strategyDetailsResponse.getCoinPnl();
        java.lang.String str11 = coinPnl == null ? "" : coinPnl;
        java.lang.String curStrike = strategyDetailsResponse.getCurStrike();
        java.lang.String reinvestment = strategyDetailsResponse.getReinvestment();
        boolean zBooleanValue = (reinvestment == null || (boolZLjUOn = StringsKt__StringsKt.zLjUOn(reinvestment)) == null) ? true : boolZLjUOn.booleanValue();
        java.lang.String settlementCcy = strategyDetailsResponse.getSettlementCcy();
        java.lang.String pTime = strategyDetailsResponse.getPTime();
        java.lang.String lastTradeExpireTime = strategyDetailsResponse.getLastTradeExpireTime();
        java.lang.String lastSettlementSettledTime = strategyDetailsResponse.getLastSettlementSettledTime();
        java.util.List<SubArbitrageType4Remote> subArbTypes = strategyDetailsResponse.getSubArbTypes();
        java.lang.String absYieldPercentage = strategyDetailsResponse.getAbsYieldPercentage();
        java.lang.String tradeQuoteCcy = strategyDetailsResponse.getTradeQuoteCcy();
        java.lang.String displayId = strategyDetailsResponse.getDisplayId();
        SmartEarnParam simpleEarn = strategyDetailsResponse.getSimpleEarn();
        java.lang.Float leveragePrincipal = strategyDetailsResponse.getLeveragePrincipal();
        ArbitrageTotalPnlInfo arbitrageTotalPnlInfo = strategyDetailsResponse.getArbitrageTotalPnlInfo();
        java.lang.String highestApyPeriod = strategyDetailsResponse.getHighestApyPeriod();
        boolean displayMinPaybackDays = strategyDetailsResponse.getDisplayMinPaybackDays();
        java.util.List<FundingFeeApyItem> fundingFeeApyList = strategyDetailsResponse.getFundingFeeApyList();
        java.util.List<StrategyProfitResponse> profitSnapshots = strategyDetailsResponse.getProfitSnapshots();
        StrategyPendingListResp strategyPendingListResp = new StrategyPendingListResp(instType, instId, ccy, ordId, algoId, ordType, tdMode, lever, state, triggerTime, cTime, pxVar, pxSpread, szLimit, pxLimit, actualSz, totalCycleProfit, arbitragePnl, str, totalCycleProfitRate, sz, side, posSide, timeInterval, maxPx, minPx, gridNum, runType, runPx, quoteSz, baseSz, tpRatio, slRatio, "", "", tradeNum, totalPnl, pnlRatio, arbApy, investment, cancelType, null, null, stopResult, profitNum, avgDailyArbitrageNum, arbitrageNum, null, null, null, null, null, null, null, uTime, direction, basePos, null, actualLever, actualMarginSz, extraMarginSz, availEq, liqPx, floatProfit, floatProfitInSourceCcy, floatProfitRate, arbitrageApy, eq, gridProfit, gridProfitInSourceCcy, gridProfitRate, algoOrdType, null, null, stgyName, amt, recurringList, period, recurringDay, str2, recurringHour, investCcy, recurringTime, cycles, investAmt, duration, investType, portfolioList, balType, deltaRatio, interval, balNum, null, null, null, null, maxSafetyOrds, fillSafetyOrds, avgPx, tpPx, slPx, slMode, completedCycles, pxSteps, pxStepsMult, volMult, tpPct, slPct, investmentCcy, investmentAmt, maxBotUsage, null, signParams, profit, triggerParams, sourceAlgoId, stopType, initPx, perGridProfitRatio, tpPriceRange, java.lang.Boolean.valueOf(reserveFunds), trailingUpConfig, trailingDownConfig, trailingDownFund, gridStatus, lmtOrderNumber, aggressiveness, profitSharingRatio, copyType, mktCap, arrayList, totalAmt, signalChanId, signalChanName, floatingPnl, availableMargin, totalPnlRatio, signalCount, null, reduce_only, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, false, null, null, null, null, null, null, null, false, false, symbolsNumber, sourceCcy, sourceCcySz, outOfRange, autoMarginReloadSwitch, autoMarginReloadMaxAmount, extendedBusinessInfo, arbPnl, instFamily, fundingFeeRatio, fundingFeeTime, arbList, null, perMinProfitRate, perMaxProfitRate, curQuoteSz, curBaseSz, pnlRatioInSourceCcy, totalPnlInSourceCcy, null, boolIsTradeBorrowMode, str3, null, null, strategyTags, maturedApy, signalOrderAmtParam, signalBotOrderStopParam, voucherInfo, forbidden, hiddenFeatures, str4, null, null, str5, str6, str7, str8, str9, str10, str11, curStrike, zBooleanValue, settlementCcy, pTime, lastTradeExpireTime, lastSettlementSettledTime, null, subArbTypes, absYieldPercentage, tradeQuoteCcy, displayId, simpleEarn, leveragePrincipal, arbitrageTotalPnlInfo, 0, highestApyPeriod, displayMinPaybackDays, fundingFeeApyList, profitSnapshots != null ? CollectionsKt___CollectionsKt.fJNWhG((java.util.Collection) profitSnapshots) : null, strategyDetailsResponse.getLatestProfit(), strategyDetailsResponse.getTotalSpreadProfit(), strategyDetailsResponse.getTotalApy(), strategyDetailsResponse.getFee(), strategyDetailsResponse.getTotalInterestAmt(), strategyDetailsResponse.getDebtCcy(), strategyDetailsResponse.getArbitrageProfit(), strategyDetailsResponse.getStakingProfit(), strategyDetailsResponse.getInitOrdAmt(), strategyDetailsResponse.getSafetyOrdAmt(), strategyDetailsResponse.getEffectiveEditParametersDetails(), strategyDetailsResponse.getBalanceDetails(), strategyDetailsResponse.getBot(), null, null, null, 0, 37717504, -268434688, 32768, -3072, 1678246015, 1077936512, 458752, null);
        strategyPendingListResp.setExt(new StrategyPendingListRespExt(strategyDetailsResponse.getTpslTriggerParamResp(), strategyDetailsResponse.getTpTriggerPx(), strategyDetailsResponse.getSlTriggerPx()));
        return strategyPendingListResp;
    }

    public final StrategyHistoryListResp EZpvd(@NotNull StrategyDetailsResponse strategyDetailsResponse) {
        java.lang.Boolean boolZLjUOn;
        Intrinsics.checkNotNullParameter(strategyDetailsResponse, "");
        java.lang.String instType = strategyDetailsResponse.getInstType();
        java.lang.String instId = strategyDetailsResponse.getInstId();
        java.lang.String uly = strategyDetailsResponse.getUly();
        java.lang.String ccy = strategyDetailsResponse.getCcy();
        java.lang.String ctVal = strategyDetailsResponse.getCtVal();
        java.lang.String ordId = strategyDetailsResponse.getOrdId();
        java.lang.String algoId = strategyDetailsResponse.getAlgoId();
        java.lang.String ordType = strategyDetailsResponse.getOrdType();
        java.lang.String tdMode = strategyDetailsResponse.getTdMode();
        java.lang.String lever = strategyDetailsResponse.getLever();
        java.lang.String state = strategyDetailsResponse.getState();
        java.lang.String triggerTime = strategyDetailsResponse.getTriggerTime();
        java.lang.String cTime = strategyDetailsResponse.getCTime();
        java.lang.String pxVar = strategyDetailsResponse.getPxVar();
        java.lang.String pxSpread = strategyDetailsResponse.getPxSpread();
        java.lang.String szLimit = strategyDetailsResponse.getSzLimit();
        java.lang.String pxLimit = strategyDetailsResponse.getPxLimit();
        java.lang.String actualSz = strategyDetailsResponse.getActualSz();
        java.lang.String sz = strategyDetailsResponse.getSz();
        java.lang.String side = strategyDetailsResponse.getSide();
        java.lang.String posSide = strategyDetailsResponse.getPosSide();
        java.lang.String timeInterval = strategyDetailsResponse.getTimeInterval();
        java.lang.String maxPx = strategyDetailsResponse.getMaxPx();
        java.lang.String minPx = strategyDetailsResponse.getMinPx();
        java.lang.String gridNum = strategyDetailsResponse.getGridNum();
        java.lang.String runType = strategyDetailsResponse.getRunType();
        java.lang.String runPx = strategyDetailsResponse.getRunPx();
        java.lang.String quoteSz = strategyDetailsResponse.getQuoteSz();
        java.lang.String baseSz = strategyDetailsResponse.getBaseSz();
        TpSlTriggerParamReqResp tpslTriggerParamResp = strategyDetailsResponse.getTpslTriggerParamResp();
        java.lang.String tpTriggerPx = strategyDetailsResponse.getTpTriggerPx();
        java.lang.String slTriggerPx = strategyDetailsResponse.getSlTriggerPx();
        java.lang.String tpRatio = strategyDetailsResponse.getTpRatio();
        java.lang.String slRatio = strategyDetailsResponse.getSlRatio();
        java.lang.String tradeNum = strategyDetailsResponse.getTradeNum();
        java.lang.String totalPnl = strategyDetailsResponse.getTotalPnl();
        java.lang.String pnlRatio = strategyDetailsResponse.getPnlRatio();
        java.lang.String arbApy = strategyDetailsResponse.getArbApy();
        java.lang.String arbitrageApy = strategyDetailsResponse.getArbitrageApy();
        java.lang.String gridProfitRate = strategyDetailsResponse.getGridProfitRate();
        java.lang.String investment = strategyDetailsResponse.getInvestment();
        java.lang.String cancelType = strategyDetailsResponse.getCancelType();
        java.lang.String stopResult = strategyDetailsResponse.getStopResult();
        java.lang.String profitNum = strategyDetailsResponse.getProfitNum();
        java.lang.String avgDailyArbitrageNum = strategyDetailsResponse.getAvgDailyArbitrageNum();
        java.lang.String totalCycleProfit = strategyDetailsResponse.getTotalCycleProfit();
        java.lang.String arbitragePnl = strategyDetailsResponse.getArbitragePnl();
        java.lang.String totalCycleProfitRate = strategyDetailsResponse.getTotalCycleProfitRate();
        java.lang.String arbitrageNum = strategyDetailsResponse.getArbitrageNum();
        java.lang.String uTime = strategyDetailsResponse.getUTime();
        java.lang.String direction = strategyDetailsResponse.getDirection();
        boolean basePos = strategyDetailsResponse.getBasePos();
        java.lang.String actualLever = strategyDetailsResponse.getActualLever();
        java.lang.String actualMarginSz = strategyDetailsResponse.getActualMarginSz();
        java.lang.String extraMarginSz = strategyDetailsResponse.getExtraMarginSz();
        java.lang.String liqPx = strategyDetailsResponse.getLiqPx();
        java.lang.String floatProfit = strategyDetailsResponse.getFloatProfit();
        java.lang.String floatProfitInSourceCcy = strategyDetailsResponse.getFloatProfitInSourceCcy();
        java.lang.String eq = strategyDetailsResponse.getEq();
        java.lang.String gridProfit = strategyDetailsResponse.getGridProfit();
        java.lang.String gridProfitInSourceCcy = strategyDetailsResponse.getGridProfitInSourceCcy();
        java.lang.String algoOrdType = strategyDetailsResponse.getAlgoOrdType();
        java.lang.String stgyName = strategyDetailsResponse.getStgyName();
        java.lang.String amt = strategyDetailsResponse.getAmt();
        java.util.ArrayList<RecurringListItem> recurringList = strategyDetailsResponse.getRecurringList();
        java.lang.String period = strategyDetailsResponse.getPeriod();
        java.lang.String recurringDay = strategyDetailsResponse.getRecurringDay();
        java.lang.String recurringHour = strategyDetailsResponse.getRecurringHour();
        java.lang.String cycles = strategyDetailsResponse.getCycles();
        java.lang.String investCcy = strategyDetailsResponse.getInvestCcy();
        java.lang.String recurringTime = strategyDetailsResponse.getRecurringTime();
        java.lang.String investAmt = strategyDetailsResponse.getInvestAmt();
        java.lang.String duration = strategyDetailsResponse.getDuration();
        java.lang.String investType = strategyDetailsResponse.getInvestType();
        java.util.ArrayList<SmartPortfolioListItem> portfolioList = strategyDetailsResponse.getPortfolioList();
        java.lang.String balType = strategyDetailsResponse.getBalType();
        java.lang.String deltaRatio = strategyDetailsResponse.getDeltaRatio();
        java.lang.String interval = strategyDetailsResponse.getInterval();
        java.lang.String balNum = strategyDetailsResponse.getBalNum();
        java.lang.String maxSafetyOrds = strategyDetailsResponse.getMaxSafetyOrds();
        java.lang.String fillSafetyOrds = strategyDetailsResponse.getFillSafetyOrds();
        java.lang.String pxSteps = strategyDetailsResponse.getPxSteps();
        java.lang.String pxStepsMult = strategyDetailsResponse.getPxStepsMult();
        java.lang.String volMult = strategyDetailsResponse.getVolMult();
        java.lang.String tpPct = strategyDetailsResponse.getTpPct();
        java.lang.String slPct = strategyDetailsResponse.getSlPct();
        java.lang.String avgPx = strategyDetailsResponse.getAvgPx();
        java.lang.String tpPx = strategyDetailsResponse.getTpPx();
        java.lang.String slPx = strategyDetailsResponse.getSlPx();
        java.lang.String slMode = strategyDetailsResponse.getSlMode();
        java.lang.String completedCycles = strategyDetailsResponse.getCompletedCycles();
        java.lang.String investmentCcy = strategyDetailsResponse.getInvestmentCcy();
        java.lang.String investmentAmt = strategyDetailsResponse.getInvestmentAmt();
        java.lang.String maxBotUsage = strategyDetailsResponse.getMaxBotUsage();
        java.util.ArrayList<SignParamItem> signParams = strategyDetailsResponse.getSignParams();
        java.lang.String profit = strategyDetailsResponse.getProfit();
        java.util.List<DcaTriggerParam> triggerParams = strategyDetailsResponse.getTriggerParams();
        java.lang.String sourceAlgoId = strategyDetailsResponse.getSourceAlgoId();
        java.lang.String stopType = strategyDetailsResponse.getStopType();
        java.lang.String initPx = strategyDetailsResponse.getInitPx();
        java.lang.String perGridProfitRatio = strategyDetailsResponse.getPerGridProfitRatio();
        java.lang.String perMinProfitRate = strategyDetailsResponse.getPerMinProfitRate();
        java.lang.String perMaxProfitRate = strategyDetailsResponse.getPerMaxProfitRate();
        boolean reserveFunds = strategyDetailsResponse.getReserveFunds();
        TrailingConfig trailingUpConfig = strategyDetailsResponse.getTrailingUpConfig();
        TrailingConfig trailingDownConfig = strategyDetailsResponse.getTrailingDownConfig();
        java.lang.String trailingDownFund = strategyDetailsResponse.getTrailingDownFund();
        java.lang.String gridStatus = strategyDetailsResponse.getGridStatus();
        java.lang.String lmtOrderNumber = strategyDetailsResponse.getLmtOrderNumber();
        java.lang.String aggressiveness = strategyDetailsResponse.getAggressiveness();
        java.lang.String profitSharingRatio = strategyDetailsResponse.getProfitSharingRatio();
        java.lang.String arbitrageProfitRate = strategyDetailsResponse.getArbitrageProfitRate();
        java.lang.String str = arbitrageProfitRate == null ? "" : arbitrageProfitRate;
        java.lang.String copyType = strategyDetailsResponse.getCopyType();
        java.util.List<java.lang.String> instIds = strategyDetailsResponse.getInstIds();
        java.util.ArrayList arrayList = instIds != null ? new java.util.ArrayList(instIds) : null;
        java.lang.String totalAmt = strategyDetailsResponse.getTotalAmt();
        java.lang.String signalChanId = strategyDetailsResponse.getSignalChanId();
        java.lang.String signalChanName = strategyDetailsResponse.getSignalChanName();
        java.lang.String floatingPnl = strategyDetailsResponse.getFloatingPnl();
        java.lang.String availableMargin = strategyDetailsResponse.getAvailableMargin();
        java.lang.String totalPnlRatio = strategyDetailsResponse.getTotalPnlRatio();
        java.lang.String signalCount = strategyDetailsResponse.getSignalCount();
        java.lang.String reduce_only = strategyDetailsResponse.getReduce_only();
        java.util.ArrayList<java.lang.String> hiddenFeatures = strategyDetailsResponse.getHiddenFeatures();
        java.lang.String sourceCcy = strategyDetailsResponse.getSourceCcy();
        java.lang.String sourceCcySz = strategyDetailsResponse.getSourceCcySz();
        ExtendedBusinessInfo extendedBusinessInfo = strategyDetailsResponse.getExtendedBusinessInfo();
        java.lang.String arbPnl = strategyDetailsResponse.getArbPnl();
        java.lang.String instFamily = strategyDetailsResponse.getInstFamily();
        java.util.ArrayList<SmartArbListItem> arbList = strategyDetailsResponse.getArbList();
        java.lang.String pnlRatioInSourceCcy = strategyDetailsResponse.getPnlRatioInSourceCcy();
        java.lang.String totalPnlInSourceCcy = strategyDetailsResponse.getTotalPnlInSourceCcy();
        java.lang.String ruleType = strategyDetailsResponse.getRuleType();
        java.lang.String str2 = ruleType == null ? "" : ruleType;
        TacticsVoucherInfo voucherInfo = strategyDetailsResponse.getVoucherInfo();
        java.lang.String dcdState = strategyDetailsResponse.getDcdState();
        java.lang.String str3 = dcdState == null ? "" : dcdState;
        java.lang.String notional = strategyDetailsResponse.getNotional();
        java.lang.String str4 = notional == null ? "" : notional;
        java.lang.String notionalCcy = strategyDetailsResponse.getNotionalCcy();
        java.lang.String str5 = notionalCcy == null ? "" : notionalCcy;
        java.lang.String cycle = strategyDetailsResponse.getCycle();
        java.lang.String str6 = cycle == null ? "" : cycle;
        java.lang.String currencyBal = strategyDetailsResponse.getCurrencyBal();
        java.lang.String str7 = currencyBal == null ? "" : currencyBal;
        java.lang.String alternateCurrency = strategyDetailsResponse.getAlternateCurrency();
        java.lang.String str8 = alternateCurrency == null ? "" : alternateCurrency;
        java.lang.String avgCost = strategyDetailsResponse.getAvgCost();
        java.lang.String str9 = avgCost == null ? "" : avgCost;
        java.lang.String coinPnl = strategyDetailsResponse.getCoinPnl();
        java.lang.String str10 = coinPnl == null ? "" : coinPnl;
        java.lang.String reinvestment = strategyDetailsResponse.getReinvestment();
        boolean zBooleanValue = (reinvestment == null || (boolZLjUOn = StringsKt__StringsKt.zLjUOn(reinvestment)) == null) ? true : boolZLjUOn.booleanValue();
        java.lang.String lastPrice = strategyDetailsResponse.getLastPrice();
        java.lang.String str11 = lastPrice == null ? "" : lastPrice;
        java.lang.String settlementCcy = strategyDetailsResponse.getSettlementCcy();
        java.lang.String str12 = settlementCcy == null ? "" : settlementCcy;
        java.lang.String lastTradeExpireTime = strategyDetailsResponse.getLastTradeExpireTime();
        java.lang.String lastSettlementSettledTime = strategyDetailsResponse.getLastSettlementSettledTime();
        StrategyProfitResponse latestProfit = strategyDetailsResponse.getLatestProfit();
        java.util.List<StrategyProfitResponse> profitSnapshots = strategyDetailsResponse.getProfitSnapshots();
        return new StrategyHistoryListResp(instType, instId, uly, ccy, ctVal, ordId, algoId, ordType, tdMode, lever, state, triggerTime, cTime, pxVar, pxSpread, szLimit, pxLimit, actualSz, sz, side, posSide, timeInterval, maxPx, minPx, gridNum, runType, runPx, quoteSz, baseSz, tpslTriggerParamResp, tpTriggerPx, slTriggerPx, tpRatio, slRatio, "", "", tradeNum, totalPnl, pnlRatio, arbApy, arbitrageApy, gridProfitRate, investment, cancelType, stopResult, profitNum, avgDailyArbitrageNum, totalCycleProfit, arbitragePnl, totalCycleProfitRate, arbitrageNum, (java.lang.String) null, (java.lang.String) null, (java.lang.String) null, (java.lang.String) null, (java.lang.String) null, (java.lang.String) null, (java.lang.String) null, uTime, direction, basePos, (java.lang.String) null, actualLever, actualMarginSz, extraMarginSz, liqPx, floatProfit, floatProfitInSourceCcy, eq, gridProfit, gridProfitInSourceCcy, algoOrdType, (java.util.List) null, (java.lang.Boolean) null, (java.lang.String) null, stgyName, amt, (java.util.ArrayList) recurringList, period, recurringDay, recurringHour, cycles, investCcy, recurringTime, investAmt, duration, investType, (java.util.ArrayList) portfolioList, balType, deltaRatio, interval, balNum, (java.lang.String) null, maxSafetyOrds, fillSafetyOrds, pxSteps, pxStepsMult, volMult, tpPct, slPct, avgPx, tpPx, slPx, slMode, completedCycles, investmentCcy, investmentAmt, maxBotUsage, (java.lang.String) null, (java.lang.String) null, (java.util.ArrayList) signParams, profit, (java.util.List) triggerParams, (java.lang.String) null, (java.lang.String) null, (java.lang.String) null, sourceAlgoId, stopType, initPx, perGridProfitRatio, perMinProfitRate, perMaxProfitRate, java.lang.Boolean.valueOf(reserveFunds), trailingUpConfig, trailingDownConfig, trailingDownFund, gridStatus, lmtOrderNumber, aggressiveness, (java.lang.String) null, (java.lang.String) null, profitSharingRatio, str, copyType, arrayList, totalAmt, signalChanId, signalChanName, floatingPnl, availableMargin, totalPnlRatio, signalCount, reduce_only, (java.lang.String) null, (java.util.ArrayList) hiddenFeatures, (java.lang.String) null, (java.lang.String) null, (java.lang.String) null, (java.lang.String) null, (java.lang.String) null, (java.lang.String) null, (java.lang.String) null, (java.lang.String) null, (java.lang.String) null, (java.lang.String) null, (java.lang.String) null, (java.lang.String) null, (java.lang.String) null, (java.lang.String) null, (java.lang.String) null, (java.lang.String) null, (java.lang.String) null, (java.lang.String) null, (java.lang.String) null, (java.lang.String) null, (java.lang.String) null, (java.lang.String) null, (java.lang.String) null, false, (java.lang.String) null, (java.lang.String) null, (java.lang.String) null, (java.lang.String) null, (java.lang.String) null, (java.lang.String) null, (java.lang.String) null, false, (java.lang.String) null, sourceCcy, sourceCcySz, extendedBusinessInfo, arbPnl, instFamily, (java.util.ArrayList) arbList, (java.lang.String) null, pnlRatioInSourceCcy, totalPnlInSourceCcy, str2, (java.lang.String) null, voucherInfo, str3, (java.lang.String) null, (java.lang.String) null, str4, str5, str6, str7, str8, str9, str10, zBooleanValue, str11, str12, lastTradeExpireTime, lastSettlementSettledTime, latestProfit, profitSnapshots != null ? CollectionsKt___CollectionsKt.fJNWhG((java.util.Collection) profitSnapshots) : null, strategyDetailsResponse.getPTime(), strategyDetailsResponse.getStakingPnl(), strategyDetailsResponse.getStakingPnlUSDT(), strategyDetailsResponse.getStakingPosCcy(), strategyDetailsResponse.getStakingPnlApy(), (java.util.List) strategyDetailsResponse.getSubArbTypes(), strategyDetailsResponse.getTradeQuoteCcy(), strategyDetailsResponse.getDisplayId(), strategyDetailsResponse.getLeveragePrincipal(), strategyDetailsResponse.getSimpleEarn(), strategyDetailsResponse.getArbitrageTotalPnlInfo(), 0, strategyDetailsResponse.getTotalSpreadProfit(), strategyDetailsResponse.getTotalApy(), strategyDetailsResponse.getFee(), strategyDetailsResponse.getTotalInterestAmt(), strategyDetailsResponse.getDebtCcy(), strategyDetailsResponse.getArbitrageProfit(), strategyDetailsResponse.getStakingProfit(), strategyDetailsResponse.getBalanceDetails(), strategyDetailsResponse.getBot(), (java.lang.String) null, (java.lang.String) null, (java.lang.String) null, 0, 603455488, 268437248, 929792, -98298, -1862008833, 67108865, WalletImportError.ERROR_CODE_AA_EXIST, (DefaultConstructorMarker) null);
    }
}
