package o;

import com.bytedance.applog.encryptor.IEncryptorType;
import com.google.android.exoplayer2.text.ttml.TtmlNode;
import com.google.android.exoplayer2.util.MimeTypes;
import com.huawei.hms.framework.common.hianalytics.CrashHianalyticsData;
import com.okinc.business.defi.wallet.mine.search.data.model.WalletSearchRequest;
import com.okinc.p2p.api.OtcExtraKeys;
import com.okinc.p2p.api.OtcRouteConst;
import com.okinc.web3.security.track.Web3SecurityTrackEvent;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.ConcurrentMap;
import org.htmlcleaner.BelongsTo;
import org.htmlcleaner.CloseTag;
import org.htmlcleaner.ContentType;

/* JADX INFO: renamed from: o.zpf, reason: case insensitive filesystem */
/* JADX INFO: loaded from: classes13.dex */
public class C59886zpf implements InterfaceC59892zpl {
    public static final C59886zpf OLrzqt = new C59886zpf();
    public ConcurrentMap<java.lang.String, C59894zpn> EZpvd = new ConcurrentHashMap();
    public C59891zpk KWHzl;

    public C59886zpf() {
        valueOf(null);
        AEQbTJ(null);
        OLrzqt(null);
        AYXKKw(null);
        copydefault(null);
        EZpvd(null);
        KWHzl(null);
        AhwBna(null);
        djBIcL(null);
        gEmmrt(null);
        this.KWHzl = new C59891zpk(null, this.EZpvd);
    }

    public void valueOf(C59894zpn c59894zpn) {
        ContentType contentType = ContentType.all;
        BelongsTo belongsTo = BelongsTo.BODY;
        CloseTag closeTag = CloseTag.required;
        org.htmlcleaner.Display display = org.htmlcleaner.Display.block;
        C59894zpn c59894zpn2 = new C59894zpn("math", contentType, belongsTo, false, false, false, closeTag, display);
        c59894zpn2.AEQbTJ("bdo,strong,em,q,b,i,sub,sup,small,s");
        c59894zpn2.KWHzl("math,p,summary,address,label,abbr,acronym,dfn,kbd,samp,var,cite,code,param,xml");
        OLrzqt("math", c59894zpn2);
        C59894zpn c59894zpn3 = new C59894zpn("section", contentType, belongsTo, false, false, false, closeTag, display);
        c59894zpn3.AEQbTJ("bdo,strong,em,q,b,i,sub,sup,small,s");
        c59894zpn3.KWHzl("p,summary,address,label,abbr,acronym,dfn,kbd,samp,var,cite,code,param,xml");
        OLrzqt("section", c59894zpn3);
        C59894zpn c59894zpn4 = new C59894zpn(OtcRouteConst.MAIN_ROUTE_NAV, contentType, belongsTo, false, false, false, closeTag, display);
        c59894zpn4.AEQbTJ("bdo,strong,em,q,b,i,sub,sup,small,s");
        c59894zpn4.KWHzl("p,summary,address,label,abbr,acronym,dfn,kbd,samp,var,cite,code,param,xml");
        OLrzqt(OtcRouteConst.MAIN_ROUTE_NAV, c59894zpn4);
        C59894zpn c59894zpn5 = new C59894zpn("article", contentType, belongsTo, false, false, false, closeTag, display);
        c59894zpn5.AEQbTJ("bdo,strong,em,q,b,i,sub,sup,small,s");
        c59894zpn5.KWHzl("p,summary,address,label,abbr,acronym,dfn,kbd,samp,var,cite,code,param,xml");
        c59894zpn5.AYXKKw("menu");
        OLrzqt("article", c59894zpn5);
        C59894zpn c59894zpn6 = new C59894zpn("aside", contentType, belongsTo, false, false, false, closeTag, display);
        c59894zpn6.AEQbTJ("bdo,strong,em,q,b,i,sub,sup,small,s");
        c59894zpn6.KWHzl("p,summary,address,label,abbr,acronym,dfn,kbd,samp,var,cite,code,param,xml");
        c59894zpn6.AYXKKw("menu");
        c59894zpn6.AYXKKw(WalletSearchRequest.SEARCH_SOURCE_ADDRESS);
        OLrzqt("aside", c59894zpn6);
        C59894zpn c59894zpn7 = new C59894zpn("h1", contentType, belongsTo, false, false, false, closeTag, display);
        c59894zpn7.AEQbTJ("bdo,strong,em,q,b,i,sub,sup,small,s");
        c59894zpn7.KWHzl("p,summary,address,label,abbr,acronym,dfn,kbd,samp,var,cite,code,param,xml,h1,h2,h3,h4,h5,h6");
        OLrzqt("h1", c59894zpn7);
        C59894zpn c59894zpn8 = new C59894zpn("h2", contentType, belongsTo, false, false, false, closeTag, display);
        c59894zpn8.AEQbTJ("bdo,strong,em,q,b,i,sub,sup,small,s");
        c59894zpn8.KWHzl("p,summary,address,label,abbr,acronym,dfn,kbd,samp,var,cite,code,param,xml,h1,h2,h3,h4,h5,h6");
        OLrzqt("h2", c59894zpn8);
        C59894zpn c59894zpn9 = new C59894zpn("h3", contentType, belongsTo, false, false, false, closeTag, display);
        c59894zpn9.AEQbTJ("bdo,strong,em,q,b,i,sub,sup,small,s");
        c59894zpn9.KWHzl("p,summary,address,label,abbr,acronym,dfn,kbd,samp,var,cite,code,param,xml,h1,h2,h3,h4,h5,h6");
        OLrzqt("h3", c59894zpn9);
        C59894zpn c59894zpn10 = new C59894zpn("h4", contentType, belongsTo, false, false, false, closeTag, display);
        c59894zpn10.AEQbTJ("bdo,strong,em,q,b,i,sub,sup,small,s");
        c59894zpn10.KWHzl("p,summary,address,label,abbr,acronym,dfn,kbd,samp,var,cite,code,param,xml,h1,h2,h3,h4,h5,h6");
        OLrzqt("h4", c59894zpn10);
        C59894zpn c59894zpn11 = new C59894zpn("h5", contentType, belongsTo, false, false, false, closeTag, display);
        c59894zpn11.AEQbTJ("bdo,strong,em,q,b,i,sub,sup,small,s");
        c59894zpn11.KWHzl("p,summary,address,label,abbr,acronym,dfn,kbd,samp,var,cite,code,param,xml,h1,h2,h3,h4,h5,h6");
        OLrzqt("h5", c59894zpn11);
        C59894zpn c59894zpn12 = new C59894zpn("h6", contentType, belongsTo, false, false, false, closeTag, display);
        c59894zpn12.AEQbTJ("bdo,strong,em,q,b,i,sub,sup,small,s");
        c59894zpn12.KWHzl("p,summary,address,label,abbr,acronym,dfn,kbd,samp,var,cite,code,param,xml,h1,h2,h3,h4,h5,h6");
        OLrzqt("h6", c59894zpn12);
        C59894zpn c59894zpn13 = new C59894zpn("hgroup", contentType, belongsTo, false, false, false, closeTag, display);
        c59894zpn13.AEQbTJ("bdo,strong,em,q,b,i,sub,sup,small,s");
        c59894zpn13.KWHzl("p,summary,address,label,abbr,acronym,dfn,kbd,samp,var,cite,code,param,xml");
        c59894zpn13.EZpvd("h1,h2,h3,h4,h5,h6");
        OLrzqt("hgroup", c59894zpn13);
        C59894zpn c59894zpn14 = new C59894zpn("header", contentType, belongsTo, false, false, false, closeTag, display);
        c59894zpn14.AEQbTJ("bdo,strong,em,q,b,i,sub,sup,small,s");
        c59894zpn14.KWHzl("p,summary,address,label,abbr,acronym,dfn,kbd,samp,var,cite,code,param,xml");
        c59894zpn14.AYXKKw("menu,header,footer");
        OLrzqt("header", c59894zpn14);
        C59894zpn c59894zpn15 = new C59894zpn("footer", contentType, belongsTo, false, false, false, closeTag, display);
        c59894zpn15.AEQbTJ("bdo,strong,em,q,b,i,sub,sup,small,s");
        c59894zpn15.KWHzl("p,summary,address,label,abbr,acronym,dfn,kbd,samp,var,cite,code,param,xml");
        c59894zpn15.AYXKKw("menu,header,footer");
        OLrzqt("footer", c59894zpn15);
        C59894zpn c59894zpn16 = new C59894zpn("main", contentType, belongsTo, false, false, false, closeTag, display);
        c59894zpn16.AEQbTJ("bdo,strong,em,q,b,i,sub,sup,small,s");
        c59894zpn16.KWHzl("p,summary,address,label,abbr,acronym,dfn,kbd,samp,var,cite,code,param,xml");
        OLrzqt("main", c59894zpn16);
        C59894zpn c59894zpn17 = new C59894zpn(WalletSearchRequest.SEARCH_SOURCE_ADDRESS, contentType, belongsTo, false, false, false, closeTag, display);
        c59894zpn17.AEQbTJ("bdo,strong,em,q,b,i,sub,sup,small,s");
        c59894zpn17.KWHzl("p,summary,address,label,abbr,acronym,dfn,kbd,samp,var,cite,code,param,xml");
        c59894zpn17.AYXKKw(WalletSearchRequest.SEARCH_SOURCE_ADDRESS);
        OLrzqt(WalletSearchRequest.SEARCH_SOURCE_ADDRESS, c59894zpn17);
    }

    public void AEQbTJ(C59894zpn c59894zpn) {
        ContentType contentType = ContentType.all;
        BelongsTo belongsTo = BelongsTo.BODY;
        CloseTag closeTag = CloseTag.required;
        org.htmlcleaner.Display display = org.htmlcleaner.Display.block;
        C59894zpn c59894zpn2 = new C59894zpn("details", contentType, belongsTo, false, false, false, closeTag, display);
        c59894zpn2.AEQbTJ("bdo,strong,em,q,b,i,sub,sup,small,s");
        c59894zpn2.KWHzl("p,summary,address,label,abbr,acronym,dfn,kbd,samp,var,cite,code,param,xml");
        OLrzqt("details", c59894zpn2);
        C59894zpn c59894zpn3 = new C59894zpn("summary", contentType, belongsTo, false, false, false, closeTag, display);
        c59894zpn3.AEQbTJ("bdo,strong,em,q,b,i,sub,sup,small,s");
        c59894zpn3.KWHzl("p,summary,address,label,abbr,acronym,dfn,kbd,samp,var,cite,code,param,xml");
        c59894zpn3.AhwBna("details");
        c59894zpn3.AYXKKw("summary");
        OLrzqt("summary", c59894zpn3);
        C59894zpn c59894zpn4 = new C59894zpn("command", contentType, belongsTo, false, false, false, closeTag, display);
        c59894zpn4.AEQbTJ("bdo,strong,em,q,b,i,sub,sup,small,s");
        c59894zpn4.AYXKKw("command");
        c59894zpn4.KWHzl("p,summary,address,label,abbr,acronym,dfn,kbd,samp,var,cite,code,param,xml");
        OLrzqt("command", c59894zpn4);
        C59894zpn c59894zpn5 = new C59894zpn("menu", contentType, belongsTo, false, false, false, closeTag, display);
        c59894zpn5.AEQbTJ("bdo,strong,em,q,b,i,sub,sup,small,s");
        c59894zpn5.KWHzl("p,summary,address,label,abbr,acronym,dfn,kbd,samp,var,cite,code,param,xml");
        c59894zpn5.EZpvd("menuitem,li");
        OLrzqt("menu", c59894zpn5);
        C59894zpn c59894zpn6 = new C59894zpn("menuitem", contentType, belongsTo, false, false, false, closeTag, display);
        c59894zpn6.AEQbTJ("bdo,strong,em,q,b,i,sub,sup,small,s");
        c59894zpn6.KWHzl("p,summary,address,label,abbr,acronym,dfn,kbd,samp,var,cite,code,param,xml");
        c59894zpn6.AhwBna("menu");
        OLrzqt("menuitem", c59894zpn6);
        C59894zpn c59894zpn7 = new C59894zpn("dialog", contentType, belongsTo, false, false, false, closeTag, org.htmlcleaner.Display.any);
        c59894zpn7.KWHzl("p,summary,address,label,abbr,acronym,dfn,kbd,samp,var,cite,code,param,xml");
        OLrzqt("dialog", c59894zpn7);
    }

    public void OLrzqt(C59894zpn c59894zpn) {
        ContentType contentType = ContentType.all;
        BelongsTo belongsTo = BelongsTo.BODY;
        CloseTag closeTag = CloseTag.required;
        org.htmlcleaner.Display display = org.htmlcleaner.Display.block;
        C59894zpn c59894zpn2 = new C59894zpn(TtmlNode.TAG_DIV, contentType, belongsTo, false, false, false, closeTag, display);
        c59894zpn2.AEQbTJ("bdo,strong,em,q,b,i,sub,sup,small,s");
        c59894zpn2.KWHzl("p,summary,address,label,abbr,acronym,dfn,kbd,samp,var,cite,code,param,xml");
        OLrzqt(TtmlNode.TAG_DIV, c59894zpn2);
        C59894zpn c59894zpn3 = new C59894zpn("figure", contentType, belongsTo, false, false, false, closeTag, display);
        c59894zpn3.AEQbTJ("bdo,strong,em,q,b,i,sub,sup,small,s");
        c59894zpn3.KWHzl("p,summary,address,label,abbr,acronym,dfn,kbd,samp,var,cite,code,param,xml");
        OLrzqt("figure", c59894zpn3);
        C59894zpn c59894zpn4 = new C59894zpn("figcaption", contentType, belongsTo, false, false, false, closeTag, org.htmlcleaner.Display.any);
        c59894zpn4.AhwBna("figure");
        OLrzqt("figcaption", c59894zpn4);
        C59894zpn c59894zpn5 = new C59894zpn(TtmlNode.TAG_P, contentType, belongsTo, false, false, false, closeTag, display);
        c59894zpn5.AEQbTJ("bdo,strong,em,q,b,i,sub,sup,small,s");
        c59894zpn5.KWHzl("p,address,summary,label,abbr,acronym,dfn,kbd,samp,var,cite,code,param,xml,time");
        OLrzqt(TtmlNode.TAG_P, c59894zpn5);
        C59894zpn c59894zpn6 = new C59894zpn("pre", contentType, belongsTo, false, false, false, closeTag, display);
        c59894zpn6.AEQbTJ("bdo,strong,em,q,b,i,sub,sup,small,s");
        c59894zpn6.KWHzl("p,summary,address,label,abbr,acronym,dfn,kbd,samp,var,cite,code,param,xml");
        OLrzqt("pre", c59894zpn6);
        C59894zpn c59894zpn7 = new C59894zpn("ul", contentType, belongsTo, false, false, false, closeTag, display);
        c59894zpn7.AEQbTJ("bdo,strong,em,q,b,i,sub,sup,small,s");
        c59894zpn7.KWHzl("dl,p,summary,address,label,abbr,acronym,dfn,kbd,samp,var,cite,code,param,xml");
        c59894zpn7.EZpvd("li,ul,ol,div");
        OLrzqt("ul", c59894zpn7);
        C59894zpn c59894zpn8 = new C59894zpn("ol", contentType, belongsTo, false, false, false, closeTag, display);
        c59894zpn8.AEQbTJ("bdo,strong,em,q,b,i,sub,sup,small,s");
        c59894zpn8.KWHzl("dl,p,summary,address,label,abbr,acronym,dfn,kbd,samp,var,cite,code,param,xml");
        c59894zpn8.EZpvd("li,ul,ol,div");
        OLrzqt("ol", c59894zpn8);
        CloseTag closeTag2 = CloseTag.optional;
        C59894zpn c59894zpn9 = new C59894zpn("li", contentType, belongsTo, false, false, false, closeTag2, display);
        c59894zpn9.AEQbTJ("bdo,strong,em,q,b,i,sub,sup,small,s");
        c59894zpn9.KWHzl("li,p,summary,address,label,abbr,acronym,dfn,kbd,samp,var,cite,code,param,xml");
        c59894zpn9.AhwBna("ol,menu,ul");
        OLrzqt("li", c59894zpn9);
        C59894zpn c59894zpn10 = new C59894zpn("dl", contentType, belongsTo, false, false, false, closeTag, display);
        c59894zpn10.AEQbTJ("bdo,strong,em,q,b,i,sub,sup,small,s");
        c59894zpn10.KWHzl("p,summary,address,label,abbr,acronym,dfn,kbd,samp,var,cite,code,param,xml");
        c59894zpn10.EZpvd("dt,dd");
        OLrzqt("dl", c59894zpn10);
        C59894zpn c59894zpn11 = new C59894zpn("dt", contentType, belongsTo, false, false, false, closeTag2, display);
        c59894zpn11.KWHzl("dt,dd");
        c59894zpn11.AhwBna("dl");
        OLrzqt("dt", c59894zpn11);
        C59894zpn c59894zpn12 = new C59894zpn("dd", contentType, belongsTo, false, false, false, closeTag2, display);
        c59894zpn12.KWHzl("dt,dd");
        c59894zpn12.AhwBna("dl");
        OLrzqt("dd", c59894zpn12);
        C59894zpn c59894zpn13 = new C59894zpn("hr", ContentType.none, belongsTo, false, false, false, CloseTag.forbidden, display);
        c59894zpn13.AEQbTJ("bdo,strong,em,q,b,i,sub,sup,small,s");
        c59894zpn13.KWHzl("p,summary,address,label,abbr,acronym,dfn,kbd,samp,var,cite,code,param,xml");
        OLrzqt("hr", c59894zpn13);
        C59894zpn c59894zpn14 = new C59894zpn("blockquote", contentType, belongsTo, false, false, false, closeTag, display);
        c59894zpn14.AEQbTJ("bdo,strong,em,q,b,i,sub,sup,small,s");
        c59894zpn14.KWHzl("p,summary,address,label,abbr,acronym,dfn,kbd,samp,var,cite,code,param,xml");
        OLrzqt("blockquote", c59894zpn14);
    }

    public void AYXKKw(C59894zpn c59894zpn) {
        ContentType contentType = ContentType.all;
        BelongsTo belongsTo = BelongsTo.BODY;
        CloseTag closeTag = CloseTag.required;
        org.htmlcleaner.Display display = org.htmlcleaner.Display.inline;
        OLrzqt("em", new C59894zpn("em", contentType, belongsTo, false, false, false, closeTag, display));
        OLrzqt("strong", new C59894zpn("strong", contentType, belongsTo, false, false, false, closeTag, display));
        C59894zpn c59894zpn2 = new C59894zpn("small", contentType, belongsTo, false, false, false, closeTag, display);
        c59894zpn2.copydefault("b,u,i,sub,sup,blink,s");
        OLrzqt("small", c59894zpn2);
        C59894zpn c59894zpn3 = new C59894zpn(com.ibm.icu.text.DateFormat.SECOND, contentType, belongsTo, false, false, false, closeTag, display);
        c59894zpn3.copydefault("b,u,i,sub,sup,small,blink");
        OLrzqt(com.ibm.icu.text.DateFormat.SECOND, c59894zpn3);
        C59894zpn c59894zpn4 = new C59894zpn(IEncryptorType.DEFAULT_ENCRYPTOR, contentType, belongsTo, false, false, false, closeTag, display);
        c59894zpn4.KWHzl(IEncryptorType.DEFAULT_ENCRYPTOR);
        OLrzqt(IEncryptorType.DEFAULT_ENCRYPTOR, c59894zpn4);
        ContentType contentType2 = ContentType.none;
        CloseTag closeTag2 = CloseTag.forbidden;
        org.htmlcleaner.Display display2 = org.htmlcleaner.Display.none;
        OLrzqt("wbr", new C59894zpn("wbr", contentType2, belongsTo, false, false, false, closeTag2, display2));
        C59894zpn c59894zpn5 = new C59894zpn("mark", contentType, belongsTo, false, false, false, closeTag, display);
        c59894zpn5.EZpvd("a,abbr,area,audio,b,bdi,bdo,br,button,canvas,cite,code,command,datalist,del,dfn,em,i,input,ins,kbd,keygen,label,link,map,mark,meta,meter,noscript,output,progress,p,ruby,samp,s,script,select,small,span,strong,sub,sup,template,textarea,time,u,var,wbr");
        OLrzqt("mark", c59894zpn5);
        C59894zpn c59894zpn6 = new C59894zpn("bdi", contentType, belongsTo, false, false, false, closeTag, display);
        c59894zpn6.EZpvd("a,abbr,area,audio,b,bdi,bdo,br,button,canvas,cite,code,command,datalist,del,dfn,em,i,input,ins,kbd,keygen,label,link,map,mark,meta,meter,noscript,output,progress,p,ruby,samp,s,script,select,small,span,strong,sub,sup,template,textarea,time,u,var,wbr");
        OLrzqt("bdi", c59894zpn6);
        C59894zpn c59894zpn7 = new C59894zpn(CrashHianalyticsData.TIME, contentType, belongsTo, false, false, false, closeTag, display);
        c59894zpn7.EZpvd("a,abbr,area,audio,b,bdi,bdo,br,button,canvas,cite,code,command,datalist,del,dfn,em,i,input,ins,kbd,keygen,label,link,map,mark,meta,meter,noscript,output,progress,p,ruby,samp,s,script,select,small,span,strong,sub,sup,template,textarea,time,u,var,wbr");
        OLrzqt(CrashHianalyticsData.TIME, c59894zpn7);
        C59894zpn c59894zpn8 = new C59894zpn("data", contentType, belongsTo, false, false, false, closeTag, display);
        c59894zpn8.KWHzl("p,summary,address,label,abbr,acronym,dfn,kbd,samp,var,cite,code,param,xml");
        OLrzqt("data", c59894zpn8);
        OLrzqt("cite", new C59894zpn("cite", contentType, belongsTo, false, false, false, closeTag, display));
        OLrzqt("q", new C59894zpn("q", contentType, belongsTo, false, false, false, closeTag, display));
        OLrzqt("code", new C59894zpn("code", contentType, belongsTo, false, false, false, closeTag, display));
        OLrzqt(TtmlNode.TAG_SPAN, new C59894zpn(TtmlNode.TAG_SPAN, contentType, belongsTo, false, false, false, closeTag, display));
        OLrzqt("bdo", new C59894zpn("bdo", contentType, belongsTo, false, false, false, closeTag, display));
        OLrzqt("dfn", new C59894zpn("dfn", contentType, belongsTo, false, false, false, closeTag, display));
        OLrzqt("kbd", new C59894zpn("kbd", contentType, belongsTo, false, false, false, closeTag, display));
        OLrzqt("abbr", new C59894zpn("abbr", contentType, belongsTo, false, false, false, closeTag, display));
        OLrzqt("var", new C59894zpn("var", contentType, belongsTo, false, false, false, closeTag, display));
        OLrzqt("samp", new C59894zpn("samp", contentType, belongsTo, false, false, false, closeTag, display));
        OLrzqt(TtmlNode.TAG_BR, new C59894zpn(TtmlNode.TAG_BR, contentType2, belongsTo, false, false, false, closeTag2, display2));
        C59894zpn c59894zpn9 = new C59894zpn("sub", contentType, belongsTo, false, false, false, closeTag, display);
        c59894zpn9.copydefault("b,u,i,sup,small,blink,s");
        OLrzqt("sub", c59894zpn9);
        C59894zpn c59894zpn10 = new C59894zpn("sup", contentType, belongsTo, false, false, false, closeTag, display);
        c59894zpn10.copydefault("b,u,i,sub,small,blink,s");
        OLrzqt("sup", c59894zpn10);
        C59894zpn c59894zpn11 = new C59894zpn("b", contentType, belongsTo, false, false, false, closeTag, display);
        c59894zpn11.copydefault("u,i,sub,sup,small,blink,s");
        OLrzqt("b", c59894zpn11);
        C59894zpn c59894zpn12 = new C59894zpn("i", contentType, belongsTo, false, false, false, closeTag, display);
        c59894zpn12.copydefault("b,u,sub,sup,small,blink,s");
        OLrzqt("i", c59894zpn12);
        C59894zpn c59894zpn13 = new C59894zpn("u", contentType, belongsTo, true, false, false, closeTag, display);
        c59894zpn13.copydefault("b,i,sub,sup,small,blink,s");
        OLrzqt("u", c59894zpn13);
        C59894zpn c59894zpn14 = new C59894zpn(TtmlNode.ATTR_TTS_RUBY, contentType, belongsTo, false, false, false, closeTag, display);
        c59894zpn14.EZpvd("rt,rp,rb,rtc");
        OLrzqt(TtmlNode.ATTR_TTS_RUBY, c59894zpn14);
        CloseTag closeTag3 = CloseTag.optional;
        C59894zpn c59894zpn15 = new C59894zpn("rtc", contentType, belongsTo, false, false, false, closeTag3, display);
        c59894zpn15.AhwBna(TtmlNode.ATTR_TTS_RUBY);
        c59894zpn15.EZpvd("rt,a,abbr,area,audio,b,bdi,bdo,br,button,canvas,cite,code,command,datalist,del,dfn,em,i,input,ins,kbd,keygen,label,link,map,mark,meta,meter,noscript,output,progress,p,ruby,samp,s,script,select,small,span,strong,sub,sup,template,textarea,time,u,var,wbr");
        OLrzqt("rtc", c59894zpn15);
        C59894zpn c59894zpn16 = new C59894zpn("rb", contentType, belongsTo, false, false, false, closeTag3, display);
        c59894zpn16.AhwBna(TtmlNode.ATTR_TTS_RUBY);
        OLrzqt("rb", c59894zpn16);
        ContentType contentType3 = ContentType.text;
        C59894zpn c59894zpn17 = new C59894zpn("rt", contentType3, belongsTo, false, false, false, closeTag3, display);
        c59894zpn17.AhwBna(TtmlNode.ATTR_TTS_RUBY);
        c59894zpn17.EZpvd("a,abbr,area,audio,b,bdi,bdo,br,button,canvas,cite,code,command,datalist,del,dfn,em,i,input,ins,kbd,keygen,label,link,map,mark,meta,meter,noscript,output,progress,p,ruby,samp,s,script,select,small,span,strong,sub,sup,template,textarea,time,u,var,wbr");
        OLrzqt("rt", c59894zpn17);
        C59894zpn c59894zpn18 = new C59894zpn("rp", contentType3, belongsTo, false, false, false, closeTag3, display);
        c59894zpn18.AhwBna(TtmlNode.ATTR_TTS_RUBY);
        c59894zpn18.EZpvd("a,abbr,area,audio,b,bdi,bdo,br,button,canvas,cite,code,command,datalist,del,dfn,em,i,input,ins,kbd,keygen,label,link,map,mark,meta,meter,noscript,output,progress,p,ruby,samp,s,script,select,small,span,strong,sub,sup,template,textarea,time,u,var,wbr");
        OLrzqt("rp", c59894zpn18);
    }

    public void copydefault(C59894zpn c59894zpn) {
        ContentType contentType = ContentType.none;
        BelongsTo belongsTo = BelongsTo.BODY;
        CloseTag closeTag = CloseTag.forbidden;
        OLrzqt("img", new C59894zpn("img", contentType, belongsTo, false, false, false, closeTag, org.htmlcleaner.Display.inline));
        ContentType contentType2 = ContentType.all;
        CloseTag closeTag2 = CloseTag.required;
        org.htmlcleaner.Display display = org.htmlcleaner.Display.any;
        OLrzqt("iframe", new C59894zpn("iframe", contentType2, belongsTo, false, false, false, closeTag2, display));
        C59894zpn c59894zpn2 = new C59894zpn("embed", contentType, belongsTo, false, false, false, closeTag, org.htmlcleaner.Display.block);
        c59894zpn2.AEQbTJ("bdo,strong,em,q,b,i,sub,sup,small,s");
        c59894zpn2.KWHzl("p,summary,address,label,abbr,acronym,dfn,kbd,samp,var,cite,code,param,xml");
        OLrzqt("embed", c59894zpn2);
        OLrzqt("object", new C59894zpn("object", contentType2, belongsTo, false, false, false, closeTag2, display));
        org.htmlcleaner.Display display2 = org.htmlcleaner.Display.none;
        C59894zpn c59894zpn3 = new C59894zpn("param", contentType, belongsTo, false, false, false, closeTag, display2);
        c59894zpn3.AEQbTJ("bdo,strong,em,q,b,i,sub,sup,small,s");
        c59894zpn3.KWHzl("p,summary,address,label,abbr,acronym,dfn,kbd,samp,var,cite,code,param,xml");
        c59894zpn3.AhwBna("object");
        OLrzqt("param", c59894zpn3);
        C59894zpn c59894zpn4 = new C59894zpn(MimeTypes.BASE_TYPE_AUDIO, contentType2, belongsTo, false, false, false, closeTag2, display);
        c59894zpn4.copydefault("audio,video,object,source");
        OLrzqt(MimeTypes.BASE_TYPE_AUDIO, c59894zpn4);
        C59894zpn c59894zpn5 = new C59894zpn("picture", contentType2, belongsTo, false, false, false, closeTag2, display);
        c59894zpn5.copydefault("audio,video,object,source");
        OLrzqt("picture", c59894zpn5);
        C59894zpn c59894zpn6 = new C59894zpn(MimeTypes.BASE_TYPE_VIDEO, contentType2, belongsTo, false, false, false, closeTag2, display);
        c59894zpn6.copydefault("audio,video,object,source");
        OLrzqt(MimeTypes.BASE_TYPE_VIDEO, c59894zpn6);
        C59894zpn c59894zpn7 = new C59894zpn("source", contentType, belongsTo, false, false, false, closeTag, display);
        c59894zpn7.AhwBna("audio,video,object");
        OLrzqt("source", c59894zpn7);
        C59894zpn c59894zpn8 = new C59894zpn("track", contentType, belongsTo, false, false, false, closeTag, display);
        c59894zpn8.AhwBna("audio,video,object,source");
        OLrzqt("track", c59894zpn8);
        OLrzqt("canvas", new C59894zpn("canvas", contentType2, belongsTo, false, false, false, closeTag2, display));
        C59894zpn c59894zpn9 = new C59894zpn(OtcExtraKeys.AREA, contentType, belongsTo, false, false, false, closeTag, display2);
        c59894zpn9.OLrzqt("map");
        c59894zpn9.KWHzl(OtcExtraKeys.AREA);
        OLrzqt(OtcExtraKeys.AREA, c59894zpn9);
        C59894zpn c59894zpn10 = new C59894zpn("map", contentType2, belongsTo, false, false, false, closeTag2, display);
        c59894zpn10.KWHzl("map");
        c59894zpn10.EZpvd(OtcExtraKeys.AREA);
        OLrzqt("map", c59894zpn10);
    }

    public void EZpvd(C59894zpn c59894zpn) {
        ContentType contentType = ContentType.all;
        BelongsTo belongsTo = BelongsTo.BODY;
        CloseTag closeTag = CloseTag.required;
        org.htmlcleaner.Display display = org.htmlcleaner.Display.any;
        OLrzqt("ins", new C59894zpn("ins", contentType, belongsTo, false, false, false, closeTag, display));
        OLrzqt("del", new C59894zpn("del", contentType, belongsTo, false, false, false, closeTag, display));
    }

    public void AhwBna(C59894zpn c59894zpn) {
        ContentType contentType = ContentType.all;
        BelongsTo belongsTo = BelongsTo.BODY;
        CloseTag closeTag = CloseTag.required;
        org.htmlcleaner.Display display = org.htmlcleaner.Display.block;
        C59894zpn c59894zpn2 = new C59894zpn("table", contentType, belongsTo, false, false, false, closeTag, display);
        c59894zpn2.EZpvd("tr,tbody,thead,tfoot,col,colgroup,caption");
        c59894zpn2.AEQbTJ("bdo,strong,em,q,b,i,sub,sup,small,s");
        c59894zpn2.KWHzl("tr,thead,tbody,tfoot,caption,colgroup,table,p,address,label,abbr,acronym,dfn,kbd,samp,var,cite,code,param,xml");
        OLrzqt("table", c59894zpn2);
        CloseTag closeTag2 = CloseTag.optional;
        C59894zpn c59894zpn3 = new C59894zpn("tr", contentType, belongsTo, false, false, false, closeTag2, display);
        c59894zpn3.OLrzqt("table");
        c59894zpn3.AhwBna("tbody");
        c59894zpn3.EZpvd("td,th");
        c59894zpn3.valueOf("thead,tfoot");
        c59894zpn3.KWHzl("tr,td,th,caption,colgroup");
        OLrzqt("tr", c59894zpn3);
        C59894zpn c59894zpn4 = new C59894zpn("td", contentType, belongsTo, false, false, false, closeTag, display);
        c59894zpn4.OLrzqt("table");
        c59894zpn4.AhwBna("tr");
        c59894zpn4.KWHzl("td,th,caption,colgroup");
        OLrzqt("td", c59894zpn4);
        C59894zpn c59894zpn5 = new C59894zpn("th", contentType, belongsTo, false, false, false, closeTag2, display);
        c59894zpn5.OLrzqt("table");
        c59894zpn5.AhwBna("tr");
        c59894zpn5.KWHzl("td,th,caption,colgroup");
        OLrzqt("th", c59894zpn5);
        C59894zpn c59894zpn6 = new C59894zpn("tbody", contentType, belongsTo, false, false, false, closeTag2, display);
        c59894zpn6.OLrzqt("table");
        c59894zpn6.EZpvd("tr,form");
        c59894zpn6.KWHzl("td,th,tr,tbody,thead,tfoot,caption,colgroup");
        OLrzqt("tbody", c59894zpn6);
        C59894zpn c59894zpn7 = new C59894zpn("thead", contentType, belongsTo, false, false, false, closeTag2, display);
        c59894zpn7.OLrzqt("table");
        c59894zpn7.EZpvd("tr,form");
        c59894zpn7.KWHzl("td,th,tr,tbody,thead,tfoot,caption,colgroup");
        OLrzqt("thead", c59894zpn7);
        C59894zpn c59894zpn8 = new C59894zpn("tfoot", contentType, belongsTo, false, false, false, closeTag2, display);
        c59894zpn8.OLrzqt("table");
        c59894zpn8.EZpvd("tr,form");
        c59894zpn8.KWHzl("td,th,tr,tbody,thead,tfoot,caption,colgroup");
        OLrzqt("tfoot", c59894zpn8);
        C59894zpn c59894zpn9 = new C59894zpn("col", ContentType.none, belongsTo, false, false, false, CloseTag.forbidden, display);
        c59894zpn9.OLrzqt("colgroup");
        OLrzqt("col", c59894zpn9);
        C59894zpn c59894zpn10 = new C59894zpn("colgroup", contentType, belongsTo, false, false, false, closeTag2, display);
        c59894zpn10.OLrzqt("table");
        c59894zpn10.EZpvd("col");
        c59894zpn10.KWHzl("td,th,tr,tbody,thead,tfoot,caption,colgroup");
        OLrzqt("colgroup", c59894zpn10);
        C59894zpn c59894zpn11 = new C59894zpn("caption", contentType, belongsTo, false, false, false, closeTag, org.htmlcleaner.Display.inline);
        c59894zpn11.OLrzqt("table");
        c59894zpn11.KWHzl("td,th,tr,tbody,thead,tfoot,caption,colgroup");
        OLrzqt("caption", c59894zpn11);
    }

    public void KWHzl(C59894zpn c59894zpn) {
        ContentType contentType = ContentType.all;
        BelongsTo belongsTo = BelongsTo.BODY;
        CloseTag closeTag = CloseTag.required;
        org.htmlcleaner.Display display = org.htmlcleaner.Display.inline;
        C59894zpn c59894zpn2 = new C59894zpn("meter", contentType, belongsTo, false, false, false, closeTag, display);
        c59894zpn2.EZpvd("a,abbr,area,audio,b,bdi,bdo,br,button,canvas,cite,code,command,datalist,del,dfn,em,i,input,ins,kbd,keygen,label,link,map,mark,meta,meter,noscript,output,progress,p,ruby,samp,s,script,select,small,span,strong,sub,sup,template,textarea,time,u,var,wbr");
        c59894zpn2.KWHzl("meter");
        OLrzqt("meter", c59894zpn2);
        org.htmlcleaner.Display display2 = org.htmlcleaner.Display.block;
        C59894zpn c59894zpn3 = new C59894zpn("form", contentType, belongsTo, false, false, true, closeTag, display2);
        c59894zpn3.AYXKKw("form");
        c59894zpn3.AEQbTJ("bdo,strong,em,q,b,i,sub,sup,small,s");
        c59894zpn3.KWHzl("option,optgroup,textarea,select,fieldset,p,address,label,abbr,acronym,dfn,kbd,samp,var,cite,code,param,xml");
        OLrzqt("form", c59894zpn3);
        ContentType contentType2 = ContentType.none;
        CloseTag closeTag2 = CloseTag.forbidden;
        C59894zpn c59894zpn4 = new C59894zpn(Web3SecurityTrackEvent.VALUE_INPUT, contentType2, belongsTo, false, false, false, closeTag2, display);
        c59894zpn4.KWHzl("select,optgroup,option");
        OLrzqt(Web3SecurityTrackEvent.VALUE_INPUT, c59894zpn4);
        C59894zpn c59894zpn5 = new C59894zpn("textarea", contentType, belongsTo, false, false, false, closeTag, display);
        c59894zpn5.KWHzl("select,optgroup,option");
        OLrzqt("textarea", c59894zpn5);
        C59894zpn c59894zpn6 = new C59894zpn("select", contentType, belongsTo, false, false, true, closeTag, display);
        c59894zpn6.EZpvd("option,optgroup");
        c59894zpn6.KWHzl("option,optgroup,select");
        OLrzqt("select", c59894zpn6);
        C59894zpn c59894zpn7 = new C59894zpn("option", ContentType.text, belongsTo, false, false, true, CloseTag.optional, display);
        c59894zpn7.OLrzqt("select,datalist");
        c59894zpn7.KWHzl("option");
        OLrzqt("option", c59894zpn7);
        C59894zpn c59894zpn8 = new C59894zpn("optgroup", contentType, belongsTo, false, false, true, closeTag, display);
        c59894zpn8.OLrzqt("select");
        c59894zpn8.EZpvd("option");
        c59894zpn8.KWHzl("optgroup");
        OLrzqt("optgroup", c59894zpn8);
        org.htmlcleaner.Display display3 = org.htmlcleaner.Display.any;
        C59894zpn c59894zpn9 = new C59894zpn("button", contentType, belongsTo, false, false, false, closeTag, display3);
        c59894zpn9.KWHzl("select,optgroup,option");
        OLrzqt("button", c59894zpn9);
        OLrzqt("label", new C59894zpn("label", contentType, belongsTo, false, false, false, closeTag, display));
        C59894zpn c59894zpn10 = new C59894zpn("legend", contentType, belongsTo, false, false, false, closeTag, display2);
        c59894zpn10.AhwBna("fieldset");
        c59894zpn10.EZpvd("a,abbr,area,audio,b,bdi,bdo,br,button,canvas,cite,code,command,datalist,del,dfn,em,i,input,ins,kbd,keygen,label,link,map,mark,meta,meter,noscript,output,progress,p,ruby,samp,s,script,select,small,span,strong,sub,sup,template,textarea,time,u,var,wbr");
        OLrzqt("legend", c59894zpn10);
        C59894zpn c59894zpn11 = new C59894zpn("fieldset", contentType, belongsTo, false, false, false, closeTag, display2);
        c59894zpn11.AEQbTJ("bdo,strong,em,q,b,i,sub,sup,small,s");
        c59894zpn11.KWHzl("p,address,label,abbr,acronym,dfn,kbd,samp,var,cite,code,param,xml");
        OLrzqt("fieldset", c59894zpn11);
        C59894zpn c59894zpn12 = new C59894zpn("progress", contentType, belongsTo, false, false, false, closeTag, display3);
        c59894zpn12.EZpvd("a,abbr,area,audio,b,bdi,bdo,br,button,canvas,cite,code,command,datalist,del,dfn,em,i,input,ins,kbd,keygen,label,link,map,mark,meta,meter,noscript,output,progress,p,ruby,samp,s,script,select,small,span,strong,sub,sup,template,textarea,time,u,var,wbr");
        c59894zpn12.KWHzl("progress");
        OLrzqt("progress", c59894zpn12);
        C59894zpn c59894zpn13 = new C59894zpn("datalist", contentType, belongsTo, false, false, false, closeTag, display3);
        c59894zpn13.EZpvd("option");
        c59894zpn13.KWHzl("datalist");
        OLrzqt("datalist", c59894zpn13);
        OLrzqt("keygen", new C59894zpn("keygen", contentType, belongsTo, false, false, false, closeTag2, display3));
        C59894zpn c59894zpn14 = new C59894zpn("output", contentType, belongsTo, false, false, false, closeTag, display3);
        c59894zpn14.KWHzl("output,p,summary,address,label,abbr,acronym,dfn,kbd,samp,var,cite,code,param,xml");
        OLrzqt("output", c59894zpn14);
    }

    public void djBIcL(C59894zpn c59894zpn) {
        ContentType contentType = ContentType.none;
        BelongsTo belongsTo = BelongsTo.HEAD_AND_BODY;
        CloseTag closeTag = CloseTag.forbidden;
        org.htmlcleaner.Display display = org.htmlcleaner.Display.none;
        OLrzqt("meta", new C59894zpn("meta", contentType, belongsTo, false, false, false, closeTag, display));
        OLrzqt("link", new C59894zpn("link", contentType, belongsTo, false, false, false, closeTag, display));
        ContentType contentType2 = ContentType.text;
        BelongsTo belongsTo2 = BelongsTo.HEAD;
        CloseTag closeTag2 = CloseTag.required;
        OLrzqt("title", new C59894zpn("title", contentType2, belongsTo2, false, true, false, closeTag2, display));
        OLrzqt(TtmlNode.TAG_STYLE, new C59894zpn(TtmlNode.TAG_STYLE, contentType2, belongsTo, false, false, false, closeTag2, display));
        OLrzqt(TtmlNode.RUBY_BASE, new C59894zpn(TtmlNode.RUBY_BASE, contentType, belongsTo2, false, false, false, closeTag, display));
    }

    public void gEmmrt(C59894zpn c59894zpn) {
        ContentType contentType = ContentType.all;
        BelongsTo belongsTo = BelongsTo.HEAD_AND_BODY;
        CloseTag closeTag = CloseTag.required;
        OLrzqt("script", new C59894zpn("script", contentType, belongsTo, false, false, false, closeTag, org.htmlcleaner.Display.none));
        OLrzqt("noscript", new C59894zpn("noscript", contentType, belongsTo, false, false, false, closeTag, org.htmlcleaner.Display.block));
    }

    public void OLrzqt(java.lang.String str, C59894zpn c59894zpn) {
        this.EZpvd.put(str, c59894zpn);
    }

    @Override // o.InterfaceC59892zpl
    public C59894zpn getTagInfo(java.lang.String str) {
        if (str == null) {
            return null;
        }
        return this.EZpvd.get(str);
    }
}
