package o;

import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.databinding.ViewDataBinding;
import com.okinc.buysell.ui.buysellconvert.transaction.buysell.view.UnifiedOrderDetailBodyTwoStepInfoView;

/* JADX INFO: loaded from: classes7.dex */
public abstract class lxI extends ViewDataBinding {
    public final android.widget.LinearLayout AEQbTJ;
    public final android.widget.ImageView AYXKKw;
    public final ConstraintLayout AhwBna;
    public final android.widget.ImageView AkhnZx;
    public final ConstraintLayout AuCTel;
    public final ConstraintLayout AuCTelauCTel;
    public final android.widget.LinearLayout AubY;
    public final android.widget.TextView AwvSrB;
    public final android.widget.ImageView AxsJAY;
    public final android.widget.TextView AxsJAYaxsJAY;
    public final android.widget.ImageView DTwDnp;
    public final ConstraintLayout DbNXlk;
    public final ConstraintLayout EZpvd;
    public final android.widget.LinearLayout KWHzl;
    public final ConstraintLayout OLrzqt;
    public final android.widget.ImageView ORxRYg;
    public final android.widget.TextView OcIXYQ;
    public final android.widget.ImageView QKVWgx;
    public final android.widget.TextView QOLQEE;
    public final android.widget.TextView QUSxYX;
    public final android.widget.TextView QVAiDq;
    public final android.widget.TextView QbewEr;
    public final android.widget.TextView QfsBiF;
    public final android.widget.TextView RJOkX;
    public final android.widget.TextView RcXXUw;
    public final android.view.View RlQdEF;
    public final android.widget.TextView UeEOUB;
    public final android.widget.TextView aKErDB;
    public final android.view.View accept;
    public final android.widget.LinearLayout copydefault;
    public final android.widget.TextView dNCPSb;
    public final android.widget.LinearLayout djBIcL;
    public final android.widget.TextView djSkpj;
    public final android.widget.TextView dvKsVJ;
    public final android.widget.TextView dxcTrN;
    public final ConstraintLayout ejfBZ;
    public final ConstraintLayout fARcdN;
    public final android.widget.TextView fFgQHt;
    public final AbstractC31607lxi fIwbmz;
    public final ConstraintLayout fJNWhG;
    public final android.widget.TextView fZBcTu;
    public final android.widget.ImageView fetchVPNInfo;
    public final android.widget.TextView finit;
    public final android.widget.TextView flVtFt;
    public final android.widget.TextView fvQaOB;
    public final android.widget.ImageView gEmmrt;
    public final android.widget.TextView gGvvIC;
    public final android.widget.TextView gHZMYf;
    public final android.widget.TextView gasjUx;
    public final ConstraintLayout getFieldNames;
    public final ConstraintLayout getNewProxyInstance;
    public final C57635ymD giSNqX;
    public final android.view.View gkJEwt;
    public final ConstraintLayout hDKMBd;
    public final android.widget.TextView hUfVAv;
    public final UnifiedOrderDetailBodyTwoStepInfoView iRxXKY;
    public final android.widget.TextView iZzfmt;
    public final android.widget.ImageView isConnected;
    public final ConstraintLayout iwGUEr;
    public final ConstraintLayout sSMYrx;
    public final ConstraintLayout uzCIH;
    public final android.widget.LinearLayout valueOf;
    public final android.widget.ImageView values;
    public final ConstraintLayout wlaJM;
    public final ConstraintLayout zLjUOn;
    public final ConstraintLayout zsXlph;
    public final android.widget.TextView zuBGHE;

    public lxI(java.lang.Object obj, android.view.View view, int i, ConstraintLayout constraintLayout, ConstraintLayout constraintLayout2, android.widget.LinearLayout linearLayout, android.widget.LinearLayout linearLayout2, android.widget.LinearLayout linearLayout3, android.widget.LinearLayout linearLayout4, ConstraintLayout constraintLayout3, android.widget.ImageView imageView, android.widget.ImageView imageView2, android.widget.LinearLayout linearLayout5, ConstraintLayout constraintLayout4, android.widget.ImageView imageView3, android.widget.ImageView imageView4, android.widget.ImageView imageView5, android.widget.ImageView imageView6, ConstraintLayout constraintLayout5, ConstraintLayout constraintLayout6, ConstraintLayout constraintLayout7, AbstractC31607lxi abstractC31607lxi, ConstraintLayout constraintLayout8, ConstraintLayout constraintLayout9, ConstraintLayout constraintLayout10, ConstraintLayout constraintLayout11, ConstraintLayout constraintLayout12, ConstraintLayout constraintLayout13, ConstraintLayout constraintLayout14, ConstraintLayout constraintLayout15, ConstraintLayout constraintLayout16, ConstraintLayout constraintLayout17, android.widget.LinearLayout linearLayout6, android.widget.TextView textView, android.widget.ImageView imageView7, ConstraintLayout constraintLayout18, android.widget.TextView textView2, android.widget.TextView textView3, android.widget.ImageView imageView8, android.widget.ImageView imageView9, android.widget.ImageView imageView10, android.widget.TextView textView4, android.widget.TextView textView5, android.widget.TextView textView6, android.widget.TextView textView7, android.widget.TextView textView8, android.widget.TextView textView9, android.widget.TextView textView10, android.widget.TextView textView11, android.widget.TextView textView12, android.widget.TextView textView13, android.widget.TextView textView14, android.widget.TextView textView15, android.widget.TextView textView16, android.widget.TextView textView17, android.widget.TextView textView18, android.widget.TextView textView19, android.widget.TextView textView20, android.widget.TextView textView21, android.widget.TextView textView22, C57635ymD c57635ymD, android.widget.TextView textView23, android.widget.TextView textView24, android.widget.TextView textView25, android.widget.TextView textView26, android.widget.TextView textView27, UnifiedOrderDetailBodyTwoStepInfoView unifiedOrderDetailBodyTwoStepInfoView, android.view.View view2, android.view.View view3, android.view.View view4) {
        super(obj, view, i);
        this.EZpvd = constraintLayout;
        this.OLrzqt = constraintLayout2;
        this.copydefault = linearLayout;
        this.KWHzl = linearLayout2;
        this.AEQbTJ = linearLayout3;
        this.djBIcL = linearLayout4;
        this.AhwBna = constraintLayout3;
        this.gEmmrt = imageView;
        this.AYXKKw = imageView2;
        this.valueOf = linearLayout5;
        this.DbNXlk = constraintLayout4;
        this.fetchVPNInfo = imageView3;
        this.AkhnZx = imageView4;
        this.isConnected = imageView5;
        this.values = imageView6;
        this.ejfBZ = constraintLayout5;
        this.AuCTel = constraintLayout6;
        this.fARcdN = constraintLayout7;
        this.fIwbmz = abstractC31607lxi;
        this.fJNWhG = constraintLayout8;
        this.hDKMBd = constraintLayout9;
        this.iwGUEr = constraintLayout10;
        this.uzCIH = constraintLayout11;
        this.getFieldNames = constraintLayout12;
        this.getNewProxyInstance = constraintLayout13;
        this.AuCTelauCTel = constraintLayout14;
        this.zsXlph = constraintLayout15;
        this.zLjUOn = constraintLayout16;
        this.wlaJM = constraintLayout17;
        this.AubY = linearLayout6;
        this.zuBGHE = textView;
        this.AxsJAY = imageView7;
        this.sSMYrx = constraintLayout18;
        this.AwvSrB = textView2;
        this.gHZMYf = textView3;
        this.DTwDnp = imageView8;
        this.QKVWgx = imageView9;
        this.ORxRYg = imageView10;
        this.OcIXYQ = textView4;
        this.QOLQEE = textView5;
        this.QUSxYX = textView6;
        this.QfsBiF = textView7;
        this.QVAiDq = textView8;
        this.RJOkX = textView9;
        this.QbewEr = textView10;
        this.RcXXUw = textView11;
        this.UeEOUB = textView12;
        this.aKErDB = textView13;
        this.djSkpj = textView14;
        this.dNCPSb = textView15;
        this.fZBcTu = textView16;
        this.finit = textView17;
        this.dvKsVJ = textView18;
        this.fFgQHt = textView19;
        this.dxcTrN = textView20;
        this.fvQaOB = textView21;
        this.gGvvIC = textView22;
        this.giSNqX = c57635ymD;
        this.gasjUx = textView23;
        this.flVtFt = textView24;
        this.iZzfmt = textView25;
        this.AxsJAYaxsJAY = textView26;
        this.hUfVAv = textView27;
        this.iRxXKY = unifiedOrderDetailBodyTwoStepInfoView;
        this.gkJEwt = view2;
        this.RlQdEF = view3;
        this.accept = view4;
    }
}
