package o;

import kotlin.text.Regex;

/* JADX INFO: loaded from: classes2.dex */
public final class NetworkIdentity {
    public static final java.util.List<OutputStream> EZpvd;

    public static final PushbackInputStream KWHzl(java.lang.String str) {
        return OutputStreamWriter.copydefault(EZpvd, str);
    }

    static {
        Regex regex = new Regex("^(us|eu|ap|sa|ca|me|af|il)\\-\\w+\\-\\d+$");
        java.util.Map mapGEmmrt = C56424yEw.gEmmrt(C56390yDp.OLrzqt("af-south-1", new PushbackInputStream(null, null, null, null, null, 31, null)), C56390yDp.OLrzqt("ap-east-1", new PushbackInputStream(null, null, null, null, null, 31, null)), C56390yDp.OLrzqt("ap-northeast-1", new PushbackInputStream(null, null, null, null, null, 31, null)), C56390yDp.OLrzqt("ap-northeast-2", new PushbackInputStream(null, null, null, null, null, 31, null)), C56390yDp.OLrzqt("ap-northeast-3", new PushbackInputStream(null, null, null, null, null, 31, null)), C56390yDp.OLrzqt("ap-south-1", new PushbackInputStream(null, null, null, null, null, 31, null)), C56390yDp.OLrzqt("ap-south-2", new PushbackInputStream(null, null, null, null, null, 31, null)), C56390yDp.OLrzqt("ap-southeast-1", new PushbackInputStream(null, null, null, null, null, 31, null)), C56390yDp.OLrzqt("ap-southeast-2", new PushbackInputStream(null, null, null, null, null, 31, null)), C56390yDp.OLrzqt("ap-southeast-3", new PushbackInputStream(null, null, null, null, null, 31, null)), C56390yDp.OLrzqt("ap-southeast-4", new PushbackInputStream(null, null, null, null, null, 31, null)), C56390yDp.OLrzqt("aws-global", new PushbackInputStream(null, null, null, null, null, 31, null)), C56390yDp.OLrzqt("ca-central-1", new PushbackInputStream(null, null, null, null, null, 31, null)), C56390yDp.OLrzqt("ca-west-1", new PushbackInputStream(null, null, null, null, null, 31, null)), C56390yDp.OLrzqt("eu-central-1", new PushbackInputStream(null, null, null, null, null, 31, null)), C56390yDp.OLrzqt("eu-central-2", new PushbackInputStream(null, null, null, null, null, 31, null)), C56390yDp.OLrzqt("eu-north-1", new PushbackInputStream(null, null, null, null, null, 31, null)), C56390yDp.OLrzqt("eu-south-1", new PushbackInputStream(null, null, null, null, null, 31, null)), C56390yDp.OLrzqt("eu-south-2", new PushbackInputStream(null, null, null, null, null, 31, null)), C56390yDp.OLrzqt("eu-west-1", new PushbackInputStream(null, null, null, null, null, 31, null)), C56390yDp.OLrzqt("eu-west-2", new PushbackInputStream(null, null, null, null, null, 31, null)), C56390yDp.OLrzqt("eu-west-3", new PushbackInputStream(null, null, null, null, null, 31, null)), C56390yDp.OLrzqt("il-central-1", new PushbackInputStream(null, null, null, null, null, 31, null)), C56390yDp.OLrzqt("me-central-1", new PushbackInputStream(null, null, null, null, null, 31, null)), C56390yDp.OLrzqt("me-south-1", new PushbackInputStream(null, null, null, null, null, 31, null)), C56390yDp.OLrzqt("sa-east-1", new PushbackInputStream(null, null, null, null, null, 31, null)), C56390yDp.OLrzqt("us-east-1", new PushbackInputStream(null, null, null, null, null, 31, null)), C56390yDp.OLrzqt("us-east-2", new PushbackInputStream(null, null, null, null, null, 31, null)), C56390yDp.OLrzqt("us-west-1", new PushbackInputStream(null, null, null, null, null, 31, null)), C56390yDp.OLrzqt("us-west-2", new PushbackInputStream(null, null, null, null, null, 31, null)));
        java.lang.Boolean bool = java.lang.Boolean.TRUE;
        OutputStream outputStream = new OutputStream("aws", mapGEmmrt, regex, new PushbackInputStream("aws", "amazonaws.com", "api.aws", bool, bool));
        OutputStream outputStream2 = new OutputStream("aws-cn", C56424yEw.gEmmrt(C56390yDp.OLrzqt("aws-cn-global", new PushbackInputStream(null, null, null, null, null, 31, null)), C56390yDp.OLrzqt("cn-north-1", new PushbackInputStream(null, null, null, null, null, 31, null)), C56390yDp.OLrzqt("cn-northwest-1", new PushbackInputStream(null, null, null, null, null, 31, null))), new Regex("^cn\\-\\w+\\-\\d+$"), new PushbackInputStream("aws-cn", "amazonaws.com.cn", "api.amazonwebservices.com.cn", bool, bool));
        OutputStream outputStream3 = new OutputStream("aws-us-gov", C56424yEw.gEmmrt(C56390yDp.OLrzqt("aws-us-gov-global", new PushbackInputStream(null, null, null, null, null, 31, null)), C56390yDp.OLrzqt("us-gov-east-1", new PushbackInputStream(null, null, null, null, null, 31, null)), C56390yDp.OLrzqt("us-gov-west-1", new PushbackInputStream(null, null, null, null, null, 31, null))), new Regex("^us\\-gov\\-\\w+\\-\\d+$"), new PushbackInputStream("aws-us-gov", "amazonaws.com", "api.aws", bool, bool));
        Regex regex2 = new Regex("^us\\-iso\\-\\w+\\-\\d+$");
        java.util.Map mapGEmmrt2 = C56424yEw.gEmmrt(C56390yDp.OLrzqt("aws-iso-global", new PushbackInputStream(null, null, null, null, null, 31, null)), C56390yDp.OLrzqt("us-iso-east-1", new PushbackInputStream(null, null, null, null, null, 31, null)), C56390yDp.OLrzqt("us-iso-west-1", new PushbackInputStream(null, null, null, null, null, 31, null)));
        java.lang.Boolean bool2 = java.lang.Boolean.FALSE;
        EZpvd = yDY.gEmmrt(outputStream, outputStream2, outputStream3, new OutputStream("aws-iso", mapGEmmrt2, regex2, new PushbackInputStream("aws-iso", "c2s.ic.gov", "c2s.ic.gov", bool, bool2)), new OutputStream("aws-iso-b", C56424yEw.gEmmrt(C56390yDp.OLrzqt("aws-iso-b-global", new PushbackInputStream(null, null, null, null, null, 31, null)), C56390yDp.OLrzqt("us-isob-east-1", new PushbackInputStream(null, null, null, null, null, 31, null))), new Regex("^us\\-isob\\-\\w+\\-\\d+$"), new PushbackInputStream("aws-iso-b", "sc2s.sgov.gov", "sc2s.sgov.gov", bool, bool2)), new OutputStream("aws-iso-e", C56424yEw.KWHzl(), new Regex("^eu\\-isoe\\-\\w+\\-\\d+$"), new PushbackInputStream("aws-iso-e", "cloud.adc-e.uk", "cloud.adc-e.uk", bool, bool2)), new OutputStream("aws-iso-f", C56424yEw.KWHzl(), new Regex("^us\\-isof\\-\\w+\\-\\d+$"), new PushbackInputStream("aws-iso-f", "csp.hci.ic.gov", "csp.hci.ic.gov", bool, bool2)));
    }
}
