package o;

import androidx.appcompat.widget.AppCompatImageView;
import androidx.appcompat.widget.LinearLayoutCompat;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.databinding.ViewDataBinding;

/* JADX INFO: loaded from: classes11.dex */
public abstract class uSW extends ViewDataBinding {
    public final LinearLayoutCompat AEQbTJ;
    public final android.widget.TextView AYXKKw;
    public final C55258xgZ AhwBna;
    public final C53539wnR AkhnZx;
    public final android.widget.TextView AuCTel;
    public final C55239xgG AuCTelauCTel;
    public final C55320xhi AubY;
    public final android.widget.ImageView AwvSrB;
    public final android.widget.ImageView AxsJAY;
    public final C55258xgZ DTwDnp;
    public final C55258xgZ DbNXlk;
    public final LinearLayoutCompat EZpvd;
    public final ConstraintLayout KWHzl;
    public final android.widget.TextView OLrzqt;
    public final ConstraintLayout ORxRYg;
    public final C55239xgG OcIXYQ;
    public final android.widget.TextView QKVWgx;
    public final C55320xhi QOLQEE;
    public final C54154wyx QUSxYX;
    public final android.widget.TextView QfsBiF;
    public final android.widget.TextView RJOkX;
    public final C53028wdk copydefault;
    public final C55258xgZ djBIcL;
    public final android.widget.TextView ejfBZ;
    public final LinearLayoutCompat fARcdN;
    public final C55052xcf fIwbmz;
    public final android.widget.TextView fJNWhG;
    public final android.widget.TextView fetchVPNInfo;
    public final LinearLayoutCompat gEmmrt;
    public final AppCompatImageView gHZMYf;
    public final C47988uAv getFieldNames;
    public final AppCompatImageView getNewProxyInstance;
    public final C53024wdg hDKMBd;
    public final android.view.View isConnected;
    public final C55258xgZ iwGUEr;
    public final android.widget.TextView sSMYrx;
    public final android.widget.TextView uzCIH;
    public final C55258xgZ valueOf;
    public final android.widget.TextView values;
    public final LinearLayoutCompat wlaJM;
    public final AppCompatImageView zLjUOn;
    public final C47988uAv zsXlph;
    public final ConstraintLayout zuBGHE;

    public uSW(java.lang.Object obj, android.view.View view, int i, C53028wdk c53028wdk, ConstraintLayout constraintLayout, android.widget.TextView textView, LinearLayoutCompat linearLayoutCompat, LinearLayoutCompat linearLayoutCompat2, LinearLayoutCompat linearLayoutCompat3, C55258xgZ c55258xgZ, C55258xgZ c55258xgZ2, C55258xgZ c55258xgZ3, android.widget.TextView textView2, android.widget.TextView textView3, android.widget.TextView textView4, C53539wnR c53539wnR, C55258xgZ c55258xgZ4, android.view.View view2, LinearLayoutCompat linearLayoutCompat4, android.widget.TextView textView5, android.widget.TextView textView6, C55052xcf c55052xcf, android.widget.TextView textView7, AppCompatImageView appCompatImageView, C55258xgZ c55258xgZ5, android.widget.TextView textView8, C53024wdg c53024wdg, C47988uAv c47988uAv, AppCompatImageView appCompatImageView2, LinearLayoutCompat linearLayoutCompat5, C47988uAv c47988uAv2, C55239xgG c55239xgG, C55320xhi c55320xhi, AppCompatImageView appCompatImageView3, ConstraintLayout constraintLayout2, android.widget.ImageView imageView, android.widget.ImageView imageView2, android.widget.TextView textView9, C55258xgZ c55258xgZ6, android.widget.TextView textView10, ConstraintLayout constraintLayout3, C55239xgG c55239xgG2, C55320xhi c55320xhi2, android.widget.TextView textView11, android.widget.TextView textView12, C54154wyx c54154wyx) {
        super(obj, view, i);
        this.copydefault = c53028wdk;
        this.KWHzl = constraintLayout;
        this.OLrzqt = textView;
        this.AEQbTJ = linearLayoutCompat;
        this.EZpvd = linearLayoutCompat2;
        this.gEmmrt = linearLayoutCompat3;
        this.valueOf = c55258xgZ;
        this.djBIcL = c55258xgZ2;
        this.AhwBna = c55258xgZ3;
        this.AYXKKw = textView2;
        this.fetchVPNInfo = textView3;
        this.values = textView4;
        this.AkhnZx = c53539wnR;
        this.DbNXlk = c55258xgZ4;
        this.isConnected = view2;
        this.fARcdN = linearLayoutCompat4;
        this.fJNWhG = textView5;
        this.AuCTel = textView6;
        this.fIwbmz = c55052xcf;
        this.ejfBZ = textView7;
        this.getNewProxyInstance = appCompatImageView;
        this.iwGUEr = c55258xgZ5;
        this.uzCIH = textView8;
        this.hDKMBd = c53024wdg;
        this.getFieldNames = c47988uAv;
        this.zLjUOn = appCompatImageView2;
        this.wlaJM = linearLayoutCompat5;
        this.zsXlph = c47988uAv2;
        this.AuCTelauCTel = c55239xgG;
        this.AubY = c55320xhi;
        this.gHZMYf = appCompatImageView3;
        this.zuBGHE = constraintLayout2;
        this.AxsJAY = imageView;
        this.AwvSrB = imageView2;
        this.sSMYrx = textView9;
        this.DTwDnp = c55258xgZ6;
        this.QKVWgx = textView10;
        this.ORxRYg = constraintLayout3;
        this.OcIXYQ = c55239xgG2;
        this.QOLQEE = c55320xhi2;
        this.RJOkX = textView11;
        this.QfsBiF = textView12;
        this.QUSxYX = c54154wyx;
    }
}
