package com.okinc.business.dex.tee.domain.model;

import com.google.api.client.googleapis.media.MediaHttpDownloader;
import com.huawei.hms.support.hianalytics.HiAnalyticsConstant;
import com.okinc.business.dexlogic.bean.ServiceFeeInfo;
import com.okinc.business.dexlogic.bean.ServiceFeeInfo$$serializer;
import com.okinc.business.dexlogic.bean.TraceData;
import com.okinc.business.dexlogic.bean.TraceData$$serializer;
import com.okinc.business.dexlogic.bean.TradeMode;
import com.okinc.business.dexlogic.main.swap.trade.referral.data.ReferralParam;
import com.okinc.business.dexlogic.main.swap.trade.referral.data.ReferralParam$$serializer;
import com.okinc.p2p.api.OtcExtraKeys;
import java.util.List;
import kotlin.Unit;
import kotlin.jvm.internal.Intrinsics;
import kotlinx.serialization.KSerializer;
import kotlinx.serialization.UnknownFieldException;
import kotlinx.serialization.builtins.BuiltinSerializersKt;
import kotlinx.serialization.descriptors.SerialDescriptor;
import kotlinx.serialization.encoding.CompositeDecoder;
import kotlinx.serialization.encoding.CompositeEncoder;
import kotlinx.serialization.encoding.Decoder;
import kotlinx.serialization.encoding.Encoder;
import kotlinx.serialization.internal.BooleanSerializer;
import kotlinx.serialization.internal.GeneratedSerializer;
import kotlinx.serialization.internal.PluginGeneratedSerialDescriptor;
import kotlinx.serialization.internal.SerializationConstructorMarker;
import kotlinx.serialization.internal.StringSerializer;
import org.jetbrains.annotations.NotNull;

/* JADX INFO: loaded from: classes15.dex */
public final /* synthetic */ class TeeMarketPlaceOrderParams$$serializer implements GeneratedSerializer<TeeMarketPlaceOrderParams> {
    public static final int $stable;
    public static final TeeMarketPlaceOrderParams$$serializer INSTANCE;
    private static final SerialDescriptor descriptor;

    /* JADX DEBUG: Don't trust debug lines info. Lines numbers was adjusted: min line is 0 */
    private TeeMarketPlaceOrderParams$$serializer() {
    }

    /* JADX DEBUG: Don't trust debug lines info. Lines numbers was adjusted: min line is 0 */
    @Override // kotlinx.serialization.KSerializer, kotlinx.serialization.SerializationStrategy, kotlinx.serialization.DeserializationStrategy
    public final SerialDescriptor getDescriptor() {
        return descriptor;
    }

    static {
        TeeMarketPlaceOrderParams$$serializer teeMarketPlaceOrderParams$$serializer = new TeeMarketPlaceOrderParams$$serializer();
        INSTANCE = teeMarketPlaceOrderParams$$serializer;
        $stable = 8;
        PluginGeneratedSerialDescriptor pluginGeneratedSerialDescriptor = new PluginGeneratedSerialDescriptor("com.okinc.business.dex.tee.domain.model.TeeMarketPlaceOrderParams", teeMarketPlaceOrderParams$$serializer, 37);
        pluginGeneratedSerialDescriptor.addElement("teeId", true);
        pluginGeneratedSerialDescriptor.addElement("walletAddress", true);
        pluginGeneratedSerialDescriptor.addElement("strategyType", false);
        pluginGeneratedSerialDescriptor.addElement("maxSlippage", true);
        pluginGeneratedSerialDescriptor.addElement("priorityFeeType", true);
        pluginGeneratedSerialDescriptor.addElement("priorityFee", true);
        pluginGeneratedSerialDescriptor.addElement("routerModeType", true);
        pluginGeneratedSerialDescriptor.addElement("tpslConfig", true);
        pluginGeneratedSerialDescriptor.addElement("orderSource", true);
        pluginGeneratedSerialDescriptor.addElement("gasPrice", true);
        pluginGeneratedSerialDescriptor.addElement("enableJito", true);
        pluginGeneratedSerialDescriptor.addElement("gasUsed", true);
        pluginGeneratedSerialDescriptor.addElement("mevInfo", true);
        pluginGeneratedSerialDescriptor.addElement("serviceFeeInfo", true);
        pluginGeneratedSerialDescriptor.addElement("tradeMode", false);
        pluginGeneratedSerialDescriptor.addElement("traceData", true);
        pluginGeneratedSerialDescriptor.addElement(HiAnalyticsConstant.HaKey.BI_KEY_DIRECTION, true);
        pluginGeneratedSerialDescriptor.addElement("chainId", true);
        pluginGeneratedSerialDescriptor.addElement("chainName", true);
        pluginGeneratedSerialDescriptor.addElement("businessType", true);
        pluginGeneratedSerialDescriptor.addElement("fromTokenAddress", true);
        pluginGeneratedSerialDescriptor.addElement("toTokenAddress", true);
        pluginGeneratedSerialDescriptor.addElement(OtcExtraKeys.AMOUNT, true);
        pluginGeneratedSerialDescriptor.addElement("slippageType", true);
        pluginGeneratedSerialDescriptor.addElement("slippage", true);
        pluginGeneratedSerialDescriptor.addElement("userWalletAddress", true);
        pluginGeneratedSerialDescriptor.addElement("accountId", true);
        pluginGeneratedSerialDescriptor.addElement("toAmount", true);
        pluginGeneratedSerialDescriptor.addElement("dexRouterList", true);
        pluginGeneratedSerialDescriptor.addElement("expireTime", true);
        pluginGeneratedSerialDescriptor.addElement("fromTokenDecimals", false);
        pluginGeneratedSerialDescriptor.addElement("toTokenDecimals", false);
        pluginGeneratedSerialDescriptor.addElement("minimumReceived", false);
        pluginGeneratedSerialDescriptor.addElement("quoteId", true);
        pluginGeneratedSerialDescriptor.addElement("refParam", false);
        pluginGeneratedSerialDescriptor.addElement("isOKXPlatform", true);
        pluginGeneratedSerialDescriptor.addElement("isAutoConfirmQuotaRemaining", true);
        descriptor = pluginGeneratedSerialDescriptor;
    }

    @Override // kotlinx.serialization.internal.GeneratedSerializer
    public final KSerializer<?>[] childSerializers() {
        KSerializer<?>[] kSerializerArr = TeeMarketPlaceOrderParams.$childSerializers;
        StringSerializer stringSerializer = StringSerializer.INSTANCE;
        BooleanSerializer booleanSerializer = BooleanSerializer.INSTANCE;
        return new KSerializer[]{stringSerializer, stringSerializer, kSerializerArr[2], BuiltinSerializersKt.getNullable(stringSerializer), stringSerializer, stringSerializer, BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(TpslConfig$$serializer.INSTANCE), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(booleanSerializer), stringSerializer, BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(ServiceFeeInfo$$serializer.INSTANCE), kSerializerArr[14], BuiltinSerializersKt.getNullable(TraceData$$serializer.INSTANCE), stringSerializer, stringSerializer, stringSerializer, stringSerializer, stringSerializer, stringSerializer, stringSerializer, stringSerializer, stringSerializer, stringSerializer, stringSerializer, stringSerializer, kSerializerArr[28], stringSerializer, stringSerializer, stringSerializer, stringSerializer, stringSerializer, ReferralParam$$serializer.INSTANCE, booleanSerializer, booleanSerializer};
    }

    /* JADX DEBUG: Method merged with bridge method: deserialize(Lkotlinx/serialization/encoding/Decoder;)Ljava/lang/Object; */
    @Override // kotlinx.serialization.DeserializationStrategy
    public final TeeMarketPlaceOrderParams deserialize(@NotNull Decoder decoder) {
        String str;
        Boolean bool;
        TpslConfig tpslConfig;
        String str2;
        String str3;
        ReferralParam referralParam;
        String str4;
        String str5;
        String str6;
        String str7;
        String str8;
        String str9;
        String str10;
        String str11;
        String str12;
        String str13;
        String str14;
        String str15;
        boolean zDecodeBooleanElement;
        String str16;
        boolean zDecodeBooleanElement2;
        String str17;
        List list;
        int i;
        StrategyType strategyType;
        TradeMode tradeMode;
        ServiceFeeInfo serviceFeeInfo;
        String str18;
        String str19;
        String str20;
        String str21;
        int i2;
        String str22;
        String str23;
        String str24;
        String str25;
        String str26;
        String str27;
        TraceData traceData;
        ReferralParam referralParam2;
        StrategyType strategyType2;
        String str28;
        String str29;
        String str30;
        String str31;
        String str32;
        String str33;
        StrategyType strategyType3;
        StrategyType strategyType4;
        String str34;
        String str35;
        String str36;
        boolean z;
        ReferralParam referralParam3;
        int i3;
        int i4;
        Intrinsics.checkNotNullParameter(decoder, "");
        SerialDescriptor serialDescriptor = descriptor;
        CompositeDecoder compositeDecoderBeginStructure = decoder.beginStructure(serialDescriptor);
        KSerializer[] kSerializerArr = TeeMarketPlaceOrderParams.$childSerializers;
        if (compositeDecoderBeginStructure.decodeSequentially()) {
            String strDecodeStringElement = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 0);
            String strDecodeStringElement2 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 1);
            StrategyType strategyType5 = (StrategyType) compositeDecoderBeginStructure.decodeSerializableElement(serialDescriptor, 2, kSerializerArr[2], null);
            StringSerializer stringSerializer = StringSerializer.INSTANCE;
            String str37 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 3, stringSerializer, null);
            String strDecodeStringElement3 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 4);
            String strDecodeStringElement4 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 5);
            String str38 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 6, stringSerializer, null);
            TpslConfig tpslConfig2 = (TpslConfig) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 7, TpslConfig$$serializer.INSTANCE, null);
            String str39 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 8, stringSerializer, null);
            String str40 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 9, stringSerializer, null);
            Boolean bool2 = (Boolean) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 10, BooleanSerializer.INSTANCE, null);
            String strDecodeStringElement5 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 11);
            String str41 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 12, stringSerializer, null);
            ServiceFeeInfo serviceFeeInfo2 = (ServiceFeeInfo) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 13, ServiceFeeInfo$$serializer.INSTANCE, null);
            TradeMode tradeMode2 = (TradeMode) compositeDecoderBeginStructure.decodeSerializableElement(serialDescriptor, 14, kSerializerArr[14], null);
            TraceData traceData2 = (TraceData) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 15, TraceData$$serializer.INSTANCE, null);
            String strDecodeStringElement6 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 16);
            String strDecodeStringElement7 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 17);
            String strDecodeStringElement8 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 18);
            String strDecodeStringElement9 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 19);
            String strDecodeStringElement10 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 20);
            String strDecodeStringElement11 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 21);
            String strDecodeStringElement12 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 22);
            String strDecodeStringElement13 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 23);
            String strDecodeStringElement14 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 24);
            String strDecodeStringElement15 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 25);
            String strDecodeStringElement16 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 26);
            String strDecodeStringElement17 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 27);
            List list2 = (List) compositeDecoderBeginStructure.decodeSerializableElement(serialDescriptor, 28, kSerializerArr[28], null);
            String strDecodeStringElement18 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 29);
            String strDecodeStringElement19 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 30);
            String strDecodeStringElement20 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 31);
            String strDecodeStringElement21 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 32);
            String strDecodeStringElement22 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 33);
            str18 = strDecodeStringElement21;
            referralParam = (ReferralParam) compositeDecoderBeginStructure.decodeSerializableElement(serialDescriptor, 34, ReferralParam$$serializer.INSTANCE, null);
            zDecodeBooleanElement = compositeDecoderBeginStructure.decodeBooleanElement(serialDescriptor, 35);
            zDecodeBooleanElement2 = compositeDecoderBeginStructure.decodeBooleanElement(serialDescriptor, 36);
            str = str37;
            str16 = strDecodeStringElement2;
            str22 = strDecodeStringElement17;
            list = list2;
            str8 = strDecodeStringElement20;
            str7 = strDecodeStringElement22;
            str23 = strDecodeStringElement18;
            str19 = strDecodeStringElement19;
            str14 = strDecodeStringElement3;
            str9 = strDecodeStringElement11;
            str20 = strDecodeStringElement12;
            str24 = strDecodeStringElement13;
            str5 = strDecodeStringElement14;
            str27 = strDecodeStringElement15;
            str26 = strDecodeStringElement16;
            str25 = strDecodeStringElement6;
            str17 = strDecodeStringElement7;
            traceData = traceData2;
            str4 = strDecodeStringElement8;
            str10 = strDecodeStringElement9;
            str21 = strDecodeStringElement10;
            tpslConfig = tpslConfig2;
            str11 = str38;
            str13 = strDecodeStringElement4;
            str3 = str41;
            bool = bool2;
            str6 = strDecodeStringElement;
            i2 = 31;
            str15 = strDecodeStringElement5;
            serviceFeeInfo = serviceFeeInfo2;
            strategyType = strategyType5;
            str12 = str39;
            i = -1;
            tradeMode = tradeMode2;
            str2 = str40;
        } else {
            StrategyType strategyType6 = null;
            int i5 = 0;
            boolean z2 = false;
            boolean z3 = false;
            int i6 = 0;
            ReferralParam referralParam4 = null;
            String str42 = null;
            TraceData traceData3 = null;
            String str43 = null;
            TradeMode tradeMode3 = null;
            Boolean bool3 = null;
            ServiceFeeInfo serviceFeeInfo3 = null;
            TpslConfig tpslConfig3 = null;
            String str44 = null;
            String str45 = null;
            String strDecodeStringElement23 = null;
            String strDecodeStringElement24 = null;
            String strDecodeStringElement25 = null;
            String strDecodeStringElement26 = null;
            String strDecodeStringElement27 = null;
            String strDecodeStringElement28 = null;
            String strDecodeStringElement29 = null;
            String strDecodeStringElement30 = null;
            String strDecodeStringElement31 = null;
            String strDecodeStringElement32 = null;
            String strDecodeStringElement33 = null;
            String strDecodeStringElement34 = null;
            String strDecodeStringElement35 = null;
            String strDecodeStringElement36 = null;
            String strDecodeStringElement37 = null;
            String strDecodeStringElement38 = null;
            String str46 = null;
            String strDecodeStringElement39 = null;
            String strDecodeStringElement40 = null;
            String str47 = null;
            String strDecodeStringElement41 = null;
            String strDecodeStringElement42 = null;
            String str48 = null;
            boolean z4 = true;
            List list3 = null;
            while (z4) {
                String str49 = str43;
                int iDecodeElementIndex = compositeDecoderBeginStructure.decodeElementIndex(serialDescriptor);
                switch (iDecodeElementIndex) {
                    case -1:
                        referralParam2 = referralParam4;
                        strategyType2 = strategyType6;
                        str28 = str46;
                        str29 = str42;
                        str30 = str47;
                        Unit unit = Unit.INSTANCE;
                        z4 = false;
                        str31 = str30;
                        str42 = str29;
                        str46 = str28;
                        strategyType6 = strategyType2;
                        referralParam4 = referralParam2;
                        str47 = str31;
                        str43 = str49;
                        break;
                    case 0:
                        referralParam2 = referralParam4;
                        strategyType2 = strategyType6;
                        str28 = str46;
                        str29 = str42;
                        str30 = str47;
                        strDecodeStringElement27 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 0);
                        i5 |= 1;
                        Unit unit2 = Unit.INSTANCE;
                        str31 = str30;
                        str42 = str29;
                        str46 = str28;
                        strategyType6 = strategyType2;
                        referralParam4 = referralParam2;
                        str47 = str31;
                        str43 = str49;
                        break;
                    case 1:
                        referralParam2 = referralParam4;
                        strategyType2 = strategyType6;
                        str28 = str46;
                        String strDecodeStringElement43 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 1);
                        i5 |= 2;
                        Unit unit3 = Unit.INSTANCE;
                        str31 = str47;
                        str48 = strDecodeStringElement43;
                        str42 = str42;
                        str46 = str28;
                        strategyType6 = strategyType2;
                        referralParam4 = referralParam2;
                        str47 = str31;
                        str43 = str49;
                        break;
                    case 2:
                        referralParam2 = referralParam4;
                        str28 = str46;
                        str32 = str42;
                        str33 = str47;
                        strategyType3 = (StrategyType) compositeDecoderBeginStructure.decodeSerializableElement(serialDescriptor, 2, kSerializerArr[2], strategyType6);
                        i5 |= 4;
                        Unit unit4 = Unit.INSTANCE;
                        strategyType2 = strategyType3;
                        str31 = str33;
                        str42 = str32;
                        str46 = str28;
                        strategyType6 = strategyType2;
                        referralParam4 = referralParam2;
                        str47 = str31;
                        str43 = str49;
                        break;
                    case 3:
                        referralParam2 = referralParam4;
                        StrategyType strategyType7 = strategyType6;
                        String str50 = str46;
                        str32 = str42;
                        str28 = str50;
                        String str51 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 3, StringSerializer.INSTANCE, str47);
                        Unit unit5 = Unit.INSTANCE;
                        i5 |= 8;
                        str33 = str51;
                        strategyType3 = strategyType7;
                        strategyType2 = strategyType3;
                        str31 = str33;
                        str42 = str32;
                        str46 = str28;
                        strategyType6 = strategyType2;
                        referralParam4 = referralParam2;
                        str47 = str31;
                        str43 = str49;
                        break;
                    case 4:
                        referralParam2 = referralParam4;
                        strategyType4 = strategyType6;
                        str34 = str46;
                        str35 = str42;
                        strDecodeStringElement40 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 4);
                        i5 |= 16;
                        Unit unit6 = Unit.INSTANCE;
                        str36 = str34;
                        z = z2;
                        z2 = z;
                        str42 = str35;
                        str31 = str47;
                        strategyType2 = strategyType4;
                        str46 = str36;
                        strategyType6 = strategyType2;
                        referralParam4 = referralParam2;
                        str47 = str31;
                        str43 = str49;
                        break;
                    case 5:
                        referralParam2 = referralParam4;
                        strategyType4 = strategyType6;
                        str34 = str46;
                        str35 = str42;
                        strDecodeStringElement39 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 5);
                        i5 |= 32;
                        Unit unit7 = Unit.INSTANCE;
                        str36 = str34;
                        z = z2;
                        z2 = z;
                        str42 = str35;
                        str31 = str47;
                        strategyType2 = strategyType4;
                        str46 = str36;
                        strategyType6 = strategyType2;
                        referralParam4 = referralParam2;
                        str47 = str31;
                        str43 = str49;
                        break;
                    case 6:
                        referralParam2 = referralParam4;
                        strategyType4 = strategyType6;
                        String str52 = str46;
                        str35 = str42;
                        String str53 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 6, StringSerializer.INSTANCE, str52);
                        int i7 = i5 | 64;
                        Unit unit8 = Unit.INSTANCE;
                        i5 = i7;
                        str34 = str53;
                        str36 = str34;
                        z = z2;
                        z2 = z;
                        str42 = str35;
                        str31 = str47;
                        strategyType2 = strategyType4;
                        str46 = str36;
                        strategyType6 = strategyType2;
                        referralParam4 = referralParam2;
                        str47 = str31;
                        str43 = str49;
                        break;
                    case 7:
                        ReferralParam referralParam5 = referralParam4;
                        strategyType4 = strategyType6;
                        tpslConfig3 = (TpslConfig) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 7, TpslConfig$$serializer.INSTANCE, tpslConfig3);
                        i5 |= 128;
                        Unit unit9 = Unit.INSTANCE;
                        referralParam4 = referralParam5;
                        referralParam2 = referralParam4;
                        str36 = str46;
                        z = z2;
                        str35 = str42;
                        z2 = z;
                        str42 = str35;
                        str31 = str47;
                        strategyType2 = strategyType4;
                        str46 = str36;
                        strategyType6 = strategyType2;
                        referralParam4 = referralParam2;
                        str47 = str31;
                        str43 = str49;
                        break;
                    case 8:
                        referralParam3 = referralParam4;
                        strategyType4 = strategyType6;
                        str42 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 8, StringSerializer.INSTANCE, str42);
                        i5 |= 256;
                        Unit unit10 = Unit.INSTANCE;
                        referralParam4 = referralParam3;
                        referralParam2 = referralParam4;
                        str36 = str46;
                        z = z2;
                        str35 = str42;
                        z2 = z;
                        str42 = str35;
                        str31 = str47;
                        strategyType2 = strategyType4;
                        str46 = str36;
                        strategyType6 = strategyType2;
                        referralParam4 = referralParam2;
                        str47 = str31;
                        str43 = str49;
                        break;
                    case 9:
                        referralParam3 = referralParam4;
                        strategyType4 = strategyType6;
                        str44 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 9, StringSerializer.INSTANCE, str44);
                        i5 |= 512;
                        Unit unit102 = Unit.INSTANCE;
                        referralParam4 = referralParam3;
                        referralParam2 = referralParam4;
                        str36 = str46;
                        z = z2;
                        str35 = str42;
                        z2 = z;
                        str42 = str35;
                        str31 = str47;
                        strategyType2 = strategyType4;
                        str46 = str36;
                        strategyType6 = strategyType2;
                        referralParam4 = referralParam2;
                        str47 = str31;
                        str43 = str49;
                        break;
                    case 10:
                        referralParam3 = referralParam4;
                        strategyType4 = strategyType6;
                        bool3 = (Boolean) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 10, BooleanSerializer.INSTANCE, bool3);
                        i5 |= 1024;
                        Unit unit1022 = Unit.INSTANCE;
                        referralParam4 = referralParam3;
                        referralParam2 = referralParam4;
                        str36 = str46;
                        z = z2;
                        str35 = str42;
                        z2 = z;
                        str42 = str35;
                        str31 = str47;
                        strategyType2 = strategyType4;
                        str46 = str36;
                        strategyType6 = strategyType2;
                        referralParam4 = referralParam2;
                        str47 = str31;
                        str43 = str49;
                        break;
                    case 11:
                        referralParam3 = referralParam4;
                        strategyType4 = strategyType6;
                        strDecodeStringElement42 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 11);
                        i5 |= 2048;
                        Unit unit11 = Unit.INSTANCE;
                        referralParam4 = referralParam3;
                        referralParam2 = referralParam4;
                        str36 = str46;
                        z = z2;
                        str35 = str42;
                        z2 = z;
                        str42 = str35;
                        str31 = str47;
                        strategyType2 = strategyType4;
                        str46 = str36;
                        strategyType6 = strategyType2;
                        referralParam4 = referralParam2;
                        str47 = str31;
                        str43 = str49;
                        break;
                    case 12:
                        referralParam3 = referralParam4;
                        strategyType4 = strategyType6;
                        str45 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 12, StringSerializer.INSTANCE, str45);
                        i5 |= 4096;
                        Unit unit10222 = Unit.INSTANCE;
                        referralParam4 = referralParam3;
                        referralParam2 = referralParam4;
                        str36 = str46;
                        z = z2;
                        str35 = str42;
                        z2 = z;
                        str42 = str35;
                        str31 = str47;
                        strategyType2 = strategyType4;
                        str46 = str36;
                        strategyType6 = strategyType2;
                        referralParam4 = referralParam2;
                        str47 = str31;
                        str43 = str49;
                        break;
                    case 13:
                        referralParam3 = referralParam4;
                        strategyType4 = strategyType6;
                        serviceFeeInfo3 = (ServiceFeeInfo) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 13, ServiceFeeInfo$$serializer.INSTANCE, serviceFeeInfo3);
                        i5 |= 8192;
                        Unit unit102222 = Unit.INSTANCE;
                        referralParam4 = referralParam3;
                        referralParam2 = referralParam4;
                        str36 = str46;
                        z = z2;
                        str35 = str42;
                        z2 = z;
                        str42 = str35;
                        str31 = str47;
                        strategyType2 = strategyType4;
                        str46 = str36;
                        strategyType6 = strategyType2;
                        referralParam4 = referralParam2;
                        str47 = str31;
                        str43 = str49;
                        break;
                    case 14:
                        referralParam3 = referralParam4;
                        strategyType4 = strategyType6;
                        tradeMode3 = (TradeMode) compositeDecoderBeginStructure.decodeSerializableElement(serialDescriptor, 14, kSerializerArr[14], tradeMode3);
                        i5 |= 16384;
                        Unit unit1022222 = Unit.INSTANCE;
                        referralParam4 = referralParam3;
                        referralParam2 = referralParam4;
                        str36 = str46;
                        z = z2;
                        str35 = str42;
                        z2 = z;
                        str42 = str35;
                        str31 = str47;
                        strategyType2 = strategyType4;
                        str46 = str36;
                        strategyType6 = strategyType2;
                        referralParam4 = referralParam2;
                        str47 = str31;
                        str43 = str49;
                        break;
                    case 15:
                        strategyType4 = strategyType6;
                        referralParam3 = referralParam4;
                        traceData3 = (TraceData) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 15, TraceData$$serializer.INSTANCE, traceData3);
                        i5 |= 32768;
                        Unit unit12 = Unit.INSTANCE;
                        referralParam4 = referralParam3;
                        referralParam2 = referralParam4;
                        str36 = str46;
                        z = z2;
                        str35 = str42;
                        z2 = z;
                        str42 = str35;
                        str31 = str47;
                        strategyType2 = strategyType4;
                        str46 = str36;
                        strategyType6 = strategyType2;
                        referralParam4 = referralParam2;
                        str47 = str31;
                        str43 = str49;
                        break;
                    case 16:
                        strategyType4 = strategyType6;
                        strDecodeStringElement41 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 16);
                        i5 |= 65536;
                        Unit unit13 = Unit.INSTANCE;
                        referralParam2 = referralParam4;
                        str36 = str46;
                        z = z2;
                        str35 = str42;
                        z2 = z;
                        str42 = str35;
                        str31 = str47;
                        strategyType2 = strategyType4;
                        str46 = str36;
                        strategyType6 = strategyType2;
                        referralParam4 = referralParam2;
                        str47 = str31;
                        str43 = str49;
                        break;
                    case 17:
                        strategyType4 = strategyType6;
                        String strDecodeStringElement44 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 17);
                        i5 |= 131072;
                        Unit unit14 = Unit.INSTANCE;
                        str49 = strDecodeStringElement44;
                        referralParam2 = referralParam4;
                        str36 = str46;
                        z = z2;
                        str35 = str42;
                        z2 = z;
                        str42 = str35;
                        str31 = str47;
                        strategyType2 = strategyType4;
                        str46 = str36;
                        strategyType6 = strategyType2;
                        referralParam4 = referralParam2;
                        str47 = str31;
                        str43 = str49;
                        break;
                    case 18:
                        strategyType4 = strategyType6;
                        strDecodeStringElement23 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 18);
                        i3 = 262144;
                        i5 |= i3;
                        Unit unit15 = Unit.INSTANCE;
                        referralParam2 = referralParam4;
                        str36 = str46;
                        z = z2;
                        str35 = str42;
                        z2 = z;
                        str42 = str35;
                        str31 = str47;
                        strategyType2 = strategyType4;
                        str46 = str36;
                        strategyType6 = strategyType2;
                        referralParam4 = referralParam2;
                        str47 = str31;
                        str43 = str49;
                        break;
                    case 19:
                        strategyType4 = strategyType6;
                        strDecodeStringElement38 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 19);
                        i3 = 524288;
                        i5 |= i3;
                        Unit unit152 = Unit.INSTANCE;
                        referralParam2 = referralParam4;
                        str36 = str46;
                        z = z2;
                        str35 = str42;
                        z2 = z;
                        str42 = str35;
                        str31 = str47;
                        strategyType2 = strategyType4;
                        str46 = str36;
                        strategyType6 = strategyType2;
                        referralParam4 = referralParam2;
                        str47 = str31;
                        str43 = str49;
                        break;
                    case 20:
                        strategyType4 = strategyType6;
                        strDecodeStringElement37 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 20);
                        i3 = 1048576;
                        i5 |= i3;
                        Unit unit1522 = Unit.INSTANCE;
                        referralParam2 = referralParam4;
                        str36 = str46;
                        z = z2;
                        str35 = str42;
                        z2 = z;
                        str42 = str35;
                        str31 = str47;
                        strategyType2 = strategyType4;
                        str46 = str36;
                        strategyType6 = strategyType2;
                        referralParam4 = referralParam2;
                        str47 = str31;
                        str43 = str49;
                        break;
                    case 21:
                        strategyType4 = strategyType6;
                        strDecodeStringElement36 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 21);
                        i3 = 2097152;
                        i5 |= i3;
                        Unit unit15222 = Unit.INSTANCE;
                        referralParam2 = referralParam4;
                        str36 = str46;
                        z = z2;
                        str35 = str42;
                        z2 = z;
                        str42 = str35;
                        str31 = str47;
                        strategyType2 = strategyType4;
                        str46 = str36;
                        strategyType6 = strategyType2;
                        referralParam4 = referralParam2;
                        str47 = str31;
                        str43 = str49;
                        break;
                    case 22:
                        strategyType4 = strategyType6;
                        strDecodeStringElement35 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 22);
                        i3 = 4194304;
                        i5 |= i3;
                        Unit unit152222 = Unit.INSTANCE;
                        referralParam2 = referralParam4;
                        str36 = str46;
                        z = z2;
                        str35 = str42;
                        z2 = z;
                        str42 = str35;
                        str31 = str47;
                        strategyType2 = strategyType4;
                        str46 = str36;
                        strategyType6 = strategyType2;
                        referralParam4 = referralParam2;
                        str47 = str31;
                        str43 = str49;
                        break;
                    case 23:
                        strategyType4 = strategyType6;
                        strDecodeStringElement34 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 23);
                        i3 = 8388608;
                        i5 |= i3;
                        Unit unit1522222 = Unit.INSTANCE;
                        referralParam2 = referralParam4;
                        str36 = str46;
                        z = z2;
                        str35 = str42;
                        z2 = z;
                        str42 = str35;
                        str31 = str47;
                        strategyType2 = strategyType4;
                        str46 = str36;
                        strategyType6 = strategyType2;
                        referralParam4 = referralParam2;
                        str47 = str31;
                        str43 = str49;
                        break;
                    case 24:
                        strategyType4 = strategyType6;
                        strDecodeStringElement24 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 24);
                        i3 = 16777216;
                        i5 |= i3;
                        Unit unit15222222 = Unit.INSTANCE;
                        referralParam2 = referralParam4;
                        str36 = str46;
                        z = z2;
                        str35 = str42;
                        z2 = z;
                        str42 = str35;
                        str31 = str47;
                        strategyType2 = strategyType4;
                        str46 = str36;
                        strategyType6 = strategyType2;
                        referralParam4 = referralParam2;
                        str47 = str31;
                        str43 = str49;
                        break;
                    case 25:
                        strategyType4 = strategyType6;
                        strDecodeStringElement25 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 25);
                        i3 = MediaHttpDownloader.MAXIMUM_CHUNK_SIZE;
                        i5 |= i3;
                        Unit unit152222222 = Unit.INSTANCE;
                        referralParam2 = referralParam4;
                        str36 = str46;
                        z = z2;
                        str35 = str42;
                        z2 = z;
                        str42 = str35;
                        str31 = str47;
                        strategyType2 = strategyType4;
                        str46 = str36;
                        strategyType6 = strategyType2;
                        referralParam4 = referralParam2;
                        str47 = str31;
                        str43 = str49;
                        break;
                    case 26:
                        strategyType4 = strategyType6;
                        strDecodeStringElement33 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 26);
                        i3 = 67108864;
                        i5 |= i3;
                        Unit unit1522222222 = Unit.INSTANCE;
                        referralParam2 = referralParam4;
                        str36 = str46;
                        z = z2;
                        str35 = str42;
                        z2 = z;
                        str42 = str35;
                        str31 = str47;
                        strategyType2 = strategyType4;
                        str46 = str36;
                        strategyType6 = strategyType2;
                        referralParam4 = referralParam2;
                        str47 = str31;
                        str43 = str49;
                        break;
                    case 27:
                        strategyType4 = strategyType6;
                        strDecodeStringElement26 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 27);
                        i3 = 134217728;
                        i5 |= i3;
                        Unit unit15222222222 = Unit.INSTANCE;
                        referralParam2 = referralParam4;
                        str36 = str46;
                        z = z2;
                        str35 = str42;
                        z2 = z;
                        str42 = str35;
                        str31 = str47;
                        strategyType2 = strategyType4;
                        str46 = str36;
                        strategyType6 = strategyType2;
                        referralParam4 = referralParam2;
                        str47 = str31;
                        str43 = str49;
                        break;
                    case 28:
                        strategyType4 = strategyType6;
                        list3 = (List) compositeDecoderBeginStructure.decodeSerializableElement(serialDescriptor, 28, kSerializerArr[28], list3);
                        i3 = 268435456;
                        i5 |= i3;
                        Unit unit152222222222 = Unit.INSTANCE;
                        referralParam2 = referralParam4;
                        str36 = str46;
                        z = z2;
                        str35 = str42;
                        z2 = z;
                        str42 = str35;
                        str31 = str47;
                        strategyType2 = strategyType4;
                        str46 = str36;
                        strategyType6 = strategyType2;
                        referralParam4 = referralParam2;
                        str47 = str31;
                        str43 = str49;
                        break;
                    case 29:
                        strategyType4 = strategyType6;
                        strDecodeStringElement32 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 29);
                        i4 = 536870912;
                        i5 |= i4;
                        Unit unit16 = Unit.INSTANCE;
                        referralParam2 = referralParam4;
                        str36 = str46;
                        z = z2;
                        str35 = str42;
                        z2 = z;
                        str42 = str35;
                        str31 = str47;
                        strategyType2 = strategyType4;
                        str46 = str36;
                        strategyType6 = strategyType2;
                        referralParam4 = referralParam2;
                        str47 = str31;
                        str43 = str49;
                        break;
                    case 30:
                        strategyType4 = strategyType6;
                        strDecodeStringElement31 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 30);
                        i4 = 1073741824;
                        i5 |= i4;
                        Unit unit162 = Unit.INSTANCE;
                        referralParam2 = referralParam4;
                        str36 = str46;
                        z = z2;
                        str35 = str42;
                        z2 = z;
                        str42 = str35;
                        str31 = str47;
                        strategyType2 = strategyType4;
                        str46 = str36;
                        strategyType6 = strategyType2;
                        referralParam4 = referralParam2;
                        str47 = str31;
                        str43 = str49;
                        break;
                    case 31:
                        strategyType4 = strategyType6;
                        strDecodeStringElement30 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 31);
                        i5 |= Integer.MIN_VALUE;
                        Unit unit17 = Unit.INSTANCE;
                        referralParam2 = referralParam4;
                        str36 = str46;
                        z = z2;
                        str35 = str42;
                        z2 = z;
                        str42 = str35;
                        str31 = str47;
                        strategyType2 = strategyType4;
                        str46 = str36;
                        strategyType6 = strategyType2;
                        referralParam4 = referralParam2;
                        str47 = str31;
                        str43 = str49;
                        break;
                    case 32:
                        strategyType4 = strategyType6;
                        strDecodeStringElement29 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 32);
                        i6 |= 1;
                        Unit unit1522222222222 = Unit.INSTANCE;
                        referralParam2 = referralParam4;
                        str36 = str46;
                        z = z2;
                        str35 = str42;
                        z2 = z;
                        str42 = str35;
                        str31 = str47;
                        strategyType2 = strategyType4;
                        str46 = str36;
                        strategyType6 = strategyType2;
                        referralParam4 = referralParam2;
                        str47 = str31;
                        str43 = str49;
                        break;
                    case 33:
                        strategyType4 = strategyType6;
                        strDecodeStringElement28 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 33);
                        i6 |= 2;
                        Unit unit1622 = Unit.INSTANCE;
                        referralParam2 = referralParam4;
                        str36 = str46;
                        z = z2;
                        str35 = str42;
                        z2 = z;
                        str42 = str35;
                        str31 = str47;
                        strategyType2 = strategyType4;
                        str46 = str36;
                        strategyType6 = strategyType2;
                        referralParam4 = referralParam2;
                        str47 = str31;
                        str43 = str49;
                        break;
                    case 34:
                        strategyType4 = strategyType6;
                        referralParam4 = (ReferralParam) compositeDecoderBeginStructure.decodeSerializableElement(serialDescriptor, 34, ReferralParam$$serializer.INSTANCE, referralParam4);
                        i6 |= 4;
                        Unit unit16222 = Unit.INSTANCE;
                        referralParam2 = referralParam4;
                        str36 = str46;
                        z = z2;
                        str35 = str42;
                        z2 = z;
                        str42 = str35;
                        str31 = str47;
                        strategyType2 = strategyType4;
                        str46 = str36;
                        strategyType6 = strategyType2;
                        referralParam4 = referralParam2;
                        str47 = str31;
                        str43 = str49;
                        break;
                    case 35:
                        boolean zDecodeBooleanElement3 = compositeDecoderBeginStructure.decodeBooleanElement(serialDescriptor, 35);
                        i6 |= 8;
                        Unit unit18 = Unit.INSTANCE;
                        referralParam2 = referralParam4;
                        strategyType4 = strategyType6;
                        z = zDecodeBooleanElement3;
                        str36 = str46;
                        str35 = str42;
                        z2 = z;
                        str42 = str35;
                        str31 = str47;
                        strategyType2 = strategyType4;
                        str46 = str36;
                        strategyType6 = strategyType2;
                        referralParam4 = referralParam2;
                        str47 = str31;
                        str43 = str49;
                        break;
                    case 36:
                        boolean zDecodeBooleanElement4 = compositeDecoderBeginStructure.decodeBooleanElement(serialDescriptor, 36);
                        i6 |= 16;
                        Unit unit19 = Unit.INSTANCE;
                        referralParam2 = referralParam4;
                        strategyType4 = strategyType6;
                        z3 = zDecodeBooleanElement4;
                        str36 = str46;
                        z = z2;
                        str35 = str42;
                        z2 = z;
                        str42 = str35;
                        str31 = str47;
                        strategyType2 = strategyType4;
                        str46 = str36;
                        strategyType6 = strategyType2;
                        referralParam4 = referralParam2;
                        str47 = str31;
                        str43 = str49;
                        break;
                    default:
                        throw new UnknownFieldException(iDecodeElementIndex);
                }
            }
            str = str47;
            bool = bool3;
            tpslConfig = tpslConfig3;
            str2 = str44;
            str3 = str45;
            referralParam = referralParam4;
            str4 = strDecodeStringElement23;
            str5 = strDecodeStringElement24;
            str6 = strDecodeStringElement27;
            str7 = strDecodeStringElement28;
            str8 = strDecodeStringElement30;
            str9 = strDecodeStringElement36;
            str10 = strDecodeStringElement38;
            str11 = str46;
            str12 = str42;
            str13 = strDecodeStringElement39;
            str14 = strDecodeStringElement40;
            str15 = strDecodeStringElement42;
            zDecodeBooleanElement = z2;
            str16 = str48;
            zDecodeBooleanElement2 = z3;
            str17 = str43;
            list = list3;
            i = i5;
            strategyType = strategyType6;
            tradeMode = tradeMode3;
            serviceFeeInfo = serviceFeeInfo3;
            str18 = strDecodeStringElement29;
            str19 = strDecodeStringElement31;
            str20 = strDecodeStringElement35;
            str21 = strDecodeStringElement37;
            i2 = i6;
            str22 = strDecodeStringElement26;
            str23 = strDecodeStringElement32;
            str24 = strDecodeStringElement34;
            str25 = strDecodeStringElement41;
            str26 = strDecodeStringElement33;
            str27 = strDecodeStringElement25;
            traceData = traceData3;
        }
        compositeDecoderBeginStructure.endStructure(serialDescriptor);
        return new TeeMarketPlaceOrderParams(i, i2, str6, str16, strategyType, str, str14, str13, str11, tpslConfig, str12, str2, bool, str15, str3, serviceFeeInfo, tradeMode, traceData, str25, str17, str4, str10, str21, str9, str20, str24, str5, str27, str26, str22, list, str23, str19, str8, str18, str7, referralParam, zDecodeBooleanElement, zDecodeBooleanElement2, (SerializationConstructorMarker) null);
    }

    /* JADX DEBUG: Method merged with bridge method: serialize(Lkotlinx/serialization/encoding/Encoder;Ljava/lang/Object;)V */
    @Override // kotlinx.serialization.SerializationStrategy
    public final void serialize(@NotNull Encoder encoder, @NotNull TeeMarketPlaceOrderParams teeMarketPlaceOrderParams) {
        Intrinsics.checkNotNullParameter(encoder, "");
        Intrinsics.checkNotNullParameter(teeMarketPlaceOrderParams, "");
        SerialDescriptor serialDescriptor = descriptor;
        CompositeEncoder compositeEncoderBeginStructure = encoder.beginStructure(serialDescriptor);
        TeeMarketPlaceOrderParams.write$Self$OKDex_dex_impl(teeMarketPlaceOrderParams, compositeEncoderBeginStructure, serialDescriptor);
        compositeEncoderBeginStructure.endStructure(serialDescriptor);
    }
}
