package com.okinc.unify_trade.biz;

import com.google.api.client.googleapis.media.MediaHttpDownloader;
import com.okinc.p2p.api.OtcExtraKeys;
import java.util.ArrayList;
import kotlin.Unit;
import kotlin.jvm.internal.Intrinsics;
import kotlinx.serialization.KSerializer;
import kotlinx.serialization.UnknownFieldException;
import kotlinx.serialization.builtins.BuiltinSerializersKt;
import kotlinx.serialization.descriptors.SerialDescriptor;
import kotlinx.serialization.encoding.CompositeDecoder;
import kotlinx.serialization.encoding.CompositeEncoder;
import kotlinx.serialization.encoding.Decoder;
import kotlinx.serialization.encoding.Encoder;
import kotlinx.serialization.internal.BooleanSerializer;
import kotlinx.serialization.internal.GeneratedSerializer;
import kotlinx.serialization.internal.PluginGeneratedSerialDescriptor;
import kotlinx.serialization.internal.SerializationConstructorMarker;
import kotlinx.serialization.internal.StringSerializer;
import org.jetbrains.annotations.NotNull;

/* JADX INFO: loaded from: classes24.dex */
public final /* synthetic */ class BizTradeOrderReq$$serializer implements GeneratedSerializer<BizTradeOrderReq> {
    public static final int $stable;
    public static final BizTradeOrderReq$$serializer INSTANCE;
    private static final SerialDescriptor descriptor;

    /* JADX DEBUG: Don't trust debug lines info. Lines numbers was adjusted: min line is 0 */
    private BizTradeOrderReq$$serializer() {
    }

    /* JADX DEBUG: Don't trust debug lines info. Lines numbers was adjusted: min line is 0 */
    @Override // kotlinx.serialization.KSerializer, kotlinx.serialization.SerializationStrategy, kotlinx.serialization.DeserializationStrategy
    public final SerialDescriptor getDescriptor() {
        return descriptor;
    }

    static {
        BizTradeOrderReq$$serializer bizTradeOrderReq$$serializer = new BizTradeOrderReq$$serializer();
        INSTANCE = bizTradeOrderReq$$serializer;
        $stable = 8;
        PluginGeneratedSerialDescriptor pluginGeneratedSerialDescriptor = new PluginGeneratedSerialDescriptor("com.okinc.unify_trade.biz.BizTradeOrderReq", bizTradeOrderReq$$serializer, 33);
        pluginGeneratedSerialDescriptor.addElement("instId", false);
        pluginGeneratedSerialDescriptor.addElement("tdMode", false);
        pluginGeneratedSerialDescriptor.addElement(OtcExtraKeys.SIDE, false);
        pluginGeneratedSerialDescriptor.addElement("ordType", false);
        pluginGeneratedSerialDescriptor.addElement("sz", false);
        pluginGeneratedSerialDescriptor.addElement("_feReq", true);
        pluginGeneratedSerialDescriptor.addElement("posSide", true);
        pluginGeneratedSerialDescriptor.addElement("px", true);
        pluginGeneratedSerialDescriptor.addElement("reduceOnly", true);
        pluginGeneratedSerialDescriptor.addElement("bboType", true);
        pluginGeneratedSerialDescriptor.addElement("tpTriggerPx", true);
        pluginGeneratedSerialDescriptor.addElement("tpOrdPx", true);
        pluginGeneratedSerialDescriptor.addElement("slTriggerPx", true);
        pluginGeneratedSerialDescriptor.addElement("slOrdPx", true);
        pluginGeneratedSerialDescriptor.addElement("ccy", true);
        pluginGeneratedSerialDescriptor.addElement("tgtCcy", true);
        pluginGeneratedSerialDescriptor.addElement("tpTriggerPxType", true);
        pluginGeneratedSerialDescriptor.addElement("slTriggerPxType", true);
        pluginGeneratedSerialDescriptor.addElement("isFullPercent", true);
        pluginGeneratedSerialDescriptor.addElement("quickMgnType", true);
        pluginGeneratedSerialDescriptor.addElement("cost", true);
        pluginGeneratedSerialDescriptor.addElement("orderSignType", true);
        pluginGeneratedSerialDescriptor.addElement("attachAlgoOrds", true);
        pluginGeneratedSerialDescriptor.addElement("pxUsd", true);
        pluginGeneratedSerialDescriptor.addElement("pxVol", true);
        pluginGeneratedSerialDescriptor.addElement("isTradeBorrowMode", true);
        pluginGeneratedSerialDescriptor.addElement("banAmend", true);
        pluginGeneratedSerialDescriptor.addElement("assetNeedTransfer", true);
        pluginGeneratedSerialDescriptor.addElement("simpleEarnNeedTransfer", true);
        pluginGeneratedSerialDescriptor.addElement("tradeAvail", true);
        pluginGeneratedSerialDescriptor.addElement("orderValue", true);
        pluginGeneratedSerialDescriptor.addElement("tradeQuoteCcy", true);
        pluginGeneratedSerialDescriptor.addElement("tag", true);
        descriptor = pluginGeneratedSerialDescriptor;
    }

    @Override // kotlinx.serialization.internal.GeneratedSerializer
    public final KSerializer<?>[] childSerializers() {
        KSerializer[] kSerializerArr = BizTradeOrderReq.$childSerializers;
        StringSerializer stringSerializer = StringSerializer.INSTANCE;
        BooleanSerializer booleanSerializer = BooleanSerializer.INSTANCE;
        return new KSerializer[]{stringSerializer, stringSerializer, stringSerializer, stringSerializer, stringSerializer, booleanSerializer, BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(booleanSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(booleanSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(kSerializerArr[22]), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(booleanSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer)};
    }

    /* JADX DEBUG: Method merged with bridge method: deserialize(Lkotlinx/serialization/encoding/Decoder;)Ljava/lang/Object; */
    @Override // kotlinx.serialization.DeserializationStrategy
    public final BizTradeOrderReq deserialize(@NotNull Decoder decoder) {
        String str;
        String str2;
        Boolean bool;
        String str3;
        String str4;
        String str5;
        String str6;
        String str7;
        String str8;
        String str9;
        String str10;
        Boolean bool2;
        String str11;
        String str12;
        ArrayList arrayList;
        String str13;
        String str14;
        String str15;
        boolean z;
        int i;
        String str16;
        String str17;
        String str18;
        String str19;
        Boolean bool3;
        String str20;
        int i2;
        String str21;
        String str22;
        String str23;
        String str24;
        String str25;
        String str26;
        String str27;
        String str28;
        KSerializer[] kSerializerArr;
        String str29;
        String str30;
        String str31;
        String str32;
        String str33;
        String str34;
        String str35;
        String str36;
        String str37;
        String str38;
        Boolean bool4;
        Boolean bool5;
        String str39;
        Boolean bool6;
        String str40;
        String str41;
        String str42;
        int i3;
        int i4;
        String str43;
        int i5;
        int i6;
        Intrinsics.checkNotNullParameter(decoder, "");
        SerialDescriptor serialDescriptor = descriptor;
        CompositeDecoder compositeDecoderBeginStructure = decoder.beginStructure(serialDescriptor);
        KSerializer[] kSerializerArr2 = BizTradeOrderReq.$childSerializers;
        String str44 = null;
        if (compositeDecoderBeginStructure.decodeSequentially()) {
            String strDecodeStringElement = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 0);
            String strDecodeStringElement2 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 1);
            String strDecodeStringElement3 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 2);
            String strDecodeStringElement4 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 3);
            String strDecodeStringElement5 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 4);
            boolean zDecodeBooleanElement = compositeDecoderBeginStructure.decodeBooleanElement(serialDescriptor, 5);
            StringSerializer stringSerializer = StringSerializer.INSTANCE;
            String str45 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 6, stringSerializer, null);
            String str46 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 7, stringSerializer, null);
            BooleanSerializer booleanSerializer = BooleanSerializer.INSTANCE;
            Boolean bool7 = (Boolean) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 8, booleanSerializer, null);
            String str47 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 9, stringSerializer, null);
            String str48 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 10, stringSerializer, null);
            String str49 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 11, stringSerializer, null);
            String str50 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 12, stringSerializer, null);
            String str51 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 13, stringSerializer, null);
            String str52 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 14, stringSerializer, null);
            String str53 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 15, stringSerializer, null);
            String str54 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 16, stringSerializer, null);
            String str55 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 17, stringSerializer, null);
            Boolean bool8 = (Boolean) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 18, booleanSerializer, null);
            String str56 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 19, stringSerializer, null);
            String str57 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 20, stringSerializer, null);
            String str58 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 21, stringSerializer, null);
            ArrayList arrayList2 = (ArrayList) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 22, kSerializerArr2[22], null);
            String str59 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 23, stringSerializer, null);
            String str60 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 24, stringSerializer, null);
            Boolean bool9 = (Boolean) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 25, booleanSerializer, null);
            String str61 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 26, stringSerializer, null);
            String str62 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 27, stringSerializer, null);
            String str63 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 28, stringSerializer, null);
            String str64 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 29, stringSerializer, null);
            String str65 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 30, stringSerializer, null);
            str2 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 31, stringSerializer, null);
            str17 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 32, stringSerializer, null);
            i2 = -1;
            str4 = str61;
            z = zDecodeBooleanElement;
            str9 = str51;
            str21 = str62;
            str22 = str63;
            str20 = str64;
            str19 = str65;
            i = 1;
            str26 = str59;
            str23 = strDecodeStringElement4;
            str16 = str47;
            arrayList = arrayList2;
            str3 = str48;
            str28 = strDecodeStringElement;
            str13 = str58;
            str25 = str60;
            bool = bool8;
            str7 = str53;
            str8 = str52;
            str15 = str56;
            bool2 = bool7;
            str10 = str46;
            str6 = str54;
            str12 = strDecodeStringElement2;
            str18 = str45;
            bool3 = bool9;
            str24 = strDecodeStringElement3;
            str14 = str57;
            str5 = str55;
            str27 = strDecodeStringElement5;
            str = str50;
            str11 = str49;
        } else {
            int i7 = 0;
            boolean zDecodeBooleanElement2 = false;
            int i8 = 0;
            String str66 = null;
            String str67 = null;
            Boolean bool10 = null;
            String str68 = null;
            String str69 = null;
            String str70 = null;
            String str71 = null;
            String str72 = null;
            String str73 = null;
            String str74 = null;
            String strDecodeStringElement6 = null;
            String strDecodeStringElement7 = null;
            String strDecodeStringElement8 = null;
            String str75 = null;
            ArrayList arrayList3 = null;
            String str76 = null;
            String str77 = null;
            String str78 = null;
            String str79 = null;
            String str80 = null;
            String str81 = null;
            String str82 = null;
            String str83 = null;
            String str84 = null;
            String str85 = null;
            Boolean bool11 = null;
            String str86 = null;
            String str87 = null;
            String strDecodeStringElement9 = null;
            String strDecodeStringElement10 = null;
            Boolean bool12 = null;
            boolean z2 = true;
            while (z2) {
                int iDecodeElementIndex = compositeDecoderBeginStructure.decodeElementIndex(serialDescriptor);
                switch (iDecodeElementIndex) {
                    case -1:
                        kSerializerArr = kSerializerArr2;
                        str29 = str66;
                        str30 = str44;
                        str31 = str75;
                        str32 = str79;
                        str33 = str80;
                        str34 = str81;
                        str35 = str82;
                        str36 = str83;
                        str37 = str84;
                        str38 = str85;
                        bool4 = bool11;
                        bool5 = bool12;
                        Unit unit = Unit.INSTANCE;
                        z2 = false;
                        bool6 = bool5;
                        str44 = str30;
                        bool12 = bool6;
                        str75 = str31;
                        str79 = str32;
                        str80 = str33;
                        str81 = str34;
                        str82 = str35;
                        kSerializerArr2 = kSerializerArr;
                        str83 = str36;
                        str84 = str37;
                        bool11 = bool4;
                        str85 = str38;
                        str66 = str29;
                        break;
                    case 0:
                        kSerializerArr = kSerializerArr2;
                        str29 = str66;
                        str30 = str44;
                        str31 = str75;
                        str32 = str79;
                        str33 = str80;
                        str34 = str81;
                        str35 = str82;
                        str36 = str83;
                        str37 = str84;
                        str38 = str85;
                        bool4 = bool11;
                        bool5 = bool12;
                        strDecodeStringElement10 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 0);
                        i7 |= 1;
                        Unit unit2 = Unit.INSTANCE;
                        bool6 = bool5;
                        str44 = str30;
                        bool12 = bool6;
                        str75 = str31;
                        str79 = str32;
                        str80 = str33;
                        str81 = str34;
                        str82 = str35;
                        kSerializerArr2 = kSerializerArr;
                        str83 = str36;
                        str84 = str37;
                        bool11 = bool4;
                        str85 = str38;
                        str66 = str29;
                        break;
                    case 1:
                        kSerializerArr = kSerializerArr2;
                        str29 = str66;
                        str30 = str44;
                        str31 = str75;
                        str32 = str79;
                        str33 = str80;
                        str34 = str81;
                        str35 = str82;
                        str36 = str83;
                        str37 = str84;
                        str38 = str85;
                        bool4 = bool11;
                        str39 = str86;
                        bool5 = bool12;
                        strDecodeStringElement8 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 1);
                        i7 |= 2;
                        Unit unit3 = Unit.INSTANCE;
                        str86 = str39;
                        bool6 = bool5;
                        str44 = str30;
                        bool12 = bool6;
                        str75 = str31;
                        str79 = str32;
                        str80 = str33;
                        str81 = str34;
                        str82 = str35;
                        kSerializerArr2 = kSerializerArr;
                        str83 = str36;
                        str84 = str37;
                        bool11 = bool4;
                        str85 = str38;
                        str66 = str29;
                        break;
                    case 2:
                        kSerializerArr = kSerializerArr2;
                        str29 = str66;
                        str30 = str44;
                        str31 = str75;
                        str32 = str79;
                        str33 = str80;
                        str34 = str81;
                        str35 = str82;
                        str36 = str83;
                        str37 = str84;
                        str38 = str85;
                        bool4 = bool11;
                        str39 = str86;
                        bool5 = bool12;
                        strDecodeStringElement7 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 2);
                        i7 |= 4;
                        Unit unit4 = Unit.INSTANCE;
                        str86 = str39;
                        bool6 = bool5;
                        str44 = str30;
                        bool12 = bool6;
                        str75 = str31;
                        str79 = str32;
                        str80 = str33;
                        str81 = str34;
                        str82 = str35;
                        kSerializerArr2 = kSerializerArr;
                        str83 = str36;
                        str84 = str37;
                        bool11 = bool4;
                        str85 = str38;
                        str66 = str29;
                        break;
                    case 3:
                        kSerializerArr = kSerializerArr2;
                        str29 = str66;
                        str30 = str44;
                        str31 = str75;
                        str32 = str79;
                        str33 = str80;
                        str34 = str81;
                        str35 = str82;
                        str36 = str83;
                        str37 = str84;
                        str38 = str85;
                        bool4 = bool11;
                        str39 = str86;
                        bool5 = bool12;
                        strDecodeStringElement6 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 3);
                        i7 |= 8;
                        Unit unit5 = Unit.INSTANCE;
                        str86 = str39;
                        bool6 = bool5;
                        str44 = str30;
                        bool12 = bool6;
                        str75 = str31;
                        str79 = str32;
                        str80 = str33;
                        str81 = str34;
                        str82 = str35;
                        kSerializerArr2 = kSerializerArr;
                        str83 = str36;
                        str84 = str37;
                        bool11 = bool4;
                        str85 = str38;
                        str66 = str29;
                        break;
                    case 4:
                        kSerializerArr = kSerializerArr2;
                        str29 = str66;
                        str30 = str44;
                        str31 = str75;
                        str32 = str79;
                        str33 = str80;
                        str34 = str81;
                        str35 = str82;
                        str36 = str83;
                        str37 = str84;
                        str38 = str85;
                        bool4 = bool11;
                        str39 = str86;
                        bool5 = bool12;
                        strDecodeStringElement9 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 4);
                        i7 |= 16;
                        Unit unit6 = Unit.INSTANCE;
                        str86 = str39;
                        bool6 = bool5;
                        str44 = str30;
                        bool12 = bool6;
                        str75 = str31;
                        str79 = str32;
                        str80 = str33;
                        str81 = str34;
                        str82 = str35;
                        kSerializerArr2 = kSerializerArr;
                        str83 = str36;
                        str84 = str37;
                        bool11 = bool4;
                        str85 = str38;
                        str66 = str29;
                        break;
                    case 5:
                        kSerializerArr = kSerializerArr2;
                        str29 = str66;
                        str30 = str44;
                        str31 = str75;
                        str32 = str79;
                        str33 = str80;
                        str34 = str81;
                        str35 = str82;
                        str36 = str83;
                        str37 = str84;
                        str38 = str85;
                        bool4 = bool11;
                        str39 = str86;
                        bool5 = bool12;
                        zDecodeBooleanElement2 = compositeDecoderBeginStructure.decodeBooleanElement(serialDescriptor, 5);
                        i7 |= 32;
                        Unit unit7 = Unit.INSTANCE;
                        str86 = str39;
                        bool6 = bool5;
                        str44 = str30;
                        bool12 = bool6;
                        str75 = str31;
                        str79 = str32;
                        str80 = str33;
                        str81 = str34;
                        str82 = str35;
                        kSerializerArr2 = kSerializerArr;
                        str83 = str36;
                        str84 = str37;
                        bool11 = bool4;
                        str85 = str38;
                        str66 = str29;
                        break;
                    case 6:
                        kSerializerArr = kSerializerArr2;
                        str29 = str66;
                        str30 = str44;
                        str31 = str75;
                        str32 = str79;
                        str33 = str80;
                        str34 = str81;
                        str35 = str82;
                        str36 = str83;
                        str37 = str84;
                        str38 = str85;
                        bool4 = bool11;
                        bool5 = bool12;
                        str39 = str86;
                        str87 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 6, StringSerializer.INSTANCE, str87);
                        Unit unit8 = Unit.INSTANCE;
                        i7 |= 64;
                        str86 = str39;
                        bool6 = bool5;
                        str44 = str30;
                        bool12 = bool6;
                        str75 = str31;
                        str79 = str32;
                        str80 = str33;
                        str81 = str34;
                        str82 = str35;
                        kSerializerArr2 = kSerializerArr;
                        str83 = str36;
                        str84 = str37;
                        bool11 = bool4;
                        str85 = str38;
                        str66 = str29;
                        break;
                    case 7:
                        kSerializerArr = kSerializerArr2;
                        str29 = str66;
                        str30 = str44;
                        str31 = str75;
                        str32 = str79;
                        str33 = str80;
                        str34 = str81;
                        str35 = str82;
                        str36 = str83;
                        str37 = str84;
                        str38 = str85;
                        bool5 = bool12;
                        bool4 = bool11;
                        str86 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 7, StringSerializer.INSTANCE, str86);
                        i7 |= 128;
                        Unit unit9 = Unit.INSTANCE;
                        bool6 = bool5;
                        str44 = str30;
                        bool12 = bool6;
                        str75 = str31;
                        str79 = str32;
                        str80 = str33;
                        str81 = str34;
                        str82 = str35;
                        kSerializerArr2 = kSerializerArr;
                        str83 = str36;
                        str84 = str37;
                        bool11 = bool4;
                        str85 = str38;
                        str66 = str29;
                        break;
                    case 8:
                        kSerializerArr = kSerializerArr2;
                        str29 = str66;
                        String str88 = str44;
                        str31 = str75;
                        str32 = str79;
                        str33 = str80;
                        str34 = str81;
                        str35 = str82;
                        str36 = str83;
                        str37 = str84;
                        str38 = str85;
                        bool5 = bool12;
                        str30 = str88;
                        bool11 = (Boolean) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 8, BooleanSerializer.INSTANCE, bool11);
                        i7 |= 256;
                        Unit unit10 = Unit.INSTANCE;
                        bool4 = bool11;
                        bool6 = bool5;
                        str44 = str30;
                        bool12 = bool6;
                        str75 = str31;
                        str79 = str32;
                        str80 = str33;
                        str81 = str34;
                        str82 = str35;
                        kSerializerArr2 = kSerializerArr;
                        str83 = str36;
                        str84 = str37;
                        bool11 = bool4;
                        str85 = str38;
                        str66 = str29;
                        break;
                    case 9:
                        kSerializerArr = kSerializerArr2;
                        str29 = str66;
                        String str89 = str44;
                        str31 = str75;
                        str32 = str79;
                        str33 = str80;
                        str34 = str81;
                        str35 = str82;
                        str36 = str83;
                        str37 = str84;
                        bool5 = bool12;
                        str38 = str85;
                        String str90 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 9, StringSerializer.INSTANCE, str89);
                        i7 |= 512;
                        Unit unit11 = Unit.INSTANCE;
                        str30 = str90;
                        bool4 = bool11;
                        bool6 = bool5;
                        str44 = str30;
                        bool12 = bool6;
                        str75 = str31;
                        str79 = str32;
                        str80 = str33;
                        str81 = str34;
                        str82 = str35;
                        kSerializerArr2 = kSerializerArr;
                        str83 = str36;
                        str84 = str37;
                        bool11 = bool4;
                        str85 = str38;
                        str66 = str29;
                        break;
                    case 10:
                        kSerializerArr = kSerializerArr2;
                        str29 = str66;
                        str30 = str44;
                        str31 = str75;
                        str32 = str79;
                        str33 = str80;
                        str34 = str81;
                        str35 = str82;
                        str36 = str83;
                        str37 = str84;
                        bool5 = bool12;
                        str70 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 10, StringSerializer.INSTANCE, str70);
                        i7 |= 1024;
                        Unit unit12 = Unit.INSTANCE;
                        str38 = str85;
                        bool4 = bool11;
                        bool6 = bool5;
                        str44 = str30;
                        bool12 = bool6;
                        str75 = str31;
                        str79 = str32;
                        str80 = str33;
                        str81 = str34;
                        str82 = str35;
                        kSerializerArr2 = kSerializerArr;
                        str83 = str36;
                        str84 = str37;
                        bool11 = bool4;
                        str85 = str38;
                        str66 = str29;
                        break;
                    case 11:
                        kSerializerArr = kSerializerArr2;
                        str29 = str66;
                        str30 = str44;
                        str31 = str75;
                        str32 = str79;
                        str33 = str80;
                        str34 = str81;
                        str35 = str82;
                        str36 = str83;
                        bool5 = bool12;
                        str37 = str84;
                        str85 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 11, StringSerializer.INSTANCE, str85);
                        i7 |= 2048;
                        Unit unit13 = Unit.INSTANCE;
                        str38 = str85;
                        bool4 = bool11;
                        bool6 = bool5;
                        str44 = str30;
                        bool12 = bool6;
                        str75 = str31;
                        str79 = str32;
                        str80 = str33;
                        str81 = str34;
                        str82 = str35;
                        kSerializerArr2 = kSerializerArr;
                        str83 = str36;
                        str84 = str37;
                        bool11 = bool4;
                        str85 = str38;
                        str66 = str29;
                        break;
                    case 12:
                        kSerializerArr = kSerializerArr2;
                        str29 = str66;
                        str30 = str44;
                        str31 = str75;
                        str32 = str79;
                        str33 = str80;
                        str34 = str81;
                        str35 = str82;
                        bool5 = bool12;
                        str36 = str83;
                        str84 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 12, StringSerializer.INSTANCE, str84);
                        i7 |= 4096;
                        Unit unit14 = Unit.INSTANCE;
                        str37 = str84;
                        str38 = str85;
                        bool4 = bool11;
                        bool6 = bool5;
                        str44 = str30;
                        bool12 = bool6;
                        str75 = str31;
                        str79 = str32;
                        str80 = str33;
                        str81 = str34;
                        str82 = str35;
                        kSerializerArr2 = kSerializerArr;
                        str83 = str36;
                        str84 = str37;
                        bool11 = bool4;
                        str85 = str38;
                        str66 = str29;
                        break;
                    case 13:
                        kSerializerArr = kSerializerArr2;
                        str29 = str66;
                        str30 = str44;
                        str31 = str75;
                        str32 = str79;
                        str33 = str80;
                        str34 = str81;
                        bool5 = bool12;
                        str35 = str82;
                        str83 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 13, StringSerializer.INSTANCE, str83);
                        i7 |= 8192;
                        Unit unit15 = Unit.INSTANCE;
                        str36 = str83;
                        str37 = str84;
                        str38 = str85;
                        bool4 = bool11;
                        bool6 = bool5;
                        str44 = str30;
                        bool12 = bool6;
                        str75 = str31;
                        str79 = str32;
                        str80 = str33;
                        str81 = str34;
                        str82 = str35;
                        kSerializerArr2 = kSerializerArr;
                        str83 = str36;
                        str84 = str37;
                        bool11 = bool4;
                        str85 = str38;
                        str66 = str29;
                        break;
                    case 14:
                        kSerializerArr = kSerializerArr2;
                        str29 = str66;
                        str30 = str44;
                        str31 = str75;
                        str32 = str79;
                        str33 = str80;
                        bool5 = bool12;
                        str34 = str81;
                        str82 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 14, StringSerializer.INSTANCE, str82);
                        i7 |= 16384;
                        Unit unit16 = Unit.INSTANCE;
                        str35 = str82;
                        str36 = str83;
                        str37 = str84;
                        str38 = str85;
                        bool4 = bool11;
                        bool6 = bool5;
                        str44 = str30;
                        bool12 = bool6;
                        str75 = str31;
                        str79 = str32;
                        str80 = str33;
                        str81 = str34;
                        str82 = str35;
                        kSerializerArr2 = kSerializerArr;
                        str83 = str36;
                        str84 = str37;
                        bool11 = bool4;
                        str85 = str38;
                        str66 = str29;
                        break;
                    case 15:
                        kSerializerArr = kSerializerArr2;
                        str29 = str66;
                        str30 = str44;
                        str31 = str75;
                        str32 = str79;
                        bool5 = bool12;
                        str33 = str80;
                        str81 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 15, StringSerializer.INSTANCE, str81);
                        i7 |= 32768;
                        Unit unit17 = Unit.INSTANCE;
                        str34 = str81;
                        str35 = str82;
                        str36 = str83;
                        str37 = str84;
                        str38 = str85;
                        bool4 = bool11;
                        bool6 = bool5;
                        str44 = str30;
                        bool12 = bool6;
                        str75 = str31;
                        str79 = str32;
                        str80 = str33;
                        str81 = str34;
                        str82 = str35;
                        kSerializerArr2 = kSerializerArr;
                        str83 = str36;
                        str84 = str37;
                        bool11 = bool4;
                        str85 = str38;
                        str66 = str29;
                        break;
                    case 16:
                        kSerializerArr = kSerializerArr2;
                        str29 = str66;
                        str30 = str44;
                        str31 = str75;
                        bool5 = bool12;
                        str32 = str79;
                        str80 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 16, StringSerializer.INSTANCE, str80);
                        i7 |= 65536;
                        Unit unit18 = Unit.INSTANCE;
                        str33 = str80;
                        str34 = str81;
                        str35 = str82;
                        str36 = str83;
                        str37 = str84;
                        str38 = str85;
                        bool4 = bool11;
                        bool6 = bool5;
                        str44 = str30;
                        bool12 = bool6;
                        str75 = str31;
                        str79 = str32;
                        str80 = str33;
                        str81 = str34;
                        str82 = str35;
                        kSerializerArr2 = kSerializerArr;
                        str83 = str36;
                        str84 = str37;
                        bool11 = bool4;
                        str85 = str38;
                        str66 = str29;
                        break;
                    case 17:
                        kSerializerArr = kSerializerArr2;
                        str29 = str66;
                        str30 = str44;
                        bool5 = bool12;
                        str31 = str75;
                        String str91 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 17, StringSerializer.INSTANCE, str79);
                        i7 |= 131072;
                        Unit unit19 = Unit.INSTANCE;
                        str32 = str91;
                        str33 = str80;
                        str34 = str81;
                        str35 = str82;
                        str36 = str83;
                        str37 = str84;
                        str38 = str85;
                        bool4 = bool11;
                        bool6 = bool5;
                        str44 = str30;
                        bool12 = bool6;
                        str75 = str31;
                        str79 = str32;
                        str80 = str33;
                        str81 = str34;
                        str82 = str35;
                        kSerializerArr2 = kSerializerArr;
                        str83 = str36;
                        str84 = str37;
                        bool11 = bool4;
                        str85 = str38;
                        str66 = str29;
                        break;
                    case 18:
                        kSerializerArr = kSerializerArr2;
                        str29 = str66;
                        str40 = str44;
                        Boolean bool13 = (Boolean) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 18, BooleanSerializer.INSTANCE, bool12);
                        i7 |= 262144;
                        Unit unit20 = Unit.INSTANCE;
                        str31 = str75;
                        bool6 = bool13;
                        str32 = str79;
                        str33 = str80;
                        str34 = str81;
                        str35 = str82;
                        str36 = str83;
                        str37 = str84;
                        str38 = str85;
                        bool4 = bool11;
                        str44 = str40;
                        bool12 = bool6;
                        str75 = str31;
                        str79 = str32;
                        str80 = str33;
                        str81 = str34;
                        str82 = str35;
                        kSerializerArr2 = kSerializerArr;
                        str83 = str36;
                        str84 = str37;
                        bool11 = bool4;
                        str85 = str38;
                        str66 = str29;
                        break;
                    case 19:
                        kSerializerArr = kSerializerArr2;
                        str41 = str66;
                        str40 = str44;
                        str42 = str75;
                        str78 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 19, StringSerializer.INSTANCE, str78);
                        i3 = 524288;
                        Unit unit21 = Unit.INSTANCE;
                        i4 = i3 | i7;
                        str43 = str42;
                        str66 = str41;
                        str31 = str43;
                        str29 = str66;
                        i7 = i4;
                        str32 = str79;
                        str33 = str80;
                        str34 = str81;
                        str35 = str82;
                        str36 = str83;
                        str37 = str84;
                        str38 = str85;
                        bool4 = bool11;
                        bool6 = bool12;
                        str44 = str40;
                        bool12 = bool6;
                        str75 = str31;
                        str79 = str32;
                        str80 = str33;
                        str81 = str34;
                        str82 = str35;
                        kSerializerArr2 = kSerializerArr;
                        str83 = str36;
                        str84 = str37;
                        bool11 = bool4;
                        str85 = str38;
                        str66 = str29;
                        break;
                    case 20:
                        kSerializerArr = kSerializerArr2;
                        str41 = str66;
                        str40 = str44;
                        str42 = str75;
                        str77 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 20, StringSerializer.INSTANCE, str77);
                        i3 = 1048576;
                        Unit unit212 = Unit.INSTANCE;
                        i4 = i3 | i7;
                        str43 = str42;
                        str66 = str41;
                        str31 = str43;
                        str29 = str66;
                        i7 = i4;
                        str32 = str79;
                        str33 = str80;
                        str34 = str81;
                        str35 = str82;
                        str36 = str83;
                        str37 = str84;
                        str38 = str85;
                        bool4 = bool11;
                        bool6 = bool12;
                        str44 = str40;
                        bool12 = bool6;
                        str75 = str31;
                        str79 = str32;
                        str80 = str33;
                        str81 = str34;
                        str82 = str35;
                        kSerializerArr2 = kSerializerArr;
                        str83 = str36;
                        str84 = str37;
                        bool11 = bool4;
                        str85 = str38;
                        str66 = str29;
                        break;
                    case 21:
                        kSerializerArr = kSerializerArr2;
                        str41 = str66;
                        str40 = str44;
                        str42 = str75;
                        str76 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 21, StringSerializer.INSTANCE, str76);
                        i3 = 2097152;
                        Unit unit2122 = Unit.INSTANCE;
                        i4 = i3 | i7;
                        str43 = str42;
                        str66 = str41;
                        str31 = str43;
                        str29 = str66;
                        i7 = i4;
                        str32 = str79;
                        str33 = str80;
                        str34 = str81;
                        str35 = str82;
                        str36 = str83;
                        str37 = str84;
                        str38 = str85;
                        bool4 = bool11;
                        bool6 = bool12;
                        str44 = str40;
                        bool12 = bool6;
                        str75 = str31;
                        str79 = str32;
                        str80 = str33;
                        str81 = str34;
                        str82 = str35;
                        kSerializerArr2 = kSerializerArr;
                        str83 = str36;
                        str84 = str37;
                        bool11 = bool4;
                        str85 = str38;
                        str66 = str29;
                        break;
                    case 22:
                        str41 = str66;
                        str40 = str44;
                        str42 = str75;
                        kSerializerArr = kSerializerArr2;
                        arrayList3 = (ArrayList) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 22, kSerializerArr2[22], arrayList3);
                        i3 = 4194304;
                        Unit unit21222 = Unit.INSTANCE;
                        i4 = i3 | i7;
                        str43 = str42;
                        str66 = str41;
                        str31 = str43;
                        str29 = str66;
                        i7 = i4;
                        str32 = str79;
                        str33 = str80;
                        str34 = str81;
                        str35 = str82;
                        str36 = str83;
                        str37 = str84;
                        str38 = str85;
                        bool4 = bool11;
                        bool6 = bool12;
                        str44 = str40;
                        bool12 = bool6;
                        str75 = str31;
                        str79 = str32;
                        str80 = str33;
                        str81 = str34;
                        str82 = str35;
                        kSerializerArr2 = kSerializerArr;
                        str83 = str36;
                        str84 = str37;
                        bool11 = bool4;
                        str85 = str38;
                        str66 = str29;
                        break;
                    case 23:
                        str40 = str44;
                        str41 = str66;
                        String str92 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 23, StringSerializer.INSTANCE, str75);
                        i4 = i7 | 8388608;
                        Unit unit22 = Unit.INSTANCE;
                        kSerializerArr = kSerializerArr2;
                        str43 = str92;
                        str66 = str41;
                        str31 = str43;
                        str29 = str66;
                        i7 = i4;
                        str32 = str79;
                        str33 = str80;
                        str34 = str81;
                        str35 = str82;
                        str36 = str83;
                        str37 = str84;
                        str38 = str85;
                        bool4 = bool11;
                        bool6 = bool12;
                        str44 = str40;
                        bool12 = bool6;
                        str75 = str31;
                        str79 = str32;
                        str80 = str33;
                        str81 = str34;
                        str82 = str35;
                        kSerializerArr2 = kSerializerArr;
                        str83 = str36;
                        str84 = str37;
                        bool11 = bool4;
                        str85 = str38;
                        str66 = str29;
                        break;
                    case 24:
                        str40 = str44;
                        str71 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 24, StringSerializer.INSTANCE, str71);
                        i5 = 16777216;
                        i4 = i5 | i7;
                        Unit unit23 = Unit.INSTANCE;
                        kSerializerArr = kSerializerArr2;
                        str43 = str75;
                        str31 = str43;
                        str29 = str66;
                        i7 = i4;
                        str32 = str79;
                        str33 = str80;
                        str34 = str81;
                        str35 = str82;
                        str36 = str83;
                        str37 = str84;
                        str38 = str85;
                        bool4 = bool11;
                        bool6 = bool12;
                        str44 = str40;
                        bool12 = bool6;
                        str75 = str31;
                        str79 = str32;
                        str80 = str33;
                        str81 = str34;
                        str82 = str35;
                        kSerializerArr2 = kSerializerArr;
                        str83 = str36;
                        str84 = str37;
                        bool11 = bool4;
                        str85 = str38;
                        str66 = str29;
                        break;
                    case 25:
                        str40 = str44;
                        bool10 = (Boolean) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 25, BooleanSerializer.INSTANCE, bool10);
                        i6 = MediaHttpDownloader.MAXIMUM_CHUNK_SIZE;
                        i7 |= i6;
                        Unit unit24 = Unit.INSTANCE;
                        kSerializerArr = kSerializerArr2;
                        i4 = i7;
                        str43 = str75;
                        str31 = str43;
                        str29 = str66;
                        i7 = i4;
                        str32 = str79;
                        str33 = str80;
                        str34 = str81;
                        str35 = str82;
                        str36 = str83;
                        str37 = str84;
                        str38 = str85;
                        bool4 = bool11;
                        bool6 = bool12;
                        str44 = str40;
                        bool12 = bool6;
                        str75 = str31;
                        str79 = str32;
                        str80 = str33;
                        str81 = str34;
                        str82 = str35;
                        kSerializerArr2 = kSerializerArr;
                        str83 = str36;
                        str84 = str37;
                        bool11 = bool4;
                        str85 = str38;
                        str66 = str29;
                        break;
                    case 26:
                        str40 = str44;
                        str72 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 26, StringSerializer.INSTANCE, str72);
                        i5 = 67108864;
                        i4 = i5 | i7;
                        Unit unit232 = Unit.INSTANCE;
                        kSerializerArr = kSerializerArr2;
                        str43 = str75;
                        str31 = str43;
                        str29 = str66;
                        i7 = i4;
                        str32 = str79;
                        str33 = str80;
                        str34 = str81;
                        str35 = str82;
                        str36 = str83;
                        str37 = str84;
                        str38 = str85;
                        bool4 = bool11;
                        bool6 = bool12;
                        str44 = str40;
                        bool12 = bool6;
                        str75 = str31;
                        str79 = str32;
                        str80 = str33;
                        str81 = str34;
                        str82 = str35;
                        kSerializerArr2 = kSerializerArr;
                        str83 = str36;
                        str84 = str37;
                        bool11 = bool4;
                        str85 = str38;
                        str66 = str29;
                        break;
                    case 27:
                        str40 = str44;
                        str73 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 27, StringSerializer.INSTANCE, str73);
                        i6 = 134217728;
                        i7 |= i6;
                        Unit unit242 = Unit.INSTANCE;
                        kSerializerArr = kSerializerArr2;
                        i4 = i7;
                        str43 = str75;
                        str31 = str43;
                        str29 = str66;
                        i7 = i4;
                        str32 = str79;
                        str33 = str80;
                        str34 = str81;
                        str35 = str82;
                        str36 = str83;
                        str37 = str84;
                        str38 = str85;
                        bool4 = bool11;
                        bool6 = bool12;
                        str44 = str40;
                        bool12 = bool6;
                        str75 = str31;
                        str79 = str32;
                        str80 = str33;
                        str81 = str34;
                        str82 = str35;
                        kSerializerArr2 = kSerializerArr;
                        str83 = str36;
                        str84 = str37;
                        bool11 = bool4;
                        str85 = str38;
                        str66 = str29;
                        break;
                    case 28:
                        str40 = str44;
                        str74 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 28, StringSerializer.INSTANCE, str74);
                        i5 = 268435456;
                        i4 = i5 | i7;
                        Unit unit2322 = Unit.INSTANCE;
                        kSerializerArr = kSerializerArr2;
                        str43 = str75;
                        str31 = str43;
                        str29 = str66;
                        i7 = i4;
                        str32 = str79;
                        str33 = str80;
                        str34 = str81;
                        str35 = str82;
                        str36 = str83;
                        str37 = str84;
                        str38 = str85;
                        bool4 = bool11;
                        bool6 = bool12;
                        str44 = str40;
                        bool12 = bool6;
                        str75 = str31;
                        str79 = str32;
                        str80 = str33;
                        str81 = str34;
                        str82 = str35;
                        kSerializerArr2 = kSerializerArr;
                        str83 = str36;
                        str84 = str37;
                        bool11 = bool4;
                        str85 = str38;
                        str66 = str29;
                        break;
                    case 29:
                        str40 = str44;
                        str68 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 29, StringSerializer.INSTANCE, str68);
                        i5 = 536870912;
                        i4 = i5 | i7;
                        Unit unit23222 = Unit.INSTANCE;
                        kSerializerArr = kSerializerArr2;
                        str43 = str75;
                        str31 = str43;
                        str29 = str66;
                        i7 = i4;
                        str32 = str79;
                        str33 = str80;
                        str34 = str81;
                        str35 = str82;
                        str36 = str83;
                        str37 = str84;
                        str38 = str85;
                        bool4 = bool11;
                        bool6 = bool12;
                        str44 = str40;
                        bool12 = bool6;
                        str75 = str31;
                        str79 = str32;
                        str80 = str33;
                        str81 = str34;
                        str82 = str35;
                        kSerializerArr2 = kSerializerArr;
                        str83 = str36;
                        str84 = str37;
                        bool11 = bool4;
                        str85 = str38;
                        str66 = str29;
                        break;
                    case 30:
                        str40 = str44;
                        str67 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 30, StringSerializer.INSTANCE, str67);
                        i5 = 1073741824;
                        i4 = i5 | i7;
                        Unit unit232222 = Unit.INSTANCE;
                        kSerializerArr = kSerializerArr2;
                        str43 = str75;
                        str31 = str43;
                        str29 = str66;
                        i7 = i4;
                        str32 = str79;
                        str33 = str80;
                        str34 = str81;
                        str35 = str82;
                        str36 = str83;
                        str37 = str84;
                        str38 = str85;
                        bool4 = bool11;
                        bool6 = bool12;
                        str44 = str40;
                        bool12 = bool6;
                        str75 = str31;
                        str79 = str32;
                        str80 = str33;
                        str81 = str34;
                        str82 = str35;
                        kSerializerArr2 = kSerializerArr;
                        str83 = str36;
                        str84 = str37;
                        bool11 = bool4;
                        str85 = str38;
                        str66 = str29;
                        break;
                    case 31:
                        str40 = str44;
                        str69 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 31, StringSerializer.INSTANCE, str69);
                        i5 = Integer.MIN_VALUE;
                        i4 = i5 | i7;
                        Unit unit2322222 = Unit.INSTANCE;
                        kSerializerArr = kSerializerArr2;
                        str43 = str75;
                        str31 = str43;
                        str29 = str66;
                        i7 = i4;
                        str32 = str79;
                        str33 = str80;
                        str34 = str81;
                        str35 = str82;
                        str36 = str83;
                        str37 = str84;
                        str38 = str85;
                        bool4 = bool11;
                        bool6 = bool12;
                        str44 = str40;
                        bool12 = bool6;
                        str75 = str31;
                        str79 = str32;
                        str80 = str33;
                        str81 = str34;
                        str82 = str35;
                        kSerializerArr2 = kSerializerArr;
                        str83 = str36;
                        str84 = str37;
                        bool11 = bool4;
                        str85 = str38;
                        str66 = str29;
                        break;
                    case 32:
                        str40 = str44;
                        str66 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 32, StringSerializer.INSTANCE, str66);
                        i8 = 1;
                        Unit unit2422 = Unit.INSTANCE;
                        kSerializerArr = kSerializerArr2;
                        i4 = i7;
                        str43 = str75;
                        str31 = str43;
                        str29 = str66;
                        i7 = i4;
                        str32 = str79;
                        str33 = str80;
                        str34 = str81;
                        str35 = str82;
                        str36 = str83;
                        str37 = str84;
                        str38 = str85;
                        bool4 = bool11;
                        bool6 = bool12;
                        str44 = str40;
                        bool12 = bool6;
                        str75 = str31;
                        str79 = str32;
                        str80 = str33;
                        str81 = str34;
                        str82 = str35;
                        kSerializerArr2 = kSerializerArr;
                        str83 = str36;
                        str84 = str37;
                        bool11 = bool4;
                        str85 = str38;
                        str66 = str29;
                        break;
                    default:
                        throw new UnknownFieldException(iDecodeElementIndex);
                }
            }
            String str93 = str75;
            String str94 = str79;
            str = str84;
            str2 = str69;
            bool = bool12;
            str3 = str70;
            str4 = str72;
            str5 = str94;
            str6 = str80;
            str7 = str81;
            str8 = str82;
            str9 = str83;
            str10 = str86;
            bool2 = bool11;
            str11 = str85;
            str12 = strDecodeStringElement8;
            arrayList = arrayList3;
            str13 = str76;
            str14 = str77;
            str15 = str78;
            z = zDecodeBooleanElement2;
            i = i8;
            str16 = str44;
            str17 = str66;
            str18 = str87;
            str19 = str67;
            bool3 = bool10;
            str20 = str68;
            i2 = i7;
            str21 = str73;
            str22 = str74;
            str23 = strDecodeStringElement6;
            str24 = strDecodeStringElement7;
            str25 = str71;
            str26 = str93;
            str27 = strDecodeStringElement9;
            str28 = strDecodeStringElement10;
        }
        compositeDecoderBeginStructure.endStructure(serialDescriptor);
        return new BizTradeOrderReq(i2, i, str28, str12, str24, str23, str27, z, str18, str10, bool2, str16, str3, str11, str, str9, str8, str7, str6, str5, bool, str15, str14, str13, arrayList, str26, str25, bool3, str4, str21, str22, str20, str19, str2, str17, (SerializationConstructorMarker) null);
    }

    /* JADX DEBUG: Method merged with bridge method: serialize(Lkotlinx/serialization/encoding/Encoder;Ljava/lang/Object;)V */
    @Override // kotlinx.serialization.SerializationStrategy
    public final void serialize(@NotNull Encoder encoder, @NotNull BizTradeOrderReq bizTradeOrderReq) {
        Intrinsics.checkNotNullParameter(encoder, "");
        Intrinsics.checkNotNullParameter(bizTradeOrderReq, "");
        SerialDescriptor serialDescriptor = descriptor;
        CompositeEncoder compositeEncoderBeginStructure = encoder.beginStructure(serialDescriptor);
        BizTradeOrderReq.write$Self$OKTradeCore_trade_core(bizTradeOrderReq, compositeEncoderBeginStructure, serialDescriptor);
        compositeEncoderBeginStructure.endStructure(serialDescriptor);
    }
}
