package com.okinc.unify_trade.biz;

import androidx.autofill.HintConstants;
import com.huawei.hms.support.hianalytics.HiAnalyticsConstant;
import java.util.List;
import kotlin.jvm.internal.Intrinsics;
import kotlinx.serialization.KSerializer;
import kotlinx.serialization.UnknownFieldException;
import kotlinx.serialization.builtins.BuiltinSerializersKt;
import kotlinx.serialization.descriptors.SerialDescriptor;
import kotlinx.serialization.encoding.CompositeDecoder;
import kotlinx.serialization.encoding.CompositeEncoder;
import kotlinx.serialization.encoding.Decoder;
import kotlinx.serialization.encoding.Encoder;
import kotlinx.serialization.internal.GeneratedSerializer;
import kotlinx.serialization.internal.PluginGeneratedSerialDescriptor;
import kotlinx.serialization.internal.SerializationConstructorMarker;
import kotlinx.serialization.internal.StringSerializer;
import org.jetbrains.annotations.NotNull;

/* JADX INFO: loaded from: classes19.dex */
public final /* synthetic */ class BotLeadUserOrderPendingModel$$serializer implements GeneratedSerializer<BotLeadUserOrderPendingModel> {
    public static final int $stable;
    public static final BotLeadUserOrderPendingModel$$serializer INSTANCE;
    private static final SerialDescriptor descriptor;

    /* JADX DEBUG: Don't trust debug lines info. Lines numbers was adjusted: min line is 0 */
    private BotLeadUserOrderPendingModel$$serializer() {
    }

    /* JADX DEBUG: Don't trust debug lines info. Lines numbers was adjusted: min line is 0 */
    @Override // kotlinx.serialization.KSerializer, kotlinx.serialization.SerializationStrategy, kotlinx.serialization.DeserializationStrategy
    public final SerialDescriptor getDescriptor() {
        return descriptor;
    }

    static {
        BotLeadUserOrderPendingModel$$serializer botLeadUserOrderPendingModel$$serializer = new BotLeadUserOrderPendingModel$$serializer();
        INSTANCE = botLeadUserOrderPendingModel$$serializer;
        $stable = 8;
        PluginGeneratedSerialDescriptor pluginGeneratedSerialDescriptor = new PluginGeneratedSerialDescriptor("com.okinc.unify_trade.biz.BotLeadUserOrderPendingModel", botLeadUserOrderPendingModel$$serializer, 23);
        pluginGeneratedSerialDescriptor.addElement("cTime", true);
        pluginGeneratedSerialDescriptor.addElement("pTime", true);
        pluginGeneratedSerialDescriptor.addElement("pnlRatio", true);
        pluginGeneratedSerialDescriptor.addElement("curAmt", true);
        pluginGeneratedSerialDescriptor.addElement(HintConstants.AUTOFILL_HINT_USERNAME, true);
        pluginGeneratedSerialDescriptor.addElement("maxDrawdown", true);
        pluginGeneratedSerialDescriptor.addElement("totalPnl", true);
        pluginGeneratedSerialDescriptor.addElement("investmentAmt", true);
        pluginGeneratedSerialDescriptor.addElement("followerCount", true);
        pluginGeneratedSerialDescriptor.addElement("algoId", true);
        pluginGeneratedSerialDescriptor.addElement("instId", true);
        pluginGeneratedSerialDescriptor.addElement("instType", true);
        pluginGeneratedSerialDescriptor.addElement("algoOrdType", true);
        pluginGeneratedSerialDescriptor.addElement("leverage", true);
        pluginGeneratedSerialDescriptor.addElement(HiAnalyticsConstant.HaKey.BI_KEY_DIRECTION, true);
        pluginGeneratedSerialDescriptor.addElement("followerAssets", true);
        pluginGeneratedSerialDescriptor.addElement("profitSharingRatio", true);
        pluginGeneratedSerialDescriptor.addElement("accumulatedProfitSharing", true);
        pluginGeneratedSerialDescriptor.addElement("estimatedProfitSharing", true);
        pluginGeneratedSerialDescriptor.addElement("profitSharingCcy", true);
        pluginGeneratedSerialDescriptor.addElement("profitHistory", true);
        pluginGeneratedSerialDescriptor.addElement("status", true);
        pluginGeneratedSerialDescriptor.addElement("avatar", true);
        descriptor = pluginGeneratedSerialDescriptor;
    }

    @Override // kotlinx.serialization.internal.GeneratedSerializer
    public final KSerializer<?>[] childSerializers() {
        KSerializer[] kSerializerArr = BotLeadUserOrderPendingModel.$childSerializers;
        StringSerializer stringSerializer = StringSerializer.INSTANCE;
        return new KSerializer[]{BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(kSerializerArr[20]), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer)};
    }

    /* JADX DEBUG: Method merged with bridge method: deserialize(Lkotlinx/serialization/encoding/Decoder;)Ljava/lang/Object; */
    @Override // kotlinx.serialization.DeserializationStrategy
    public final BotLeadUserOrderPendingModel deserialize(@NotNull Decoder decoder) {
        int i;
        String str;
        String str2;
        List list;
        String str3;
        String str4;
        String str5;
        String str6;
        String str7;
        String str8;
        String str9;
        String str10;
        String str11;
        String str12;
        String str13;
        String str14;
        String str15;
        String str16;
        String str17;
        String str18;
        String str19;
        String str20;
        String str21;
        String str22;
        String str23;
        int i2;
        int i3;
        KSerializer[] kSerializerArr;
        String str24;
        String str25;
        String str26;
        String str27;
        String str28;
        String str29;
        String str30;
        String str31;
        String str32;
        String str33;
        String str34;
        String str35;
        Intrinsics.checkNotNullParameter(decoder, "");
        SerialDescriptor serialDescriptor = descriptor;
        CompositeDecoder compositeDecoderBeginStructure = decoder.beginStructure(serialDescriptor);
        KSerializer[] kSerializerArr2 = BotLeadUserOrderPendingModel.$childSerializers;
        String str36 = null;
        if (compositeDecoderBeginStructure.decodeSequentially()) {
            StringSerializer stringSerializer = StringSerializer.INSTANCE;
            String str37 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 0, stringSerializer, null);
            String str38 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 1, stringSerializer, null);
            String str39 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 2, stringSerializer, null);
            String str40 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 3, stringSerializer, null);
            String str41 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 4, stringSerializer, null);
            String str42 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 5, stringSerializer, null);
            String str43 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 6, stringSerializer, null);
            String str44 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 7, stringSerializer, null);
            String str45 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 8, stringSerializer, null);
            String str46 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 9, stringSerializer, null);
            String str47 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 10, stringSerializer, null);
            String str48 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 11, stringSerializer, null);
            String str49 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 12, stringSerializer, null);
            String str50 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 13, stringSerializer, null);
            String str51 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 14, stringSerializer, null);
            String str52 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 15, stringSerializer, null);
            String str53 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 16, stringSerializer, null);
            String str54 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 17, stringSerializer, null);
            String str55 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 18, stringSerializer, null);
            String str56 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 19, stringSerializer, null);
            List list2 = (List) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 20, kSerializerArr2[20], null);
            String str57 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 21, stringSerializer, null);
            str3 = str56;
            str4 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 22, stringSerializer, null);
            str2 = str57;
            str13 = str47;
            str12 = str46;
            str19 = str55;
            str18 = str54;
            str15 = str53;
            str16 = str52;
            str22 = str51;
            str20 = str50;
            list = list2;
            str17 = str49;
            str14 = str48;
            str9 = str42;
            i = 8388607;
            str7 = str40;
            str11 = str45;
            str8 = str41;
            str6 = str39;
            str = str37;
            str5 = str38;
            str21 = str44;
            str10 = str43;
        } else {
            int i4 = 0;
            boolean z = true;
            String str58 = null;
            String str59 = null;
            String str60 = null;
            String str61 = null;
            String str62 = null;
            List list3 = null;
            String str63 = null;
            String str64 = null;
            String str65 = null;
            String str66 = null;
            String str67 = null;
            String str68 = null;
            String str69 = null;
            String str70 = null;
            String str71 = null;
            String str72 = null;
            String str73 = null;
            String str74 = null;
            String str75 = null;
            String str76 = null;
            String str77 = null;
            String str78 = null;
            while (z) {
                String str79 = str66;
                int iDecodeElementIndex = compositeDecoderBeginStructure.decodeElementIndex(serialDescriptor);
                switch (iDecodeElementIndex) {
                    case -1:
                        kSerializerArr = kSerializerArr2;
                        str24 = str58;
                        str25 = str68;
                        str26 = str69;
                        str27 = str70;
                        str28 = str71;
                        str29 = str72;
                        str30 = str73;
                        str31 = str74;
                        str32 = str75;
                        str33 = str76;
                        str34 = str77;
                        str35 = str79;
                        z = false;
                        kSerializerArr2 = kSerializerArr;
                        str58 = str24;
                        str75 = str32;
                        str74 = str31;
                        str73 = str30;
                        str72 = str29;
                        str71 = str28;
                        str68 = str25;
                        str69 = str26;
                        str70 = str27;
                        str76 = str33;
                        str77 = str34;
                        str66 = str35;
                        break;
                    case 0:
                        kSerializerArr = kSerializerArr2;
                        str24 = str58;
                        str25 = str68;
                        str26 = str69;
                        str27 = str70;
                        str28 = str71;
                        str29 = str72;
                        str30 = str73;
                        str31 = str74;
                        str33 = str76;
                        str34 = str77;
                        str35 = str79;
                        str32 = str75;
                        i4 |= 1;
                        str78 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 0, StringSerializer.INSTANCE, str78);
                        kSerializerArr2 = kSerializerArr;
                        str58 = str24;
                        str75 = str32;
                        str74 = str31;
                        str73 = str30;
                        str72 = str29;
                        str71 = str28;
                        str68 = str25;
                        str69 = str26;
                        str70 = str27;
                        str76 = str33;
                        str77 = str34;
                        str66 = str35;
                        break;
                    case 1:
                        kSerializerArr = kSerializerArr2;
                        str24 = str58;
                        str25 = str68;
                        str26 = str69;
                        str27 = str70;
                        str28 = str71;
                        str29 = str72;
                        str30 = str73;
                        str33 = str76;
                        str34 = str77;
                        str35 = str79;
                        str31 = str74;
                        i4 |= 2;
                        str32 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 1, StringSerializer.INSTANCE, str75);
                        kSerializerArr2 = kSerializerArr;
                        str58 = str24;
                        str75 = str32;
                        str74 = str31;
                        str73 = str30;
                        str72 = str29;
                        str71 = str28;
                        str68 = str25;
                        str69 = str26;
                        str70 = str27;
                        str76 = str33;
                        str77 = str34;
                        str66 = str35;
                        break;
                    case 2:
                        kSerializerArr = kSerializerArr2;
                        str24 = str58;
                        str25 = str68;
                        str26 = str69;
                        str27 = str70;
                        str28 = str71;
                        str29 = str72;
                        str33 = str76;
                        str34 = str77;
                        str35 = str79;
                        str30 = str73;
                        i4 |= 4;
                        str31 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 2, StringSerializer.INSTANCE, str74);
                        str32 = str75;
                        kSerializerArr2 = kSerializerArr;
                        str58 = str24;
                        str75 = str32;
                        str74 = str31;
                        str73 = str30;
                        str72 = str29;
                        str71 = str28;
                        str68 = str25;
                        str69 = str26;
                        str70 = str27;
                        str76 = str33;
                        str77 = str34;
                        str66 = str35;
                        break;
                    case 3:
                        kSerializerArr = kSerializerArr2;
                        str24 = str58;
                        str25 = str68;
                        str26 = str69;
                        str27 = str70;
                        str28 = str71;
                        str33 = str76;
                        str34 = str77;
                        str35 = str79;
                        str29 = str72;
                        i4 |= 8;
                        str30 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 3, StringSerializer.INSTANCE, str73);
                        str31 = str74;
                        str32 = str75;
                        kSerializerArr2 = kSerializerArr;
                        str58 = str24;
                        str75 = str32;
                        str74 = str31;
                        str73 = str30;
                        str72 = str29;
                        str71 = str28;
                        str68 = str25;
                        str69 = str26;
                        str70 = str27;
                        str76 = str33;
                        str77 = str34;
                        str66 = str35;
                        break;
                    case 4:
                        kSerializerArr = kSerializerArr2;
                        str24 = str58;
                        str25 = str68;
                        str26 = str69;
                        str27 = str70;
                        str33 = str76;
                        str34 = str77;
                        str35 = str79;
                        str28 = str71;
                        i4 |= 16;
                        str29 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 4, StringSerializer.INSTANCE, str72);
                        str30 = str73;
                        str31 = str74;
                        str32 = str75;
                        kSerializerArr2 = kSerializerArr;
                        str58 = str24;
                        str75 = str32;
                        str74 = str31;
                        str73 = str30;
                        str72 = str29;
                        str71 = str28;
                        str68 = str25;
                        str69 = str26;
                        str70 = str27;
                        str76 = str33;
                        str77 = str34;
                        str66 = str35;
                        break;
                    case 5:
                        kSerializerArr = kSerializerArr2;
                        str24 = str58;
                        str26 = str69;
                        str27 = str70;
                        str33 = str76;
                        str34 = str77;
                        str35 = str79;
                        str25 = str68;
                        i4 |= 32;
                        str28 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 5, StringSerializer.INSTANCE, str71);
                        str29 = str72;
                        str30 = str73;
                        str31 = str74;
                        str32 = str75;
                        kSerializerArr2 = kSerializerArr;
                        str58 = str24;
                        str75 = str32;
                        str74 = str31;
                        str73 = str30;
                        str72 = str29;
                        str71 = str28;
                        str68 = str25;
                        str69 = str26;
                        str70 = str27;
                        str76 = str33;
                        str77 = str34;
                        str66 = str35;
                        break;
                    case 6:
                        kSerializerArr = kSerializerArr2;
                        str24 = str58;
                        str27 = str70;
                        str33 = str76;
                        str34 = str77;
                        str35 = str79;
                        str26 = str69;
                        i4 |= 64;
                        str25 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 6, StringSerializer.INSTANCE, str68);
                        str28 = str71;
                        str29 = str72;
                        str30 = str73;
                        str31 = str74;
                        str32 = str75;
                        kSerializerArr2 = kSerializerArr;
                        str58 = str24;
                        str75 = str32;
                        str74 = str31;
                        str73 = str30;
                        str72 = str29;
                        str71 = str28;
                        str68 = str25;
                        str69 = str26;
                        str70 = str27;
                        str76 = str33;
                        str77 = str34;
                        str66 = str35;
                        break;
                    case 7:
                        kSerializerArr = kSerializerArr2;
                        str24 = str58;
                        str33 = str76;
                        str34 = str77;
                        str35 = str79;
                        str27 = str70;
                        i4 |= 128;
                        str26 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 7, StringSerializer.INSTANCE, str69);
                        str25 = str68;
                        str28 = str71;
                        str29 = str72;
                        str30 = str73;
                        str31 = str74;
                        str32 = str75;
                        kSerializerArr2 = kSerializerArr;
                        str58 = str24;
                        str75 = str32;
                        str74 = str31;
                        str73 = str30;
                        str72 = str29;
                        str71 = str28;
                        str68 = str25;
                        str69 = str26;
                        str70 = str27;
                        str76 = str33;
                        str77 = str34;
                        str66 = str35;
                        break;
                    case 8:
                        kSerializerArr = kSerializerArr2;
                        str24 = str58;
                        str34 = str77;
                        str35 = str79;
                        str33 = str76;
                        i4 |= 256;
                        str27 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 8, StringSerializer.INSTANCE, str70);
                        str25 = str68;
                        str26 = str69;
                        str28 = str71;
                        str29 = str72;
                        str30 = str73;
                        str31 = str74;
                        str32 = str75;
                        kSerializerArr2 = kSerializerArr;
                        str58 = str24;
                        str75 = str32;
                        str74 = str31;
                        str73 = str30;
                        str72 = str29;
                        str71 = str28;
                        str68 = str25;
                        str69 = str26;
                        str70 = str27;
                        str76 = str33;
                        str77 = str34;
                        str66 = str35;
                        break;
                    case 9:
                        kSerializerArr = kSerializerArr2;
                        str24 = str58;
                        str35 = str79;
                        str34 = str77;
                        i4 |= 512;
                        str33 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 9, StringSerializer.INSTANCE, str76);
                        str25 = str68;
                        str26 = str69;
                        str27 = str70;
                        str28 = str71;
                        str29 = str72;
                        str30 = str73;
                        str31 = str74;
                        str32 = str75;
                        kSerializerArr2 = kSerializerArr;
                        str58 = str24;
                        str75 = str32;
                        str74 = str31;
                        str73 = str30;
                        str72 = str29;
                        str71 = str28;
                        str68 = str25;
                        str69 = str26;
                        str70 = str27;
                        str76 = str33;
                        str77 = str34;
                        str66 = str35;
                        break;
                    case 10:
                        kSerializerArr = kSerializerArr2;
                        str24 = str58;
                        str35 = str79;
                        i4 |= 1024;
                        str34 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 10, StringSerializer.INSTANCE, str77);
                        str25 = str68;
                        str26 = str69;
                        str27 = str70;
                        str28 = str71;
                        str29 = str72;
                        str30 = str73;
                        str31 = str74;
                        str32 = str75;
                        str33 = str76;
                        kSerializerArr2 = kSerializerArr;
                        str58 = str24;
                        str75 = str32;
                        str74 = str31;
                        str73 = str30;
                        str72 = str29;
                        str71 = str28;
                        str68 = str25;
                        str69 = str26;
                        str70 = str27;
                        str76 = str33;
                        str77 = str34;
                        str66 = str35;
                        break;
                    case 11:
                        str66 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 11, StringSerializer.INSTANCE, str79);
                        i4 |= 2048;
                        kSerializerArr2 = kSerializerArr2;
                        str58 = str58;
                        break;
                    case 12:
                        str62 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 12, StringSerializer.INSTANCE, str62);
                        i4 |= 4096;
                        kSerializerArr2 = kSerializerArr2;
                        str66 = str79;
                        break;
                    case 13:
                        str23 = str62;
                        str58 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 13, StringSerializer.INSTANCE, str58);
                        i4 |= 8192;
                        str66 = str79;
                        str62 = str23;
                        break;
                    case 14:
                        str23 = str62;
                        i4 |= 16384;
                        str67 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 14, StringSerializer.INSTANCE, str67);
                        str66 = str79;
                        str62 = str23;
                        break;
                    case 15:
                        str23 = str62;
                        str61 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 15, StringSerializer.INSTANCE, str61);
                        i2 = 32768;
                        i4 |= i2;
                        str66 = str79;
                        str62 = str23;
                        break;
                    case 16:
                        str23 = str62;
                        str59 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 16, StringSerializer.INSTANCE, str59);
                        i2 = 65536;
                        i4 |= i2;
                        str66 = str79;
                        str62 = str23;
                        break;
                    case 17:
                        str23 = str62;
                        str64 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 17, StringSerializer.INSTANCE, str64);
                        i2 = 131072;
                        i4 |= i2;
                        str66 = str79;
                        str62 = str23;
                        break;
                    case 18:
                        str23 = str62;
                        str65 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 18, StringSerializer.INSTANCE, str65);
                        i2 = 262144;
                        i4 |= i2;
                        str66 = str79;
                        str62 = str23;
                        break;
                    case 19:
                        str23 = str62;
                        str63 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 19, StringSerializer.INSTANCE, str63);
                        i2 = 524288;
                        i4 |= i2;
                        str66 = str79;
                        str62 = str23;
                        break;
                    case 20:
                        str23 = str62;
                        list3 = (List) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 20, kSerializerArr2[20], list3);
                        i2 = 1048576;
                        i4 |= i2;
                        str66 = str79;
                        str62 = str23;
                        break;
                    case 21:
                        str23 = str62;
                        str60 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 21, StringSerializer.INSTANCE, str60);
                        i3 = 2097152;
                        i4 |= i3;
                        str66 = str79;
                        str62 = str23;
                        break;
                    case 22:
                        str23 = str62;
                        str36 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 22, StringSerializer.INSTANCE, str36);
                        i3 = 4194304;
                        i4 |= i3;
                        str66 = str79;
                        str62 = str23;
                        break;
                    default:
                        throw new UnknownFieldException(iDecodeElementIndex);
                }
            }
            String str80 = str68;
            String str81 = str69;
            String str82 = str70;
            String str83 = str71;
            i = i4;
            str = str78;
            str2 = str60;
            list = list3;
            str3 = str63;
            str4 = str36;
            str5 = str75;
            str6 = str74;
            str7 = str73;
            str8 = str72;
            str9 = str83;
            str10 = str80;
            str11 = str82;
            str12 = str76;
            str13 = str77;
            str14 = str66;
            str15 = str59;
            str16 = str61;
            str17 = str62;
            str18 = str64;
            str19 = str65;
            str20 = str58;
            str21 = str81;
            str22 = str67;
        }
        compositeDecoderBeginStructure.endStructure(serialDescriptor);
        return new BotLeadUserOrderPendingModel(i, str, str5, str6, str7, str8, str9, str10, str21, str11, str12, str13, str14, str17, str20, str22, str16, str15, str18, str19, str3, list, str2, str4, (SerializationConstructorMarker) null);
    }

    /* JADX DEBUG: Method merged with bridge method: serialize(Lkotlinx/serialization/encoding/Encoder;Ljava/lang/Object;)V */
    @Override // kotlinx.serialization.SerializationStrategy
    public final void serialize(@NotNull Encoder encoder, @NotNull BotLeadUserOrderPendingModel botLeadUserOrderPendingModel) {
        Intrinsics.checkNotNullParameter(encoder, "");
        Intrinsics.checkNotNullParameter(botLeadUserOrderPendingModel, "");
        SerialDescriptor serialDescriptor = descriptor;
        CompositeEncoder compositeEncoderBeginStructure = encoder.beginStructure(serialDescriptor);
        BotLeadUserOrderPendingModel.write$Self$OKTradeCore_trade_core(botLeadUserOrderPendingModel, compositeEncoderBeginStructure, serialDescriptor);
        compositeEncoderBeginStructure.endStructure(serialDescriptor);
    }
}
