package com.okinc.unify_trade.biz;

import com.huawei.hms.support.hianalytics.HiAnalyticsConstant;
import kotlin.jvm.internal.Intrinsics;
import kotlinx.serialization.KSerializer;
import kotlinx.serialization.UnknownFieldException;
import kotlinx.serialization.builtins.BuiltinSerializersKt;
import kotlinx.serialization.descriptors.SerialDescriptor;
import kotlinx.serialization.encoding.CompositeDecoder;
import kotlinx.serialization.encoding.CompositeEncoder;
import kotlinx.serialization.encoding.Decoder;
import kotlinx.serialization.encoding.Encoder;
import kotlinx.serialization.internal.GeneratedSerializer;
import kotlinx.serialization.internal.PluginGeneratedSerialDescriptor;
import kotlinx.serialization.internal.SerializationConstructorMarker;
import kotlinx.serialization.internal.StringSerializer;
import org.jetbrains.annotations.NotNull;

/* JADX INFO: loaded from: classes19.dex */
public final /* synthetic */ class BotLeadUserOrderHistoryModel$$serializer implements GeneratedSerializer<BotLeadUserOrderHistoryModel> {
    public static final int $stable;
    public static final BotLeadUserOrderHistoryModel$$serializer INSTANCE;
    private static final SerialDescriptor descriptor;

    /* JADX DEBUG: Don't trust debug lines info. Lines numbers was adjusted: min line is 0 */
    private BotLeadUserOrderHistoryModel$$serializer() {
    }

    /* JADX DEBUG: Don't trust debug lines info. Lines numbers was adjusted: min line is 0 */
    @Override // kotlinx.serialization.KSerializer, kotlinx.serialization.SerializationStrategy, kotlinx.serialization.DeserializationStrategy
    public final SerialDescriptor getDescriptor() {
        return descriptor;
    }

    static {
        BotLeadUserOrderHistoryModel$$serializer botLeadUserOrderHistoryModel$$serializer = new BotLeadUserOrderHistoryModel$$serializer();
        INSTANCE = botLeadUserOrderHistoryModel$$serializer;
        $stable = 8;
        PluginGeneratedSerialDescriptor pluginGeneratedSerialDescriptor = new PluginGeneratedSerialDescriptor("com.okinc.unify_trade.biz.BotLeadUserOrderHistoryModel", botLeadUserOrderHistoryModel$$serializer, 21);
        pluginGeneratedSerialDescriptor.addElement("cTime", true);
        pluginGeneratedSerialDescriptor.addElement("uTime", true);
        pluginGeneratedSerialDescriptor.addElement("pnlRatio", true);
        pluginGeneratedSerialDescriptor.addElement("maxDrawdown", true);
        pluginGeneratedSerialDescriptor.addElement("totalPnl", true);
        pluginGeneratedSerialDescriptor.addElement("investmentAmt", true);
        pluginGeneratedSerialDescriptor.addElement("followerCount", true);
        pluginGeneratedSerialDescriptor.addElement("algoId", true);
        pluginGeneratedSerialDescriptor.addElement("instId", true);
        pluginGeneratedSerialDescriptor.addElement("instType", true);
        pluginGeneratedSerialDescriptor.addElement("algoOrdType", true);
        pluginGeneratedSerialDescriptor.addElement("leverage", true);
        pluginGeneratedSerialDescriptor.addElement(HiAnalyticsConstant.HaKey.BI_KEY_DIRECTION, true);
        pluginGeneratedSerialDescriptor.addElement("followerAssets", true);
        pluginGeneratedSerialDescriptor.addElement("profitSharingRatio", true);
        pluginGeneratedSerialDescriptor.addElement("accumulatedProfitSharing", true);
        pluginGeneratedSerialDescriptor.addElement("profitSharingCcy", true);
        pluginGeneratedSerialDescriptor.addElement("runPx", true);
        pluginGeneratedSerialDescriptor.addElement("completedCycles", true);
        pluginGeneratedSerialDescriptor.addElement("trailingUpConfig", true);
        pluginGeneratedSerialDescriptor.addElement("trailingDownConfig", true);
        descriptor = pluginGeneratedSerialDescriptor;
    }

    @Override // kotlinx.serialization.internal.GeneratedSerializer
    public final KSerializer<?>[] childSerializers() {
        StringSerializer stringSerializer = StringSerializer.INSTANCE;
        KSerializer nullable = BuiltinSerializersKt.getNullable(stringSerializer);
        KSerializer nullable2 = BuiltinSerializersKt.getNullable(stringSerializer);
        KSerializer nullable3 = BuiltinSerializersKt.getNullable(stringSerializer);
        KSerializer nullable4 = BuiltinSerializersKt.getNullable(stringSerializer);
        KSerializer nullable5 = BuiltinSerializersKt.getNullable(stringSerializer);
        KSerializer nullable6 = BuiltinSerializersKt.getNullable(stringSerializer);
        KSerializer nullable7 = BuiltinSerializersKt.getNullable(stringSerializer);
        KSerializer nullable8 = BuiltinSerializersKt.getNullable(stringSerializer);
        KSerializer nullable9 = BuiltinSerializersKt.getNullable(stringSerializer);
        KSerializer nullable10 = BuiltinSerializersKt.getNullable(stringSerializer);
        KSerializer nullable11 = BuiltinSerializersKt.getNullable(stringSerializer);
        KSerializer nullable12 = BuiltinSerializersKt.getNullable(stringSerializer);
        KSerializer nullable13 = BuiltinSerializersKt.getNullable(stringSerializer);
        KSerializer nullable14 = BuiltinSerializersKt.getNullable(stringSerializer);
        KSerializer nullable15 = BuiltinSerializersKt.getNullable(stringSerializer);
        KSerializer nullable16 = BuiltinSerializersKt.getNullable(stringSerializer);
        KSerializer nullable17 = BuiltinSerializersKt.getNullable(stringSerializer);
        KSerializer nullable18 = BuiltinSerializersKt.getNullable(stringSerializer);
        KSerializer nullable19 = BuiltinSerializersKt.getNullable(stringSerializer);
        TrailingConfig$$serializer trailingConfig$$serializer = TrailingConfig$$serializer.INSTANCE;
        return new KSerializer[]{nullable, nullable2, nullable3, nullable4, nullable5, nullable6, nullable7, nullable8, nullable9, nullable10, nullable11, nullable12, nullable13, nullable14, nullable15, nullable16, nullable17, nullable18, nullable19, BuiltinSerializersKt.getNullable(trailingConfig$$serializer), BuiltinSerializersKt.getNullable(trailingConfig$$serializer)};
    }

    /* JADX DEBUG: Method merged with bridge method: deserialize(Lkotlinx/serialization/encoding/Decoder;)Ljava/lang/Object; */
    @Override // kotlinx.serialization.DeserializationStrategy
    public final BotLeadUserOrderHistoryModel deserialize(@NotNull Decoder decoder) {
        int i;
        String str;
        String str2;
        String str3;
        String str4;
        String str5;
        String str6;
        TrailingConfig trailingConfig;
        TrailingConfig trailingConfig2;
        String str7;
        String str8;
        String str9;
        String str10;
        String str11;
        String str12;
        String str13;
        String str14;
        String str15;
        String str16;
        String str17;
        String str18;
        String str19;
        String str20;
        String str21;
        String str22;
        String str23;
        TrailingConfig trailingConfig3;
        String str24;
        int i2;
        TrailingConfig trailingConfig4;
        String str25;
        String str26;
        String str27;
        String str28;
        String str29;
        String str30;
        String str31;
        String str32;
        String str33;
        String str34;
        String str35;
        String str36;
        String str37;
        Intrinsics.checkNotNullParameter(decoder, "");
        SerialDescriptor serialDescriptor = descriptor;
        CompositeDecoder compositeDecoderBeginStructure = decoder.beginStructure(serialDescriptor);
        if (compositeDecoderBeginStructure.decodeSequentially()) {
            StringSerializer stringSerializer = StringSerializer.INSTANCE;
            String str38 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 0, stringSerializer, null);
            String str39 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 1, stringSerializer, null);
            String str40 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 2, stringSerializer, null);
            String str41 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 3, stringSerializer, null);
            String str42 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 4, stringSerializer, null);
            String str43 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 5, stringSerializer, null);
            String str44 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 6, stringSerializer, null);
            String str45 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 7, stringSerializer, null);
            String str46 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 8, stringSerializer, null);
            String str47 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 9, stringSerializer, null);
            String str48 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 10, stringSerializer, null);
            String str49 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 11, stringSerializer, null);
            str5 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 12, stringSerializer, null);
            String str50 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 13, stringSerializer, null);
            String str51 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 14, stringSerializer, null);
            String str52 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 15, stringSerializer, null);
            String str53 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 16, stringSerializer, null);
            String str54 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 17, stringSerializer, null);
            String str55 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 18, stringSerializer, null);
            TrailingConfig$$serializer trailingConfig$$serializer = TrailingConfig$$serializer.INSTANCE;
            trailingConfig = (TrailingConfig) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 19, trailingConfig$$serializer, null);
            trailingConfig2 = (TrailingConfig) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 20, trailingConfig$$serializer, null);
            i = 2097151;
            str6 = str55;
            str15 = str54;
            str14 = str53;
            str13 = str52;
            str12 = str51;
            str2 = str46;
            str10 = str48;
            str9 = str47;
            str = str45;
            str4 = str44;
            str7 = str41;
            str8 = str42;
            str19 = str40;
            str16 = str39;
            str17 = str49;
            str11 = str38;
            str3 = str43;
            str18 = str50;
        } else {
            boolean z = true;
            String str56 = null;
            String str57 = null;
            String str58 = null;
            String str59 = null;
            String str60 = null;
            String str61 = null;
            String str62 = null;
            String str63 = null;
            String str64 = null;
            String str65 = null;
            TrailingConfig trailingConfig5 = null;
            String str66 = null;
            String str67 = null;
            String str68 = null;
            String str69 = null;
            String str70 = null;
            String str71 = null;
            String str72 = null;
            String str73 = null;
            String str74 = null;
            i = 0;
            TrailingConfig trailingConfig6 = null;
            while (z) {
                int iDecodeElementIndex = compositeDecoderBeginStructure.decodeElementIndex(serialDescriptor);
                switch (iDecodeElementIndex) {
                    case -1:
                        trailingConfig4 = trailingConfig6;
                        str25 = str56;
                        str26 = str59;
                        str27 = str61;
                        str28 = str66;
                        str29 = str67;
                        str30 = str68;
                        str31 = str69;
                        str32 = str71;
                        str33 = str73;
                        str34 = str74;
                        str35 = str70;
                        z = false;
                        str74 = str34;
                        trailingConfig6 = trailingConfig4;
                        str69 = str31;
                        str68 = str30;
                        str56 = str25;
                        str67 = str29;
                        str73 = str33;
                        str70 = str35;
                        str61 = str27;
                        str59 = str26;
                        str71 = str32;
                        str66 = str28;
                        break;
                    case 0:
                        trailingConfig4 = trailingConfig6;
                        str25 = str56;
                        str26 = str59;
                        str27 = str61;
                        str28 = str66;
                        str29 = str67;
                        str30 = str68;
                        str31 = str69;
                        String str75 = str71;
                        str33 = str73;
                        str34 = str74;
                        str35 = str70;
                        str32 = str75;
                        str72 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 0, StringSerializer.INSTANCE, str72);
                        i |= 1;
                        str74 = str34;
                        trailingConfig6 = trailingConfig4;
                        str69 = str31;
                        str68 = str30;
                        str56 = str25;
                        str67 = str29;
                        str73 = str33;
                        str70 = str35;
                        str61 = str27;
                        str59 = str26;
                        str71 = str32;
                        str66 = str28;
                        break;
                    case 1:
                        trailingConfig4 = trailingConfig6;
                        str25 = str56;
                        str26 = str59;
                        str27 = str61;
                        str28 = str66;
                        str29 = str67;
                        str30 = str68;
                        str31 = str69;
                        str33 = str73;
                        str34 = str74;
                        String str76 = str71;
                        str35 = str70;
                        i |= 2;
                        str32 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 1, StringSerializer.INSTANCE, str76);
                        str74 = str34;
                        trailingConfig6 = trailingConfig4;
                        str69 = str31;
                        str68 = str30;
                        str56 = str25;
                        str67 = str29;
                        str73 = str33;
                        str70 = str35;
                        str61 = str27;
                        str59 = str26;
                        str71 = str32;
                        str66 = str28;
                        break;
                    case 2:
                        trailingConfig4 = trailingConfig6;
                        str25 = str56;
                        str26 = str59;
                        str27 = str61;
                        str28 = str66;
                        str29 = str67;
                        str30 = str68;
                        str33 = str73;
                        str34 = str74;
                        str31 = str69;
                        str70 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 2, StringSerializer.INSTANCE, str70);
                        i |= 4;
                        str32 = str71;
                        str35 = str70;
                        str74 = str34;
                        trailingConfig6 = trailingConfig4;
                        str69 = str31;
                        str68 = str30;
                        str56 = str25;
                        str67 = str29;
                        str73 = str33;
                        str70 = str35;
                        str61 = str27;
                        str59 = str26;
                        str71 = str32;
                        str66 = str28;
                        break;
                    case 3:
                        trailingConfig4 = trailingConfig6;
                        str25 = str56;
                        str26 = str59;
                        str27 = str61;
                        str28 = str66;
                        str29 = str67;
                        str33 = str73;
                        str34 = str74;
                        str30 = str68;
                        str69 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 3, StringSerializer.INSTANCE, str69);
                        i |= 8;
                        str31 = str69;
                        str32 = str71;
                        str35 = str70;
                        str74 = str34;
                        trailingConfig6 = trailingConfig4;
                        str69 = str31;
                        str68 = str30;
                        str56 = str25;
                        str67 = str29;
                        str73 = str33;
                        str70 = str35;
                        str61 = str27;
                        str59 = str26;
                        str71 = str32;
                        str66 = str28;
                        break;
                    case 4:
                        trailingConfig4 = trailingConfig6;
                        str26 = str59;
                        str27 = str61;
                        str28 = str66;
                        str29 = str67;
                        str33 = str73;
                        str34 = str74;
                        str25 = str56;
                        str68 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 4, StringSerializer.INSTANCE, str68);
                        i |= 16;
                        str30 = str68;
                        str31 = str69;
                        str32 = str71;
                        str35 = str70;
                        str74 = str34;
                        trailingConfig6 = trailingConfig4;
                        str69 = str31;
                        str68 = str30;
                        str56 = str25;
                        str67 = str29;
                        str73 = str33;
                        str70 = str35;
                        str61 = str27;
                        str59 = str26;
                        str71 = str32;
                        str66 = str28;
                        break;
                    case 5:
                        trailingConfig4 = trailingConfig6;
                        str26 = str59;
                        String str77 = str61;
                        str28 = str66;
                        str33 = str73;
                        str34 = str74;
                        str29 = str67;
                        str27 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 5, StringSerializer.INSTANCE, str77);
                        i |= 32;
                        str25 = str56;
                        str30 = str68;
                        str31 = str69;
                        str32 = str71;
                        str35 = str70;
                        str74 = str34;
                        trailingConfig6 = trailingConfig4;
                        str69 = str31;
                        str68 = str30;
                        str56 = str25;
                        str67 = str29;
                        str73 = str33;
                        str70 = str35;
                        str61 = str27;
                        str59 = str26;
                        str71 = str32;
                        str66 = str28;
                        break;
                    case 6:
                        trailingConfig4 = trailingConfig6;
                        str26 = str59;
                        str36 = str61;
                        str28 = str66;
                        str37 = str67;
                        str33 = str73;
                        str34 = str74;
                        str60 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 6, StringSerializer.INSTANCE, str60);
                        i |= 64;
                        str29 = str37;
                        str25 = str56;
                        str30 = str68;
                        str31 = str69;
                        str32 = str71;
                        str27 = str36;
                        str35 = str70;
                        str74 = str34;
                        trailingConfig6 = trailingConfig4;
                        str69 = str31;
                        str68 = str30;
                        str56 = str25;
                        str67 = str29;
                        str73 = str33;
                        str70 = str35;
                        str61 = str27;
                        str59 = str26;
                        str71 = str32;
                        str66 = str28;
                        break;
                    case 7:
                        trailingConfig4 = trailingConfig6;
                        str26 = str59;
                        str36 = str61;
                        str28 = str66;
                        str37 = str67;
                        str33 = str73;
                        str34 = str74;
                        str57 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 7, StringSerializer.INSTANCE, str57);
                        i |= 128;
                        str29 = str37;
                        str25 = str56;
                        str30 = str68;
                        str31 = str69;
                        str32 = str71;
                        str27 = str36;
                        str35 = str70;
                        str74 = str34;
                        trailingConfig6 = trailingConfig4;
                        str69 = str31;
                        str68 = str30;
                        str56 = str25;
                        str67 = str29;
                        str73 = str33;
                        str70 = str35;
                        str61 = str27;
                        str59 = str26;
                        str71 = str32;
                        str66 = str28;
                        break;
                    case 8:
                        trailingConfig4 = trailingConfig6;
                        str26 = str59;
                        str36 = str61;
                        str28 = str66;
                        str33 = str73;
                        str34 = str74;
                        str58 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 8, StringSerializer.INSTANCE, str58);
                        str29 = str67;
                        str25 = str56;
                        i |= 256;
                        str30 = str68;
                        str31 = str69;
                        str32 = str71;
                        str27 = str36;
                        str35 = str70;
                        str74 = str34;
                        trailingConfig6 = trailingConfig4;
                        str69 = str31;
                        str68 = str30;
                        str56 = str25;
                        str67 = str29;
                        str73 = str33;
                        str70 = str35;
                        str61 = str27;
                        str59 = str26;
                        str71 = str32;
                        str66 = str28;
                        break;
                    case 9:
                        str28 = str66;
                        str56 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 9, StringSerializer.INSTANCE, str56);
                        i |= 512;
                        trailingConfig6 = trailingConfig6;
                        str59 = str59;
                        str61 = str61;
                        str66 = str28;
                        break;
                    case 10:
                        str20 = str59;
                        str21 = str61;
                        str22 = str74;
                        str67 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 10, StringSerializer.INSTANCE, str67);
                        i |= 1024;
                        trailingConfig6 = trailingConfig6;
                        str23 = str73;
                        str66 = str66;
                        str73 = str23;
                        str74 = str22;
                        str59 = str20;
                        str61 = str21;
                        break;
                    case 11:
                        str20 = str59;
                        str21 = str61;
                        str22 = str74;
                        i |= 2048;
                        trailingConfig6 = trailingConfig6;
                        str23 = str73;
                        str66 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 11, StringSerializer.INSTANCE, str66);
                        str73 = str23;
                        str74 = str22;
                        str59 = str20;
                        str61 = str21;
                        break;
                    case 12:
                        trailingConfig3 = trailingConfig6;
                        str20 = str59;
                        str21 = str61;
                        str24 = str73;
                        str22 = str74;
                        i |= 4096;
                        str62 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 12, StringSerializer.INSTANCE, str62);
                        str23 = str24;
                        trailingConfig6 = trailingConfig3;
                        str73 = str23;
                        str74 = str22;
                        str59 = str20;
                        str61 = str21;
                        break;
                    case 13:
                        trailingConfig3 = trailingConfig6;
                        str21 = str61;
                        str22 = str74;
                        str20 = str59;
                        str24 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 13, StringSerializer.INSTANCE, str73);
                        i |= 8192;
                        str23 = str24;
                        trailingConfig6 = trailingConfig3;
                        str73 = str23;
                        str74 = str22;
                        str59 = str20;
                        str61 = str21;
                        break;
                    case 14:
                        str21 = str61;
                        str20 = str59;
                        i |= 16384;
                        trailingConfig6 = trailingConfig6;
                        str22 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 14, StringSerializer.INSTANCE, str74);
                        str23 = str73;
                        str73 = str23;
                        str74 = str22;
                        str59 = str20;
                        str61 = str21;
                        break;
                    case 15:
                        str21 = str61;
                        str63 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 15, StringSerializer.INSTANCE, str63);
                        i2 = 32768;
                        str20 = str59;
                        i = i2 | i;
                        str23 = str73;
                        str22 = str74;
                        str73 = str23;
                        str74 = str22;
                        str59 = str20;
                        str61 = str21;
                        break;
                    case 16:
                        str21 = str61;
                        str64 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 16, StringSerializer.INSTANCE, str64);
                        i2 = 65536;
                        str20 = str59;
                        i = i2 | i;
                        str23 = str73;
                        str22 = str74;
                        str73 = str23;
                        str74 = str22;
                        str59 = str20;
                        str61 = str21;
                        break;
                    case 17:
                        str21 = str61;
                        str59 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 17, StringSerializer.INSTANCE, str59);
                        i2 = 131072;
                        str20 = str59;
                        i = i2 | i;
                        str23 = str73;
                        str22 = str74;
                        str73 = str23;
                        str74 = str22;
                        str59 = str20;
                        str61 = str21;
                        break;
                    case 18:
                        str21 = str61;
                        str65 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 18, StringSerializer.INSTANCE, str65);
                        i2 = 262144;
                        str20 = str59;
                        i = i2 | i;
                        str23 = str73;
                        str22 = str74;
                        str73 = str23;
                        str74 = str22;
                        str59 = str20;
                        str61 = str21;
                        break;
                    case 19:
                        str21 = str61;
                        trailingConfig5 = (TrailingConfig) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 19, TrailingConfig$$serializer.INSTANCE, trailingConfig5);
                        i2 = 524288;
                        str20 = str59;
                        i = i2 | i;
                        str23 = str73;
                        str22 = str74;
                        str73 = str23;
                        str74 = str22;
                        str59 = str20;
                        str61 = str21;
                        break;
                    case 20:
                        str21 = str61;
                        trailingConfig6 = (TrailingConfig) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 20, TrailingConfig$$serializer.INSTANCE, trailingConfig6);
                        i2 = 1048576;
                        str20 = str59;
                        i = i2 | i;
                        str23 = str73;
                        str22 = str74;
                        str73 = str23;
                        str74 = str22;
                        str59 = str20;
                        str61 = str21;
                        break;
                    default:
                        throw new UnknownFieldException(iDecodeElementIndex);
                }
            }
            str = str57;
            str2 = str58;
            str3 = str61;
            str4 = str60;
            str5 = str62;
            str6 = str65;
            trailingConfig = trailingConfig5;
            trailingConfig2 = trailingConfig6;
            str7 = str69;
            str8 = str68;
            str9 = str56;
            str10 = str67;
            str11 = str72;
            str12 = str74;
            str13 = str63;
            str14 = str64;
            str15 = str59;
            str16 = str71;
            str17 = str66;
            str18 = str73;
            str19 = str70;
        }
        compositeDecoderBeginStructure.endStructure(serialDescriptor);
        return new BotLeadUserOrderHistoryModel(i, str11, str16, str19, str7, str8, str3, str4, str, str2, str9, str10, str17, str5, str18, str12, str13, str14, str15, str6, trailingConfig, trailingConfig2, (SerializationConstructorMarker) null);
    }

    /* JADX DEBUG: Method merged with bridge method: serialize(Lkotlinx/serialization/encoding/Encoder;Ljava/lang/Object;)V */
    @Override // kotlinx.serialization.SerializationStrategy
    public final void serialize(@NotNull Encoder encoder, @NotNull BotLeadUserOrderHistoryModel botLeadUserOrderHistoryModel) {
        Intrinsics.checkNotNullParameter(encoder, "");
        Intrinsics.checkNotNullParameter(botLeadUserOrderHistoryModel, "");
        SerialDescriptor serialDescriptor = descriptor;
        CompositeEncoder compositeEncoderBeginStructure = encoder.beginStructure(serialDescriptor);
        BotLeadUserOrderHistoryModel.write$Self$OKTradeCore_trade_core(botLeadUserOrderHistoryModel, compositeEncoderBeginStructure, serialDescriptor);
        compositeEncoderBeginStructure.endStructure(serialDescriptor);
    }
}
