package com.okinc.unify_trade.biz;

import com.google.api.client.googleapis.media.MediaHttpDownloader;
import com.huawei.hms.support.hianalytics.HiAnalyticsConstant;
import com.okinc.localization2.bean.AppLocaleInfo;
import java.util.ArrayList;
import kotlin.Unit;
import kotlin.jvm.internal.Intrinsics;
import kotlinx.serialization.KSerializer;
import kotlinx.serialization.UnknownFieldException;
import kotlinx.serialization.builtins.BuiltinSerializersKt;
import kotlinx.serialization.descriptors.SerialDescriptor;
import kotlinx.serialization.encoding.CompositeDecoder;
import kotlinx.serialization.encoding.CompositeEncoder;
import kotlinx.serialization.encoding.Decoder;
import kotlinx.serialization.encoding.Encoder;
import kotlinx.serialization.internal.BooleanSerializer;
import kotlinx.serialization.internal.GeneratedSerializer;
import kotlinx.serialization.internal.PluginGeneratedSerialDescriptor;
import kotlinx.serialization.internal.SerializationConstructorMarker;
import kotlinx.serialization.internal.StringSerializer;
import org.jetbrains.annotations.NotNull;

/* JADX INFO: loaded from: classes17.dex */
public final /* synthetic */ class ContractGridReq$$serializer implements GeneratedSerializer<ContractGridReq> {
    public static final int $stable;
    public static final ContractGridReq$$serializer INSTANCE;
    private static final SerialDescriptor descriptor;

    /* JADX DEBUG: Don't trust debug lines info. Lines numbers was adjusted: min line is 0 */
    private ContractGridReq$$serializer() {
    }

    /* JADX DEBUG: Don't trust debug lines info. Lines numbers was adjusted: min line is 0 */
    @Override // kotlinx.serialization.KSerializer, kotlinx.serialization.SerializationStrategy, kotlinx.serialization.DeserializationStrategy
    public final SerialDescriptor getDescriptor() {
        return descriptor;
    }

    static {
        ContractGridReq$$serializer contractGridReq$$serializer = new ContractGridReq$$serializer();
        INSTANCE = contractGridReq$$serializer;
        $stable = 8;
        PluginGeneratedSerialDescriptor pluginGeneratedSerialDescriptor = new PluginGeneratedSerialDescriptor("com.okinc.unify_trade.biz.ContractGridReq", contractGridReq$$serializer, 36);
        pluginGeneratedSerialDescriptor.addElement("instId", true);
        pluginGeneratedSerialDescriptor.addElement("instType", true);
        pluginGeneratedSerialDescriptor.addElement("basePos", true);
        pluginGeneratedSerialDescriptor.addElement("gridNum", true);
        pluginGeneratedSerialDescriptor.addElement("investType", true);
        pluginGeneratedSerialDescriptor.addElement("maxPx", true);
        pluginGeneratedSerialDescriptor.addElement("minPx", true);
        pluginGeneratedSerialDescriptor.addElement("sz", true);
        pluginGeneratedSerialDescriptor.addElement("runType", true);
        pluginGeneratedSerialDescriptor.addElement("slTriggerPx", true);
        pluginGeneratedSerialDescriptor.addElement("tpTriggerPx", true);
        pluginGeneratedSerialDescriptor.addElement("tpRatio", true);
        pluginGeneratedSerialDescriptor.addElement("slRatio", true);
        pluginGeneratedSerialDescriptor.addElement("tpOrdPx", true);
        pluginGeneratedSerialDescriptor.addElement("slOrdPx", true);
        pluginGeneratedSerialDescriptor.addElement(HiAnalyticsConstant.HaKey.BI_KEY_DIRECTION, true);
        pluginGeneratedSerialDescriptor.addElement(AppLocaleInfo.KEY_DISPLAY_NAME, true);
        pluginGeneratedSerialDescriptor.addElement(HiAnalyticsConstant.HaKey.BI_KEY_TRANSTYPE, true);
        pluginGeneratedSerialDescriptor.addElement("signParams", true);
        pluginGeneratedSerialDescriptor.addElement("profitSharingRatio", true);
        pluginGeneratedSerialDescriptor.addElement("ordType", true);
        pluginGeneratedSerialDescriptor.addElement("annualizedRate", true);
        pluginGeneratedSerialDescriptor.addElement("autoTransfer", true);
        pluginGeneratedSerialDescriptor.addElement("systemSource", true);
        pluginGeneratedSerialDescriptor.addElement("nmpUnderlyingId", true);
        pluginGeneratedSerialDescriptor.addElement("batchNo", true);
        pluginGeneratedSerialDescriptor.addElement("voucherId", true);
        pluginGeneratedSerialDescriptor.addElement("autoReserve", true);
        pluginGeneratedSerialDescriptor.addElement("actualMarginSz", true);
        pluginGeneratedSerialDescriptor.addElement("extraMarginSz", true);
        pluginGeneratedSerialDescriptor.addElement("contractGridVersion", true);
        pluginGeneratedSerialDescriptor.addElement("openPosSlippage", true);
        pluginGeneratedSerialDescriptor.addElement("openPosSlippageDefault", true);
        pluginGeneratedSerialDescriptor.addElement("ordVariant", true);
        pluginGeneratedSerialDescriptor.addElement("algoId", true);
        pluginGeneratedSerialDescriptor.addElement("topupActualMarginSz", true);
        descriptor = pluginGeneratedSerialDescriptor;
    }

    @Override // kotlinx.serialization.internal.GeneratedSerializer
    public final KSerializer<?>[] childSerializers() {
        KSerializer<?>[] kSerializerArr = ContractGridReq.$childSerializers;
        StringSerializer stringSerializer = StringSerializer.INSTANCE;
        BooleanSerializer booleanSerializer = BooleanSerializer.INSTANCE;
        return new KSerializer[]{stringSerializer, stringSerializer, BuiltinSerializersKt.getNullable(booleanSerializer), stringSerializer, BuiltinSerializersKt.getNullable(stringSerializer), stringSerializer, stringSerializer, stringSerializer, BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), stringSerializer, kSerializerArr[18], stringSerializer, stringSerializer, BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(booleanSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(booleanSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer)};
    }

    /* JADX DEBUG: Method merged with bridge method: deserialize(Lkotlinx/serialization/encoding/Decoder;)Ljava/lang/Object; */
    @Override // kotlinx.serialization.DeserializationStrategy
    public final ContractGridReq deserialize(@NotNull Decoder decoder) {
        String str;
        Boolean bool;
        String str2;
        String str3;
        String str4;
        String str5;
        String str6;
        String str7;
        Boolean bool2;
        ArrayList arrayList;
        String str8;
        String str9;
        String str10;
        String str11;
        Boolean bool3;
        String str12;
        String str13;
        String str14;
        String str15;
        String str16;
        String str17;
        String str18;
        String str19;
        String str20;
        String str21;
        String str22;
        int i;
        String str23;
        String str24;
        String str25;
        String str26;
        String str27;
        String str28;
        String str29;
        String str30;
        String str31;
        int i2;
        String str32;
        String str33;
        String str34;
        Boolean bool4;
        String str35;
        String str36;
        String str37;
        ArrayList arrayList2;
        String str38;
        String str39;
        String str40;
        String str41;
        String str42;
        String str43;
        String str44;
        String str45;
        String str46;
        String str47;
        String str48;
        String str49;
        String str50;
        String str51;
        String str52;
        int i3;
        String str53;
        String str54;
        String str55;
        String str56;
        int i4;
        Intrinsics.checkNotNullParameter(decoder, "");
        SerialDescriptor serialDescriptor = descriptor;
        CompositeDecoder compositeDecoderBeginStructure = decoder.beginStructure(serialDescriptor);
        KSerializer[] kSerializerArr = ContractGridReq.$childSerializers;
        if (compositeDecoderBeginStructure.decodeSequentially()) {
            String strDecodeStringElement = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 0);
            String strDecodeStringElement2 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 1);
            BooleanSerializer booleanSerializer = BooleanSerializer.INSTANCE;
            Boolean bool5 = (Boolean) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 2, booleanSerializer, null);
            String strDecodeStringElement3 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 3);
            StringSerializer stringSerializer = StringSerializer.INSTANCE;
            String str57 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 4, stringSerializer, null);
            String strDecodeStringElement4 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 5);
            String strDecodeStringElement5 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 6);
            String strDecodeStringElement6 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 7);
            String str58 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 8, stringSerializer, null);
            String str59 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 9, stringSerializer, null);
            String str60 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 10, stringSerializer, null);
            String str61 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 11, stringSerializer, null);
            String str62 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 12, stringSerializer, null);
            String str63 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 13, stringSerializer, null);
            String str64 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 14, stringSerializer, null);
            String str65 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 15, stringSerializer, null);
            String str66 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 16, stringSerializer, null);
            String strDecodeStringElement7 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 17);
            ArrayList arrayList3 = (ArrayList) compositeDecoderBeginStructure.decodeSerializableElement(serialDescriptor, 18, kSerializerArr[18], null);
            String strDecodeStringElement8 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 19);
            String strDecodeStringElement9 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 20);
            String str67 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 21, stringSerializer, null);
            String str68 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 22, stringSerializer, null);
            String str69 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 23, stringSerializer, null);
            String str70 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 24, stringSerializer, null);
            String str71 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 25, stringSerializer, null);
            String str72 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 26, stringSerializer, null);
            Boolean bool6 = (Boolean) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 27, booleanSerializer, null);
            String str73 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 28, stringSerializer, null);
            String str74 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 29, stringSerializer, null);
            String str75 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 30, stringSerializer, null);
            String str76 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 31, stringSerializer, null);
            Boolean bool7 = (Boolean) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 32, booleanSerializer, null);
            String str77 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 33, stringSerializer, null);
            String str78 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 34, stringSerializer, null);
            str3 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 35, stringSerializer, null);
            str8 = str77;
            str20 = strDecodeStringElement5;
            bool2 = bool7;
            bool = bool5;
            str5 = str72;
            bool3 = bool6;
            str27 = str73;
            str6 = str74;
            str7 = str75;
            str2 = str76;
            str4 = str78;
            i = 15;
            str15 = strDecodeStringElement8;
            str14 = strDecodeStringElement9;
            str31 = strDecodeStringElement4;
            str18 = strDecodeStringElement;
            str28 = str67;
            str22 = str68;
            str23 = str69;
            str24 = str70;
            str25 = str71;
            arrayList = arrayList3;
            str16 = strDecodeStringElement7;
            str32 = str66;
            str29 = str64;
            str11 = str62;
            str9 = str65;
            str12 = str59;
            str19 = strDecodeStringElement6;
            str21 = strDecodeStringElement3;
            str17 = strDecodeStringElement2;
            str10 = str63;
            str30 = str58;
            str26 = str57;
            i2 = -1;
            str = str61;
            str13 = str60;
        } else {
            String str79 = null;
            String str80 = null;
            Boolean bool8 = null;
            String str81 = null;
            String str82 = null;
            String str83 = null;
            String str84 = null;
            String str85 = null;
            String str86 = null;
            String str87 = null;
            Boolean bool9 = null;
            String str88 = null;
            String strDecodeStringElement10 = null;
            String strDecodeStringElement11 = null;
            String str89 = null;
            ArrayList arrayList4 = null;
            String strDecodeStringElement12 = null;
            String str90 = null;
            String str91 = null;
            String str92 = null;
            String str93 = null;
            String str94 = null;
            String str95 = null;
            String str96 = null;
            String str97 = null;
            String str98 = null;
            Boolean bool10 = null;
            String strDecodeStringElement13 = null;
            String strDecodeStringElement14 = null;
            String strDecodeStringElement15 = null;
            String strDecodeStringElement16 = null;
            String strDecodeStringElement17 = null;
            String strDecodeStringElement18 = null;
            String str99 = null;
            int i5 = 0;
            boolean z = true;
            String str100 = null;
            int i6 = 0;
            String str101 = null;
            while (z) {
                String str102 = str83;
                int iDecodeElementIndex = compositeDecoderBeginStructure.decodeElementIndex(serialDescriptor);
                switch (iDecodeElementIndex) {
                    case -1:
                        str33 = str79;
                        str34 = str80;
                        bool4 = bool8;
                        str35 = str82;
                        str36 = str88;
                        str37 = str89;
                        arrayList2 = arrayList4;
                        str38 = str90;
                        str39 = str91;
                        str40 = str92;
                        str41 = str93;
                        str42 = str94;
                        str43 = str95;
                        str44 = str96;
                        str45 = str97;
                        str46 = str98;
                        Unit unit = Unit.INSTANCE;
                        z = false;
                        str98 = str46;
                        str80 = str34;
                        str82 = str35;
                        str53 = str38;
                        str83 = str102;
                        arrayList4 = arrayList2;
                        str89 = str37;
                        str90 = str53;
                        str91 = str39;
                        str92 = str40;
                        str93 = str41;
                        str94 = str42;
                        str95 = str43;
                        bool8 = bool4;
                        str97 = str45;
                        str96 = str44;
                        str88 = str36;
                        str79 = str33;
                        break;
                    case 0:
                        str33 = str79;
                        str34 = str80;
                        bool4 = bool8;
                        str35 = str82;
                        str36 = str88;
                        str37 = str89;
                        arrayList2 = arrayList4;
                        str38 = str90;
                        str39 = str91;
                        str40 = str92;
                        str41 = str93;
                        str42 = str94;
                        str43 = str95;
                        str44 = str96;
                        str45 = str97;
                        str46 = str98;
                        strDecodeStringElement14 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 0);
                        i6 |= 1;
                        Unit unit2 = Unit.INSTANCE;
                        str98 = str46;
                        str80 = str34;
                        str82 = str35;
                        str53 = str38;
                        str83 = str102;
                        arrayList4 = arrayList2;
                        str89 = str37;
                        str90 = str53;
                        str91 = str39;
                        str92 = str40;
                        str93 = str41;
                        str94 = str42;
                        str95 = str43;
                        bool8 = bool4;
                        str97 = str45;
                        str96 = str44;
                        str88 = str36;
                        str79 = str33;
                        break;
                    case 1:
                        str33 = str79;
                        str34 = str80;
                        bool4 = bool8;
                        str35 = str82;
                        str36 = str88;
                        str37 = str89;
                        arrayList2 = arrayList4;
                        str38 = str90;
                        str39 = str91;
                        str40 = str92;
                        str41 = str93;
                        str42 = str94;
                        str43 = str95;
                        str44 = str96;
                        str45 = str97;
                        str46 = str98;
                        strDecodeStringElement13 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 1);
                        i6 |= 2;
                        Unit unit3 = Unit.INSTANCE;
                        str98 = str46;
                        str80 = str34;
                        str82 = str35;
                        str53 = str38;
                        str83 = str102;
                        arrayList4 = arrayList2;
                        str89 = str37;
                        str90 = str53;
                        str91 = str39;
                        str92 = str40;
                        str93 = str41;
                        str94 = str42;
                        str95 = str43;
                        bool8 = bool4;
                        str97 = str45;
                        str96 = str44;
                        str88 = str36;
                        str79 = str33;
                        break;
                    case 2:
                        str33 = str79;
                        str34 = str80;
                        str35 = str82;
                        str36 = str88;
                        str37 = str89;
                        arrayList2 = arrayList4;
                        str38 = str90;
                        str39 = str91;
                        str40 = str92;
                        str41 = str93;
                        str42 = str94;
                        str43 = str95;
                        str44 = str96;
                        str45 = str97;
                        str46 = str98;
                        bool4 = bool8;
                        bool10 = (Boolean) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 2, BooleanSerializer.INSTANCE, bool10);
                        i6 |= 4;
                        Unit unit4 = Unit.INSTANCE;
                        str98 = str46;
                        str80 = str34;
                        str82 = str35;
                        str53 = str38;
                        str83 = str102;
                        arrayList4 = arrayList2;
                        str89 = str37;
                        str90 = str53;
                        str91 = str39;
                        str92 = str40;
                        str93 = str41;
                        str94 = str42;
                        str95 = str43;
                        bool8 = bool4;
                        str97 = str45;
                        str96 = str44;
                        str88 = str36;
                        str79 = str33;
                        break;
                    case 3:
                        str33 = str79;
                        str47 = str80;
                        str48 = str82;
                        str49 = str88;
                        str37 = str89;
                        arrayList2 = arrayList4;
                        str38 = str90;
                        str39 = str91;
                        str40 = str92;
                        str41 = str93;
                        str42 = str94;
                        str43 = str95;
                        str44 = str96;
                        str50 = str97;
                        strDecodeStringElement18 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 3);
                        i6 |= 8;
                        Unit unit5 = Unit.INSTANCE;
                        str97 = str50;
                        str51 = str49;
                        bool4 = bool8;
                        str36 = str51;
                        str80 = str47;
                        str45 = str97;
                        str82 = str48;
                        str53 = str38;
                        str83 = str102;
                        arrayList4 = arrayList2;
                        str89 = str37;
                        str90 = str53;
                        str91 = str39;
                        str92 = str40;
                        str93 = str41;
                        str94 = str42;
                        str95 = str43;
                        bool8 = bool4;
                        str97 = str45;
                        str96 = str44;
                        str88 = str36;
                        str79 = str33;
                        break;
                    case 4:
                        str33 = str79;
                        str47 = str80;
                        str48 = str82;
                        str49 = str88;
                        str37 = str89;
                        arrayList2 = arrayList4;
                        str38 = str90;
                        str39 = str91;
                        str40 = str92;
                        str41 = str93;
                        str42 = str94;
                        str43 = str95;
                        str44 = str96;
                        str50 = str97;
                        str98 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 4, StringSerializer.INSTANCE, str98);
                        int i7 = i6 | 16;
                        Unit unit6 = Unit.INSTANCE;
                        i6 = i7;
                        str97 = str50;
                        str51 = str49;
                        bool4 = bool8;
                        str36 = str51;
                        str80 = str47;
                        str45 = str97;
                        str82 = str48;
                        str53 = str38;
                        str83 = str102;
                        arrayList4 = arrayList2;
                        str89 = str37;
                        str90 = str53;
                        str91 = str39;
                        str92 = str40;
                        str93 = str41;
                        str94 = str42;
                        str95 = str43;
                        bool8 = bool4;
                        str97 = str45;
                        str96 = str44;
                        str88 = str36;
                        str79 = str33;
                        break;
                    case 5:
                        str33 = str79;
                        str47 = str80;
                        str48 = str82;
                        str52 = str88;
                        str37 = str89;
                        arrayList2 = arrayList4;
                        str38 = str90;
                        str39 = str91;
                        str40 = str92;
                        str41 = str93;
                        str42 = str94;
                        str43 = str95;
                        str44 = str96;
                        strDecodeStringElement17 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 5);
                        i6 |= 32;
                        Unit unit7 = Unit.INSTANCE;
                        str51 = str52;
                        bool4 = bool8;
                        str36 = str51;
                        str80 = str47;
                        str45 = str97;
                        str82 = str48;
                        str53 = str38;
                        str83 = str102;
                        arrayList4 = arrayList2;
                        str89 = str37;
                        str90 = str53;
                        str91 = str39;
                        str92 = str40;
                        str93 = str41;
                        str94 = str42;
                        str95 = str43;
                        bool8 = bool4;
                        str97 = str45;
                        str96 = str44;
                        str88 = str36;
                        str79 = str33;
                        break;
                    case 6:
                        str33 = str79;
                        str47 = str80;
                        str48 = str82;
                        str52 = str88;
                        str37 = str89;
                        arrayList2 = arrayList4;
                        str38 = str90;
                        str39 = str91;
                        str40 = str92;
                        str41 = str93;
                        str42 = str94;
                        str43 = str95;
                        str44 = str96;
                        strDecodeStringElement16 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 6);
                        i6 |= 64;
                        Unit unit8 = Unit.INSTANCE;
                        str51 = str52;
                        bool4 = bool8;
                        str36 = str51;
                        str80 = str47;
                        str45 = str97;
                        str82 = str48;
                        str53 = str38;
                        str83 = str102;
                        arrayList4 = arrayList2;
                        str89 = str37;
                        str90 = str53;
                        str91 = str39;
                        str92 = str40;
                        str93 = str41;
                        str94 = str42;
                        str95 = str43;
                        bool8 = bool4;
                        str97 = str45;
                        str96 = str44;
                        str88 = str36;
                        str79 = str33;
                        break;
                    case 7:
                        str33 = str79;
                        str47 = str80;
                        str48 = str82;
                        str52 = str88;
                        str37 = str89;
                        arrayList2 = arrayList4;
                        str38 = str90;
                        str39 = str91;
                        str40 = str92;
                        str41 = str93;
                        str42 = str94;
                        str43 = str95;
                        str44 = str96;
                        strDecodeStringElement15 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 7);
                        i6 |= 128;
                        Unit unit9 = Unit.INSTANCE;
                        str51 = str52;
                        bool4 = bool8;
                        str36 = str51;
                        str80 = str47;
                        str45 = str97;
                        str82 = str48;
                        str53 = str38;
                        str83 = str102;
                        arrayList4 = arrayList2;
                        str89 = str37;
                        str90 = str53;
                        str91 = str39;
                        str92 = str40;
                        str93 = str41;
                        str94 = str42;
                        str95 = str43;
                        bool8 = bool4;
                        str97 = str45;
                        str96 = str44;
                        str88 = str36;
                        str79 = str33;
                        break;
                    case 8:
                        str33 = str79;
                        str47 = str80;
                        str48 = str82;
                        str52 = str88;
                        str37 = str89;
                        arrayList2 = arrayList4;
                        str38 = str90;
                        str39 = str91;
                        str40 = str92;
                        str41 = str93;
                        str42 = str94;
                        str43 = str95;
                        str44 = str96;
                        str97 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 8, StringSerializer.INSTANCE, str97);
                        int i8 = i6 | 256;
                        Unit unit10 = Unit.INSTANCE;
                        i6 = i8;
                        str51 = str52;
                        bool4 = bool8;
                        str36 = str51;
                        str80 = str47;
                        str45 = str97;
                        str82 = str48;
                        str53 = str38;
                        str83 = str102;
                        arrayList4 = arrayList2;
                        str89 = str37;
                        str90 = str53;
                        str91 = str39;
                        str92 = str40;
                        str93 = str41;
                        str94 = str42;
                        str95 = str43;
                        bool8 = bool4;
                        str97 = str45;
                        str96 = str44;
                        str88 = str36;
                        str79 = str33;
                        break;
                    case 9:
                        str33 = str79;
                        str47 = str80;
                        str48 = str82;
                        str37 = str89;
                        arrayList2 = arrayList4;
                        str38 = str90;
                        str39 = str91;
                        str40 = str92;
                        str41 = str93;
                        str42 = str94;
                        str43 = str95;
                        str96 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 9, StringSerializer.INSTANCE, str96);
                        i6 |= 512;
                        Unit unit11 = Unit.INSTANCE;
                        str51 = str88;
                        str44 = str96;
                        bool4 = bool8;
                        str36 = str51;
                        str80 = str47;
                        str45 = str97;
                        str82 = str48;
                        str53 = str38;
                        str83 = str102;
                        arrayList4 = arrayList2;
                        str89 = str37;
                        str90 = str53;
                        str91 = str39;
                        str92 = str40;
                        str93 = str41;
                        str94 = str42;
                        str95 = str43;
                        bool8 = bool4;
                        str97 = str45;
                        str96 = str44;
                        str88 = str36;
                        str79 = str33;
                        break;
                    case 10:
                        str33 = str79;
                        str47 = str80;
                        str48 = str82;
                        str37 = str89;
                        arrayList2 = arrayList4;
                        str38 = str90;
                        str39 = str91;
                        str40 = str92;
                        str41 = str93;
                        str42 = str94;
                        str43 = str95;
                        str51 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 10, StringSerializer.INSTANCE, str88);
                        i6 |= 1024;
                        Unit unit12 = Unit.INSTANCE;
                        str44 = str96;
                        bool4 = bool8;
                        str36 = str51;
                        str80 = str47;
                        str45 = str97;
                        str82 = str48;
                        str53 = str38;
                        str83 = str102;
                        arrayList4 = arrayList2;
                        str89 = str37;
                        str90 = str53;
                        str91 = str39;
                        str92 = str40;
                        str93 = str41;
                        str94 = str42;
                        str95 = str43;
                        bool8 = bool4;
                        str97 = str45;
                        str96 = str44;
                        str88 = str36;
                        str79 = str33;
                        break;
                    case 11:
                        str33 = str79;
                        str47 = str80;
                        str48 = str82;
                        str37 = str89;
                        arrayList2 = arrayList4;
                        str38 = str90;
                        str39 = str91;
                        str40 = str92;
                        str41 = str93;
                        str42 = str94;
                        str95 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 11, StringSerializer.INSTANCE, str95);
                        i6 |= 2048;
                        Unit unit13 = Unit.INSTANCE;
                        str51 = str88;
                        str43 = str95;
                        str44 = str96;
                        bool4 = bool8;
                        str36 = str51;
                        str80 = str47;
                        str45 = str97;
                        str82 = str48;
                        str53 = str38;
                        str83 = str102;
                        arrayList4 = arrayList2;
                        str89 = str37;
                        str90 = str53;
                        str91 = str39;
                        str92 = str40;
                        str93 = str41;
                        str94 = str42;
                        str95 = str43;
                        bool8 = bool4;
                        str97 = str45;
                        str96 = str44;
                        str88 = str36;
                        str79 = str33;
                        break;
                    case 12:
                        str33 = str79;
                        str47 = str80;
                        str48 = str82;
                        str37 = str89;
                        arrayList2 = arrayList4;
                        str38 = str90;
                        str39 = str91;
                        str40 = str92;
                        str41 = str93;
                        str94 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 12, StringSerializer.INSTANCE, str94);
                        i6 |= 4096;
                        Unit unit14 = Unit.INSTANCE;
                        str51 = str88;
                        str42 = str94;
                        str43 = str95;
                        str44 = str96;
                        bool4 = bool8;
                        str36 = str51;
                        str80 = str47;
                        str45 = str97;
                        str82 = str48;
                        str53 = str38;
                        str83 = str102;
                        arrayList4 = arrayList2;
                        str89 = str37;
                        str90 = str53;
                        str91 = str39;
                        str92 = str40;
                        str93 = str41;
                        str94 = str42;
                        str95 = str43;
                        bool8 = bool4;
                        str97 = str45;
                        str96 = str44;
                        str88 = str36;
                        str79 = str33;
                        break;
                    case 13:
                        str33 = str79;
                        str47 = str80;
                        str48 = str82;
                        str37 = str89;
                        arrayList2 = arrayList4;
                        str38 = str90;
                        str39 = str91;
                        str40 = str92;
                        str93 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 13, StringSerializer.INSTANCE, str93);
                        i6 |= 8192;
                        Unit unit15 = Unit.INSTANCE;
                        str51 = str88;
                        str41 = str93;
                        str42 = str94;
                        str43 = str95;
                        str44 = str96;
                        bool4 = bool8;
                        str36 = str51;
                        str80 = str47;
                        str45 = str97;
                        str82 = str48;
                        str53 = str38;
                        str83 = str102;
                        arrayList4 = arrayList2;
                        str89 = str37;
                        str90 = str53;
                        str91 = str39;
                        str92 = str40;
                        str93 = str41;
                        str94 = str42;
                        str95 = str43;
                        bool8 = bool4;
                        str97 = str45;
                        str96 = str44;
                        str88 = str36;
                        str79 = str33;
                        break;
                    case 14:
                        str33 = str79;
                        str47 = str80;
                        str48 = str82;
                        str37 = str89;
                        arrayList2 = arrayList4;
                        str38 = str90;
                        str39 = str91;
                        str92 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 14, StringSerializer.INSTANCE, str92);
                        i6 |= 16384;
                        Unit unit16 = Unit.INSTANCE;
                        str51 = str88;
                        str40 = str92;
                        str41 = str93;
                        str42 = str94;
                        str43 = str95;
                        str44 = str96;
                        bool4 = bool8;
                        str36 = str51;
                        str80 = str47;
                        str45 = str97;
                        str82 = str48;
                        str53 = str38;
                        str83 = str102;
                        arrayList4 = arrayList2;
                        str89 = str37;
                        str90 = str53;
                        str91 = str39;
                        str92 = str40;
                        str93 = str41;
                        str94 = str42;
                        str95 = str43;
                        bool8 = bool4;
                        str97 = str45;
                        str96 = str44;
                        str88 = str36;
                        str79 = str33;
                        break;
                    case 15:
                        str33 = str79;
                        str48 = str82;
                        str37 = str89;
                        arrayList2 = arrayList4;
                        str38 = str90;
                        str47 = str80;
                        str91 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 15, StringSerializer.INSTANCE, str91);
                        i6 |= 32768;
                        Unit unit17 = Unit.INSTANCE;
                        str51 = str88;
                        str39 = str91;
                        str40 = str92;
                        str41 = str93;
                        str42 = str94;
                        str43 = str95;
                        str44 = str96;
                        bool4 = bool8;
                        str36 = str51;
                        str80 = str47;
                        str45 = str97;
                        str82 = str48;
                        str53 = str38;
                        str83 = str102;
                        arrayList4 = arrayList2;
                        str89 = str37;
                        str90 = str53;
                        str91 = str39;
                        str92 = str40;
                        str93 = str41;
                        str94 = str42;
                        str95 = str43;
                        bool8 = bool4;
                        str97 = str45;
                        str96 = str44;
                        str88 = str36;
                        str79 = str33;
                        break;
                    case 16:
                        str33 = str79;
                        str48 = str82;
                        str37 = str89;
                        arrayList2 = arrayList4;
                        String str103 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 16, StringSerializer.INSTANCE, str90);
                        i6 |= 65536;
                        Unit unit18 = Unit.INSTANCE;
                        str47 = str80;
                        str51 = str88;
                        str38 = str103;
                        str39 = str91;
                        str40 = str92;
                        str41 = str93;
                        str42 = str94;
                        str43 = str95;
                        str44 = str96;
                        bool4 = bool8;
                        str36 = str51;
                        str80 = str47;
                        str45 = str97;
                        str82 = str48;
                        str53 = str38;
                        str83 = str102;
                        arrayList4 = arrayList2;
                        str89 = str37;
                        str90 = str53;
                        str91 = str39;
                        str92 = str40;
                        str93 = str41;
                        str94 = str42;
                        str95 = str43;
                        bool8 = bool4;
                        str97 = str45;
                        str96 = str44;
                        str88 = str36;
                        str79 = str33;
                        break;
                    case 17:
                        str33 = str79;
                        str35 = str82;
                        str37 = str89;
                        strDecodeStringElement12 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 17);
                        Unit unit19 = Unit.INSTANCE;
                        i3 = i6 | 131072;
                        i6 = i3;
                        str34 = str80;
                        bool4 = bool8;
                        str36 = str88;
                        arrayList2 = arrayList4;
                        str38 = str90;
                        str39 = str91;
                        str40 = str92;
                        str41 = str93;
                        str42 = str94;
                        str43 = str95;
                        str44 = str96;
                        str45 = str97;
                        str46 = str98;
                        str98 = str46;
                        str80 = str34;
                        str82 = str35;
                        str53 = str38;
                        str83 = str102;
                        arrayList4 = arrayList2;
                        str89 = str37;
                        str90 = str53;
                        str91 = str39;
                        str92 = str40;
                        str93 = str41;
                        str94 = str42;
                        str95 = str43;
                        bool8 = bool4;
                        str97 = str45;
                        str96 = str44;
                        str88 = str36;
                        str79 = str33;
                        break;
                    case 18:
                        str33 = str79;
                        str35 = str82;
                        str37 = str89;
                        arrayList4 = (ArrayList) compositeDecoderBeginStructure.decodeSerializableElement(serialDescriptor, 18, kSerializerArr[18], arrayList4);
                        i3 = 262144 | i6;
                        Unit unit20 = Unit.INSTANCE;
                        i6 = i3;
                        str34 = str80;
                        bool4 = bool8;
                        str36 = str88;
                        arrayList2 = arrayList4;
                        str38 = str90;
                        str39 = str91;
                        str40 = str92;
                        str41 = str93;
                        str42 = str94;
                        str43 = str95;
                        str44 = str96;
                        str45 = str97;
                        str46 = str98;
                        str98 = str46;
                        str80 = str34;
                        str82 = str35;
                        str53 = str38;
                        str83 = str102;
                        arrayList4 = arrayList2;
                        str89 = str37;
                        str90 = str53;
                        str91 = str39;
                        str92 = str40;
                        str93 = str41;
                        str94 = str42;
                        str95 = str43;
                        bool8 = bool4;
                        str97 = str45;
                        str96 = str44;
                        str88 = str36;
                        str79 = str33;
                        break;
                    case 19:
                        str54 = str79;
                        str55 = str82;
                        strDecodeStringElement11 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 19);
                        i6 |= 524288;
                        Unit unit21 = Unit.INSTANCE;
                        str56 = str99;
                        str83 = str102;
                        str99 = str56;
                        str79 = str54;
                        str33 = str79;
                        bool4 = bool8;
                        str36 = str88;
                        str37 = str89;
                        arrayList2 = arrayList4;
                        str53 = str90;
                        str39 = str91;
                        str40 = str92;
                        str41 = str93;
                        str42 = str94;
                        str43 = str95;
                        str44 = str96;
                        str45 = str97;
                        str82 = str55;
                        arrayList4 = arrayList2;
                        str89 = str37;
                        str90 = str53;
                        str91 = str39;
                        str92 = str40;
                        str93 = str41;
                        str94 = str42;
                        str95 = str43;
                        bool8 = bool4;
                        str97 = str45;
                        str96 = str44;
                        str88 = str36;
                        str79 = str33;
                        break;
                    case 20:
                        str54 = str79;
                        str55 = str82;
                        strDecodeStringElement10 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 20);
                        i6 |= 1048576;
                        Unit unit22 = Unit.INSTANCE;
                        str56 = str99;
                        str83 = str102;
                        str99 = str56;
                        str79 = str54;
                        str33 = str79;
                        bool4 = bool8;
                        str36 = str88;
                        str37 = str89;
                        arrayList2 = arrayList4;
                        str53 = str90;
                        str39 = str91;
                        str40 = str92;
                        str41 = str93;
                        str42 = str94;
                        str43 = str95;
                        str44 = str96;
                        str45 = str97;
                        str82 = str55;
                        arrayList4 = arrayList2;
                        str89 = str37;
                        str90 = str53;
                        str91 = str39;
                        str92 = str40;
                        str93 = str41;
                        str94 = str42;
                        str95 = str43;
                        bool8 = bool4;
                        str97 = str45;
                        str96 = str44;
                        str88 = str36;
                        str79 = str33;
                        break;
                    case 21:
                        str54 = str79;
                        str55 = str82;
                        str89 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 21, StringSerializer.INSTANCE, str89);
                        int i9 = 2097152 | i6;
                        Unit unit23 = Unit.INSTANCE;
                        i6 = i9;
                        str56 = str99;
                        str83 = str102;
                        str99 = str56;
                        str79 = str54;
                        str33 = str79;
                        bool4 = bool8;
                        str36 = str88;
                        str37 = str89;
                        arrayList2 = arrayList4;
                        str53 = str90;
                        str39 = str91;
                        str40 = str92;
                        str41 = str93;
                        str42 = str94;
                        str43 = str95;
                        str44 = str96;
                        str45 = str97;
                        str82 = str55;
                        arrayList4 = arrayList2;
                        str89 = str37;
                        str90 = str53;
                        str91 = str39;
                        str92 = str40;
                        str93 = str41;
                        str94 = str42;
                        str95 = str43;
                        bool8 = bool4;
                        str97 = str45;
                        str96 = str44;
                        str88 = str36;
                        str79 = str33;
                        break;
                    case 22:
                        str54 = str79;
                        str55 = str82;
                        str56 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 22, StringSerializer.INSTANCE, str99);
                        i6 |= 4194304;
                        Unit unit24 = Unit.INSTANCE;
                        str83 = str102;
                        str99 = str56;
                        str79 = str54;
                        str33 = str79;
                        bool4 = bool8;
                        str36 = str88;
                        str37 = str89;
                        arrayList2 = arrayList4;
                        str53 = str90;
                        str39 = str91;
                        str40 = str92;
                        str41 = str93;
                        str42 = str94;
                        str43 = str95;
                        str44 = str96;
                        str45 = str97;
                        str82 = str55;
                        arrayList4 = arrayList2;
                        str89 = str37;
                        str90 = str53;
                        str91 = str39;
                        str92 = str40;
                        str93 = str41;
                        str94 = str42;
                        str95 = str43;
                        bool8 = bool4;
                        str97 = str45;
                        str96 = str44;
                        str88 = str36;
                        str79 = str33;
                        break;
                    case 23:
                        str54 = str79;
                        str55 = str82;
                        str83 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 23, StringSerializer.INSTANCE, str102);
                        int i10 = 8388608 | i6;
                        Unit unit25 = Unit.INSTANCE;
                        i6 = i10;
                        str56 = str99;
                        str99 = str56;
                        str79 = str54;
                        str33 = str79;
                        bool4 = bool8;
                        str36 = str88;
                        str37 = str89;
                        arrayList2 = arrayList4;
                        str53 = str90;
                        str39 = str91;
                        str40 = str92;
                        str41 = str93;
                        str42 = str94;
                        str43 = str95;
                        str44 = str96;
                        str45 = str97;
                        str82 = str55;
                        arrayList4 = arrayList2;
                        str89 = str37;
                        str90 = str53;
                        str91 = str39;
                        str92 = str40;
                        str93 = str41;
                        str94 = str42;
                        str95 = str43;
                        bool8 = bool4;
                        str97 = str45;
                        str96 = str44;
                        str88 = str36;
                        str79 = str33;
                        break;
                    case 24:
                        str54 = str79;
                        String str104 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 24, StringSerializer.INSTANCE, str82);
                        int i11 = 16777216 | i6;
                        Unit unit26 = Unit.INSTANCE;
                        i6 = i11;
                        str55 = str104;
                        str56 = str99;
                        str83 = str102;
                        str99 = str56;
                        str79 = str54;
                        str33 = str79;
                        bool4 = bool8;
                        str36 = str88;
                        str37 = str89;
                        arrayList2 = arrayList4;
                        str53 = str90;
                        str39 = str91;
                        str40 = str92;
                        str41 = str93;
                        str42 = str94;
                        str43 = str95;
                        str44 = str96;
                        str45 = str97;
                        str82 = str55;
                        arrayList4 = arrayList2;
                        str89 = str37;
                        str90 = str53;
                        str91 = str39;
                        str92 = str40;
                        str93 = str41;
                        str94 = str42;
                        str95 = str43;
                        bool8 = bool4;
                        str97 = str45;
                        str96 = str44;
                        str88 = str36;
                        str79 = str33;
                        break;
                    case 25:
                        str55 = str82;
                        str79 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 25, StringSerializer.INSTANCE, str79);
                        i4 = MediaHttpDownloader.MAXIMUM_CHUNK_SIZE;
                        i6 |= i4;
                        Unit unit27 = Unit.INSTANCE;
                        str83 = str102;
                        str33 = str79;
                        bool4 = bool8;
                        str36 = str88;
                        str37 = str89;
                        arrayList2 = arrayList4;
                        str53 = str90;
                        str39 = str91;
                        str40 = str92;
                        str41 = str93;
                        str42 = str94;
                        str43 = str95;
                        str44 = str96;
                        str45 = str97;
                        str82 = str55;
                        arrayList4 = arrayList2;
                        str89 = str37;
                        str90 = str53;
                        str91 = str39;
                        str92 = str40;
                        str93 = str41;
                        str94 = str42;
                        str95 = str43;
                        bool8 = bool4;
                        str97 = str45;
                        str96 = str44;
                        str88 = str36;
                        str79 = str33;
                        break;
                    case 26:
                        str55 = str82;
                        str84 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 26, StringSerializer.INSTANCE, str84);
                        i4 = 67108864;
                        i6 |= i4;
                        Unit unit272 = Unit.INSTANCE;
                        str83 = str102;
                        str33 = str79;
                        bool4 = bool8;
                        str36 = str88;
                        str37 = str89;
                        arrayList2 = arrayList4;
                        str53 = str90;
                        str39 = str91;
                        str40 = str92;
                        str41 = str93;
                        str42 = str94;
                        str43 = str95;
                        str44 = str96;
                        str45 = str97;
                        str82 = str55;
                        arrayList4 = arrayList2;
                        str89 = str37;
                        str90 = str53;
                        str91 = str39;
                        str92 = str40;
                        str93 = str41;
                        str94 = str42;
                        str95 = str43;
                        bool8 = bool4;
                        str97 = str45;
                        str96 = str44;
                        str88 = str36;
                        str79 = str33;
                        break;
                    case 27:
                        str55 = str82;
                        bool8 = (Boolean) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 27, BooleanSerializer.INSTANCE, bool8);
                        i4 = 134217728;
                        i6 |= i4;
                        Unit unit2722 = Unit.INSTANCE;
                        str83 = str102;
                        str33 = str79;
                        bool4 = bool8;
                        str36 = str88;
                        str37 = str89;
                        arrayList2 = arrayList4;
                        str53 = str90;
                        str39 = str91;
                        str40 = str92;
                        str41 = str93;
                        str42 = str94;
                        str43 = str95;
                        str44 = str96;
                        str45 = str97;
                        str82 = str55;
                        arrayList4 = arrayList2;
                        str89 = str37;
                        str90 = str53;
                        str91 = str39;
                        str92 = str40;
                        str93 = str41;
                        str94 = str42;
                        str95 = str43;
                        bool8 = bool4;
                        str97 = str45;
                        str96 = str44;
                        str88 = str36;
                        str79 = str33;
                        break;
                    case 28:
                        str55 = str82;
                        str85 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 28, StringSerializer.INSTANCE, str85);
                        i4 = 268435456;
                        i6 |= i4;
                        Unit unit27222 = Unit.INSTANCE;
                        str83 = str102;
                        str33 = str79;
                        bool4 = bool8;
                        str36 = str88;
                        str37 = str89;
                        arrayList2 = arrayList4;
                        str53 = str90;
                        str39 = str91;
                        str40 = str92;
                        str41 = str93;
                        str42 = str94;
                        str43 = str95;
                        str44 = str96;
                        str45 = str97;
                        str82 = str55;
                        arrayList4 = arrayList2;
                        str89 = str37;
                        str90 = str53;
                        str91 = str39;
                        str92 = str40;
                        str93 = str41;
                        str94 = str42;
                        str95 = str43;
                        bool8 = bool4;
                        str97 = str45;
                        str96 = str44;
                        str88 = str36;
                        str79 = str33;
                        break;
                    case 29:
                        str55 = str82;
                        str86 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 29, StringSerializer.INSTANCE, str86);
                        i4 = 536870912;
                        i6 |= i4;
                        Unit unit272222 = Unit.INSTANCE;
                        str83 = str102;
                        str33 = str79;
                        bool4 = bool8;
                        str36 = str88;
                        str37 = str89;
                        arrayList2 = arrayList4;
                        str53 = str90;
                        str39 = str91;
                        str40 = str92;
                        str41 = str93;
                        str42 = str94;
                        str43 = str95;
                        str44 = str96;
                        str45 = str97;
                        str82 = str55;
                        arrayList4 = arrayList2;
                        str89 = str37;
                        str90 = str53;
                        str91 = str39;
                        str92 = str40;
                        str93 = str41;
                        str94 = str42;
                        str95 = str43;
                        bool8 = bool4;
                        str97 = str45;
                        str96 = str44;
                        str88 = str36;
                        str79 = str33;
                        break;
                    case 30:
                        str55 = str82;
                        str87 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 30, StringSerializer.INSTANCE, str87);
                        i4 = 1073741824;
                        i6 |= i4;
                        Unit unit2722222 = Unit.INSTANCE;
                        str83 = str102;
                        str33 = str79;
                        bool4 = bool8;
                        str36 = str88;
                        str37 = str89;
                        arrayList2 = arrayList4;
                        str53 = str90;
                        str39 = str91;
                        str40 = str92;
                        str41 = str93;
                        str42 = str94;
                        str43 = str95;
                        str44 = str96;
                        str45 = str97;
                        str82 = str55;
                        arrayList4 = arrayList2;
                        str89 = str37;
                        str90 = str53;
                        str91 = str39;
                        str92 = str40;
                        str93 = str41;
                        str94 = str42;
                        str95 = str43;
                        bool8 = bool4;
                        str97 = str45;
                        str96 = str44;
                        str88 = str36;
                        str79 = str33;
                        break;
                    case 31:
                        str55 = str82;
                        str81 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 31, StringSerializer.INSTANCE, str81);
                        i4 = Integer.MIN_VALUE;
                        i6 |= i4;
                        Unit unit27222222 = Unit.INSTANCE;
                        str83 = str102;
                        str33 = str79;
                        bool4 = bool8;
                        str36 = str88;
                        str37 = str89;
                        arrayList2 = arrayList4;
                        str53 = str90;
                        str39 = str91;
                        str40 = str92;
                        str41 = str93;
                        str42 = str94;
                        str43 = str95;
                        str44 = str96;
                        str45 = str97;
                        str82 = str55;
                        arrayList4 = arrayList2;
                        str89 = str37;
                        str90 = str53;
                        str91 = str39;
                        str92 = str40;
                        str93 = str41;
                        str94 = str42;
                        str95 = str43;
                        bool8 = bool4;
                        str97 = str45;
                        str96 = str44;
                        str88 = str36;
                        str79 = str33;
                        break;
                    case 32:
                        str55 = str82;
                        bool9 = (Boolean) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 32, BooleanSerializer.INSTANCE, bool9);
                        i5 |= 1;
                        Unit unit272222222 = Unit.INSTANCE;
                        str83 = str102;
                        str33 = str79;
                        bool4 = bool8;
                        str36 = str88;
                        str37 = str89;
                        arrayList2 = arrayList4;
                        str53 = str90;
                        str39 = str91;
                        str40 = str92;
                        str41 = str93;
                        str42 = str94;
                        str43 = str95;
                        str44 = str96;
                        str45 = str97;
                        str82 = str55;
                        arrayList4 = arrayList2;
                        str89 = str37;
                        str90 = str53;
                        str91 = str39;
                        str92 = str40;
                        str93 = str41;
                        str94 = str42;
                        str95 = str43;
                        bool8 = bool4;
                        str97 = str45;
                        str96 = str44;
                        str88 = str36;
                        str79 = str33;
                        break;
                    case 33:
                        str55 = str82;
                        str80 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 33, StringSerializer.INSTANCE, str80);
                        i5 |= 2;
                        Unit unit2722222222 = Unit.INSTANCE;
                        str83 = str102;
                        str33 = str79;
                        bool4 = bool8;
                        str36 = str88;
                        str37 = str89;
                        arrayList2 = arrayList4;
                        str53 = str90;
                        str39 = str91;
                        str40 = str92;
                        str41 = str93;
                        str42 = str94;
                        str43 = str95;
                        str44 = str96;
                        str45 = str97;
                        str82 = str55;
                        arrayList4 = arrayList2;
                        str89 = str37;
                        str90 = str53;
                        str91 = str39;
                        str92 = str40;
                        str93 = str41;
                        str94 = str42;
                        str95 = str43;
                        bool8 = bool4;
                        str97 = str45;
                        str96 = str44;
                        str88 = str36;
                        str79 = str33;
                        break;
                    case 34:
                        str55 = str82;
                        str100 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 34, StringSerializer.INSTANCE, str100);
                        i5 |= 4;
                        Unit unit27222222222 = Unit.INSTANCE;
                        str83 = str102;
                        str33 = str79;
                        bool4 = bool8;
                        str36 = str88;
                        str37 = str89;
                        arrayList2 = arrayList4;
                        str53 = str90;
                        str39 = str91;
                        str40 = str92;
                        str41 = str93;
                        str42 = str94;
                        str43 = str95;
                        str44 = str96;
                        str45 = str97;
                        str82 = str55;
                        arrayList4 = arrayList2;
                        str89 = str37;
                        str90 = str53;
                        str91 = str39;
                        str92 = str40;
                        str93 = str41;
                        str94 = str42;
                        str95 = str43;
                        bool8 = bool4;
                        str97 = str45;
                        str96 = str44;
                        str88 = str36;
                        str79 = str33;
                        break;
                    case 35:
                        str55 = str82;
                        str101 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 35, StringSerializer.INSTANCE, str101);
                        i5 |= 8;
                        Unit unit272222222222 = Unit.INSTANCE;
                        str83 = str102;
                        str33 = str79;
                        bool4 = bool8;
                        str36 = str88;
                        str37 = str89;
                        arrayList2 = arrayList4;
                        str53 = str90;
                        str39 = str91;
                        str40 = str92;
                        str41 = str93;
                        str42 = str94;
                        str43 = str95;
                        str44 = str96;
                        str45 = str97;
                        str82 = str55;
                        arrayList4 = arrayList2;
                        str89 = str37;
                        str90 = str53;
                        str91 = str39;
                        str92 = str40;
                        str93 = str41;
                        str94 = str42;
                        str95 = str43;
                        bool8 = bool4;
                        str97 = str45;
                        str96 = str44;
                        str88 = str36;
                        str79 = str33;
                        break;
                    default:
                        throw new UnknownFieldException(iDecodeElementIndex);
                }
            }
            String str105 = str83;
            String str106 = str89;
            String str107 = str90;
            String str108 = str91;
            String str109 = str92;
            String str110 = str93;
            String str111 = str94;
            str = str95;
            String str112 = str96;
            bool = bool10;
            str2 = str81;
            str3 = str101;
            str4 = str100;
            str5 = str84;
            str6 = str86;
            str7 = str87;
            bool2 = bool9;
            arrayList = arrayList4;
            str8 = str80;
            str9 = str108;
            str10 = str110;
            str11 = str111;
            bool3 = bool8;
            str12 = str112;
            str13 = str88;
            str14 = strDecodeStringElement10;
            str15 = strDecodeStringElement11;
            str16 = strDecodeStringElement12;
            str17 = strDecodeStringElement13;
            str18 = strDecodeStringElement14;
            str19 = strDecodeStringElement15;
            str20 = strDecodeStringElement16;
            str21 = strDecodeStringElement18;
            str22 = str99;
            i = i5;
            str23 = str105;
            str24 = str82;
            str25 = str79;
            str26 = str98;
            str27 = str85;
            str28 = str106;
            str29 = str109;
            str30 = str97;
            str31 = strDecodeStringElement17;
            i2 = i6;
            str32 = str107;
        }
        compositeDecoderBeginStructure.endStructure(serialDescriptor);
        return new ContractGridReq(i2, i, str18, str17, bool, str21, str26, str31, str20, str19, str30, str12, str13, str, str11, str10, str29, str9, str32, str16, arrayList, str15, str14, str28, str22, str23, str24, str25, str5, bool3, str27, str6, str7, str2, bool2, str8, str4, str3, (SerializationConstructorMarker) null);
    }

    /* JADX DEBUG: Method merged with bridge method: serialize(Lkotlinx/serialization/encoding/Encoder;Ljava/lang/Object;)V */
    @Override // kotlinx.serialization.SerializationStrategy
    public final void serialize(@NotNull Encoder encoder, @NotNull ContractGridReq contractGridReq) {
        Intrinsics.checkNotNullParameter(encoder, "");
        Intrinsics.checkNotNullParameter(contractGridReq, "");
        SerialDescriptor serialDescriptor = descriptor;
        CompositeEncoder compositeEncoderBeginStructure = encoder.beginStructure(serialDescriptor);
        ContractGridReq.write$Self$OKTradeCore_trade_core(contractGridReq, compositeEncoderBeginStructure, serialDescriptor);
        compositeEncoderBeginStructure.endStructure(serialDescriptor);
    }
}
