package com.okinc.unify_trade.biz;

import com.huawei.hms.support.hianalytics.HiAnalyticsConstant;
import java.util.List;
import kotlin.jvm.internal.Intrinsics;
import kotlinx.serialization.KSerializer;
import kotlinx.serialization.UnknownFieldException;
import kotlinx.serialization.builtins.BuiltinSerializersKt;
import kotlinx.serialization.descriptors.SerialDescriptor;
import kotlinx.serialization.encoding.CompositeDecoder;
import kotlinx.serialization.encoding.CompositeEncoder;
import kotlinx.serialization.encoding.Decoder;
import kotlinx.serialization.encoding.Encoder;
import kotlinx.serialization.internal.BooleanSerializer;
import kotlinx.serialization.internal.GeneratedSerializer;
import kotlinx.serialization.internal.PluginGeneratedSerialDescriptor;
import kotlinx.serialization.internal.SerializationConstructorMarker;
import kotlinx.serialization.internal.StringSerializer;
import org.jetbrains.annotations.NotNull;

/* JADX INFO: loaded from: classes24.dex */
public final /* synthetic */ class DcaAiData$$serializer implements GeneratedSerializer<DcaAiData> {
    public static final int $stable;
    public static final DcaAiData$$serializer INSTANCE;
    private static final SerialDescriptor descriptor;

    /* JADX DEBUG: Don't trust debug lines info. Lines numbers was adjusted: min line is 0 */
    private DcaAiData$$serializer() {
    }

    /* JADX DEBUG: Don't trust debug lines info. Lines numbers was adjusted: min line is 0 */
    @Override // kotlinx.serialization.KSerializer, kotlinx.serialization.SerializationStrategy, kotlinx.serialization.DeserializationStrategy
    public final SerialDescriptor getDescriptor() {
        return descriptor;
    }

    static {
        DcaAiData$$serializer dcaAiData$$serializer = new DcaAiData$$serializer();
        INSTANCE = dcaAiData$$serializer;
        $stable = 8;
        PluginGeneratedSerialDescriptor pluginGeneratedSerialDescriptor = new PluginGeneratedSerialDescriptor("com.okinc.unify_trade.biz.DcaAiData", dcaAiData$$serializer, 20);
        pluginGeneratedSerialDescriptor.addElement("instId", true);
        pluginGeneratedSerialDescriptor.addElement("algoOrdType", true);
        pluginGeneratedSerialDescriptor.addElement(HiAnalyticsConstant.HaKey.BI_KEY_DIRECTION, true);
        pluginGeneratedSerialDescriptor.addElement("apy", true);
        pluginGeneratedSerialDescriptor.addElement("reserveFunds", true);
        pluginGeneratedSerialDescriptor.addElement("triggerType", true);
        pluginGeneratedSerialDescriptor.addElement("initOrds", true);
        pluginGeneratedSerialDescriptor.addElement("initOrdPct", true);
        pluginGeneratedSerialDescriptor.addElement("maxSafetyOrds", true);
        pluginGeneratedSerialDescriptor.addElement("duration", true);
        pluginGeneratedSerialDescriptor.addElement("pxSteps", true);
        pluginGeneratedSerialDescriptor.addElement("pxStepsMult", true);
        pluginGeneratedSerialDescriptor.addElement("volMult", true);
        pluginGeneratedSerialDescriptor.addElement("tpPct", true);
        pluginGeneratedSerialDescriptor.addElement("slPct", true);
        pluginGeneratedSerialDescriptor.addElement("minInvestment", true);
        pluginGeneratedSerialDescriptor.addElement("ccy", true);
        pluginGeneratedSerialDescriptor.addElement(HiAnalyticsConstant.HaKey.BI_KEY_TRANSTYPE, true);
        pluginGeneratedSerialDescriptor.addElement("slMode", true);
        pluginGeneratedSerialDescriptor.addElement("triggerParams", true);
        descriptor = pluginGeneratedSerialDescriptor;
    }

    @Override // kotlinx.serialization.internal.GeneratedSerializer
    public final KSerializer<?>[] childSerializers() {
        KSerializer[] kSerializerArr = DcaAiData.$childSerializers;
        StringSerializer stringSerializer = StringSerializer.INSTANCE;
        return new KSerializer[]{BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BooleanSerializer.INSTANCE, BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(kSerializerArr[19])};
    }

    /* JADX DEBUG: Method merged with bridge method: deserialize(Lkotlinx/serialization/encoding/Decoder;)Ljava/lang/Object; */
    @Override // kotlinx.serialization.DeserializationStrategy
    public final DcaAiData deserialize(@NotNull Decoder decoder) {
        String str;
        String str2;
        String str3;
        String str4;
        String str5;
        String str6;
        boolean z;
        String str7;
        String str8;
        String str9;
        String str10;
        String str11;
        String str12;
        List list;
        String str13;
        int i;
        String str14;
        String str15;
        String str16;
        String str17;
        String str18;
        KSerializer[] kSerializerArr;
        String str19;
        String str20;
        String str21;
        String str22;
        String str23;
        String str24;
        String str25;
        String str26;
        String str27;
        String str28;
        String str29;
        String str30;
        Intrinsics.checkNotNullParameter(decoder, "");
        SerialDescriptor serialDescriptor = descriptor;
        CompositeDecoder compositeDecoderBeginStructure = decoder.beginStructure(serialDescriptor);
        KSerializer[] kSerializerArr2 = DcaAiData.$childSerializers;
        if (compositeDecoderBeginStructure.decodeSequentially()) {
            StringSerializer stringSerializer = StringSerializer.INSTANCE;
            str11 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 0, stringSerializer, null);
            str14 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 1, stringSerializer, null);
            String str31 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 2, stringSerializer, null);
            String str32 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 3, stringSerializer, null);
            boolean zDecodeBooleanElement = compositeDecoderBeginStructure.decodeBooleanElement(serialDescriptor, 4);
            String str33 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 5, stringSerializer, null);
            str8 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 6, stringSerializer, null);
            String str34 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 7, stringSerializer, null);
            String str35 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 8, stringSerializer, null);
            String str36 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 9, stringSerializer, null);
            String str37 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 10, stringSerializer, null);
            String str38 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 11, stringSerializer, null);
            String str39 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 12, stringSerializer, null);
            String str40 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 13, stringSerializer, null);
            String str41 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 14, stringSerializer, null);
            String str42 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 15, stringSerializer, null);
            String str43 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 16, stringSerializer, null);
            String str44 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 17, stringSerializer, null);
            String str45 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 18, stringSerializer, null);
            list = (List) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 19, kSerializerArr2[19], null);
            str = str45;
            str15 = str31;
            str16 = str44;
            str13 = str40;
            str3 = str39;
            i = 1048575;
            str9 = str35;
            str6 = str41;
            str4 = str38;
            str2 = str42;
            str5 = str37;
            str12 = str32;
            str17 = str43;
            str10 = str36;
            z = zDecodeBooleanElement;
            str18 = str34;
            str7 = str33;
        } else {
            int i2 = 19;
            boolean zDecodeBooleanElement2 = false;
            boolean z2 = true;
            String str46 = null;
            String str47 = null;
            String str48 = null;
            List list2 = null;
            String str49 = null;
            String str50 = null;
            String str51 = null;
            String str52 = null;
            String str53 = null;
            String str54 = null;
            String str55 = null;
            String str56 = null;
            String str57 = null;
            String str58 = null;
            String str59 = null;
            String str60 = null;
            String str61 = null;
            String str62 = null;
            String str63 = null;
            int i3 = 0;
            while (z2) {
                String str64 = str47;
                int iDecodeElementIndex = compositeDecoderBeginStructure.decodeElementIndex(serialDescriptor);
                switch (iDecodeElementIndex) {
                    case -1:
                        kSerializerArr = kSerializerArr2;
                        str19 = str46;
                        str20 = str55;
                        str21 = str56;
                        str22 = str57;
                        str23 = str59;
                        str24 = str60;
                        str25 = str61;
                        str26 = str62;
                        str27 = str64;
                        z2 = false;
                        str28 = str24;
                        str29 = str21;
                        str47 = str27;
                        str56 = str29;
                        str60 = str28;
                        str59 = str23;
                        str46 = str19;
                        str62 = str26;
                        str61 = str25;
                        str57 = str22;
                        str55 = str20;
                        kSerializerArr2 = kSerializerArr;
                        i2 = 19;
                        break;
                    case 0:
                        kSerializerArr = kSerializerArr2;
                        str19 = str46;
                        str20 = str55;
                        str22 = str57;
                        str23 = str59;
                        str24 = str60;
                        str25 = str61;
                        str26 = str62;
                        str27 = str64;
                        str21 = str56;
                        str58 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 0, StringSerializer.INSTANCE, str58);
                        i3 |= 1;
                        str28 = str24;
                        str29 = str21;
                        str47 = str27;
                        str56 = str29;
                        str60 = str28;
                        str59 = str23;
                        str46 = str19;
                        str62 = str26;
                        str61 = str25;
                        str57 = str22;
                        str55 = str20;
                        kSerializerArr2 = kSerializerArr;
                        i2 = 19;
                        break;
                    case 1:
                        kSerializerArr = kSerializerArr2;
                        str19 = str46;
                        str20 = str55;
                        str22 = str57;
                        str25 = str61;
                        str26 = str62;
                        str23 = str59;
                        str29 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 1, StringSerializer.INSTANCE, str56);
                        i3 |= 2;
                        str28 = str60;
                        str47 = str64;
                        str56 = str29;
                        str60 = str28;
                        str59 = str23;
                        str46 = str19;
                        str62 = str26;
                        str61 = str25;
                        str57 = str22;
                        str55 = str20;
                        kSerializerArr2 = kSerializerArr;
                        i2 = 19;
                        break;
                    case 2:
                        kSerializerArr = kSerializerArr2;
                        str20 = str55;
                        str22 = str57;
                        str25 = str61;
                        str26 = str62;
                        str19 = str46;
                        str23 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 2, StringSerializer.INSTANCE, str59);
                        i3 |= 4;
                        str28 = str60;
                        str47 = str64;
                        str29 = str56;
                        str56 = str29;
                        str60 = str28;
                        str59 = str23;
                        str46 = str19;
                        str62 = str26;
                        str61 = str25;
                        str57 = str22;
                        str55 = str20;
                        kSerializerArr2 = kSerializerArr;
                        i2 = 19;
                        break;
                    case 3:
                        kSerializerArr = kSerializerArr2;
                        str20 = str55;
                        str22 = str57;
                        str25 = str61;
                        str26 = str62;
                        str28 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 3, StringSerializer.INSTANCE, str60);
                        str19 = str46;
                        i3 |= 8;
                        str47 = str64;
                        str29 = str56;
                        str23 = str59;
                        str56 = str29;
                        str60 = str28;
                        str59 = str23;
                        str46 = str19;
                        str62 = str26;
                        str61 = str25;
                        str57 = str22;
                        str55 = str20;
                        kSerializerArr2 = kSerializerArr;
                        i2 = 19;
                        break;
                    case 4:
                        kSerializerArr = kSerializerArr2;
                        str20 = str55;
                        str22 = str57;
                        str25 = str61;
                        str30 = str64;
                        zDecodeBooleanElement2 = compositeDecoderBeginStructure.decodeBooleanElement(serialDescriptor, 4);
                        i3 |= 16;
                        str26 = str62;
                        str19 = str46;
                        str47 = str30;
                        str29 = str56;
                        str23 = str59;
                        str28 = str60;
                        str56 = str29;
                        str60 = str28;
                        str59 = str23;
                        str46 = str19;
                        str62 = str26;
                        str61 = str25;
                        str57 = str22;
                        str55 = str20;
                        kSerializerArr2 = kSerializerArr;
                        i2 = 19;
                        break;
                    case 5:
                        kSerializerArr = kSerializerArr2;
                        str20 = str55;
                        str22 = str57;
                        str30 = str64;
                        str25 = str61;
                        str26 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 5, StringSerializer.INSTANCE, str62);
                        str19 = str46;
                        i3 |= 32;
                        str47 = str30;
                        str29 = str56;
                        str23 = str59;
                        str28 = str60;
                        str56 = str29;
                        str60 = str28;
                        str59 = str23;
                        str46 = str19;
                        str62 = str26;
                        str61 = str25;
                        str57 = str22;
                        str55 = str20;
                        kSerializerArr2 = kSerializerArr;
                        i2 = 19;
                        break;
                    case 6:
                        kSerializerArr = kSerializerArr2;
                        str20 = str55;
                        str22 = str57;
                        str25 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 6, StringSerializer.INSTANCE, str61);
                        str19 = str46;
                        i3 |= 64;
                        str47 = str64;
                        str29 = str56;
                        str23 = str59;
                        str28 = str60;
                        str26 = str62;
                        str56 = str29;
                        str60 = str28;
                        str59 = str23;
                        str46 = str19;
                        str62 = str26;
                        str61 = str25;
                        str57 = str22;
                        str55 = str20;
                        kSerializerArr2 = kSerializerArr;
                        i2 = 19;
                        break;
                    case 7:
                        kSerializerArr = kSerializerArr2;
                        str20 = str55;
                        str22 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 7, StringSerializer.INSTANCE, str57);
                        str19 = str46;
                        i3 |= 128;
                        str47 = str64;
                        str29 = str56;
                        str23 = str59;
                        str28 = str60;
                        str25 = str61;
                        str26 = str62;
                        str56 = str29;
                        str60 = str28;
                        str59 = str23;
                        str46 = str19;
                        str62 = str26;
                        str61 = str25;
                        str57 = str22;
                        str55 = str20;
                        kSerializerArr2 = kSerializerArr;
                        i2 = 19;
                        break;
                    case 8:
                        kSerializerArr = kSerializerArr2;
                        str20 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 8, StringSerializer.INSTANCE, str55);
                        str19 = str46;
                        i3 |= 256;
                        str47 = str64;
                        str29 = str56;
                        str22 = str57;
                        str23 = str59;
                        str28 = str60;
                        str25 = str61;
                        str26 = str62;
                        str56 = str29;
                        str60 = str28;
                        str59 = str23;
                        str46 = str19;
                        str62 = str26;
                        str61 = str25;
                        str57 = str22;
                        str55 = str20;
                        kSerializerArr2 = kSerializerArr;
                        i2 = 19;
                        break;
                    case 9:
                        kSerializerArr = kSerializerArr2;
                        str19 = str46;
                        i3 |= 512;
                        str20 = str55;
                        str29 = str56;
                        str22 = str57;
                        str23 = str59;
                        str25 = str61;
                        str26 = str62;
                        str47 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 9, StringSerializer.INSTANCE, str64);
                        str28 = str60;
                        str56 = str29;
                        str60 = str28;
                        str59 = str23;
                        str46 = str19;
                        str62 = str26;
                        str61 = str25;
                        str57 = str22;
                        str55 = str20;
                        kSerializerArr2 = kSerializerArr;
                        i2 = 19;
                        break;
                    case 10:
                        i3 |= 1024;
                        kSerializerArr = kSerializerArr2;
                        str19 = str46;
                        str52 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 10, StringSerializer.INSTANCE, str52);
                        str20 = str55;
                        str29 = str56;
                        str22 = str57;
                        str23 = str59;
                        str28 = str60;
                        str25 = str61;
                        str26 = str62;
                        str47 = str64;
                        str56 = str29;
                        str60 = str28;
                        str59 = str23;
                        str46 = str19;
                        str62 = str26;
                        str61 = str25;
                        str57 = str22;
                        str55 = str20;
                        kSerializerArr2 = kSerializerArr;
                        i2 = 19;
                        break;
                    case 11:
                        i3 |= 2048;
                        kSerializerArr = kSerializerArr2;
                        str19 = str46;
                        str51 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 11, StringSerializer.INSTANCE, str51);
                        str20 = str55;
                        str29 = str56;
                        str22 = str57;
                        str23 = str59;
                        str28 = str60;
                        str25 = str61;
                        str26 = str62;
                        str47 = str64;
                        str56 = str29;
                        str60 = str28;
                        str59 = str23;
                        str46 = str19;
                        str62 = str26;
                        str61 = str25;
                        str57 = str22;
                        str55 = str20;
                        kSerializerArr2 = kSerializerArr;
                        i2 = 19;
                        break;
                    case 12:
                        i3 |= 4096;
                        kSerializerArr = kSerializerArr2;
                        str19 = str46;
                        str50 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 12, StringSerializer.INSTANCE, str50);
                        str20 = str55;
                        str29 = str56;
                        str22 = str57;
                        str23 = str59;
                        str28 = str60;
                        str25 = str61;
                        str26 = str62;
                        str47 = str64;
                        str56 = str29;
                        str60 = str28;
                        str59 = str23;
                        str46 = str19;
                        str62 = str26;
                        str61 = str25;
                        str57 = str22;
                        str55 = str20;
                        kSerializerArr2 = kSerializerArr;
                        i2 = 19;
                        break;
                    case 13:
                        kSerializerArr = kSerializerArr2;
                        str19 = str46;
                        i3 |= 8192;
                        str20 = str55;
                        str29 = str56;
                        str22 = str57;
                        str23 = str59;
                        str28 = str60;
                        str25 = str61;
                        str26 = str62;
                        str49 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 13, StringSerializer.INSTANCE, str49);
                        str47 = str64;
                        str56 = str29;
                        str60 = str28;
                        str59 = str23;
                        str46 = str19;
                        str62 = str26;
                        str61 = str25;
                        str57 = str22;
                        str55 = str20;
                        kSerializerArr2 = kSerializerArr;
                        i2 = 19;
                        break;
                    case 14:
                        i3 |= 16384;
                        kSerializerArr = kSerializerArr2;
                        str19 = str46;
                        str53 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 14, StringSerializer.INSTANCE, str53);
                        str20 = str55;
                        str29 = str56;
                        str22 = str57;
                        str23 = str59;
                        str28 = str60;
                        str25 = str61;
                        str26 = str62;
                        str47 = str64;
                        str56 = str29;
                        str60 = str28;
                        str59 = str23;
                        str46 = str19;
                        str62 = str26;
                        str61 = str25;
                        str57 = str22;
                        str55 = str20;
                        kSerializerArr2 = kSerializerArr;
                        i2 = 19;
                        break;
                    case 15:
                        kSerializerArr = kSerializerArr2;
                        str19 = str46;
                        i3 = 32768 | i3;
                        str20 = str55;
                        str29 = str56;
                        str22 = str57;
                        str23 = str59;
                        str28 = str60;
                        str25 = str61;
                        str26 = str62;
                        str63 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 15, StringSerializer.INSTANCE, str63);
                        str47 = str64;
                        str56 = str29;
                        str60 = str28;
                        str59 = str23;
                        str46 = str19;
                        str62 = str26;
                        str61 = str25;
                        str57 = str22;
                        str55 = str20;
                        kSerializerArr2 = kSerializerArr;
                        i2 = 19;
                        break;
                    case 16:
                        i3 |= 65536;
                        kSerializerArr = kSerializerArr2;
                        str19 = str46;
                        str54 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 16, StringSerializer.INSTANCE, str54);
                        str20 = str55;
                        str29 = str56;
                        str22 = str57;
                        str23 = str59;
                        str28 = str60;
                        str25 = str61;
                        str26 = str62;
                        str47 = str64;
                        str56 = str29;
                        str60 = str28;
                        str59 = str23;
                        str46 = str19;
                        str62 = str26;
                        str61 = str25;
                        str57 = str22;
                        str55 = str20;
                        kSerializerArr2 = kSerializerArr;
                        i2 = 19;
                        break;
                    case 17:
                        kSerializerArr = kSerializerArr2;
                        str19 = str46;
                        i3 = 131072 | i3;
                        str20 = str55;
                        str29 = str56;
                        str22 = str57;
                        str23 = str59;
                        str28 = str60;
                        str25 = str61;
                        str26 = str62;
                        str48 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 17, StringSerializer.INSTANCE, str48);
                        str47 = str64;
                        str56 = str29;
                        str60 = str28;
                        str59 = str23;
                        str46 = str19;
                        str62 = str26;
                        str61 = str25;
                        str57 = str22;
                        str55 = str20;
                        kSerializerArr2 = kSerializerArr;
                        i2 = 19;
                        break;
                    case 18:
                        str46 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 18, StringSerializer.INSTANCE, str46);
                        i3 |= 262144;
                        str47 = str64;
                        i2 = 19;
                        break;
                    case 19:
                        list2 = (List) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, i2, kSerializerArr2[i2], list2);
                        i3 |= 524288;
                        str47 = str64;
                        break;
                    default:
                        throw new UnknownFieldException(iDecodeElementIndex);
                }
            }
            str = str46;
            str2 = str63;
            str3 = str50;
            str4 = str51;
            str5 = str52;
            str6 = str53;
            z = zDecodeBooleanElement2;
            str7 = str62;
            str8 = str61;
            str9 = str55;
            str10 = str47;
            str11 = str58;
            str12 = str60;
            list = list2;
            str13 = str49;
            i = i3;
            str14 = str56;
            str15 = str59;
            str16 = str48;
            str17 = str54;
            str18 = str57;
        }
        compositeDecoderBeginStructure.endStructure(serialDescriptor);
        return new DcaAiData(i, str11, str14, str15, str12, z, str7, str8, str18, str9, str10, str5, str4, str3, str13, str6, str2, str17, str16, str, list, (SerializationConstructorMarker) null);
    }

    /* JADX DEBUG: Method merged with bridge method: serialize(Lkotlinx/serialization/encoding/Encoder;Ljava/lang/Object;)V */
    @Override // kotlinx.serialization.SerializationStrategy
    public final void serialize(@NotNull Encoder encoder, @NotNull DcaAiData dcaAiData) {
        Intrinsics.checkNotNullParameter(encoder, "");
        Intrinsics.checkNotNullParameter(dcaAiData, "");
        SerialDescriptor serialDescriptor = descriptor;
        CompositeEncoder compositeEncoderBeginStructure = encoder.beginStructure(serialDescriptor);
        DcaAiData.write$Self$OKTradeCore_trade_core(dcaAiData, compositeEncoderBeginStructure, serialDescriptor);
        compositeEncoderBeginStructure.endStructure(serialDescriptor);
    }
}
