package com.okinc.unify_trade.biz;

import kotlin.jvm.internal.Intrinsics;
import kotlinx.serialization.KSerializer;
import kotlinx.serialization.UnknownFieldException;
import kotlinx.serialization.builtins.BuiltinSerializersKt;
import kotlinx.serialization.descriptors.SerialDescriptor;
import kotlinx.serialization.encoding.CompositeDecoder;
import kotlinx.serialization.encoding.CompositeEncoder;
import kotlinx.serialization.encoding.Decoder;
import kotlinx.serialization.encoding.Encoder;
import kotlinx.serialization.internal.GeneratedSerializer;
import kotlinx.serialization.internal.PluginGeneratedSerialDescriptor;
import kotlinx.serialization.internal.SerializationConstructorMarker;
import kotlinx.serialization.internal.StringSerializer;
import org.jetbrains.annotations.NotNull;

/* JADX INFO: loaded from: classes19.dex */
public final /* synthetic */ class SignalProviderSignalBean$$serializer implements GeneratedSerializer<SignalProviderSignalBean> {
    public static final int $stable;
    public static final SignalProviderSignalBean$$serializer INSTANCE;
    private static final SerialDescriptor descriptor;

    /* JADX DEBUG: Don't trust debug lines info. Lines numbers was adjusted: min line is 0 */
    private SignalProviderSignalBean$$serializer() {
    }

    /* JADX DEBUG: Don't trust debug lines info. Lines numbers was adjusted: min line is 0 */
    @Override // kotlinx.serialization.KSerializer, kotlinx.serialization.SerializationStrategy, kotlinx.serialization.DeserializationStrategy
    public final SerialDescriptor getDescriptor() {
        return descriptor;
    }

    static {
        SignalProviderSignalBean$$serializer signalProviderSignalBean$$serializer = new SignalProviderSignalBean$$serializer();
        INSTANCE = signalProviderSignalBean$$serializer;
        $stable = 8;
        PluginGeneratedSerialDescriptor pluginGeneratedSerialDescriptor = new PluginGeneratedSerialDescriptor("com.okinc.unify_trade.biz.SignalProviderSignalBean", signalProviderSignalBean$$serializer, 25);
        pluginGeneratedSerialDescriptor.addElement("accumulatedProfitSharing", true);
        pluginGeneratedSerialDescriptor.addElement("accumulatedSubscriptionAmount", true);
        pluginGeneratedSerialDescriptor.addElement("approvalStatus", true);
        pluginGeneratedSerialDescriptor.addElement("cTime", true);
        pluginGeneratedSerialDescriptor.addElement("estimatedProfitSharing", true);
        pluginGeneratedSerialDescriptor.addElement("estimatedSubscriptionAmount", true);
        pluginGeneratedSerialDescriptor.addElement("profitSharingCcy", true);
        pluginGeneratedSerialDescriptor.addElement("profitSharingFollowerAssets", true);
        pluginGeneratedSerialDescriptor.addElement("profitSharingFollowerCount", true);
        pluginGeneratedSerialDescriptor.addElement("profitSharingRatio", true);
        pluginGeneratedSerialDescriptor.addElement("signalChanId", true);
        pluginGeneratedSerialDescriptor.addElement("signalDescription", true);
        pluginGeneratedSerialDescriptor.addElement("signalChanName", true);
        pluginGeneratedSerialDescriptor.addElement("subscriptionFee", true);
        pluginGeneratedSerialDescriptor.addElement("subscriptionFeeCcy", true);
        pluginGeneratedSerialDescriptor.addElement("subscriptionFollowerAssets", true);
        pluginGeneratedSerialDescriptor.addElement("subscriptionFollowerCount", true);
        pluginGeneratedSerialDescriptor.addElement("subscriptionType", true);
        pluginGeneratedSerialDescriptor.addElement("totalFollowerCount", true);
        pluginGeneratedSerialDescriptor.addElement("uTime", true);
        pluginGeneratedSerialDescriptor.addElement("freeFollowerAssets", true);
        pluginGeneratedSerialDescriptor.addElement("freeFollowerCount", true);
        pluginGeneratedSerialDescriptor.addElement("instIds", true);
        pluginGeneratedSerialDescriptor.addElement("recommendInvestAmount", true);
        pluginGeneratedSerialDescriptor.addElement("recommendLeverage", true);
        descriptor = pluginGeneratedSerialDescriptor;
    }

    @Override // kotlinx.serialization.internal.GeneratedSerializer
    public final KSerializer<?>[] childSerializers() {
        StringSerializer stringSerializer = StringSerializer.INSTANCE;
        return new KSerializer[]{BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), stringSerializer, stringSerializer, BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer)};
    }

    /* JADX DEBUG: Method merged with bridge method: deserialize(Lkotlinx/serialization/encoding/Decoder;)Ljava/lang/Object; */
    @Override // kotlinx.serialization.DeserializationStrategy
    public final SignalProviderSignalBean deserialize(@NotNull Decoder decoder) {
        String str;
        String str2;
        String str3;
        String str4;
        String str5;
        String str6;
        String str7;
        String str8;
        String str9;
        String str10;
        String str11;
        String str12;
        String str13;
        String str14;
        String str15;
        int i;
        String str16;
        String str17;
        String str18;
        String str19;
        String str20;
        String str21;
        String str22;
        String str23;
        String str24;
        String str25;
        String str26;
        int i2;
        String str27;
        String str28;
        String str29;
        String str30;
        String str31;
        String str32;
        String str33;
        String str34;
        String str35;
        String str36;
        String str37;
        String str38;
        String str39;
        String str40;
        String str41;
        String str42;
        Intrinsics.checkNotNullParameter(decoder, "");
        SerialDescriptor serialDescriptor = descriptor;
        CompositeDecoder compositeDecoderBeginStructure = decoder.beginStructure(serialDescriptor);
        String str43 = null;
        if (compositeDecoderBeginStructure.decodeSequentially()) {
            StringSerializer stringSerializer = StringSerializer.INSTANCE;
            String str44 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 0, stringSerializer, null);
            String str45 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 1, stringSerializer, null);
            String str46 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 2, stringSerializer, null);
            String str47 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 3, stringSerializer, null);
            String str48 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 4, stringSerializer, null);
            String str49 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 5, stringSerializer, null);
            String str50 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 6, stringSerializer, null);
            str14 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 7, stringSerializer, null);
            String str51 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 8, stringSerializer, null);
            String str52 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 9, stringSerializer, null);
            String str53 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 10, stringSerializer, null);
            String strDecodeStringElement = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 11);
            String strDecodeStringElement2 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 12);
            String str54 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 13, stringSerializer, null);
            str = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 14, stringSerializer, null);
            String str55 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 15, stringSerializer, null);
            String str56 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 16, stringSerializer, null);
            String str57 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 17, stringSerializer, null);
            String str58 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 18, stringSerializer, null);
            String str59 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 19, stringSerializer, null);
            String str60 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 20, stringSerializer, null);
            String str61 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 21, stringSerializer, null);
            String str62 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 22, stringSerializer, null);
            String str63 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 23, stringSerializer, null);
            str17 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 24, stringSerializer, null);
            str24 = str47;
            str12 = str61;
            str16 = str62;
            str23 = str63;
            str11 = str60;
            str25 = str59;
            str21 = str58;
            str3 = str53;
            str6 = str52;
            str22 = str50;
            str13 = str49;
            str15 = str51;
            str10 = str57;
            i = 33554431;
            str5 = strDecodeStringElement;
            str4 = str48;
            str20 = str46;
            str9 = str44;
            str18 = str45;
            str2 = str56;
            str8 = strDecodeStringElement2;
            str19 = str55;
            str7 = str54;
        } else {
            int i3 = 0;
            boolean z = true;
            String str64 = null;
            String str65 = null;
            String str66 = null;
            String str67 = null;
            String str68 = null;
            String str69 = null;
            String str70 = null;
            String str71 = null;
            String str72 = null;
            String str73 = null;
            String str74 = null;
            String str75 = null;
            String strDecodeStringElement3 = null;
            String str76 = null;
            String strDecodeStringElement4 = null;
            String str77 = null;
            String str78 = null;
            String str79 = null;
            String str80 = null;
            String str81 = null;
            String str82 = null;
            String str83 = null;
            String str84 = null;
            String str85 = null;
            while (z) {
                String str86 = str65;
                int iDecodeElementIndex = compositeDecoderBeginStructure.decodeElementIndex(serialDescriptor);
                switch (iDecodeElementIndex) {
                    case -1:
                        str27 = str66;
                        str28 = str67;
                        z = false;
                        str65 = str86;
                        str67 = str28;
                        str66 = str27;
                        break;
                    case 0:
                        str29 = str64;
                        str27 = str66;
                        str28 = str67;
                        str30 = str76;
                        str31 = str77;
                        str32 = str78;
                        str33 = str79;
                        str34 = str80;
                        str35 = str81;
                        str36 = str82;
                        str37 = str83;
                        str38 = str85;
                        str39 = str86;
                        str84 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 0, StringSerializer.INSTANCE, str84);
                        i3 |= 1;
                        str41 = str39;
                        str65 = str41;
                        str83 = str37;
                        str64 = str29;
                        str81 = str35;
                        str80 = str34;
                        str82 = str36;
                        str79 = str33;
                        str78 = str32;
                        str76 = str30;
                        str77 = str31;
                        str85 = str38;
                        str67 = str28;
                        str66 = str27;
                        break;
                    case 1:
                        str29 = str64;
                        str27 = str66;
                        str28 = str67;
                        str30 = str76;
                        str31 = str77;
                        str32 = str78;
                        str33 = str79;
                        str34 = str80;
                        str36 = str82;
                        str38 = str85;
                        str35 = str81;
                        str83 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 1, StringSerializer.INSTANCE, str83);
                        i3 |= 2;
                        str39 = str86;
                        str37 = str83;
                        str41 = str39;
                        str65 = str41;
                        str83 = str37;
                        str64 = str29;
                        str81 = str35;
                        str80 = str34;
                        str82 = str36;
                        str79 = str33;
                        str78 = str32;
                        str76 = str30;
                        str77 = str31;
                        str85 = str38;
                        str67 = str28;
                        str66 = str27;
                        break;
                    case 2:
                        str29 = str64;
                        str27 = str66;
                        str28 = str67;
                        str30 = str76;
                        str31 = str77;
                        str32 = str78;
                        str33 = str79;
                        str36 = str82;
                        str38 = str85;
                        str34 = str80;
                        str81 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 2, StringSerializer.INSTANCE, str81);
                        i3 |= 4;
                        str39 = str86;
                        str35 = str81;
                        str37 = str83;
                        str41 = str39;
                        str65 = str41;
                        str83 = str37;
                        str64 = str29;
                        str81 = str35;
                        str80 = str34;
                        str82 = str36;
                        str79 = str33;
                        str78 = str32;
                        str76 = str30;
                        str77 = str31;
                        str85 = str38;
                        str67 = str28;
                        str66 = str27;
                        break;
                    case 3:
                        str29 = str64;
                        str27 = str66;
                        str28 = str67;
                        str30 = str76;
                        str31 = str77;
                        str32 = str78;
                        str33 = str79;
                        str38 = str85;
                        str36 = str82;
                        i3 |= 8;
                        str39 = str86;
                        str34 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 3, StringSerializer.INSTANCE, str80);
                        str35 = str81;
                        str37 = str83;
                        str41 = str39;
                        str65 = str41;
                        str83 = str37;
                        str64 = str29;
                        str81 = str35;
                        str80 = str34;
                        str82 = str36;
                        str79 = str33;
                        str78 = str32;
                        str76 = str30;
                        str77 = str31;
                        str85 = str38;
                        str67 = str28;
                        str66 = str27;
                        break;
                    case 4:
                        str29 = str64;
                        str27 = str66;
                        str28 = str67;
                        str30 = str76;
                        str31 = str77;
                        str32 = str78;
                        str38 = str85;
                        str33 = str79;
                        str82 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 4, StringSerializer.INSTANCE, str82);
                        i3 |= 16;
                        str39 = str86;
                        str34 = str80;
                        str35 = str81;
                        str36 = str82;
                        str37 = str83;
                        str41 = str39;
                        str65 = str41;
                        str83 = str37;
                        str64 = str29;
                        str81 = str35;
                        str80 = str34;
                        str82 = str36;
                        str79 = str33;
                        str78 = str32;
                        str76 = str30;
                        str77 = str31;
                        str85 = str38;
                        str67 = str28;
                        str66 = str27;
                        break;
                    case 5:
                        str29 = str64;
                        str27 = str66;
                        str28 = str67;
                        str30 = str76;
                        str31 = str77;
                        str38 = str85;
                        str32 = str78;
                        str79 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 5, StringSerializer.INSTANCE, str79);
                        i3 |= 32;
                        str39 = str86;
                        str33 = str79;
                        str34 = str80;
                        str35 = str81;
                        str36 = str82;
                        str37 = str83;
                        str41 = str39;
                        str65 = str41;
                        str83 = str37;
                        str64 = str29;
                        str81 = str35;
                        str80 = str34;
                        str82 = str36;
                        str79 = str33;
                        str78 = str32;
                        str76 = str30;
                        str77 = str31;
                        str85 = str38;
                        str67 = str28;
                        str66 = str27;
                        break;
                    case 6:
                        str29 = str64;
                        str27 = str66;
                        str28 = str67;
                        str31 = str77;
                        str38 = str85;
                        str40 = str86;
                        str30 = str76;
                        str78 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 6, StringSerializer.INSTANCE, str78);
                        i3 |= 64;
                        str39 = str40;
                        str32 = str78;
                        str33 = str79;
                        str34 = str80;
                        str35 = str81;
                        str36 = str82;
                        str37 = str83;
                        str41 = str39;
                        str65 = str41;
                        str83 = str37;
                        str64 = str29;
                        str81 = str35;
                        str80 = str34;
                        str82 = str36;
                        str79 = str33;
                        str78 = str32;
                        str76 = str30;
                        str77 = str31;
                        str85 = str38;
                        str67 = str28;
                        str66 = str27;
                        break;
                    case 7:
                        str29 = str64;
                        str27 = str66;
                        str28 = str67;
                        str38 = str85;
                        str40 = str86;
                        str31 = str77;
                        i3 |= 128;
                        str30 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 7, StringSerializer.INSTANCE, str76);
                        str39 = str40;
                        str32 = str78;
                        str33 = str79;
                        str34 = str80;
                        str35 = str81;
                        str36 = str82;
                        str37 = str83;
                        str41 = str39;
                        str65 = str41;
                        str83 = str37;
                        str64 = str29;
                        str81 = str35;
                        str80 = str34;
                        str82 = str36;
                        str79 = str33;
                        str78 = str32;
                        str76 = str30;
                        str77 = str31;
                        str85 = str38;
                        str67 = str28;
                        str66 = str27;
                        break;
                    case 8:
                        str29 = str64;
                        str27 = str66;
                        str28 = str67;
                        str38 = str85;
                        i3 |= 256;
                        str31 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 8, StringSerializer.INSTANCE, str77);
                        str39 = str86;
                        str30 = str76;
                        str32 = str78;
                        str33 = str79;
                        str34 = str80;
                        str35 = str81;
                        str36 = str82;
                        str37 = str83;
                        str41 = str39;
                        str65 = str41;
                        str83 = str37;
                        str64 = str29;
                        str81 = str35;
                        str80 = str34;
                        str82 = str36;
                        str79 = str33;
                        str78 = str32;
                        str76 = str30;
                        str77 = str31;
                        str85 = str38;
                        str67 = str28;
                        str66 = str27;
                        break;
                    case 9:
                        str29 = str64;
                        str27 = str66;
                        str28 = str67;
                        i3 |= 512;
                        str38 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 9, StringSerializer.INSTANCE, str85);
                        str39 = str86;
                        str30 = str76;
                        str31 = str77;
                        str32 = str78;
                        str33 = str79;
                        str34 = str80;
                        str35 = str81;
                        str36 = str82;
                        str37 = str83;
                        str41 = str39;
                        str65 = str41;
                        str83 = str37;
                        str64 = str29;
                        str81 = str35;
                        str80 = str34;
                        str82 = str36;
                        str79 = str33;
                        str78 = str32;
                        str76 = str30;
                        str77 = str31;
                        str85 = str38;
                        str67 = str28;
                        str66 = str27;
                        break;
                    case 10:
                        str29 = str64;
                        str27 = str66;
                        str41 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 10, StringSerializer.INSTANCE, str86);
                        i3 |= 1024;
                        str28 = str67;
                        str30 = str76;
                        str31 = str77;
                        str32 = str78;
                        str33 = str79;
                        str34 = str80;
                        str35 = str81;
                        str36 = str82;
                        str37 = str83;
                        str38 = str85;
                        str65 = str41;
                        str83 = str37;
                        str64 = str29;
                        str81 = str35;
                        str80 = str34;
                        str82 = str36;
                        str79 = str33;
                        str78 = str32;
                        str76 = str30;
                        str77 = str31;
                        str85 = str38;
                        str67 = str28;
                        str66 = str27;
                        break;
                    case 11:
                        str42 = str64;
                        strDecodeStringElement3 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 11);
                        i3 |= 2048;
                        str64 = str42;
                        str65 = str86;
                        break;
                    case 12:
                        str42 = str64;
                        strDecodeStringElement4 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 12);
                        i3 |= 4096;
                        str64 = str42;
                        str65 = str86;
                        break;
                    case 13:
                        str42 = str64;
                        i3 |= 8192;
                        str66 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 13, StringSerializer.INSTANCE, str66);
                        str64 = str42;
                        str65 = str86;
                        break;
                    case 14:
                        str26 = str66;
                        i3 |= 16384;
                        str68 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 14, StringSerializer.INSTANCE, str68);
                        str65 = str86;
                        str66 = str26;
                        break;
                    case 15:
                        str26 = str66;
                        str70 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 15, StringSerializer.INSTANCE, str70);
                        i2 = 32768;
                        i3 |= i2;
                        str65 = str86;
                        str66 = str26;
                        break;
                    case 16:
                        str26 = str66;
                        str71 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 16, StringSerializer.INSTANCE, str71);
                        i2 = 65536;
                        i3 |= i2;
                        str65 = str86;
                        str66 = str26;
                        break;
                    case 17:
                        str26 = str66;
                        str72 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 17, StringSerializer.INSTANCE, str72);
                        i2 = 131072;
                        i3 |= i2;
                        str65 = str86;
                        str66 = str26;
                        break;
                    case 18:
                        str26 = str66;
                        str73 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 18, StringSerializer.INSTANCE, str73);
                        i2 = 262144;
                        i3 |= i2;
                        str65 = str86;
                        str66 = str26;
                        break;
                    case 19:
                        str26 = str66;
                        str67 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 19, StringSerializer.INSTANCE, str67);
                        i2 = 524288;
                        i3 |= i2;
                        str65 = str86;
                        str66 = str26;
                        break;
                    case 20:
                        str26 = str66;
                        str74 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 20, StringSerializer.INSTANCE, str74);
                        i2 = 1048576;
                        i3 |= i2;
                        str65 = str86;
                        str66 = str26;
                        break;
                    case 21:
                        str26 = str66;
                        str75 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 21, StringSerializer.INSTANCE, str75);
                        i2 = 2097152;
                        i3 |= i2;
                        str65 = str86;
                        str66 = str26;
                        break;
                    case 22:
                        str26 = str66;
                        str69 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 22, StringSerializer.INSTANCE, str69);
                        i2 = 4194304;
                        i3 |= i2;
                        str65 = str86;
                        str66 = str26;
                        break;
                    case 23:
                        str26 = str66;
                        str43 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 23, StringSerializer.INSTANCE, str43);
                        i2 = 8388608;
                        i3 |= i2;
                        str65 = str86;
                        str66 = str26;
                        break;
                    case 24:
                        str26 = str66;
                        str64 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 24, StringSerializer.INSTANCE, str64);
                        i2 = 16777216;
                        i3 |= i2;
                        str65 = str86;
                        str66 = str26;
                        break;
                    default:
                        throw new UnknownFieldException(iDecodeElementIndex);
                }
            }
            String str87 = str67;
            str = str68;
            str2 = str71;
            str3 = str65;
            str4 = str82;
            str5 = strDecodeStringElement3;
            str6 = str85;
            str7 = str66;
            str8 = strDecodeStringElement4;
            str9 = str84;
            str10 = str72;
            str11 = str74;
            str12 = str75;
            str13 = str79;
            str14 = str76;
            str15 = str77;
            i = i3;
            str16 = str69;
            str17 = str64;
            str18 = str83;
            str19 = str70;
            str20 = str81;
            str21 = str73;
            str22 = str78;
            str23 = str43;
            str24 = str80;
            str25 = str87;
        }
        compositeDecoderBeginStructure.endStructure(serialDescriptor);
        return new SignalProviderSignalBean(i, str9, str18, str20, str24, str4, str13, str22, str14, str15, str6, str3, str5, str8, str7, str, str19, str2, str10, str21, str25, str11, str12, str16, str23, str17, (SerializationConstructorMarker) null);
    }

    /* JADX DEBUG: Method merged with bridge method: serialize(Lkotlinx/serialization/encoding/Encoder;Ljava/lang/Object;)V */
    @Override // kotlinx.serialization.SerializationStrategy
    public final void serialize(@NotNull Encoder encoder, @NotNull SignalProviderSignalBean signalProviderSignalBean) {
        Intrinsics.checkNotNullParameter(encoder, "");
        Intrinsics.checkNotNullParameter(signalProviderSignalBean, "");
        SerialDescriptor serialDescriptor = descriptor;
        CompositeEncoder compositeEncoderBeginStructure = encoder.beginStructure(serialDescriptor);
        SignalProviderSignalBean.write$Self$OKTradeCore_trade_core(signalProviderSignalBean, compositeEncoderBeginStructure, serialDescriptor);
        compositeEncoderBeginStructure.endStructure(serialDescriptor);
    }
}
