package com.okinc.unify_trade.biz;

import com.google.api.client.googleapis.media.MediaHttpDownloader;
import com.okinc.web3.security.track.Web3SecurityTrackEvent;
import java.util.List;
import kotlin.jvm.internal.Intrinsics;
import kotlinx.serialization.KSerializer;
import kotlinx.serialization.UnknownFieldException;
import kotlinx.serialization.builtins.BuiltinSerializersKt;
import kotlinx.serialization.descriptors.SerialDescriptor;
import kotlinx.serialization.encoding.CompositeDecoder;
import kotlinx.serialization.encoding.CompositeEncoder;
import kotlinx.serialization.encoding.Decoder;
import kotlinx.serialization.encoding.Encoder;
import kotlinx.serialization.internal.BooleanSerializer;
import kotlinx.serialization.internal.GeneratedSerializer;
import kotlinx.serialization.internal.IntSerializer;
import kotlinx.serialization.internal.PluginGeneratedSerialDescriptor;
import kotlinx.serialization.internal.SerializationConstructorMarker;
import kotlinx.serialization.internal.StringSerializer;
import org.jetbrains.annotations.NotNull;

/* JADX INFO: loaded from: classes17.dex */
public final /* synthetic */ class TradeInfo$$serializer implements GeneratedSerializer<TradeInfo> {
    public static final int $stable;
    public static final TradeInfo$$serializer INSTANCE;
    private static final SerialDescriptor descriptor;

    /* JADX DEBUG: Don't trust debug lines info. Lines numbers was adjusted: min line is 0 */
    private TradeInfo$$serializer() {
    }

    /* JADX DEBUG: Don't trust debug lines info. Lines numbers was adjusted: min line is 0 */
    @Override // kotlinx.serialization.KSerializer, kotlinx.serialization.SerializationStrategy, kotlinx.serialization.DeserializationStrategy
    public final SerialDescriptor getDescriptor() {
        return descriptor;
    }

    static {
        TradeInfo$$serializer tradeInfo$$serializer = new TradeInfo$$serializer();
        INSTANCE = tradeInfo$$serializer;
        $stable = 8;
        PluginGeneratedSerialDescriptor pluginGeneratedSerialDescriptor = new PluginGeneratedSerialDescriptor("com.okinc.unify_trade.biz.TradeInfo", tradeInfo$$serializer, 28);
        pluginGeneratedSerialDescriptor.addElement("invertTradeUnit", true);
        pluginGeneratedSerialDescriptor.addElement("inverseFuturesUnit", true);
        pluginGeneratedSerialDescriptor.addElement("linearTradeUnit", true);
        pluginGeneratedSerialDescriptor.addElement(Web3SecurityTrackEvent.VALUE_CONFIRM, true);
        pluginGeneratedSerialDescriptor.addElement("depthCountConfirm", true);
        pluginGeneratedSerialDescriptor.addElement("kLineWithPriceConfig", true);
        pluginGeneratedSerialDescriptor.addElement("ccy", true);
        pluginGeneratedSerialDescriptor.addElement("greekUnit", true);
        pluginGeneratedSerialDescriptor.addElement("kLineConfig", true);
        pluginGeneratedSerialDescriptor.addElement("manualKLineConfig", true);
        pluginGeneratedSerialDescriptor.addElement("mktCloseConfirm", true);
        pluginGeneratedSerialDescriptor.addElement("liqPxSwitch", true);
        pluginGeneratedSerialDescriptor.addElement("uplPriceType", true);
        pluginGeneratedSerialDescriptor.addElement("reversePosEnable", true);
        pluginGeneratedSerialDescriptor.addElement("placeLayoutConfig", true);
        pluginGeneratedSerialDescriptor.addElement("reversePosConfirm", true);
        pluginGeneratedSerialDescriptor.addElement("tabCustomConfig", true);
        pluginGeneratedSerialDescriptor.addElement("stableCoin", true);
        pluginGeneratedSerialDescriptor.addElement("supportedStableCoin", true);
        pluginGeneratedSerialDescriptor.addElement("hostingShow", true);
        pluginGeneratedSerialDescriptor.addElement("hostingStatus", true);
        pluginGeneratedSerialDescriptor.addElement("curPosHostingShow", true);
        pluginGeneratedSerialDescriptor.addElement("spotAverageConfig", true);
        pluginGeneratedSerialDescriptor.addElement("scaleOrderNum", true);
        pluginGeneratedSerialDescriptor.addElement("enableUseNewPotential", true);
        pluginGeneratedSerialDescriptor.addElement("chasePriceConfirm", true);
        pluginGeneratedSerialDescriptor.addElement("simpleBorrowAgreementConfirm", true);
        pluginGeneratedSerialDescriptor.addElement("realizedPnlSwitch", true);
        descriptor = pluginGeneratedSerialDescriptor;
    }

    @Override // kotlinx.serialization.internal.GeneratedSerializer
    public final KSerializer<?>[] childSerializers() {
        KSerializer[] kSerializerArr = TradeInfo.$childSerializers;
        StringSerializer stringSerializer = StringSerializer.INSTANCE;
        IntSerializer intSerializer = IntSerializer.INSTANCE;
        return new KSerializer[]{stringSerializer, stringSerializer, stringSerializer, stringSerializer, stringSerializer, stringSerializer, stringSerializer, stringSerializer, stringSerializer, stringSerializer, stringSerializer, stringSerializer, BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(kSerializerArr[16]), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(kSerializerArr[18]), BuiltinSerializersKt.getNullable(intSerializer), BuiltinSerializersKt.getNullable(intSerializer), BuiltinSerializersKt.getNullable(intSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(intSerializer), BooleanSerializer.INSTANCE, BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer)};
    }

    /* JADX DEBUG: Method merged with bridge method: deserialize(Lkotlinx/serialization/encoding/Decoder;)Ljava/lang/Object; */
    @Override // kotlinx.serialization.DeserializationStrategy
    public final TradeInfo deserialize(@NotNull Decoder decoder) {
        String str;
        List list;
        Integer num;
        String str2;
        List list2;
        Integer num2;
        String str3;
        String str4;
        String str5;
        String str6;
        String str7;
        String str8;
        String str9;
        String str10;
        String str11;
        boolean z;
        String str12;
        String str13;
        String str14;
        String str15;
        String str16;
        String str17;
        Integer num3;
        String str18;
        int i;
        Integer num4;
        String str19;
        String str20;
        String str21;
        List list3;
        Integer num5;
        int i2;
        int i3;
        String str22;
        String str23;
        String str24;
        Integer num6;
        Integer num7;
        String str25;
        Integer num8;
        Integer num9;
        KSerializer[] kSerializerArr;
        String str26;
        List list4;
        Integer num10;
        String str27;
        String str28;
        String str29;
        String str30;
        Integer num11;
        Intrinsics.checkNotNullParameter(decoder, "");
        SerialDescriptor serialDescriptor = descriptor;
        CompositeDecoder compositeDecoderBeginStructure = decoder.beginStructure(serialDescriptor);
        KSerializer[] kSerializerArr2 = TradeInfo.$childSerializers;
        List list5 = null;
        if (compositeDecoderBeginStructure.decodeSequentially()) {
            String strDecodeStringElement = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 0);
            String strDecodeStringElement2 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 1);
            String strDecodeStringElement3 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 2);
            String strDecodeStringElement4 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 3);
            String strDecodeStringElement5 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 4);
            String strDecodeStringElement6 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 5);
            String strDecodeStringElement7 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 6);
            String strDecodeStringElement8 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 7);
            String strDecodeStringElement9 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 8);
            String strDecodeStringElement10 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 9);
            String strDecodeStringElement11 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 10);
            String strDecodeStringElement12 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 11);
            StringSerializer stringSerializer = StringSerializer.INSTANCE;
            str18 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 12, stringSerializer, null);
            String str31 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 13, stringSerializer, null);
            String str32 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 14, stringSerializer, null);
            String str33 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 15, stringSerializer, null);
            List list6 = (List) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 16, kSerializerArr2[16], null);
            String str34 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 17, stringSerializer, null);
            List list7 = (List) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 18, kSerializerArr2[18], null);
            IntSerializer intSerializer = IntSerializer.INSTANCE;
            Integer num12 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 19, intSerializer, null);
            Integer num13 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 20, intSerializer, null);
            Integer num14 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 21, intSerializer, null);
            String str35 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 22, stringSerializer, null);
            Integer num15 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 23, intSerializer, null);
            boolean zDecodeBooleanElement = compositeDecoderBeginStructure.decodeBooleanElement(serialDescriptor, 24);
            String str36 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 25, stringSerializer, null);
            String str37 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 26, stringSerializer, null);
            str4 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 27, stringSerializer, null);
            z = zDecodeBooleanElement;
            str17 = strDecodeStringElement2;
            num4 = num14;
            str19 = str35;
            num3 = num15;
            str2 = str36;
            str3 = str37;
            num2 = num13;
            i = 268435455;
            str5 = str34;
            num = num12;
            list = list6;
            list2 = list7;
            str13 = strDecodeStringElement7;
            str8 = strDecodeStringElement8;
            str12 = strDecodeStringElement12;
            str21 = strDecodeStringElement;
            str14 = strDecodeStringElement6;
            str15 = strDecodeStringElement5;
            str = str33;
            str7 = str31;
            str9 = strDecodeStringElement9;
            str11 = strDecodeStringElement11;
            str16 = strDecodeStringElement3;
            str10 = strDecodeStringElement10;
            str20 = strDecodeStringElement4;
            str6 = str32;
        } else {
            int i4 = 0;
            boolean zDecodeBooleanElement2 = false;
            boolean z2 = true;
            String str38 = null;
            List list8 = null;
            Integer num16 = null;
            String str39 = null;
            Integer num17 = null;
            String str40 = null;
            Integer num18 = null;
            Integer num19 = null;
            String str41 = null;
            String str42 = null;
            String str43 = null;
            String strDecodeStringElement13 = null;
            String strDecodeStringElement14 = null;
            String strDecodeStringElement15 = null;
            String strDecodeStringElement16 = null;
            String str44 = null;
            String str45 = null;
            String strDecodeStringElement17 = null;
            String strDecodeStringElement18 = null;
            String strDecodeStringElement19 = null;
            String strDecodeStringElement20 = null;
            String strDecodeStringElement21 = null;
            String strDecodeStringElement22 = null;
            String strDecodeStringElement23 = null;
            String strDecodeStringElement24 = null;
            String str46 = null;
            while (z2) {
                String str47 = str39;
                int iDecodeElementIndex = compositeDecoderBeginStructure.decodeElementIndex(serialDescriptor);
                switch (iDecodeElementIndex) {
                    case -1:
                        kSerializerArr = kSerializerArr2;
                        str26 = str38;
                        list4 = list8;
                        num10 = num16;
                        str27 = str44;
                        str28 = str45;
                        str29 = str46;
                        str30 = str47;
                        z2 = false;
                        str46 = str29;
                        list8 = list4;
                        kSerializerArr2 = kSerializerArr;
                        str38 = str26;
                        str44 = str27;
                        str45 = str28;
                        str39 = str30;
                        num16 = num10;
                        break;
                    case 0:
                        kSerializerArr = kSerializerArr2;
                        str26 = str38;
                        list4 = list8;
                        num10 = num16;
                        str27 = str44;
                        str28 = str45;
                        str29 = str46;
                        str30 = str47;
                        strDecodeStringElement24 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 0);
                        i4 |= 1;
                        str46 = str29;
                        list8 = list4;
                        kSerializerArr2 = kSerializerArr;
                        str38 = str26;
                        str44 = str27;
                        str45 = str28;
                        str39 = str30;
                        num16 = num10;
                        break;
                    case 1:
                        kSerializerArr = kSerializerArr2;
                        str26 = str38;
                        list4 = list8;
                        num10 = num16;
                        str27 = str44;
                        str28 = str45;
                        str29 = str46;
                        str30 = str47;
                        strDecodeStringElement23 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 1);
                        i4 |= 2;
                        str46 = str29;
                        list8 = list4;
                        kSerializerArr2 = kSerializerArr;
                        str38 = str26;
                        str44 = str27;
                        str45 = str28;
                        str39 = str30;
                        num16 = num10;
                        break;
                    case 2:
                        kSerializerArr = kSerializerArr2;
                        str26 = str38;
                        list4 = list8;
                        num10 = num16;
                        str27 = str44;
                        str28 = str45;
                        str29 = str46;
                        str30 = str47;
                        strDecodeStringElement22 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 2);
                        i4 |= 4;
                        str46 = str29;
                        list8 = list4;
                        kSerializerArr2 = kSerializerArr;
                        str38 = str26;
                        str44 = str27;
                        str45 = str28;
                        str39 = str30;
                        num16 = num10;
                        break;
                    case 3:
                        kSerializerArr = kSerializerArr2;
                        str26 = str38;
                        list4 = list8;
                        num10 = num16;
                        str27 = str44;
                        str28 = str45;
                        str29 = str46;
                        str30 = str47;
                        strDecodeStringElement21 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 3);
                        i4 |= 8;
                        str46 = str29;
                        list8 = list4;
                        kSerializerArr2 = kSerializerArr;
                        str38 = str26;
                        str44 = str27;
                        str45 = str28;
                        str39 = str30;
                        num16 = num10;
                        break;
                    case 4:
                        kSerializerArr = kSerializerArr2;
                        str26 = str38;
                        list4 = list8;
                        num10 = num16;
                        str27 = str44;
                        str28 = str45;
                        str29 = str46;
                        str30 = str47;
                        strDecodeStringElement20 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 4);
                        i4 |= 16;
                        str46 = str29;
                        list8 = list4;
                        kSerializerArr2 = kSerializerArr;
                        str38 = str26;
                        str44 = str27;
                        str45 = str28;
                        str39 = str30;
                        num16 = num10;
                        break;
                    case 5:
                        kSerializerArr = kSerializerArr2;
                        str26 = str38;
                        list4 = list8;
                        num10 = num16;
                        str27 = str44;
                        str28 = str45;
                        str29 = str46;
                        str30 = str47;
                        strDecodeStringElement19 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 5);
                        i4 |= 32;
                        str46 = str29;
                        list8 = list4;
                        kSerializerArr2 = kSerializerArr;
                        str38 = str26;
                        str44 = str27;
                        str45 = str28;
                        str39 = str30;
                        num16 = num10;
                        break;
                    case 6:
                        kSerializerArr = kSerializerArr2;
                        str26 = str38;
                        list4 = list8;
                        num10 = num16;
                        str27 = str44;
                        str28 = str45;
                        str29 = str46;
                        str30 = str47;
                        strDecodeStringElement18 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 6);
                        i4 |= 64;
                        str46 = str29;
                        list8 = list4;
                        kSerializerArr2 = kSerializerArr;
                        str38 = str26;
                        str44 = str27;
                        str45 = str28;
                        str39 = str30;
                        num16 = num10;
                        break;
                    case 7:
                        kSerializerArr = kSerializerArr2;
                        str26 = str38;
                        list4 = list8;
                        num10 = num16;
                        str27 = str44;
                        str28 = str45;
                        str29 = str46;
                        str30 = str47;
                        strDecodeStringElement13 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 7);
                        i4 |= 128;
                        str46 = str29;
                        list8 = list4;
                        kSerializerArr2 = kSerializerArr;
                        str38 = str26;
                        str44 = str27;
                        str45 = str28;
                        str39 = str30;
                        num16 = num10;
                        break;
                    case 8:
                        kSerializerArr = kSerializerArr2;
                        str26 = str38;
                        list4 = list8;
                        num10 = num16;
                        str27 = str44;
                        str28 = str45;
                        str29 = str46;
                        str30 = str47;
                        strDecodeStringElement14 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 8);
                        i4 |= 256;
                        str46 = str29;
                        list8 = list4;
                        kSerializerArr2 = kSerializerArr;
                        str38 = str26;
                        str44 = str27;
                        str45 = str28;
                        str39 = str30;
                        num16 = num10;
                        break;
                    case 9:
                        kSerializerArr = kSerializerArr2;
                        str26 = str38;
                        list4 = list8;
                        num10 = num16;
                        str27 = str44;
                        str28 = str45;
                        str29 = str46;
                        str30 = str47;
                        strDecodeStringElement15 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 9);
                        i4 |= 512;
                        str46 = str29;
                        list8 = list4;
                        kSerializerArr2 = kSerializerArr;
                        str38 = str26;
                        str44 = str27;
                        str45 = str28;
                        str39 = str30;
                        num16 = num10;
                        break;
                    case 10:
                        kSerializerArr = kSerializerArr2;
                        str26 = str38;
                        list4 = list8;
                        num10 = num16;
                        str27 = str44;
                        str28 = str45;
                        str29 = str46;
                        str30 = str47;
                        strDecodeStringElement16 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 10);
                        i4 |= 1024;
                        str46 = str29;
                        list8 = list4;
                        kSerializerArr2 = kSerializerArr;
                        str38 = str26;
                        str44 = str27;
                        str45 = str28;
                        str39 = str30;
                        num16 = num10;
                        break;
                    case 11:
                        kSerializerArr = kSerializerArr2;
                        str26 = str38;
                        list4 = list8;
                        num10 = num16;
                        str27 = str44;
                        str28 = str45;
                        str29 = str46;
                        str30 = str47;
                        strDecodeStringElement17 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 11);
                        i4 |= 2048;
                        str46 = str29;
                        list8 = list4;
                        kSerializerArr2 = kSerializerArr;
                        str38 = str26;
                        str44 = str27;
                        str45 = str28;
                        str39 = str30;
                        num16 = num10;
                        break;
                    case 12:
                        num10 = num16;
                        str30 = str47;
                        str28 = str45;
                        str46 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 12, StringSerializer.INSTANCE, str46);
                        i4 |= 4096;
                        list8 = list8;
                        kSerializerArr2 = kSerializerArr2;
                        str38 = str38;
                        str45 = str28;
                        str39 = str30;
                        num16 = num10;
                        break;
                    case 13:
                        kSerializerArr = kSerializerArr2;
                        str26 = str38;
                        list4 = list8;
                        num10 = num16;
                        str30 = str47;
                        str27 = str44;
                        i4 |= 8192;
                        str28 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 13, StringSerializer.INSTANCE, str45);
                        str29 = str46;
                        str46 = str29;
                        list8 = list4;
                        kSerializerArr2 = kSerializerArr;
                        str38 = str26;
                        str44 = str27;
                        str45 = str28;
                        str39 = str30;
                        num16 = num10;
                        break;
                    case 14:
                        kSerializerArr = kSerializerArr2;
                        list4 = list8;
                        num10 = num16;
                        str30 = str47;
                        str26 = str38;
                        i4 |= 16384;
                        str27 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 14, StringSerializer.INSTANCE, str44);
                        str28 = str45;
                        str29 = str46;
                        str46 = str29;
                        list8 = list4;
                        kSerializerArr2 = kSerializerArr;
                        str38 = str26;
                        str44 = str27;
                        str45 = str28;
                        str39 = str30;
                        num16 = num10;
                        break;
                    case 15:
                        list4 = list8;
                        num10 = num16;
                        kSerializerArr = kSerializerArr2;
                        i4 |= 32768;
                        str26 = str38;
                        str30 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 15, StringSerializer.INSTANCE, str47);
                        str27 = str44;
                        str28 = str45;
                        str29 = str46;
                        str46 = str29;
                        list8 = list4;
                        kSerializerArr2 = kSerializerArr;
                        str38 = str26;
                        str44 = str27;
                        str45 = str28;
                        str39 = str30;
                        num16 = num10;
                        break;
                    case 16:
                        num11 = num16;
                        list8 = (List) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 16, kSerializerArr2[16], list8);
                        i4 |= 65536;
                        num16 = num11;
                        str39 = str47;
                        break;
                    case 17:
                        list3 = list8;
                        num5 = num16;
                        str38 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 17, StringSerializer.INSTANCE, str38);
                        i2 = 131072;
                        i4 |= i2;
                        num16 = num5;
                        str39 = str47;
                        list8 = list3;
                        break;
                    case 18:
                        list3 = list8;
                        num5 = num16;
                        list5 = (List) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 18, kSerializerArr2[18], list5);
                        i2 = 262144;
                        i4 |= i2;
                        num16 = num5;
                        str39 = str47;
                        list8 = list3;
                        break;
                    case 19:
                        list3 = list8;
                        i3 = 524288;
                        str22 = str43;
                        str23 = str42;
                        str24 = str41;
                        num6 = num19;
                        num7 = num18;
                        str25 = str40;
                        num8 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 19, IntSerializer.INSTANCE, num17);
                        num9 = num16;
                        i4 |= i3;
                        num16 = num9;
                        num17 = num8;
                        str40 = str25;
                        num18 = num7;
                        num19 = num6;
                        str41 = str24;
                        str42 = str23;
                        str43 = str22;
                        str39 = str47;
                        list8 = list3;
                        break;
                    case 20:
                        list3 = list8;
                        num19 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 20, IntSerializer.INSTANCE, num19);
                        i3 = 1048576;
                        str22 = str43;
                        str23 = str42;
                        str24 = str41;
                        num6 = num19;
                        num7 = num18;
                        str25 = str40;
                        num8 = num17;
                        num9 = num16;
                        i4 |= i3;
                        num16 = num9;
                        num17 = num8;
                        str40 = str25;
                        num18 = num7;
                        num19 = num6;
                        str41 = str24;
                        str42 = str23;
                        str43 = str22;
                        str39 = str47;
                        list8 = list3;
                        break;
                    case 21:
                        list3 = list8;
                        num18 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 21, IntSerializer.INSTANCE, num18);
                        i3 = 2097152;
                        str22 = str43;
                        str23 = str42;
                        str24 = str41;
                        num6 = num19;
                        num7 = num18;
                        str25 = str40;
                        num8 = num17;
                        num9 = num16;
                        i4 |= i3;
                        num16 = num9;
                        num17 = num8;
                        str40 = str25;
                        num18 = num7;
                        num19 = num6;
                        str41 = str24;
                        str42 = str23;
                        str43 = str22;
                        str39 = str47;
                        list8 = list3;
                        break;
                    case 22:
                        list3 = list8;
                        str41 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 22, StringSerializer.INSTANCE, str41);
                        i3 = 4194304;
                        str22 = str43;
                        str23 = str42;
                        str24 = str41;
                        num6 = num19;
                        num7 = num18;
                        str25 = str40;
                        num8 = num17;
                        num9 = num16;
                        i4 |= i3;
                        num16 = num9;
                        num17 = num8;
                        str40 = str25;
                        num18 = num7;
                        num19 = num6;
                        str41 = str24;
                        str42 = str23;
                        str43 = str22;
                        str39 = str47;
                        list8 = list3;
                        break;
                    case 23:
                        list3 = list8;
                        num16 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 23, IntSerializer.INSTANCE, num16);
                        i3 = 8388608;
                        str22 = str43;
                        str23 = str42;
                        str24 = str41;
                        num6 = num19;
                        num7 = num18;
                        str25 = str40;
                        num8 = num17;
                        num9 = num16;
                        i4 |= i3;
                        num16 = num9;
                        num17 = num8;
                        str40 = str25;
                        num18 = num7;
                        num19 = num6;
                        str41 = str24;
                        str42 = str23;
                        str43 = str22;
                        str39 = str47;
                        list8 = list3;
                        break;
                    case 24:
                        i4 |= 16777216;
                        zDecodeBooleanElement2 = compositeDecoderBeginStructure.decodeBooleanElement(serialDescriptor, 24);
                        num11 = num16;
                        list8 = list8;
                        num16 = num11;
                        str39 = str47;
                        break;
                    case 25:
                        list3 = list8;
                        str40 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 25, StringSerializer.INSTANCE, str40);
                        i3 = MediaHttpDownloader.MAXIMUM_CHUNK_SIZE;
                        str22 = str43;
                        str23 = str42;
                        str24 = str41;
                        num6 = num19;
                        num7 = num18;
                        str25 = str40;
                        num8 = num17;
                        num9 = num16;
                        i4 |= i3;
                        num16 = num9;
                        num17 = num8;
                        str40 = str25;
                        num18 = num7;
                        num19 = num6;
                        str41 = str24;
                        str42 = str23;
                        str43 = str22;
                        str39 = str47;
                        list8 = list3;
                        break;
                    case 26:
                        list3 = list8;
                        str42 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 26, StringSerializer.INSTANCE, str42);
                        i3 = 67108864;
                        str22 = str43;
                        str23 = str42;
                        str24 = str41;
                        num6 = num19;
                        num7 = num18;
                        str25 = str40;
                        num8 = num17;
                        num9 = num16;
                        i4 |= i3;
                        num16 = num9;
                        num17 = num8;
                        str40 = str25;
                        num18 = num7;
                        num19 = num6;
                        str41 = str24;
                        str42 = str23;
                        str43 = str22;
                        str39 = str47;
                        list8 = list3;
                        break;
                    case 27:
                        list3 = list8;
                        str43 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 27, StringSerializer.INSTANCE, str43);
                        i3 = 134217728;
                        str22 = str43;
                        str23 = str42;
                        str24 = str41;
                        num6 = num19;
                        num7 = num18;
                        str25 = str40;
                        num8 = num17;
                        num9 = num16;
                        i4 |= i3;
                        num16 = num9;
                        num17 = num8;
                        str40 = str25;
                        num18 = num7;
                        num19 = num6;
                        str41 = str24;
                        str42 = str23;
                        str43 = str22;
                        str39 = str47;
                        list8 = list3;
                        break;
                    default:
                        throw new UnknownFieldException(iDecodeElementIndex);
                }
            }
            str = str39;
            list = list8;
            num = num17;
            str2 = str40;
            list2 = list5;
            num2 = num19;
            str3 = str42;
            str4 = str43;
            str5 = str38;
            str6 = str44;
            str7 = str45;
            str8 = strDecodeStringElement13;
            str9 = strDecodeStringElement14;
            str10 = strDecodeStringElement15;
            str11 = strDecodeStringElement16;
            z = zDecodeBooleanElement2;
            str12 = strDecodeStringElement17;
            str13 = strDecodeStringElement18;
            str14 = strDecodeStringElement19;
            str15 = strDecodeStringElement20;
            str16 = strDecodeStringElement22;
            str17 = strDecodeStringElement23;
            num3 = num16;
            str18 = str46;
            i = i4;
            num4 = num18;
            str19 = str41;
            str20 = strDecodeStringElement21;
            str21 = strDecodeStringElement24;
        }
        compositeDecoderBeginStructure.endStructure(serialDescriptor);
        return new TradeInfo(i, str21, str17, str16, str20, str15, str14, str13, str8, str9, str10, str11, str12, str18, str7, str6, str, list, str5, list2, num, num2, num4, str19, num3, z, str2, str3, str4, (SerializationConstructorMarker) null);
    }

    /* JADX DEBUG: Method merged with bridge method: serialize(Lkotlinx/serialization/encoding/Encoder;Ljava/lang/Object;)V */
    @Override // kotlinx.serialization.SerializationStrategy
    public final void serialize(@NotNull Encoder encoder, @NotNull TradeInfo tradeInfo) {
        Intrinsics.checkNotNullParameter(encoder, "");
        Intrinsics.checkNotNullParameter(tradeInfo, "");
        SerialDescriptor serialDescriptor = descriptor;
        CompositeEncoder compositeEncoderBeginStructure = encoder.beginStructure(serialDescriptor);
        TradeInfo.write$Self$OKTradeCore_trade_core(tradeInfo, compositeEncoderBeginStructure, serialDescriptor);
        compositeEncoderBeginStructure.endStructure(serialDescriptor);
    }
}
