package com.okinc.unify_trade.biz;

import com.google.api.client.googleapis.media.MediaHttpDownloader;
import java.util.List;
import kotlin.Unit;
import kotlin.jvm.internal.Intrinsics;
import kotlinx.serialization.KSerializer;
import kotlinx.serialization.UnknownFieldException;
import kotlinx.serialization.builtins.BuiltinSerializersKt;
import kotlinx.serialization.descriptors.SerialDescriptor;
import kotlinx.serialization.encoding.CompositeDecoder;
import kotlinx.serialization.encoding.CompositeEncoder;
import kotlinx.serialization.encoding.Decoder;
import kotlinx.serialization.encoding.Encoder;
import kotlinx.serialization.internal.BooleanSerializer;
import kotlinx.serialization.internal.GeneratedSerializer;
import kotlinx.serialization.internal.IntSerializer;
import kotlinx.serialization.internal.PluginGeneratedSerialDescriptor;
import kotlinx.serialization.internal.SerializationConstructorMarker;
import kotlinx.serialization.internal.StringSerializer;
import org.jetbrains.annotations.NotNull;

/* JADX INFO: loaded from: classes17.dex */
public final /* synthetic */ class UserTradeConfigInfo$$serializer implements GeneratedSerializer<UserTradeConfigInfo> {
    public static final int $stable;
    public static final UserTradeConfigInfo$$serializer INSTANCE;
    private static final SerialDescriptor descriptor;

    /* JADX DEBUG: Don't trust debug lines info. Lines numbers was adjusted: min line is 0 */
    private UserTradeConfigInfo$$serializer() {
    }

    /* JADX DEBUG: Don't trust debug lines info. Lines numbers was adjusted: min line is 0 */
    @Override // kotlinx.serialization.KSerializer, kotlinx.serialization.SerializationStrategy, kotlinx.serialization.DeserializationStrategy
    public final SerialDescriptor getDescriptor() {
        return descriptor;
    }

    static {
        UserTradeConfigInfo$$serializer userTradeConfigInfo$$serializer = new UserTradeConfigInfo$$serializer();
        INSTANCE = userTradeConfigInfo$$serializer;
        $stable = 8;
        PluginGeneratedSerialDescriptor pluginGeneratedSerialDescriptor = new PluginGeneratedSerialDescriptor("com.okinc.unify_trade.biz.UserTradeConfigInfo", userTradeConfigInfo$$serializer, 31);
        pluginGeneratedSerialDescriptor.addElement("acctLv", true);
        pluginGeneratedSerialDescriptor.addElement("maxLevel", true);
        pluginGeneratedSerialDescriptor.addElement("posMode", true);
        pluginGeneratedSerialDescriptor.addElement("autoLoan", true);
        pluginGeneratedSerialDescriptor.addElement("exist", true);
        pluginGeneratedSerialDescriptor.addElement("opQuote", true);
        pluginGeneratedSerialDescriptor.addElement("opAuth", true);
        pluginGeneratedSerialDescriptor.addElement("vipLoan", true);
        pluginGeneratedSerialDescriptor.addElement("ctIsoMode", true);
        pluginGeneratedSerialDescriptor.addElement("mgnIsoMode", true);
        pluginGeneratedSerialDescriptor.addElement("roleType", true);
        pluginGeneratedSerialDescriptor.addElement("traderInsts", true);
        pluginGeneratedSerialDescriptor.addElement("liquidationGear", true);
        pluginGeneratedSerialDescriptor.addElement("firstTradeTime", true);
        pluginGeneratedSerialDescriptor.addElement("orderNotice", true);
        pluginGeneratedSerialDescriptor.addElement("limitOrderNotice", true);
        pluginGeneratedSerialDescriptor.addElement("reduceOnlyNotice", true);
        pluginGeneratedSerialDescriptor.addElement("marketOrderNotice", true);
        pluginGeneratedSerialDescriptor.addElement("spotFeeCoinType", true);
        pluginGeneratedSerialDescriptor.addElement("spotRoleType", true);
        pluginGeneratedSerialDescriptor.addElement("spotTraderInsts", true);
        pluginGeneratedSerialDescriptor.addElement("acctStpMode", true);
        pluginGeneratedSerialDescriptor.addElement("enableSpotBorrow", true);
        pluginGeneratedSerialDescriptor.addElement("enableTradeBorrowModeAutoRepay", true);
        pluginGeneratedSerialDescriptor.addElement("usdLinearSettleCcy", true);
        pluginGeneratedSerialDescriptor.addElement("usdLinearSettleCcyList", true);
        pluginGeneratedSerialDescriptor.addElement("stgyType", true);
        pluginGeneratedSerialDescriptor.addElement("bonusCcy", true);
        pluginGeneratedSerialDescriptor.addElement("bonus", true);
        pluginGeneratedSerialDescriptor.addElement("rateType", true);
        pluginGeneratedSerialDescriptor.addElement("equityPerpDisclosure", true);
        descriptor = pluginGeneratedSerialDescriptor;
    }

    @Override // kotlinx.serialization.internal.GeneratedSerializer
    public final KSerializer<?>[] childSerializers() {
        KSerializer[] kSerializerArr = UserTradeConfigInfo.$childSerializers;
        StringSerializer stringSerializer = StringSerializer.INSTANCE;
        BooleanSerializer booleanSerializer = BooleanSerializer.INSTANCE;
        IntSerializer intSerializer = IntSerializer.INSTANCE;
        return new KSerializer[]{stringSerializer, stringSerializer, stringSerializer, booleanSerializer, booleanSerializer, booleanSerializer, stringSerializer, booleanSerializer, stringSerializer, stringSerializer, intSerializer, BuiltinSerializersKt.getNullable(kSerializerArr[11]), stringSerializer, BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), intSerializer, BuiltinSerializersKt.getNullable(kSerializerArr[20]), BuiltinSerializersKt.getNullable(stringSerializer), booleanSerializer, booleanSerializer, BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(kSerializerArr[25]), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer)};
    }

    /* JADX DEBUG: Method merged with bridge method: deserialize(Lkotlinx/serialization/encoding/Decoder;)Ljava/lang/Object; */
    @Override // kotlinx.serialization.DeserializationStrategy
    public final UserTradeConfigInfo deserialize(@NotNull Decoder decoder) {
        List list;
        List list2;
        String str;
        List list3;
        String str2;
        String str3;
        String str4;
        String str5;
        String str6;
        String str7;
        String str8;
        String str9;
        String str10;
        boolean z;
        String str11;
        String str12;
        boolean z2;
        int i;
        String str13;
        String str14;
        String str15;
        String str16;
        boolean z3;
        boolean z4;
        int i2;
        boolean zDecodeBooleanElement;
        String str17;
        String str18;
        String str19;
        String str20;
        boolean z5;
        String str21;
        String str22;
        String str23;
        String str24;
        String str25;
        String str26;
        KSerializer[] kSerializerArr;
        List list4;
        String str27;
        String str28;
        String str29;
        int i3;
        String str30;
        int i4;
        String str31;
        String str32;
        String str33;
        String str34;
        String str35;
        String str36;
        String str37;
        List list5;
        boolean z6;
        String str38;
        int i5;
        int i6;
        int i7;
        int i8;
        List list6;
        Intrinsics.checkNotNullParameter(decoder, "");
        SerialDescriptor serialDescriptor = descriptor;
        CompositeDecoder compositeDecoderBeginStructure = decoder.beginStructure(serialDescriptor);
        KSerializer[] kSerializerArr2 = UserTradeConfigInfo.$childSerializers;
        int i9 = 0;
        if (compositeDecoderBeginStructure.decodeSequentially()) {
            String strDecodeStringElement = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 0);
            String strDecodeStringElement2 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 1);
            String strDecodeStringElement3 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 2);
            boolean zDecodeBooleanElement2 = compositeDecoderBeginStructure.decodeBooleanElement(serialDescriptor, 3);
            boolean zDecodeBooleanElement3 = compositeDecoderBeginStructure.decodeBooleanElement(serialDescriptor, 4);
            zDecodeBooleanElement = compositeDecoderBeginStructure.decodeBooleanElement(serialDescriptor, 5);
            String strDecodeStringElement4 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 6);
            boolean zDecodeBooleanElement4 = compositeDecoderBeginStructure.decodeBooleanElement(serialDescriptor, 7);
            String strDecodeStringElement5 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 8);
            String strDecodeStringElement6 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 9);
            int iDecodeIntElement = compositeDecoderBeginStructure.decodeIntElement(serialDescriptor, 10);
            List list7 = (List) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 11, kSerializerArr2[11], null);
            String strDecodeStringElement7 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 12);
            StringSerializer stringSerializer = StringSerializer.INSTANCE;
            str17 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 13, stringSerializer, null);
            String str39 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 14, stringSerializer, null);
            String str40 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 15, stringSerializer, null);
            String str41 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 16, stringSerializer, null);
            String str42 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 17, stringSerializer, null);
            String str43 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 18, stringSerializer, null);
            int iDecodeIntElement2 = compositeDecoderBeginStructure.decodeIntElement(serialDescriptor, 19);
            List list8 = (List) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 20, kSerializerArr2[20], null);
            String str44 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 21, stringSerializer, null);
            boolean zDecodeBooleanElement5 = compositeDecoderBeginStructure.decodeBooleanElement(serialDescriptor, 22);
            boolean zDecodeBooleanElement6 = compositeDecoderBeginStructure.decodeBooleanElement(serialDescriptor, 23);
            String str45 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 24, stringSerializer, null);
            List list9 = (List) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 25, kSerializerArr2[25], null);
            String str46 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 26, stringSerializer, null);
            String str47 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 27, stringSerializer, null);
            String str48 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 28, stringSerializer, null);
            String str49 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 29, stringSerializer, null);
            str18 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 30, stringSerializer, null);
            str4 = str46;
            list2 = list9;
            list = list7;
            str16 = strDecodeStringElement;
            str5 = str47;
            str = str48;
            str6 = str49;
            z3 = zDecodeBooleanElement5;
            str9 = str40;
            str10 = str39;
            str3 = str45;
            z2 = zDecodeBooleanElement6;
            i9 = Integer.MAX_VALUE;
            i2 = iDecodeIntElement;
            str20 = strDecodeStringElement6;
            str7 = str42;
            str15 = strDecodeStringElement2;
            list3 = list8;
            str8 = str43;
            str14 = strDecodeStringElement3;
            i = iDecodeIntElement2;
            z5 = zDecodeBooleanElement4;
            z4 = zDecodeBooleanElement2;
            str2 = str44;
            str11 = strDecodeStringElement4;
            z = zDecodeBooleanElement3;
            str19 = str41;
            str12 = strDecodeStringElement5;
            str13 = strDecodeStringElement7;
        } else {
            List list10 = null;
            boolean zDecodeBooleanElement7 = false;
            boolean zDecodeBooleanElement8 = false;
            int iDecodeIntElement3 = 0;
            boolean zDecodeBooleanElement9 = false;
            boolean zDecodeBooleanElement10 = false;
            int iDecodeIntElement4 = 0;
            boolean zDecodeBooleanElement11 = false;
            boolean zDecodeBooleanElement12 = false;
            boolean z7 = true;
            String str50 = null;
            String str51 = null;
            List list11 = null;
            String str52 = null;
            String str53 = null;
            String str54 = null;
            String str55 = null;
            String str56 = null;
            String str57 = null;
            String str58 = null;
            String str59 = null;
            String strDecodeStringElement8 = null;
            String strDecodeStringElement9 = null;
            String str60 = null;
            String str61 = null;
            String str62 = null;
            String strDecodeStringElement10 = null;
            List list12 = null;
            String strDecodeStringElement11 = null;
            String strDecodeStringElement12 = null;
            String strDecodeStringElement13 = null;
            String strDecodeStringElement14 = null;
            while (z7) {
                String str63 = str52;
                int iDecodeElementIndex = compositeDecoderBeginStructure.decodeElementIndex(serialDescriptor);
                switch (iDecodeElementIndex) {
                    case -1:
                        str21 = str50;
                        str22 = str51;
                        str23 = str60;
                        str24 = str61;
                        str25 = str62;
                        str26 = str63;
                        kSerializerArr = kSerializerArr2;
                        Unit unit = Unit.INSTANCE;
                        z7 = false;
                        str27 = str25;
                        str51 = str22;
                        str50 = str21;
                        str52 = str26;
                        str61 = str24;
                        str60 = str23;
                        KSerializer[] kSerializerArr3 = kSerializerArr;
                        str62 = str27;
                        kSerializerArr2 = kSerializerArr3;
                        break;
                    case 0:
                        str21 = str50;
                        str22 = str51;
                        str23 = str60;
                        str24 = str61;
                        str25 = str62;
                        str26 = str63;
                        kSerializerArr = kSerializerArr2;
                        strDecodeStringElement14 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 0);
                        i9 |= 1;
                        Unit unit2 = Unit.INSTANCE;
                        str27 = str25;
                        str51 = str22;
                        str50 = str21;
                        str52 = str26;
                        str61 = str24;
                        str60 = str23;
                        KSerializer[] kSerializerArr32 = kSerializerArr;
                        str62 = str27;
                        kSerializerArr2 = kSerializerArr32;
                        break;
                    case 1:
                        str21 = str50;
                        str22 = str51;
                        str23 = str60;
                        str24 = str61;
                        str25 = str62;
                        str26 = str63;
                        kSerializerArr = kSerializerArr2;
                        list4 = list12;
                        strDecodeStringElement13 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 1);
                        i9 |= 2;
                        Unit unit3 = Unit.INSTANCE;
                        list12 = list4;
                        str27 = str25;
                        str51 = str22;
                        str50 = str21;
                        str52 = str26;
                        str61 = str24;
                        str60 = str23;
                        KSerializer[] kSerializerArr322 = kSerializerArr;
                        str62 = str27;
                        kSerializerArr2 = kSerializerArr322;
                        break;
                    case 2:
                        str21 = str50;
                        str22 = str51;
                        str23 = str60;
                        str24 = str61;
                        str25 = str62;
                        str26 = str63;
                        kSerializerArr = kSerializerArr2;
                        list4 = list12;
                        strDecodeStringElement12 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 2);
                        i9 |= 4;
                        Unit unit4 = Unit.INSTANCE;
                        list12 = list4;
                        str27 = str25;
                        str51 = str22;
                        str50 = str21;
                        str52 = str26;
                        str61 = str24;
                        str60 = str23;
                        KSerializer[] kSerializerArr3222 = kSerializerArr;
                        str62 = str27;
                        kSerializerArr2 = kSerializerArr3222;
                        break;
                    case 3:
                        str21 = str50;
                        str22 = str51;
                        str23 = str60;
                        str24 = str61;
                        str25 = str62;
                        str26 = str63;
                        kSerializerArr = kSerializerArr2;
                        list4 = list12;
                        zDecodeBooleanElement10 = compositeDecoderBeginStructure.decodeBooleanElement(serialDescriptor, 3);
                        i9 |= 8;
                        Unit unit5 = Unit.INSTANCE;
                        list12 = list4;
                        str27 = str25;
                        str51 = str22;
                        str50 = str21;
                        str52 = str26;
                        str61 = str24;
                        str60 = str23;
                        KSerializer[] kSerializerArr32222 = kSerializerArr;
                        str62 = str27;
                        kSerializerArr2 = kSerializerArr32222;
                        break;
                    case 4:
                        str21 = str50;
                        str22 = str51;
                        str23 = str60;
                        str24 = str61;
                        str25 = str62;
                        str26 = str63;
                        kSerializerArr = kSerializerArr2;
                        list4 = list12;
                        zDecodeBooleanElement7 = compositeDecoderBeginStructure.decodeBooleanElement(serialDescriptor, 4);
                        i9 |= 16;
                        Unit unit6 = Unit.INSTANCE;
                        list12 = list4;
                        str27 = str25;
                        str51 = str22;
                        str50 = str21;
                        str52 = str26;
                        str61 = str24;
                        str60 = str23;
                        KSerializer[] kSerializerArr322222 = kSerializerArr;
                        str62 = str27;
                        kSerializerArr2 = kSerializerArr322222;
                        break;
                    case 5:
                        str21 = str50;
                        str22 = str51;
                        str23 = str60;
                        str24 = str61;
                        str25 = str62;
                        str26 = str63;
                        kSerializerArr = kSerializerArr2;
                        list4 = list12;
                        zDecodeBooleanElement12 = compositeDecoderBeginStructure.decodeBooleanElement(serialDescriptor, 5);
                        i9 |= 32;
                        Unit unit7 = Unit.INSTANCE;
                        list12 = list4;
                        str27 = str25;
                        str51 = str22;
                        str50 = str21;
                        str52 = str26;
                        str61 = str24;
                        str60 = str23;
                        KSerializer[] kSerializerArr3222222 = kSerializerArr;
                        str62 = str27;
                        kSerializerArr2 = kSerializerArr3222222;
                        break;
                    case 6:
                        str21 = str50;
                        str22 = str51;
                        str23 = str60;
                        str24 = str61;
                        str25 = str62;
                        str26 = str63;
                        kSerializerArr = kSerializerArr2;
                        list4 = list12;
                        strDecodeStringElement8 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 6);
                        i9 |= 64;
                        Unit unit8 = Unit.INSTANCE;
                        list12 = list4;
                        str27 = str25;
                        str51 = str22;
                        str50 = str21;
                        str52 = str26;
                        str61 = str24;
                        str60 = str23;
                        KSerializer[] kSerializerArr32222222 = kSerializerArr;
                        str62 = str27;
                        kSerializerArr2 = kSerializerArr32222222;
                        break;
                    case 7:
                        str21 = str50;
                        str22 = str51;
                        str23 = str60;
                        str24 = str61;
                        str25 = str62;
                        str26 = str63;
                        kSerializerArr = kSerializerArr2;
                        list4 = list12;
                        zDecodeBooleanElement11 = compositeDecoderBeginStructure.decodeBooleanElement(serialDescriptor, 7);
                        i9 |= 128;
                        Unit unit9 = Unit.INSTANCE;
                        list12 = list4;
                        str27 = str25;
                        str51 = str22;
                        str50 = str21;
                        str52 = str26;
                        str61 = str24;
                        str60 = str23;
                        KSerializer[] kSerializerArr322222222 = kSerializerArr;
                        str62 = str27;
                        kSerializerArr2 = kSerializerArr322222222;
                        break;
                    case 8:
                        str21 = str50;
                        str22 = str51;
                        str23 = str60;
                        str24 = str61;
                        str25 = str62;
                        str26 = str63;
                        kSerializerArr = kSerializerArr2;
                        list4 = list12;
                        strDecodeStringElement9 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 8);
                        i9 |= 256;
                        Unit unit10 = Unit.INSTANCE;
                        list12 = list4;
                        str27 = str25;
                        str51 = str22;
                        str50 = str21;
                        str52 = str26;
                        str61 = str24;
                        str60 = str23;
                        KSerializer[] kSerializerArr3222222222 = kSerializerArr;
                        str62 = str27;
                        kSerializerArr2 = kSerializerArr3222222222;
                        break;
                    case 9:
                        str21 = str50;
                        str22 = str51;
                        str23 = str60;
                        str24 = str61;
                        str25 = str62;
                        str26 = str63;
                        kSerializerArr = kSerializerArr2;
                        list4 = list12;
                        strDecodeStringElement11 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 9);
                        i9 |= 512;
                        Unit unit11 = Unit.INSTANCE;
                        list12 = list4;
                        str27 = str25;
                        str51 = str22;
                        str50 = str21;
                        str52 = str26;
                        str61 = str24;
                        str60 = str23;
                        KSerializer[] kSerializerArr32222222222 = kSerializerArr;
                        str62 = str27;
                        kSerializerArr2 = kSerializerArr32222222222;
                        break;
                    case 10:
                        str21 = str50;
                        str22 = str51;
                        str23 = str60;
                        str24 = str61;
                        str25 = str62;
                        str26 = str63;
                        kSerializerArr = kSerializerArr2;
                        list4 = list12;
                        iDecodeIntElement4 = compositeDecoderBeginStructure.decodeIntElement(serialDescriptor, 10);
                        i9 |= 1024;
                        Unit unit12 = Unit.INSTANCE;
                        list12 = list4;
                        str27 = str25;
                        str51 = str22;
                        str50 = str21;
                        str52 = str26;
                        str61 = str24;
                        str60 = str23;
                        KSerializer[] kSerializerArr322222222222 = kSerializerArr;
                        str62 = str27;
                        kSerializerArr2 = kSerializerArr322222222222;
                        break;
                    case 11:
                        str21 = str50;
                        str22 = str51;
                        str23 = str60;
                        str24 = str61;
                        str25 = str62;
                        str26 = str63;
                        kSerializerArr = kSerializerArr2;
                        list12 = (List) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 11, kSerializerArr2[11], list12);
                        i9 |= 2048;
                        Unit unit13 = Unit.INSTANCE;
                        str27 = str25;
                        str51 = str22;
                        str50 = str21;
                        str52 = str26;
                        str61 = str24;
                        str60 = str23;
                        KSerializer[] kSerializerArr3222222222222 = kSerializerArr;
                        str62 = str27;
                        kSerializerArr2 = kSerializerArr3222222222222;
                        break;
                    case 12:
                        str21 = str50;
                        str22 = str51;
                        str23 = str60;
                        str24 = str61;
                        str26 = str63;
                        strDecodeStringElement10 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 12);
                        i9 |= 4096;
                        Unit unit14 = Unit.INSTANCE;
                        str25 = str62;
                        kSerializerArr = kSerializerArr2;
                        str27 = str25;
                        str51 = str22;
                        str50 = str21;
                        str52 = str26;
                        str61 = str24;
                        str60 = str23;
                        KSerializer[] kSerializerArr32222222222222 = kSerializerArr;
                        str62 = str27;
                        kSerializerArr2 = kSerializerArr32222222222222;
                        break;
                    case 13:
                        str21 = str50;
                        str22 = str51;
                        str24 = str61;
                        str26 = str63;
                        str23 = str60;
                        str62 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 13, StringSerializer.INSTANCE, str62);
                        Unit unit15 = Unit.INSTANCE;
                        i9 |= 8192;
                        str25 = str62;
                        kSerializerArr = kSerializerArr2;
                        str27 = str25;
                        str51 = str22;
                        str50 = str21;
                        str52 = str26;
                        str61 = str24;
                        str60 = str23;
                        KSerializer[] kSerializerArr322222222222222 = kSerializerArr;
                        str62 = str27;
                        kSerializerArr2 = kSerializerArr322222222222222;
                        break;
                    case 14:
                        String str64 = str50;
                        str28 = str51;
                        str29 = str63;
                        str24 = str61;
                        String str65 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 14, StringSerializer.INSTANCE, str60);
                        i3 = i9 | 16384;
                        Unit unit16 = Unit.INSTANCE;
                        str60 = str65;
                        str30 = str53;
                        str50 = str64;
                        i4 = i3;
                        str31 = str59;
                        str32 = str29;
                        str33 = str58;
                        str34 = str57;
                        str35 = str56;
                        str36 = str55;
                        str37 = str54;
                        list5 = list10;
                        z6 = zDecodeBooleanElement8;
                        str26 = str32;
                        zDecodeBooleanElement8 = z6;
                        list10 = list5;
                        str54 = str37;
                        str55 = str36;
                        str56 = str35;
                        str57 = str34;
                        str58 = str33;
                        str59 = str31;
                        str51 = str28;
                        str23 = str60;
                        str21 = str50;
                        String str66 = str62;
                        kSerializerArr = kSerializerArr2;
                        str27 = str66;
                        String str67 = str30;
                        i9 = i4;
                        str53 = str67;
                        str50 = str21;
                        str52 = str26;
                        str61 = str24;
                        str60 = str23;
                        KSerializer[] kSerializerArr3222222222222222 = kSerializerArr;
                        str62 = str27;
                        kSerializerArr2 = kSerializerArr3222222222222222;
                        break;
                    case 15:
                        str28 = str51;
                        str29 = str63;
                        String str68 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 15, StringSerializer.INSTANCE, str61);
                        i3 = 32768 | i9;
                        Unit unit17 = Unit.INSTANCE;
                        str24 = str68;
                        str30 = str53;
                        str50 = str50;
                        i4 = i3;
                        str31 = str59;
                        str32 = str29;
                        str33 = str58;
                        str34 = str57;
                        str35 = str56;
                        str36 = str55;
                        str37 = str54;
                        list5 = list10;
                        z6 = zDecodeBooleanElement8;
                        str26 = str32;
                        zDecodeBooleanElement8 = z6;
                        list10 = list5;
                        str54 = str37;
                        str55 = str36;
                        str56 = str35;
                        str57 = str34;
                        str58 = str33;
                        str59 = str31;
                        str51 = str28;
                        str23 = str60;
                        str21 = str50;
                        String str662 = str62;
                        kSerializerArr = kSerializerArr2;
                        str27 = str662;
                        String str672 = str30;
                        i9 = i4;
                        str53 = str672;
                        str50 = str21;
                        str52 = str26;
                        str61 = str24;
                        str60 = str23;
                        KSerializer[] kSerializerArr32222222222222222 = kSerializerArr;
                        str62 = str27;
                        kSerializerArr2 = kSerializerArr32222222222222222;
                        break;
                    case 16:
                        String str69 = str50;
                        str28 = str51;
                        str32 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 16, StringSerializer.INSTANCE, str63);
                        int i10 = 65536 | i9;
                        Unit unit18 = Unit.INSTANCE;
                        str30 = str53;
                        str24 = str61;
                        i4 = i10;
                        str50 = str69;
                        str31 = str59;
                        str33 = str58;
                        str34 = str57;
                        str35 = str56;
                        str36 = str55;
                        str37 = str54;
                        list5 = list10;
                        z6 = zDecodeBooleanElement8;
                        str26 = str32;
                        zDecodeBooleanElement8 = z6;
                        list10 = list5;
                        str54 = str37;
                        str55 = str36;
                        str56 = str35;
                        str57 = str34;
                        str58 = str33;
                        str59 = str31;
                        str51 = str28;
                        str23 = str60;
                        str21 = str50;
                        String str6622 = str62;
                        kSerializerArr = kSerializerArr2;
                        str27 = str6622;
                        String str6722 = str30;
                        i9 = i4;
                        str53 = str6722;
                        str50 = str21;
                        str52 = str26;
                        str61 = str24;
                        str60 = str23;
                        KSerializer[] kSerializerArr322222222222222222 = kSerializerArr;
                        str62 = str27;
                        kSerializerArr2 = kSerializerArr322222222222222222;
                        break;
                    case 17:
                        String str70 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 17, StringSerializer.INSTANCE, str59);
                        int i11 = 131072 | i9;
                        Unit unit19 = Unit.INSTANCE;
                        str28 = str51;
                        str30 = str53;
                        str50 = str50;
                        str24 = str61;
                        i4 = i11;
                        str31 = str70;
                        str32 = str63;
                        str33 = str58;
                        str34 = str57;
                        str35 = str56;
                        str36 = str55;
                        str37 = str54;
                        list5 = list10;
                        z6 = zDecodeBooleanElement8;
                        str26 = str32;
                        zDecodeBooleanElement8 = z6;
                        list10 = list5;
                        str54 = str37;
                        str55 = str36;
                        str56 = str35;
                        str57 = str34;
                        str58 = str33;
                        str59 = str31;
                        str51 = str28;
                        str23 = str60;
                        str21 = str50;
                        String str66222 = str62;
                        kSerializerArr = kSerializerArr2;
                        str27 = str66222;
                        String str67222 = str30;
                        i9 = i4;
                        str53 = str67222;
                        str50 = str21;
                        str52 = str26;
                        str61 = str24;
                        str60 = str23;
                        KSerializer[] kSerializerArr3222222222222222222 = kSerializerArr;
                        str62 = str27;
                        kSerializerArr2 = kSerializerArr3222222222222222222;
                        break;
                    case 18:
                        str38 = str59;
                        str51 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 18, StringSerializer.INSTANCE, str51);
                        i5 = 262144;
                        i8 = i5 | i9;
                        Unit unit20 = Unit.INSTANCE;
                        list6 = list10;
                        z6 = zDecodeBooleanElement8;
                        str28 = str51;
                        str33 = str58;
                        str24 = str61;
                        str31 = str38;
                        str34 = str57;
                        str35 = str56;
                        str36 = str55;
                        str37 = str54;
                        list5 = list6;
                        str30 = str53;
                        i4 = i8;
                        str32 = str63;
                        str26 = str32;
                        zDecodeBooleanElement8 = z6;
                        list10 = list5;
                        str54 = str37;
                        str55 = str36;
                        str56 = str35;
                        str57 = str34;
                        str58 = str33;
                        str59 = str31;
                        str51 = str28;
                        str23 = str60;
                        str21 = str50;
                        String str662222 = str62;
                        kSerializerArr = kSerializerArr2;
                        str27 = str662222;
                        String str672222 = str30;
                        i9 = i4;
                        str53 = str672222;
                        str50 = str21;
                        str52 = str26;
                        str61 = str24;
                        str60 = str23;
                        KSerializer[] kSerializerArr32222222222222222222 = kSerializerArr;
                        str62 = str27;
                        kSerializerArr2 = kSerializerArr32222222222222222222;
                        break;
                    case 19:
                        str38 = str59;
                        iDecodeIntElement3 = compositeDecoderBeginStructure.decodeIntElement(serialDescriptor, 19);
                        i5 = 524288;
                        i8 = i5 | i9;
                        Unit unit202 = Unit.INSTANCE;
                        list6 = list10;
                        z6 = zDecodeBooleanElement8;
                        str28 = str51;
                        str33 = str58;
                        str24 = str61;
                        str31 = str38;
                        str34 = str57;
                        str35 = str56;
                        str36 = str55;
                        str37 = str54;
                        list5 = list6;
                        str30 = str53;
                        i4 = i8;
                        str32 = str63;
                        str26 = str32;
                        zDecodeBooleanElement8 = z6;
                        list10 = list5;
                        str54 = str37;
                        str55 = str36;
                        str56 = str35;
                        str57 = str34;
                        str58 = str33;
                        str59 = str31;
                        str51 = str28;
                        str23 = str60;
                        str21 = str50;
                        String str6622222 = str62;
                        kSerializerArr = kSerializerArr2;
                        str27 = str6622222;
                        String str6722222 = str30;
                        i9 = i4;
                        str53 = str6722222;
                        str50 = str21;
                        str52 = str26;
                        str61 = str24;
                        str60 = str23;
                        KSerializer[] kSerializerArr322222222222222222222 = kSerializerArr;
                        str62 = str27;
                        kSerializerArr2 = kSerializerArr322222222222222222222;
                        break;
                    case 20:
                        str38 = str59;
                        list10 = (List) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 20, kSerializerArr2[20], list10);
                        i5 = 1048576;
                        i8 = i5 | i9;
                        Unit unit2022 = Unit.INSTANCE;
                        list6 = list10;
                        z6 = zDecodeBooleanElement8;
                        str28 = str51;
                        str33 = str58;
                        str24 = str61;
                        str31 = str38;
                        str34 = str57;
                        str35 = str56;
                        str36 = str55;
                        str37 = str54;
                        list5 = list6;
                        str30 = str53;
                        i4 = i8;
                        str32 = str63;
                        str26 = str32;
                        zDecodeBooleanElement8 = z6;
                        list10 = list5;
                        str54 = str37;
                        str55 = str36;
                        str56 = str35;
                        str57 = str34;
                        str58 = str33;
                        str59 = str31;
                        str51 = str28;
                        str23 = str60;
                        str21 = str50;
                        String str66222222 = str62;
                        kSerializerArr = kSerializerArr2;
                        str27 = str66222222;
                        String str67222222 = str30;
                        i9 = i4;
                        str53 = str67222222;
                        str50 = str21;
                        str52 = str26;
                        str61 = str24;
                        str60 = str23;
                        KSerializer[] kSerializerArr3222222222222222222222 = kSerializerArr;
                        str62 = str27;
                        kSerializerArr2 = kSerializerArr3222222222222222222222;
                        break;
                    case 21:
                        str38 = str59;
                        String str71 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 21, StringSerializer.INSTANCE, str54);
                        i6 = i9 | 2097152;
                        Unit unit21 = Unit.INSTANCE;
                        str54 = str71;
                        i8 = i6;
                        list6 = list10;
                        z6 = zDecodeBooleanElement8;
                        str28 = str51;
                        str33 = str58;
                        str24 = str61;
                        str31 = str38;
                        str34 = str57;
                        str35 = str56;
                        str36 = str55;
                        str37 = str54;
                        list5 = list6;
                        str30 = str53;
                        i4 = i8;
                        str32 = str63;
                        str26 = str32;
                        zDecodeBooleanElement8 = z6;
                        list10 = list5;
                        str54 = str37;
                        str55 = str36;
                        str56 = str35;
                        str57 = str34;
                        str58 = str33;
                        str59 = str31;
                        str51 = str28;
                        str23 = str60;
                        str21 = str50;
                        String str662222222 = str62;
                        kSerializerArr = kSerializerArr2;
                        str27 = str662222222;
                        String str672222222 = str30;
                        i9 = i4;
                        str53 = str672222222;
                        str50 = str21;
                        str52 = str26;
                        str61 = str24;
                        str60 = str23;
                        KSerializer[] kSerializerArr32222222222222222222222 = kSerializerArr;
                        str62 = str27;
                        kSerializerArr2 = kSerializerArr32222222222222222222222;
                        break;
                    case 22:
                        str38 = str59;
                        zDecodeBooleanElement9 = compositeDecoderBeginStructure.decodeBooleanElement(serialDescriptor, 22);
                        i7 = 4194304;
                        i8 = i7 | i9;
                        Unit unit22 = Unit.INSTANCE;
                        list6 = list10;
                        z6 = zDecodeBooleanElement8;
                        str28 = str51;
                        str33 = str58;
                        str24 = str61;
                        str31 = str38;
                        str34 = str57;
                        str35 = str56;
                        str36 = str55;
                        str37 = str54;
                        list5 = list6;
                        str30 = str53;
                        i4 = i8;
                        str32 = str63;
                        str26 = str32;
                        zDecodeBooleanElement8 = z6;
                        list10 = list5;
                        str54 = str37;
                        str55 = str36;
                        str56 = str35;
                        str57 = str34;
                        str58 = str33;
                        str59 = str31;
                        str51 = str28;
                        str23 = str60;
                        str21 = str50;
                        String str6622222222 = str62;
                        kSerializerArr = kSerializerArr2;
                        str27 = str6622222222;
                        String str6722222222 = str30;
                        i9 = i4;
                        str53 = str6722222222;
                        str50 = str21;
                        str52 = str26;
                        str61 = str24;
                        str60 = str23;
                        KSerializer[] kSerializerArr322222222222222222222222 = kSerializerArr;
                        str62 = str27;
                        kSerializerArr2 = kSerializerArr322222222222222222222222;
                        break;
                    case 23:
                        str38 = str59;
                        zDecodeBooleanElement8 = compositeDecoderBeginStructure.decodeBooleanElement(serialDescriptor, 23);
                        i7 = 8388608;
                        i8 = i7 | i9;
                        Unit unit222 = Unit.INSTANCE;
                        list6 = list10;
                        z6 = zDecodeBooleanElement8;
                        str28 = str51;
                        str33 = str58;
                        str24 = str61;
                        str31 = str38;
                        str34 = str57;
                        str35 = str56;
                        str36 = str55;
                        str37 = str54;
                        list5 = list6;
                        str30 = str53;
                        i4 = i8;
                        str32 = str63;
                        str26 = str32;
                        zDecodeBooleanElement8 = z6;
                        list10 = list5;
                        str54 = str37;
                        str55 = str36;
                        str56 = str35;
                        str57 = str34;
                        str58 = str33;
                        str59 = str31;
                        str51 = str28;
                        str23 = str60;
                        str21 = str50;
                        String str66222222222 = str62;
                        kSerializerArr = kSerializerArr2;
                        str27 = str66222222222;
                        String str67222222222 = str30;
                        i9 = i4;
                        str53 = str67222222222;
                        str50 = str21;
                        str52 = str26;
                        str61 = str24;
                        str60 = str23;
                        KSerializer[] kSerializerArr3222222222222222222222222 = kSerializerArr;
                        str62 = str27;
                        kSerializerArr2 = kSerializerArr3222222222222222222222222;
                        break;
                    case 24:
                        str38 = str59;
                        String str72 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 24, StringSerializer.INSTANCE, str55);
                        i6 = i9 | 16777216;
                        Unit unit23 = Unit.INSTANCE;
                        str55 = str72;
                        i8 = i6;
                        list6 = list10;
                        z6 = zDecodeBooleanElement8;
                        str28 = str51;
                        str33 = str58;
                        str24 = str61;
                        str31 = str38;
                        str34 = str57;
                        str35 = str56;
                        str36 = str55;
                        str37 = str54;
                        list5 = list6;
                        str30 = str53;
                        i4 = i8;
                        str32 = str63;
                        str26 = str32;
                        zDecodeBooleanElement8 = z6;
                        list10 = list5;
                        str54 = str37;
                        str55 = str36;
                        str56 = str35;
                        str57 = str34;
                        str58 = str33;
                        str59 = str31;
                        str51 = str28;
                        str23 = str60;
                        str21 = str50;
                        String str662222222222 = str62;
                        kSerializerArr = kSerializerArr2;
                        str27 = str662222222222;
                        String str672222222222 = str30;
                        i9 = i4;
                        str53 = str672222222222;
                        str50 = str21;
                        str52 = str26;
                        str61 = str24;
                        str60 = str23;
                        KSerializer[] kSerializerArr32222222222222222222222222 = kSerializerArr;
                        str62 = str27;
                        kSerializerArr2 = kSerializerArr32222222222222222222222222;
                        break;
                    case 25:
                        str38 = str59;
                        list11 = (List) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 25, kSerializerArr2[25], list11);
                        i5 = MediaHttpDownloader.MAXIMUM_CHUNK_SIZE;
                        i8 = i5 | i9;
                        Unit unit20222 = Unit.INSTANCE;
                        list6 = list10;
                        z6 = zDecodeBooleanElement8;
                        str28 = str51;
                        str33 = str58;
                        str24 = str61;
                        str31 = str38;
                        str34 = str57;
                        str35 = str56;
                        str36 = str55;
                        str37 = str54;
                        list5 = list6;
                        str30 = str53;
                        i4 = i8;
                        str32 = str63;
                        str26 = str32;
                        zDecodeBooleanElement8 = z6;
                        list10 = list5;
                        str54 = str37;
                        str55 = str36;
                        str56 = str35;
                        str57 = str34;
                        str58 = str33;
                        str59 = str31;
                        str51 = str28;
                        str23 = str60;
                        str21 = str50;
                        String str6622222222222 = str62;
                        kSerializerArr = kSerializerArr2;
                        str27 = str6622222222222;
                        String str6722222222222 = str30;
                        i9 = i4;
                        str53 = str6722222222222;
                        str50 = str21;
                        str52 = str26;
                        str61 = str24;
                        str60 = str23;
                        KSerializer[] kSerializerArr322222222222222222222222222 = kSerializerArr;
                        str62 = str27;
                        kSerializerArr2 = kSerializerArr322222222222222222222222222;
                        break;
                    case 26:
                        str38 = str59;
                        String str73 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 26, StringSerializer.INSTANCE, str56);
                        i6 = i9 | 67108864;
                        Unit unit24 = Unit.INSTANCE;
                        str56 = str73;
                        i8 = i6;
                        list6 = list10;
                        z6 = zDecodeBooleanElement8;
                        str28 = str51;
                        str33 = str58;
                        str24 = str61;
                        str31 = str38;
                        str34 = str57;
                        str35 = str56;
                        str36 = str55;
                        str37 = str54;
                        list5 = list6;
                        str30 = str53;
                        i4 = i8;
                        str32 = str63;
                        str26 = str32;
                        zDecodeBooleanElement8 = z6;
                        list10 = list5;
                        str54 = str37;
                        str55 = str36;
                        str56 = str35;
                        str57 = str34;
                        str58 = str33;
                        str59 = str31;
                        str51 = str28;
                        str23 = str60;
                        str21 = str50;
                        String str66222222222222 = str62;
                        kSerializerArr = kSerializerArr2;
                        str27 = str66222222222222;
                        String str67222222222222 = str30;
                        i9 = i4;
                        str53 = str67222222222222;
                        str50 = str21;
                        str52 = str26;
                        str61 = str24;
                        str60 = str23;
                        KSerializer[] kSerializerArr3222222222222222222222222222 = kSerializerArr;
                        str62 = str27;
                        kSerializerArr2 = kSerializerArr3222222222222222222222222222;
                        break;
                    case 27:
                        str38 = str59;
                        String str74 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 27, StringSerializer.INSTANCE, str57);
                        i6 = i9 | 134217728;
                        Unit unit25 = Unit.INSTANCE;
                        str57 = str74;
                        i8 = i6;
                        list6 = list10;
                        z6 = zDecodeBooleanElement8;
                        str28 = str51;
                        str33 = str58;
                        str24 = str61;
                        str31 = str38;
                        str34 = str57;
                        str35 = str56;
                        str36 = str55;
                        str37 = str54;
                        list5 = list6;
                        str30 = str53;
                        i4 = i8;
                        str32 = str63;
                        str26 = str32;
                        zDecodeBooleanElement8 = z6;
                        list10 = list5;
                        str54 = str37;
                        str55 = str36;
                        str56 = str35;
                        str57 = str34;
                        str58 = str33;
                        str59 = str31;
                        str51 = str28;
                        str23 = str60;
                        str21 = str50;
                        String str662222222222222 = str62;
                        kSerializerArr = kSerializerArr2;
                        str27 = str662222222222222;
                        String str672222222222222 = str30;
                        i9 = i4;
                        str53 = str672222222222222;
                        str50 = str21;
                        str52 = str26;
                        str61 = str24;
                        str60 = str23;
                        KSerializer[] kSerializerArr32222222222222222222222222222 = kSerializerArr;
                        str62 = str27;
                        kSerializerArr2 = kSerializerArr32222222222222222222222222222;
                        break;
                    case 28:
                        str38 = str59;
                        str53 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 28, StringSerializer.INSTANCE, str53);
                        i7 = 268435456;
                        i8 = i7 | i9;
                        Unit unit2222 = Unit.INSTANCE;
                        list6 = list10;
                        z6 = zDecodeBooleanElement8;
                        str28 = str51;
                        str33 = str58;
                        str24 = str61;
                        str31 = str38;
                        str34 = str57;
                        str35 = str56;
                        str36 = str55;
                        str37 = str54;
                        list5 = list6;
                        str30 = str53;
                        i4 = i8;
                        str32 = str63;
                        str26 = str32;
                        zDecodeBooleanElement8 = z6;
                        list10 = list5;
                        str54 = str37;
                        str55 = str36;
                        str56 = str35;
                        str57 = str34;
                        str58 = str33;
                        str59 = str31;
                        str51 = str28;
                        str23 = str60;
                        str21 = str50;
                        String str6622222222222222 = str62;
                        kSerializerArr = kSerializerArr2;
                        str27 = str6622222222222222;
                        String str6722222222222222 = str30;
                        i9 = i4;
                        str53 = str6722222222222222;
                        str50 = str21;
                        str52 = str26;
                        str61 = str24;
                        str60 = str23;
                        KSerializer[] kSerializerArr322222222222222222222222222222 = kSerializerArr;
                        str62 = str27;
                        kSerializerArr2 = kSerializerArr322222222222222222222222222222;
                        break;
                    case 29:
                        str38 = str59;
                        String str75 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 29, StringSerializer.INSTANCE, str58);
                        i6 = i9 | 536870912;
                        Unit unit26 = Unit.INSTANCE;
                        str58 = str75;
                        i8 = i6;
                        list6 = list10;
                        z6 = zDecodeBooleanElement8;
                        str28 = str51;
                        str33 = str58;
                        str24 = str61;
                        str31 = str38;
                        str34 = str57;
                        str35 = str56;
                        str36 = str55;
                        str37 = str54;
                        list5 = list6;
                        str30 = str53;
                        i4 = i8;
                        str32 = str63;
                        str26 = str32;
                        zDecodeBooleanElement8 = z6;
                        list10 = list5;
                        str54 = str37;
                        str55 = str36;
                        str56 = str35;
                        str57 = str34;
                        str58 = str33;
                        str59 = str31;
                        str51 = str28;
                        str23 = str60;
                        str21 = str50;
                        String str66222222222222222 = str62;
                        kSerializerArr = kSerializerArr2;
                        str27 = str66222222222222222;
                        String str67222222222222222 = str30;
                        i9 = i4;
                        str53 = str67222222222222222;
                        str50 = str21;
                        str52 = str26;
                        str61 = str24;
                        str60 = str23;
                        KSerializer[] kSerializerArr3222222222222222222222222222222 = kSerializerArr;
                        str62 = str27;
                        kSerializerArr2 = kSerializerArr3222222222222222222222222222222;
                        break;
                    case 30:
                        str38 = str59;
                        str50 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 30, StringSerializer.INSTANCE, str50);
                        i7 = 1073741824;
                        i8 = i7 | i9;
                        Unit unit22222 = Unit.INSTANCE;
                        list6 = list10;
                        z6 = zDecodeBooleanElement8;
                        str28 = str51;
                        str33 = str58;
                        str24 = str61;
                        str31 = str38;
                        str34 = str57;
                        str35 = str56;
                        str36 = str55;
                        str37 = str54;
                        list5 = list6;
                        str30 = str53;
                        i4 = i8;
                        str32 = str63;
                        str26 = str32;
                        zDecodeBooleanElement8 = z6;
                        list10 = list5;
                        str54 = str37;
                        str55 = str36;
                        str56 = str35;
                        str57 = str34;
                        str58 = str33;
                        str59 = str31;
                        str51 = str28;
                        str23 = str60;
                        str21 = str50;
                        String str662222222222222222 = str62;
                        kSerializerArr = kSerializerArr2;
                        str27 = str662222222222222222;
                        String str672222222222222222 = str30;
                        i9 = i4;
                        str53 = str672222222222222222;
                        str50 = str21;
                        str52 = str26;
                        str61 = str24;
                        str60 = str23;
                        KSerializer[] kSerializerArr32222222222222222222222222222222 = kSerializerArr;
                        str62 = str27;
                        kSerializerArr2 = kSerializerArr32222222222222222222222222222222;
                        break;
                    default:
                        throw new UnknownFieldException(iDecodeElementIndex);
                }
            }
            list = list12;
            list2 = list11;
            str = str53;
            list3 = list10;
            str2 = str54;
            str3 = str55;
            str4 = str56;
            str5 = str57;
            str6 = str58;
            str7 = str59;
            str8 = str51;
            str9 = str61;
            str10 = str60;
            z = zDecodeBooleanElement7;
            str11 = strDecodeStringElement8;
            str12 = strDecodeStringElement9;
            z2 = zDecodeBooleanElement8;
            i = iDecodeIntElement3;
            str13 = strDecodeStringElement10;
            str14 = strDecodeStringElement12;
            str15 = strDecodeStringElement13;
            str16 = strDecodeStringElement14;
            z3 = zDecodeBooleanElement9;
            z4 = zDecodeBooleanElement10;
            i2 = iDecodeIntElement4;
            zDecodeBooleanElement = zDecodeBooleanElement12;
            str17 = str62;
            str18 = str50;
            str19 = str52;
            str20 = strDecodeStringElement11;
            z5 = zDecodeBooleanElement11;
        }
        compositeDecoderBeginStructure.endStructure(serialDescriptor);
        return new UserTradeConfigInfo(i9, str16, str15, str14, z4, z, zDecodeBooleanElement, str11, z5, str12, str20, i2, list, str13, str17, str10, str9, str19, str7, str8, i, list3, str2, z3, z2, str3, list2, str4, str5, str, str6, str18, (SerializationConstructorMarker) null);
    }

    /* JADX DEBUG: Method merged with bridge method: serialize(Lkotlinx/serialization/encoding/Encoder;Ljava/lang/Object;)V */
    @Override // kotlinx.serialization.SerializationStrategy
    public final void serialize(@NotNull Encoder encoder, @NotNull UserTradeConfigInfo userTradeConfigInfo) {
        Intrinsics.checkNotNullParameter(encoder, "");
        Intrinsics.checkNotNullParameter(userTradeConfigInfo, "");
        SerialDescriptor serialDescriptor = descriptor;
        CompositeEncoder compositeEncoderBeginStructure = encoder.beginStructure(serialDescriptor);
        UserTradeConfigInfo.write$Self$OKTradeCore_trade_core(userTradeConfigInfo, compositeEncoderBeginStructure, serialDescriptor);
        compositeEncoderBeginStructure.endStructure(serialDescriptor);
    }
}
