package uniffi.settings;

import com.sun.jna.Structure;
import kotlin.jvm.internal.DefaultConstructorMarker;
import kotlin.jvm.internal.Intrinsics;
import org.jetbrains.annotations.NotNull;
import uniffi.UniffiCallbackInterfaceClone;
import uniffi.UniffiCallbackInterfaceFree;

/* JADX INFO: loaded from: classes13.dex */
@Structure.FieldOrder({"uniffiFree", "uniffiClone", "getSettingsFromRemote", "getSettingsFromCache", "getCurrencyListFromRemote", "getCurrencyListFromCache", "updateCurrencyList", "getCurrencyInfoWithIsoCode", "getCurrencyPref", "getFundUnit", "updateUserSettings", "setRiseFallColor", "setColorAppearance", "setColorPalette", "setRiseFallCycle", "setCurrencyPref", "setFundUnit", "setUserLanguage", "registerSettingsEventCallback"})
public class UniffiVTableCallbackInterfaceSettingsServiceForeignHandling extends Structure {
    public static final int $stable = 8;
    public UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod5 getCurrencyInfoWithIsoCode;
    public UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod3 getCurrencyListFromCache;
    public UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod2 getCurrencyListFromRemote;
    public UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod6 getCurrencyPref;
    public UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod7 getFundUnit;
    public UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod1 getSettingsFromCache;
    public UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod0 getSettingsFromRemote;
    public UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod16 registerSettingsEventCallback;
    public UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod10 setColorAppearance;
    public UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod11 setColorPalette;
    public UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod13 setCurrencyPref;
    public UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod14 setFundUnit;
    public UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod9 setRiseFallColor;
    public UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod12 setRiseFallCycle;
    public UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod15 setUserLanguage;
    public UniffiCallbackInterfaceClone uniffiClone;
    public UniffiCallbackInterfaceFree uniffiFree;
    public UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod4 updateCurrencyList;
    public UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod8 updateUserSettings;

    /* JADX DEBUG: Don't trust debug lines info. Lines numbers was adjusted: min line is 0 */
    public UniffiVTableCallbackInterfaceSettingsServiceForeignHandling() {
        this(null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 524287, null);
    }

    /* JADX DEBUG: Can't inline method, not implemented redirect type for insn: 0x00ce: CONSTRUCTOR 
  (wrap:uniffi.UniffiCallbackInterfaceFree:?: TERNARY null = ((wrap:int:0x0002: ARITH (r40v0 int) & (1 int) A[WRAPPED]) != (0 int)) ? (null uniffi.UniffiCallbackInterfaceFree) : (r21v0 uniffi.UniffiCallbackInterfaceFree))
  (wrap:uniffi.UniffiCallbackInterfaceClone:?: TERNARY null = ((wrap:int:0x000a: ARITH (r40v0 int) & (2 int) A[WRAPPED]) != (0 int)) ? (null uniffi.UniffiCallbackInterfaceClone) : (r22v0 uniffi.UniffiCallbackInterfaceClone))
  (wrap:uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod0:?: TERNARY null = ((wrap:int:0x0012: ARITH (r40v0 int) & (4 int) A[WRAPPED]) != (0 int)) ? (null uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod0) : (r23v0 uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod0))
  (wrap:uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod1:?: TERNARY null = ((wrap:int:0x001a: ARITH (r40v0 int) & (8 int) A[WRAPPED]) != (0 int)) ? (null uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod1) : (r24v0 uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod1))
  (wrap:uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod2:?: TERNARY null = ((wrap:int:0x0022: ARITH (r40v0 int) & (16 int) A[WRAPPED]) != (0 int)) ? (null uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod2) : (r25v0 uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod2))
  (wrap:uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod3:?: TERNARY null = ((wrap:int:0x002a: ARITH (r40v0 int) & (32 int) A[WRAPPED]) != (0 int)) ? (null uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod3) : (r26v0 uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod3))
  (wrap:uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod4:?: TERNARY null = ((wrap:int:0x0032: ARITH (r40v0 int) & (64 int) A[WRAPPED]) != (0 int)) ? (null uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod4) : (r27v0 uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod4))
  (wrap:uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod5:?: TERNARY null = ((wrap:int:0x003a: ARITH (r40v0 int) & (128 int) A[WRAPPED]) != (0 int)) ? (null uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod5) : (r28v0 uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod5))
  (wrap:uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod6:?: TERNARY null = ((wrap:int:0x0042: ARITH (r40v0 int) & (256 int) A[WRAPPED]) != (0 int)) ? (null uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod6) : (r29v0 uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod6))
  (wrap:uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod7:?: TERNARY null = ((wrap:int:0x004a: ARITH (r40v0 int) & (512 int) A[WRAPPED]) != (0 int)) ? (null uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod7) : (r30v0 uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod7))
  (wrap:uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod8:?: TERNARY null = ((wrap:int:0x0052: ARITH (r40v0 int) & (1024 int) A[WRAPPED]) != (0 int)) ? (null uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod8) : (r31v0 uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod8))
  (wrap:uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod9:?: TERNARY null = ((wrap:int:0x005a: ARITH (r40v0 int) & (2048 int) A[WRAPPED]) != (0 int)) ? (null uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod9) : (r32v0 uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod9))
  (wrap:uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod10:?: TERNARY null = ((wrap:int:0x0062: ARITH (r40v0 int) & (4096 int) A[WRAPPED]) != (0 int)) ? (null uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod10) : (r33v0 uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod10))
  (wrap:uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod11:?: TERNARY null = ((wrap:int:0x006a: ARITH (r40v0 int) & (8192 int) A[WRAPPED]) != (0 int)) ? (null uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod11) : (r34v0 uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod11))
  (wrap:uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod12:?: TERNARY null = ((wrap:int:0x0072: ARITH (r40v0 int) & (16384 int) A[WRAPPED]) != (0 int)) ? (null uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod12) : (r35v0 uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod12))
  (wrap:uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod13:?: TERNARY null = ((wrap:int:0x007d: ARITH (r40v0 int) & (32768 int) A[WRAPPED]) != (0 int)) ? (null uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod13) : (r36v0 uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod13))
  (wrap:uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod14:?: TERNARY null = ((wrap:int:0x0088: ARITH (r40v0 int) & (65536 int) A[WRAPPED]) != (0 int)) ? (null uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod14) : (r37v0 uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod14))
  (wrap:uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod15:?: TERNARY null = ((wrap:int:0x0093: ARITH (r40v0 int) & (131072 int) A[WRAPPED]) != (0 int)) ? (null uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod15) : (r38v0 uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod15))
  (wrap:uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod16:?: TERNARY null = ((wrap:int:0x009e: ARITH (r40v0 int) & (262144 int) A[WRAPPED]) != (0 int)) ? (null uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod16) : (r39v0 uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod16))
 A[MD:(uniffi.UniffiCallbackInterfaceFree, uniffi.UniffiCallbackInterfaceClone, uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod0, uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod1, uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod2, uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod3, uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod4, uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod5, uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod6, uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod7, uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod8, uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod9, uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod10, uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod11, uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod12, uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod13, uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod14, uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod15, uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod16):void (m)] (LINE:344) call: uniffi.settings.UniffiVTableCallbackInterfaceSettingsServiceForeignHandling.<init>(uniffi.UniffiCallbackInterfaceFree, uniffi.UniffiCallbackInterfaceClone, uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod0, uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod1, uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod2, uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod3, uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod4, uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod5, uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod6, uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod7, uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod8, uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod9, uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod10, uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod11, uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod12, uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod13, uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod14, uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod15, uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod16):void type: THIS */
    public /* synthetic */ UniffiVTableCallbackInterfaceSettingsServiceForeignHandling(UniffiCallbackInterfaceFree uniffiCallbackInterfaceFree, UniffiCallbackInterfaceClone uniffiCallbackInterfaceClone, UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod0 uniffiCallbackInterfaceSettingsServiceForeignHandlingMethod0, UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod1 uniffiCallbackInterfaceSettingsServiceForeignHandlingMethod1, UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod2 uniffiCallbackInterfaceSettingsServiceForeignHandlingMethod2, UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod3 uniffiCallbackInterfaceSettingsServiceForeignHandlingMethod3, UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod4 uniffiCallbackInterfaceSettingsServiceForeignHandlingMethod4, UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod5 uniffiCallbackInterfaceSettingsServiceForeignHandlingMethod5, UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod6 uniffiCallbackInterfaceSettingsServiceForeignHandlingMethod6, UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod7 uniffiCallbackInterfaceSettingsServiceForeignHandlingMethod7, UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod8 uniffiCallbackInterfaceSettingsServiceForeignHandlingMethod8, UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod9 uniffiCallbackInterfaceSettingsServiceForeignHandlingMethod9, UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod10 uniffiCallbackInterfaceSettingsServiceForeignHandlingMethod10, UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod11 uniffiCallbackInterfaceSettingsServiceForeignHandlingMethod11, UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod12 uniffiCallbackInterfaceSettingsServiceForeignHandlingMethod12, UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod13 uniffiCallbackInterfaceSettingsServiceForeignHandlingMethod13, UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod14 uniffiCallbackInterfaceSettingsServiceForeignHandlingMethod14, UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod15 uniffiCallbackInterfaceSettingsServiceForeignHandlingMethod15, UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod16 uniffiCallbackInterfaceSettingsServiceForeignHandlingMethod16, int i, DefaultConstructorMarker defaultConstructorMarker) {
        this((i & 1) != 0 ? null : uniffiCallbackInterfaceFree, (i & 2) != 0 ? null : uniffiCallbackInterfaceClone, (i & 4) != 0 ? null : uniffiCallbackInterfaceSettingsServiceForeignHandlingMethod0, (i & 8) != 0 ? null : uniffiCallbackInterfaceSettingsServiceForeignHandlingMethod1, (i & 16) != 0 ? null : uniffiCallbackInterfaceSettingsServiceForeignHandlingMethod2, (i & 32) != 0 ? null : uniffiCallbackInterfaceSettingsServiceForeignHandlingMethod3, (i & 64) != 0 ? null : uniffiCallbackInterfaceSettingsServiceForeignHandlingMethod4, (i & 128) != 0 ? null : uniffiCallbackInterfaceSettingsServiceForeignHandlingMethod5, (i & 256) != 0 ? null : uniffiCallbackInterfaceSettingsServiceForeignHandlingMethod6, (i & 512) != 0 ? null : uniffiCallbackInterfaceSettingsServiceForeignHandlingMethod7, (i & 1024) != 0 ? null : uniffiCallbackInterfaceSettingsServiceForeignHandlingMethod8, (i & 2048) != 0 ? null : uniffiCallbackInterfaceSettingsServiceForeignHandlingMethod9, (i & 4096) != 0 ? null : uniffiCallbackInterfaceSettingsServiceForeignHandlingMethod10, (i & 8192) != 0 ? null : uniffiCallbackInterfaceSettingsServiceForeignHandlingMethod11, (i & 16384) != 0 ? null : uniffiCallbackInterfaceSettingsServiceForeignHandlingMethod12, (i & 32768) != 0 ? null : uniffiCallbackInterfaceSettingsServiceForeignHandlingMethod13, (i & 65536) != 0 ? null : uniffiCallbackInterfaceSettingsServiceForeignHandlingMethod14, (i & 131072) != 0 ? null : uniffiCallbackInterfaceSettingsServiceForeignHandlingMethod15, (i & 262144) != 0 ? null : uniffiCallbackInterfaceSettingsServiceForeignHandlingMethod16);
    }

    public static final class UniffiByValue extends UniffiVTableCallbackInterfaceSettingsServiceForeignHandling implements Structure.ByValue {
        public static final int $stable = 0;

        /* JADX DEBUG: Don't trust debug lines info. Lines numbers was adjusted: min line is 0 */
        public UniffiByValue() {
            this(null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 524287, null);
        }

        /* JADX DEBUG: Can't inline method, not implemented redirect type for insn: 0x00ce: CONSTRUCTOR 
  (wrap:uniffi.UniffiCallbackInterfaceFree:?: TERNARY null = ((wrap:int:0x0002: ARITH (r40v0 int) & (1 int) A[WRAPPED]) != (0 int)) ? (null uniffi.UniffiCallbackInterfaceFree) : (r21v0 uniffi.UniffiCallbackInterfaceFree))
  (wrap:uniffi.UniffiCallbackInterfaceClone:?: TERNARY null = ((wrap:int:0x000a: ARITH (r40v0 int) & (2 int) A[WRAPPED]) != (0 int)) ? (null uniffi.UniffiCallbackInterfaceClone) : (r22v0 uniffi.UniffiCallbackInterfaceClone))
  (wrap:uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod0:?: TERNARY null = ((wrap:int:0x0012: ARITH (r40v0 int) & (4 int) A[WRAPPED]) != (0 int)) ? (null uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod0) : (r23v0 uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod0))
  (wrap:uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod1:?: TERNARY null = ((wrap:int:0x001a: ARITH (r40v0 int) & (8 int) A[WRAPPED]) != (0 int)) ? (null uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod1) : (r24v0 uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod1))
  (wrap:uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod2:?: TERNARY null = ((wrap:int:0x0022: ARITH (r40v0 int) & (16 int) A[WRAPPED]) != (0 int)) ? (null uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod2) : (r25v0 uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod2))
  (wrap:uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod3:?: TERNARY null = ((wrap:int:0x002a: ARITH (r40v0 int) & (32 int) A[WRAPPED]) != (0 int)) ? (null uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod3) : (r26v0 uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod3))
  (wrap:uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod4:?: TERNARY null = ((wrap:int:0x0032: ARITH (r40v0 int) & (64 int) A[WRAPPED]) != (0 int)) ? (null uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod4) : (r27v0 uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod4))
  (wrap:uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod5:?: TERNARY null = ((wrap:int:0x003a: ARITH (r40v0 int) & (128 int) A[WRAPPED]) != (0 int)) ? (null uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod5) : (r28v0 uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod5))
  (wrap:uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod6:?: TERNARY null = ((wrap:int:0x0042: ARITH (r40v0 int) & (256 int) A[WRAPPED]) != (0 int)) ? (null uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod6) : (r29v0 uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod6))
  (wrap:uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod7:?: TERNARY null = ((wrap:int:0x004a: ARITH (r40v0 int) & (512 int) A[WRAPPED]) != (0 int)) ? (null uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod7) : (r30v0 uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod7))
  (wrap:uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod8:?: TERNARY null = ((wrap:int:0x0052: ARITH (r40v0 int) & (1024 int) A[WRAPPED]) != (0 int)) ? (null uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod8) : (r31v0 uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod8))
  (wrap:uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod9:?: TERNARY null = ((wrap:int:0x005a: ARITH (r40v0 int) & (2048 int) A[WRAPPED]) != (0 int)) ? (null uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod9) : (r32v0 uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod9))
  (wrap:uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod10:?: TERNARY null = ((wrap:int:0x0062: ARITH (r40v0 int) & (4096 int) A[WRAPPED]) != (0 int)) ? (null uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod10) : (r33v0 uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod10))
  (wrap:uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod11:?: TERNARY null = ((wrap:int:0x006a: ARITH (r40v0 int) & (8192 int) A[WRAPPED]) != (0 int)) ? (null uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod11) : (r34v0 uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod11))
  (wrap:uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod12:?: TERNARY null = ((wrap:int:0x0072: ARITH (r40v0 int) & (16384 int) A[WRAPPED]) != (0 int)) ? (null uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod12) : (r35v0 uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod12))
  (wrap:uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod13:?: TERNARY null = ((wrap:int:0x007d: ARITH (r40v0 int) & (32768 int) A[WRAPPED]) != (0 int)) ? (null uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod13) : (r36v0 uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod13))
  (wrap:uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod14:?: TERNARY null = ((wrap:int:0x0088: ARITH (r40v0 int) & (65536 int) A[WRAPPED]) != (0 int)) ? (null uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod14) : (r37v0 uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod14))
  (wrap:uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod15:?: TERNARY null = ((wrap:int:0x0093: ARITH (r40v0 int) & (131072 int) A[WRAPPED]) != (0 int)) ? (null uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod15) : (r38v0 uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod15))
  (wrap:uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod16:?: TERNARY null = ((wrap:int:0x009e: ARITH (r40v0 int) & (262144 int) A[WRAPPED]) != (0 int)) ? (null uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod16) : (r39v0 uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod16))
 A[MD:(uniffi.UniffiCallbackInterfaceFree, uniffi.UniffiCallbackInterfaceClone, uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod0, uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod1, uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod2, uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod3, uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod4, uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod5, uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod6, uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod7, uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod8, uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod9, uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod10, uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod11, uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod12, uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod13, uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod14, uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod15, uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod16):void (m)] (LINE:365) call: uniffi.settings.UniffiVTableCallbackInterfaceSettingsServiceForeignHandling.UniffiByValue.<init>(uniffi.UniffiCallbackInterfaceFree, uniffi.UniffiCallbackInterfaceClone, uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod0, uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod1, uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod2, uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod3, uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod4, uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod5, uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod6, uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod7, uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod8, uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod9, uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod10, uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod11, uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod12, uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod13, uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod14, uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod15, uniffi.settings.UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod16):void type: THIS */
        public /* synthetic */ UniffiByValue(UniffiCallbackInterfaceFree uniffiCallbackInterfaceFree, UniffiCallbackInterfaceClone uniffiCallbackInterfaceClone, UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod0 uniffiCallbackInterfaceSettingsServiceForeignHandlingMethod0, UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod1 uniffiCallbackInterfaceSettingsServiceForeignHandlingMethod1, UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod2 uniffiCallbackInterfaceSettingsServiceForeignHandlingMethod2, UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod3 uniffiCallbackInterfaceSettingsServiceForeignHandlingMethod3, UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod4 uniffiCallbackInterfaceSettingsServiceForeignHandlingMethod4, UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod5 uniffiCallbackInterfaceSettingsServiceForeignHandlingMethod5, UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod6 uniffiCallbackInterfaceSettingsServiceForeignHandlingMethod6, UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod7 uniffiCallbackInterfaceSettingsServiceForeignHandlingMethod7, UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod8 uniffiCallbackInterfaceSettingsServiceForeignHandlingMethod8, UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod9 uniffiCallbackInterfaceSettingsServiceForeignHandlingMethod9, UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod10 uniffiCallbackInterfaceSettingsServiceForeignHandlingMethod10, UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod11 uniffiCallbackInterfaceSettingsServiceForeignHandlingMethod11, UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod12 uniffiCallbackInterfaceSettingsServiceForeignHandlingMethod12, UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod13 uniffiCallbackInterfaceSettingsServiceForeignHandlingMethod13, UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod14 uniffiCallbackInterfaceSettingsServiceForeignHandlingMethod14, UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod15 uniffiCallbackInterfaceSettingsServiceForeignHandlingMethod15, UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod16 uniffiCallbackInterfaceSettingsServiceForeignHandlingMethod16, int i, DefaultConstructorMarker defaultConstructorMarker) {
            this((i & 1) != 0 ? null : uniffiCallbackInterfaceFree, (i & 2) != 0 ? null : uniffiCallbackInterfaceClone, (i & 4) != 0 ? null : uniffiCallbackInterfaceSettingsServiceForeignHandlingMethod0, (i & 8) != 0 ? null : uniffiCallbackInterfaceSettingsServiceForeignHandlingMethod1, (i & 16) != 0 ? null : uniffiCallbackInterfaceSettingsServiceForeignHandlingMethod2, (i & 32) != 0 ? null : uniffiCallbackInterfaceSettingsServiceForeignHandlingMethod3, (i & 64) != 0 ? null : uniffiCallbackInterfaceSettingsServiceForeignHandlingMethod4, (i & 128) != 0 ? null : uniffiCallbackInterfaceSettingsServiceForeignHandlingMethod5, (i & 256) != 0 ? null : uniffiCallbackInterfaceSettingsServiceForeignHandlingMethod6, (i & 512) != 0 ? null : uniffiCallbackInterfaceSettingsServiceForeignHandlingMethod7, (i & 1024) != 0 ? null : uniffiCallbackInterfaceSettingsServiceForeignHandlingMethod8, (i & 2048) != 0 ? null : uniffiCallbackInterfaceSettingsServiceForeignHandlingMethod9, (i & 4096) != 0 ? null : uniffiCallbackInterfaceSettingsServiceForeignHandlingMethod10, (i & 8192) != 0 ? null : uniffiCallbackInterfaceSettingsServiceForeignHandlingMethod11, (i & 16384) != 0 ? null : uniffiCallbackInterfaceSettingsServiceForeignHandlingMethod12, (i & 32768) != 0 ? null : uniffiCallbackInterfaceSettingsServiceForeignHandlingMethod13, (i & 65536) != 0 ? null : uniffiCallbackInterfaceSettingsServiceForeignHandlingMethod14, (i & 131072) != 0 ? null : uniffiCallbackInterfaceSettingsServiceForeignHandlingMethod15, (i & 262144) != 0 ? null : uniffiCallbackInterfaceSettingsServiceForeignHandlingMethod16);
        }

        public UniffiByValue(UniffiCallbackInterfaceFree uniffiCallbackInterfaceFree, UniffiCallbackInterfaceClone uniffiCallbackInterfaceClone, UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod0 uniffiCallbackInterfaceSettingsServiceForeignHandlingMethod0, UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod1 uniffiCallbackInterfaceSettingsServiceForeignHandlingMethod1, UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod2 uniffiCallbackInterfaceSettingsServiceForeignHandlingMethod2, UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod3 uniffiCallbackInterfaceSettingsServiceForeignHandlingMethod3, UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod4 uniffiCallbackInterfaceSettingsServiceForeignHandlingMethod4, UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod5 uniffiCallbackInterfaceSettingsServiceForeignHandlingMethod5, UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod6 uniffiCallbackInterfaceSettingsServiceForeignHandlingMethod6, UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod7 uniffiCallbackInterfaceSettingsServiceForeignHandlingMethod7, UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod8 uniffiCallbackInterfaceSettingsServiceForeignHandlingMethod8, UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod9 uniffiCallbackInterfaceSettingsServiceForeignHandlingMethod9, UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod10 uniffiCallbackInterfaceSettingsServiceForeignHandlingMethod10, UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod11 uniffiCallbackInterfaceSettingsServiceForeignHandlingMethod11, UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod12 uniffiCallbackInterfaceSettingsServiceForeignHandlingMethod12, UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod13 uniffiCallbackInterfaceSettingsServiceForeignHandlingMethod13, UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod14 uniffiCallbackInterfaceSettingsServiceForeignHandlingMethod14, UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod15 uniffiCallbackInterfaceSettingsServiceForeignHandlingMethod15, UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod16 uniffiCallbackInterfaceSettingsServiceForeignHandlingMethod16) {
            super(uniffiCallbackInterfaceFree, uniffiCallbackInterfaceClone, uniffiCallbackInterfaceSettingsServiceForeignHandlingMethod0, uniffiCallbackInterfaceSettingsServiceForeignHandlingMethod1, uniffiCallbackInterfaceSettingsServiceForeignHandlingMethod2, uniffiCallbackInterfaceSettingsServiceForeignHandlingMethod3, uniffiCallbackInterfaceSettingsServiceForeignHandlingMethod4, uniffiCallbackInterfaceSettingsServiceForeignHandlingMethod5, uniffiCallbackInterfaceSettingsServiceForeignHandlingMethod6, uniffiCallbackInterfaceSettingsServiceForeignHandlingMethod7, uniffiCallbackInterfaceSettingsServiceForeignHandlingMethod8, uniffiCallbackInterfaceSettingsServiceForeignHandlingMethod9, uniffiCallbackInterfaceSettingsServiceForeignHandlingMethod10, uniffiCallbackInterfaceSettingsServiceForeignHandlingMethod11, uniffiCallbackInterfaceSettingsServiceForeignHandlingMethod12, uniffiCallbackInterfaceSettingsServiceForeignHandlingMethod13, uniffiCallbackInterfaceSettingsServiceForeignHandlingMethod14, uniffiCallbackInterfaceSettingsServiceForeignHandlingMethod15, uniffiCallbackInterfaceSettingsServiceForeignHandlingMethod16);
        }
    }

    public UniffiVTableCallbackInterfaceSettingsServiceForeignHandling(UniffiCallbackInterfaceFree uniffiCallbackInterfaceFree, UniffiCallbackInterfaceClone uniffiCallbackInterfaceClone, UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod0 uniffiCallbackInterfaceSettingsServiceForeignHandlingMethod0, UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod1 uniffiCallbackInterfaceSettingsServiceForeignHandlingMethod1, UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod2 uniffiCallbackInterfaceSettingsServiceForeignHandlingMethod2, UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod3 uniffiCallbackInterfaceSettingsServiceForeignHandlingMethod3, UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod4 uniffiCallbackInterfaceSettingsServiceForeignHandlingMethod4, UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod5 uniffiCallbackInterfaceSettingsServiceForeignHandlingMethod5, UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod6 uniffiCallbackInterfaceSettingsServiceForeignHandlingMethod6, UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod7 uniffiCallbackInterfaceSettingsServiceForeignHandlingMethod7, UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod8 uniffiCallbackInterfaceSettingsServiceForeignHandlingMethod8, UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod9 uniffiCallbackInterfaceSettingsServiceForeignHandlingMethod9, UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod10 uniffiCallbackInterfaceSettingsServiceForeignHandlingMethod10, UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod11 uniffiCallbackInterfaceSettingsServiceForeignHandlingMethod11, UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod12 uniffiCallbackInterfaceSettingsServiceForeignHandlingMethod12, UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod13 uniffiCallbackInterfaceSettingsServiceForeignHandlingMethod13, UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod14 uniffiCallbackInterfaceSettingsServiceForeignHandlingMethod14, UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod15 uniffiCallbackInterfaceSettingsServiceForeignHandlingMethod15, UniffiCallbackInterfaceSettingsServiceForeignHandlingMethod16 uniffiCallbackInterfaceSettingsServiceForeignHandlingMethod16) {
        this.uniffiFree = uniffiCallbackInterfaceFree;
        this.uniffiClone = uniffiCallbackInterfaceClone;
        this.getSettingsFromRemote = uniffiCallbackInterfaceSettingsServiceForeignHandlingMethod0;
        this.getSettingsFromCache = uniffiCallbackInterfaceSettingsServiceForeignHandlingMethod1;
        this.getCurrencyListFromRemote = uniffiCallbackInterfaceSettingsServiceForeignHandlingMethod2;
        this.getCurrencyListFromCache = uniffiCallbackInterfaceSettingsServiceForeignHandlingMethod3;
        this.updateCurrencyList = uniffiCallbackInterfaceSettingsServiceForeignHandlingMethod4;
        this.getCurrencyInfoWithIsoCode = uniffiCallbackInterfaceSettingsServiceForeignHandlingMethod5;
        this.getCurrencyPref = uniffiCallbackInterfaceSettingsServiceForeignHandlingMethod6;
        this.getFundUnit = uniffiCallbackInterfaceSettingsServiceForeignHandlingMethod7;
        this.updateUserSettings = uniffiCallbackInterfaceSettingsServiceForeignHandlingMethod8;
        this.setRiseFallColor = uniffiCallbackInterfaceSettingsServiceForeignHandlingMethod9;
        this.setColorAppearance = uniffiCallbackInterfaceSettingsServiceForeignHandlingMethod10;
        this.setColorPalette = uniffiCallbackInterfaceSettingsServiceForeignHandlingMethod11;
        this.setRiseFallCycle = uniffiCallbackInterfaceSettingsServiceForeignHandlingMethod12;
        this.setCurrencyPref = uniffiCallbackInterfaceSettingsServiceForeignHandlingMethod13;
        this.setFundUnit = uniffiCallbackInterfaceSettingsServiceForeignHandlingMethod14;
        this.setUserLanguage = uniffiCallbackInterfaceSettingsServiceForeignHandlingMethod15;
        this.registerSettingsEventCallback = uniffiCallbackInterfaceSettingsServiceForeignHandlingMethod16;
    }

    public final void uniffiSetValue$OKCore_deploy(@NotNull UniffiVTableCallbackInterfaceSettingsServiceForeignHandling uniffiVTableCallbackInterfaceSettingsServiceForeignHandling) {
        Intrinsics.checkNotNullParameter(uniffiVTableCallbackInterfaceSettingsServiceForeignHandling, "");
        this.uniffiFree = uniffiVTableCallbackInterfaceSettingsServiceForeignHandling.uniffiFree;
        this.uniffiClone = uniffiVTableCallbackInterfaceSettingsServiceForeignHandling.uniffiClone;
        this.getSettingsFromRemote = uniffiVTableCallbackInterfaceSettingsServiceForeignHandling.getSettingsFromRemote;
        this.getSettingsFromCache = uniffiVTableCallbackInterfaceSettingsServiceForeignHandling.getSettingsFromCache;
        this.getCurrencyListFromRemote = uniffiVTableCallbackInterfaceSettingsServiceForeignHandling.getCurrencyListFromRemote;
        this.getCurrencyListFromCache = uniffiVTableCallbackInterfaceSettingsServiceForeignHandling.getCurrencyListFromCache;
        this.updateCurrencyList = uniffiVTableCallbackInterfaceSettingsServiceForeignHandling.updateCurrencyList;
        this.getCurrencyInfoWithIsoCode = uniffiVTableCallbackInterfaceSettingsServiceForeignHandling.getCurrencyInfoWithIsoCode;
        this.getCurrencyPref = uniffiVTableCallbackInterfaceSettingsServiceForeignHandling.getCurrencyPref;
        this.getFundUnit = uniffiVTableCallbackInterfaceSettingsServiceForeignHandling.getFundUnit;
        this.updateUserSettings = uniffiVTableCallbackInterfaceSettingsServiceForeignHandling.updateUserSettings;
        this.setRiseFallColor = uniffiVTableCallbackInterfaceSettingsServiceForeignHandling.setRiseFallColor;
        this.setColorAppearance = uniffiVTableCallbackInterfaceSettingsServiceForeignHandling.setColorAppearance;
        this.setColorPalette = uniffiVTableCallbackInterfaceSettingsServiceForeignHandling.setColorPalette;
        this.setRiseFallCycle = uniffiVTableCallbackInterfaceSettingsServiceForeignHandling.setRiseFallCycle;
        this.setCurrencyPref = uniffiVTableCallbackInterfaceSettingsServiceForeignHandling.setCurrencyPref;
        this.setFundUnit = uniffiVTableCallbackInterfaceSettingsServiceForeignHandling.setFundUnit;
        this.setUserLanguage = uniffiVTableCallbackInterfaceSettingsServiceForeignHandling.setUserLanguage;
        this.registerSettingsEventCallback = uniffiVTableCallbackInterfaceSettingsServiceForeignHandling.registerSettingsEventCallback;
    }
}
