package com.okinc.business.defi.wallet.passkey.common.ws.bean;

import com.google.api.client.googleapis.media.MediaHttpDownloader;
import java.util.List;
import kotlin.Unit;
import kotlin.jvm.internal.Intrinsics;
import kotlinx.serialization.KSerializer;
import kotlinx.serialization.UnknownFieldException;
import kotlinx.serialization.builtins.BuiltinSerializersKt;
import kotlinx.serialization.descriptors.SerialDescriptor;
import kotlinx.serialization.encoding.CompositeDecoder;
import kotlinx.serialization.encoding.CompositeEncoder;
import kotlinx.serialization.encoding.Decoder;
import kotlinx.serialization.encoding.Encoder;
import kotlinx.serialization.internal.GeneratedSerializer;
import kotlinx.serialization.internal.IntSerializer;
import kotlinx.serialization.internal.LongSerializer;
import kotlinx.serialization.internal.PluginGeneratedSerialDescriptor;
import kotlinx.serialization.internal.SerializationConstructorMarker;
import kotlinx.serialization.internal.StringSerializer;
import org.jetbrains.annotations.NotNull;

/* JADX INFO: loaded from: classes5.dex */
public final /* synthetic */ class TxStatusSubResponse$$serializer implements GeneratedSerializer<TxStatusSubResponse> {
    public static final int $stable;
    public static final TxStatusSubResponse$$serializer INSTANCE;
    private static final SerialDescriptor descriptor;

    /* JADX DEBUG: Don't trust debug lines info. Lines numbers was adjusted: min line is 0 */
    private TxStatusSubResponse$$serializer() {
    }

    /* JADX DEBUG: Don't trust debug lines info. Lines numbers was adjusted: min line is 0 */
    @Override // kotlinx.serialization.KSerializer, kotlinx.serialization.SerializationStrategy, kotlinx.serialization.DeserializationStrategy
    public final SerialDescriptor getDescriptor() {
        return descriptor;
    }

    static {
        TxStatusSubResponse$$serializer txStatusSubResponse$$serializer = new TxStatusSubResponse$$serializer();
        INSTANCE = txStatusSubResponse$$serializer;
        $stable = 8;
        PluginGeneratedSerialDescriptor pluginGeneratedSerialDescriptor = new PluginGeneratedSerialDescriptor("com.okinc.business.defi.wallet.passkey.common.ws.bean.TxStatusSubResponse", txStatusSubResponse$$serializer, 30);
        pluginGeneratedSerialDescriptor.addElement("orderId", false);
        pluginGeneratedSerialDescriptor.addElement("parentOrderId", false);
        pluginGeneratedSerialDescriptor.addElement("status", false);
        pluginGeneratedSerialDescriptor.addElement("uopHash", true);
        pluginGeneratedSerialDescriptor.addElement("txHash", false);
        pluginGeneratedSerialDescriptor.addElement("timeToCancel", true);
        pluginGeneratedSerialDescriptor.addElement("orderType", false);
        pluginGeneratedSerialDescriptor.addElement("productCode", true);
        pluginGeneratedSerialDescriptor.addElement("merchantId", true);
        pluginGeneratedSerialDescriptor.addElement("code", true);
        pluginGeneratedSerialDescriptor.addElement("convertStages", true);
        pluginGeneratedSerialDescriptor.addElement("failedType", true);
        pluginGeneratedSerialDescriptor.addElement("toTokenAmount", true);
        pluginGeneratedSerialDescriptor.addElement("msgType", true);
        pluginGeneratedSerialDescriptor.addElement("tokenSymbol", true);
        pluginGeneratedSerialDescriptor.addElement("tokenDecimal", true);
        pluginGeneratedSerialDescriptor.addElement("chainIndex", true);
        pluginGeneratedSerialDescriptor.addElement("tokenAddress", true);
        pluginGeneratedSerialDescriptor.addElement("tokenAmount", true);
        pluginGeneratedSerialDescriptor.addElement("currencyAmount", true);
        pluginGeneratedSerialDescriptor.addElement("from", true);
        pluginGeneratedSerialDescriptor.addElement("to", true);
        pluginGeneratedSerialDescriptor.addElement("createTime", true);
        pluginGeneratedSerialDescriptor.addElement("receiverType", true);
        pluginGeneratedSerialDescriptor.addElement("areaCode", true);
        pluginGeneratedSerialDescriptor.addElement("subStatus", true);
        pluginGeneratedSerialDescriptor.addElement("firstPackTime", true);
        pluginGeneratedSerialDescriptor.addElement("gasFeeType", true);
        pluginGeneratedSerialDescriptor.addElement("tokenCoinTypeNo", true);
        pluginGeneratedSerialDescriptor.addElement("convertInfo", true);
        descriptor = pluginGeneratedSerialDescriptor;
    }

    @Override // kotlinx.serialization.internal.GeneratedSerializer
    public final KSerializer<?>[] childSerializers() {
        KSerializer[] kSerializerArr = TxStatusSubResponse.$childSerializers;
        StringSerializer stringSerializer = StringSerializer.INSTANCE;
        IntSerializer intSerializer = IntSerializer.INSTANCE;
        LongSerializer longSerializer = LongSerializer.INSTANCE;
        return new KSerializer[]{stringSerializer, stringSerializer, intSerializer, BuiltinSerializersKt.getNullable(stringSerializer), stringSerializer, BuiltinSerializersKt.getNullable(longSerializer), intSerializer, BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(intSerializer), BuiltinSerializersKt.getNullable(kSerializerArr[10]), BuiltinSerializersKt.getNullable(intSerializer), BuiltinSerializersKt.getNullable(stringSerializer), intSerializer, BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(intSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(longSerializer), BuiltinSerializersKt.getNullable(intSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(intSerializer), BuiltinSerializersKt.getNullable(longSerializer), BuiltinSerializersKt.getNullable(intSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(ConvertInfoWS$$serializer.INSTANCE)};
    }

    /* JADX DEBUG: Method merged with bridge method: deserialize(Lkotlinx/serialization/encoding/Decoder;)Ljava/lang/Object; */
    @Override // kotlinx.serialization.DeserializationStrategy
    public final TxStatusSubResponse deserialize(@NotNull Decoder decoder) {
        ConvertInfoWS convertInfoWS;
        Integer num;
        int i;
        String str;
        String str2;
        String str3;
        String str4;
        Integer num2;
        String str5;
        String str6;
        Long l;
        String str7;
        Integer num3;
        List list;
        int i2;
        int i3;
        Integer num4;
        String str8;
        int i4;
        Integer num5;
        Long l2;
        String str9;
        Integer num6;
        String str10;
        String str11;
        Long l3;
        String str12;
        String str13;
        String str14;
        String str15;
        String str16;
        String str17;
        Long l4;
        String str18;
        String str19;
        String str20;
        Integer num7;
        List list2;
        String str21;
        String str22;
        Integer num8;
        String str23;
        Long l5;
        String str24;
        String str25;
        String str26;
        String str27;
        Long l6;
        String str28;
        Integer num9;
        List list3;
        String str29;
        Integer num10;
        String str30;
        String str31;
        Integer num11;
        Integer num12;
        String str32;
        String str33;
        List list4;
        Integer num13;
        String str34;
        String str35;
        ConvertInfoWS convertInfoWS2;
        Long l7;
        String str36;
        Integer num14;
        List list5;
        String str37;
        Integer num15;
        String str38;
        List list6;
        String str39;
        String str40;
        Integer num16;
        Integer num17;
        int i5;
        String str41;
        String str42;
        Integer num18;
        String str43;
        int i6;
        int i7;
        String str44;
        int i8;
        int i9;
        Intrinsics.checkNotNullParameter(decoder, "");
        SerialDescriptor serialDescriptor = descriptor;
        CompositeDecoder compositeDecoderBeginStructure = decoder.beginStructure(serialDescriptor);
        KSerializer[] kSerializerArr = TxStatusSubResponse.$childSerializers;
        if (compositeDecoderBeginStructure.decodeSequentially()) {
            String strDecodeStringElement = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 0);
            String strDecodeStringElement2 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 1);
            int iDecodeIntElement = compositeDecoderBeginStructure.decodeIntElement(serialDescriptor, 2);
            StringSerializer stringSerializer = StringSerializer.INSTANCE;
            String str45 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 3, stringSerializer, null);
            String strDecodeStringElement3 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 4);
            LongSerializer longSerializer = LongSerializer.INSTANCE;
            Long l8 = (Long) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 5, longSerializer, null);
            int iDecodeIntElement2 = compositeDecoderBeginStructure.decodeIntElement(serialDescriptor, 6);
            String str46 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 7, stringSerializer, null);
            String str47 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 8, stringSerializer, null);
            IntSerializer intSerializer = IntSerializer.INSTANCE;
            Integer num19 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 9, intSerializer, null);
            List list7 = (List) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 10, kSerializerArr[10], null);
            Integer num20 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 11, intSerializer, null);
            str9 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 12, stringSerializer, null);
            int iDecodeIntElement3 = compositeDecoderBeginStructure.decodeIntElement(serialDescriptor, 13);
            String str48 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 14, stringSerializer, null);
            Integer num21 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 15, intSerializer, null);
            String str49 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 16, stringSerializer, null);
            String str50 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 17, stringSerializer, null);
            String str51 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 18, stringSerializer, null);
            String str52 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 19, stringSerializer, null);
            String str53 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 20, stringSerializer, null);
            String str54 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 21, stringSerializer, null);
            Long l9 = (Long) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 22, longSerializer, null);
            Integer num22 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 23, intSerializer, null);
            String str55 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 24, stringSerializer, null);
            Integer num23 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 25, intSerializer, null);
            Long l10 = (Long) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 26, longSerializer, null);
            Integer num24 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 27, intSerializer, null);
            String str56 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 28, stringSerializer, null);
            convertInfoWS = (ConvertInfoWS) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 29, ConvertInfoWS$$serializer.INSTANCE, null);
            num = num24;
            str = str56;
            str8 = strDecodeStringElement2;
            i = 1073741823;
            str13 = strDecodeStringElement;
            l2 = l9;
            num5 = num22;
            str10 = str55;
            num6 = num23;
            l3 = l10;
            str15 = str53;
            str2 = str52;
            str11 = str51;
            str3 = str50;
            num2 = num21;
            str6 = str54;
            l = l8;
            num3 = num19;
            str12 = str46;
            i4 = iDecodeIntElement2;
            str4 = str49;
            str5 = str48;
            list = list7;
            str14 = str45;
            str16 = strDecodeStringElement3;
            str7 = str47;
            i3 = iDecodeIntElement;
            i2 = iDecodeIntElement3;
            num4 = num20;
        } else {
            int i10 = 0;
            int i11 = 0;
            int iDecodeIntElement4 = 0;
            boolean z = true;
            String str57 = null;
            Long l11 = null;
            String str58 = null;
            Integer num25 = null;
            Long l12 = null;
            ConvertInfoWS convertInfoWS3 = null;
            String str59 = null;
            Integer num26 = null;
            String str60 = null;
            String str61 = null;
            String str62 = null;
            String str63 = null;
            String str64 = null;
            String str65 = null;
            Integer num27 = null;
            List list8 = null;
            Integer num28 = null;
            String str66 = null;
            String str67 = null;
            Integer num29 = null;
            String str68 = null;
            Long l13 = null;
            String str69 = null;
            String strDecodeStringElement4 = null;
            String strDecodeStringElement5 = null;
            String strDecodeStringElement6 = null;
            Integer num30 = null;
            int i12 = 0;
            while (z) {
                String str70 = str59;
                int iDecodeElementIndex = compositeDecoderBeginStructure.decodeElementIndex(serialDescriptor);
                switch (iDecodeElementIndex) {
                    case -1:
                        str17 = str57;
                        l4 = l11;
                        str18 = str58;
                        str19 = str64;
                        str20 = str65;
                        num7 = num27;
                        list2 = list8;
                        str21 = str66;
                        str22 = str67;
                        num8 = num29;
                        str23 = str68;
                        l5 = l13;
                        str24 = str69;
                        str25 = str70;
                        Unit unit = Unit.INSTANCE;
                        z = false;
                        String str71 = str25;
                        str26 = str24;
                        l11 = l4;
                        str27 = str23;
                        str59 = str71;
                        str57 = str17;
                        str68 = str27;
                        str69 = str26;
                        str67 = str22;
                        num29 = num8;
                        str66 = str21;
                        str58 = str18;
                        l13 = l5;
                        str64 = str19;
                        str65 = str20;
                        num27 = num7;
                        list8 = list2;
                        break;
                    case 0:
                        str17 = str57;
                        l4 = l11;
                        str18 = str58;
                        str19 = str64;
                        str20 = str65;
                        num7 = num27;
                        list2 = list8;
                        str21 = str66;
                        str22 = str67;
                        num8 = num29;
                        str23 = str68;
                        l5 = l13;
                        str24 = str69;
                        str25 = str70;
                        strDecodeStringElement6 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 0);
                        i12 |= 1;
                        Unit unit2 = Unit.INSTANCE;
                        String str712 = str25;
                        str26 = str24;
                        l11 = l4;
                        str27 = str23;
                        str59 = str712;
                        str57 = str17;
                        str68 = str27;
                        str69 = str26;
                        str67 = str22;
                        num29 = num8;
                        str66 = str21;
                        str58 = str18;
                        l13 = l5;
                        str64 = str19;
                        str65 = str20;
                        num27 = num7;
                        list8 = list2;
                        break;
                    case 1:
                        str17 = str57;
                        l4 = l11;
                        str18 = str58;
                        str19 = str64;
                        str20 = str65;
                        num7 = num27;
                        list2 = list8;
                        str21 = str66;
                        str22 = str67;
                        num8 = num29;
                        str23 = str68;
                        l5 = l13;
                        str24 = str69;
                        str25 = str70;
                        strDecodeStringElement5 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 1);
                        i12 |= 2;
                        Unit unit3 = Unit.INSTANCE;
                        String str7122 = str25;
                        str26 = str24;
                        l11 = l4;
                        str27 = str23;
                        str59 = str7122;
                        str57 = str17;
                        str68 = str27;
                        str69 = str26;
                        str67 = str22;
                        num29 = num8;
                        str66 = str21;
                        str58 = str18;
                        l13 = l5;
                        str64 = str19;
                        str65 = str20;
                        num27 = num7;
                        list8 = list2;
                        break;
                    case 2:
                        str17 = str57;
                        l4 = l11;
                        str18 = str58;
                        str19 = str64;
                        str20 = str65;
                        num7 = num27;
                        list2 = list8;
                        str21 = str66;
                        str22 = str67;
                        num8 = num29;
                        str23 = str68;
                        l5 = l13;
                        str24 = str69;
                        str25 = str70;
                        int iDecodeIntElement5 = compositeDecoderBeginStructure.decodeIntElement(serialDescriptor, 2);
                        i12 |= 4;
                        Unit unit4 = Unit.INSTANCE;
                        i11 = iDecodeIntElement5;
                        String str71222 = str25;
                        str26 = str24;
                        l11 = l4;
                        str27 = str23;
                        str59 = str71222;
                        str57 = str17;
                        str68 = str27;
                        str69 = str26;
                        str67 = str22;
                        num29 = num8;
                        str66 = str21;
                        str58 = str18;
                        l13 = l5;
                        str64 = str19;
                        str65 = str20;
                        num27 = num7;
                        list8 = list2;
                        break;
                    case 3:
                        str17 = str57;
                        l4 = l11;
                        str18 = str58;
                        str19 = str64;
                        str20 = str65;
                        num7 = num27;
                        list2 = list8;
                        str21 = str66;
                        str22 = str67;
                        num8 = num29;
                        str23 = str68;
                        str25 = str70;
                        l5 = l13;
                        String str72 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 3, StringSerializer.INSTANCE, str69);
                        i12 |= 8;
                        Unit unit5 = Unit.INSTANCE;
                        str24 = str72;
                        String str712222 = str25;
                        str26 = str24;
                        l11 = l4;
                        str27 = str23;
                        str59 = str712222;
                        str57 = str17;
                        str68 = str27;
                        str69 = str26;
                        str67 = str22;
                        num29 = num8;
                        str66 = str21;
                        str58 = str18;
                        l13 = l5;
                        str64 = str19;
                        str65 = str20;
                        num27 = num7;
                        list8 = list2;
                        break;
                    case 4:
                        str17 = str57;
                        l6 = l11;
                        str18 = str58;
                        str28 = str64;
                        str20 = str65;
                        num9 = num27;
                        list3 = list8;
                        str21 = str66;
                        str29 = str67;
                        num10 = num29;
                        str30 = str68;
                        str31 = str70;
                        strDecodeStringElement4 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 4);
                        i12 |= 16;
                        Unit unit6 = Unit.INSTANCE;
                        num11 = num10;
                        num12 = num9;
                        str32 = str29;
                        str33 = str63;
                        list4 = list3;
                        Long l14 = l12;
                        num13 = num25;
                        str34 = str28;
                        str35 = str30;
                        convertInfoWS2 = convertInfoWS3;
                        l7 = l14;
                        num7 = num12;
                        list2 = list4;
                        l11 = l6;
                        str63 = str33;
                        str22 = str32;
                        num8 = num11;
                        str27 = str35;
                        l5 = l13;
                        str19 = str34;
                        num25 = num13;
                        l12 = l7;
                        convertInfoWS3 = convertInfoWS2;
                        str59 = str31;
                        str26 = str69;
                        str57 = str17;
                        str68 = str27;
                        str69 = str26;
                        str67 = str22;
                        num29 = num8;
                        str66 = str21;
                        str58 = str18;
                        l13 = l5;
                        str64 = str19;
                        str65 = str20;
                        num27 = num7;
                        list8 = list2;
                        break;
                    case 5:
                        str17 = str57;
                        l6 = l11;
                        str18 = str58;
                        str20 = str65;
                        num9 = num27;
                        list3 = list8;
                        str21 = str66;
                        str29 = str67;
                        num10 = num29;
                        str30 = str68;
                        str31 = str70;
                        str28 = str64;
                        l13 = (Long) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 5, LongSerializer.INSTANCE, l13);
                        Unit unit7 = Unit.INSTANCE;
                        i12 |= 32;
                        num11 = num10;
                        num12 = num9;
                        str32 = str29;
                        str33 = str63;
                        list4 = list3;
                        Long l142 = l12;
                        num13 = num25;
                        str34 = str28;
                        str35 = str30;
                        convertInfoWS2 = convertInfoWS3;
                        l7 = l142;
                        num7 = num12;
                        list2 = list4;
                        l11 = l6;
                        str63 = str33;
                        str22 = str32;
                        num8 = num11;
                        str27 = str35;
                        l5 = l13;
                        str19 = str34;
                        num25 = num13;
                        l12 = l7;
                        convertInfoWS3 = convertInfoWS2;
                        str59 = str31;
                        str26 = str69;
                        str57 = str17;
                        str68 = str27;
                        str69 = str26;
                        str67 = str22;
                        num29 = num8;
                        str66 = str21;
                        str58 = str18;
                        l13 = l5;
                        str64 = str19;
                        str65 = str20;
                        num27 = num7;
                        list8 = list2;
                        break;
                    case 6:
                        str17 = str57;
                        l6 = l11;
                        str18 = str58;
                        str36 = str64;
                        str20 = str65;
                        num14 = num27;
                        list5 = list8;
                        str21 = str66;
                        str37 = str67;
                        num15 = num29;
                        str38 = str68;
                        str31 = str70;
                        iDecodeIntElement4 = compositeDecoderBeginStructure.decodeIntElement(serialDescriptor, 6);
                        i12 |= 64;
                        Unit unit8 = Unit.INSTANCE;
                        str35 = str38;
                        num11 = num15;
                        num12 = num14;
                        convertInfoWS2 = convertInfoWS3;
                        str32 = str37;
                        l7 = l12;
                        str33 = str63;
                        list4 = list5;
                        num13 = num25;
                        str34 = str36;
                        num7 = num12;
                        list2 = list4;
                        l11 = l6;
                        str63 = str33;
                        str22 = str32;
                        num8 = num11;
                        str27 = str35;
                        l5 = l13;
                        str19 = str34;
                        num25 = num13;
                        l12 = l7;
                        convertInfoWS3 = convertInfoWS2;
                        str59 = str31;
                        str26 = str69;
                        str57 = str17;
                        str68 = str27;
                        str69 = str26;
                        str67 = str22;
                        num29 = num8;
                        str66 = str21;
                        str58 = str18;
                        l13 = l5;
                        str64 = str19;
                        str65 = str20;
                        num27 = num7;
                        list8 = list2;
                        break;
                    case 7:
                        str17 = str57;
                        l6 = l11;
                        str18 = str58;
                        num14 = num27;
                        list5 = list8;
                        str21 = str66;
                        str37 = str67;
                        num15 = num29;
                        str38 = str68;
                        str31 = str70;
                        str20 = str65;
                        str36 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 7, StringSerializer.INSTANCE, str64);
                        int i13 = i12 | 128;
                        Unit unit9 = Unit.INSTANCE;
                        i12 = i13;
                        str35 = str38;
                        num11 = num15;
                        num12 = num14;
                        convertInfoWS2 = convertInfoWS3;
                        str32 = str37;
                        l7 = l12;
                        str33 = str63;
                        list4 = list5;
                        num13 = num25;
                        str34 = str36;
                        num7 = num12;
                        list2 = list4;
                        l11 = l6;
                        str63 = str33;
                        str22 = str32;
                        num8 = num11;
                        str27 = str35;
                        l5 = l13;
                        str19 = str34;
                        num25 = num13;
                        l12 = l7;
                        convertInfoWS3 = convertInfoWS2;
                        str59 = str31;
                        str26 = str69;
                        str57 = str17;
                        str68 = str27;
                        str69 = str26;
                        str67 = str22;
                        num29 = num8;
                        str66 = str21;
                        str58 = str18;
                        l13 = l5;
                        str64 = str19;
                        str65 = str20;
                        num27 = num7;
                        list8 = list2;
                        break;
                    case 8:
                        str17 = str57;
                        l6 = l11;
                        str18 = str58;
                        list6 = list8;
                        str21 = str66;
                        str39 = str67;
                        str31 = str70;
                        String str73 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 8, StringSerializer.INSTANCE, str65);
                        int i14 = i12 | 256;
                        Unit unit10 = Unit.INSTANCE;
                        str20 = str73;
                        i12 = i14;
                        str35 = str68;
                        num11 = num29;
                        num12 = num27;
                        convertInfoWS2 = convertInfoWS3;
                        str32 = str39;
                        l7 = l12;
                        str33 = str63;
                        list4 = list6;
                        num13 = num25;
                        str34 = str64;
                        num7 = num12;
                        list2 = list4;
                        l11 = l6;
                        str63 = str33;
                        str22 = str32;
                        num8 = num11;
                        str27 = str35;
                        l5 = l13;
                        str19 = str34;
                        num25 = num13;
                        l12 = l7;
                        convertInfoWS3 = convertInfoWS2;
                        str59 = str31;
                        str26 = str69;
                        str57 = str17;
                        str68 = str27;
                        str69 = str26;
                        str67 = str22;
                        num29 = num8;
                        str66 = str21;
                        str58 = str18;
                        l13 = l5;
                        str64 = str19;
                        str65 = str20;
                        num27 = num7;
                        list8 = list2;
                        break;
                    case 9:
                        str17 = str57;
                        l6 = l11;
                        str18 = str58;
                        str21 = str66;
                        str39 = str67;
                        str31 = str70;
                        list6 = list8;
                        num12 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 9, IntSerializer.INSTANCE, num27);
                        int i15 = i12 | 512;
                        Unit unit11 = Unit.INSTANCE;
                        i12 = i15;
                        str35 = str68;
                        num11 = num29;
                        str20 = str65;
                        convertInfoWS2 = convertInfoWS3;
                        str32 = str39;
                        l7 = l12;
                        str33 = str63;
                        list4 = list6;
                        num13 = num25;
                        str34 = str64;
                        num7 = num12;
                        list2 = list4;
                        l11 = l6;
                        str63 = str33;
                        str22 = str32;
                        num8 = num11;
                        str27 = str35;
                        l5 = l13;
                        str19 = str34;
                        num25 = num13;
                        l12 = l7;
                        convertInfoWS3 = convertInfoWS2;
                        str59 = str31;
                        str26 = str69;
                        str57 = str17;
                        str68 = str27;
                        str69 = str26;
                        str67 = str22;
                        num29 = num8;
                        str66 = str21;
                        str58 = str18;
                        l13 = l5;
                        str64 = str19;
                        str65 = str20;
                        num27 = num7;
                        list8 = list2;
                        break;
                    case 10:
                        str17 = str57;
                        l6 = l11;
                        str18 = str58;
                        str21 = str66;
                        str31 = str70;
                        List list9 = (List) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 10, kSerializerArr[10], list8);
                        int i16 = i12 | 1024;
                        Unit unit12 = Unit.INSTANCE;
                        i12 = i16;
                        str35 = str68;
                        num11 = num29;
                        str20 = str65;
                        num12 = num27;
                        convertInfoWS2 = convertInfoWS3;
                        str32 = str67;
                        l7 = l12;
                        str33 = str63;
                        list4 = list9;
                        num13 = num25;
                        str34 = str64;
                        num7 = num12;
                        list2 = list4;
                        l11 = l6;
                        str63 = str33;
                        str22 = str32;
                        num8 = num11;
                        str27 = str35;
                        l5 = l13;
                        str19 = str34;
                        num25 = num13;
                        l12 = l7;
                        convertInfoWS3 = convertInfoWS2;
                        str59 = str31;
                        str26 = str69;
                        str57 = str17;
                        str68 = str27;
                        str69 = str26;
                        str67 = str22;
                        num29 = num8;
                        str66 = str21;
                        str58 = str18;
                        l13 = l5;
                        str64 = str19;
                        str65 = str20;
                        num27 = num7;
                        list8 = list2;
                        break;
                    case 11:
                        str17 = str57;
                        l6 = l11;
                        str21 = str66;
                        str40 = str67;
                        num16 = num29;
                        str31 = str70;
                        str18 = str58;
                        num17 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 11, IntSerializer.INSTANCE, num28);
                        int i17 = i12 | 2048;
                        Unit unit13 = Unit.INSTANCE;
                        i5 = i17;
                        str41 = str68;
                        num28 = num17;
                        str35 = str41;
                        i12 = i5;
                        num11 = num16;
                        str20 = str65;
                        num12 = num27;
                        convertInfoWS2 = convertInfoWS3;
                        str32 = str40;
                        l7 = l12;
                        str33 = str63;
                        list4 = list8;
                        num13 = num25;
                        str34 = str64;
                        num7 = num12;
                        list2 = list4;
                        l11 = l6;
                        str63 = str33;
                        str22 = str32;
                        num8 = num11;
                        str27 = str35;
                        l5 = l13;
                        str19 = str34;
                        num25 = num13;
                        l12 = l7;
                        convertInfoWS3 = convertInfoWS2;
                        str59 = str31;
                        str26 = str69;
                        str57 = str17;
                        str68 = str27;
                        str69 = str26;
                        str67 = str22;
                        num29 = num8;
                        str66 = str21;
                        str58 = str18;
                        l13 = l5;
                        str64 = str19;
                        str65 = str20;
                        num27 = num7;
                        list8 = list2;
                        break;
                    case 12:
                        str17 = str57;
                        l6 = l11;
                        str40 = str67;
                        num16 = num29;
                        str31 = str70;
                        str21 = str66;
                        String str74 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 12, StringSerializer.INSTANCE, str68);
                        Unit unit14 = Unit.INSTANCE;
                        i5 = i12 | 4096;
                        str18 = str58;
                        num17 = num28;
                        str41 = str74;
                        num28 = num17;
                        str35 = str41;
                        i12 = i5;
                        num11 = num16;
                        str20 = str65;
                        num12 = num27;
                        convertInfoWS2 = convertInfoWS3;
                        str32 = str40;
                        l7 = l12;
                        str33 = str63;
                        list4 = list8;
                        num13 = num25;
                        str34 = str64;
                        num7 = num12;
                        list2 = list4;
                        l11 = l6;
                        str63 = str33;
                        str22 = str32;
                        num8 = num11;
                        str27 = str35;
                        l5 = l13;
                        str19 = str34;
                        num25 = num13;
                        l12 = l7;
                        convertInfoWS3 = convertInfoWS2;
                        str59 = str31;
                        str26 = str69;
                        str57 = str17;
                        str68 = str27;
                        str69 = str26;
                        str67 = str22;
                        num29 = num8;
                        str66 = str21;
                        str58 = str18;
                        l13 = l5;
                        str64 = str19;
                        str65 = str20;
                        num27 = num7;
                        list8 = list2;
                        break;
                    case 13:
                        str17 = str57;
                        l6 = l11;
                        str42 = str67;
                        num18 = num29;
                        str31 = str70;
                        int iDecodeIntElement6 = compositeDecoderBeginStructure.decodeIntElement(serialDescriptor, 13);
                        int i18 = i12 | 8192;
                        Unit unit15 = Unit.INSTANCE;
                        str43 = str66;
                        i6 = iDecodeIntElement6;
                        i7 = i18;
                        i10 = i6;
                        str18 = str58;
                        convertInfoWS2 = convertInfoWS3;
                        str21 = str43;
                        num11 = num18;
                        i12 = i7;
                        str20 = str65;
                        num12 = num27;
                        str35 = str68;
                        l7 = l12;
                        str32 = str42;
                        num13 = num25;
                        str33 = str63;
                        str34 = str64;
                        list4 = list8;
                        num7 = num12;
                        list2 = list4;
                        l11 = l6;
                        str63 = str33;
                        str22 = str32;
                        num8 = num11;
                        str27 = str35;
                        l5 = l13;
                        str19 = str34;
                        num25 = num13;
                        l12 = l7;
                        convertInfoWS3 = convertInfoWS2;
                        str59 = str31;
                        str26 = str69;
                        str57 = str17;
                        str68 = str27;
                        str69 = str26;
                        str67 = str22;
                        num29 = num8;
                        str66 = str21;
                        str58 = str18;
                        l13 = l5;
                        str64 = str19;
                        str65 = str20;
                        num27 = num7;
                        list8 = list2;
                        break;
                    case 14:
                        str17 = str57;
                        l6 = l11;
                        str42 = str67;
                        str31 = str70;
                        num18 = num29;
                        String str75 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 14, StringSerializer.INSTANCE, str66);
                        int i19 = i12 | 16384;
                        Unit unit16 = Unit.INSTANCE;
                        i7 = i19;
                        str43 = str75;
                        i6 = i10;
                        i10 = i6;
                        str18 = str58;
                        convertInfoWS2 = convertInfoWS3;
                        str21 = str43;
                        num11 = num18;
                        i12 = i7;
                        str20 = str65;
                        num12 = num27;
                        str35 = str68;
                        l7 = l12;
                        str32 = str42;
                        num13 = num25;
                        str33 = str63;
                        str34 = str64;
                        list4 = list8;
                        num7 = num12;
                        list2 = list4;
                        l11 = l6;
                        str63 = str33;
                        str22 = str32;
                        num8 = num11;
                        str27 = str35;
                        l5 = l13;
                        str19 = str34;
                        num25 = num13;
                        l12 = l7;
                        convertInfoWS3 = convertInfoWS2;
                        str59 = str31;
                        str26 = str69;
                        str57 = str17;
                        str68 = str27;
                        str69 = str26;
                        str67 = str22;
                        num29 = num8;
                        str66 = str21;
                        str58 = str18;
                        l13 = l5;
                        str64 = str19;
                        str65 = str20;
                        num27 = num7;
                        list8 = list2;
                        break;
                    case 15:
                        str17 = str57;
                        l6 = l11;
                        str31 = str70;
                        Integer num31 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 15, IntSerializer.INSTANCE, num29);
                        Unit unit17 = Unit.INSTANCE;
                        str18 = str58;
                        i12 |= 32768;
                        str32 = str67;
                        str20 = str65;
                        num12 = num27;
                        str21 = str66;
                        num11 = num31;
                        str35 = str68;
                        convertInfoWS2 = convertInfoWS3;
                        str33 = str63;
                        list4 = list8;
                        l7 = l12;
                        num13 = num25;
                        str34 = str64;
                        num7 = num12;
                        list2 = list4;
                        l11 = l6;
                        str63 = str33;
                        str22 = str32;
                        num8 = num11;
                        str27 = str35;
                        l5 = l13;
                        str19 = str34;
                        num25 = num13;
                        l12 = l7;
                        convertInfoWS3 = convertInfoWS2;
                        str59 = str31;
                        str26 = str69;
                        str57 = str17;
                        str68 = str27;
                        str69 = str26;
                        str67 = str22;
                        num29 = num8;
                        str66 = str21;
                        str58 = str18;
                        l13 = l5;
                        str64 = str19;
                        str65 = str20;
                        num27 = num7;
                        list8 = list2;
                        break;
                    case 16:
                        str17 = str57;
                        l6 = l11;
                        str31 = str70;
                        str67 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 16, StringSerializer.INSTANCE, str67);
                        Unit unit18 = Unit.INSTANCE;
                        str18 = str58;
                        i12 |= 65536;
                        str33 = str63;
                        str20 = str65;
                        num12 = num27;
                        list4 = list8;
                        str21 = str66;
                        str32 = str67;
                        num11 = num29;
                        str35 = str68;
                        convertInfoWS2 = convertInfoWS3;
                        l7 = l12;
                        num13 = num25;
                        str34 = str64;
                        num7 = num12;
                        list2 = list4;
                        l11 = l6;
                        str63 = str33;
                        str22 = str32;
                        num8 = num11;
                        str27 = str35;
                        l5 = l13;
                        str19 = str34;
                        num25 = num13;
                        l12 = l7;
                        convertInfoWS3 = convertInfoWS2;
                        str59 = str31;
                        str26 = str69;
                        str57 = str17;
                        str68 = str27;
                        str69 = str26;
                        str67 = str22;
                        num29 = num8;
                        str66 = str21;
                        str58 = str18;
                        l13 = l5;
                        str64 = str19;
                        str65 = str20;
                        num27 = num7;
                        list8 = list2;
                        break;
                    case 17:
                        str17 = str57;
                        l6 = l11;
                        String str76 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 17, StringSerializer.INSTANCE, str70);
                        int i20 = 131072 | i12;
                        Unit unit19 = Unit.INSTANCE;
                        i12 = i20;
                        str18 = str58;
                        str31 = str76;
                        str33 = str63;
                        str20 = str65;
                        num12 = num27;
                        list4 = list8;
                        str21 = str66;
                        str32 = str67;
                        num11 = num29;
                        str35 = str68;
                        convertInfoWS2 = convertInfoWS3;
                        l7 = l12;
                        num13 = num25;
                        str34 = str64;
                        num7 = num12;
                        list2 = list4;
                        l11 = l6;
                        str63 = str33;
                        str22 = str32;
                        num8 = num11;
                        str27 = str35;
                        l5 = l13;
                        str19 = str34;
                        num25 = num13;
                        l12 = l7;
                        convertInfoWS3 = convertInfoWS2;
                        str59 = str31;
                        str26 = str69;
                        str57 = str17;
                        str68 = str27;
                        str69 = str26;
                        str67 = str22;
                        num29 = num8;
                        str66 = str21;
                        str58 = str18;
                        l13 = l5;
                        str64 = str19;
                        str65 = str20;
                        num27 = num7;
                        list8 = list2;
                        break;
                    case 18:
                        str17 = str57;
                        str62 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 18, StringSerializer.INSTANCE, str62);
                        int i21 = 262144 | i12;
                        Unit unit20 = Unit.INSTANCE;
                        l6 = l11;
                        str18 = str58;
                        i12 = i21;
                        str33 = str63;
                        str20 = str65;
                        num12 = num27;
                        list4 = list8;
                        str21 = str66;
                        str32 = str67;
                        num11 = num29;
                        str35 = str68;
                        str31 = str70;
                        convertInfoWS2 = convertInfoWS3;
                        l7 = l12;
                        num13 = num25;
                        str34 = str64;
                        num7 = num12;
                        list2 = list4;
                        l11 = l6;
                        str63 = str33;
                        str22 = str32;
                        num8 = num11;
                        str27 = str35;
                        l5 = l13;
                        str19 = str34;
                        num25 = num13;
                        l12 = l7;
                        convertInfoWS3 = convertInfoWS2;
                        str59 = str31;
                        str26 = str69;
                        str57 = str17;
                        str68 = str27;
                        str69 = str26;
                        str67 = str22;
                        num29 = num8;
                        str66 = str21;
                        str58 = str18;
                        l13 = l5;
                        str64 = str19;
                        str65 = str20;
                        num27 = num7;
                        list8 = list2;
                        break;
                    case 19:
                        str44 = str62;
                        str57 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 19, StringSerializer.INSTANCE, str57);
                        i8 = 524288 | i12;
                        Unit unit21 = Unit.INSTANCE;
                        str17 = str57;
                        l6 = l11;
                        str18 = str58;
                        i12 = i8;
                        str33 = str63;
                        str20 = str65;
                        num12 = num27;
                        list4 = list8;
                        str21 = str66;
                        str32 = str67;
                        num11 = num29;
                        str35 = str68;
                        str31 = str70;
                        str62 = str44;
                        convertInfoWS2 = convertInfoWS3;
                        l7 = l12;
                        num13 = num25;
                        str34 = str64;
                        num7 = num12;
                        list2 = list4;
                        l11 = l6;
                        str63 = str33;
                        str22 = str32;
                        num8 = num11;
                        str27 = str35;
                        l5 = l13;
                        str19 = str34;
                        num25 = num13;
                        l12 = l7;
                        convertInfoWS3 = convertInfoWS2;
                        str59 = str31;
                        str26 = str69;
                        str57 = str17;
                        str68 = str27;
                        str69 = str26;
                        str67 = str22;
                        num29 = num8;
                        str66 = str21;
                        str58 = str18;
                        l13 = l5;
                        str64 = str19;
                        str65 = str20;
                        num27 = num7;
                        list8 = list2;
                        break;
                    case 20:
                        str44 = str62;
                        str63 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 20, StringSerializer.INSTANCE, str63);
                        i9 = 1048576;
                        i8 = i9 | i12;
                        Unit unit22 = Unit.INSTANCE;
                        str17 = str57;
                        l6 = l11;
                        str18 = str58;
                        i12 = i8;
                        str33 = str63;
                        str20 = str65;
                        num12 = num27;
                        list4 = list8;
                        str21 = str66;
                        str32 = str67;
                        num11 = num29;
                        str35 = str68;
                        str31 = str70;
                        str62 = str44;
                        convertInfoWS2 = convertInfoWS3;
                        l7 = l12;
                        num13 = num25;
                        str34 = str64;
                        num7 = num12;
                        list2 = list4;
                        l11 = l6;
                        str63 = str33;
                        str22 = str32;
                        num8 = num11;
                        str27 = str35;
                        l5 = l13;
                        str19 = str34;
                        num25 = num13;
                        l12 = l7;
                        convertInfoWS3 = convertInfoWS2;
                        str59 = str31;
                        str26 = str69;
                        str57 = str17;
                        str68 = str27;
                        str69 = str26;
                        str67 = str22;
                        num29 = num8;
                        str66 = str21;
                        str58 = str18;
                        l13 = l5;
                        str64 = str19;
                        str65 = str20;
                        num27 = num7;
                        list8 = list2;
                        break;
                    case 21:
                        str44 = str62;
                        str58 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 21, StringSerializer.INSTANCE, str58);
                        i9 = 2097152;
                        i8 = i9 | i12;
                        Unit unit222 = Unit.INSTANCE;
                        str17 = str57;
                        l6 = l11;
                        str18 = str58;
                        i12 = i8;
                        str33 = str63;
                        str20 = str65;
                        num12 = num27;
                        list4 = list8;
                        str21 = str66;
                        str32 = str67;
                        num11 = num29;
                        str35 = str68;
                        str31 = str70;
                        str62 = str44;
                        convertInfoWS2 = convertInfoWS3;
                        l7 = l12;
                        num13 = num25;
                        str34 = str64;
                        num7 = num12;
                        list2 = list4;
                        l11 = l6;
                        str63 = str33;
                        str22 = str32;
                        num8 = num11;
                        str27 = str35;
                        l5 = l13;
                        str19 = str34;
                        num25 = num13;
                        l12 = l7;
                        convertInfoWS3 = convertInfoWS2;
                        str59 = str31;
                        str26 = str69;
                        str57 = str17;
                        str68 = str27;
                        str69 = str26;
                        str67 = str22;
                        num29 = num8;
                        str66 = str21;
                        str58 = str18;
                        l13 = l5;
                        str64 = str19;
                        str65 = str20;
                        num27 = num7;
                        list8 = list2;
                        break;
                    case 22:
                        str44 = str62;
                        l12 = (Long) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 22, LongSerializer.INSTANCE, l12);
                        i9 = 4194304;
                        i8 = i9 | i12;
                        Unit unit2222 = Unit.INSTANCE;
                        str17 = str57;
                        l6 = l11;
                        str18 = str58;
                        i12 = i8;
                        str33 = str63;
                        str20 = str65;
                        num12 = num27;
                        list4 = list8;
                        str21 = str66;
                        str32 = str67;
                        num11 = num29;
                        str35 = str68;
                        str31 = str70;
                        str62 = str44;
                        convertInfoWS2 = convertInfoWS3;
                        l7 = l12;
                        num13 = num25;
                        str34 = str64;
                        num7 = num12;
                        list2 = list4;
                        l11 = l6;
                        str63 = str33;
                        str22 = str32;
                        num8 = num11;
                        str27 = str35;
                        l5 = l13;
                        str19 = str34;
                        num25 = num13;
                        l12 = l7;
                        convertInfoWS3 = convertInfoWS2;
                        str59 = str31;
                        str26 = str69;
                        str57 = str17;
                        str68 = str27;
                        str69 = str26;
                        str67 = str22;
                        num29 = num8;
                        str66 = str21;
                        str58 = str18;
                        l13 = l5;
                        str64 = str19;
                        str65 = str20;
                        num27 = num7;
                        list8 = list2;
                        break;
                    case 23:
                        str44 = str62;
                        num25 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 23, IntSerializer.INSTANCE, num25);
                        i9 = 8388608;
                        i8 = i9 | i12;
                        Unit unit22222 = Unit.INSTANCE;
                        str17 = str57;
                        l6 = l11;
                        str18 = str58;
                        i12 = i8;
                        str33 = str63;
                        str20 = str65;
                        num12 = num27;
                        list4 = list8;
                        str21 = str66;
                        str32 = str67;
                        num11 = num29;
                        str35 = str68;
                        str31 = str70;
                        str62 = str44;
                        convertInfoWS2 = convertInfoWS3;
                        l7 = l12;
                        num13 = num25;
                        str34 = str64;
                        num7 = num12;
                        list2 = list4;
                        l11 = l6;
                        str63 = str33;
                        str22 = str32;
                        num8 = num11;
                        str27 = str35;
                        l5 = l13;
                        str19 = str34;
                        num25 = num13;
                        l12 = l7;
                        convertInfoWS3 = convertInfoWS2;
                        str59 = str31;
                        str26 = str69;
                        str57 = str17;
                        str68 = str27;
                        str69 = str26;
                        str67 = str22;
                        num29 = num8;
                        str66 = str21;
                        str58 = str18;
                        l13 = l5;
                        str64 = str19;
                        str65 = str20;
                        num27 = num7;
                        list8 = list2;
                        break;
                    case 24:
                        str44 = str62;
                        str60 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 24, StringSerializer.INSTANCE, str60);
                        i9 = 16777216;
                        i8 = i9 | i12;
                        Unit unit222222 = Unit.INSTANCE;
                        str17 = str57;
                        l6 = l11;
                        str18 = str58;
                        i12 = i8;
                        str33 = str63;
                        str20 = str65;
                        num12 = num27;
                        list4 = list8;
                        str21 = str66;
                        str32 = str67;
                        num11 = num29;
                        str35 = str68;
                        str31 = str70;
                        str62 = str44;
                        convertInfoWS2 = convertInfoWS3;
                        l7 = l12;
                        num13 = num25;
                        str34 = str64;
                        num7 = num12;
                        list2 = list4;
                        l11 = l6;
                        str63 = str33;
                        str22 = str32;
                        num8 = num11;
                        str27 = str35;
                        l5 = l13;
                        str19 = str34;
                        num25 = num13;
                        l12 = l7;
                        convertInfoWS3 = convertInfoWS2;
                        str59 = str31;
                        str26 = str69;
                        str57 = str17;
                        str68 = str27;
                        str69 = str26;
                        str67 = str22;
                        num29 = num8;
                        str66 = str21;
                        str58 = str18;
                        l13 = l5;
                        str64 = str19;
                        str65 = str20;
                        num27 = num7;
                        list8 = list2;
                        break;
                    case 25:
                        str44 = str62;
                        num26 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 25, IntSerializer.INSTANCE, num26);
                        i9 = MediaHttpDownloader.MAXIMUM_CHUNK_SIZE;
                        i8 = i9 | i12;
                        Unit unit2222222 = Unit.INSTANCE;
                        str17 = str57;
                        l6 = l11;
                        str18 = str58;
                        i12 = i8;
                        str33 = str63;
                        str20 = str65;
                        num12 = num27;
                        list4 = list8;
                        str21 = str66;
                        str32 = str67;
                        num11 = num29;
                        str35 = str68;
                        str31 = str70;
                        str62 = str44;
                        convertInfoWS2 = convertInfoWS3;
                        l7 = l12;
                        num13 = num25;
                        str34 = str64;
                        num7 = num12;
                        list2 = list4;
                        l11 = l6;
                        str63 = str33;
                        str22 = str32;
                        num8 = num11;
                        str27 = str35;
                        l5 = l13;
                        str19 = str34;
                        num25 = num13;
                        l12 = l7;
                        convertInfoWS3 = convertInfoWS2;
                        str59 = str31;
                        str26 = str69;
                        str57 = str17;
                        str68 = str27;
                        str69 = str26;
                        str67 = str22;
                        num29 = num8;
                        str66 = str21;
                        str58 = str18;
                        l13 = l5;
                        str64 = str19;
                        str65 = str20;
                        num27 = num7;
                        list8 = list2;
                        break;
                    case 26:
                        str44 = str62;
                        l11 = (Long) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 26, LongSerializer.INSTANCE, l11);
                        i9 = 67108864;
                        i8 = i9 | i12;
                        Unit unit22222222 = Unit.INSTANCE;
                        str17 = str57;
                        l6 = l11;
                        str18 = str58;
                        i12 = i8;
                        str33 = str63;
                        str20 = str65;
                        num12 = num27;
                        list4 = list8;
                        str21 = str66;
                        str32 = str67;
                        num11 = num29;
                        str35 = str68;
                        str31 = str70;
                        str62 = str44;
                        convertInfoWS2 = convertInfoWS3;
                        l7 = l12;
                        num13 = num25;
                        str34 = str64;
                        num7 = num12;
                        list2 = list4;
                        l11 = l6;
                        str63 = str33;
                        str22 = str32;
                        num8 = num11;
                        str27 = str35;
                        l5 = l13;
                        str19 = str34;
                        num25 = num13;
                        l12 = l7;
                        convertInfoWS3 = convertInfoWS2;
                        str59 = str31;
                        str26 = str69;
                        str57 = str17;
                        str68 = str27;
                        str69 = str26;
                        str67 = str22;
                        num29 = num8;
                        str66 = str21;
                        str58 = str18;
                        l13 = l5;
                        str64 = str19;
                        str65 = str20;
                        num27 = num7;
                        list8 = list2;
                        break;
                    case 27:
                        str44 = str62;
                        num30 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 27, IntSerializer.INSTANCE, num30);
                        i9 = 134217728;
                        i8 = i9 | i12;
                        Unit unit222222222 = Unit.INSTANCE;
                        str17 = str57;
                        l6 = l11;
                        str18 = str58;
                        i12 = i8;
                        str33 = str63;
                        str20 = str65;
                        num12 = num27;
                        list4 = list8;
                        str21 = str66;
                        str32 = str67;
                        num11 = num29;
                        str35 = str68;
                        str31 = str70;
                        str62 = str44;
                        convertInfoWS2 = convertInfoWS3;
                        l7 = l12;
                        num13 = num25;
                        str34 = str64;
                        num7 = num12;
                        list2 = list4;
                        l11 = l6;
                        str63 = str33;
                        str22 = str32;
                        num8 = num11;
                        str27 = str35;
                        l5 = l13;
                        str19 = str34;
                        num25 = num13;
                        l12 = l7;
                        convertInfoWS3 = convertInfoWS2;
                        str59 = str31;
                        str26 = str69;
                        str57 = str17;
                        str68 = str27;
                        str69 = str26;
                        str67 = str22;
                        num29 = num8;
                        str66 = str21;
                        str58 = str18;
                        l13 = l5;
                        str64 = str19;
                        str65 = str20;
                        num27 = num7;
                        list8 = list2;
                        break;
                    case 28:
                        str44 = str62;
                        str61 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 28, StringSerializer.INSTANCE, str61);
                        i9 = 268435456;
                        i8 = i9 | i12;
                        Unit unit2222222222 = Unit.INSTANCE;
                        str17 = str57;
                        l6 = l11;
                        str18 = str58;
                        i12 = i8;
                        str33 = str63;
                        str20 = str65;
                        num12 = num27;
                        list4 = list8;
                        str21 = str66;
                        str32 = str67;
                        num11 = num29;
                        str35 = str68;
                        str31 = str70;
                        str62 = str44;
                        convertInfoWS2 = convertInfoWS3;
                        l7 = l12;
                        num13 = num25;
                        str34 = str64;
                        num7 = num12;
                        list2 = list4;
                        l11 = l6;
                        str63 = str33;
                        str22 = str32;
                        num8 = num11;
                        str27 = str35;
                        l5 = l13;
                        str19 = str34;
                        num25 = num13;
                        l12 = l7;
                        convertInfoWS3 = convertInfoWS2;
                        str59 = str31;
                        str26 = str69;
                        str57 = str17;
                        str68 = str27;
                        str69 = str26;
                        str67 = str22;
                        num29 = num8;
                        str66 = str21;
                        str58 = str18;
                        l13 = l5;
                        str64 = str19;
                        str65 = str20;
                        num27 = num7;
                        list8 = list2;
                        break;
                    case 29:
                        str44 = str62;
                        convertInfoWS3 = (ConvertInfoWS) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 29, ConvertInfoWS$$serializer.INSTANCE, convertInfoWS3);
                        i9 = 536870912;
                        i8 = i9 | i12;
                        Unit unit22222222222 = Unit.INSTANCE;
                        str17 = str57;
                        l6 = l11;
                        str18 = str58;
                        i12 = i8;
                        str33 = str63;
                        str20 = str65;
                        num12 = num27;
                        list4 = list8;
                        str21 = str66;
                        str32 = str67;
                        num11 = num29;
                        str35 = str68;
                        str31 = str70;
                        str62 = str44;
                        convertInfoWS2 = convertInfoWS3;
                        l7 = l12;
                        num13 = num25;
                        str34 = str64;
                        num7 = num12;
                        list2 = list4;
                        l11 = l6;
                        str63 = str33;
                        str22 = str32;
                        num8 = num11;
                        str27 = str35;
                        l5 = l13;
                        str19 = str34;
                        num25 = num13;
                        l12 = l7;
                        convertInfoWS3 = convertInfoWS2;
                        str59 = str31;
                        str26 = str69;
                        str57 = str17;
                        str68 = str27;
                        str69 = str26;
                        str67 = str22;
                        num29 = num8;
                        str66 = str21;
                        str58 = str18;
                        l13 = l5;
                        str64 = str19;
                        str65 = str20;
                        num27 = num7;
                        list8 = list2;
                        break;
                    default:
                        throw new UnknownFieldException(iDecodeElementIndex);
                }
            }
            String str77 = str64;
            String str78 = str65;
            Integer num32 = num27;
            convertInfoWS = convertInfoWS3;
            num = num30;
            i = i12;
            str = str61;
            str2 = str57;
            str3 = str59;
            str4 = str67;
            num2 = num29;
            str5 = str66;
            str6 = str58;
            l = l13;
            str7 = str78;
            num3 = num32;
            list = list8;
            i2 = i10;
            i3 = i11;
            num4 = num28;
            str8 = strDecodeStringElement5;
            i4 = iDecodeIntElement4;
            num5 = num25;
            l2 = l12;
            str9 = str68;
            num6 = num26;
            str10 = str60;
            str11 = str62;
            l3 = l11;
            str12 = str77;
            str13 = strDecodeStringElement6;
            str14 = str69;
            str15 = str63;
            str16 = strDecodeStringElement4;
        }
        compositeDecoderBeginStructure.endStructure(serialDescriptor);
        return new TxStatusSubResponse(i, str13, str8, i3, str14, str16, l, i4, str12, str7, num3, list, num4, str9, i2, str5, num2, str4, str3, str11, str2, str15, str6, l2, num5, str10, num6, l3, num, str, convertInfoWS, (SerializationConstructorMarker) null);
    }

    /* JADX DEBUG: Method merged with bridge method: serialize(Lkotlinx/serialization/encoding/Encoder;Ljava/lang/Object;)V */
    @Override // kotlinx.serialization.SerializationStrategy
    public final void serialize(@NotNull Encoder encoder, @NotNull TxStatusSubResponse txStatusSubResponse) {
        Intrinsics.checkNotNullParameter(encoder, "");
        Intrinsics.checkNotNullParameter(txStatusSubResponse, "");
        SerialDescriptor serialDescriptor = descriptor;
        CompositeEncoder compositeEncoderBeginStructure = encoder.beginStructure(serialDescriptor);
        TxStatusSubResponse.write$Self$OKWallet_wallet_impl(txStatusSubResponse, compositeEncoderBeginStructure, serialDescriptor);
        compositeEncoderBeginStructure.endStructure(serialDescriptor);
    }
}
