package com.okinc.unify_trade.biz.subscribe;

import com.google.api.client.googleapis.media.MediaHttpDownloader;
import com.okinc.unify_trade.biz.AssetsRubikIncome;
import com.okinc.unify_trade.biz.AssetsRubikIncome$$serializer;
import kotlin.Unit;
import kotlin.jvm.internal.Intrinsics;
import kotlinx.serialization.KSerializer;
import kotlinx.serialization.UnknownFieldException;
import kotlinx.serialization.builtins.BuiltinSerializersKt;
import kotlinx.serialization.descriptors.SerialDescriptor;
import kotlinx.serialization.encoding.CompositeDecoder;
import kotlinx.serialization.encoding.CompositeEncoder;
import kotlinx.serialization.encoding.Decoder;
import kotlinx.serialization.encoding.Encoder;
import kotlinx.serialization.internal.BooleanSerializer;
import kotlinx.serialization.internal.GeneratedSerializer;
import kotlinx.serialization.internal.PluginGeneratedSerialDescriptor;
import kotlinx.serialization.internal.SerializationConstructorMarker;
import kotlinx.serialization.internal.StringSerializer;
import org.jetbrains.annotations.NotNull;

/* JADX INFO: loaded from: classes12.dex */
public final /* synthetic */ class AccountDetailData$$serializer implements GeneratedSerializer<AccountDetailData> {
    public static final int $stable;
    public static final AccountDetailData$$serializer INSTANCE;
    private static final SerialDescriptor descriptor;

    /* JADX DEBUG: Don't trust debug lines info. Lines numbers was adjusted: min line is 0 */
    private AccountDetailData$$serializer() {
    }

    /* JADX DEBUG: Don't trust debug lines info. Lines numbers was adjusted: min line is 0 */
    @Override // kotlinx.serialization.KSerializer, kotlinx.serialization.SerializationStrategy, kotlinx.serialization.DeserializationStrategy
    public final SerialDescriptor getDescriptor() {
        return descriptor;
    }

    static {
        AccountDetailData$$serializer accountDetailData$$serializer = new AccountDetailData$$serializer();
        INSTANCE = accountDetailData$$serializer;
        $stable = 8;
        PluginGeneratedSerialDescriptor pluginGeneratedSerialDescriptor = new PluginGeneratedSerialDescriptor("com.okinc.unify_trade.biz.subscribe.AccountDetailData", accountDetailData$$serializer, 63);
        pluginGeneratedSerialDescriptor.addElement("ccy", true);
        pluginGeneratedSerialDescriptor.addElement("eq", true);
        pluginGeneratedSerialDescriptor.addElement("isoEq", true);
        pluginGeneratedSerialDescriptor.addElement("availEq", true);
        pluginGeneratedSerialDescriptor.addElement("availBal", true);
        pluginGeneratedSerialDescriptor.addElement("frozenBal", true);
        pluginGeneratedSerialDescriptor.addElement("liab", true);
        pluginGeneratedSerialDescriptor.addElement("upl", true);
        pluginGeneratedSerialDescriptor.addElement("mgnRatio", true);
        pluginGeneratedSerialDescriptor.addElement("interest", true);
        pluginGeneratedSerialDescriptor.addElement("crossLiab", true);
        pluginGeneratedSerialDescriptor.addElement("isoLiab", true);
        pluginGeneratedSerialDescriptor.addElement("twap", true);
        pluginGeneratedSerialDescriptor.addElement("frpType", true);
        pluginGeneratedSerialDescriptor.addElement("notionalLever", true);
        pluginGeneratedSerialDescriptor.addElement("cashBal", true);
        pluginGeneratedSerialDescriptor.addElement("uTime", true);
        pluginGeneratedSerialDescriptor.addElement("disEq", true);
        pluginGeneratedSerialDescriptor.addElement("ordFrozen", true);
        pluginGeneratedSerialDescriptor.addElement("maxLoan", true);
        pluginGeneratedSerialDescriptor.addElement("eqUsd", true);
        pluginGeneratedSerialDescriptor.addElement("stgyEq", true);
        pluginGeneratedSerialDescriptor.addElement("isoUpl", true);
        pluginGeneratedSerialDescriptor.addElement("assetsRubikIncome", true);
        pluginGeneratedSerialDescriptor.addElement("coinFullName", true);
        pluginGeneratedSerialDescriptor.addElement("fixedBal", true);
        pluginGeneratedSerialDescriptor.addElement("spotInUseAmt", true);
        pluginGeneratedSerialDescriptor.addElement("borrowFroz", true);
        pluginGeneratedSerialDescriptor.addElement("coinUsdPrice", true);
        pluginGeneratedSerialDescriptor.addElement("spotIsoBal", true);
        pluginGeneratedSerialDescriptor.addElement("spotCopyTradingEq", true);
        pluginGeneratedSerialDescriptor.addElement("smtSyncEq", true);
        pluginGeneratedSerialDescriptor.addElement("rewardBal", true);
        pluginGeneratedSerialDescriptor.addElement("spotBal", true);
        pluginGeneratedSerialDescriptor.addElement("openAvgPx", true);
        pluginGeneratedSerialDescriptor.addElement("accAvgPx", true);
        pluginGeneratedSerialDescriptor.addElement("spotUpl", true);
        pluginGeneratedSerialDescriptor.addElement("spotUplRatio", true);
        pluginGeneratedSerialDescriptor.addElement("totalPnl", true);
        pluginGeneratedSerialDescriptor.addElement("totalPnlRatio", true);
        pluginGeneratedSerialDescriptor.addElement("yearRates", true);
        pluginGeneratedSerialDescriptor.addElement("coinRealBorrowAmt", true);
        pluginGeneratedSerialDescriptor.addElement("coinLeverage", true);
        pluginGeneratedSerialDescriptor.addElement("coinBorrowFrozenMargin", true);
        pluginGeneratedSerialDescriptor.addElement("leverageBorrowLimit", true);
        pluginGeneratedSerialDescriptor.addElement("masterAccountLimit", true);
        pluginGeneratedSerialDescriptor.addElement("colBorrAutoConversion", true);
        pluginGeneratedSerialDescriptor.addElement("supportAutoLend", true);
        pluginGeneratedSerialDescriptor.addElement("supportAutoEarn", true);
        pluginGeneratedSerialDescriptor.addElement("autoEarnEnabled", true);
        pluginGeneratedSerialDescriptor.addElement("autoLendMtAmt", true);
        pluginGeneratedSerialDescriptor.addElement("autoLendStatus", true);
        pluginGeneratedSerialDescriptor.addElement("autoLendApr", true);
        pluginGeneratedSerialDescriptor.addElement("autoLendAmt", true);
        pluginGeneratedSerialDescriptor.addElement("supportAutoStaking", true);
        pluginGeneratedSerialDescriptor.addElement("autoStakingStatus", true);
        pluginGeneratedSerialDescriptor.addElement("stakingApr", true);
        pluginGeneratedSerialDescriptor.addElement("stakeDistribFreq", true);
        pluginGeneratedSerialDescriptor.addElement("colRes", true);
        pluginGeneratedSerialDescriptor.addElement("freeInterest", true);
        pluginGeneratedSerialDescriptor.addElement("liabConversionHistory", true);
        pluginGeneratedSerialDescriptor.addElement("hourRates", true);
        pluginGeneratedSerialDescriptor.addElement("rateType", true);
        descriptor = pluginGeneratedSerialDescriptor;
    }

    @Override // kotlinx.serialization.internal.GeneratedSerializer
    public final KSerializer<?>[] childSerializers() {
        StringSerializer stringSerializer = StringSerializer.INSTANCE;
        BooleanSerializer booleanSerializer = BooleanSerializer.INSTANCE;
        return new KSerializer[]{stringSerializer, stringSerializer, stringSerializer, stringSerializer, stringSerializer, stringSerializer, stringSerializer, stringSerializer, stringSerializer, stringSerializer, stringSerializer, stringSerializer, stringSerializer, stringSerializer, stringSerializer, stringSerializer, stringSerializer, stringSerializer, stringSerializer, stringSerializer, stringSerializer, stringSerializer, stringSerializer, BuiltinSerializersKt.getNullable(AssetsRubikIncome$$serializer.INSTANCE), stringSerializer, stringSerializer, stringSerializer, stringSerializer, stringSerializer, stringSerializer, stringSerializer, stringSerializer, stringSerializer, stringSerializer, stringSerializer, stringSerializer, stringSerializer, stringSerializer, stringSerializer, stringSerializer, stringSerializer, stringSerializer, stringSerializer, stringSerializer, stringSerializer, stringSerializer, BuiltinSerializersKt.getNullable(stringSerializer), booleanSerializer, booleanSerializer, booleanSerializer, BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(booleanSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), stringSerializer, stringSerializer, stringSerializer, stringSerializer, stringSerializer};
    }

    /* JADX DEBUG: Method merged with bridge method: deserialize(Lkotlinx/serialization/encoding/Decoder;)Ljava/lang/Object; */
    @Override // kotlinx.serialization.DeserializationStrategy
    public final AccountDetailData deserialize(@NotNull Decoder decoder) {
        int i;
        int i2;
        String str;
        String str2;
        String str3;
        String str4;
        String str5;
        String str6;
        String str7;
        String str8;
        String str9;
        String str10;
        String str11;
        String str12;
        String str13;
        String str14;
        String str15;
        String str16;
        String str17;
        String str18;
        String str19;
        String str20;
        String str21;
        String str22;
        String str23;
        String str24;
        boolean z;
        boolean z2;
        String str25;
        Boolean bool;
        String str26;
        String str27;
        String str28;
        String str29;
        boolean z3;
        String str30;
        String str31;
        String str32;
        String str33;
        String str34;
        String str35;
        String str36;
        String str37;
        String str38;
        String str39;
        String strDecodeStringElement;
        String str40;
        String str41;
        String str42;
        String str43;
        String str44;
        String str45;
        String str46;
        AssetsRubikIncome assetsRubikIncome;
        String str47;
        String str48;
        String str49;
        String str50;
        String str51;
        String str52;
        String str53;
        String str54;
        String str55;
        String str56;
        String str57;
        boolean z4;
        int i3;
        boolean zDecodeBooleanElement;
        int i4;
        int i5;
        int i6;
        int i7;
        int i8;
        int i9;
        Intrinsics.checkNotNullParameter(decoder, "");
        SerialDescriptor serialDescriptor = descriptor;
        CompositeDecoder compositeDecoderBeginStructure = decoder.beginStructure(serialDescriptor);
        if (compositeDecoderBeginStructure.decodeSequentially()) {
            String strDecodeStringElement2 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 0);
            String strDecodeStringElement3 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 1);
            String strDecodeStringElement4 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 2);
            String strDecodeStringElement5 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 3);
            String strDecodeStringElement6 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 4);
            String strDecodeStringElement7 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 5);
            String strDecodeStringElement8 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 6);
            String strDecodeStringElement9 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 7);
            String strDecodeStringElement10 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 8);
            String strDecodeStringElement11 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 9);
            String strDecodeStringElement12 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 10);
            String strDecodeStringElement13 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 11);
            String strDecodeStringElement14 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 12);
            String strDecodeStringElement15 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 13);
            String strDecodeStringElement16 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 14);
            String strDecodeStringElement17 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 15);
            String strDecodeStringElement18 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 16);
            String strDecodeStringElement19 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 17);
            String strDecodeStringElement20 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 18);
            String strDecodeStringElement21 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 19);
            String strDecodeStringElement22 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 20);
            String strDecodeStringElement23 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 21);
            String strDecodeStringElement24 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 22);
            AssetsRubikIncome assetsRubikIncome2 = (AssetsRubikIncome) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 23, AssetsRubikIncome$$serializer.INSTANCE, null);
            String strDecodeStringElement25 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 24);
            String strDecodeStringElement26 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 25);
            String strDecodeStringElement27 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 26);
            String strDecodeStringElement28 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 27);
            String strDecodeStringElement29 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 28);
            String strDecodeStringElement30 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 29);
            String strDecodeStringElement31 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 30);
            String strDecodeStringElement32 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 31);
            String strDecodeStringElement33 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 32);
            String strDecodeStringElement34 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 33);
            String strDecodeStringElement35 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 34);
            String strDecodeStringElement36 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 35);
            String strDecodeStringElement37 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 36);
            String strDecodeStringElement38 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 37);
            String strDecodeStringElement39 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 38);
            String strDecodeStringElement40 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 39);
            String strDecodeStringElement41 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 40);
            String strDecodeStringElement42 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 41);
            String strDecodeStringElement43 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 42);
            String strDecodeStringElement44 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 43);
            String strDecodeStringElement45 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 44);
            String strDecodeStringElement46 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 45);
            StringSerializer stringSerializer = StringSerializer.INSTANCE;
            String str58 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 46, stringSerializer, null);
            boolean zDecodeBooleanElement2 = compositeDecoderBeginStructure.decodeBooleanElement(serialDescriptor, 47);
            boolean zDecodeBooleanElement3 = compositeDecoderBeginStructure.decodeBooleanElement(serialDescriptor, 48);
            boolean zDecodeBooleanElement4 = compositeDecoderBeginStructure.decodeBooleanElement(serialDescriptor, 49);
            String str59 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 50, stringSerializer, null);
            String str60 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 51, stringSerializer, null);
            String str61 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 52, stringSerializer, null);
            String str62 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 53, stringSerializer, null);
            Boolean bool2 = (Boolean) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 54, BooleanSerializer.INSTANCE, null);
            String str63 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 55, stringSerializer, null);
            String str64 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 56, stringSerializer, null);
            String str65 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 57, stringSerializer, null);
            String strDecodeStringElement47 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 58);
            String strDecodeStringElement48 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 59);
            String strDecodeStringElement49 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 60);
            String strDecodeStringElement50 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 61);
            strDecodeStringElement = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 62);
            str32 = strDecodeStringElement47;
            str37 = str63;
            str31 = strDecodeStringElement48;
            bool = bool2;
            str43 = str64;
            str25 = str65;
            str30 = strDecodeStringElement49;
            str45 = strDecodeStringElement50;
            z3 = zDecodeBooleanElement2;
            str44 = str59;
            z = zDecodeBooleanElement3;
            z2 = zDecodeBooleanElement4;
            str28 = str60;
            str34 = strDecodeStringElement14;
            str35 = strDecodeStringElement5;
            str57 = strDecodeStringElement41;
            str56 = strDecodeStringElement42;
            str52 = strDecodeStringElement44;
            str6 = strDecodeStringElement33;
            str19 = strDecodeStringElement17;
            str5 = strDecodeStringElement32;
            str15 = strDecodeStringElement35;
            str23 = strDecodeStringElement7;
            str38 = strDecodeStringElement26;
            str14 = strDecodeStringElement10;
            assetsRubikIncome = assetsRubikIncome2;
            str54 = strDecodeStringElement43;
            str27 = str58;
            str11 = strDecodeStringElement19;
            str7 = strDecodeStringElement34;
            str55 = strDecodeStringElement40;
            str33 = strDecodeStringElement25;
            str22 = strDecodeStringElement8;
            str4 = strDecodeStringElement31;
            str51 = strDecodeStringElement38;
            str36 = strDecodeStringElement4;
            str41 = strDecodeStringElement24;
            str2 = strDecodeStringElement29;
            str42 = strDecodeStringElement16;
            str17 = strDecodeStringElement22;
            str12 = strDecodeStringElement13;
            str20 = strDecodeStringElement11;
            str47 = strDecodeStringElement2;
            i = -1;
            str13 = strDecodeStringElement12;
            str26 = str62;
            i2 = Integer.MAX_VALUE;
            str48 = strDecodeStringElement46;
            str29 = str61;
            str49 = strDecodeStringElement37;
            str50 = strDecodeStringElement45;
            str = strDecodeStringElement28;
            str8 = strDecodeStringElement36;
            str9 = strDecodeStringElement21;
            str39 = strDecodeStringElement27;
            str10 = strDecodeStringElement20;
            str24 = strDecodeStringElement6;
            str18 = strDecodeStringElement18;
            str21 = strDecodeStringElement9;
            str46 = strDecodeStringElement3;
            str53 = strDecodeStringElement39;
            str3 = strDecodeStringElement30;
            str16 = strDecodeStringElement23;
            str40 = strDecodeStringElement15;
        } else {
            boolean z5 = false;
            i = 0;
            i2 = 0;
            boolean zDecodeBooleanElement5 = false;
            boolean z6 = true;
            Boolean bool3 = null;
            String str66 = null;
            String str67 = null;
            String str68 = null;
            String str69 = null;
            AssetsRubikIncome assetsRubikIncome3 = null;
            String str70 = null;
            String str71 = null;
            String str72 = null;
            String strDecodeStringElement51 = null;
            String strDecodeStringElement52 = null;
            String strDecodeStringElement53 = null;
            String strDecodeStringElement54 = null;
            String strDecodeStringElement55 = null;
            String strDecodeStringElement56 = null;
            String strDecodeStringElement57 = null;
            String strDecodeStringElement58 = null;
            String strDecodeStringElement59 = null;
            String strDecodeStringElement60 = null;
            String strDecodeStringElement61 = null;
            String strDecodeStringElement62 = null;
            String strDecodeStringElement63 = null;
            String strDecodeStringElement64 = null;
            String strDecodeStringElement65 = null;
            String strDecodeStringElement66 = null;
            String strDecodeStringElement67 = null;
            String strDecodeStringElement68 = null;
            String strDecodeStringElement69 = null;
            String strDecodeStringElement70 = null;
            String strDecodeStringElement71 = null;
            String strDecodeStringElement72 = null;
            String strDecodeStringElement73 = null;
            String strDecodeStringElement74 = null;
            String strDecodeStringElement75 = null;
            String strDecodeStringElement76 = null;
            String strDecodeStringElement77 = null;
            String strDecodeStringElement78 = null;
            String strDecodeStringElement79 = null;
            String strDecodeStringElement80 = null;
            String strDecodeStringElement81 = null;
            String strDecodeStringElement82 = null;
            String strDecodeStringElement83 = null;
            String strDecodeStringElement84 = null;
            String strDecodeStringElement85 = null;
            String strDecodeStringElement86 = null;
            String strDecodeStringElement87 = null;
            String strDecodeStringElement88 = null;
            String strDecodeStringElement89 = null;
            String strDecodeStringElement90 = null;
            String strDecodeStringElement91 = null;
            String strDecodeStringElement92 = null;
            String strDecodeStringElement93 = null;
            String strDecodeStringElement94 = null;
            String strDecodeStringElement95 = null;
            String strDecodeStringElement96 = null;
            String strDecodeStringElement97 = null;
            String strDecodeStringElement98 = null;
            String strDecodeStringElement99 = null;
            String str73 = null;
            String str74 = null;
            boolean z7 = false;
            while (true) {
                boolean z8 = z7;
                if (z6) {
                    int iDecodeElementIndex = compositeDecoderBeginStructure.decodeElementIndex(serialDescriptor);
                    switch (iDecodeElementIndex) {
                        case -1:
                            z4 = z5;
                            Unit unit = Unit.INSTANCE;
                            z6 = false;
                            z7 = z8;
                            z5 = z4;
                            break;
                        case 0:
                            z4 = z5;
                            String strDecodeStringElement100 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 0);
                            i |= 1;
                            Unit unit2 = Unit.INSTANCE;
                            str73 = strDecodeStringElement100;
                            z7 = z8;
                            z5 = z4;
                            break;
                        case 1:
                            z4 = z5;
                            strDecodeStringElement99 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 1);
                            i |= 2;
                            Unit unit3 = Unit.INSTANCE;
                            z7 = z8;
                            z5 = z4;
                            break;
                        case 2:
                            z4 = z5;
                            strDecodeStringElement98 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 2);
                            i |= 4;
                            Unit unit4 = Unit.INSTANCE;
                            z7 = z8;
                            z5 = z4;
                            break;
                        case 3:
                            z4 = z5;
                            strDecodeStringElement97 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 3);
                            i |= 8;
                            Unit unit42 = Unit.INSTANCE;
                            z7 = z8;
                            z5 = z4;
                            break;
                        case 4:
                            z4 = z5;
                            strDecodeStringElement96 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 4);
                            i |= 16;
                            Unit unit422 = Unit.INSTANCE;
                            z7 = z8;
                            z5 = z4;
                            break;
                        case 5:
                            z4 = z5;
                            strDecodeStringElement95 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 5);
                            i |= 32;
                            Unit unit4222 = Unit.INSTANCE;
                            z7 = z8;
                            z5 = z4;
                            break;
                        case 6:
                            z4 = z5;
                            strDecodeStringElement94 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 6);
                            i |= 64;
                            Unit unit42222 = Unit.INSTANCE;
                            z7 = z8;
                            z5 = z4;
                            break;
                        case 7:
                            z4 = z5;
                            strDecodeStringElement93 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 7);
                            i |= 128;
                            Unit unit422222 = Unit.INSTANCE;
                            z7 = z8;
                            z5 = z4;
                            break;
                        case 8:
                            z4 = z5;
                            strDecodeStringElement82 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 8);
                            i |= 256;
                            Unit unit4222222 = Unit.INSTANCE;
                            z7 = z8;
                            z5 = z4;
                            break;
                        case 9:
                            z4 = z5;
                            strDecodeStringElement92 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 9);
                            i |= 512;
                            Unit unit42222222 = Unit.INSTANCE;
                            z7 = z8;
                            z5 = z4;
                            break;
                        case 10:
                            z4 = z5;
                            strDecodeStringElement81 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 10);
                            i |= 1024;
                            Unit unit422222222 = Unit.INSTANCE;
                            z7 = z8;
                            z5 = z4;
                            break;
                        case 11:
                            z4 = z5;
                            strDecodeStringElement80 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 11);
                            i |= 2048;
                            Unit unit4222222222 = Unit.INSTANCE;
                            z7 = z8;
                            z5 = z4;
                            break;
                        case 12:
                            z4 = z5;
                            strDecodeStringElement91 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 12);
                            i |= 4096;
                            Unit unit42222222222 = Unit.INSTANCE;
                            z7 = z8;
                            z5 = z4;
                            break;
                        case 13:
                            z4 = z5;
                            strDecodeStringElement79 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 13);
                            i |= 8192;
                            Unit unit422222222222 = Unit.INSTANCE;
                            z7 = z8;
                            z5 = z4;
                            break;
                        case 14:
                            z4 = z5;
                            strDecodeStringElement90 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 14);
                            i |= 16384;
                            Unit unit4222222222222 = Unit.INSTANCE;
                            z7 = z8;
                            z5 = z4;
                            break;
                        case 15:
                            z4 = z5;
                            strDecodeStringElement89 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 15);
                            i3 = 32768;
                            i |= i3;
                            Unit unit42222222222222 = Unit.INSTANCE;
                            z7 = z8;
                            z5 = z4;
                            break;
                        case 16:
                            z4 = z5;
                            strDecodeStringElement88 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 16);
                            i3 = 65536;
                            i |= i3;
                            Unit unit422222222222222 = Unit.INSTANCE;
                            z7 = z8;
                            z5 = z4;
                            break;
                        case 17:
                            z4 = z5;
                            strDecodeStringElement78 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 17);
                            i3 = 131072;
                            i |= i3;
                            Unit unit4222222222222222 = Unit.INSTANCE;
                            z7 = z8;
                            z5 = z4;
                            break;
                        case 18:
                            z4 = z5;
                            strDecodeStringElement77 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 18);
                            i3 = 262144;
                            i |= i3;
                            Unit unit42222222222222222 = Unit.INSTANCE;
                            z7 = z8;
                            z5 = z4;
                            break;
                        case 19:
                            z4 = z5;
                            strDecodeStringElement76 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 19);
                            int i10 = 524288 | i;
                            Unit unit5 = Unit.INSTANCE;
                            i = i10;
                            zDecodeBooleanElement = z8;
                            z8 = zDecodeBooleanElement;
                            z7 = z8;
                            z5 = z4;
                            break;
                        case 20:
                            z4 = z5;
                            strDecodeStringElement87 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 20);
                            i4 = 1048576;
                            i5 = i4 | i;
                            Unit unit6 = Unit.INSTANCE;
                            i = i5;
                            zDecodeBooleanElement = z8;
                            z8 = zDecodeBooleanElement;
                            z7 = z8;
                            z5 = z4;
                            break;
                        case 21:
                            z4 = z5;
                            strDecodeStringElement86 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 21);
                            i4 = 2097152;
                            i5 = i4 | i;
                            Unit unit62 = Unit.INSTANCE;
                            i = i5;
                            zDecodeBooleanElement = z8;
                            z8 = zDecodeBooleanElement;
                            z7 = z8;
                            z5 = z4;
                            break;
                        case 22:
                            z4 = z5;
                            strDecodeStringElement85 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 22);
                            i4 = 4194304;
                            i5 = i4 | i;
                            Unit unit622 = Unit.INSTANCE;
                            i = i5;
                            zDecodeBooleanElement = z8;
                            z8 = zDecodeBooleanElement;
                            z7 = z8;
                            z5 = z4;
                            break;
                        case 23:
                            z4 = z5;
                            assetsRubikIncome3 = (AssetsRubikIncome) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 23, AssetsRubikIncome$$serializer.INSTANCE, assetsRubikIncome3);
                            i4 = 8388608;
                            i5 = i4 | i;
                            Unit unit6222 = Unit.INSTANCE;
                            i = i5;
                            zDecodeBooleanElement = z8;
                            z8 = zDecodeBooleanElement;
                            z7 = z8;
                            z5 = z4;
                            break;
                        case 24:
                            z4 = z5;
                            strDecodeStringElement84 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 24);
                            i6 = 16777216;
                            i5 = i6 | i;
                            Unit unit7 = Unit.INSTANCE;
                            i = i5;
                            zDecodeBooleanElement = z8;
                            z8 = zDecodeBooleanElement;
                            z7 = z8;
                            z5 = z4;
                            break;
                        case 25:
                            z4 = z5;
                            strDecodeStringElement51 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 25);
                            i6 = MediaHttpDownloader.MAXIMUM_CHUNK_SIZE;
                            i5 = i6 | i;
                            Unit unit72 = Unit.INSTANCE;
                            i = i5;
                            zDecodeBooleanElement = z8;
                            z8 = zDecodeBooleanElement;
                            z7 = z8;
                            z5 = z4;
                            break;
                        case 26:
                            z4 = z5;
                            strDecodeStringElement52 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 26);
                            i6 = 67108864;
                            i5 = i6 | i;
                            Unit unit722 = Unit.INSTANCE;
                            i = i5;
                            zDecodeBooleanElement = z8;
                            z8 = zDecodeBooleanElement;
                            z7 = z8;
                            z5 = z4;
                            break;
                        case 27:
                            z4 = z5;
                            strDecodeStringElement53 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 27);
                            i6 = 134217728;
                            i5 = i6 | i;
                            Unit unit7222 = Unit.INSTANCE;
                            i = i5;
                            zDecodeBooleanElement = z8;
                            z8 = zDecodeBooleanElement;
                            z7 = z8;
                            z5 = z4;
                            break;
                        case 28:
                            z4 = z5;
                            strDecodeStringElement54 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 28);
                            i6 = 268435456;
                            i5 = i6 | i;
                            Unit unit72222 = Unit.INSTANCE;
                            i = i5;
                            zDecodeBooleanElement = z8;
                            z8 = zDecodeBooleanElement;
                            z7 = z8;
                            z5 = z4;
                            break;
                        case 29:
                            z4 = z5;
                            strDecodeStringElement55 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 29);
                            i6 = 536870912;
                            i5 = i6 | i;
                            Unit unit722222 = Unit.INSTANCE;
                            i = i5;
                            zDecodeBooleanElement = z8;
                            z8 = zDecodeBooleanElement;
                            z7 = z8;
                            z5 = z4;
                            break;
                        case 30:
                            z4 = z5;
                            strDecodeStringElement56 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 30);
                            i6 = 1073741824;
                            i5 = i6 | i;
                            Unit unit7222222 = Unit.INSTANCE;
                            i = i5;
                            zDecodeBooleanElement = z8;
                            z8 = zDecodeBooleanElement;
                            z7 = z8;
                            z5 = z4;
                            break;
                        case 31:
                            z4 = z5;
                            strDecodeStringElement57 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 31);
                            i6 = Integer.MIN_VALUE;
                            i5 = i6 | i;
                            Unit unit72222222 = Unit.INSTANCE;
                            i = i5;
                            zDecodeBooleanElement = z8;
                            z8 = zDecodeBooleanElement;
                            z7 = z8;
                            z5 = z4;
                            break;
                        case 32:
                            z4 = z5;
                            strDecodeStringElement58 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 32);
                            i7 = i2 | 1;
                            Unit unit8 = Unit.INSTANCE;
                            i2 = i7;
                            zDecodeBooleanElement = z8;
                            z8 = zDecodeBooleanElement;
                            z7 = z8;
                            z5 = z4;
                            break;
                        case 33:
                            z4 = z5;
                            strDecodeStringElement59 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 33);
                            i7 = i2 | 2;
                            Unit unit9 = Unit.INSTANCE;
                            i2 = i7;
                            zDecodeBooleanElement = z8;
                            z8 = zDecodeBooleanElement;
                            z7 = z8;
                            z5 = z4;
                            break;
                        case 34:
                            z4 = z5;
                            strDecodeStringElement83 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 34);
                            i7 = i2 | 4;
                            Unit unit92 = Unit.INSTANCE;
                            i2 = i7;
                            zDecodeBooleanElement = z8;
                            z8 = zDecodeBooleanElement;
                            z7 = z8;
                            z5 = z4;
                            break;
                        case 35:
                            z4 = z5;
                            strDecodeStringElement75 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 35);
                            i7 = i2 | 8;
                            Unit unit922 = Unit.INSTANCE;
                            i2 = i7;
                            zDecodeBooleanElement = z8;
                            z8 = zDecodeBooleanElement;
                            z7 = z8;
                            z5 = z4;
                            break;
                        case 36:
                            z4 = z5;
                            strDecodeStringElement74 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 36);
                            i7 = i2 | 16;
                            Unit unit9222 = Unit.INSTANCE;
                            i2 = i7;
                            zDecodeBooleanElement = z8;
                            z8 = zDecodeBooleanElement;
                            z7 = z8;
                            z5 = z4;
                            break;
                        case 37:
                            z4 = z5;
                            strDecodeStringElement73 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 37);
                            i7 = i2 | 32;
                            Unit unit92222 = Unit.INSTANCE;
                            i2 = i7;
                            zDecodeBooleanElement = z8;
                            z8 = zDecodeBooleanElement;
                            z7 = z8;
                            z5 = z4;
                            break;
                        case 38:
                            z4 = z5;
                            strDecodeStringElement72 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 38);
                            i7 = i2 | 64;
                            Unit unit922222 = Unit.INSTANCE;
                            i2 = i7;
                            zDecodeBooleanElement = z8;
                            z8 = zDecodeBooleanElement;
                            z7 = z8;
                            z5 = z4;
                            break;
                        case 39:
                            z4 = z5;
                            strDecodeStringElement71 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 39);
                            i7 = i2 | 128;
                            Unit unit9222222 = Unit.INSTANCE;
                            i2 = i7;
                            zDecodeBooleanElement = z8;
                            z8 = zDecodeBooleanElement;
                            z7 = z8;
                            z5 = z4;
                            break;
                        case 40:
                            z4 = z5;
                            strDecodeStringElement70 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 40);
                            i7 = i2 | 256;
                            Unit unit92222222 = Unit.INSTANCE;
                            i2 = i7;
                            zDecodeBooleanElement = z8;
                            z8 = zDecodeBooleanElement;
                            z7 = z8;
                            z5 = z4;
                            break;
                        case 41:
                            z4 = z5;
                            strDecodeStringElement69 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 41);
                            i7 = i2 | 512;
                            Unit unit922222222 = Unit.INSTANCE;
                            i2 = i7;
                            zDecodeBooleanElement = z8;
                            z8 = zDecodeBooleanElement;
                            z7 = z8;
                            z5 = z4;
                            break;
                        case 42:
                            z4 = z5;
                            strDecodeStringElement68 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 42);
                            i7 = i2 | 1024;
                            Unit unit9222222222 = Unit.INSTANCE;
                            i2 = i7;
                            zDecodeBooleanElement = z8;
                            z8 = zDecodeBooleanElement;
                            z7 = z8;
                            z5 = z4;
                            break;
                        case 43:
                            z4 = z5;
                            strDecodeStringElement67 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 43);
                            i7 = i2 | 2048;
                            Unit unit92222222222 = Unit.INSTANCE;
                            i2 = i7;
                            zDecodeBooleanElement = z8;
                            z8 = zDecodeBooleanElement;
                            z7 = z8;
                            z5 = z4;
                            break;
                        case 44:
                            z4 = z5;
                            strDecodeStringElement66 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 44);
                            i7 = i2 | 4096;
                            Unit unit922222222222 = Unit.INSTANCE;
                            i2 = i7;
                            zDecodeBooleanElement = z8;
                            z8 = zDecodeBooleanElement;
                            z7 = z8;
                            z5 = z4;
                            break;
                        case 45:
                            z4 = z5;
                            strDecodeStringElement65 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 45);
                            i7 = i2 | 8192;
                            Unit unit9222222222222 = Unit.INSTANCE;
                            i2 = i7;
                            zDecodeBooleanElement = z8;
                            z8 = zDecodeBooleanElement;
                            z7 = z8;
                            z5 = z4;
                            break;
                        case 46:
                            z4 = z5;
                            str67 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 46, StringSerializer.INSTANCE, str67);
                            i7 = i2 | 16384;
                            Unit unit92222222222222 = Unit.INSTANCE;
                            i2 = i7;
                            zDecodeBooleanElement = z8;
                            z8 = zDecodeBooleanElement;
                            z7 = z8;
                            z5 = z4;
                            break;
                        case 47:
                            z4 = z5;
                            zDecodeBooleanElement5 = compositeDecoderBeginStructure.decodeBooleanElement(serialDescriptor, 47);
                            i8 = 32768;
                            i7 = i8 | i2;
                            Unit unit922222222222222 = Unit.INSTANCE;
                            i2 = i7;
                            zDecodeBooleanElement = z8;
                            z8 = zDecodeBooleanElement;
                            z7 = z8;
                            z5 = z4;
                            break;
                        case 48:
                            z4 = z5;
                            zDecodeBooleanElement = compositeDecoderBeginStructure.decodeBooleanElement(serialDescriptor, 48);
                            int i11 = 65536 | i2;
                            Unit unit10 = Unit.INSTANCE;
                            i2 = i11;
                            z8 = zDecodeBooleanElement;
                            z7 = z8;
                            z5 = z4;
                            break;
                        case 49:
                            boolean zDecodeBooleanElement6 = compositeDecoderBeginStructure.decodeBooleanElement(serialDescriptor, 49);
                            int i12 = 131072 | i2;
                            Unit unit11 = Unit.INSTANCE;
                            z4 = zDecodeBooleanElement6;
                            i2 = i12;
                            zDecodeBooleanElement = z8;
                            z8 = zDecodeBooleanElement;
                            z7 = z8;
                            z5 = z4;
                            break;
                        case 50:
                            z4 = z5;
                            str70 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 50, StringSerializer.INSTANCE, str70);
                            i8 = 262144;
                            i7 = i8 | i2;
                            Unit unit9222222222222222 = Unit.INSTANCE;
                            i2 = i7;
                            zDecodeBooleanElement = z8;
                            z8 = zDecodeBooleanElement;
                            z7 = z8;
                            z5 = z4;
                            break;
                        case 51:
                            z4 = z5;
                            str71 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 51, StringSerializer.INSTANCE, str71);
                            i8 = 524288;
                            i7 = i8 | i2;
                            Unit unit92222222222222222 = Unit.INSTANCE;
                            i2 = i7;
                            zDecodeBooleanElement = z8;
                            z8 = zDecodeBooleanElement;
                            z7 = z8;
                            z5 = z4;
                            break;
                        case 52:
                            z4 = z5;
                            str72 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 52, StringSerializer.INSTANCE, str72);
                            i8 = 1048576;
                            i7 = i8 | i2;
                            Unit unit922222222222222222 = Unit.INSTANCE;
                            i2 = i7;
                            zDecodeBooleanElement = z8;
                            z8 = zDecodeBooleanElement;
                            z7 = z8;
                            z5 = z4;
                            break;
                        case 53:
                            z4 = z5;
                            str66 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 53, StringSerializer.INSTANCE, str66);
                            i8 = 2097152;
                            i7 = i8 | i2;
                            Unit unit9222222222222222222 = Unit.INSTANCE;
                            i2 = i7;
                            zDecodeBooleanElement = z8;
                            z8 = zDecodeBooleanElement;
                            z7 = z8;
                            z5 = z4;
                            break;
                        case 54:
                            z4 = z5;
                            bool3 = (Boolean) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 54, BooleanSerializer.INSTANCE, bool3);
                            i8 = 4194304;
                            i7 = i8 | i2;
                            Unit unit92222222222222222222 = Unit.INSTANCE;
                            i2 = i7;
                            zDecodeBooleanElement = z8;
                            z8 = zDecodeBooleanElement;
                            z7 = z8;
                            z5 = z4;
                            break;
                        case 55:
                            z4 = z5;
                            str68 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 55, StringSerializer.INSTANCE, str68);
                            i8 = 8388608;
                            i7 = i8 | i2;
                            Unit unit922222222222222222222 = Unit.INSTANCE;
                            i2 = i7;
                            zDecodeBooleanElement = z8;
                            z8 = zDecodeBooleanElement;
                            z7 = z8;
                            z5 = z4;
                            break;
                        case 56:
                            z4 = z5;
                            str69 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 56, StringSerializer.INSTANCE, str69);
                            i8 = 16777216;
                            i7 = i8 | i2;
                            Unit unit9222222222222222222222 = Unit.INSTANCE;
                            i2 = i7;
                            zDecodeBooleanElement = z8;
                            z8 = zDecodeBooleanElement;
                            z7 = z8;
                            z5 = z4;
                            break;
                        case 57:
                            z4 = z5;
                            str74 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 57, StringSerializer.INSTANCE, str74);
                            i8 = MediaHttpDownloader.MAXIMUM_CHUNK_SIZE;
                            i7 = i8 | i2;
                            Unit unit92222222222222222222222 = Unit.INSTANCE;
                            i2 = i7;
                            zDecodeBooleanElement = z8;
                            z8 = zDecodeBooleanElement;
                            z7 = z8;
                            z5 = z4;
                            break;
                        case 58:
                            strDecodeStringElement64 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 58);
                            i9 = 67108864;
                            int i13 = i9 | i2;
                            Unit unit12 = Unit.INSTANCE;
                            i2 = i13;
                            z4 = z5;
                            zDecodeBooleanElement = z8;
                            z8 = zDecodeBooleanElement;
                            z7 = z8;
                            z5 = z4;
                            break;
                        case 59:
                            strDecodeStringElement63 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 59);
                            i9 = 134217728;
                            int i132 = i9 | i2;
                            Unit unit122 = Unit.INSTANCE;
                            i2 = i132;
                            z4 = z5;
                            zDecodeBooleanElement = z8;
                            z8 = zDecodeBooleanElement;
                            z7 = z8;
                            z5 = z4;
                            break;
                        case 60:
                            strDecodeStringElement62 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 60);
                            i9 = 268435456;
                            int i1322 = i9 | i2;
                            Unit unit1222 = Unit.INSTANCE;
                            i2 = i1322;
                            z4 = z5;
                            zDecodeBooleanElement = z8;
                            z8 = zDecodeBooleanElement;
                            z7 = z8;
                            z5 = z4;
                            break;
                        case 61:
                            strDecodeStringElement61 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 61);
                            i9 = 536870912;
                            int i13222 = i9 | i2;
                            Unit unit12222 = Unit.INSTANCE;
                            i2 = i13222;
                            z4 = z5;
                            zDecodeBooleanElement = z8;
                            z8 = zDecodeBooleanElement;
                            z7 = z8;
                            z5 = z4;
                            break;
                        case 62:
                            strDecodeStringElement60 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 62);
                            i9 = 1073741824;
                            int i132222 = i9 | i2;
                            Unit unit122222 = Unit.INSTANCE;
                            i2 = i132222;
                            z4 = z5;
                            zDecodeBooleanElement = z8;
                            z8 = zDecodeBooleanElement;
                            z7 = z8;
                            z5 = z4;
                            break;
                        default:
                            throw new UnknownFieldException(iDecodeElementIndex);
                    }
                } else {
                    str = strDecodeStringElement53;
                    str2 = strDecodeStringElement54;
                    str3 = strDecodeStringElement55;
                    str4 = strDecodeStringElement56;
                    str5 = strDecodeStringElement57;
                    str6 = strDecodeStringElement58;
                    str7 = strDecodeStringElement59;
                    str8 = strDecodeStringElement75;
                    str9 = strDecodeStringElement76;
                    str10 = strDecodeStringElement77;
                    str11 = strDecodeStringElement78;
                    str12 = strDecodeStringElement80;
                    str13 = strDecodeStringElement81;
                    str14 = strDecodeStringElement82;
                    str15 = strDecodeStringElement83;
                    str16 = strDecodeStringElement86;
                    str17 = strDecodeStringElement87;
                    str18 = strDecodeStringElement88;
                    str19 = strDecodeStringElement89;
                    str20 = strDecodeStringElement92;
                    str21 = strDecodeStringElement93;
                    str22 = strDecodeStringElement94;
                    str23 = strDecodeStringElement95;
                    str24 = strDecodeStringElement96;
                    z = z8;
                    z2 = z5;
                    str25 = str74;
                    bool = bool3;
                    str26 = str66;
                    str27 = str67;
                    str28 = str71;
                    str29 = str72;
                    z3 = zDecodeBooleanElement5;
                    str30 = strDecodeStringElement62;
                    str31 = strDecodeStringElement63;
                    str32 = strDecodeStringElement64;
                    str33 = strDecodeStringElement84;
                    str34 = strDecodeStringElement91;
                    str35 = strDecodeStringElement97;
                    str36 = strDecodeStringElement98;
                    str37 = str68;
                    str38 = strDecodeStringElement51;
                    str39 = strDecodeStringElement52;
                    strDecodeStringElement = strDecodeStringElement60;
                    str40 = strDecodeStringElement79;
                    str41 = strDecodeStringElement85;
                    str42 = strDecodeStringElement90;
                    str43 = str69;
                    str44 = str70;
                    str45 = strDecodeStringElement61;
                    str46 = strDecodeStringElement99;
                    assetsRubikIncome = assetsRubikIncome3;
                    str47 = str73;
                    String str75 = strDecodeStringElement74;
                    str48 = strDecodeStringElement65;
                    str49 = str75;
                    String str76 = strDecodeStringElement73;
                    str50 = strDecodeStringElement66;
                    str51 = str76;
                    String str77 = strDecodeStringElement72;
                    str52 = strDecodeStringElement67;
                    str53 = str77;
                    String str78 = strDecodeStringElement71;
                    str54 = strDecodeStringElement68;
                    str55 = str78;
                    String str79 = strDecodeStringElement70;
                    str56 = strDecodeStringElement69;
                    str57 = str79;
                }
            }
        }
        compositeDecoderBeginStructure.endStructure(serialDescriptor);
        return new AccountDetailData(i, i2, str47, str46, str36, str35, str24, str23, str22, str21, str14, str20, str13, str12, str34, str40, str42, str19, str18, str11, str10, str9, str17, str16, str41, assetsRubikIncome, str33, str38, str39, str, str2, str3, str4, str5, str6, str7, str15, str8, str49, str51, str53, str55, str57, str56, str54, str52, str50, str48, str27, z3, z, z2, str44, str28, str29, str26, bool, str37, str43, str25, str32, str31, str30, str45, strDecodeStringElement, (SerializationConstructorMarker) null);
    }

    /* JADX DEBUG: Method merged with bridge method: serialize(Lkotlinx/serialization/encoding/Encoder;Ljava/lang/Object;)V */
    @Override // kotlinx.serialization.SerializationStrategy
    public final void serialize(@NotNull Encoder encoder, @NotNull AccountDetailData accountDetailData) {
        Intrinsics.checkNotNullParameter(encoder, "");
        Intrinsics.checkNotNullParameter(accountDetailData, "");
        SerialDescriptor serialDescriptor = descriptor;
        CompositeEncoder compositeEncoderBeginStructure = encoder.beginStructure(serialDescriptor);
        AccountDetailData.write$Self$OKTradeCore_trade_core(accountDetailData, compositeEncoderBeginStructure, serialDescriptor);
        compositeEncoderBeginStructure.endStructure(serialDescriptor);
    }
}
