package com.okinc.business.dexlogic.bean;

import com.google.api.client.googleapis.media.MediaHttpDownloader;
import kotlin.Unit;
import kotlin.jvm.internal.Intrinsics;
import kotlinx.serialization.KSerializer;
import kotlinx.serialization.UnknownFieldException;
import kotlinx.serialization.builtins.BuiltinSerializersKt;
import kotlinx.serialization.descriptors.SerialDescriptor;
import kotlinx.serialization.encoding.CompositeDecoder;
import kotlinx.serialization.encoding.CompositeEncoder;
import kotlinx.serialization.encoding.Decoder;
import kotlinx.serialization.encoding.Encoder;
import kotlinx.serialization.internal.BooleanSerializer;
import kotlinx.serialization.internal.GeneratedSerializer;
import kotlinx.serialization.internal.PluginGeneratedSerialDescriptor;
import kotlinx.serialization.internal.SerializationConstructorMarker;
import kotlinx.serialization.internal.StringSerializer;
import org.jetbrains.annotations.NotNull;

/* JADX INFO: loaded from: classes15.dex */
public final /* synthetic */ class DexMultiChildOrderInfoVo$$serializer implements GeneratedSerializer<DexMultiChildOrderInfoVo> {
    public static final int $stable;
    public static final DexMultiChildOrderInfoVo$$serializer INSTANCE;
    private static final SerialDescriptor descriptor;

    /* JADX DEBUG: Don't trust debug lines info. Lines numbers was adjusted: min line is 0 */
    private DexMultiChildOrderInfoVo$$serializer() {
    }

    /* JADX DEBUG: Don't trust debug lines info. Lines numbers was adjusted: min line is 0 */
    @Override // kotlinx.serialization.KSerializer, kotlinx.serialization.SerializationStrategy, kotlinx.serialization.DeserializationStrategy
    public final SerialDescriptor getDescriptor() {
        return descriptor;
    }

    static {
        DexMultiChildOrderInfoVo$$serializer dexMultiChildOrderInfoVo$$serializer = new DexMultiChildOrderInfoVo$$serializer();
        INSTANCE = dexMultiChildOrderInfoVo$$serializer;
        $stable = 8;
        PluginGeneratedSerialDescriptor pluginGeneratedSerialDescriptor = new PluginGeneratedSerialDescriptor("com.okinc.business.dexlogic.bean.DexMultiChildOrderInfoVo", dexMultiChildOrderInfoVo$$serializer, 58);
        pluginGeneratedSerialDescriptor.addElement("bridgeOrderInfoVo", true);
        pluginGeneratedSerialDescriptor.addElement("dexBridgeShadowTokenPairInfoVo", true);
        pluginGeneratedSerialDescriptor.addElement("childOrderId", true);
        pluginGeneratedSerialDescriptor.addElement("exploreUrl", true);
        pluginGeneratedSerialDescriptor.addElement("fromAmountIn", true);
        pluginGeneratedSerialDescriptor.addElement("fromChainId", true);
        pluginGeneratedSerialDescriptor.addElement("fromChainLogoUrl", true);
        pluginGeneratedSerialDescriptor.addElement("fromChainName", true);
        pluginGeneratedSerialDescriptor.addElement("fromTokenSymbol", true);
        pluginGeneratedSerialDescriptor.addElement("toastGuideUrl", true);
        pluginGeneratedSerialDescriptor.addElement("orderIndex", true);
        pluginGeneratedSerialDescriptor.addElement("status", true);
        pluginGeneratedSerialDescriptor.addElement("toAmountOut", true);
        pluginGeneratedSerialDescriptor.addElement("toTokenSymbol", true);
        pluginGeneratedSerialDescriptor.addElement("toastType", true);
        pluginGeneratedSerialDescriptor.addElement("transactionHash", true);
        pluginGeneratedSerialDescriptor.addElement("mark", true);
        pluginGeneratedSerialDescriptor.addElement("fromTokenIcon", true);
        pluginGeneratedSerialDescriptor.addElement("toTokenIcon", true);
        pluginGeneratedSerialDescriptor.addElement("toChainId", true);
        pluginGeneratedSerialDescriptor.addElement("toChainName", true);
        pluginGeneratedSerialDescriptor.addElement("toChainLogoUrl", true);
        pluginGeneratedSerialDescriptor.addElement("showArrow", true);
        pluginGeneratedSerialDescriptor.addElement("swapTradeType", true);
        pluginGeneratedSerialDescriptor.addElement("mainStatus", true);
        pluginGeneratedSerialDescriptor.addElement("orderFailReason", true);
        pluginGeneratedSerialDescriptor.addElement("originalTokenSymbol", true);
        pluginGeneratedSerialDescriptor.addElement("lastChildOrderToTokenSymbol", true);
        pluginGeneratedSerialDescriptor.addElement("lastChildOrderChainName", true);
        pluginGeneratedSerialDescriptor.addElement("hiddenFromOrder", true);
        pluginGeneratedSerialDescriptor.addElement("refundAmount", true);
        pluginGeneratedSerialDescriptor.addElement("refundAmountShow", true);
        pluginGeneratedSerialDescriptor.addElement("isPayOrder", true);
        pluginGeneratedSerialDescriptor.addElement("extendStatus", true);
        pluginGeneratedSerialDescriptor.addElement("isShowSpeedUp", true);
        pluginGeneratedSerialDescriptor.addElement("isShowCancel", true);
        pluginGeneratedSerialDescriptor.addElement("isShowSpeedUpCancel", true);
        pluginGeneratedSerialDescriptor.addElement("isDiscountGasStation", true);
        pluginGeneratedSerialDescriptor.addElement("firstOrder", true);
        pluginGeneratedSerialDescriptor.addElement("finalOrder", true);
        pluginGeneratedSerialDescriptor.addElement("gasStationActivityReward", true);
        pluginGeneratedSerialDescriptor.addElement("officialBridgeTime", true);
        pluginGeneratedSerialDescriptor.addElement("localFromChildTag", true);
        pluginGeneratedSerialDescriptor.addElement("localBridgeTag", true);
        pluginGeneratedSerialDescriptor.addElement("localBridgeToTag", true);
        pluginGeneratedSerialDescriptor.addElement("mainEstimatedTime", true);
        pluginGeneratedSerialDescriptor.addElement("fromEstimatedTime", true);
        pluginGeneratedSerialDescriptor.addElement("bridgeEstimatedTime", true);
        pluginGeneratedSerialDescriptor.addElement("originFromEstimatedTime", true);
        pluginGeneratedSerialDescriptor.addElement("originBridgeEstimatedTime", true);
        pluginGeneratedSerialDescriptor.addElement("errorCode", true);
        pluginGeneratedSerialDescriptor.addElement("refundSymbol", true);
        pluginGeneratedSerialDescriptor.addElement("refundChain", true);
        pluginGeneratedSerialDescriptor.addElement("dataType", true);
        pluginGeneratedSerialDescriptor.addElement("mainFromAddress", true);
        pluginGeneratedSerialDescriptor.addElement("mainSpecialOrderType", true);
        pluginGeneratedSerialDescriptor.addElement("mainRelativeTransaction", true);
        pluginGeneratedSerialDescriptor.addElement("guideUrl", true);
        descriptor = pluginGeneratedSerialDescriptor;
    }

    @Override // kotlinx.serialization.internal.GeneratedSerializer
    public final KSerializer<?>[] childSerializers() {
        StringSerializer stringSerializer = StringSerializer.INSTANCE;
        BooleanSerializer booleanSerializer = BooleanSerializer.INSTANCE;
        return new KSerializer[]{BuiltinSerializersKt.getNullable(DexBridgeOrderInfoVo$$serializer.INSTANCE), BuiltinSerializersKt.getNullable(DexBridgeShadowTokenPairInfoVo$$serializer.INSTANCE), stringSerializer, stringSerializer, stringSerializer, stringSerializer, stringSerializer, stringSerializer, stringSerializer, stringSerializer, stringSerializer, stringSerializer, stringSerializer, stringSerializer, stringSerializer, stringSerializer, stringSerializer, stringSerializer, stringSerializer, stringSerializer, stringSerializer, stringSerializer, booleanSerializer, stringSerializer, stringSerializer, stringSerializer, stringSerializer, stringSerializer, stringSerializer, stringSerializer, stringSerializer, stringSerializer, booleanSerializer, stringSerializer, booleanSerializer, booleanSerializer, booleanSerializer, booleanSerializer, booleanSerializer, booleanSerializer, DexGasStationActivity$$serializer.INSTANCE, stringSerializer, booleanSerializer, booleanSerializer, booleanSerializer, stringSerializer, stringSerializer, stringSerializer, stringSerializer, stringSerializer, stringSerializer, stringSerializer, stringSerializer, stringSerializer, stringSerializer, stringSerializer, BuiltinSerializersKt.getNullable(RelativeTransactionVO$$serializer.INSTANCE), stringSerializer};
    }

    /* JADX DEBUG: Method merged with bridge method: deserialize(Lkotlinx/serialization/encoding/Decoder;)Ljava/lang/Object; */
    @Override // kotlinx.serialization.DeserializationStrategy
    public final DexMultiChildOrderInfoVo deserialize(@NotNull Decoder decoder) {
        boolean z;
        boolean z2;
        String str;
        String str2;
        String str3;
        String str4;
        String str5;
        String str6;
        String str7;
        String str8;
        String str9;
        String str10;
        String str11;
        String str12;
        String strDecodeStringElement;
        String str13;
        String str14;
        String str15;
        String str16;
        RelativeTransactionVO relativeTransactionVO;
        String str17;
        String strDecodeStringElement2;
        String str18;
        DexBridgeShadowTokenPairInfoVo dexBridgeShadowTokenPairInfoVo;
        DexGasStationActivity dexGasStationActivity;
        boolean z3;
        boolean z4;
        String str19;
        String str20;
        String str21;
        int i;
        boolean z5;
        String str22;
        String str23;
        String str24;
        String str25;
        String str26;
        boolean z6;
        boolean z7;
        String str27;
        String str28;
        String str29;
        String str30;
        boolean z8;
        DexBridgeOrderInfoVo dexBridgeOrderInfoVo;
        boolean z9;
        String str31;
        String str32;
        String str33;
        boolean z10;
        String str34;
        String str35;
        boolean z11;
        int i2;
        String str36;
        String str37;
        String str38;
        String str39;
        String str40;
        String str41;
        DexBridgeShadowTokenPairInfoVo dexBridgeShadowTokenPairInfoVo2;
        int i3;
        int i4;
        Intrinsics.checkNotNullParameter(decoder, "");
        SerialDescriptor serialDescriptor = descriptor;
        CompositeDecoder compositeDecoderBeginStructure = decoder.beginStructure(serialDescriptor);
        int i5 = 11;
        int i6 = 10;
        int i7 = 5;
        int i8 = 8;
        if (compositeDecoderBeginStructure.decodeSequentially()) {
            DexBridgeOrderInfoVo dexBridgeOrderInfoVo2 = (DexBridgeOrderInfoVo) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 0, DexBridgeOrderInfoVo$$serializer.INSTANCE, null);
            DexBridgeShadowTokenPairInfoVo dexBridgeShadowTokenPairInfoVo3 = (DexBridgeShadowTokenPairInfoVo) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 1, DexBridgeShadowTokenPairInfoVo$$serializer.INSTANCE, null);
            String strDecodeStringElement3 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 2);
            String strDecodeStringElement4 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 3);
            String strDecodeStringElement5 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 4);
            String strDecodeStringElement6 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 5);
            strDecodeStringElement = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 6);
            String strDecodeStringElement7 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 7);
            String strDecodeStringElement8 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 8);
            String strDecodeStringElement9 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 9);
            String strDecodeStringElement10 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 10);
            String strDecodeStringElement11 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 11);
            String strDecodeStringElement12 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 12);
            String strDecodeStringElement13 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 13);
            String strDecodeStringElement14 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 14);
            String strDecodeStringElement15 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 15);
            String strDecodeStringElement16 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 16);
            String strDecodeStringElement17 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 17);
            String strDecodeStringElement18 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 18);
            String strDecodeStringElement19 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 19);
            String strDecodeStringElement20 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 20);
            String strDecodeStringElement21 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 21);
            boolean zDecodeBooleanElement = compositeDecoderBeginStructure.decodeBooleanElement(serialDescriptor, 22);
            String strDecodeStringElement22 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 23);
            String strDecodeStringElement23 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 24);
            String strDecodeStringElement24 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 25);
            String strDecodeStringElement25 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 26);
            String strDecodeStringElement26 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 27);
            String strDecodeStringElement27 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 28);
            String strDecodeStringElement28 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 29);
            String strDecodeStringElement29 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 30);
            String strDecodeStringElement30 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 31);
            boolean zDecodeBooleanElement2 = compositeDecoderBeginStructure.decodeBooleanElement(serialDescriptor, 32);
            String strDecodeStringElement31 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 33);
            boolean zDecodeBooleanElement3 = compositeDecoderBeginStructure.decodeBooleanElement(serialDescriptor, 34);
            boolean zDecodeBooleanElement4 = compositeDecoderBeginStructure.decodeBooleanElement(serialDescriptor, 35);
            boolean zDecodeBooleanElement5 = compositeDecoderBeginStructure.decodeBooleanElement(serialDescriptor, 36);
            boolean zDecodeBooleanElement6 = compositeDecoderBeginStructure.decodeBooleanElement(serialDescriptor, 37);
            boolean zDecodeBooleanElement7 = compositeDecoderBeginStructure.decodeBooleanElement(serialDescriptor, 38);
            boolean zDecodeBooleanElement8 = compositeDecoderBeginStructure.decodeBooleanElement(serialDescriptor, 39);
            DexGasStationActivity dexGasStationActivity2 = (DexGasStationActivity) compositeDecoderBeginStructure.decodeSerializableElement(serialDescriptor, 40, DexGasStationActivity$$serializer.INSTANCE, null);
            String strDecodeStringElement32 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 41);
            boolean zDecodeBooleanElement9 = compositeDecoderBeginStructure.decodeBooleanElement(serialDescriptor, 42);
            boolean zDecodeBooleanElement10 = compositeDecoderBeginStructure.decodeBooleanElement(serialDescriptor, 43);
            boolean zDecodeBooleanElement11 = compositeDecoderBeginStructure.decodeBooleanElement(serialDescriptor, 44);
            String strDecodeStringElement33 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 45);
            String strDecodeStringElement34 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 46);
            String strDecodeStringElement35 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 47);
            String strDecodeStringElement36 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 48);
            String strDecodeStringElement37 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 49);
            String strDecodeStringElement38 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 50);
            String strDecodeStringElement39 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 51);
            String strDecodeStringElement40 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 52);
            String strDecodeStringElement41 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 53);
            String strDecodeStringElement42 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 54);
            String strDecodeStringElement43 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 55);
            i2 = 67108863;
            relativeTransactionVO = (RelativeTransactionVO) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 56, RelativeTransactionVO$$serializer.INSTANCE, null);
            strDecodeStringElement2 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 57);
            str30 = strDecodeStringElement41;
            str35 = strDecodeStringElement42;
            str29 = strDecodeStringElement43;
            str16 = strDecodeStringElement36;
            str22 = strDecodeStringElement37;
            str18 = strDecodeStringElement38;
            z6 = zDecodeBooleanElement10;
            z5 = zDecodeBooleanElement11;
            str41 = strDecodeStringElement33;
            z7 = zDecodeBooleanElement7;
            z10 = zDecodeBooleanElement8;
            dexGasStationActivity = dexGasStationActivity2;
            str19 = strDecodeStringElement31;
            z = zDecodeBooleanElement3;
            z8 = zDecodeBooleanElement6;
            z3 = zDecodeBooleanElement2;
            str20 = strDecodeStringElement27;
            str26 = strDecodeStringElement28;
            str10 = strDecodeStringElement9;
            str2 = strDecodeStringElement23;
            str = strDecodeStringElement24;
            str14 = strDecodeStringElement5;
            str31 = strDecodeStringElement20;
            str3 = strDecodeStringElement21;
            z11 = zDecodeBooleanElement5;
            str34 = strDecodeStringElement17;
            str4 = strDecodeStringElement15;
            str39 = strDecodeStringElement30;
            str9 = strDecodeStringElement10;
            str7 = strDecodeStringElement12;
            str40 = strDecodeStringElement26;
            str15 = strDecodeStringElement4;
            str12 = strDecodeStringElement7;
            str21 = strDecodeStringElement22;
            z9 = zDecodeBooleanElement4;
            str23 = strDecodeStringElement19;
            str13 = strDecodeStringElement6;
            str36 = strDecodeStringElement29;
            dexBridgeShadowTokenPairInfoVo = dexBridgeShadowTokenPairInfoVo3;
            str37 = strDecodeStringElement25;
            str25 = strDecodeStringElement40;
            z4 = zDecodeBooleanElement;
            str17 = strDecodeStringElement35;
            z2 = zDecodeBooleanElement9;
            str27 = strDecodeStringElement18;
            str11 = strDecodeStringElement8;
            str32 = strDecodeStringElement3;
            i = -1;
            str28 = strDecodeStringElement16;
            str8 = strDecodeStringElement11;
            str6 = strDecodeStringElement13;
            dexBridgeOrderInfoVo = dexBridgeOrderInfoVo2;
            str5 = strDecodeStringElement14;
            str38 = strDecodeStringElement34;
            str24 = strDecodeStringElement32;
            str33 = strDecodeStringElement39;
        } else {
            int i9 = 0;
            int i10 = 0;
            boolean zDecodeBooleanElement12 = false;
            boolean zDecodeBooleanElement13 = false;
            boolean zDecodeBooleanElement14 = false;
            boolean zDecodeBooleanElement15 = false;
            boolean zDecodeBooleanElement16 = false;
            boolean zDecodeBooleanElement17 = false;
            boolean zDecodeBooleanElement18 = false;
            boolean zDecodeBooleanElement19 = false;
            boolean zDecodeBooleanElement20 = false;
            boolean zDecodeBooleanElement21 = false;
            DexGasStationActivity dexGasStationActivity3 = null;
            String strDecodeStringElement44 = null;
            String strDecodeStringElement45 = null;
            String strDecodeStringElement46 = null;
            String strDecodeStringElement47 = null;
            String strDecodeStringElement48 = null;
            String strDecodeStringElement49 = null;
            String strDecodeStringElement50 = null;
            String strDecodeStringElement51 = null;
            String strDecodeStringElement52 = null;
            String strDecodeStringElement53 = null;
            String strDecodeStringElement54 = null;
            String strDecodeStringElement55 = null;
            String strDecodeStringElement56 = null;
            String strDecodeStringElement57 = null;
            String strDecodeStringElement58 = null;
            String strDecodeStringElement59 = null;
            String strDecodeStringElement60 = null;
            String strDecodeStringElement61 = null;
            String strDecodeStringElement62 = null;
            String strDecodeStringElement63 = null;
            String strDecodeStringElement64 = null;
            String strDecodeStringElement65 = null;
            String strDecodeStringElement66 = null;
            String strDecodeStringElement67 = null;
            String strDecodeStringElement68 = null;
            String strDecodeStringElement69 = null;
            String strDecodeStringElement70 = null;
            String strDecodeStringElement71 = null;
            String strDecodeStringElement72 = null;
            String strDecodeStringElement73 = null;
            String strDecodeStringElement74 = null;
            String strDecodeStringElement75 = null;
            String strDecodeStringElement76 = null;
            String strDecodeStringElement77 = null;
            String strDecodeStringElement78 = null;
            String strDecodeStringElement79 = null;
            String strDecodeStringElement80 = null;
            String strDecodeStringElement81 = null;
            String strDecodeStringElement82 = null;
            String strDecodeStringElement83 = null;
            String strDecodeStringElement84 = null;
            String strDecodeStringElement85 = null;
            DexBridgeShadowTokenPairInfoVo dexBridgeShadowTokenPairInfoVo4 = null;
            String strDecodeStringElement86 = null;
            DexBridgeOrderInfoVo dexBridgeOrderInfoVo3 = null;
            boolean z12 = true;
            RelativeTransactionVO relativeTransactionVO2 = null;
            boolean zDecodeBooleanElement22 = false;
            while (z12) {
                int iDecodeElementIndex = compositeDecoderBeginStructure.decodeElementIndex(serialDescriptor);
                switch (iDecodeElementIndex) {
                    case -1:
                        dexBridgeShadowTokenPairInfoVo2 = dexBridgeShadowTokenPairInfoVo4;
                        Unit unit = Unit.INSTANCE;
                        z12 = false;
                        dexBridgeShadowTokenPairInfoVo4 = dexBridgeShadowTokenPairInfoVo2;
                        i8 = 8;
                        i5 = 11;
                        i6 = 10;
                        i7 = 5;
                        break;
                    case 0:
                        dexBridgeShadowTokenPairInfoVo2 = dexBridgeShadowTokenPairInfoVo4;
                        DexBridgeOrderInfoVo dexBridgeOrderInfoVo4 = (DexBridgeOrderInfoVo) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 0, DexBridgeOrderInfoVo$$serializer.INSTANCE, dexBridgeOrderInfoVo3);
                        i10 |= 1;
                        Unit unit2 = Unit.INSTANCE;
                        dexBridgeOrderInfoVo3 = dexBridgeOrderInfoVo4;
                        dexBridgeShadowTokenPairInfoVo4 = dexBridgeShadowTokenPairInfoVo2;
                        i8 = 8;
                        i5 = 11;
                        i6 = 10;
                        i7 = 5;
                        break;
                    case 1:
                        dexBridgeShadowTokenPairInfoVo4 = (DexBridgeShadowTokenPairInfoVo) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 1, DexBridgeShadowTokenPairInfoVo$$serializer.INSTANCE, dexBridgeShadowTokenPairInfoVo4);
                        i10 |= 2;
                        Unit unit3 = Unit.INSTANCE;
                        dexBridgeShadowTokenPairInfoVo2 = dexBridgeShadowTokenPairInfoVo4;
                        dexBridgeShadowTokenPairInfoVo4 = dexBridgeShadowTokenPairInfoVo2;
                        i8 = 8;
                        i5 = 11;
                        i6 = 10;
                        i7 = 5;
                        break;
                    case 2:
                        strDecodeStringElement85 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 2);
                        i10 |= 4;
                        Unit unit4 = Unit.INSTANCE;
                        dexBridgeShadowTokenPairInfoVo2 = dexBridgeShadowTokenPairInfoVo4;
                        dexBridgeShadowTokenPairInfoVo4 = dexBridgeShadowTokenPairInfoVo2;
                        i8 = 8;
                        i5 = 11;
                        i6 = 10;
                        i7 = 5;
                        break;
                    case 3:
                        strDecodeStringElement84 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 3);
                        i10 |= 8;
                        Unit unit42 = Unit.INSTANCE;
                        dexBridgeShadowTokenPairInfoVo2 = dexBridgeShadowTokenPairInfoVo4;
                        dexBridgeShadowTokenPairInfoVo4 = dexBridgeShadowTokenPairInfoVo2;
                        i8 = 8;
                        i5 = 11;
                        i6 = 10;
                        i7 = 5;
                        break;
                    case 4:
                        strDecodeStringElement83 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 4);
                        i10 |= 16;
                        Unit unit422 = Unit.INSTANCE;
                        dexBridgeShadowTokenPairInfoVo2 = dexBridgeShadowTokenPairInfoVo4;
                        dexBridgeShadowTokenPairInfoVo4 = dexBridgeShadowTokenPairInfoVo2;
                        i8 = 8;
                        i5 = 11;
                        i6 = 10;
                        i7 = 5;
                        break;
                    case 5:
                        strDecodeStringElement82 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, i7);
                        i10 |= 32;
                        Unit unit4222 = Unit.INSTANCE;
                        dexBridgeShadowTokenPairInfoVo2 = dexBridgeShadowTokenPairInfoVo4;
                        dexBridgeShadowTokenPairInfoVo4 = dexBridgeShadowTokenPairInfoVo2;
                        i8 = 8;
                        i5 = 11;
                        i6 = 10;
                        i7 = 5;
                        break;
                    case 6:
                        strDecodeStringElement81 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 6);
                        i10 |= 64;
                        Unit unit42222 = Unit.INSTANCE;
                        dexBridgeShadowTokenPairInfoVo2 = dexBridgeShadowTokenPairInfoVo4;
                        dexBridgeShadowTokenPairInfoVo4 = dexBridgeShadowTokenPairInfoVo2;
                        i8 = 8;
                        i5 = 11;
                        i6 = 10;
                        i7 = 5;
                        break;
                    case 7:
                        strDecodeStringElement80 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 7);
                        i10 |= 128;
                        Unit unit422222 = Unit.INSTANCE;
                        dexBridgeShadowTokenPairInfoVo2 = dexBridgeShadowTokenPairInfoVo4;
                        dexBridgeShadowTokenPairInfoVo4 = dexBridgeShadowTokenPairInfoVo2;
                        i8 = 8;
                        i5 = 11;
                        i6 = 10;
                        i7 = 5;
                        break;
                    case 8:
                        strDecodeStringElement79 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, i8);
                        i10 |= 256;
                        Unit unit4222222 = Unit.INSTANCE;
                        dexBridgeShadowTokenPairInfoVo2 = dexBridgeShadowTokenPairInfoVo4;
                        dexBridgeShadowTokenPairInfoVo4 = dexBridgeShadowTokenPairInfoVo2;
                        i8 = 8;
                        i5 = 11;
                        i6 = 10;
                        i7 = 5;
                        break;
                    case 9:
                        strDecodeStringElement78 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 9);
                        i10 |= 512;
                        Unit unit42222222 = Unit.INSTANCE;
                        dexBridgeShadowTokenPairInfoVo2 = dexBridgeShadowTokenPairInfoVo4;
                        dexBridgeShadowTokenPairInfoVo4 = dexBridgeShadowTokenPairInfoVo2;
                        i8 = 8;
                        i5 = 11;
                        i6 = 10;
                        i7 = 5;
                        break;
                    case 10:
                        strDecodeStringElement77 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, i6);
                        i10 |= 1024;
                        Unit unit422222222 = Unit.INSTANCE;
                        dexBridgeShadowTokenPairInfoVo2 = dexBridgeShadowTokenPairInfoVo4;
                        dexBridgeShadowTokenPairInfoVo4 = dexBridgeShadowTokenPairInfoVo2;
                        i8 = 8;
                        i5 = 11;
                        i6 = 10;
                        i7 = 5;
                        break;
                    case 11:
                        strDecodeStringElement76 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, i5);
                        i10 |= 2048;
                        Unit unit4222222222 = Unit.INSTANCE;
                        dexBridgeShadowTokenPairInfoVo2 = dexBridgeShadowTokenPairInfoVo4;
                        dexBridgeShadowTokenPairInfoVo4 = dexBridgeShadowTokenPairInfoVo2;
                        i8 = 8;
                        i5 = 11;
                        i6 = 10;
                        i7 = 5;
                        break;
                    case 12:
                        strDecodeStringElement75 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 12);
                        i10 |= 4096;
                        Unit unit42222222222 = Unit.INSTANCE;
                        dexBridgeShadowTokenPairInfoVo2 = dexBridgeShadowTokenPairInfoVo4;
                        dexBridgeShadowTokenPairInfoVo4 = dexBridgeShadowTokenPairInfoVo2;
                        i8 = 8;
                        i5 = 11;
                        i6 = 10;
                        i7 = 5;
                        break;
                    case 13:
                        strDecodeStringElement74 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 13);
                        i10 |= 8192;
                        Unit unit5 = Unit.INSTANCE;
                        dexBridgeShadowTokenPairInfoVo2 = dexBridgeShadowTokenPairInfoVo4;
                        dexBridgeShadowTokenPairInfoVo4 = dexBridgeShadowTokenPairInfoVo2;
                        i8 = 8;
                        i5 = 11;
                        i6 = 10;
                        i7 = 5;
                        break;
                    case 14:
                        strDecodeStringElement73 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 14);
                        i10 |= 16384;
                        Unit unit6 = Unit.INSTANCE;
                        dexBridgeShadowTokenPairInfoVo2 = dexBridgeShadowTokenPairInfoVo4;
                        dexBridgeShadowTokenPairInfoVo4 = dexBridgeShadowTokenPairInfoVo2;
                        i8 = 8;
                        i5 = 11;
                        i6 = 10;
                        i7 = 5;
                        break;
                    case 15:
                        strDecodeStringElement72 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 15);
                        i10 |= 32768;
                        Unit unit7 = Unit.INSTANCE;
                        dexBridgeShadowTokenPairInfoVo2 = dexBridgeShadowTokenPairInfoVo4;
                        dexBridgeShadowTokenPairInfoVo4 = dexBridgeShadowTokenPairInfoVo2;
                        i8 = 8;
                        i5 = 11;
                        i6 = 10;
                        i7 = 5;
                        break;
                    case 16:
                        strDecodeStringElement71 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 16);
                        i10 |= 65536;
                        Unit unit8 = Unit.INSTANCE;
                        dexBridgeShadowTokenPairInfoVo2 = dexBridgeShadowTokenPairInfoVo4;
                        dexBridgeShadowTokenPairInfoVo4 = dexBridgeShadowTokenPairInfoVo2;
                        i8 = 8;
                        i5 = 11;
                        i6 = 10;
                        i7 = 5;
                        break;
                    case 17:
                        strDecodeStringElement70 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 17);
                        i10 |= 131072;
                        Unit unit9 = Unit.INSTANCE;
                        dexBridgeShadowTokenPairInfoVo2 = dexBridgeShadowTokenPairInfoVo4;
                        dexBridgeShadowTokenPairInfoVo4 = dexBridgeShadowTokenPairInfoVo2;
                        i8 = 8;
                        i5 = 11;
                        i6 = 10;
                        i7 = 5;
                        break;
                    case 18:
                        strDecodeStringElement69 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 18);
                        i10 |= 262144;
                        Unit unit10 = Unit.INSTANCE;
                        dexBridgeShadowTokenPairInfoVo2 = dexBridgeShadowTokenPairInfoVo4;
                        dexBridgeShadowTokenPairInfoVo4 = dexBridgeShadowTokenPairInfoVo2;
                        i8 = 8;
                        i5 = 11;
                        i6 = 10;
                        i7 = 5;
                        break;
                    case 19:
                        strDecodeStringElement68 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 19);
                        i10 |= 524288;
                        Unit unit11 = Unit.INSTANCE;
                        dexBridgeShadowTokenPairInfoVo2 = dexBridgeShadowTokenPairInfoVo4;
                        dexBridgeShadowTokenPairInfoVo4 = dexBridgeShadowTokenPairInfoVo2;
                        i8 = 8;
                        i5 = 11;
                        i6 = 10;
                        i7 = 5;
                        break;
                    case 20:
                        strDecodeStringElement67 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 20);
                        i3 = 1048576;
                        i10 |= i3;
                        Unit unit12 = Unit.INSTANCE;
                        dexBridgeShadowTokenPairInfoVo2 = dexBridgeShadowTokenPairInfoVo4;
                        dexBridgeShadowTokenPairInfoVo4 = dexBridgeShadowTokenPairInfoVo2;
                        i8 = 8;
                        i5 = 11;
                        i6 = 10;
                        i7 = 5;
                        break;
                    case 21:
                        strDecodeStringElement66 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 21);
                        i3 = 2097152;
                        i10 |= i3;
                        Unit unit122 = Unit.INSTANCE;
                        dexBridgeShadowTokenPairInfoVo2 = dexBridgeShadowTokenPairInfoVo4;
                        dexBridgeShadowTokenPairInfoVo4 = dexBridgeShadowTokenPairInfoVo2;
                        i8 = 8;
                        i5 = 11;
                        i6 = 10;
                        i7 = 5;
                        break;
                    case 22:
                        zDecodeBooleanElement20 = compositeDecoderBeginStructure.decodeBooleanElement(serialDescriptor, 22);
                        i3 = 4194304;
                        i10 |= i3;
                        Unit unit1222 = Unit.INSTANCE;
                        dexBridgeShadowTokenPairInfoVo2 = dexBridgeShadowTokenPairInfoVo4;
                        dexBridgeShadowTokenPairInfoVo4 = dexBridgeShadowTokenPairInfoVo2;
                        i8 = 8;
                        i5 = 11;
                        i6 = 10;
                        i7 = 5;
                        break;
                    case 23:
                        strDecodeStringElement65 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 23);
                        i3 = 8388608;
                        i10 |= i3;
                        Unit unit12222 = Unit.INSTANCE;
                        dexBridgeShadowTokenPairInfoVo2 = dexBridgeShadowTokenPairInfoVo4;
                        dexBridgeShadowTokenPairInfoVo4 = dexBridgeShadowTokenPairInfoVo2;
                        i8 = 8;
                        i5 = 11;
                        i6 = 10;
                        i7 = 5;
                        break;
                    case 24:
                        strDecodeStringElement64 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 24);
                        i3 = 16777216;
                        i10 |= i3;
                        Unit unit122222 = Unit.INSTANCE;
                        dexBridgeShadowTokenPairInfoVo2 = dexBridgeShadowTokenPairInfoVo4;
                        dexBridgeShadowTokenPairInfoVo4 = dexBridgeShadowTokenPairInfoVo2;
                        i8 = 8;
                        i5 = 11;
                        i6 = 10;
                        i7 = 5;
                        break;
                    case 25:
                        strDecodeStringElement63 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 25);
                        i3 = MediaHttpDownloader.MAXIMUM_CHUNK_SIZE;
                        i10 |= i3;
                        Unit unit1222222 = Unit.INSTANCE;
                        dexBridgeShadowTokenPairInfoVo2 = dexBridgeShadowTokenPairInfoVo4;
                        dexBridgeShadowTokenPairInfoVo4 = dexBridgeShadowTokenPairInfoVo2;
                        i8 = 8;
                        i5 = 11;
                        i6 = 10;
                        i7 = 5;
                        break;
                    case 26:
                        strDecodeStringElement62 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 26);
                        i3 = 67108864;
                        i10 |= i3;
                        Unit unit12222222 = Unit.INSTANCE;
                        dexBridgeShadowTokenPairInfoVo2 = dexBridgeShadowTokenPairInfoVo4;
                        dexBridgeShadowTokenPairInfoVo4 = dexBridgeShadowTokenPairInfoVo2;
                        i8 = 8;
                        i5 = 11;
                        i6 = 10;
                        i7 = 5;
                        break;
                    case 27:
                        strDecodeStringElement61 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 27);
                        i3 = 134217728;
                        i10 |= i3;
                        Unit unit122222222 = Unit.INSTANCE;
                        dexBridgeShadowTokenPairInfoVo2 = dexBridgeShadowTokenPairInfoVo4;
                        dexBridgeShadowTokenPairInfoVo4 = dexBridgeShadowTokenPairInfoVo2;
                        i8 = 8;
                        i5 = 11;
                        i6 = 10;
                        i7 = 5;
                        break;
                    case 28:
                        strDecodeStringElement60 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 28);
                        i3 = 268435456;
                        i10 |= i3;
                        Unit unit1222222222 = Unit.INSTANCE;
                        dexBridgeShadowTokenPairInfoVo2 = dexBridgeShadowTokenPairInfoVo4;
                        dexBridgeShadowTokenPairInfoVo4 = dexBridgeShadowTokenPairInfoVo2;
                        i8 = 8;
                        i5 = 11;
                        i6 = 10;
                        i7 = 5;
                        break;
                    case 29:
                        strDecodeStringElement59 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 29);
                        i3 = 536870912;
                        i10 |= i3;
                        Unit unit12222222222 = Unit.INSTANCE;
                        dexBridgeShadowTokenPairInfoVo2 = dexBridgeShadowTokenPairInfoVo4;
                        dexBridgeShadowTokenPairInfoVo4 = dexBridgeShadowTokenPairInfoVo2;
                        i8 = 8;
                        i5 = 11;
                        i6 = 10;
                        i7 = 5;
                        break;
                    case 30:
                        strDecodeStringElement44 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 30);
                        i3 = 1073741824;
                        i10 |= i3;
                        Unit unit122222222222 = Unit.INSTANCE;
                        dexBridgeShadowTokenPairInfoVo2 = dexBridgeShadowTokenPairInfoVo4;
                        dexBridgeShadowTokenPairInfoVo4 = dexBridgeShadowTokenPairInfoVo2;
                        i8 = 8;
                        i5 = 11;
                        i6 = 10;
                        i7 = 5;
                        break;
                    case 31:
                        strDecodeStringElement45 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 31);
                        i3 = Integer.MIN_VALUE;
                        i10 |= i3;
                        Unit unit1222222222222 = Unit.INSTANCE;
                        dexBridgeShadowTokenPairInfoVo2 = dexBridgeShadowTokenPairInfoVo4;
                        dexBridgeShadowTokenPairInfoVo4 = dexBridgeShadowTokenPairInfoVo2;
                        i8 = 8;
                        i5 = 11;
                        i6 = 10;
                        i7 = 5;
                        break;
                    case 32:
                        zDecodeBooleanElement19 = compositeDecoderBeginStructure.decodeBooleanElement(serialDescriptor, 32);
                        i9 |= 1;
                        Unit unit12222222222222 = Unit.INSTANCE;
                        dexBridgeShadowTokenPairInfoVo2 = dexBridgeShadowTokenPairInfoVo4;
                        dexBridgeShadowTokenPairInfoVo4 = dexBridgeShadowTokenPairInfoVo2;
                        i8 = 8;
                        i5 = 11;
                        i6 = 10;
                        i7 = 5;
                        break;
                    case 33:
                        strDecodeStringElement46 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 33);
                        i9 |= 2;
                        Unit unit13 = Unit.INSTANCE;
                        dexBridgeShadowTokenPairInfoVo2 = dexBridgeShadowTokenPairInfoVo4;
                        dexBridgeShadowTokenPairInfoVo4 = dexBridgeShadowTokenPairInfoVo2;
                        i8 = 8;
                        i5 = 11;
                        i6 = 10;
                        i7 = 5;
                        break;
                    case 34:
                        zDecodeBooleanElement18 = compositeDecoderBeginStructure.decodeBooleanElement(serialDescriptor, 34);
                        i9 |= 4;
                        Unit unit132 = Unit.INSTANCE;
                        dexBridgeShadowTokenPairInfoVo2 = dexBridgeShadowTokenPairInfoVo4;
                        dexBridgeShadowTokenPairInfoVo4 = dexBridgeShadowTokenPairInfoVo2;
                        i8 = 8;
                        i5 = 11;
                        i6 = 10;
                        i7 = 5;
                        break;
                    case 35:
                        zDecodeBooleanElement17 = compositeDecoderBeginStructure.decodeBooleanElement(serialDescriptor, 35);
                        i9 |= 8;
                        Unit unit1322 = Unit.INSTANCE;
                        dexBridgeShadowTokenPairInfoVo2 = dexBridgeShadowTokenPairInfoVo4;
                        dexBridgeShadowTokenPairInfoVo4 = dexBridgeShadowTokenPairInfoVo2;
                        i8 = 8;
                        i5 = 11;
                        i6 = 10;
                        i7 = 5;
                        break;
                    case 36:
                        zDecodeBooleanElement22 = compositeDecoderBeginStructure.decodeBooleanElement(serialDescriptor, 36);
                        i9 |= 16;
                        Unit unit13222 = Unit.INSTANCE;
                        dexBridgeShadowTokenPairInfoVo2 = dexBridgeShadowTokenPairInfoVo4;
                        dexBridgeShadowTokenPairInfoVo4 = dexBridgeShadowTokenPairInfoVo2;
                        i8 = 8;
                        i5 = 11;
                        i6 = 10;
                        i7 = 5;
                        break;
                    case 37:
                        zDecodeBooleanElement12 = compositeDecoderBeginStructure.decodeBooleanElement(serialDescriptor, 37);
                        i9 |= 32;
                        Unit unit132222 = Unit.INSTANCE;
                        dexBridgeShadowTokenPairInfoVo2 = dexBridgeShadowTokenPairInfoVo4;
                        dexBridgeShadowTokenPairInfoVo4 = dexBridgeShadowTokenPairInfoVo2;
                        i8 = 8;
                        i5 = 11;
                        i6 = 10;
                        i7 = 5;
                        break;
                    case 38:
                        zDecodeBooleanElement15 = compositeDecoderBeginStructure.decodeBooleanElement(serialDescriptor, 38);
                        i9 |= 64;
                        Unit unit1322222 = Unit.INSTANCE;
                        dexBridgeShadowTokenPairInfoVo2 = dexBridgeShadowTokenPairInfoVo4;
                        dexBridgeShadowTokenPairInfoVo4 = dexBridgeShadowTokenPairInfoVo2;
                        i8 = 8;
                        i5 = 11;
                        i6 = 10;
                        i7 = 5;
                        break;
                    case 39:
                        zDecodeBooleanElement14 = compositeDecoderBeginStructure.decodeBooleanElement(serialDescriptor, 39);
                        i9 |= 128;
                        Unit unit13222222 = Unit.INSTANCE;
                        dexBridgeShadowTokenPairInfoVo2 = dexBridgeShadowTokenPairInfoVo4;
                        dexBridgeShadowTokenPairInfoVo4 = dexBridgeShadowTokenPairInfoVo2;
                        i8 = 8;
                        i5 = 11;
                        i6 = 10;
                        i7 = 5;
                        break;
                    case 40:
                        dexGasStationActivity3 = (DexGasStationActivity) compositeDecoderBeginStructure.decodeSerializableElement(serialDescriptor, 40, DexGasStationActivity$$serializer.INSTANCE, dexGasStationActivity3);
                        i9 |= 256;
                        Unit unit132222222 = Unit.INSTANCE;
                        dexBridgeShadowTokenPairInfoVo2 = dexBridgeShadowTokenPairInfoVo4;
                        dexBridgeShadowTokenPairInfoVo4 = dexBridgeShadowTokenPairInfoVo2;
                        i8 = 8;
                        i5 = 11;
                        i6 = 10;
                        i7 = 5;
                        break;
                    case 41:
                        strDecodeStringElement47 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 41);
                        i9 |= 512;
                        Unit unit1322222222 = Unit.INSTANCE;
                        dexBridgeShadowTokenPairInfoVo2 = dexBridgeShadowTokenPairInfoVo4;
                        dexBridgeShadowTokenPairInfoVo4 = dexBridgeShadowTokenPairInfoVo2;
                        i8 = 8;
                        i5 = 11;
                        i6 = 10;
                        i7 = 5;
                        break;
                    case 42:
                        zDecodeBooleanElement21 = compositeDecoderBeginStructure.decodeBooleanElement(serialDescriptor, 42);
                        i9 |= 1024;
                        Unit unit13222222222 = Unit.INSTANCE;
                        dexBridgeShadowTokenPairInfoVo2 = dexBridgeShadowTokenPairInfoVo4;
                        dexBridgeShadowTokenPairInfoVo4 = dexBridgeShadowTokenPairInfoVo2;
                        i8 = 8;
                        i5 = 11;
                        i6 = 10;
                        i7 = 5;
                        break;
                    case 43:
                        zDecodeBooleanElement13 = compositeDecoderBeginStructure.decodeBooleanElement(serialDescriptor, 43);
                        i9 |= 2048;
                        Unit unit132222222222 = Unit.INSTANCE;
                        dexBridgeShadowTokenPairInfoVo2 = dexBridgeShadowTokenPairInfoVo4;
                        dexBridgeShadowTokenPairInfoVo4 = dexBridgeShadowTokenPairInfoVo2;
                        i8 = 8;
                        i5 = 11;
                        i6 = 10;
                        i7 = 5;
                        break;
                    case 44:
                        zDecodeBooleanElement16 = compositeDecoderBeginStructure.decodeBooleanElement(serialDescriptor, 44);
                        i9 |= 4096;
                        Unit unit1322222222222 = Unit.INSTANCE;
                        dexBridgeShadowTokenPairInfoVo2 = dexBridgeShadowTokenPairInfoVo4;
                        dexBridgeShadowTokenPairInfoVo4 = dexBridgeShadowTokenPairInfoVo2;
                        i8 = 8;
                        i5 = 11;
                        i6 = 10;
                        i7 = 5;
                        break;
                    case 45:
                        strDecodeStringElement48 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 45);
                        i9 |= 8192;
                        Unit unit13222222222222 = Unit.INSTANCE;
                        dexBridgeShadowTokenPairInfoVo2 = dexBridgeShadowTokenPairInfoVo4;
                        dexBridgeShadowTokenPairInfoVo4 = dexBridgeShadowTokenPairInfoVo2;
                        i8 = 8;
                        i5 = 11;
                        i6 = 10;
                        i7 = 5;
                        break;
                    case 46:
                        strDecodeStringElement49 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 46);
                        i9 |= 16384;
                        Unit unit132222222222222 = Unit.INSTANCE;
                        dexBridgeShadowTokenPairInfoVo2 = dexBridgeShadowTokenPairInfoVo4;
                        dexBridgeShadowTokenPairInfoVo4 = dexBridgeShadowTokenPairInfoVo2;
                        i8 = 8;
                        i5 = 11;
                        i6 = 10;
                        i7 = 5;
                        break;
                    case 47:
                        strDecodeStringElement50 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 47);
                        i4 = 32768;
                        i9 |= i4;
                        Unit unit1322222222222222 = Unit.INSTANCE;
                        dexBridgeShadowTokenPairInfoVo2 = dexBridgeShadowTokenPairInfoVo4;
                        dexBridgeShadowTokenPairInfoVo4 = dexBridgeShadowTokenPairInfoVo2;
                        i8 = 8;
                        i5 = 11;
                        i6 = 10;
                        i7 = 5;
                        break;
                    case 48:
                        strDecodeStringElement86 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 48);
                        i4 = 65536;
                        i9 |= i4;
                        Unit unit13222222222222222 = Unit.INSTANCE;
                        dexBridgeShadowTokenPairInfoVo2 = dexBridgeShadowTokenPairInfoVo4;
                        dexBridgeShadowTokenPairInfoVo4 = dexBridgeShadowTokenPairInfoVo2;
                        i8 = 8;
                        i5 = 11;
                        i6 = 10;
                        i7 = 5;
                        break;
                    case 49:
                        strDecodeStringElement58 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 49);
                        i4 = 131072;
                        i9 |= i4;
                        Unit unit132222222222222222 = Unit.INSTANCE;
                        dexBridgeShadowTokenPairInfoVo2 = dexBridgeShadowTokenPairInfoVo4;
                        dexBridgeShadowTokenPairInfoVo4 = dexBridgeShadowTokenPairInfoVo2;
                        i8 = 8;
                        i5 = 11;
                        i6 = 10;
                        i7 = 5;
                        break;
                    case 50:
                        strDecodeStringElement57 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 50);
                        i4 = 262144;
                        i9 |= i4;
                        Unit unit1322222222222222222 = Unit.INSTANCE;
                        dexBridgeShadowTokenPairInfoVo2 = dexBridgeShadowTokenPairInfoVo4;
                        dexBridgeShadowTokenPairInfoVo4 = dexBridgeShadowTokenPairInfoVo2;
                        i8 = 8;
                        i5 = 11;
                        i6 = 10;
                        i7 = 5;
                        break;
                    case 51:
                        strDecodeStringElement56 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 51);
                        i4 = 524288;
                        i9 |= i4;
                        Unit unit13222222222222222222 = Unit.INSTANCE;
                        dexBridgeShadowTokenPairInfoVo2 = dexBridgeShadowTokenPairInfoVo4;
                        dexBridgeShadowTokenPairInfoVo4 = dexBridgeShadowTokenPairInfoVo2;
                        i8 = 8;
                        i5 = 11;
                        i6 = 10;
                        i7 = 5;
                        break;
                    case 52:
                        strDecodeStringElement55 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 52);
                        i4 = 1048576;
                        i9 |= i4;
                        Unit unit132222222222222222222 = Unit.INSTANCE;
                        dexBridgeShadowTokenPairInfoVo2 = dexBridgeShadowTokenPairInfoVo4;
                        dexBridgeShadowTokenPairInfoVo4 = dexBridgeShadowTokenPairInfoVo2;
                        i8 = 8;
                        i5 = 11;
                        i6 = 10;
                        i7 = 5;
                        break;
                    case 53:
                        strDecodeStringElement54 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 53);
                        i4 = 2097152;
                        i9 |= i4;
                        Unit unit1322222222222222222222 = Unit.INSTANCE;
                        dexBridgeShadowTokenPairInfoVo2 = dexBridgeShadowTokenPairInfoVo4;
                        dexBridgeShadowTokenPairInfoVo4 = dexBridgeShadowTokenPairInfoVo2;
                        i8 = 8;
                        i5 = 11;
                        i6 = 10;
                        i7 = 5;
                        break;
                    case 54:
                        strDecodeStringElement53 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 54);
                        i4 = 4194304;
                        i9 |= i4;
                        Unit unit13222222222222222222222 = Unit.INSTANCE;
                        dexBridgeShadowTokenPairInfoVo2 = dexBridgeShadowTokenPairInfoVo4;
                        dexBridgeShadowTokenPairInfoVo4 = dexBridgeShadowTokenPairInfoVo2;
                        i8 = 8;
                        i5 = 11;
                        i6 = 10;
                        i7 = 5;
                        break;
                    case 55:
                        strDecodeStringElement52 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 55);
                        i4 = 8388608;
                        i9 |= i4;
                        Unit unit132222222222222222222222 = Unit.INSTANCE;
                        dexBridgeShadowTokenPairInfoVo2 = dexBridgeShadowTokenPairInfoVo4;
                        dexBridgeShadowTokenPairInfoVo4 = dexBridgeShadowTokenPairInfoVo2;
                        i8 = 8;
                        i5 = 11;
                        i6 = 10;
                        i7 = 5;
                        break;
                    case 56:
                        relativeTransactionVO2 = (RelativeTransactionVO) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 56, RelativeTransactionVO$$serializer.INSTANCE, relativeTransactionVO2);
                        i4 = 16777216;
                        i9 |= i4;
                        Unit unit1322222222222222222222222 = Unit.INSTANCE;
                        dexBridgeShadowTokenPairInfoVo2 = dexBridgeShadowTokenPairInfoVo4;
                        dexBridgeShadowTokenPairInfoVo4 = dexBridgeShadowTokenPairInfoVo2;
                        i8 = 8;
                        i5 = 11;
                        i6 = 10;
                        i7 = 5;
                        break;
                    case 57:
                        strDecodeStringElement51 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 57);
                        i4 = MediaHttpDownloader.MAXIMUM_CHUNK_SIZE;
                        i9 |= i4;
                        Unit unit13222222222222222222222222 = Unit.INSTANCE;
                        dexBridgeShadowTokenPairInfoVo2 = dexBridgeShadowTokenPairInfoVo4;
                        dexBridgeShadowTokenPairInfoVo4 = dexBridgeShadowTokenPairInfoVo2;
                        i8 = 8;
                        i5 = 11;
                        i6 = 10;
                        i7 = 5;
                        break;
                    default:
                        throw new UnknownFieldException(iDecodeElementIndex);
                }
            }
            z = zDecodeBooleanElement18;
            z2 = zDecodeBooleanElement21;
            str = strDecodeStringElement63;
            str2 = strDecodeStringElement64;
            str3 = strDecodeStringElement66;
            str4 = strDecodeStringElement72;
            str5 = strDecodeStringElement73;
            str6 = strDecodeStringElement74;
            str7 = strDecodeStringElement75;
            str8 = strDecodeStringElement76;
            str9 = strDecodeStringElement77;
            str10 = strDecodeStringElement78;
            str11 = strDecodeStringElement79;
            str12 = strDecodeStringElement80;
            strDecodeStringElement = strDecodeStringElement81;
            str13 = strDecodeStringElement82;
            str14 = strDecodeStringElement83;
            str15 = strDecodeStringElement84;
            str16 = strDecodeStringElement86;
            relativeTransactionVO = relativeTransactionVO2;
            str17 = strDecodeStringElement50;
            strDecodeStringElement2 = strDecodeStringElement51;
            str18 = strDecodeStringElement57;
            dexBridgeShadowTokenPairInfoVo = dexBridgeShadowTokenPairInfoVo4;
            dexGasStationActivity = dexGasStationActivity3;
            z3 = zDecodeBooleanElement19;
            z4 = zDecodeBooleanElement20;
            str19 = strDecodeStringElement46;
            str20 = strDecodeStringElement60;
            str21 = strDecodeStringElement65;
            i = i10;
            z5 = zDecodeBooleanElement16;
            str22 = strDecodeStringElement58;
            str23 = strDecodeStringElement68;
            str24 = strDecodeStringElement47;
            str25 = strDecodeStringElement55;
            str26 = strDecodeStringElement59;
            z6 = zDecodeBooleanElement13;
            z7 = zDecodeBooleanElement15;
            str27 = strDecodeStringElement69;
            str28 = strDecodeStringElement71;
            str29 = strDecodeStringElement52;
            str30 = strDecodeStringElement54;
            z8 = zDecodeBooleanElement12;
            dexBridgeOrderInfoVo = dexBridgeOrderInfoVo3;
            z9 = zDecodeBooleanElement17;
            str31 = strDecodeStringElement67;
            str32 = strDecodeStringElement85;
            str33 = strDecodeStringElement56;
            z10 = zDecodeBooleanElement14;
            str34 = strDecodeStringElement70;
            str35 = strDecodeStringElement53;
            z11 = zDecodeBooleanElement22;
            i2 = i9;
            String str42 = strDecodeStringElement48;
            str36 = strDecodeStringElement44;
            str37 = strDecodeStringElement62;
            str38 = strDecodeStringElement49;
            str39 = strDecodeStringElement45;
            str40 = strDecodeStringElement61;
            str41 = str42;
        }
        compositeDecoderBeginStructure.endStructure(serialDescriptor);
        return new DexMultiChildOrderInfoVo(i, i2, dexBridgeOrderInfoVo, dexBridgeShadowTokenPairInfoVo, str32, str15, str14, str13, strDecodeStringElement, str12, str11, str10, str9, str8, str7, str6, str5, str4, str28, str34, str27, str23, str31, str3, z4, str21, str2, str, str37, str40, str20, str26, str36, str39, z3, str19, z, z9, z11, z8, z7, z10, dexGasStationActivity, str24, z2, z6, z5, str41, str38, str17, str16, str22, str18, str33, str25, str30, str35, str29, relativeTransactionVO, strDecodeStringElement2, (SerializationConstructorMarker) null);
    }

    /* JADX DEBUG: Method merged with bridge method: serialize(Lkotlinx/serialization/encoding/Encoder;Ljava/lang/Object;)V */
    @Override // kotlinx.serialization.SerializationStrategy
    public final void serialize(@NotNull Encoder encoder, @NotNull DexMultiChildOrderInfoVo dexMultiChildOrderInfoVo) {
        Intrinsics.checkNotNullParameter(encoder, "");
        Intrinsics.checkNotNullParameter(dexMultiChildOrderInfoVo, "");
        SerialDescriptor serialDescriptor = descriptor;
        CompositeEncoder compositeEncoderBeginStructure = encoder.beginStructure(serialDescriptor);
        DexMultiChildOrderInfoVo.write$Self$OKDex_dex_impl(dexMultiChildOrderInfoVo, compositeEncoderBeginStructure, serialDescriptor);
        compositeEncoderBeginStructure.endStructure(serialDescriptor);
    }
}
