package com.okinc.business.dexlogic.bean;

import com.google.api.client.googleapis.media.MediaHttpDownloader;
import com.okinc.business.dex.trade.core.domain.model.common.AccountInfo;
import com.okinc.business.dex.trade.core.domain.model.common.AccountInfo$$serializer;
import com.okinc.business.dexui.main.swap.widget.slippage.SlippageMode;
import com.okinc.p2p.api.OtcExtraKeys;
import java.util.List;
import kotlin.Unit;
import kotlin.jvm.internal.Intrinsics;
import kotlinx.serialization.KSerializer;
import kotlinx.serialization.UnknownFieldException;
import kotlinx.serialization.builtins.BuiltinSerializersKt;
import kotlinx.serialization.descriptors.SerialDescriptor;
import kotlinx.serialization.encoding.CompositeDecoder;
import kotlinx.serialization.encoding.CompositeEncoder;
import kotlinx.serialization.encoding.Decoder;
import kotlinx.serialization.encoding.Encoder;
import kotlinx.serialization.internal.BooleanSerializer;
import kotlinx.serialization.internal.GeneratedSerializer;
import kotlinx.serialization.internal.PluginGeneratedSerialDescriptor;
import kotlinx.serialization.internal.SerializationConstructorMarker;
import kotlinx.serialization.internal.StringSerializer;
import org.jetbrains.annotations.NotNull;

/* JADX INFO: loaded from: classes23.dex */
public final /* synthetic */ class QuoteCallDataReq$$serializer implements GeneratedSerializer<QuoteCallDataReq> {
    public static final int $stable;
    public static final QuoteCallDataReq$$serializer INSTANCE;
    private static final SerialDescriptor descriptor;

    /* JADX DEBUG: Don't trust debug lines info. Lines numbers was adjusted: min line is 0 */
    private QuoteCallDataReq$$serializer() {
    }

    /* JADX DEBUG: Don't trust debug lines info. Lines numbers was adjusted: min line is 0 */
    @Override // kotlinx.serialization.KSerializer, kotlinx.serialization.SerializationStrategy, kotlinx.serialization.DeserializationStrategy
    public final SerialDescriptor getDescriptor() {
        return descriptor;
    }

    static {
        QuoteCallDataReq$$serializer quoteCallDataReq$$serializer = new QuoteCallDataReq$$serializer();
        INSTANCE = quoteCallDataReq$$serializer;
        $stable = 8;
        PluginGeneratedSerialDescriptor pluginGeneratedSerialDescriptor = new PluginGeneratedSerialDescriptor("com.okinc.business.dexlogic.bean.QuoteCallDataReq", quoteCallDataReq$$serializer, 30);
        pluginGeneratedSerialDescriptor.addElement(OtcExtraKeys.AMOUNT, true);
        pluginGeneratedSerialDescriptor.addElement("slippage", true);
        pluginGeneratedSerialDescriptor.addElement("userWalletAddress", true);
        pluginGeneratedSerialDescriptor.addElement("chainId", true);
        pluginGeneratedSerialDescriptor.addElement("toChainId", true);
        pluginGeneratedSerialDescriptor.addElement("fromTokenAddress", true);
        pluginGeneratedSerialDescriptor.addElement("fromTokenDecimal", true);
        pluginGeneratedSerialDescriptor.addElement("toTokenAddress", true);
        pluginGeneratedSerialDescriptor.addElement("toTokenDecimal", true);
        pluginGeneratedSerialDescriptor.addElement("pmm", true);
        pluginGeneratedSerialDescriptor.addElement("receiveWalletAddress", true);
        pluginGeneratedSerialDescriptor.addElement("dexMultiMetaSaveOrderParam", true);
        pluginGeneratedSerialDescriptor.addElement("dexIds", true);
        pluginGeneratedSerialDescriptor.addElement("calldataType", true);
        pluginGeneratedSerialDescriptor.addElement("bridgeId", true);
        pluginGeneratedSerialDescriptor.addElement("defiPlatformId", true);
        pluginGeneratedSerialDescriptor.addElement("unsignedTx", true);
        pluginGeneratedSerialDescriptor.addElement("signature", true);
        pluginGeneratedSerialDescriptor.addElement("jitoEnable", true);
        pluginGeneratedSerialDescriptor.addElement("priorityFee", true);
        pluginGeneratedSerialDescriptor.addElement("customPriorityFee", true);
        pluginGeneratedSerialDescriptor.addElement("serviceFeeInfo", true);
        pluginGeneratedSerialDescriptor.addElement("refCode", true);
        pluginGeneratedSerialDescriptor.addElement("referralCommissionJsVersion", true);
        pluginGeneratedSerialDescriptor.addElement("mevInfo", true);
        pluginGeneratedSerialDescriptor.addElement("priorityFeeType", true);
        pluginGeneratedSerialDescriptor.addElement("gasPrice", true);
        pluginGeneratedSerialDescriptor.addElement("accountInfo", true);
        pluginGeneratedSerialDescriptor.addElement("routerModeType", true);
        pluginGeneratedSerialDescriptor.addElement("slippageMode", true);
        descriptor = pluginGeneratedSerialDescriptor;
    }

    @Override // kotlinx.serialization.internal.GeneratedSerializer
    public final KSerializer<?>[] childSerializers() {
        KSerializer[] kSerializerArr = QuoteCallDataReq.$childSerializers;
        StringSerializer stringSerializer = StringSerializer.INSTANCE;
        BooleanSerializer booleanSerializer = BooleanSerializer.INSTANCE;
        return new KSerializer[]{stringSerializer, BuiltinSerializersKt.getNullable(stringSerializer), stringSerializer, stringSerializer, stringSerializer, stringSerializer, stringSerializer, stringSerializer, stringSerializer, stringSerializer, BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(DexMultiMetaSaveOrderParam$$serializer.INSTANCE), BuiltinSerializersKt.getNullable(kSerializerArr[12]), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), booleanSerializer, BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(booleanSerializer), BuiltinSerializersKt.getNullable(ServiceFeeInfo$$serializer.INSTANCE), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(AccountInfo$$serializer.INSTANCE), BuiltinSerializersKt.getNullable(kSerializerArr[28]), BuiltinSerializersKt.getNullable(kSerializerArr[29])};
    }

    /* JADX DEBUG: Method merged with bridge method: deserialize(Lkotlinx/serialization/encoding/Decoder;)Ljava/lang/Object; */
    @Override // kotlinx.serialization.DeserializationStrategy
    public final QuoteCallDataReq deserialize(@NotNull Decoder decoder) {
        List list;
        String str;
        PresetRouteType presetRouteType;
        AccountInfo accountInfo;
        DexMultiMetaSaveOrderParam dexMultiMetaSaveOrderParam;
        String str2;
        ServiceFeeInfo serviceFeeInfo;
        String str3;
        SlippageMode slippageMode;
        String str4;
        String str5;
        String str6;
        String str7;
        String str8;
        boolean z;
        String str9;
        Boolean bool;
        String str10;
        String str11;
        String str12;
        String str13;
        String str14;
        String strDecodeStringElement;
        String str15;
        String str16;
        String str17;
        int i;
        String str18;
        String str19;
        String str20;
        String str21;
        String str22;
        String str23;
        String str24;
        String str25;
        String str26;
        List list2;
        String str27;
        String str28;
        DexMultiMetaSaveOrderParam dexMultiMetaSaveOrderParam2;
        KSerializer[] kSerializerArr;
        DexMultiMetaSaveOrderParam dexMultiMetaSaveOrderParam3;
        String str29;
        DexMultiMetaSaveOrderParam dexMultiMetaSaveOrderParam4;
        String str30;
        String str31;
        String str32;
        String str33;
        int i2;
        int i3;
        int i4;
        String str34;
        int i5;
        Intrinsics.checkNotNullParameter(decoder, "");
        SerialDescriptor serialDescriptor = descriptor;
        CompositeDecoder compositeDecoderBeginStructure = decoder.beginStructure(serialDescriptor);
        KSerializer[] kSerializerArr2 = QuoteCallDataReq.$childSerializers;
        if (compositeDecoderBeginStructure.decodeSequentially()) {
            String strDecodeStringElement2 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 0);
            StringSerializer stringSerializer = StringSerializer.INSTANCE;
            String str35 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 1, stringSerializer, null);
            String strDecodeStringElement3 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 2);
            strDecodeStringElement = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 3);
            String strDecodeStringElement4 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 4);
            String strDecodeStringElement5 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 5);
            String strDecodeStringElement6 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 6);
            String strDecodeStringElement7 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 7);
            String strDecodeStringElement8 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 8);
            String strDecodeStringElement9 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 9);
            String str36 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 10, stringSerializer, null);
            dexMultiMetaSaveOrderParam = (DexMultiMetaSaveOrderParam) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 11, DexMultiMetaSaveOrderParam$$serializer.INSTANCE, null);
            List list3 = (List) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 12, kSerializerArr2[12], null);
            String str37 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 13, stringSerializer, null);
            String str38 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 14, stringSerializer, null);
            String str39 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 15, stringSerializer, null);
            String str40 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 16, stringSerializer, null);
            String str41 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 17, stringSerializer, null);
            boolean zDecodeBooleanElement = compositeDecoderBeginStructure.decodeBooleanElement(serialDescriptor, 18);
            String str42 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 19, stringSerializer, null);
            Boolean bool2 = (Boolean) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 20, BooleanSerializer.INSTANCE, null);
            ServiceFeeInfo serviceFeeInfo2 = (ServiceFeeInfo) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 21, ServiceFeeInfo$$serializer.INSTANCE, null);
            String str43 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 22, stringSerializer, null);
            String str44 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 23, stringSerializer, null);
            String str45 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 24, stringSerializer, null);
            String str46 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 25, stringSerializer, null);
            String str47 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 26, stringSerializer, null);
            AccountInfo accountInfo2 = (AccountInfo) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 27, AccountInfo$$serializer.INSTANCE, null);
            PresetRouteType presetRouteType2 = (PresetRouteType) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 28, kSerializerArr2[28], null);
            slippageMode = (SlippageMode) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 29, kSerializerArr2[29], null);
            presetRouteType = presetRouteType2;
            str = str43;
            str10 = strDecodeStringElement8;
            accountInfo = accountInfo2;
            str18 = str44;
            str19 = str45;
            str3 = str46;
            str17 = str47;
            z = zDecodeBooleanElement;
            str7 = strDecodeStringElement9;
            str4 = str42;
            bool = bool2;
            serviceFeeInfo = serviceFeeInfo2;
            str5 = str41;
            i = 1073741823;
            str2 = str40;
            list = list3;
            str16 = str36;
            str13 = strDecodeStringElement5;
            str15 = strDecodeStringElement3;
            str11 = strDecodeStringElement7;
            str20 = strDecodeStringElement2;
            str9 = str37;
            str6 = str39;
            str12 = strDecodeStringElement6;
            str21 = str35;
            str14 = strDecodeStringElement4;
            str8 = str38;
        } else {
            int i6 = 29;
            boolean zDecodeBooleanElement2 = false;
            String str48 = null;
            String str49 = null;
            PresetRouteType presetRouteType3 = null;
            String str50 = null;
            ServiceFeeInfo serviceFeeInfo3 = null;
            String str51 = null;
            String str52 = null;
            String str53 = null;
            SlippageMode slippageMode2 = null;
            String strDecodeStringElement10 = null;
            String str54 = null;
            String str55 = null;
            String str56 = null;
            String str57 = null;
            List list4 = null;
            String str58 = null;
            String str59 = null;
            DexMultiMetaSaveOrderParam dexMultiMetaSaveOrderParam5 = null;
            Boolean bool3 = null;
            String strDecodeStringElement11 = null;
            String strDecodeStringElement12 = null;
            String strDecodeStringElement13 = null;
            String strDecodeStringElement14 = null;
            String strDecodeStringElement15 = null;
            String strDecodeStringElement16 = null;
            String strDecodeStringElement17 = null;
            String strDecodeStringElement18 = null;
            boolean z2 = true;
            AccountInfo accountInfo3 = null;
            String str60 = null;
            int i7 = 0;
            while (z2) {
                String str61 = str60;
                int iDecodeElementIndex = compositeDecoderBeginStructure.decodeElementIndex(serialDescriptor);
                switch (iDecodeElementIndex) {
                    case -1:
                        str22 = str48;
                        str23 = str54;
                        str24 = str55;
                        str25 = str56;
                        str26 = str57;
                        list2 = list4;
                        str27 = str58;
                        str28 = str59;
                        dexMultiMetaSaveOrderParam2 = dexMultiMetaSaveOrderParam5;
                        kSerializerArr = kSerializerArr2;
                        Unit unit = Unit.INSTANCE;
                        z2 = false;
                        str56 = str25;
                        dexMultiMetaSaveOrderParam3 = dexMultiMetaSaveOrderParam2;
                        str60 = str61;
                        str48 = str22;
                        str59 = str28;
                        str57 = str26;
                        str54 = str23;
                        str58 = str27;
                        list4 = list2;
                        dexMultiMetaSaveOrderParam5 = dexMultiMetaSaveOrderParam3;
                        kSerializerArr2 = kSerializerArr;
                        i6 = 29;
                        str55 = str24;
                        break;
                    case 0:
                        str22 = str48;
                        str23 = str54;
                        str24 = str55;
                        str25 = str56;
                        str26 = str57;
                        list2 = list4;
                        str27 = str58;
                        str28 = str59;
                        dexMultiMetaSaveOrderParam2 = dexMultiMetaSaveOrderParam5;
                        kSerializerArr = kSerializerArr2;
                        strDecodeStringElement18 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 0);
                        i7 |= 1;
                        Unit unit2 = Unit.INSTANCE;
                        str56 = str25;
                        dexMultiMetaSaveOrderParam3 = dexMultiMetaSaveOrderParam2;
                        str60 = str61;
                        str48 = str22;
                        str59 = str28;
                        str57 = str26;
                        str54 = str23;
                        str58 = str27;
                        list4 = list2;
                        dexMultiMetaSaveOrderParam5 = dexMultiMetaSaveOrderParam3;
                        kSerializerArr2 = kSerializerArr;
                        i6 = 29;
                        str55 = str24;
                        break;
                    case 1:
                        String str62 = str48;
                        str23 = str54;
                        str24 = str55;
                        str26 = str57;
                        list2 = list4;
                        str27 = str58;
                        str28 = str59;
                        kSerializerArr = kSerializerArr2;
                        String str63 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 1, StringSerializer.INSTANCE, str56);
                        int i8 = i7 | 2;
                        Unit unit3 = Unit.INSTANCE;
                        str56 = str63;
                        i7 = i8;
                        dexMultiMetaSaveOrderParam3 = dexMultiMetaSaveOrderParam5;
                        str60 = str61;
                        str48 = str62;
                        str59 = str28;
                        str57 = str26;
                        str54 = str23;
                        str58 = str27;
                        list4 = list2;
                        dexMultiMetaSaveOrderParam5 = dexMultiMetaSaveOrderParam3;
                        kSerializerArr2 = kSerializerArr;
                        i6 = 29;
                        str55 = str24;
                        break;
                    case 2:
                        str29 = str48;
                        str23 = str54;
                        str24 = str55;
                        str26 = str57;
                        list2 = list4;
                        str27 = str58;
                        str28 = str59;
                        dexMultiMetaSaveOrderParam4 = dexMultiMetaSaveOrderParam5;
                        kSerializerArr = kSerializerArr2;
                        str30 = str61;
                        strDecodeStringElement17 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 2);
                        i7 |= 4;
                        Unit unit4 = Unit.INSTANCE;
                        dexMultiMetaSaveOrderParam3 = dexMultiMetaSaveOrderParam4;
                        str48 = str29;
                        str60 = str30;
                        str59 = str28;
                        str57 = str26;
                        str54 = str23;
                        str58 = str27;
                        list4 = list2;
                        dexMultiMetaSaveOrderParam5 = dexMultiMetaSaveOrderParam3;
                        kSerializerArr2 = kSerializerArr;
                        i6 = 29;
                        str55 = str24;
                        break;
                    case 3:
                        str29 = str48;
                        str23 = str54;
                        str24 = str55;
                        str26 = str57;
                        list2 = list4;
                        str27 = str58;
                        str28 = str59;
                        dexMultiMetaSaveOrderParam4 = dexMultiMetaSaveOrderParam5;
                        kSerializerArr = kSerializerArr2;
                        str30 = str61;
                        strDecodeStringElement16 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 3);
                        i7 |= 8;
                        Unit unit5 = Unit.INSTANCE;
                        dexMultiMetaSaveOrderParam3 = dexMultiMetaSaveOrderParam4;
                        str48 = str29;
                        str60 = str30;
                        str59 = str28;
                        str57 = str26;
                        str54 = str23;
                        str58 = str27;
                        list4 = list2;
                        dexMultiMetaSaveOrderParam5 = dexMultiMetaSaveOrderParam3;
                        kSerializerArr2 = kSerializerArr;
                        i6 = 29;
                        str55 = str24;
                        break;
                    case 4:
                        str29 = str48;
                        str23 = str54;
                        str24 = str55;
                        str26 = str57;
                        list2 = list4;
                        str27 = str58;
                        str28 = str59;
                        dexMultiMetaSaveOrderParam4 = dexMultiMetaSaveOrderParam5;
                        kSerializerArr = kSerializerArr2;
                        str30 = str61;
                        strDecodeStringElement15 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 4);
                        i7 |= 16;
                        Unit unit6 = Unit.INSTANCE;
                        dexMultiMetaSaveOrderParam3 = dexMultiMetaSaveOrderParam4;
                        str48 = str29;
                        str60 = str30;
                        str59 = str28;
                        str57 = str26;
                        str54 = str23;
                        str58 = str27;
                        list4 = list2;
                        dexMultiMetaSaveOrderParam5 = dexMultiMetaSaveOrderParam3;
                        kSerializerArr2 = kSerializerArr;
                        i6 = 29;
                        str55 = str24;
                        break;
                    case 5:
                        str29 = str48;
                        str23 = str54;
                        str24 = str55;
                        str26 = str57;
                        list2 = list4;
                        str27 = str58;
                        str28 = str59;
                        dexMultiMetaSaveOrderParam4 = dexMultiMetaSaveOrderParam5;
                        kSerializerArr = kSerializerArr2;
                        str30 = str61;
                        strDecodeStringElement14 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 5);
                        i7 |= 32;
                        Unit unit7 = Unit.INSTANCE;
                        dexMultiMetaSaveOrderParam3 = dexMultiMetaSaveOrderParam4;
                        str48 = str29;
                        str60 = str30;
                        str59 = str28;
                        str57 = str26;
                        str54 = str23;
                        str58 = str27;
                        list4 = list2;
                        dexMultiMetaSaveOrderParam5 = dexMultiMetaSaveOrderParam3;
                        kSerializerArr2 = kSerializerArr;
                        i6 = 29;
                        str55 = str24;
                        break;
                    case 6:
                        str29 = str48;
                        str23 = str54;
                        str24 = str55;
                        str26 = str57;
                        list2 = list4;
                        str27 = str58;
                        str28 = str59;
                        dexMultiMetaSaveOrderParam4 = dexMultiMetaSaveOrderParam5;
                        kSerializerArr = kSerializerArr2;
                        str30 = str61;
                        strDecodeStringElement13 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 6);
                        i7 |= 64;
                        Unit unit8 = Unit.INSTANCE;
                        dexMultiMetaSaveOrderParam3 = dexMultiMetaSaveOrderParam4;
                        str48 = str29;
                        str60 = str30;
                        str59 = str28;
                        str57 = str26;
                        str54 = str23;
                        str58 = str27;
                        list4 = list2;
                        dexMultiMetaSaveOrderParam5 = dexMultiMetaSaveOrderParam3;
                        kSerializerArr2 = kSerializerArr;
                        i6 = 29;
                        str55 = str24;
                        break;
                    case 7:
                        str29 = str48;
                        str23 = str54;
                        str24 = str55;
                        str26 = str57;
                        list2 = list4;
                        str27 = str58;
                        str28 = str59;
                        dexMultiMetaSaveOrderParam4 = dexMultiMetaSaveOrderParam5;
                        kSerializerArr = kSerializerArr2;
                        str30 = str61;
                        strDecodeStringElement12 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 7);
                        i7 |= 128;
                        Unit unit9 = Unit.INSTANCE;
                        dexMultiMetaSaveOrderParam3 = dexMultiMetaSaveOrderParam4;
                        str48 = str29;
                        str60 = str30;
                        str59 = str28;
                        str57 = str26;
                        str54 = str23;
                        str58 = str27;
                        list4 = list2;
                        dexMultiMetaSaveOrderParam5 = dexMultiMetaSaveOrderParam3;
                        kSerializerArr2 = kSerializerArr;
                        i6 = 29;
                        str55 = str24;
                        break;
                    case 8:
                        str29 = str48;
                        str23 = str54;
                        str24 = str55;
                        str26 = str57;
                        list2 = list4;
                        str27 = str58;
                        str28 = str59;
                        dexMultiMetaSaveOrderParam4 = dexMultiMetaSaveOrderParam5;
                        kSerializerArr = kSerializerArr2;
                        str30 = str61;
                        strDecodeStringElement11 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 8);
                        i7 |= 256;
                        Unit unit10 = Unit.INSTANCE;
                        dexMultiMetaSaveOrderParam3 = dexMultiMetaSaveOrderParam4;
                        str48 = str29;
                        str60 = str30;
                        str59 = str28;
                        str57 = str26;
                        str54 = str23;
                        str58 = str27;
                        list4 = list2;
                        dexMultiMetaSaveOrderParam5 = dexMultiMetaSaveOrderParam3;
                        kSerializerArr2 = kSerializerArr;
                        i6 = 29;
                        str55 = str24;
                        break;
                    case 9:
                        str29 = str48;
                        str23 = str54;
                        str24 = str55;
                        str26 = str57;
                        list2 = list4;
                        str27 = str58;
                        str28 = str59;
                        dexMultiMetaSaveOrderParam4 = dexMultiMetaSaveOrderParam5;
                        kSerializerArr = kSerializerArr2;
                        str30 = str61;
                        strDecodeStringElement10 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 9);
                        i7 |= 512;
                        Unit unit11 = Unit.INSTANCE;
                        dexMultiMetaSaveOrderParam3 = dexMultiMetaSaveOrderParam4;
                        str48 = str29;
                        str60 = str30;
                        str59 = str28;
                        str57 = str26;
                        str54 = str23;
                        str58 = str27;
                        list4 = list2;
                        dexMultiMetaSaveOrderParam5 = dexMultiMetaSaveOrderParam3;
                        kSerializerArr2 = kSerializerArr;
                        i6 = 29;
                        str55 = str24;
                        break;
                    case 10:
                        str29 = str48;
                        str23 = str54;
                        String str64 = str55;
                        str26 = str57;
                        list2 = list4;
                        str27 = str58;
                        str28 = str59;
                        dexMultiMetaSaveOrderParam4 = dexMultiMetaSaveOrderParam5;
                        kSerializerArr = kSerializerArr2;
                        str24 = str64;
                        str30 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 10, StringSerializer.INSTANCE, str61);
                        int i9 = i7 | 1024;
                        Unit unit12 = Unit.INSTANCE;
                        i7 = i9;
                        dexMultiMetaSaveOrderParam3 = dexMultiMetaSaveOrderParam4;
                        str48 = str29;
                        str60 = str30;
                        str59 = str28;
                        str57 = str26;
                        str54 = str23;
                        str58 = str27;
                        list4 = list2;
                        dexMultiMetaSaveOrderParam5 = dexMultiMetaSaveOrderParam3;
                        kSerializerArr2 = kSerializerArr;
                        i6 = 29;
                        str55 = str24;
                        break;
                    case 11:
                        str31 = str48;
                        str23 = str54;
                        str32 = str55;
                        str26 = str57;
                        str27 = str58;
                        kSerializerArr = kSerializerArr2;
                        list2 = list4;
                        dexMultiMetaSaveOrderParam5 = (DexMultiMetaSaveOrderParam) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 11, DexMultiMetaSaveOrderParam$$serializer.INSTANCE, dexMultiMetaSaveOrderParam5);
                        int i10 = i7 | 2048;
                        Unit unit13 = Unit.INSTANCE;
                        i7 = i10;
                        str34 = str32;
                        str48 = str31;
                        str24 = str34;
                        str28 = str59;
                        dexMultiMetaSaveOrderParam3 = dexMultiMetaSaveOrderParam5;
                        str60 = str61;
                        str59 = str28;
                        str57 = str26;
                        str54 = str23;
                        str58 = str27;
                        list4 = list2;
                        dexMultiMetaSaveOrderParam5 = dexMultiMetaSaveOrderParam3;
                        kSerializerArr2 = kSerializerArr;
                        i6 = 29;
                        str55 = str24;
                        break;
                    case 12:
                        str31 = str48;
                        str23 = str54;
                        str32 = str55;
                        str26 = str57;
                        str27 = str58;
                        kSerializerArr = kSerializerArr2;
                        List list5 = (List) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 12, kSerializerArr2[12], list4);
                        Unit unit14 = Unit.INSTANCE;
                        i7 |= 4096;
                        list2 = list5;
                        str34 = str32;
                        str48 = str31;
                        str24 = str34;
                        str28 = str59;
                        dexMultiMetaSaveOrderParam3 = dexMultiMetaSaveOrderParam5;
                        str60 = str61;
                        str59 = str28;
                        str57 = str26;
                        str54 = str23;
                        str58 = str27;
                        list4 = list2;
                        dexMultiMetaSaveOrderParam5 = dexMultiMetaSaveOrderParam3;
                        kSerializerArr2 = kSerializerArr;
                        i6 = 29;
                        str55 = str24;
                        break;
                    case 13:
                        str31 = str48;
                        str23 = str54;
                        str26 = str57;
                        str33 = str59;
                        str27 = str58;
                        str55 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 13, StringSerializer.INSTANCE, str55);
                        i2 = i7 | 8192;
                        Unit unit15 = Unit.INSTANCE;
                        i7 = i2;
                        str59 = str33;
                        str32 = str55;
                        list2 = list4;
                        kSerializerArr = kSerializerArr2;
                        str34 = str32;
                        str48 = str31;
                        str24 = str34;
                        str28 = str59;
                        dexMultiMetaSaveOrderParam3 = dexMultiMetaSaveOrderParam5;
                        str60 = str61;
                        str59 = str28;
                        str57 = str26;
                        str54 = str23;
                        str58 = str27;
                        list4 = list2;
                        dexMultiMetaSaveOrderParam5 = dexMultiMetaSaveOrderParam3;
                        kSerializerArr2 = kSerializerArr;
                        i6 = 29;
                        str55 = str24;
                        break;
                    case 14:
                        str31 = str48;
                        str26 = str57;
                        str23 = str54;
                        str58 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 14, StringSerializer.INSTANCE, str58);
                        int i11 = i7 | 16384;
                        Unit unit16 = Unit.INSTANCE;
                        i7 = i11;
                        str32 = str55;
                        list2 = list4;
                        str27 = str58;
                        kSerializerArr = kSerializerArr2;
                        str34 = str32;
                        str48 = str31;
                        str24 = str34;
                        str28 = str59;
                        dexMultiMetaSaveOrderParam3 = dexMultiMetaSaveOrderParam5;
                        str60 = str61;
                        str59 = str28;
                        str57 = str26;
                        str54 = str23;
                        str58 = str27;
                        list4 = list2;
                        dexMultiMetaSaveOrderParam5 = dexMultiMetaSaveOrderParam3;
                        kSerializerArr2 = kSerializerArr;
                        i6 = 29;
                        str55 = str24;
                        break;
                    case 15:
                        str31 = str48;
                        str26 = str57;
                        str54 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 15, StringSerializer.INSTANCE, str54);
                        int i12 = 32768 | i7;
                        Unit unit17 = Unit.INSTANCE;
                        i7 = i12;
                        str23 = str54;
                        str32 = str55;
                        list2 = list4;
                        str27 = str58;
                        kSerializerArr = kSerializerArr2;
                        str34 = str32;
                        str48 = str31;
                        str24 = str34;
                        str28 = str59;
                        dexMultiMetaSaveOrderParam3 = dexMultiMetaSaveOrderParam5;
                        str60 = str61;
                        str59 = str28;
                        str57 = str26;
                        str54 = str23;
                        str58 = str27;
                        list4 = list2;
                        dexMultiMetaSaveOrderParam5 = dexMultiMetaSaveOrderParam3;
                        kSerializerArr2 = kSerializerArr;
                        i6 = 29;
                        str55 = str24;
                        break;
                    case 16:
                        str31 = str48;
                        str50 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 16, StringSerializer.INSTANCE, str50);
                        i7 |= 65536;
                        Unit unit18 = Unit.INSTANCE;
                        str26 = str57;
                        str23 = str54;
                        str32 = str55;
                        list2 = list4;
                        str27 = str58;
                        kSerializerArr = kSerializerArr2;
                        str34 = str32;
                        str48 = str31;
                        str24 = str34;
                        str28 = str59;
                        dexMultiMetaSaveOrderParam3 = dexMultiMetaSaveOrderParam5;
                        str60 = str61;
                        str59 = str28;
                        str57 = str26;
                        str54 = str23;
                        str58 = str27;
                        list4 = list2;
                        dexMultiMetaSaveOrderParam5 = dexMultiMetaSaveOrderParam3;
                        kSerializerArr2 = kSerializerArr;
                        i6 = 29;
                        str55 = str24;
                        break;
                    case 17:
                        str31 = str48;
                        str33 = str59;
                        str57 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 17, StringSerializer.INSTANCE, str57);
                        i3 = 131072;
                        i2 = i7 | i3;
                        str23 = str54;
                        str26 = str57;
                        str27 = str58;
                        Unit unit152 = Unit.INSTANCE;
                        i7 = i2;
                        str59 = str33;
                        str32 = str55;
                        list2 = list4;
                        kSerializerArr = kSerializerArr2;
                        str34 = str32;
                        str48 = str31;
                        str24 = str34;
                        str28 = str59;
                        dexMultiMetaSaveOrderParam3 = dexMultiMetaSaveOrderParam5;
                        str60 = str61;
                        str59 = str28;
                        str57 = str26;
                        str54 = str23;
                        str58 = str27;
                        list4 = list2;
                        dexMultiMetaSaveOrderParam5 = dexMultiMetaSaveOrderParam3;
                        kSerializerArr2 = kSerializerArr;
                        i6 = 29;
                        str55 = str24;
                        break;
                    case 18:
                        str31 = str48;
                        zDecodeBooleanElement2 = compositeDecoderBeginStructure.decodeBooleanElement(serialDescriptor, 18);
                        i3 = 262144;
                        str33 = str59;
                        i2 = i7 | i3;
                        str23 = str54;
                        str26 = str57;
                        str27 = str58;
                        Unit unit1522 = Unit.INSTANCE;
                        i7 = i2;
                        str59 = str33;
                        str32 = str55;
                        list2 = list4;
                        kSerializerArr = kSerializerArr2;
                        str34 = str32;
                        str48 = str31;
                        str24 = str34;
                        str28 = str59;
                        dexMultiMetaSaveOrderParam3 = dexMultiMetaSaveOrderParam5;
                        str60 = str61;
                        str59 = str28;
                        str57 = str26;
                        str54 = str23;
                        str58 = str27;
                        list4 = list2;
                        dexMultiMetaSaveOrderParam5 = dexMultiMetaSaveOrderParam3;
                        kSerializerArr2 = kSerializerArr;
                        i6 = 29;
                        str55 = str24;
                        break;
                    case 19:
                        str31 = str48;
                        str59 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 19, StringSerializer.INSTANCE, str59);
                        i4 = 524288;
                        Unit unit19 = Unit.INSTANCE;
                        i7 = i4 | i7;
                        str23 = str54;
                        str32 = str55;
                        str26 = str57;
                        list2 = list4;
                        str27 = str58;
                        kSerializerArr = kSerializerArr2;
                        str34 = str32;
                        str48 = str31;
                        str24 = str34;
                        str28 = str59;
                        dexMultiMetaSaveOrderParam3 = dexMultiMetaSaveOrderParam5;
                        str60 = str61;
                        str59 = str28;
                        str57 = str26;
                        str54 = str23;
                        str58 = str27;
                        list4 = list2;
                        dexMultiMetaSaveOrderParam5 = dexMultiMetaSaveOrderParam3;
                        kSerializerArr2 = kSerializerArr;
                        i6 = 29;
                        str55 = str24;
                        break;
                    case 20:
                        str31 = str48;
                        bool3 = (Boolean) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 20, BooleanSerializer.INSTANCE, bool3);
                        i4 = 1048576;
                        Unit unit192 = Unit.INSTANCE;
                        i7 = i4 | i7;
                        str23 = str54;
                        str32 = str55;
                        str26 = str57;
                        list2 = list4;
                        str27 = str58;
                        kSerializerArr = kSerializerArr2;
                        str34 = str32;
                        str48 = str31;
                        str24 = str34;
                        str28 = str59;
                        dexMultiMetaSaveOrderParam3 = dexMultiMetaSaveOrderParam5;
                        str60 = str61;
                        str59 = str28;
                        str57 = str26;
                        str54 = str23;
                        str58 = str27;
                        list4 = list2;
                        dexMultiMetaSaveOrderParam5 = dexMultiMetaSaveOrderParam3;
                        kSerializerArr2 = kSerializerArr;
                        i6 = 29;
                        str55 = str24;
                        break;
                    case 21:
                        serviceFeeInfo3 = (ServiceFeeInfo) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 21, ServiceFeeInfo$$serializer.INSTANCE, serviceFeeInfo3);
                        i7 |= 2097152;
                        Unit unit20 = Unit.INSTANCE;
                        str23 = str54;
                        str34 = str55;
                        str26 = str57;
                        list2 = list4;
                        str27 = str58;
                        kSerializerArr = kSerializerArr2;
                        str24 = str34;
                        str28 = str59;
                        dexMultiMetaSaveOrderParam3 = dexMultiMetaSaveOrderParam5;
                        str60 = str61;
                        str59 = str28;
                        str57 = str26;
                        str54 = str23;
                        str58 = str27;
                        list4 = list2;
                        dexMultiMetaSaveOrderParam5 = dexMultiMetaSaveOrderParam3;
                        kSerializerArr2 = kSerializerArr;
                        i6 = 29;
                        str55 = str24;
                        break;
                    case 22:
                        str49 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 22, StringSerializer.INSTANCE, str49);
                        i5 = 4194304;
                        int i13 = i5 | i7;
                        Unit unit21 = Unit.INSTANCE;
                        i7 = i13;
                        str23 = str54;
                        str34 = str55;
                        str26 = str57;
                        list2 = list4;
                        str27 = str58;
                        kSerializerArr = kSerializerArr2;
                        str24 = str34;
                        str28 = str59;
                        dexMultiMetaSaveOrderParam3 = dexMultiMetaSaveOrderParam5;
                        str60 = str61;
                        str59 = str28;
                        str57 = str26;
                        str54 = str23;
                        str58 = str27;
                        list4 = list2;
                        dexMultiMetaSaveOrderParam5 = dexMultiMetaSaveOrderParam3;
                        kSerializerArr2 = kSerializerArr;
                        i6 = 29;
                        str55 = str24;
                        break;
                    case 23:
                        str51 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 23, StringSerializer.INSTANCE, str51);
                        i5 = 8388608;
                        int i132 = i5 | i7;
                        Unit unit212 = Unit.INSTANCE;
                        i7 = i132;
                        str23 = str54;
                        str34 = str55;
                        str26 = str57;
                        list2 = list4;
                        str27 = str58;
                        kSerializerArr = kSerializerArr2;
                        str24 = str34;
                        str28 = str59;
                        dexMultiMetaSaveOrderParam3 = dexMultiMetaSaveOrderParam5;
                        str60 = str61;
                        str59 = str28;
                        str57 = str26;
                        str54 = str23;
                        str58 = str27;
                        list4 = list2;
                        dexMultiMetaSaveOrderParam5 = dexMultiMetaSaveOrderParam3;
                        kSerializerArr2 = kSerializerArr;
                        i6 = 29;
                        str55 = str24;
                        break;
                    case 24:
                        str52 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 24, StringSerializer.INSTANCE, str52);
                        i5 = 16777216;
                        int i1322 = i5 | i7;
                        Unit unit2122 = Unit.INSTANCE;
                        i7 = i1322;
                        str23 = str54;
                        str34 = str55;
                        str26 = str57;
                        list2 = list4;
                        str27 = str58;
                        kSerializerArr = kSerializerArr2;
                        str24 = str34;
                        str28 = str59;
                        dexMultiMetaSaveOrderParam3 = dexMultiMetaSaveOrderParam5;
                        str60 = str61;
                        str59 = str28;
                        str57 = str26;
                        str54 = str23;
                        str58 = str27;
                        list4 = list2;
                        dexMultiMetaSaveOrderParam5 = dexMultiMetaSaveOrderParam3;
                        kSerializerArr2 = kSerializerArr;
                        i6 = 29;
                        str55 = str24;
                        break;
                    case 25:
                        str53 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 25, StringSerializer.INSTANCE, str53);
                        i5 = MediaHttpDownloader.MAXIMUM_CHUNK_SIZE;
                        int i13222 = i5 | i7;
                        Unit unit21222 = Unit.INSTANCE;
                        i7 = i13222;
                        str23 = str54;
                        str34 = str55;
                        str26 = str57;
                        list2 = list4;
                        str27 = str58;
                        kSerializerArr = kSerializerArr2;
                        str24 = str34;
                        str28 = str59;
                        dexMultiMetaSaveOrderParam3 = dexMultiMetaSaveOrderParam5;
                        str60 = str61;
                        str59 = str28;
                        str57 = str26;
                        str54 = str23;
                        str58 = str27;
                        list4 = list2;
                        dexMultiMetaSaveOrderParam5 = dexMultiMetaSaveOrderParam3;
                        kSerializerArr2 = kSerializerArr;
                        i6 = 29;
                        str55 = str24;
                        break;
                    case 26:
                        str48 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 26, StringSerializer.INSTANCE, str48);
                        i5 = 67108864;
                        int i132222 = i5 | i7;
                        Unit unit212222 = Unit.INSTANCE;
                        i7 = i132222;
                        str23 = str54;
                        str34 = str55;
                        str26 = str57;
                        list2 = list4;
                        str27 = str58;
                        kSerializerArr = kSerializerArr2;
                        str24 = str34;
                        str28 = str59;
                        dexMultiMetaSaveOrderParam3 = dexMultiMetaSaveOrderParam5;
                        str60 = str61;
                        str59 = str28;
                        str57 = str26;
                        str54 = str23;
                        str58 = str27;
                        list4 = list2;
                        dexMultiMetaSaveOrderParam5 = dexMultiMetaSaveOrderParam3;
                        kSerializerArr2 = kSerializerArr;
                        i6 = 29;
                        str55 = str24;
                        break;
                    case 27:
                        accountInfo3 = (AccountInfo) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 27, AccountInfo$$serializer.INSTANCE, accountInfo3);
                        i5 = 134217728;
                        int i1322222 = i5 | i7;
                        Unit unit2122222 = Unit.INSTANCE;
                        i7 = i1322222;
                        str23 = str54;
                        str34 = str55;
                        str26 = str57;
                        list2 = list4;
                        str27 = str58;
                        kSerializerArr = kSerializerArr2;
                        str24 = str34;
                        str28 = str59;
                        dexMultiMetaSaveOrderParam3 = dexMultiMetaSaveOrderParam5;
                        str60 = str61;
                        str59 = str28;
                        str57 = str26;
                        str54 = str23;
                        str58 = str27;
                        list4 = list2;
                        dexMultiMetaSaveOrderParam5 = dexMultiMetaSaveOrderParam3;
                        kSerializerArr2 = kSerializerArr;
                        i6 = 29;
                        str55 = str24;
                        break;
                    case 28:
                        presetRouteType3 = (PresetRouteType) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 28, kSerializerArr2[28], presetRouteType3);
                        i5 = 268435456;
                        int i13222222 = i5 | i7;
                        Unit unit21222222 = Unit.INSTANCE;
                        i7 = i13222222;
                        str23 = str54;
                        str34 = str55;
                        str26 = str57;
                        list2 = list4;
                        str27 = str58;
                        kSerializerArr = kSerializerArr2;
                        str24 = str34;
                        str28 = str59;
                        dexMultiMetaSaveOrderParam3 = dexMultiMetaSaveOrderParam5;
                        str60 = str61;
                        str59 = str28;
                        str57 = str26;
                        str54 = str23;
                        str58 = str27;
                        list4 = list2;
                        dexMultiMetaSaveOrderParam5 = dexMultiMetaSaveOrderParam3;
                        kSerializerArr2 = kSerializerArr;
                        i6 = 29;
                        str55 = str24;
                        break;
                    case 29:
                        slippageMode2 = (SlippageMode) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, i6, kSerializerArr2[i6], slippageMode2);
                        i7 |= 536870912;
                        Unit unit22 = Unit.INSTANCE;
                        str23 = str54;
                        str34 = str55;
                        str26 = str57;
                        list2 = list4;
                        str27 = str58;
                        kSerializerArr = kSerializerArr2;
                        str24 = str34;
                        str28 = str59;
                        dexMultiMetaSaveOrderParam3 = dexMultiMetaSaveOrderParam5;
                        str60 = str61;
                        str59 = str28;
                        str57 = str26;
                        str54 = str23;
                        str58 = str27;
                        list4 = list2;
                        dexMultiMetaSaveOrderParam5 = dexMultiMetaSaveOrderParam3;
                        kSerializerArr2 = kSerializerArr;
                        i6 = 29;
                        str55 = str24;
                        break;
                    default:
                        throw new UnknownFieldException(iDecodeElementIndex);
                }
            }
            String str65 = str48;
            String str66 = str54;
            String str67 = str56;
            String str68 = str57;
            list = list4;
            str = str49;
            presetRouteType = presetRouteType3;
            accountInfo = accountInfo3;
            dexMultiMetaSaveOrderParam = dexMultiMetaSaveOrderParam5;
            str2 = str50;
            serviceFeeInfo = serviceFeeInfo3;
            str3 = str53;
            slippageMode = slippageMode2;
            str4 = str59;
            str5 = str68;
            str6 = str66;
            str7 = strDecodeStringElement10;
            str8 = str58;
            z = zDecodeBooleanElement2;
            str9 = str55;
            bool = bool3;
            str10 = strDecodeStringElement11;
            str11 = strDecodeStringElement12;
            str12 = strDecodeStringElement13;
            str13 = strDecodeStringElement14;
            str14 = strDecodeStringElement15;
            strDecodeStringElement = strDecodeStringElement16;
            str15 = strDecodeStringElement17;
            str16 = str60;
            str17 = str65;
            i = i7;
            str18 = str51;
            str19 = str52;
            str20 = strDecodeStringElement18;
            str21 = str67;
        }
        compositeDecoderBeginStructure.endStructure(serialDescriptor);
        return new QuoteCallDataReq(i, str20, str21, str15, strDecodeStringElement, str14, str13, str12, str11, str10, str7, str16, dexMultiMetaSaveOrderParam, list, str9, str8, str6, str2, str5, z, str4, bool, serviceFeeInfo, str, str18, str19, str3, str17, accountInfo, presetRouteType, slippageMode, (SerializationConstructorMarker) null);
    }

    /* JADX DEBUG: Method merged with bridge method: serialize(Lkotlinx/serialization/encoding/Encoder;Ljava/lang/Object;)V */
    @Override // kotlinx.serialization.SerializationStrategy
    public final void serialize(@NotNull Encoder encoder, @NotNull QuoteCallDataReq quoteCallDataReq) {
        Intrinsics.checkNotNullParameter(encoder, "");
        Intrinsics.checkNotNullParameter(quoteCallDataReq, "");
        SerialDescriptor serialDescriptor = descriptor;
        CompositeEncoder compositeEncoderBeginStructure = encoder.beginStructure(serialDescriptor);
        QuoteCallDataReq.write$Self$OKDex_dex_impl(quoteCallDataReq, compositeEncoderBeginStructure, serialDescriptor);
        compositeEncoderBeginStructure.endStructure(serialDescriptor);
    }
}
