package com.okinc.business.dexlogic.bean;

import com.google.api.client.googleapis.media.MediaHttpDownloader;
import com.okinc.business.dex.trade.core.domain.model.common.AccountInfo;
import com.okinc.business.dex.trade.core.domain.model.common.AccountInfo$$serializer;
import com.okinc.business.dex.trade.core.domain.model.common.TeeSaStatus;
import com.okinc.business.dexlogic.bean.TransactionBean;
import com.okinc.business.dexlogic.main.swap.trade.transaction.base.bean.OrderIdTypeData;
import com.okinc.business.dexlogic.main.swap.trade.transaction.base.bean.OrderIdTypeData$$serializer;
import com.okinc.business.dexui.main.swap.widget.slippage.SlippageMode;
import kotlin.Unit;
import kotlin.jvm.internal.Intrinsics;
import kotlinx.serialization.KSerializer;
import kotlinx.serialization.UnknownFieldException;
import kotlinx.serialization.builtins.BuiltinSerializersKt;
import kotlinx.serialization.descriptors.SerialDescriptor;
import kotlinx.serialization.encoding.CompositeDecoder;
import kotlinx.serialization.encoding.CompositeEncoder;
import kotlinx.serialization.encoding.Decoder;
import kotlinx.serialization.encoding.Encoder;
import kotlinx.serialization.internal.BooleanSerializer;
import kotlinx.serialization.internal.GeneratedSerializer;
import kotlinx.serialization.internal.IntSerializer;
import kotlinx.serialization.internal.LongSerializer;
import kotlinx.serialization.internal.PluginGeneratedSerialDescriptor;
import kotlinx.serialization.internal.SerializationConstructorMarker;
import kotlinx.serialization.internal.StringSerializer;
import org.jetbrains.annotations.NotNull;

/* JADX INFO: loaded from: classes15.dex */
public final /* synthetic */ class TransactionBean$$serializer implements GeneratedSerializer<TransactionBean> {
    public static final int $stable;
    public static final TransactionBean$$serializer INSTANCE;
    private static final SerialDescriptor descriptor;

    /* JADX DEBUG: Don't trust debug lines info. Lines numbers was adjusted: min line is 0 */
    private TransactionBean$$serializer() {
    }

    /* JADX DEBUG: Don't trust debug lines info. Lines numbers was adjusted: min line is 0 */
    @Override // kotlinx.serialization.KSerializer, kotlinx.serialization.SerializationStrategy, kotlinx.serialization.DeserializationStrategy
    public final SerialDescriptor getDescriptor() {
        return descriptor;
    }

    static {
        TransactionBean$$serializer transactionBean$$serializer = new TransactionBean$$serializer();
        INSTANCE = transactionBean$$serializer;
        $stable = 8;
        PluginGeneratedSerialDescriptor pluginGeneratedSerialDescriptor = new PluginGeneratedSerialDescriptor("com.okinc.business.dexlogic.bean.TransactionBean", transactionBean$$serializer, 33);
        pluginGeneratedSerialDescriptor.addElement("receiveWalletAddress", true);
        pluginGeneratedSerialDescriptor.addElement("spSlipPage", true);
        pluginGeneratedSerialDescriptor.addElement("isCustomSlippage", true);
        pluginGeneratedSerialDescriptor.addElement("fromCoinAmountBalance", true);
        pluginGeneratedSerialDescriptor.addElement("reservedAmount", true);
        pluginGeneratedSerialDescriptor.addElement("quotePriceRes", true);
        pluginGeneratedSerialDescriptor.addElement("balanceBracket", true);
        pluginGeneratedSerialDescriptor.addElement("gasPriceRate", true);
        pluginGeneratedSerialDescriptor.addElement("bridgeSelection", true);
        pluginGeneratedSerialDescriptor.addElement("transactionType", true);
        pluginGeneratedSerialDescriptor.addElement("orderIdTypeData", true);
        pluginGeneratedSerialDescriptor.addElement("transactionString", true);
        pluginGeneratedSerialDescriptor.addElement("signedTx", true);
        pluginGeneratedSerialDescriptor.addElement("walletAddressType", true);
        pluginGeneratedSerialDescriptor.addElement("openMev", true);
        pluginGeneratedSerialDescriptor.addElement("supportMev", true);
        pluginGeneratedSerialDescriptor.addElement("expireTime", true);
        pluginGeneratedSerialDescriptor.addElement("unSignedTx", true);
        pluginGeneratedSerialDescriptor.addElement("swapType", true);
        pluginGeneratedSerialDescriptor.addElement("callData", true);
        pluginGeneratedSerialDescriptor.addElement("serviceFeeInfo", true);
        pluginGeneratedSerialDescriptor.addElement("slippageMode", true);
        pluginGeneratedSerialDescriptor.addElement("maxSlippage", true);
        pluginGeneratedSerialDescriptor.addElement("slippageFeeType", true);
        pluginGeneratedSerialDescriptor.addElement("priorityFee", true);
        pluginGeneratedSerialDescriptor.addElement("customPriorityFee", true);
        pluginGeneratedSerialDescriptor.addElement("priorityFeeType", true);
        pluginGeneratedSerialDescriptor.addElement("mevInfo", true);
        pluginGeneratedSerialDescriptor.addElement("gasPrice", true);
        pluginGeneratedSerialDescriptor.addElement("accountInfo", true);
        pluginGeneratedSerialDescriptor.addElement("routerModeType", true);
        pluginGeneratedSerialDescriptor.addElement("teeSaStatus", true);
        pluginGeneratedSerialDescriptor.addElement("dexAutoConfirmEnabled", false);
        descriptor = pluginGeneratedSerialDescriptor;
    }

    @Override // kotlinx.serialization.internal.GeneratedSerializer
    public final KSerializer<?>[] childSerializers() {
        KSerializer<?>[] kSerializerArr = TransactionBean.$childSerializers;
        StringSerializer stringSerializer = StringSerializer.INSTANCE;
        BooleanSerializer booleanSerializer = BooleanSerializer.INSTANCE;
        return new KSerializer[]{BuiltinSerializersKt.getNullable(stringSerializer), stringSerializer, booleanSerializer, stringSerializer, stringSerializer, BuiltinSerializersKt.getNullable(QuotePriceRes$$serializer.INSTANCE), stringSerializer, stringSerializer, stringSerializer, kSerializerArr[9], OrderIdTypeData$$serializer.INSTANCE, stringSerializer, stringSerializer, BuiltinSerializersKt.getNullable(IntSerializer.INSTANCE), booleanSerializer, booleanSerializer, LongSerializer.INSTANCE, stringSerializer, kSerializerArr[18], BuiltinSerializersKt.getNullable(MergeCallData$$serializer.INSTANCE), BuiltinSerializersKt.getNullable(ServiceFeeInfo$$serializer.INSTANCE), BuiltinSerializersKt.getNullable(kSerializerArr[21]), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(kSerializerArr[23]), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(booleanSerializer), BuiltinSerializersKt.getNullable(stringSerializer), stringSerializer, BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(AccountInfo$$serializer.INSTANCE), BuiltinSerializersKt.getNullable(kSerializerArr[30]), kSerializerArr[31], booleanSerializer};
    }

    /* JADX DEBUG: Method merged with bridge method: deserialize(Lkotlinx/serialization/encoding/Decoder;)Ljava/lang/Object; */
    @Override // kotlinx.serialization.DeserializationStrategy
    public final TransactionBean deserialize(@NotNull Decoder decoder) {
        String str;
        OrderIdTypeData orderIdTypeData;
        Integer num;
        String str2;
        String str3;
        Boolean bool;
        boolean z;
        MergeCallData mergeCallData;
        TransactionBean.SwapType swapType;
        String str4;
        String str5;
        String str6;
        String str7;
        ServiceFeeInfo serviceFeeInfo;
        String str8;
        String str9;
        String str10;
        String str11;
        String str12;
        boolean z2;
        long j;
        int i;
        SlippageMode slippageMode;
        AccountInfo accountInfo;
        QuotePriceRes quotePriceRes;
        int i2;
        SlippageFeeType slippageFeeType;
        TeeSaStatus teeSaStatus;
        PresetRouteType presetRouteType;
        String str13;
        com.okinc.business.dexlogic.main.swap.trade.transaction.base.bean.TransactionType transactionType;
        String str14;
        boolean z3;
        boolean zDecodeBooleanElement;
        String str15;
        PresetRouteType presetRouteType2;
        String str16;
        TeeSaStatus teeSaStatus2;
        SlippageMode slippageMode2;
        MergeCallData mergeCallData2;
        TransactionBean.SwapType swapType2;
        Integer num2;
        OrderIdTypeData orderIdTypeData2;
        KSerializer[] kSerializerArr;
        int i3;
        int i4;
        OrderIdTypeData orderIdTypeData3;
        Integer num3;
        PresetRouteType presetRouteType3;
        String str17;
        TeeSaStatus teeSaStatus3;
        Integer num4;
        OrderIdTypeData orderIdTypeData4;
        com.okinc.business.dexlogic.main.swap.trade.transaction.base.bean.TransactionType transactionType2;
        int i5;
        PresetRouteType presetRouteType4;
        String str18;
        TeeSaStatus teeSaStatus4;
        Integer num5;
        com.okinc.business.dexlogic.main.swap.trade.transaction.base.bean.TransactionType transactionType3;
        int i6;
        Integer num6;
        int i7;
        int i8;
        TeeSaStatus teeSaStatus5;
        Integer num7;
        int i9;
        Integer num8;
        int i10;
        TransactionBean.SwapType swapType3;
        int i11;
        int i12;
        TeeSaStatus teeSaStatus6;
        int i13;
        int i14;
        int i15;
        Intrinsics.checkNotNullParameter(decoder, "");
        SerialDescriptor serialDescriptor = descriptor;
        CompositeDecoder compositeDecoderBeginStructure = decoder.beginStructure(serialDescriptor);
        KSerializer[] kSerializerArr2 = TransactionBean.$childSerializers;
        if (compositeDecoderBeginStructure.decodeSequentially()) {
            StringSerializer stringSerializer = StringSerializer.INSTANCE;
            String str19 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 0, stringSerializer, null);
            String strDecodeStringElement = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 1);
            boolean zDecodeBooleanElement2 = compositeDecoderBeginStructure.decodeBooleanElement(serialDescriptor, 2);
            String strDecodeStringElement2 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 3);
            String strDecodeStringElement3 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 4);
            QuotePriceRes quotePriceRes2 = (QuotePriceRes) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 5, QuotePriceRes$$serializer.INSTANCE, null);
            String strDecodeStringElement4 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 6);
            String strDecodeStringElement5 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 7);
            String strDecodeStringElement6 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 8);
            com.okinc.business.dexlogic.main.swap.trade.transaction.base.bean.TransactionType transactionType4 = (com.okinc.business.dexlogic.main.swap.trade.transaction.base.bean.TransactionType) compositeDecoderBeginStructure.decodeSerializableElement(serialDescriptor, 9, kSerializerArr2[9], null);
            OrderIdTypeData orderIdTypeData5 = (OrderIdTypeData) compositeDecoderBeginStructure.decodeSerializableElement(serialDescriptor, 10, OrderIdTypeData$$serializer.INSTANCE, null);
            String strDecodeStringElement7 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 11);
            String strDecodeStringElement8 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 12);
            Integer num9 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 13, IntSerializer.INSTANCE, null);
            boolean zDecodeBooleanElement3 = compositeDecoderBeginStructure.decodeBooleanElement(serialDescriptor, 14);
            boolean zDecodeBooleanElement4 = compositeDecoderBeginStructure.decodeBooleanElement(serialDescriptor, 15);
            long jDecodeLongElement = compositeDecoderBeginStructure.decodeLongElement(serialDescriptor, 16);
            String strDecodeStringElement9 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 17);
            TransactionBean.SwapType swapType4 = (TransactionBean.SwapType) compositeDecoderBeginStructure.decodeSerializableElement(serialDescriptor, 18, kSerializerArr2[18], null);
            MergeCallData mergeCallData3 = (MergeCallData) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 19, MergeCallData$$serializer.INSTANCE, null);
            ServiceFeeInfo serviceFeeInfo2 = (ServiceFeeInfo) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 20, ServiceFeeInfo$$serializer.INSTANCE, null);
            SlippageMode slippageMode3 = (SlippageMode) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 21, kSerializerArr2[21], null);
            String str20 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 22, stringSerializer, null);
            SlippageFeeType slippageFeeType2 = (SlippageFeeType) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 23, kSerializerArr2[23], null);
            String str21 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 24, stringSerializer, null);
            Boolean bool2 = (Boolean) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 25, BooleanSerializer.INSTANCE, null);
            String str22 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 26, stringSerializer, null);
            String strDecodeStringElement10 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 27);
            String str23 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 28, stringSerializer, null);
            AccountInfo accountInfo2 = (AccountInfo) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 29, AccountInfo$$serializer.INSTANCE, null);
            PresetRouteType presetRouteType5 = (PresetRouteType) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 30, kSerializerArr2[30], null);
            teeSaStatus = (TeeSaStatus) compositeDecoderBeginStructure.decodeSerializableElement(serialDescriptor, 31, kSerializerArr2[31], null);
            presetRouteType = presetRouteType5;
            zDecodeBooleanElement = compositeDecoderBeginStructure.decodeBooleanElement(serialDescriptor, 32);
            str3 = str22;
            orderIdTypeData = orderIdTypeData5;
            str5 = strDecodeStringElement10;
            accountInfo = accountInfo2;
            str2 = str20;
            z3 = zDecodeBooleanElement2;
            str12 = strDecodeStringElement;
            str11 = strDecodeStringElement2;
            slippageFeeType = slippageFeeType2;
            str6 = str21;
            str15 = str23;
            bool = bool2;
            str10 = strDecodeStringElement4;
            z2 = zDecodeBooleanElement4;
            transactionType = transactionType4;
            str7 = strDecodeStringElement9;
            serviceFeeInfo = serviceFeeInfo2;
            str = str19;
            swapType = swapType4;
            mergeCallData = mergeCallData3;
            str14 = strDecodeStringElement3;
            str9 = strDecodeStringElement5;
            str13 = strDecodeStringElement7;
            i2 = -1;
            slippageMode = slippageMode3;
            i = 1;
            j = jDecodeLongElement;
            z = zDecodeBooleanElement3;
            quotePriceRes = quotePriceRes2;
            num = num9;
            str4 = strDecodeStringElement8;
            str8 = strDecodeStringElement6;
        } else {
            int i16 = 32;
            boolean zDecodeBooleanElement5 = false;
            boolean zDecodeBooleanElement6 = false;
            boolean zDecodeBooleanElement7 = false;
            int i17 = 0;
            int i18 = 0;
            PresetRouteType presetRouteType6 = null;
            TeeSaStatus teeSaStatus7 = null;
            String str24 = null;
            String str25 = null;
            String str26 = null;
            AccountInfo accountInfo3 = null;
            QuotePriceRes quotePriceRes3 = null;
            SlippageFeeType slippageFeeType3 = null;
            Boolean bool3 = null;
            String strDecodeStringElement11 = null;
            String strDecodeStringElement12 = null;
            String strDecodeStringElement13 = null;
            SlippageMode slippageMode4 = null;
            ServiceFeeInfo serviceFeeInfo3 = null;
            MergeCallData mergeCallData4 = null;
            TransactionBean.SwapType swapType5 = null;
            Integer num10 = null;
            OrderIdTypeData orderIdTypeData6 = null;
            com.okinc.business.dexlogic.main.swap.trade.transaction.base.bean.TransactionType transactionType5 = null;
            String strDecodeStringElement14 = null;
            String strDecodeStringElement15 = null;
            String strDecodeStringElement16 = null;
            String strDecodeStringElement17 = null;
            String strDecodeStringElement18 = null;
            String str27 = null;
            String strDecodeStringElement19 = null;
            long jDecodeLongElement2 = 0;
            boolean z4 = true;
            String str28 = null;
            String strDecodeStringElement20 = null;
            boolean zDecodeBooleanElement8 = false;
            while (z4) {
                boolean z5 = zDecodeBooleanElement5;
                int iDecodeElementIndex = compositeDecoderBeginStructure.decodeElementIndex(serialDescriptor);
                switch (iDecodeElementIndex) {
                    case -1:
                        presetRouteType2 = presetRouteType6;
                        str16 = str28;
                        teeSaStatus2 = teeSaStatus7;
                        slippageMode2 = slippageMode4;
                        mergeCallData2 = mergeCallData4;
                        swapType2 = swapType5;
                        num2 = num10;
                        orderIdTypeData2 = orderIdTypeData6;
                        kSerializerArr = kSerializerArr2;
                        Unit unit = Unit.INSTANCE;
                        z4 = false;
                        i3 = i17;
                        str28 = str16;
                        zDecodeBooleanElement5 = z5;
                        PresetRouteType presetRouteType7 = presetRouteType2;
                        i4 = i3;
                        presetRouteType6 = presetRouteType7;
                        TeeSaStatus teeSaStatus8 = teeSaStatus2;
                        orderIdTypeData3 = orderIdTypeData2;
                        num3 = num2;
                        teeSaStatus7 = teeSaStatus8;
                        orderIdTypeData6 = orderIdTypeData3;
                        i17 = i4;
                        mergeCallData4 = mergeCallData2;
                        swapType5 = swapType2;
                        kSerializerArr2 = kSerializerArr;
                        slippageMode4 = slippageMode2;
                        num10 = num3;
                        i16 = 32;
                        break;
                    case 0:
                        presetRouteType2 = presetRouteType6;
                        str16 = str28;
                        teeSaStatus2 = teeSaStatus7;
                        slippageMode2 = slippageMode4;
                        mergeCallData2 = mergeCallData4;
                        swapType2 = swapType5;
                        num2 = num10;
                        orderIdTypeData2 = orderIdTypeData6;
                        kSerializerArr = kSerializerArr2;
                        str27 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 0, StringSerializer.INSTANCE, str27);
                        i3 = i17 | 1;
                        Unit unit2 = Unit.INSTANCE;
                        str28 = str16;
                        zDecodeBooleanElement5 = z5;
                        PresetRouteType presetRouteType72 = presetRouteType2;
                        i4 = i3;
                        presetRouteType6 = presetRouteType72;
                        TeeSaStatus teeSaStatus82 = teeSaStatus2;
                        orderIdTypeData3 = orderIdTypeData2;
                        num3 = num2;
                        teeSaStatus7 = teeSaStatus82;
                        orderIdTypeData6 = orderIdTypeData3;
                        i17 = i4;
                        mergeCallData4 = mergeCallData2;
                        swapType5 = swapType2;
                        kSerializerArr2 = kSerializerArr;
                        slippageMode4 = slippageMode2;
                        num10 = num3;
                        i16 = 32;
                        break;
                    case 1:
                        presetRouteType3 = presetRouteType6;
                        str17 = str28;
                        teeSaStatus3 = teeSaStatus7;
                        slippageMode2 = slippageMode4;
                        mergeCallData2 = mergeCallData4;
                        swapType2 = swapType5;
                        num4 = num10;
                        orderIdTypeData4 = orderIdTypeData6;
                        kSerializerArr = kSerializerArr2;
                        transactionType2 = transactionType5;
                        strDecodeStringElement19 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 1);
                        i5 = i17 | 2;
                        Unit unit3 = Unit.INSTANCE;
                        transactionType5 = transactionType2;
                        presetRouteType6 = presetRouteType3;
                        str28 = str17;
                        i4 = i5;
                        zDecodeBooleanElement5 = z5;
                        TeeSaStatus teeSaStatus9 = teeSaStatus3;
                        orderIdTypeData3 = orderIdTypeData4;
                        num3 = num4;
                        teeSaStatus7 = teeSaStatus9;
                        orderIdTypeData6 = orderIdTypeData3;
                        i17 = i4;
                        mergeCallData4 = mergeCallData2;
                        swapType5 = swapType2;
                        kSerializerArr2 = kSerializerArr;
                        slippageMode4 = slippageMode2;
                        num10 = num3;
                        i16 = 32;
                        break;
                    case 2:
                        presetRouteType3 = presetRouteType6;
                        str17 = str28;
                        teeSaStatus3 = teeSaStatus7;
                        slippageMode2 = slippageMode4;
                        mergeCallData2 = mergeCallData4;
                        swapType2 = swapType5;
                        num4 = num10;
                        orderIdTypeData4 = orderIdTypeData6;
                        kSerializerArr = kSerializerArr2;
                        transactionType2 = transactionType5;
                        zDecodeBooleanElement7 = compositeDecoderBeginStructure.decodeBooleanElement(serialDescriptor, 2);
                        i5 = i17 | 4;
                        Unit unit4 = Unit.INSTANCE;
                        transactionType5 = transactionType2;
                        presetRouteType6 = presetRouteType3;
                        str28 = str17;
                        i4 = i5;
                        zDecodeBooleanElement5 = z5;
                        TeeSaStatus teeSaStatus92 = teeSaStatus3;
                        orderIdTypeData3 = orderIdTypeData4;
                        num3 = num4;
                        teeSaStatus7 = teeSaStatus92;
                        orderIdTypeData6 = orderIdTypeData3;
                        i17 = i4;
                        mergeCallData4 = mergeCallData2;
                        swapType5 = swapType2;
                        kSerializerArr2 = kSerializerArr;
                        slippageMode4 = slippageMode2;
                        num10 = num3;
                        i16 = 32;
                        break;
                    case 3:
                        presetRouteType3 = presetRouteType6;
                        str17 = str28;
                        teeSaStatus3 = teeSaStatus7;
                        slippageMode2 = slippageMode4;
                        mergeCallData2 = mergeCallData4;
                        swapType2 = swapType5;
                        num4 = num10;
                        orderIdTypeData4 = orderIdTypeData6;
                        kSerializerArr = kSerializerArr2;
                        transactionType2 = transactionType5;
                        strDecodeStringElement18 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 3);
                        i5 = i17 | 8;
                        Unit unit5 = Unit.INSTANCE;
                        transactionType5 = transactionType2;
                        presetRouteType6 = presetRouteType3;
                        str28 = str17;
                        i4 = i5;
                        zDecodeBooleanElement5 = z5;
                        TeeSaStatus teeSaStatus922 = teeSaStatus3;
                        orderIdTypeData3 = orderIdTypeData4;
                        num3 = num4;
                        teeSaStatus7 = teeSaStatus922;
                        orderIdTypeData6 = orderIdTypeData3;
                        i17 = i4;
                        mergeCallData4 = mergeCallData2;
                        swapType5 = swapType2;
                        kSerializerArr2 = kSerializerArr;
                        slippageMode4 = slippageMode2;
                        num10 = num3;
                        i16 = 32;
                        break;
                    case 4:
                        presetRouteType3 = presetRouteType6;
                        str17 = str28;
                        teeSaStatus3 = teeSaStatus7;
                        slippageMode2 = slippageMode4;
                        mergeCallData2 = mergeCallData4;
                        swapType2 = swapType5;
                        num4 = num10;
                        orderIdTypeData4 = orderIdTypeData6;
                        kSerializerArr = kSerializerArr2;
                        transactionType2 = transactionType5;
                        strDecodeStringElement17 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 4);
                        i5 = i17 | 16;
                        Unit unit6 = Unit.INSTANCE;
                        transactionType5 = transactionType2;
                        presetRouteType6 = presetRouteType3;
                        str28 = str17;
                        i4 = i5;
                        zDecodeBooleanElement5 = z5;
                        TeeSaStatus teeSaStatus9222 = teeSaStatus3;
                        orderIdTypeData3 = orderIdTypeData4;
                        num3 = num4;
                        teeSaStatus7 = teeSaStatus9222;
                        orderIdTypeData6 = orderIdTypeData3;
                        i17 = i4;
                        mergeCallData4 = mergeCallData2;
                        swapType5 = swapType2;
                        kSerializerArr2 = kSerializerArr;
                        slippageMode4 = slippageMode2;
                        num10 = num3;
                        i16 = 32;
                        break;
                    case 5:
                        presetRouteType3 = presetRouteType6;
                        str17 = str28;
                        teeSaStatus3 = teeSaStatus7;
                        slippageMode2 = slippageMode4;
                        mergeCallData2 = mergeCallData4;
                        swapType2 = swapType5;
                        num4 = num10;
                        orderIdTypeData4 = orderIdTypeData6;
                        kSerializerArr = kSerializerArr2;
                        transactionType2 = transactionType5;
                        quotePriceRes3 = (QuotePriceRes) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 5, QuotePriceRes$$serializer.INSTANCE, quotePriceRes3);
                        Unit unit7 = Unit.INSTANCE;
                        i5 = i17 | 32;
                        transactionType5 = transactionType2;
                        presetRouteType6 = presetRouteType3;
                        str28 = str17;
                        i4 = i5;
                        zDecodeBooleanElement5 = z5;
                        TeeSaStatus teeSaStatus92222 = teeSaStatus3;
                        orderIdTypeData3 = orderIdTypeData4;
                        num3 = num4;
                        teeSaStatus7 = teeSaStatus92222;
                        orderIdTypeData6 = orderIdTypeData3;
                        i17 = i4;
                        mergeCallData4 = mergeCallData2;
                        swapType5 = swapType2;
                        kSerializerArr2 = kSerializerArr;
                        slippageMode4 = slippageMode2;
                        num10 = num3;
                        i16 = 32;
                        break;
                    case 6:
                        presetRouteType4 = presetRouteType6;
                        str18 = str28;
                        teeSaStatus4 = teeSaStatus7;
                        slippageMode2 = slippageMode4;
                        mergeCallData2 = mergeCallData4;
                        swapType2 = swapType5;
                        num5 = num10;
                        kSerializerArr = kSerializerArr2;
                        transactionType3 = transactionType5;
                        strDecodeStringElement16 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 6);
                        i6 = i17 | 64;
                        Unit unit8 = Unit.INSTANCE;
                        transactionType5 = transactionType3;
                        num8 = num5;
                        i7 = i6;
                        i10 = i7;
                        teeSaStatus7 = teeSaStatus4;
                        zDecodeBooleanElement5 = z5;
                        presetRouteType6 = presetRouteType4;
                        str28 = str18;
                        orderIdTypeData3 = orderIdTypeData6;
                        i4 = i10;
                        num3 = num8;
                        orderIdTypeData6 = orderIdTypeData3;
                        i17 = i4;
                        mergeCallData4 = mergeCallData2;
                        swapType5 = swapType2;
                        kSerializerArr2 = kSerializerArr;
                        slippageMode4 = slippageMode2;
                        num10 = num3;
                        i16 = 32;
                        break;
                    case 7:
                        presetRouteType4 = presetRouteType6;
                        str18 = str28;
                        teeSaStatus4 = teeSaStatus7;
                        slippageMode2 = slippageMode4;
                        mergeCallData2 = mergeCallData4;
                        swapType2 = swapType5;
                        num5 = num10;
                        kSerializerArr = kSerializerArr2;
                        transactionType3 = transactionType5;
                        strDecodeStringElement15 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 7);
                        i6 = i17 | 128;
                        Unit unit9 = Unit.INSTANCE;
                        transactionType5 = transactionType3;
                        num8 = num5;
                        i7 = i6;
                        i10 = i7;
                        teeSaStatus7 = teeSaStatus4;
                        zDecodeBooleanElement5 = z5;
                        presetRouteType6 = presetRouteType4;
                        str28 = str18;
                        orderIdTypeData3 = orderIdTypeData6;
                        i4 = i10;
                        num3 = num8;
                        orderIdTypeData6 = orderIdTypeData3;
                        i17 = i4;
                        mergeCallData4 = mergeCallData2;
                        swapType5 = swapType2;
                        kSerializerArr2 = kSerializerArr;
                        slippageMode4 = slippageMode2;
                        num10 = num3;
                        i16 = 32;
                        break;
                    case 8:
                        presetRouteType4 = presetRouteType6;
                        str18 = str28;
                        teeSaStatus4 = teeSaStatus7;
                        slippageMode2 = slippageMode4;
                        mergeCallData2 = mergeCallData4;
                        swapType2 = swapType5;
                        num5 = num10;
                        kSerializerArr = kSerializerArr2;
                        transactionType3 = transactionType5;
                        strDecodeStringElement14 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 8);
                        i6 = i17 | 256;
                        Unit unit10 = Unit.INSTANCE;
                        transactionType5 = transactionType3;
                        num8 = num5;
                        i7 = i6;
                        i10 = i7;
                        teeSaStatus7 = teeSaStatus4;
                        zDecodeBooleanElement5 = z5;
                        presetRouteType6 = presetRouteType4;
                        str28 = str18;
                        orderIdTypeData3 = orderIdTypeData6;
                        i4 = i10;
                        num3 = num8;
                        orderIdTypeData6 = orderIdTypeData3;
                        i17 = i4;
                        mergeCallData4 = mergeCallData2;
                        swapType5 = swapType2;
                        kSerializerArr2 = kSerializerArr;
                        slippageMode4 = slippageMode2;
                        num10 = num3;
                        i16 = 32;
                        break;
                    case 9:
                        presetRouteType4 = presetRouteType6;
                        str18 = str28;
                        teeSaStatus4 = teeSaStatus7;
                        slippageMode2 = slippageMode4;
                        mergeCallData2 = mergeCallData4;
                        swapType2 = swapType5;
                        Integer num11 = num10;
                        kSerializerArr = kSerializerArr2;
                        transactionType5 = (com.okinc.business.dexlogic.main.swap.trade.transaction.base.bean.TransactionType) compositeDecoderBeginStructure.decodeSerializableElement(serialDescriptor, 9, kSerializerArr2[9], transactionType5);
                        Unit unit11 = Unit.INSTANCE;
                        num6 = num11;
                        i7 = i17 | 512;
                        num8 = num6;
                        i10 = i7;
                        teeSaStatus7 = teeSaStatus4;
                        zDecodeBooleanElement5 = z5;
                        presetRouteType6 = presetRouteType4;
                        str28 = str18;
                        orderIdTypeData3 = orderIdTypeData6;
                        i4 = i10;
                        num3 = num8;
                        orderIdTypeData6 = orderIdTypeData3;
                        i17 = i4;
                        mergeCallData4 = mergeCallData2;
                        swapType5 = swapType2;
                        kSerializerArr2 = kSerializerArr;
                        slippageMode4 = slippageMode2;
                        num10 = num3;
                        i16 = 32;
                        break;
                    case 10:
                        presetRouteType4 = presetRouteType6;
                        teeSaStatus4 = teeSaStatus7;
                        slippageMode2 = slippageMode4;
                        mergeCallData2 = mergeCallData4;
                        swapType2 = swapType5;
                        num5 = num10;
                        str18 = str28;
                        orderIdTypeData6 = (OrderIdTypeData) compositeDecoderBeginStructure.decodeSerializableElement(serialDescriptor, 10, OrderIdTypeData$$serializer.INSTANCE, orderIdTypeData6);
                        i8 = i17 | 1024;
                        Unit unit12 = Unit.INSTANCE;
                        kSerializerArr = kSerializerArr2;
                        i6 = i8;
                        transactionType3 = transactionType5;
                        transactionType5 = transactionType3;
                        num8 = num5;
                        i7 = i6;
                        i10 = i7;
                        teeSaStatus7 = teeSaStatus4;
                        zDecodeBooleanElement5 = z5;
                        presetRouteType6 = presetRouteType4;
                        str28 = str18;
                        orderIdTypeData3 = orderIdTypeData6;
                        i4 = i10;
                        num3 = num8;
                        orderIdTypeData6 = orderIdTypeData3;
                        i17 = i4;
                        mergeCallData4 = mergeCallData2;
                        swapType5 = swapType2;
                        kSerializerArr2 = kSerializerArr;
                        slippageMode4 = slippageMode2;
                        num10 = num3;
                        i16 = 32;
                        break;
                    case 11:
                        presetRouteType4 = presetRouteType6;
                        teeSaStatus5 = teeSaStatus7;
                        slippageMode2 = slippageMode4;
                        mergeCallData2 = mergeCallData4;
                        swapType2 = swapType5;
                        num7 = num10;
                        strDecodeStringElement11 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 11);
                        i9 = i17 | 2048;
                        Unit unit13 = Unit.INSTANCE;
                        kSerializerArr = kSerializerArr2;
                        str18 = str28;
                        num8 = num7;
                        i10 = i9;
                        teeSaStatus7 = teeSaStatus5;
                        zDecodeBooleanElement5 = z5;
                        presetRouteType6 = presetRouteType4;
                        str28 = str18;
                        orderIdTypeData3 = orderIdTypeData6;
                        i4 = i10;
                        num3 = num8;
                        orderIdTypeData6 = orderIdTypeData3;
                        i17 = i4;
                        mergeCallData4 = mergeCallData2;
                        swapType5 = swapType2;
                        kSerializerArr2 = kSerializerArr;
                        slippageMode4 = slippageMode2;
                        num10 = num3;
                        i16 = 32;
                        break;
                    case 12:
                        presetRouteType4 = presetRouteType6;
                        teeSaStatus5 = teeSaStatus7;
                        slippageMode2 = slippageMode4;
                        mergeCallData2 = mergeCallData4;
                        swapType2 = swapType5;
                        num7 = num10;
                        strDecodeStringElement20 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 12);
                        i9 = i17 | 4096;
                        Unit unit14 = Unit.INSTANCE;
                        kSerializerArr = kSerializerArr2;
                        str18 = str28;
                        num8 = num7;
                        i10 = i9;
                        teeSaStatus7 = teeSaStatus5;
                        zDecodeBooleanElement5 = z5;
                        presetRouteType6 = presetRouteType4;
                        str28 = str18;
                        orderIdTypeData3 = orderIdTypeData6;
                        i4 = i10;
                        num3 = num8;
                        orderIdTypeData6 = orderIdTypeData3;
                        i17 = i4;
                        mergeCallData4 = mergeCallData2;
                        swapType5 = swapType2;
                        kSerializerArr2 = kSerializerArr;
                        slippageMode4 = slippageMode2;
                        num10 = num3;
                        i16 = 32;
                        break;
                    case 13:
                        presetRouteType4 = presetRouteType6;
                        teeSaStatus4 = teeSaStatus7;
                        slippageMode2 = slippageMode4;
                        mergeCallData2 = mergeCallData4;
                        swapType2 = swapType5;
                        num10 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 13, IntSerializer.INSTANCE, num10);
                        i7 = i17 | 8192;
                        Unit unit15 = Unit.INSTANCE;
                        str18 = str28;
                        num6 = num10;
                        kSerializerArr = kSerializerArr2;
                        num8 = num6;
                        i10 = i7;
                        teeSaStatus7 = teeSaStatus4;
                        zDecodeBooleanElement5 = z5;
                        presetRouteType6 = presetRouteType4;
                        str28 = str18;
                        orderIdTypeData3 = orderIdTypeData6;
                        i4 = i10;
                        num3 = num8;
                        orderIdTypeData6 = orderIdTypeData3;
                        i17 = i4;
                        mergeCallData4 = mergeCallData2;
                        swapType5 = swapType2;
                        kSerializerArr2 = kSerializerArr;
                        slippageMode4 = slippageMode2;
                        num10 = num3;
                        i16 = 32;
                        break;
                    case 14:
                        presetRouteType4 = presetRouteType6;
                        teeSaStatus4 = teeSaStatus7;
                        slippageMode2 = slippageMode4;
                        mergeCallData2 = mergeCallData4;
                        swapType3 = swapType5;
                        zDecodeBooleanElement8 = compositeDecoderBeginStructure.decodeBooleanElement(serialDescriptor, 14);
                        i8 = i17 | 16384;
                        swapType2 = swapType3;
                        str18 = str28;
                        num5 = num10;
                        Unit unit122 = Unit.INSTANCE;
                        kSerializerArr = kSerializerArr2;
                        i6 = i8;
                        transactionType3 = transactionType5;
                        transactionType5 = transactionType3;
                        num8 = num5;
                        i7 = i6;
                        i10 = i7;
                        teeSaStatus7 = teeSaStatus4;
                        zDecodeBooleanElement5 = z5;
                        presetRouteType6 = presetRouteType4;
                        str28 = str18;
                        orderIdTypeData3 = orderIdTypeData6;
                        i4 = i10;
                        num3 = num8;
                        orderIdTypeData6 = orderIdTypeData3;
                        i17 = i4;
                        mergeCallData4 = mergeCallData2;
                        swapType5 = swapType2;
                        kSerializerArr2 = kSerializerArr;
                        slippageMode4 = slippageMode2;
                        num10 = num3;
                        i16 = 32;
                        break;
                    case 15:
                        presetRouteType4 = presetRouteType6;
                        teeSaStatus4 = teeSaStatus7;
                        slippageMode2 = slippageMode4;
                        mergeCallData2 = mergeCallData4;
                        swapType3 = swapType5;
                        zDecodeBooleanElement6 = compositeDecoderBeginStructure.decodeBooleanElement(serialDescriptor, 15);
                        i8 = 32768 | i17;
                        swapType2 = swapType3;
                        str18 = str28;
                        num5 = num10;
                        Unit unit1222 = Unit.INSTANCE;
                        kSerializerArr = kSerializerArr2;
                        i6 = i8;
                        transactionType3 = transactionType5;
                        transactionType5 = transactionType3;
                        num8 = num5;
                        i7 = i6;
                        i10 = i7;
                        teeSaStatus7 = teeSaStatus4;
                        zDecodeBooleanElement5 = z5;
                        presetRouteType6 = presetRouteType4;
                        str28 = str18;
                        orderIdTypeData3 = orderIdTypeData6;
                        i4 = i10;
                        num3 = num8;
                        orderIdTypeData6 = orderIdTypeData3;
                        i17 = i4;
                        mergeCallData4 = mergeCallData2;
                        swapType5 = swapType2;
                        kSerializerArr2 = kSerializerArr;
                        slippageMode4 = slippageMode2;
                        num10 = num3;
                        i16 = 32;
                        break;
                    case 16:
                        presetRouteType4 = presetRouteType6;
                        teeSaStatus4 = teeSaStatus7;
                        slippageMode2 = slippageMode4;
                        mergeCallData2 = mergeCallData4;
                        jDecodeLongElement2 = compositeDecoderBeginStructure.decodeLongElement(serialDescriptor, 16);
                        i6 = i17 | 65536;
                        Unit unit16 = Unit.INSTANCE;
                        swapType2 = swapType5;
                        str18 = str28;
                        num5 = num10;
                        kSerializerArr = kSerializerArr2;
                        transactionType3 = transactionType5;
                        transactionType5 = transactionType3;
                        num8 = num5;
                        i7 = i6;
                        i10 = i7;
                        teeSaStatus7 = teeSaStatus4;
                        zDecodeBooleanElement5 = z5;
                        presetRouteType6 = presetRouteType4;
                        str28 = str18;
                        orderIdTypeData3 = orderIdTypeData6;
                        i4 = i10;
                        num3 = num8;
                        orderIdTypeData6 = orderIdTypeData3;
                        i17 = i4;
                        mergeCallData4 = mergeCallData2;
                        swapType5 = swapType2;
                        kSerializerArr2 = kSerializerArr;
                        slippageMode4 = slippageMode2;
                        num10 = num3;
                        i16 = 32;
                        break;
                    case 17:
                        presetRouteType4 = presetRouteType6;
                        teeSaStatus4 = teeSaStatus7;
                        slippageMode2 = slippageMode4;
                        mergeCallData2 = mergeCallData4;
                        strDecodeStringElement13 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 17);
                        i7 = 131072 | i17;
                        Unit unit17 = Unit.INSTANCE;
                        swapType2 = swapType5;
                        str18 = str28;
                        num6 = num10;
                        kSerializerArr = kSerializerArr2;
                        num8 = num6;
                        i10 = i7;
                        teeSaStatus7 = teeSaStatus4;
                        zDecodeBooleanElement5 = z5;
                        presetRouteType6 = presetRouteType4;
                        str28 = str18;
                        orderIdTypeData3 = orderIdTypeData6;
                        i4 = i10;
                        num3 = num8;
                        orderIdTypeData6 = orderIdTypeData3;
                        i17 = i4;
                        mergeCallData4 = mergeCallData2;
                        swapType5 = swapType2;
                        kSerializerArr2 = kSerializerArr;
                        slippageMode4 = slippageMode2;
                        num10 = num3;
                        i16 = 32;
                        break;
                    case 18:
                        presetRouteType4 = presetRouteType6;
                        teeSaStatus4 = teeSaStatus7;
                        slippageMode2 = slippageMode4;
                        mergeCallData2 = mergeCallData4;
                        swapType5 = (TransactionBean.SwapType) compositeDecoderBeginStructure.decodeSerializableElement(serialDescriptor, 18, kSerializerArr2[18], swapType5);
                        i7 = i17 | 262144;
                        Unit unit18 = Unit.INSTANCE;
                        str18 = str28;
                        swapType2 = swapType5;
                        num6 = num10;
                        kSerializerArr = kSerializerArr2;
                        num8 = num6;
                        i10 = i7;
                        teeSaStatus7 = teeSaStatus4;
                        zDecodeBooleanElement5 = z5;
                        presetRouteType6 = presetRouteType4;
                        str28 = str18;
                        orderIdTypeData3 = orderIdTypeData6;
                        i4 = i10;
                        num3 = num8;
                        orderIdTypeData6 = orderIdTypeData3;
                        i17 = i4;
                        mergeCallData4 = mergeCallData2;
                        swapType5 = swapType2;
                        kSerializerArr2 = kSerializerArr;
                        slippageMode4 = slippageMode2;
                        num10 = num3;
                        i16 = 32;
                        break;
                    case 19:
                        presetRouteType4 = presetRouteType6;
                        teeSaStatus4 = teeSaStatus7;
                        slippageMode2 = slippageMode4;
                        i11 = i17;
                        mergeCallData4 = (MergeCallData) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 19, MergeCallData$$serializer.INSTANCE, mergeCallData4);
                        i12 = 524288;
                        i7 = i11 | i12;
                        Unit unit19 = Unit.INSTANCE;
                        str18 = str28;
                        mergeCallData2 = mergeCallData4;
                        swapType2 = swapType5;
                        num6 = num10;
                        kSerializerArr = kSerializerArr2;
                        num8 = num6;
                        i10 = i7;
                        teeSaStatus7 = teeSaStatus4;
                        zDecodeBooleanElement5 = z5;
                        presetRouteType6 = presetRouteType4;
                        str28 = str18;
                        orderIdTypeData3 = orderIdTypeData6;
                        i4 = i10;
                        num3 = num8;
                        orderIdTypeData6 = orderIdTypeData3;
                        i17 = i4;
                        mergeCallData4 = mergeCallData2;
                        swapType5 = swapType2;
                        kSerializerArr2 = kSerializerArr;
                        slippageMode4 = slippageMode2;
                        num10 = num3;
                        i16 = 32;
                        break;
                    case 20:
                        presetRouteType4 = presetRouteType6;
                        teeSaStatus4 = teeSaStatus7;
                        i11 = i17;
                        slippageMode2 = slippageMode4;
                        serviceFeeInfo3 = (ServiceFeeInfo) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 20, ServiceFeeInfo$$serializer.INSTANCE, serviceFeeInfo3);
                        i12 = 1048576;
                        i7 = i11 | i12;
                        Unit unit192 = Unit.INSTANCE;
                        str18 = str28;
                        mergeCallData2 = mergeCallData4;
                        swapType2 = swapType5;
                        num6 = num10;
                        kSerializerArr = kSerializerArr2;
                        num8 = num6;
                        i10 = i7;
                        teeSaStatus7 = teeSaStatus4;
                        zDecodeBooleanElement5 = z5;
                        presetRouteType6 = presetRouteType4;
                        str28 = str18;
                        orderIdTypeData3 = orderIdTypeData6;
                        i4 = i10;
                        num3 = num8;
                        orderIdTypeData6 = orderIdTypeData3;
                        i17 = i4;
                        mergeCallData4 = mergeCallData2;
                        swapType5 = swapType2;
                        kSerializerArr2 = kSerializerArr;
                        slippageMode4 = slippageMode2;
                        num10 = num3;
                        i16 = 32;
                        break;
                    case 21:
                        teeSaStatus4 = teeSaStatus7;
                        presetRouteType4 = presetRouteType6;
                        slippageMode4 = (SlippageMode) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 21, kSerializerArr2[21], slippageMode4);
                        i7 = i17 | 2097152;
                        Unit unit20 = Unit.INSTANCE;
                        str18 = str28;
                        slippageMode2 = slippageMode4;
                        mergeCallData2 = mergeCallData4;
                        swapType2 = swapType5;
                        num6 = num10;
                        kSerializerArr = kSerializerArr2;
                        num8 = num6;
                        i10 = i7;
                        teeSaStatus7 = teeSaStatus4;
                        zDecodeBooleanElement5 = z5;
                        presetRouteType6 = presetRouteType4;
                        str28 = str18;
                        orderIdTypeData3 = orderIdTypeData6;
                        i4 = i10;
                        num3 = num8;
                        orderIdTypeData6 = orderIdTypeData3;
                        i17 = i4;
                        mergeCallData4 = mergeCallData2;
                        swapType5 = swapType2;
                        kSerializerArr2 = kSerializerArr;
                        slippageMode4 = slippageMode2;
                        num10 = num3;
                        i16 = 32;
                        break;
                    case 22:
                        teeSaStatus4 = teeSaStatus7;
                        str24 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 22, StringSerializer.INSTANCE, str24);
                        i7 = i17 | 4194304;
                        Unit unit21 = Unit.INSTANCE;
                        presetRouteType4 = presetRouteType6;
                        str18 = str28;
                        slippageMode2 = slippageMode4;
                        mergeCallData2 = mergeCallData4;
                        swapType2 = swapType5;
                        num6 = num10;
                        kSerializerArr = kSerializerArr2;
                        num8 = num6;
                        i10 = i7;
                        teeSaStatus7 = teeSaStatus4;
                        zDecodeBooleanElement5 = z5;
                        presetRouteType6 = presetRouteType4;
                        str28 = str18;
                        orderIdTypeData3 = orderIdTypeData6;
                        i4 = i10;
                        num3 = num8;
                        orderIdTypeData6 = orderIdTypeData3;
                        i17 = i4;
                        mergeCallData4 = mergeCallData2;
                        swapType5 = swapType2;
                        kSerializerArr2 = kSerializerArr;
                        slippageMode4 = slippageMode2;
                        num10 = num3;
                        i16 = 32;
                        break;
                    case 23:
                        teeSaStatus4 = teeSaStatus7;
                        slippageFeeType3 = (SlippageFeeType) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 23, kSerializerArr2[23], slippageFeeType3);
                        i7 = 8388608 | i17;
                        Unit unit22 = Unit.INSTANCE;
                        presetRouteType4 = presetRouteType6;
                        str18 = str28;
                        slippageMode2 = slippageMode4;
                        mergeCallData2 = mergeCallData4;
                        swapType2 = swapType5;
                        num6 = num10;
                        kSerializerArr = kSerializerArr2;
                        num8 = num6;
                        i10 = i7;
                        teeSaStatus7 = teeSaStatus4;
                        zDecodeBooleanElement5 = z5;
                        presetRouteType6 = presetRouteType4;
                        str28 = str18;
                        orderIdTypeData3 = orderIdTypeData6;
                        i4 = i10;
                        num3 = num8;
                        orderIdTypeData6 = orderIdTypeData3;
                        i17 = i4;
                        mergeCallData4 = mergeCallData2;
                        swapType5 = swapType2;
                        kSerializerArr2 = kSerializerArr;
                        slippageMode4 = slippageMode2;
                        num10 = num3;
                        i16 = 32;
                        break;
                    case 24:
                        teeSaStatus6 = teeSaStatus7;
                        String str29 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 24, StringSerializer.INSTANCE, str28);
                        i10 = 16777216 | i17;
                        Unit unit23 = Unit.INSTANCE;
                        presetRouteType4 = presetRouteType6;
                        str18 = str29;
                        teeSaStatus7 = teeSaStatus6;
                        slippageMode2 = slippageMode4;
                        mergeCallData2 = mergeCallData4;
                        swapType2 = swapType5;
                        Integer num12 = num10;
                        kSerializerArr = kSerializerArr2;
                        num8 = num12;
                        zDecodeBooleanElement5 = z5;
                        presetRouteType6 = presetRouteType4;
                        str28 = str18;
                        orderIdTypeData3 = orderIdTypeData6;
                        i4 = i10;
                        num3 = num8;
                        orderIdTypeData6 = orderIdTypeData3;
                        i17 = i4;
                        mergeCallData4 = mergeCallData2;
                        swapType5 = swapType2;
                        kSerializerArr2 = kSerializerArr;
                        slippageMode4 = slippageMode2;
                        num10 = num3;
                        i16 = 32;
                        break;
                    case 25:
                        teeSaStatus6 = teeSaStatus7;
                        i13 = i17;
                        bool3 = (Boolean) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 25, BooleanSerializer.INSTANCE, bool3);
                        i14 = MediaHttpDownloader.MAXIMUM_CHUNK_SIZE;
                        i15 = i13 | i14;
                        Unit unit24 = Unit.INSTANCE;
                        presetRouteType4 = presetRouteType6;
                        str18 = str28;
                        i10 = i15;
                        teeSaStatus7 = teeSaStatus6;
                        slippageMode2 = slippageMode4;
                        mergeCallData2 = mergeCallData4;
                        swapType2 = swapType5;
                        Integer num122 = num10;
                        kSerializerArr = kSerializerArr2;
                        num8 = num122;
                        zDecodeBooleanElement5 = z5;
                        presetRouteType6 = presetRouteType4;
                        str28 = str18;
                        orderIdTypeData3 = orderIdTypeData6;
                        i4 = i10;
                        num3 = num8;
                        orderIdTypeData6 = orderIdTypeData3;
                        i17 = i4;
                        mergeCallData4 = mergeCallData2;
                        swapType5 = swapType2;
                        kSerializerArr2 = kSerializerArr;
                        slippageMode4 = slippageMode2;
                        num10 = num3;
                        i16 = 32;
                        break;
                    case 26:
                        teeSaStatus6 = teeSaStatus7;
                        i13 = i17;
                        str25 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 26, StringSerializer.INSTANCE, str25);
                        i14 = 67108864;
                        i15 = i13 | i14;
                        Unit unit242 = Unit.INSTANCE;
                        presetRouteType4 = presetRouteType6;
                        str18 = str28;
                        i10 = i15;
                        teeSaStatus7 = teeSaStatus6;
                        slippageMode2 = slippageMode4;
                        mergeCallData2 = mergeCallData4;
                        swapType2 = swapType5;
                        Integer num1222 = num10;
                        kSerializerArr = kSerializerArr2;
                        num8 = num1222;
                        zDecodeBooleanElement5 = z5;
                        presetRouteType6 = presetRouteType4;
                        str28 = str18;
                        orderIdTypeData3 = orderIdTypeData6;
                        i4 = i10;
                        num3 = num8;
                        orderIdTypeData6 = orderIdTypeData3;
                        i17 = i4;
                        mergeCallData4 = mergeCallData2;
                        swapType5 = swapType2;
                        kSerializerArr2 = kSerializerArr;
                        slippageMode4 = slippageMode2;
                        num10 = num3;
                        i16 = 32;
                        break;
                    case 27:
                        teeSaStatus6 = teeSaStatus7;
                        i13 = i17;
                        strDecodeStringElement12 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 27);
                        i14 = 134217728;
                        i15 = i13 | i14;
                        Unit unit2422 = Unit.INSTANCE;
                        presetRouteType4 = presetRouteType6;
                        str18 = str28;
                        i10 = i15;
                        teeSaStatus7 = teeSaStatus6;
                        slippageMode2 = slippageMode4;
                        mergeCallData2 = mergeCallData4;
                        swapType2 = swapType5;
                        Integer num12222 = num10;
                        kSerializerArr = kSerializerArr2;
                        num8 = num12222;
                        zDecodeBooleanElement5 = z5;
                        presetRouteType6 = presetRouteType4;
                        str28 = str18;
                        orderIdTypeData3 = orderIdTypeData6;
                        i4 = i10;
                        num3 = num8;
                        orderIdTypeData6 = orderIdTypeData3;
                        i17 = i4;
                        mergeCallData4 = mergeCallData2;
                        swapType5 = swapType2;
                        kSerializerArr2 = kSerializerArr;
                        slippageMode4 = slippageMode2;
                        num10 = num3;
                        i16 = 32;
                        break;
                    case 28:
                        teeSaStatus6 = teeSaStatus7;
                        i13 = i17;
                        str26 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 28, StringSerializer.INSTANCE, str26);
                        i14 = 268435456;
                        i15 = i13 | i14;
                        Unit unit24222 = Unit.INSTANCE;
                        presetRouteType4 = presetRouteType6;
                        str18 = str28;
                        i10 = i15;
                        teeSaStatus7 = teeSaStatus6;
                        slippageMode2 = slippageMode4;
                        mergeCallData2 = mergeCallData4;
                        swapType2 = swapType5;
                        Integer num122222 = num10;
                        kSerializerArr = kSerializerArr2;
                        num8 = num122222;
                        zDecodeBooleanElement5 = z5;
                        presetRouteType6 = presetRouteType4;
                        str28 = str18;
                        orderIdTypeData3 = orderIdTypeData6;
                        i4 = i10;
                        num3 = num8;
                        orderIdTypeData6 = orderIdTypeData3;
                        i17 = i4;
                        mergeCallData4 = mergeCallData2;
                        swapType5 = swapType2;
                        kSerializerArr2 = kSerializerArr;
                        slippageMode4 = slippageMode2;
                        num10 = num3;
                        i16 = 32;
                        break;
                    case 29:
                        teeSaStatus6 = teeSaStatus7;
                        i13 = i17;
                        accountInfo3 = (AccountInfo) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 29, AccountInfo$$serializer.INSTANCE, accountInfo3);
                        i14 = 536870912;
                        i15 = i13 | i14;
                        Unit unit242222 = Unit.INSTANCE;
                        presetRouteType4 = presetRouteType6;
                        str18 = str28;
                        i10 = i15;
                        teeSaStatus7 = teeSaStatus6;
                        slippageMode2 = slippageMode4;
                        mergeCallData2 = mergeCallData4;
                        swapType2 = swapType5;
                        Integer num1222222 = num10;
                        kSerializerArr = kSerializerArr2;
                        num8 = num1222222;
                        zDecodeBooleanElement5 = z5;
                        presetRouteType6 = presetRouteType4;
                        str28 = str18;
                        orderIdTypeData3 = orderIdTypeData6;
                        i4 = i10;
                        num3 = num8;
                        orderIdTypeData6 = orderIdTypeData3;
                        i17 = i4;
                        mergeCallData4 = mergeCallData2;
                        swapType5 = swapType2;
                        kSerializerArr2 = kSerializerArr;
                        slippageMode4 = slippageMode2;
                        num10 = num3;
                        i16 = 32;
                        break;
                    case 30:
                        teeSaStatus6 = teeSaStatus7;
                        presetRouteType6 = (PresetRouteType) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 30, kSerializerArr2[30], presetRouteType6);
                        i15 = 1073741824 | i17;
                        Unit unit25 = Unit.INSTANCE;
                        presetRouteType4 = presetRouteType6;
                        str18 = str28;
                        i10 = i15;
                        teeSaStatus7 = teeSaStatus6;
                        slippageMode2 = slippageMode4;
                        mergeCallData2 = mergeCallData4;
                        swapType2 = swapType5;
                        Integer num12222222 = num10;
                        kSerializerArr = kSerializerArr2;
                        num8 = num12222222;
                        zDecodeBooleanElement5 = z5;
                        presetRouteType6 = presetRouteType4;
                        str28 = str18;
                        orderIdTypeData3 = orderIdTypeData6;
                        i4 = i10;
                        num3 = num8;
                        orderIdTypeData6 = orderIdTypeData3;
                        i17 = i4;
                        mergeCallData4 = mergeCallData2;
                        swapType5 = swapType2;
                        kSerializerArr2 = kSerializerArr;
                        slippageMode4 = slippageMode2;
                        num10 = num3;
                        i16 = 32;
                        break;
                    case 31:
                        teeSaStatus7 = (TeeSaStatus) compositeDecoderBeginStructure.decodeSerializableElement(serialDescriptor, 31, kSerializerArr2[31], teeSaStatus7);
                        i10 = Integer.MIN_VALUE | i17;
                        Unit unit26 = Unit.INSTANCE;
                        presetRouteType4 = presetRouteType6;
                        str18 = str28;
                        slippageMode2 = slippageMode4;
                        mergeCallData2 = mergeCallData4;
                        swapType2 = swapType5;
                        Integer num122222222 = num10;
                        kSerializerArr = kSerializerArr2;
                        num8 = num122222222;
                        zDecodeBooleanElement5 = z5;
                        presetRouteType6 = presetRouteType4;
                        str28 = str18;
                        orderIdTypeData3 = orderIdTypeData6;
                        i4 = i10;
                        num3 = num8;
                        orderIdTypeData6 = orderIdTypeData3;
                        i17 = i4;
                        mergeCallData4 = mergeCallData2;
                        swapType5 = swapType2;
                        kSerializerArr2 = kSerializerArr;
                        slippageMode4 = slippageMode2;
                        num10 = num3;
                        i16 = 32;
                        break;
                    case 32:
                        zDecodeBooleanElement5 = compositeDecoderBeginStructure.decodeBooleanElement(serialDescriptor, i16);
                        Unit unit27 = Unit.INSTANCE;
                        presetRouteType4 = presetRouteType6;
                        str18 = str28;
                        slippageMode2 = slippageMode4;
                        mergeCallData2 = mergeCallData4;
                        swapType2 = swapType5;
                        i10 = i17;
                        i18 = 1;
                        Integer num13 = num10;
                        kSerializerArr = kSerializerArr2;
                        num8 = num13;
                        presetRouteType6 = presetRouteType4;
                        str28 = str18;
                        orderIdTypeData3 = orderIdTypeData6;
                        i4 = i10;
                        num3 = num8;
                        orderIdTypeData6 = orderIdTypeData3;
                        i17 = i4;
                        mergeCallData4 = mergeCallData2;
                        swapType5 = swapType2;
                        kSerializerArr2 = kSerializerArr;
                        slippageMode4 = slippageMode2;
                        num10 = num3;
                        i16 = 32;
                        break;
                    default:
                        throw new UnknownFieldException(iDecodeElementIndex);
                }
            }
            SlippageMode slippageMode5 = slippageMode4;
            TransactionBean.SwapType swapType6 = swapType5;
            str = str27;
            orderIdTypeData = orderIdTypeData6;
            num = num10;
            str2 = str24;
            str3 = str25;
            bool = bool3;
            z = zDecodeBooleanElement8;
            mergeCallData = mergeCallData4;
            swapType = swapType6;
            str4 = strDecodeStringElement20;
            str5 = strDecodeStringElement12;
            str6 = str28;
            str7 = strDecodeStringElement13;
            serviceFeeInfo = serviceFeeInfo3;
            str8 = strDecodeStringElement14;
            str9 = strDecodeStringElement15;
            str10 = strDecodeStringElement16;
            str11 = strDecodeStringElement18;
            str12 = strDecodeStringElement19;
            z2 = zDecodeBooleanElement6;
            j = jDecodeLongElement2;
            i = i18;
            slippageMode = slippageMode5;
            accountInfo = accountInfo3;
            quotePriceRes = quotePriceRes3;
            i2 = i17;
            slippageFeeType = slippageFeeType3;
            teeSaStatus = teeSaStatus7;
            presetRouteType = presetRouteType6;
            str13 = strDecodeStringElement11;
            transactionType = transactionType5;
            str14 = strDecodeStringElement17;
            z3 = zDecodeBooleanElement7;
            zDecodeBooleanElement = zDecodeBooleanElement5;
            str15 = str26;
        }
        compositeDecoderBeginStructure.endStructure(serialDescriptor);
        return new TransactionBean(i2, i, str, str12, z3, str11, str14, quotePriceRes, str10, str9, str8, transactionType, orderIdTypeData, str13, str4, num, z, z2, j, str7, swapType, mergeCallData, serviceFeeInfo, slippageMode, str2, slippageFeeType, str6, bool, str3, str5, str15, accountInfo, presetRouteType, teeSaStatus, zDecodeBooleanElement, (SerializationConstructorMarker) null);
    }

    /* JADX DEBUG: Method merged with bridge method: serialize(Lkotlinx/serialization/encoding/Encoder;Ljava/lang/Object;)V */
    @Override // kotlinx.serialization.SerializationStrategy
    public final void serialize(@NotNull Encoder encoder, @NotNull TransactionBean transactionBean) {
        Intrinsics.checkNotNullParameter(encoder, "");
        Intrinsics.checkNotNullParameter(transactionBean, "");
        SerialDescriptor serialDescriptor = descriptor;
        CompositeEncoder compositeEncoderBeginStructure = encoder.beginStructure(serialDescriptor);
        TransactionBean.write$Self$OKDex_dex_impl(transactionBean, compositeEncoderBeginStructure, serialDescriptor);
        compositeEncoderBeginStructure.endStructure(serialDescriptor);
    }
}
