package uniffi.account;

import com.sun.jna.Structure;
import kotlin.jvm.internal.DefaultConstructorMarker;
import kotlin.jvm.internal.Intrinsics;
import org.jetbrains.annotations.NotNull;
import uniffi.UniffiCallbackInterfaceClone;
import uniffi.UniffiCallbackInterfaceFree;

/* JADX INFO: loaded from: classes13.dex */
@Structure.FieldOrder({"uniffiFree", "uniffiClone", "checkDevicePasscode", "isProtectionKeyAvailable", "showDevicePasscodeForLockout", "verifyUserPresence", "getProtectionPublicKey", "decryptWithProtectionKey", "removeProtectionKey", "storeEncryptedPasskey", "loadEncryptedPasskey", "loadEncryptedPasskeyByCredentialId", "removeEncryptedPasskey", "hasEncryptedPasskey"})
public class UniffiVTableCallbackInterfaceNativePasskeyKeyProvider extends Structure {
    public static final int $stable = 8;
    public UniffiCallbackInterfaceNativePasskeyKeyProviderMethod0 checkDevicePasscode;
    public UniffiCallbackInterfaceNativePasskeyKeyProviderMethod5 decryptWithProtectionKey;
    public UniffiCallbackInterfaceNativePasskeyKeyProviderMethod4 getProtectionPublicKey;
    public UniffiCallbackInterfaceNativePasskeyKeyProviderMethod11 hasEncryptedPasskey;
    public UniffiCallbackInterfaceNativePasskeyKeyProviderMethod1 isProtectionKeyAvailable;
    public UniffiCallbackInterfaceNativePasskeyKeyProviderMethod8 loadEncryptedPasskey;
    public UniffiCallbackInterfaceNativePasskeyKeyProviderMethod9 loadEncryptedPasskeyByCredentialId;
    public UniffiCallbackInterfaceNativePasskeyKeyProviderMethod10 removeEncryptedPasskey;
    public UniffiCallbackInterfaceNativePasskeyKeyProviderMethod6 removeProtectionKey;
    public UniffiCallbackInterfaceNativePasskeyKeyProviderMethod2 showDevicePasscodeForLockout;
    public UniffiCallbackInterfaceNativePasskeyKeyProviderMethod7 storeEncryptedPasskey;
    public UniffiCallbackInterfaceClone uniffiClone;
    public UniffiCallbackInterfaceFree uniffiFree;
    public UniffiCallbackInterfaceNativePasskeyKeyProviderMethod3 verifyUserPresence;

    /* JADX DEBUG: Don't trust debug lines info. Lines numbers was adjusted: min line is 0 */
    public UniffiVTableCallbackInterfaceNativePasskeyKeyProvider() {
        this(null, null, null, null, null, null, null, null, null, null, null, null, null, null, 16383, null);
    }

    /* JADX DEBUG: Can't inline method, not implemented redirect type for insn: 0x0090: CONSTRUCTOR 
  (wrap:uniffi.UniffiCallbackInterfaceFree:?: TERNARY null = ((wrap:int:0x0002: ARITH (r30v0 int) & (1 int) A[WRAPPED]) != (0 int)) ? (null uniffi.UniffiCallbackInterfaceFree) : (r16v0 uniffi.UniffiCallbackInterfaceFree))
  (wrap:uniffi.UniffiCallbackInterfaceClone:?: TERNARY null = ((wrap:int:0x000b: ARITH (r30v0 int) & (2 int) A[WRAPPED]) != (0 int)) ? (null uniffi.UniffiCallbackInterfaceClone) : (r17v0 uniffi.UniffiCallbackInterfaceClone))
  (wrap:uniffi.account.UniffiCallbackInterfaceNativePasskeyKeyProviderMethod0:?: TERNARY null = ((wrap:int:0x0013: ARITH (r30v0 int) & (4 int) A[WRAPPED]) != (0 int)) ? (null uniffi.account.UniffiCallbackInterfaceNativePasskeyKeyProviderMethod0) : (r18v0 uniffi.account.UniffiCallbackInterfaceNativePasskeyKeyProviderMethod0))
  (wrap:uniffi.account.UniffiCallbackInterfaceNativePasskeyKeyProviderMethod1:?: TERNARY null = ((wrap:int:0x001b: ARITH (r30v0 int) & (8 int) A[WRAPPED]) != (0 int)) ? (null uniffi.account.UniffiCallbackInterfaceNativePasskeyKeyProviderMethod1) : (r19v0 uniffi.account.UniffiCallbackInterfaceNativePasskeyKeyProviderMethod1))
  (wrap:uniffi.account.UniffiCallbackInterfaceNativePasskeyKeyProviderMethod2:?: TERNARY null = ((wrap:int:0x0023: ARITH (r30v0 int) & (16 int) A[WRAPPED]) != (0 int)) ? (null uniffi.account.UniffiCallbackInterfaceNativePasskeyKeyProviderMethod2) : (r20v0 uniffi.account.UniffiCallbackInterfaceNativePasskeyKeyProviderMethod2))
  (wrap:uniffi.account.UniffiCallbackInterfaceNativePasskeyKeyProviderMethod3:?: TERNARY null = ((wrap:int:0x002b: ARITH (r30v0 int) & (32 int) A[WRAPPED]) != (0 int)) ? (null uniffi.account.UniffiCallbackInterfaceNativePasskeyKeyProviderMethod3) : (r21v0 uniffi.account.UniffiCallbackInterfaceNativePasskeyKeyProviderMethod3))
  (wrap:uniffi.account.UniffiCallbackInterfaceNativePasskeyKeyProviderMethod4:?: TERNARY null = ((wrap:int:0x0033: ARITH (r30v0 int) & (64 int) A[WRAPPED]) != (0 int)) ? (null uniffi.account.UniffiCallbackInterfaceNativePasskeyKeyProviderMethod4) : (r22v0 uniffi.account.UniffiCallbackInterfaceNativePasskeyKeyProviderMethod4))
  (wrap:uniffi.account.UniffiCallbackInterfaceNativePasskeyKeyProviderMethod5:?: TERNARY null = ((wrap:int:0x003b: ARITH (r30v0 int) & (128 int) A[WRAPPED]) != (0 int)) ? (null uniffi.account.UniffiCallbackInterfaceNativePasskeyKeyProviderMethod5) : (r23v0 uniffi.account.UniffiCallbackInterfaceNativePasskeyKeyProviderMethod5))
  (wrap:uniffi.account.UniffiCallbackInterfaceNativePasskeyKeyProviderMethod6:?: TERNARY null = ((wrap:int:0x0043: ARITH (r30v0 int) & (256 int) A[WRAPPED]) != (0 int)) ? (null uniffi.account.UniffiCallbackInterfaceNativePasskeyKeyProviderMethod6) : (r24v0 uniffi.account.UniffiCallbackInterfaceNativePasskeyKeyProviderMethod6))
  (wrap:uniffi.account.UniffiCallbackInterfaceNativePasskeyKeyProviderMethod7:?: TERNARY null = ((wrap:int:0x004b: ARITH (r30v0 int) & (512 int) A[WRAPPED]) != (0 int)) ? (null uniffi.account.UniffiCallbackInterfaceNativePasskeyKeyProviderMethod7) : (r25v0 uniffi.account.UniffiCallbackInterfaceNativePasskeyKeyProviderMethod7))
  (wrap:uniffi.account.UniffiCallbackInterfaceNativePasskeyKeyProviderMethod8:?: TERNARY null = ((wrap:int:0x0053: ARITH (r30v0 int) & (1024 int) A[WRAPPED]) != (0 int)) ? (null uniffi.account.UniffiCallbackInterfaceNativePasskeyKeyProviderMethod8) : (r26v0 uniffi.account.UniffiCallbackInterfaceNativePasskeyKeyProviderMethod8))
  (wrap:uniffi.account.UniffiCallbackInterfaceNativePasskeyKeyProviderMethod9:?: TERNARY null = ((wrap:int:0x005b: ARITH (r30v0 int) & (2048 int) A[WRAPPED]) != (0 int)) ? (null uniffi.account.UniffiCallbackInterfaceNativePasskeyKeyProviderMethod9) : (r27v0 uniffi.account.UniffiCallbackInterfaceNativePasskeyKeyProviderMethod9))
  (wrap:uniffi.account.UniffiCallbackInterfaceNativePasskeyKeyProviderMethod10:?: TERNARY null = ((wrap:int:0x0063: ARITH (r30v0 int) & (4096 int) A[WRAPPED]) != (0 int)) ? (null uniffi.account.UniffiCallbackInterfaceNativePasskeyKeyProviderMethod10) : (r28v0 uniffi.account.UniffiCallbackInterfaceNativePasskeyKeyProviderMethod10))
  (wrap:uniffi.account.UniffiCallbackInterfaceNativePasskeyKeyProviderMethod11:?: TERNARY null = ((wrap:int:0x006b: ARITH (r30v0 int) & (8192 int) A[WRAPPED]) == (0 int)) ? (r29v0 uniffi.account.UniffiCallbackInterfaceNativePasskeyKeyProviderMethod11) : (null uniffi.account.UniffiCallbackInterfaceNativePasskeyKeyProviderMethod11))
 A[MD:(uniffi.UniffiCallbackInterfaceFree, uniffi.UniffiCallbackInterfaceClone, uniffi.account.UniffiCallbackInterfaceNativePasskeyKeyProviderMethod0, uniffi.account.UniffiCallbackInterfaceNativePasskeyKeyProviderMethod1, uniffi.account.UniffiCallbackInterfaceNativePasskeyKeyProviderMethod2, uniffi.account.UniffiCallbackInterfaceNativePasskeyKeyProviderMethod3, uniffi.account.UniffiCallbackInterfaceNativePasskeyKeyProviderMethod4, uniffi.account.UniffiCallbackInterfaceNativePasskeyKeyProviderMethod5, uniffi.account.UniffiCallbackInterfaceNativePasskeyKeyProviderMethod6, uniffi.account.UniffiCallbackInterfaceNativePasskeyKeyProviderMethod7, uniffi.account.UniffiCallbackInterfaceNativePasskeyKeyProviderMethod8, uniffi.account.UniffiCallbackInterfaceNativePasskeyKeyProviderMethod9, uniffi.account.UniffiCallbackInterfaceNativePasskeyKeyProviderMethod10, uniffi.account.UniffiCallbackInterfaceNativePasskeyKeyProviderMethod11):void (m)] (LINE:1108) call: uniffi.account.UniffiVTableCallbackInterfaceNativePasskeyKeyProvider.<init>(uniffi.UniffiCallbackInterfaceFree, uniffi.UniffiCallbackInterfaceClone, uniffi.account.UniffiCallbackInterfaceNativePasskeyKeyProviderMethod0, uniffi.account.UniffiCallbackInterfaceNativePasskeyKeyProviderMethod1, uniffi.account.UniffiCallbackInterfaceNativePasskeyKeyProviderMethod2, uniffi.account.UniffiCallbackInterfaceNativePasskeyKeyProviderMethod3, uniffi.account.UniffiCallbackInterfaceNativePasskeyKeyProviderMethod4, uniffi.account.UniffiCallbackInterfaceNativePasskeyKeyProviderMethod5, uniffi.account.UniffiCallbackInterfaceNativePasskeyKeyProviderMethod6, uniffi.account.UniffiCallbackInterfaceNativePasskeyKeyProviderMethod7, uniffi.account.UniffiCallbackInterfaceNativePasskeyKeyProviderMethod8, uniffi.account.UniffiCallbackInterfaceNativePasskeyKeyProviderMethod9, uniffi.account.UniffiCallbackInterfaceNativePasskeyKeyProviderMethod10, uniffi.account.UniffiCallbackInterfaceNativePasskeyKeyProviderMethod11):void type: THIS */
    public /* synthetic */ UniffiVTableCallbackInterfaceNativePasskeyKeyProvider(UniffiCallbackInterfaceFree uniffiCallbackInterfaceFree, UniffiCallbackInterfaceClone uniffiCallbackInterfaceClone, UniffiCallbackInterfaceNativePasskeyKeyProviderMethod0 uniffiCallbackInterfaceNativePasskeyKeyProviderMethod0, UniffiCallbackInterfaceNativePasskeyKeyProviderMethod1 uniffiCallbackInterfaceNativePasskeyKeyProviderMethod1, UniffiCallbackInterfaceNativePasskeyKeyProviderMethod2 uniffiCallbackInterfaceNativePasskeyKeyProviderMethod2, UniffiCallbackInterfaceNativePasskeyKeyProviderMethod3 uniffiCallbackInterfaceNativePasskeyKeyProviderMethod3, UniffiCallbackInterfaceNativePasskeyKeyProviderMethod4 uniffiCallbackInterfaceNativePasskeyKeyProviderMethod4, UniffiCallbackInterfaceNativePasskeyKeyProviderMethod5 uniffiCallbackInterfaceNativePasskeyKeyProviderMethod5, UniffiCallbackInterfaceNativePasskeyKeyProviderMethod6 uniffiCallbackInterfaceNativePasskeyKeyProviderMethod6, UniffiCallbackInterfaceNativePasskeyKeyProviderMethod7 uniffiCallbackInterfaceNativePasskeyKeyProviderMethod7, UniffiCallbackInterfaceNativePasskeyKeyProviderMethod8 uniffiCallbackInterfaceNativePasskeyKeyProviderMethod8, UniffiCallbackInterfaceNativePasskeyKeyProviderMethod9 uniffiCallbackInterfaceNativePasskeyKeyProviderMethod9, UniffiCallbackInterfaceNativePasskeyKeyProviderMethod10 uniffiCallbackInterfaceNativePasskeyKeyProviderMethod10, UniffiCallbackInterfaceNativePasskeyKeyProviderMethod11 uniffiCallbackInterfaceNativePasskeyKeyProviderMethod11, int i, DefaultConstructorMarker defaultConstructorMarker) {
        this((i & 1) != 0 ? null : uniffiCallbackInterfaceFree, (i & 2) != 0 ? null : uniffiCallbackInterfaceClone, (i & 4) != 0 ? null : uniffiCallbackInterfaceNativePasskeyKeyProviderMethod0, (i & 8) != 0 ? null : uniffiCallbackInterfaceNativePasskeyKeyProviderMethod1, (i & 16) != 0 ? null : uniffiCallbackInterfaceNativePasskeyKeyProviderMethod2, (i & 32) != 0 ? null : uniffiCallbackInterfaceNativePasskeyKeyProviderMethod3, (i & 64) != 0 ? null : uniffiCallbackInterfaceNativePasskeyKeyProviderMethod4, (i & 128) != 0 ? null : uniffiCallbackInterfaceNativePasskeyKeyProviderMethod5, (i & 256) != 0 ? null : uniffiCallbackInterfaceNativePasskeyKeyProviderMethod6, (i & 512) != 0 ? null : uniffiCallbackInterfaceNativePasskeyKeyProviderMethod7, (i & 1024) != 0 ? null : uniffiCallbackInterfaceNativePasskeyKeyProviderMethod8, (i & 2048) != 0 ? null : uniffiCallbackInterfaceNativePasskeyKeyProviderMethod9, (i & 4096) != 0 ? null : uniffiCallbackInterfaceNativePasskeyKeyProviderMethod10, (i & 8192) == 0 ? uniffiCallbackInterfaceNativePasskeyKeyProviderMethod11 : null);
    }

    public static final class UniffiByValue extends UniffiVTableCallbackInterfaceNativePasskeyKeyProvider implements Structure.ByValue {
        public static final int $stable = 0;

        /* JADX DEBUG: Don't trust debug lines info. Lines numbers was adjusted: min line is 0 */
        public UniffiByValue() {
            this(null, null, null, null, null, null, null, null, null, null, null, null, null, null, 16383, null);
        }

        /* JADX DEBUG: Can't inline method, not implemented redirect type for insn: 0x0090: CONSTRUCTOR 
  (wrap:uniffi.UniffiCallbackInterfaceFree:?: TERNARY null = ((wrap:int:0x0002: ARITH (r30v0 int) & (1 int) A[WRAPPED]) != (0 int)) ? (null uniffi.UniffiCallbackInterfaceFree) : (r16v0 uniffi.UniffiCallbackInterfaceFree))
  (wrap:uniffi.UniffiCallbackInterfaceClone:?: TERNARY null = ((wrap:int:0x000b: ARITH (r30v0 int) & (2 int) A[WRAPPED]) != (0 int)) ? (null uniffi.UniffiCallbackInterfaceClone) : (r17v0 uniffi.UniffiCallbackInterfaceClone))
  (wrap:uniffi.account.UniffiCallbackInterfaceNativePasskeyKeyProviderMethod0:?: TERNARY null = ((wrap:int:0x0013: ARITH (r30v0 int) & (4 int) A[WRAPPED]) != (0 int)) ? (null uniffi.account.UniffiCallbackInterfaceNativePasskeyKeyProviderMethod0) : (r18v0 uniffi.account.UniffiCallbackInterfaceNativePasskeyKeyProviderMethod0))
  (wrap:uniffi.account.UniffiCallbackInterfaceNativePasskeyKeyProviderMethod1:?: TERNARY null = ((wrap:int:0x001b: ARITH (r30v0 int) & (8 int) A[WRAPPED]) != (0 int)) ? (null uniffi.account.UniffiCallbackInterfaceNativePasskeyKeyProviderMethod1) : (r19v0 uniffi.account.UniffiCallbackInterfaceNativePasskeyKeyProviderMethod1))
  (wrap:uniffi.account.UniffiCallbackInterfaceNativePasskeyKeyProviderMethod2:?: TERNARY null = ((wrap:int:0x0023: ARITH (r30v0 int) & (16 int) A[WRAPPED]) != (0 int)) ? (null uniffi.account.UniffiCallbackInterfaceNativePasskeyKeyProviderMethod2) : (r20v0 uniffi.account.UniffiCallbackInterfaceNativePasskeyKeyProviderMethod2))
  (wrap:uniffi.account.UniffiCallbackInterfaceNativePasskeyKeyProviderMethod3:?: TERNARY null = ((wrap:int:0x002b: ARITH (r30v0 int) & (32 int) A[WRAPPED]) != (0 int)) ? (null uniffi.account.UniffiCallbackInterfaceNativePasskeyKeyProviderMethod3) : (r21v0 uniffi.account.UniffiCallbackInterfaceNativePasskeyKeyProviderMethod3))
  (wrap:uniffi.account.UniffiCallbackInterfaceNativePasskeyKeyProviderMethod4:?: TERNARY null = ((wrap:int:0x0033: ARITH (r30v0 int) & (64 int) A[WRAPPED]) != (0 int)) ? (null uniffi.account.UniffiCallbackInterfaceNativePasskeyKeyProviderMethod4) : (r22v0 uniffi.account.UniffiCallbackInterfaceNativePasskeyKeyProviderMethod4))
  (wrap:uniffi.account.UniffiCallbackInterfaceNativePasskeyKeyProviderMethod5:?: TERNARY null = ((wrap:int:0x003b: ARITH (r30v0 int) & (128 int) A[WRAPPED]) != (0 int)) ? (null uniffi.account.UniffiCallbackInterfaceNativePasskeyKeyProviderMethod5) : (r23v0 uniffi.account.UniffiCallbackInterfaceNativePasskeyKeyProviderMethod5))
  (wrap:uniffi.account.UniffiCallbackInterfaceNativePasskeyKeyProviderMethod6:?: TERNARY null = ((wrap:int:0x0043: ARITH (r30v0 int) & (256 int) A[WRAPPED]) != (0 int)) ? (null uniffi.account.UniffiCallbackInterfaceNativePasskeyKeyProviderMethod6) : (r24v0 uniffi.account.UniffiCallbackInterfaceNativePasskeyKeyProviderMethod6))
  (wrap:uniffi.account.UniffiCallbackInterfaceNativePasskeyKeyProviderMethod7:?: TERNARY null = ((wrap:int:0x004b: ARITH (r30v0 int) & (512 int) A[WRAPPED]) != (0 int)) ? (null uniffi.account.UniffiCallbackInterfaceNativePasskeyKeyProviderMethod7) : (r25v0 uniffi.account.UniffiCallbackInterfaceNativePasskeyKeyProviderMethod7))
  (wrap:uniffi.account.UniffiCallbackInterfaceNativePasskeyKeyProviderMethod8:?: TERNARY null = ((wrap:int:0x0053: ARITH (r30v0 int) & (1024 int) A[WRAPPED]) != (0 int)) ? (null uniffi.account.UniffiCallbackInterfaceNativePasskeyKeyProviderMethod8) : (r26v0 uniffi.account.UniffiCallbackInterfaceNativePasskeyKeyProviderMethod8))
  (wrap:uniffi.account.UniffiCallbackInterfaceNativePasskeyKeyProviderMethod9:?: TERNARY null = ((wrap:int:0x005b: ARITH (r30v0 int) & (2048 int) A[WRAPPED]) != (0 int)) ? (null uniffi.account.UniffiCallbackInterfaceNativePasskeyKeyProviderMethod9) : (r27v0 uniffi.account.UniffiCallbackInterfaceNativePasskeyKeyProviderMethod9))
  (wrap:uniffi.account.UniffiCallbackInterfaceNativePasskeyKeyProviderMethod10:?: TERNARY null = ((wrap:int:0x0063: ARITH (r30v0 int) & (4096 int) A[WRAPPED]) != (0 int)) ? (null uniffi.account.UniffiCallbackInterfaceNativePasskeyKeyProviderMethod10) : (r28v0 uniffi.account.UniffiCallbackInterfaceNativePasskeyKeyProviderMethod10))
  (wrap:uniffi.account.UniffiCallbackInterfaceNativePasskeyKeyProviderMethod11:?: TERNARY null = ((wrap:int:0x006b: ARITH (r30v0 int) & (8192 int) A[WRAPPED]) == (0 int)) ? (r29v0 uniffi.account.UniffiCallbackInterfaceNativePasskeyKeyProviderMethod11) : (null uniffi.account.UniffiCallbackInterfaceNativePasskeyKeyProviderMethod11))
 A[MD:(uniffi.UniffiCallbackInterfaceFree, uniffi.UniffiCallbackInterfaceClone, uniffi.account.UniffiCallbackInterfaceNativePasskeyKeyProviderMethod0, uniffi.account.UniffiCallbackInterfaceNativePasskeyKeyProviderMethod1, uniffi.account.UniffiCallbackInterfaceNativePasskeyKeyProviderMethod2, uniffi.account.UniffiCallbackInterfaceNativePasskeyKeyProviderMethod3, uniffi.account.UniffiCallbackInterfaceNativePasskeyKeyProviderMethod4, uniffi.account.UniffiCallbackInterfaceNativePasskeyKeyProviderMethod5, uniffi.account.UniffiCallbackInterfaceNativePasskeyKeyProviderMethod6, uniffi.account.UniffiCallbackInterfaceNativePasskeyKeyProviderMethod7, uniffi.account.UniffiCallbackInterfaceNativePasskeyKeyProviderMethod8, uniffi.account.UniffiCallbackInterfaceNativePasskeyKeyProviderMethod9, uniffi.account.UniffiCallbackInterfaceNativePasskeyKeyProviderMethod10, uniffi.account.UniffiCallbackInterfaceNativePasskeyKeyProviderMethod11):void (m)] (LINE:1124) call: uniffi.account.UniffiVTableCallbackInterfaceNativePasskeyKeyProvider.UniffiByValue.<init>(uniffi.UniffiCallbackInterfaceFree, uniffi.UniffiCallbackInterfaceClone, uniffi.account.UniffiCallbackInterfaceNativePasskeyKeyProviderMethod0, uniffi.account.UniffiCallbackInterfaceNativePasskeyKeyProviderMethod1, uniffi.account.UniffiCallbackInterfaceNativePasskeyKeyProviderMethod2, uniffi.account.UniffiCallbackInterfaceNativePasskeyKeyProviderMethod3, uniffi.account.UniffiCallbackInterfaceNativePasskeyKeyProviderMethod4, uniffi.account.UniffiCallbackInterfaceNativePasskeyKeyProviderMethod5, uniffi.account.UniffiCallbackInterfaceNativePasskeyKeyProviderMethod6, uniffi.account.UniffiCallbackInterfaceNativePasskeyKeyProviderMethod7, uniffi.account.UniffiCallbackInterfaceNativePasskeyKeyProviderMethod8, uniffi.account.UniffiCallbackInterfaceNativePasskeyKeyProviderMethod9, uniffi.account.UniffiCallbackInterfaceNativePasskeyKeyProviderMethod10, uniffi.account.UniffiCallbackInterfaceNativePasskeyKeyProviderMethod11):void type: THIS */
        public /* synthetic */ UniffiByValue(UniffiCallbackInterfaceFree uniffiCallbackInterfaceFree, UniffiCallbackInterfaceClone uniffiCallbackInterfaceClone, UniffiCallbackInterfaceNativePasskeyKeyProviderMethod0 uniffiCallbackInterfaceNativePasskeyKeyProviderMethod0, UniffiCallbackInterfaceNativePasskeyKeyProviderMethod1 uniffiCallbackInterfaceNativePasskeyKeyProviderMethod1, UniffiCallbackInterfaceNativePasskeyKeyProviderMethod2 uniffiCallbackInterfaceNativePasskeyKeyProviderMethod2, UniffiCallbackInterfaceNativePasskeyKeyProviderMethod3 uniffiCallbackInterfaceNativePasskeyKeyProviderMethod3, UniffiCallbackInterfaceNativePasskeyKeyProviderMethod4 uniffiCallbackInterfaceNativePasskeyKeyProviderMethod4, UniffiCallbackInterfaceNativePasskeyKeyProviderMethod5 uniffiCallbackInterfaceNativePasskeyKeyProviderMethod5, UniffiCallbackInterfaceNativePasskeyKeyProviderMethod6 uniffiCallbackInterfaceNativePasskeyKeyProviderMethod6, UniffiCallbackInterfaceNativePasskeyKeyProviderMethod7 uniffiCallbackInterfaceNativePasskeyKeyProviderMethod7, UniffiCallbackInterfaceNativePasskeyKeyProviderMethod8 uniffiCallbackInterfaceNativePasskeyKeyProviderMethod8, UniffiCallbackInterfaceNativePasskeyKeyProviderMethod9 uniffiCallbackInterfaceNativePasskeyKeyProviderMethod9, UniffiCallbackInterfaceNativePasskeyKeyProviderMethod10 uniffiCallbackInterfaceNativePasskeyKeyProviderMethod10, UniffiCallbackInterfaceNativePasskeyKeyProviderMethod11 uniffiCallbackInterfaceNativePasskeyKeyProviderMethod11, int i, DefaultConstructorMarker defaultConstructorMarker) {
            this((i & 1) != 0 ? null : uniffiCallbackInterfaceFree, (i & 2) != 0 ? null : uniffiCallbackInterfaceClone, (i & 4) != 0 ? null : uniffiCallbackInterfaceNativePasskeyKeyProviderMethod0, (i & 8) != 0 ? null : uniffiCallbackInterfaceNativePasskeyKeyProviderMethod1, (i & 16) != 0 ? null : uniffiCallbackInterfaceNativePasskeyKeyProviderMethod2, (i & 32) != 0 ? null : uniffiCallbackInterfaceNativePasskeyKeyProviderMethod3, (i & 64) != 0 ? null : uniffiCallbackInterfaceNativePasskeyKeyProviderMethod4, (i & 128) != 0 ? null : uniffiCallbackInterfaceNativePasskeyKeyProviderMethod5, (i & 256) != 0 ? null : uniffiCallbackInterfaceNativePasskeyKeyProviderMethod6, (i & 512) != 0 ? null : uniffiCallbackInterfaceNativePasskeyKeyProviderMethod7, (i & 1024) != 0 ? null : uniffiCallbackInterfaceNativePasskeyKeyProviderMethod8, (i & 2048) != 0 ? null : uniffiCallbackInterfaceNativePasskeyKeyProviderMethod9, (i & 4096) != 0 ? null : uniffiCallbackInterfaceNativePasskeyKeyProviderMethod10, (i & 8192) == 0 ? uniffiCallbackInterfaceNativePasskeyKeyProviderMethod11 : null);
        }

        public UniffiByValue(UniffiCallbackInterfaceFree uniffiCallbackInterfaceFree, UniffiCallbackInterfaceClone uniffiCallbackInterfaceClone, UniffiCallbackInterfaceNativePasskeyKeyProviderMethod0 uniffiCallbackInterfaceNativePasskeyKeyProviderMethod0, UniffiCallbackInterfaceNativePasskeyKeyProviderMethod1 uniffiCallbackInterfaceNativePasskeyKeyProviderMethod1, UniffiCallbackInterfaceNativePasskeyKeyProviderMethod2 uniffiCallbackInterfaceNativePasskeyKeyProviderMethod2, UniffiCallbackInterfaceNativePasskeyKeyProviderMethod3 uniffiCallbackInterfaceNativePasskeyKeyProviderMethod3, UniffiCallbackInterfaceNativePasskeyKeyProviderMethod4 uniffiCallbackInterfaceNativePasskeyKeyProviderMethod4, UniffiCallbackInterfaceNativePasskeyKeyProviderMethod5 uniffiCallbackInterfaceNativePasskeyKeyProviderMethod5, UniffiCallbackInterfaceNativePasskeyKeyProviderMethod6 uniffiCallbackInterfaceNativePasskeyKeyProviderMethod6, UniffiCallbackInterfaceNativePasskeyKeyProviderMethod7 uniffiCallbackInterfaceNativePasskeyKeyProviderMethod7, UniffiCallbackInterfaceNativePasskeyKeyProviderMethod8 uniffiCallbackInterfaceNativePasskeyKeyProviderMethod8, UniffiCallbackInterfaceNativePasskeyKeyProviderMethod9 uniffiCallbackInterfaceNativePasskeyKeyProviderMethod9, UniffiCallbackInterfaceNativePasskeyKeyProviderMethod10 uniffiCallbackInterfaceNativePasskeyKeyProviderMethod10, UniffiCallbackInterfaceNativePasskeyKeyProviderMethod11 uniffiCallbackInterfaceNativePasskeyKeyProviderMethod11) {
            super(uniffiCallbackInterfaceFree, uniffiCallbackInterfaceClone, uniffiCallbackInterfaceNativePasskeyKeyProviderMethod0, uniffiCallbackInterfaceNativePasskeyKeyProviderMethod1, uniffiCallbackInterfaceNativePasskeyKeyProviderMethod2, uniffiCallbackInterfaceNativePasskeyKeyProviderMethod3, uniffiCallbackInterfaceNativePasskeyKeyProviderMethod4, uniffiCallbackInterfaceNativePasskeyKeyProviderMethod5, uniffiCallbackInterfaceNativePasskeyKeyProviderMethod6, uniffiCallbackInterfaceNativePasskeyKeyProviderMethod7, uniffiCallbackInterfaceNativePasskeyKeyProviderMethod8, uniffiCallbackInterfaceNativePasskeyKeyProviderMethod9, uniffiCallbackInterfaceNativePasskeyKeyProviderMethod10, uniffiCallbackInterfaceNativePasskeyKeyProviderMethod11);
        }
    }

    public UniffiVTableCallbackInterfaceNativePasskeyKeyProvider(UniffiCallbackInterfaceFree uniffiCallbackInterfaceFree, UniffiCallbackInterfaceClone uniffiCallbackInterfaceClone, UniffiCallbackInterfaceNativePasskeyKeyProviderMethod0 uniffiCallbackInterfaceNativePasskeyKeyProviderMethod0, UniffiCallbackInterfaceNativePasskeyKeyProviderMethod1 uniffiCallbackInterfaceNativePasskeyKeyProviderMethod1, UniffiCallbackInterfaceNativePasskeyKeyProviderMethod2 uniffiCallbackInterfaceNativePasskeyKeyProviderMethod2, UniffiCallbackInterfaceNativePasskeyKeyProviderMethod3 uniffiCallbackInterfaceNativePasskeyKeyProviderMethod3, UniffiCallbackInterfaceNativePasskeyKeyProviderMethod4 uniffiCallbackInterfaceNativePasskeyKeyProviderMethod4, UniffiCallbackInterfaceNativePasskeyKeyProviderMethod5 uniffiCallbackInterfaceNativePasskeyKeyProviderMethod5, UniffiCallbackInterfaceNativePasskeyKeyProviderMethod6 uniffiCallbackInterfaceNativePasskeyKeyProviderMethod6, UniffiCallbackInterfaceNativePasskeyKeyProviderMethod7 uniffiCallbackInterfaceNativePasskeyKeyProviderMethod7, UniffiCallbackInterfaceNativePasskeyKeyProviderMethod8 uniffiCallbackInterfaceNativePasskeyKeyProviderMethod8, UniffiCallbackInterfaceNativePasskeyKeyProviderMethod9 uniffiCallbackInterfaceNativePasskeyKeyProviderMethod9, UniffiCallbackInterfaceNativePasskeyKeyProviderMethod10 uniffiCallbackInterfaceNativePasskeyKeyProviderMethod10, UniffiCallbackInterfaceNativePasskeyKeyProviderMethod11 uniffiCallbackInterfaceNativePasskeyKeyProviderMethod11) {
        this.uniffiFree = uniffiCallbackInterfaceFree;
        this.uniffiClone = uniffiCallbackInterfaceClone;
        this.checkDevicePasscode = uniffiCallbackInterfaceNativePasskeyKeyProviderMethod0;
        this.isProtectionKeyAvailable = uniffiCallbackInterfaceNativePasskeyKeyProviderMethod1;
        this.showDevicePasscodeForLockout = uniffiCallbackInterfaceNativePasskeyKeyProviderMethod2;
        this.verifyUserPresence = uniffiCallbackInterfaceNativePasskeyKeyProviderMethod3;
        this.getProtectionPublicKey = uniffiCallbackInterfaceNativePasskeyKeyProviderMethod4;
        this.decryptWithProtectionKey = uniffiCallbackInterfaceNativePasskeyKeyProviderMethod5;
        this.removeProtectionKey = uniffiCallbackInterfaceNativePasskeyKeyProviderMethod6;
        this.storeEncryptedPasskey = uniffiCallbackInterfaceNativePasskeyKeyProviderMethod7;
        this.loadEncryptedPasskey = uniffiCallbackInterfaceNativePasskeyKeyProviderMethod8;
        this.loadEncryptedPasskeyByCredentialId = uniffiCallbackInterfaceNativePasskeyKeyProviderMethod9;
        this.removeEncryptedPasskey = uniffiCallbackInterfaceNativePasskeyKeyProviderMethod10;
        this.hasEncryptedPasskey = uniffiCallbackInterfaceNativePasskeyKeyProviderMethod11;
    }

    public final void uniffiSetValue$OKCore_deploy(@NotNull UniffiVTableCallbackInterfaceNativePasskeyKeyProvider uniffiVTableCallbackInterfaceNativePasskeyKeyProvider) {
        Intrinsics.checkNotNullParameter(uniffiVTableCallbackInterfaceNativePasskeyKeyProvider, "");
        this.uniffiFree = uniffiVTableCallbackInterfaceNativePasskeyKeyProvider.uniffiFree;
        this.uniffiClone = uniffiVTableCallbackInterfaceNativePasskeyKeyProvider.uniffiClone;
        this.checkDevicePasscode = uniffiVTableCallbackInterfaceNativePasskeyKeyProvider.checkDevicePasscode;
        this.isProtectionKeyAvailable = uniffiVTableCallbackInterfaceNativePasskeyKeyProvider.isProtectionKeyAvailable;
        this.showDevicePasscodeForLockout = uniffiVTableCallbackInterfaceNativePasskeyKeyProvider.showDevicePasscodeForLockout;
        this.verifyUserPresence = uniffiVTableCallbackInterfaceNativePasskeyKeyProvider.verifyUserPresence;
        this.getProtectionPublicKey = uniffiVTableCallbackInterfaceNativePasskeyKeyProvider.getProtectionPublicKey;
        this.decryptWithProtectionKey = uniffiVTableCallbackInterfaceNativePasskeyKeyProvider.decryptWithProtectionKey;
        this.removeProtectionKey = uniffiVTableCallbackInterfaceNativePasskeyKeyProvider.removeProtectionKey;
        this.storeEncryptedPasskey = uniffiVTableCallbackInterfaceNativePasskeyKeyProvider.storeEncryptedPasskey;
        this.loadEncryptedPasskey = uniffiVTableCallbackInterfaceNativePasskeyKeyProvider.loadEncryptedPasskey;
        this.loadEncryptedPasskeyByCredentialId = uniffiVTableCallbackInterfaceNativePasskeyKeyProvider.loadEncryptedPasskeyByCredentialId;
        this.removeEncryptedPasskey = uniffiVTableCallbackInterfaceNativePasskeyKeyProvider.removeEncryptedPasskey;
        this.hasEncryptedPasskey = uniffiVTableCallbackInterfaceNativePasskeyKeyProvider.hasEncryptedPasskey;
    }
}
