package com.okinc.business.web3pay.lib.features.transactionhistory.datasource.remote.http.model;

import com.google.api.client.googleapis.media.MediaHttpDownloader;
import kotlin.Unit;
import kotlin.jvm.internal.Intrinsics;
import kotlinx.serialization.KSerializer;
import kotlinx.serialization.UnknownFieldException;
import kotlinx.serialization.builtins.BuiltinSerializersKt;
import kotlinx.serialization.descriptors.SerialDescriptor;
import kotlinx.serialization.encoding.CompositeDecoder;
import kotlinx.serialization.encoding.CompositeEncoder;
import kotlinx.serialization.encoding.Decoder;
import kotlinx.serialization.encoding.Encoder;
import kotlinx.serialization.internal.BooleanSerializer;
import kotlinx.serialization.internal.GeneratedSerializer;
import kotlinx.serialization.internal.IntSerializer;
import kotlinx.serialization.internal.LongSerializer;
import kotlinx.serialization.internal.PluginGeneratedSerialDescriptor;
import kotlinx.serialization.internal.SerializationConstructorMarker;
import kotlinx.serialization.internal.StringSerializer;
import org.jetbrains.annotations.NotNull;

/* JADX INFO: loaded from: classes23.dex */
public final /* synthetic */ class CardReferralRewardsOrderDetailApiModel$$serializer implements GeneratedSerializer<CardReferralRewardsOrderDetailApiModel> {
    public static final int $stable;
    public static final CardReferralRewardsOrderDetailApiModel$$serializer INSTANCE;
    private static final SerialDescriptor descriptor;

    /* JADX DEBUG: Don't trust debug lines info. Lines numbers was adjusted: min line is 0 */
    private CardReferralRewardsOrderDetailApiModel$$serializer() {
    }

    /* JADX DEBUG: Don't trust debug lines info. Lines numbers was adjusted: min line is 0 */
    @Override // kotlinx.serialization.KSerializer, kotlinx.serialization.SerializationStrategy, kotlinx.serialization.DeserializationStrategy
    public final SerialDescriptor getDescriptor() {
        return descriptor;
    }

    static {
        CardReferralRewardsOrderDetailApiModel$$serializer cardReferralRewardsOrderDetailApiModel$$serializer = new CardReferralRewardsOrderDetailApiModel$$serializer();
        INSTANCE = cardReferralRewardsOrderDetailApiModel$$serializer;
        $stable = 8;
        PluginGeneratedSerialDescriptor pluginGeneratedSerialDescriptor = new PluginGeneratedSerialDescriptor("com.okinc.business.web3pay.lib.features.transactionhistory.datasource.remote.http.model.CardReferralRewardsOrderDetailApiModel", cardReferralRewardsOrderDetailApiModel$$serializer, 39);
        pluginGeneratedSerialDescriptor.addElement("orderId", false);
        pluginGeneratedSerialDescriptor.addElement("parentOrderId", false);
        pluginGeneratedSerialDescriptor.addElement("uopHash", true);
        pluginGeneratedSerialDescriptor.addElement("txHash", true);
        pluginGeneratedSerialDescriptor.addElement("chainIndex", false);
        pluginGeneratedSerialDescriptor.addElement("orderType", false);
        pluginGeneratedSerialDescriptor.addElement("from", true);
        pluginGeneratedSerialDescriptor.addElement("fromType", true);
        pluginGeneratedSerialDescriptor.addElement("to", true);
        pluginGeneratedSerialDescriptor.addElement("areaCode", true);
        pluginGeneratedSerialDescriptor.addElement("toType", true);
        pluginGeneratedSerialDescriptor.addElement("tokenAmount", false);
        pluginGeneratedSerialDescriptor.addElement("tokenDecimal", false);
        pluginGeneratedSerialDescriptor.addElement("tokenUsdAmount", false);
        pluginGeneratedSerialDescriptor.addElement("tokenLogo", false);
        pluginGeneratedSerialDescriptor.addElement("tokenSymbol", false);
        pluginGeneratedSerialDescriptor.addElement("tokenAddress", true);
        pluginGeneratedSerialDescriptor.addElement("tokenCoinTypeNo", true);
        pluginGeneratedSerialDescriptor.addElement("feeTokenSymbol", true);
        pluginGeneratedSerialDescriptor.addElement("feeTokenDecimal", true);
        pluginGeneratedSerialDescriptor.addElement("feeTokenAmount", true);
        pluginGeneratedSerialDescriptor.addElement("feeTokenUsdAmount", true);
        pluginGeneratedSerialDescriptor.addElement("feeTokenCoinTypeNo", true);
        pluginGeneratedSerialDescriptor.addElement("status", false);
        pluginGeneratedSerialDescriptor.addElement("failedType", true);
        pluginGeneratedSerialDescriptor.addElement("errMsg", true);
        pluginGeneratedSerialDescriptor.addElement("transferComment", true);
        pluginGeneratedSerialDescriptor.addElement("createTime", false);
        pluginGeneratedSerialDescriptor.addElement("timeToCancel", true);
        pluginGeneratedSerialDescriptor.addElement("gasPayType", false);
        pluginGeneratedSerialDescriptor.addElement("networkName", false);
        pluginGeneratedSerialDescriptor.addElement("networkLogo", false);
        pluginGeneratedSerialDescriptor.addElement("activationFeeTokenAmount", true);
        pluginGeneratedSerialDescriptor.addElement("activationFeeUsdAmount", true);
        pluginGeneratedSerialDescriptor.addElement("merchantId", true);
        pluginGeneratedSerialDescriptor.addElement("productCode", true);
        pluginGeneratedSerialDescriptor.addElement("isFreeze", true);
        pluginGeneratedSerialDescriptor.addElement("playBook", true);
        pluginGeneratedSerialDescriptor.addElement("travelRuleId", true);
        descriptor = pluginGeneratedSerialDescriptor;
    }

    @Override // kotlinx.serialization.internal.GeneratedSerializer
    public final KSerializer<?>[] childSerializers() {
        StringSerializer stringSerializer = StringSerializer.INSTANCE;
        IntSerializer intSerializer = IntSerializer.INSTANCE;
        LongSerializer longSerializer = LongSerializer.INSTANCE;
        return new KSerializer[]{stringSerializer, stringSerializer, BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), stringSerializer, intSerializer, BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(intSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(intSerializer), stringSerializer, intSerializer, stringSerializer, stringSerializer, stringSerializer, BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(intSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), intSerializer, BuiltinSerializersKt.getNullable(intSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), longSerializer, BuiltinSerializersKt.getNullable(longSerializer), intSerializer, stringSerializer, stringSerializer, BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(BooleanSerializer.INSTANCE), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer)};
    }

    /* JADX DEBUG: Method merged with bridge method: deserialize(Lkotlinx/serialization/encoding/Decoder;)Ljava/lang/Object; */
    @Override // kotlinx.serialization.DeserializationStrategy
    public final CardReferralRewardsOrderDetailApiModel deserialize(@NotNull Decoder decoder) {
        String str;
        Integer num;
        String str2;
        String str3;
        Boolean bool;
        String str4;
        String str5;
        String str6;
        String str7;
        String str8;
        String str9;
        int iDecodeIntElement;
        int i;
        String str10;
        String str11;
        String str12;
        String str13;
        String str14;
        String str15;
        String str16;
        int i2;
        Integer num2;
        String str17;
        Integer num3;
        Long l;
        String str18;
        int i3;
        String str19;
        Integer num4;
        String str20;
        String str21;
        String str22;
        String str23;
        long j;
        String str24;
        String str25;
        String str26;
        String str27;
        String str28;
        int i4;
        String str29;
        String str30;
        String str31;
        Integer num5;
        String str32;
        String str33;
        String str34;
        Integer num6;
        String str35;
        String str36;
        Integer num7;
        String str37;
        String str38;
        String str39;
        Integer num8;
        int i5;
        String str40;
        String str41;
        int i6;
        String str42;
        int i7;
        Integer num9;
        String str43;
        Integer num10;
        Integer num11;
        int i8;
        String str44;
        String str45;
        int i9;
        Boolean bool2;
        String str46;
        String str47;
        String str48;
        Long l2;
        String str49;
        int i10;
        Intrinsics.checkNotNullParameter(decoder, "");
        SerialDescriptor serialDescriptor = descriptor;
        CompositeDecoder compositeDecoderBeginStructure = decoder.beginStructure(serialDescriptor);
        int i11 = 0;
        if (compositeDecoderBeginStructure.decodeSequentially()) {
            String strDecodeStringElement = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 0);
            String strDecodeStringElement2 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 1);
            StringSerializer stringSerializer = StringSerializer.INSTANCE;
            String str50 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 2, stringSerializer, null);
            String str51 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 3, stringSerializer, null);
            String strDecodeStringElement3 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 4);
            int iDecodeIntElement2 = compositeDecoderBeginStructure.decodeIntElement(serialDescriptor, 5);
            String str52 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 6, stringSerializer, null);
            IntSerializer intSerializer = IntSerializer.INSTANCE;
            Integer num12 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 7, intSerializer, null);
            String str53 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 8, stringSerializer, null);
            String str54 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 9, stringSerializer, null);
            Integer num13 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 10, intSerializer, null);
            String strDecodeStringElement4 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 11);
            iDecodeIntElement = compositeDecoderBeginStructure.decodeIntElement(serialDescriptor, 12);
            String strDecodeStringElement5 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 13);
            String strDecodeStringElement6 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 14);
            String strDecodeStringElement7 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 15);
            String str55 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 16, stringSerializer, null);
            String str56 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 17, stringSerializer, null);
            String str57 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 18, stringSerializer, null);
            Integer num14 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 19, intSerializer, null);
            String str58 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 20, stringSerializer, null);
            String str59 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 21, stringSerializer, null);
            String str60 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 22, stringSerializer, null);
            int iDecodeIntElement3 = compositeDecoderBeginStructure.decodeIntElement(serialDescriptor, 23);
            Integer num15 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 24, intSerializer, null);
            String str61 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 25, stringSerializer, null);
            String str62 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 26, stringSerializer, null);
            long jDecodeLongElement = compositeDecoderBeginStructure.decodeLongElement(serialDescriptor, 27);
            Long l3 = (Long) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 28, LongSerializer.INSTANCE, null);
            int iDecodeIntElement4 = compositeDecoderBeginStructure.decodeIntElement(serialDescriptor, 29);
            String strDecodeStringElement8 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 30);
            String strDecodeStringElement9 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 31);
            String str63 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 32, stringSerializer, null);
            String str64 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 33, stringSerializer, null);
            String str65 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 34, stringSerializer, null);
            String str66 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 35, stringSerializer, null);
            Boolean bool3 = (Boolean) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 36, BooleanSerializer.INSTANCE, null);
            String str67 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 37, stringSerializer, null);
            String str68 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 38, stringSerializer, null);
            i11 = -1;
            str17 = str68;
            str4 = str67;
            str2 = str63;
            str19 = strDecodeStringElement9;
            str = str64;
            str25 = str65;
            str3 = str66;
            bool = bool3;
            str11 = str58;
            j = jDecodeLongElement;
            str26 = str62;
            l = l3;
            str20 = strDecodeStringElement8;
            i = iDecodeIntElement4;
            i3 = iDecodeIntElement3;
            str28 = str61;
            str10 = strDecodeStringElement7;
            str16 = str59;
            str24 = str60;
            i4 = 127;
            str9 = str54;
            str18 = str57;
            str15 = strDecodeStringElement2;
            str21 = str55;
            str8 = str53;
            i2 = iDecodeIntElement2;
            str12 = strDecodeStringElement3;
            str22 = strDecodeStringElement6;
            num = num13;
            str7 = str52;
            str23 = strDecodeStringElement;
            str6 = str51;
            str13 = strDecodeStringElement5;
            num2 = num15;
            str14 = strDecodeStringElement4;
            str5 = str56;
            num4 = num12;
            str27 = str50;
            num3 = num14;
        } else {
            String str69 = null;
            String str70 = null;
            String str71 = null;
            String str72 = null;
            Integer num16 = null;
            String str73 = null;
            Long l4 = null;
            String str74 = null;
            String str75 = null;
            String str76 = null;
            Boolean bool4 = null;
            String strDecodeStringElement10 = null;
            String strDecodeStringElement11 = null;
            String str77 = null;
            String strDecodeStringElement12 = null;
            String str78 = null;
            String str79 = null;
            String str80 = null;
            String strDecodeStringElement13 = null;
            Integer num17 = null;
            String str81 = null;
            String str82 = null;
            Integer num18 = null;
            String str83 = null;
            String strDecodeStringElement14 = null;
            String str84 = null;
            String strDecodeStringElement15 = null;
            String strDecodeStringElement16 = null;
            String strDecodeStringElement17 = null;
            String str85 = null;
            String strDecodeStringElement18 = null;
            Integer num19 = null;
            String str86 = null;
            boolean z = true;
            int i12 = 0;
            int i13 = 0;
            int i14 = 0;
            int iDecodeIntElement5 = 0;
            long jDecodeLongElement2 = 0;
            String str87 = null;
            int iDecodeIntElement6 = 0;
            while (z) {
                String str88 = str87;
                int iDecodeElementIndex = compositeDecoderBeginStructure.decodeElementIndex(serialDescriptor);
                switch (iDecodeElementIndex) {
                    case -1:
                        str29 = str70;
                        str30 = str71;
                        str31 = str69;
                        num5 = num16;
                        str32 = str77;
                        str33 = str79;
                        str34 = str80;
                        num6 = num17;
                        str35 = str81;
                        str36 = str82;
                        num7 = num18;
                        str37 = str83;
                        str38 = str84;
                        str39 = str85;
                        num8 = num19;
                        Unit unit = Unit.INSTANCE;
                        z = false;
                        str85 = str39;
                        i5 = i13;
                        i13 = i5;
                        num9 = num6;
                        num19 = num8;
                        str69 = str31;
                        str87 = str88;
                        num16 = num5;
                        str71 = str30;
                        str79 = str33;
                        str80 = str34;
                        num17 = num9;
                        str84 = str38;
                        str83 = str37;
                        num18 = num7;
                        str82 = str36;
                        str81 = str35;
                        str77 = str32;
                        str70 = str29;
                        break;
                    case 0:
                        str29 = str70;
                        str30 = str71;
                        str31 = str69;
                        num5 = num16;
                        str32 = str77;
                        str33 = str79;
                        str34 = str80;
                        num6 = num17;
                        str35 = str81;
                        str36 = str82;
                        num7 = num18;
                        str37 = str83;
                        str38 = str84;
                        str39 = str85;
                        num8 = num19;
                        strDecodeStringElement18 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 0);
                        i11 |= 1;
                        Unit unit2 = Unit.INSTANCE;
                        str85 = str39;
                        i5 = i13;
                        i13 = i5;
                        num9 = num6;
                        num19 = num8;
                        str69 = str31;
                        str87 = str88;
                        num16 = num5;
                        str71 = str30;
                        str79 = str33;
                        str80 = str34;
                        num17 = num9;
                        str84 = str38;
                        str83 = str37;
                        num18 = num7;
                        str82 = str36;
                        str81 = str35;
                        str77 = str32;
                        str70 = str29;
                        break;
                    case 1:
                        str29 = str70;
                        str30 = str71;
                        str31 = str69;
                        num5 = num16;
                        str32 = str77;
                        str33 = str79;
                        str34 = str80;
                        num6 = num17;
                        str35 = str81;
                        str36 = str82;
                        num7 = num18;
                        str37 = str83;
                        str38 = str84;
                        num8 = num19;
                        strDecodeStringElement17 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 1);
                        i11 |= 2;
                        Unit unit3 = Unit.INSTANCE;
                        i5 = i13;
                        i13 = i5;
                        num9 = num6;
                        num19 = num8;
                        str69 = str31;
                        str87 = str88;
                        num16 = num5;
                        str71 = str30;
                        str79 = str33;
                        str80 = str34;
                        num17 = num9;
                        str84 = str38;
                        str83 = str37;
                        num18 = num7;
                        str82 = str36;
                        str81 = str35;
                        str77 = str32;
                        str70 = str29;
                        break;
                    case 2:
                        str29 = str70;
                        str30 = str71;
                        str31 = str69;
                        num5 = num16;
                        str32 = str77;
                        str33 = str79;
                        str34 = str80;
                        num6 = num17;
                        str35 = str81;
                        str36 = str82;
                        num7 = num18;
                        str37 = str83;
                        num8 = num19;
                        str38 = str84;
                        str85 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 2, StringSerializer.INSTANCE, str85);
                        Unit unit4 = Unit.INSTANCE;
                        i11 |= 4;
                        i5 = i13;
                        i13 = i5;
                        num9 = num6;
                        num19 = num8;
                        str69 = str31;
                        str87 = str88;
                        num16 = num5;
                        str71 = str30;
                        str79 = str33;
                        str80 = str34;
                        num17 = num9;
                        str84 = str38;
                        str83 = str37;
                        num18 = num7;
                        str82 = str36;
                        str81 = str35;
                        str77 = str32;
                        str70 = str29;
                        break;
                    case 3:
                        str29 = str70;
                        str30 = str71;
                        str31 = str69;
                        num5 = num16;
                        str32 = str77;
                        str33 = str79;
                        str34 = str80;
                        num6 = num17;
                        str35 = str81;
                        str36 = str82;
                        num7 = num18;
                        num8 = num19;
                        str37 = str83;
                        str84 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 3, StringSerializer.INSTANCE, str84);
                        Unit unit5 = Unit.INSTANCE;
                        i11 |= 8;
                        i5 = i13;
                        str38 = str84;
                        i13 = i5;
                        num9 = num6;
                        num19 = num8;
                        str69 = str31;
                        str87 = str88;
                        num16 = num5;
                        str71 = str30;
                        str79 = str33;
                        str80 = str34;
                        num17 = num9;
                        str84 = str38;
                        str83 = str37;
                        num18 = num7;
                        str82 = str36;
                        str81 = str35;
                        str77 = str32;
                        str70 = str29;
                        break;
                    case 4:
                        str29 = str70;
                        str30 = str71;
                        str31 = str69;
                        num5 = num16;
                        str32 = str77;
                        str33 = str79;
                        str34 = str80;
                        num6 = num17;
                        str35 = str81;
                        str36 = str82;
                        num7 = num18;
                        str40 = str83;
                        num8 = num19;
                        strDecodeStringElement14 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 4);
                        i11 |= 16;
                        Unit unit6 = Unit.INSTANCE;
                        str83 = str40;
                        i5 = i13;
                        str37 = str83;
                        str38 = str84;
                        i13 = i5;
                        num9 = num6;
                        num19 = num8;
                        str69 = str31;
                        str87 = str88;
                        num16 = num5;
                        str71 = str30;
                        str79 = str33;
                        str80 = str34;
                        num17 = num9;
                        str84 = str38;
                        str83 = str37;
                        num18 = num7;
                        str82 = str36;
                        str81 = str35;
                        str77 = str32;
                        str70 = str29;
                        break;
                    case 5:
                        str29 = str70;
                        str30 = str71;
                        str31 = str69;
                        num5 = num16;
                        str32 = str77;
                        str33 = str79;
                        str34 = str80;
                        num6 = num17;
                        str35 = str81;
                        str36 = str82;
                        num7 = num18;
                        str40 = str83;
                        num8 = num19;
                        iDecodeIntElement5 = compositeDecoderBeginStructure.decodeIntElement(serialDescriptor, 5);
                        i11 |= 32;
                        Unit unit7 = Unit.INSTANCE;
                        str83 = str40;
                        i5 = i13;
                        str37 = str83;
                        str38 = str84;
                        i13 = i5;
                        num9 = num6;
                        num19 = num8;
                        str69 = str31;
                        str87 = str88;
                        num16 = num5;
                        str71 = str30;
                        str79 = str33;
                        str80 = str34;
                        num17 = num9;
                        str84 = str38;
                        str83 = str37;
                        num18 = num7;
                        str82 = str36;
                        str81 = str35;
                        str77 = str32;
                        str70 = str29;
                        break;
                    case 6:
                        str29 = str70;
                        str30 = str71;
                        str31 = str69;
                        num5 = num16;
                        str32 = str77;
                        str33 = str79;
                        str34 = str80;
                        num6 = num17;
                        str35 = str81;
                        str36 = str82;
                        num8 = num19;
                        num7 = num18;
                        str83 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 6, StringSerializer.INSTANCE, str83);
                        Unit unit8 = Unit.INSTANCE;
                        i11 |= 64;
                        i5 = i13;
                        str37 = str83;
                        str38 = str84;
                        i13 = i5;
                        num9 = num6;
                        num19 = num8;
                        str69 = str31;
                        str87 = str88;
                        num16 = num5;
                        str71 = str30;
                        str79 = str33;
                        str80 = str34;
                        num17 = num9;
                        str84 = str38;
                        str83 = str37;
                        num18 = num7;
                        str82 = str36;
                        str81 = str35;
                        str77 = str32;
                        str70 = str29;
                        break;
                    case 7:
                        str29 = str70;
                        str30 = str71;
                        str31 = str69;
                        num5 = num16;
                        str32 = str77;
                        str33 = str79;
                        str34 = str80;
                        num6 = num17;
                        str35 = str81;
                        num8 = num19;
                        str36 = str82;
                        num18 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 7, IntSerializer.INSTANCE, num18);
                        Unit unit9 = Unit.INSTANCE;
                        i11 |= 128;
                        i5 = i13;
                        num7 = num18;
                        str37 = str83;
                        str38 = str84;
                        i13 = i5;
                        num9 = num6;
                        num19 = num8;
                        str69 = str31;
                        str87 = str88;
                        num16 = num5;
                        str71 = str30;
                        str79 = str33;
                        str80 = str34;
                        num17 = num9;
                        str84 = str38;
                        str83 = str37;
                        num18 = num7;
                        str82 = str36;
                        str81 = str35;
                        str77 = str32;
                        str70 = str29;
                        break;
                    case 8:
                        str29 = str70;
                        str30 = str71;
                        str31 = str69;
                        num5 = num16;
                        str32 = str77;
                        str33 = str79;
                        str34 = str80;
                        num6 = num17;
                        num8 = num19;
                        str35 = str81;
                        str82 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 8, StringSerializer.INSTANCE, str82);
                        Unit unit10 = Unit.INSTANCE;
                        i11 |= 256;
                        i5 = i13;
                        str36 = str82;
                        num7 = num18;
                        str37 = str83;
                        str38 = str84;
                        i13 = i5;
                        num9 = num6;
                        num19 = num8;
                        str69 = str31;
                        str87 = str88;
                        num16 = num5;
                        str71 = str30;
                        str79 = str33;
                        str80 = str34;
                        num17 = num9;
                        str84 = str38;
                        str83 = str37;
                        num18 = num7;
                        str82 = str36;
                        str81 = str35;
                        str77 = str32;
                        str70 = str29;
                        break;
                    case 9:
                        str29 = str70;
                        str30 = str71;
                        num5 = num16;
                        str32 = str77;
                        str33 = str79;
                        str34 = str80;
                        num6 = num17;
                        num8 = num19;
                        str31 = str69;
                        str81 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 9, StringSerializer.INSTANCE, str81);
                        Unit unit11 = Unit.INSTANCE;
                        i11 |= 512;
                        i5 = i13;
                        str35 = str81;
                        str36 = str82;
                        num7 = num18;
                        str37 = str83;
                        str38 = str84;
                        i13 = i5;
                        num9 = num6;
                        num19 = num8;
                        str69 = str31;
                        str87 = str88;
                        num16 = num5;
                        str71 = str30;
                        str79 = str33;
                        str80 = str34;
                        num17 = num9;
                        str84 = str38;
                        str83 = str37;
                        num18 = num7;
                        str82 = str36;
                        str81 = str35;
                        str77 = str32;
                        str70 = str29;
                        break;
                    case 10:
                        str29 = str70;
                        str30 = str71;
                        num5 = num16;
                        str33 = str79;
                        str34 = str80;
                        num8 = num19;
                        str32 = str77;
                        num17 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 10, IntSerializer.INSTANCE, num17);
                        Unit unit12 = Unit.INSTANCE;
                        i11 |= 1024;
                        str31 = str69;
                        i5 = i13;
                        num6 = num17;
                        str35 = str81;
                        str36 = str82;
                        num7 = num18;
                        str37 = str83;
                        str38 = str84;
                        i13 = i5;
                        num9 = num6;
                        num19 = num8;
                        str69 = str31;
                        str87 = str88;
                        num16 = num5;
                        str71 = str30;
                        str79 = str33;
                        str80 = str34;
                        num17 = num9;
                        str84 = str38;
                        str83 = str37;
                        num18 = num7;
                        str82 = str36;
                        str81 = str35;
                        str77 = str32;
                        str70 = str29;
                        break;
                    case 11:
                        str29 = str70;
                        str30 = str71;
                        num5 = num16;
                        str41 = str77;
                        str33 = str79;
                        str34 = str80;
                        num8 = num19;
                        strDecodeStringElement16 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 11);
                        i6 = i11 | 2048;
                        Unit unit13 = Unit.INSTANCE;
                        int i15 = i6;
                        str42 = str41;
                        i7 = i15;
                        str31 = str69;
                        str32 = str42;
                        i5 = i13;
                        num6 = num17;
                        str35 = str81;
                        str36 = str82;
                        num7 = num18;
                        str37 = str83;
                        str38 = str84;
                        i11 = i7;
                        i13 = i5;
                        num9 = num6;
                        num19 = num8;
                        str69 = str31;
                        str87 = str88;
                        num16 = num5;
                        str71 = str30;
                        str79 = str33;
                        str80 = str34;
                        num17 = num9;
                        str84 = str38;
                        str83 = str37;
                        num18 = num7;
                        str82 = str36;
                        str81 = str35;
                        str77 = str32;
                        str70 = str29;
                        break;
                    case 12:
                        str29 = str70;
                        str30 = str71;
                        num5 = num16;
                        str41 = str77;
                        str33 = str79;
                        str34 = str80;
                        num8 = num19;
                        int iDecodeIntElement7 = compositeDecoderBeginStructure.decodeIntElement(serialDescriptor, 12);
                        i6 = i11 | 4096;
                        Unit unit14 = Unit.INSTANCE;
                        i13 = iDecodeIntElement7;
                        int i152 = i6;
                        str42 = str41;
                        i7 = i152;
                        str31 = str69;
                        str32 = str42;
                        i5 = i13;
                        num6 = num17;
                        str35 = str81;
                        str36 = str82;
                        num7 = num18;
                        str37 = str83;
                        str38 = str84;
                        i11 = i7;
                        i13 = i5;
                        num9 = num6;
                        num19 = num8;
                        str69 = str31;
                        str87 = str88;
                        num16 = num5;
                        str71 = str30;
                        str79 = str33;
                        str80 = str34;
                        num17 = num9;
                        str84 = str38;
                        str83 = str37;
                        num18 = num7;
                        str82 = str36;
                        str81 = str35;
                        str77 = str32;
                        str70 = str29;
                        break;
                    case 13:
                        str29 = str70;
                        str30 = str71;
                        num5 = num16;
                        str41 = str77;
                        str33 = str79;
                        str34 = str80;
                        num8 = num19;
                        strDecodeStringElement15 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 13);
                        i6 = i11 | 8192;
                        Unit unit15 = Unit.INSTANCE;
                        int i1522 = i6;
                        str42 = str41;
                        i7 = i1522;
                        str31 = str69;
                        str32 = str42;
                        i5 = i13;
                        num6 = num17;
                        str35 = str81;
                        str36 = str82;
                        num7 = num18;
                        str37 = str83;
                        str38 = str84;
                        i11 = i7;
                        i13 = i5;
                        num9 = num6;
                        num19 = num8;
                        str69 = str31;
                        str87 = str88;
                        num16 = num5;
                        str71 = str30;
                        str79 = str33;
                        str80 = str34;
                        num17 = num9;
                        str84 = str38;
                        str83 = str37;
                        num18 = num7;
                        str82 = str36;
                        str81 = str35;
                        str77 = str32;
                        str70 = str29;
                        break;
                    case 14:
                        str29 = str70;
                        str30 = str71;
                        num5 = num16;
                        str41 = str77;
                        str33 = str79;
                        str34 = str80;
                        num8 = num19;
                        strDecodeStringElement13 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 14);
                        i6 = i11 | 16384;
                        Unit unit16 = Unit.INSTANCE;
                        int i15222 = i6;
                        str42 = str41;
                        i7 = i15222;
                        str31 = str69;
                        str32 = str42;
                        i5 = i13;
                        num6 = num17;
                        str35 = str81;
                        str36 = str82;
                        num7 = num18;
                        str37 = str83;
                        str38 = str84;
                        i11 = i7;
                        i13 = i5;
                        num9 = num6;
                        num19 = num8;
                        str69 = str31;
                        str87 = str88;
                        num16 = num5;
                        str71 = str30;
                        str79 = str33;
                        str80 = str34;
                        num17 = num9;
                        str84 = str38;
                        str83 = str37;
                        num18 = num7;
                        str82 = str36;
                        str81 = str35;
                        str77 = str32;
                        str70 = str29;
                        break;
                    case 15:
                        str29 = str70;
                        str30 = str71;
                        num5 = num16;
                        str41 = str77;
                        str33 = str79;
                        str34 = str80;
                        num8 = num19;
                        strDecodeStringElement12 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 15);
                        i6 = i11 | 32768;
                        Unit unit17 = Unit.INSTANCE;
                        int i152222 = i6;
                        str42 = str41;
                        i7 = i152222;
                        str31 = str69;
                        str32 = str42;
                        i5 = i13;
                        num6 = num17;
                        str35 = str81;
                        str36 = str82;
                        num7 = num18;
                        str37 = str83;
                        str38 = str84;
                        i11 = i7;
                        i13 = i5;
                        num9 = num6;
                        num19 = num8;
                        str69 = str31;
                        str87 = str88;
                        num16 = num5;
                        str71 = str30;
                        str79 = str33;
                        str80 = str34;
                        num17 = num9;
                        str84 = str38;
                        str83 = str37;
                        num18 = num7;
                        str82 = str36;
                        str81 = str35;
                        str77 = str32;
                        str70 = str29;
                        break;
                    case 16:
                        str29 = str70;
                        str30 = str71;
                        num5 = num16;
                        str33 = str79;
                        num8 = num19;
                        str34 = str80;
                        String str89 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 16, StringSerializer.INSTANCE, str77);
                        int i16 = 65536 | i11;
                        Unit unit18 = Unit.INSTANCE;
                        str42 = str89;
                        i7 = i16;
                        str31 = str69;
                        str32 = str42;
                        i5 = i13;
                        num6 = num17;
                        str35 = str81;
                        str36 = str82;
                        num7 = num18;
                        str37 = str83;
                        str38 = str84;
                        i11 = i7;
                        i13 = i5;
                        num9 = num6;
                        num19 = num8;
                        str69 = str31;
                        str87 = str88;
                        num16 = num5;
                        str71 = str30;
                        str79 = str33;
                        str80 = str34;
                        num17 = num9;
                        str84 = str38;
                        str83 = str37;
                        num18 = num7;
                        str82 = str36;
                        str81 = str35;
                        str77 = str32;
                        str70 = str29;
                        break;
                    case 17:
                        str29 = str70;
                        str30 = str71;
                        num5 = num16;
                        num8 = num19;
                        str33 = str79;
                        str80 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 17, StringSerializer.INSTANCE, str80);
                        Unit unit19 = Unit.INSTANCE;
                        i11 = 131072 | i11;
                        str31 = str69;
                        i5 = i13;
                        str32 = str77;
                        str34 = str80;
                        num6 = num17;
                        str35 = str81;
                        str36 = str82;
                        num7 = num18;
                        str37 = str83;
                        str38 = str84;
                        i13 = i5;
                        num9 = num6;
                        num19 = num8;
                        str69 = str31;
                        str87 = str88;
                        num16 = num5;
                        str71 = str30;
                        str79 = str33;
                        str80 = str34;
                        num17 = num9;
                        str84 = str38;
                        str83 = str37;
                        num18 = num7;
                        str82 = str36;
                        str81 = str35;
                        str77 = str32;
                        str70 = str29;
                        break;
                    case 18:
                        str29 = str70;
                        num5 = num16;
                        num8 = num19;
                        str30 = str71;
                        String str90 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 18, StringSerializer.INSTANCE, str79);
                        Unit unit20 = Unit.INSTANCE;
                        i11 = 262144 | i11;
                        str31 = str69;
                        i5 = i13;
                        str32 = str77;
                        str33 = str90;
                        str34 = str80;
                        num6 = num17;
                        str35 = str81;
                        str36 = str82;
                        num7 = num18;
                        str37 = str83;
                        str38 = str84;
                        i13 = i5;
                        num9 = num6;
                        num19 = num8;
                        str69 = str31;
                        str87 = str88;
                        num16 = num5;
                        str71 = str30;
                        str79 = str33;
                        str80 = str34;
                        num17 = num9;
                        str84 = str38;
                        str83 = str37;
                        num18 = num7;
                        str82 = str36;
                        str81 = str35;
                        str77 = str32;
                        str70 = str29;
                        break;
                    case 19:
                        str29 = str70;
                        Integer num20 = num16;
                        Integer num21 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 19, IntSerializer.INSTANCE, num19);
                        int i17 = 524288 | i11;
                        Unit unit21 = Unit.INSTANCE;
                        str30 = str71;
                        num19 = num21;
                        i11 = i17;
                        str32 = str77;
                        str33 = str79;
                        str34 = str80;
                        num9 = num17;
                        str35 = str81;
                        str36 = str82;
                        num7 = num18;
                        str37 = str83;
                        str38 = str84;
                        str87 = str88;
                        num16 = num20;
                        str71 = str30;
                        str79 = str33;
                        str80 = str34;
                        num17 = num9;
                        str84 = str38;
                        str83 = str37;
                        num18 = num7;
                        str82 = str36;
                        str81 = str35;
                        str77 = str32;
                        str70 = str29;
                        break;
                    case 20:
                        str43 = str70;
                        num10 = num16;
                        str78 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 20, StringSerializer.INSTANCE, str78);
                        Unit unit22 = Unit.INSTANCE;
                        i11 = 1048576 | i11;
                        str87 = str88;
                        num16 = num10;
                        str70 = str43;
                        Long l5 = l4;
                        str49 = str73;
                        i10 = i14;
                        str44 = strDecodeStringElement11;
                        str45 = strDecodeStringElement10;
                        i9 = iDecodeIntElement6;
                        bool2 = bool4;
                        str46 = str76;
                        str47 = str75;
                        str48 = str74;
                        l2 = l5;
                        str29 = str70;
                        str30 = str71;
                        str32 = str77;
                        str33 = str79;
                        str34 = str80;
                        num9 = num17;
                        str35 = str81;
                        str36 = str82;
                        num7 = num18;
                        str37 = str83;
                        str38 = str84;
                        String str91 = str44;
                        i14 = i10;
                        str73 = str49;
                        l4 = l2;
                        str74 = str48;
                        str75 = str47;
                        str76 = str46;
                        bool4 = bool2;
                        iDecodeIntElement6 = i9;
                        strDecodeStringElement10 = str45;
                        strDecodeStringElement11 = str91;
                        str71 = str30;
                        str79 = str33;
                        str80 = str34;
                        num17 = num9;
                        str84 = str38;
                        str83 = str37;
                        num18 = num7;
                        str82 = str36;
                        str81 = str35;
                        str77 = str32;
                        str70 = str29;
                        break;
                    case 21:
                        str43 = str70;
                        num10 = num16;
                        String str92 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 21, StringSerializer.INSTANCE, str86);
                        Unit unit23 = Unit.INSTANCE;
                        str86 = str92;
                        i11 = 2097152 | i11;
                        str87 = str88;
                        num16 = num10;
                        str70 = str43;
                        Long l52 = l4;
                        str49 = str73;
                        i10 = i14;
                        str44 = strDecodeStringElement11;
                        str45 = strDecodeStringElement10;
                        i9 = iDecodeIntElement6;
                        bool2 = bool4;
                        str46 = str76;
                        str47 = str75;
                        str48 = str74;
                        l2 = l52;
                        str29 = str70;
                        str30 = str71;
                        str32 = str77;
                        str33 = str79;
                        str34 = str80;
                        num9 = num17;
                        str35 = str81;
                        str36 = str82;
                        num7 = num18;
                        str37 = str83;
                        str38 = str84;
                        String str912 = str44;
                        i14 = i10;
                        str73 = str49;
                        l4 = l2;
                        str74 = str48;
                        str75 = str47;
                        str76 = str46;
                        bool4 = bool2;
                        iDecodeIntElement6 = i9;
                        strDecodeStringElement10 = str45;
                        strDecodeStringElement11 = str912;
                        str71 = str30;
                        str79 = str33;
                        str80 = str34;
                        num17 = num9;
                        str84 = str38;
                        str83 = str37;
                        num18 = num7;
                        str82 = str36;
                        str81 = str35;
                        str77 = str32;
                        str70 = str29;
                        break;
                    case 22:
                        str43 = str70;
                        num10 = num16;
                        str87 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 22, StringSerializer.INSTANCE, str88);
                        Unit unit24 = Unit.INSTANCE;
                        i11 = 4194304 | i11;
                        num16 = num10;
                        str70 = str43;
                        Long l522 = l4;
                        str49 = str73;
                        i10 = i14;
                        str44 = strDecodeStringElement11;
                        str45 = strDecodeStringElement10;
                        i9 = iDecodeIntElement6;
                        bool2 = bool4;
                        str46 = str76;
                        str47 = str75;
                        str48 = str74;
                        l2 = l522;
                        str29 = str70;
                        str30 = str71;
                        str32 = str77;
                        str33 = str79;
                        str34 = str80;
                        num9 = num17;
                        str35 = str81;
                        str36 = str82;
                        num7 = num18;
                        str37 = str83;
                        str38 = str84;
                        String str9122 = str44;
                        i14 = i10;
                        str73 = str49;
                        l4 = l2;
                        str74 = str48;
                        str75 = str47;
                        str76 = str46;
                        bool4 = bool2;
                        iDecodeIntElement6 = i9;
                        strDecodeStringElement10 = str45;
                        strDecodeStringElement11 = str9122;
                        str71 = str30;
                        str79 = str33;
                        str80 = str34;
                        num17 = num9;
                        str84 = str38;
                        str83 = str37;
                        num18 = num7;
                        str82 = str36;
                        str81 = str35;
                        str77 = str32;
                        str70 = str29;
                        break;
                    case 23:
                        str43 = str70;
                        iDecodeIntElement6 = compositeDecoderBeginStructure.decodeIntElement(serialDescriptor, 23);
                        Unit unit25 = Unit.INSTANCE;
                        i11 = 8388608 | i11;
                        str87 = str88;
                        num16 = num16;
                        str70 = str43;
                        Long l5222 = l4;
                        str49 = str73;
                        i10 = i14;
                        str44 = strDecodeStringElement11;
                        str45 = strDecodeStringElement10;
                        i9 = iDecodeIntElement6;
                        bool2 = bool4;
                        str46 = str76;
                        str47 = str75;
                        str48 = str74;
                        l2 = l5222;
                        str29 = str70;
                        str30 = str71;
                        str32 = str77;
                        str33 = str79;
                        str34 = str80;
                        num9 = num17;
                        str35 = str81;
                        str36 = str82;
                        num7 = num18;
                        str37 = str83;
                        str38 = str84;
                        String str91222 = str44;
                        i14 = i10;
                        str73 = str49;
                        l4 = l2;
                        str74 = str48;
                        str75 = str47;
                        str76 = str46;
                        bool4 = bool2;
                        iDecodeIntElement6 = i9;
                        strDecodeStringElement10 = str45;
                        strDecodeStringElement11 = str91222;
                        str71 = str30;
                        str79 = str33;
                        str80 = str34;
                        num17 = num9;
                        str84 = str38;
                        str83 = str37;
                        num18 = num7;
                        str82 = str36;
                        str81 = str35;
                        str77 = str32;
                        str70 = str29;
                        break;
                    case 24:
                        str43 = str70;
                        num16 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 24, IntSerializer.INSTANCE, num16);
                        Unit unit26 = Unit.INSTANCE;
                        i11 = 16777216 | i11;
                        str87 = str88;
                        str70 = str43;
                        Long l52222 = l4;
                        str49 = str73;
                        i10 = i14;
                        str44 = strDecodeStringElement11;
                        str45 = strDecodeStringElement10;
                        i9 = iDecodeIntElement6;
                        bool2 = bool4;
                        str46 = str76;
                        str47 = str75;
                        str48 = str74;
                        l2 = l52222;
                        str29 = str70;
                        str30 = str71;
                        str32 = str77;
                        str33 = str79;
                        str34 = str80;
                        num9 = num17;
                        str35 = str81;
                        str36 = str82;
                        num7 = num18;
                        str37 = str83;
                        str38 = str84;
                        String str912222 = str44;
                        i14 = i10;
                        str73 = str49;
                        l4 = l2;
                        str74 = str48;
                        str75 = str47;
                        str76 = str46;
                        bool4 = bool2;
                        iDecodeIntElement6 = i9;
                        strDecodeStringElement10 = str45;
                        strDecodeStringElement11 = str912222;
                        str71 = str30;
                        str79 = str33;
                        str80 = str34;
                        num17 = num9;
                        str84 = str38;
                        str83 = str37;
                        num18 = num7;
                        str82 = str36;
                        str81 = str35;
                        str77 = str32;
                        str70 = str29;
                        break;
                    case 25:
                        num11 = num16;
                        str73 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 25, StringSerializer.INSTANCE, str73);
                        i8 = MediaHttpDownloader.MAXIMUM_CHUNK_SIZE;
                        i11 |= i8;
                        Unit unit27 = Unit.INSTANCE;
                        str87 = str88;
                        num16 = num11;
                        Long l522222 = l4;
                        str49 = str73;
                        i10 = i14;
                        str44 = strDecodeStringElement11;
                        str45 = strDecodeStringElement10;
                        i9 = iDecodeIntElement6;
                        bool2 = bool4;
                        str46 = str76;
                        str47 = str75;
                        str48 = str74;
                        l2 = l522222;
                        str29 = str70;
                        str30 = str71;
                        str32 = str77;
                        str33 = str79;
                        str34 = str80;
                        num9 = num17;
                        str35 = str81;
                        str36 = str82;
                        num7 = num18;
                        str37 = str83;
                        str38 = str84;
                        String str9122222 = str44;
                        i14 = i10;
                        str73 = str49;
                        l4 = l2;
                        str74 = str48;
                        str75 = str47;
                        str76 = str46;
                        bool4 = bool2;
                        iDecodeIntElement6 = i9;
                        strDecodeStringElement10 = str45;
                        strDecodeStringElement11 = str9122222;
                        str71 = str30;
                        str79 = str33;
                        str80 = str34;
                        num17 = num9;
                        str84 = str38;
                        str83 = str37;
                        num18 = num7;
                        str82 = str36;
                        str81 = str35;
                        str77 = str32;
                        str70 = str29;
                        break;
                    case 26:
                        num11 = num16;
                        str69 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 26, StringSerializer.INSTANCE, str69);
                        i8 = 67108864;
                        i11 |= i8;
                        Unit unit272 = Unit.INSTANCE;
                        str87 = str88;
                        num16 = num11;
                        Long l5222222 = l4;
                        str49 = str73;
                        i10 = i14;
                        str44 = strDecodeStringElement11;
                        str45 = strDecodeStringElement10;
                        i9 = iDecodeIntElement6;
                        bool2 = bool4;
                        str46 = str76;
                        str47 = str75;
                        str48 = str74;
                        l2 = l5222222;
                        str29 = str70;
                        str30 = str71;
                        str32 = str77;
                        str33 = str79;
                        str34 = str80;
                        num9 = num17;
                        str35 = str81;
                        str36 = str82;
                        num7 = num18;
                        str37 = str83;
                        str38 = str84;
                        String str91222222 = str44;
                        i14 = i10;
                        str73 = str49;
                        l4 = l2;
                        str74 = str48;
                        str75 = str47;
                        str76 = str46;
                        bool4 = bool2;
                        iDecodeIntElement6 = i9;
                        strDecodeStringElement10 = str45;
                        strDecodeStringElement11 = str91222222;
                        str71 = str30;
                        str79 = str33;
                        str80 = str34;
                        num17 = num9;
                        str84 = str38;
                        str83 = str37;
                        num18 = num7;
                        str82 = str36;
                        str81 = str35;
                        str77 = str32;
                        str70 = str29;
                        break;
                    case 27:
                        num11 = num16;
                        jDecodeLongElement2 = compositeDecoderBeginStructure.decodeLongElement(serialDescriptor, 27);
                        i8 = 134217728;
                        i11 |= i8;
                        Unit unit2722 = Unit.INSTANCE;
                        str87 = str88;
                        num16 = num11;
                        Long l52222222 = l4;
                        str49 = str73;
                        i10 = i14;
                        str44 = strDecodeStringElement11;
                        str45 = strDecodeStringElement10;
                        i9 = iDecodeIntElement6;
                        bool2 = bool4;
                        str46 = str76;
                        str47 = str75;
                        str48 = str74;
                        l2 = l52222222;
                        str29 = str70;
                        str30 = str71;
                        str32 = str77;
                        str33 = str79;
                        str34 = str80;
                        num9 = num17;
                        str35 = str81;
                        str36 = str82;
                        num7 = num18;
                        str37 = str83;
                        str38 = str84;
                        String str912222222 = str44;
                        i14 = i10;
                        str73 = str49;
                        l4 = l2;
                        str74 = str48;
                        str75 = str47;
                        str76 = str46;
                        bool4 = bool2;
                        iDecodeIntElement6 = i9;
                        strDecodeStringElement10 = str45;
                        strDecodeStringElement11 = str912222222;
                        str71 = str30;
                        str79 = str33;
                        str80 = str34;
                        num17 = num9;
                        str84 = str38;
                        str83 = str37;
                        num18 = num7;
                        str82 = str36;
                        str81 = str35;
                        str77 = str32;
                        str70 = str29;
                        break;
                    case 28:
                        num11 = num16;
                        l4 = (Long) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 28, LongSerializer.INSTANCE, l4);
                        i8 = 268435456;
                        i11 |= i8;
                        Unit unit27222 = Unit.INSTANCE;
                        str87 = str88;
                        num16 = num11;
                        Long l522222222 = l4;
                        str49 = str73;
                        i10 = i14;
                        str44 = strDecodeStringElement11;
                        str45 = strDecodeStringElement10;
                        i9 = iDecodeIntElement6;
                        bool2 = bool4;
                        str46 = str76;
                        str47 = str75;
                        str48 = str74;
                        l2 = l522222222;
                        str29 = str70;
                        str30 = str71;
                        str32 = str77;
                        str33 = str79;
                        str34 = str80;
                        num9 = num17;
                        str35 = str81;
                        str36 = str82;
                        num7 = num18;
                        str37 = str83;
                        str38 = str84;
                        String str9122222222 = str44;
                        i14 = i10;
                        str73 = str49;
                        l4 = l2;
                        str74 = str48;
                        str75 = str47;
                        str76 = str46;
                        bool4 = bool2;
                        iDecodeIntElement6 = i9;
                        strDecodeStringElement10 = str45;
                        strDecodeStringElement11 = str9122222222;
                        str71 = str30;
                        str79 = str33;
                        str80 = str34;
                        num17 = num9;
                        str84 = str38;
                        str83 = str37;
                        num18 = num7;
                        str82 = str36;
                        str81 = str35;
                        str77 = str32;
                        str70 = str29;
                        break;
                    case 29:
                        Integer num22 = num16;
                        int iDecodeIntElement8 = compositeDecoderBeginStructure.decodeIntElement(serialDescriptor, 29);
                        i11 |= 536870912;
                        Unit unit28 = Unit.INSTANCE;
                        str44 = strDecodeStringElement11;
                        str87 = str88;
                        str45 = strDecodeStringElement10;
                        i9 = iDecodeIntElement6;
                        bool2 = bool4;
                        str46 = str76;
                        str47 = str75;
                        str48 = str74;
                        l2 = l4;
                        str49 = str73;
                        i10 = iDecodeIntElement8;
                        num16 = num22;
                        str29 = str70;
                        str30 = str71;
                        str32 = str77;
                        str33 = str79;
                        str34 = str80;
                        num9 = num17;
                        str35 = str81;
                        str36 = str82;
                        num7 = num18;
                        str37 = str83;
                        str38 = str84;
                        String str91222222222 = str44;
                        i14 = i10;
                        str73 = str49;
                        l4 = l2;
                        str74 = str48;
                        str75 = str47;
                        str76 = str46;
                        bool4 = bool2;
                        iDecodeIntElement6 = i9;
                        strDecodeStringElement10 = str45;
                        strDecodeStringElement11 = str91222222222;
                        str71 = str30;
                        str79 = str33;
                        str80 = str34;
                        num17 = num9;
                        str84 = str38;
                        str83 = str37;
                        num18 = num7;
                        str82 = str36;
                        str81 = str35;
                        str77 = str32;
                        str70 = str29;
                        break;
                    case 30:
                        num11 = num16;
                        strDecodeStringElement11 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 30);
                        i8 = 1073741824;
                        i11 |= i8;
                        Unit unit272222 = Unit.INSTANCE;
                        str87 = str88;
                        num16 = num11;
                        Long l5222222222 = l4;
                        str49 = str73;
                        i10 = i14;
                        str44 = strDecodeStringElement11;
                        str45 = strDecodeStringElement10;
                        i9 = iDecodeIntElement6;
                        bool2 = bool4;
                        str46 = str76;
                        str47 = str75;
                        str48 = str74;
                        l2 = l5222222222;
                        str29 = str70;
                        str30 = str71;
                        str32 = str77;
                        str33 = str79;
                        str34 = str80;
                        num9 = num17;
                        str35 = str81;
                        str36 = str82;
                        num7 = num18;
                        str37 = str83;
                        str38 = str84;
                        String str912222222222 = str44;
                        i14 = i10;
                        str73 = str49;
                        l4 = l2;
                        str74 = str48;
                        str75 = str47;
                        str76 = str46;
                        bool4 = bool2;
                        iDecodeIntElement6 = i9;
                        strDecodeStringElement10 = str45;
                        strDecodeStringElement11 = str912222222222;
                        str71 = str30;
                        str79 = str33;
                        str80 = str34;
                        num17 = num9;
                        str84 = str38;
                        str83 = str37;
                        num18 = num7;
                        str82 = str36;
                        str81 = str35;
                        str77 = str32;
                        str70 = str29;
                        break;
                    case 31:
                        num11 = num16;
                        strDecodeStringElement10 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 31);
                        i8 = Integer.MIN_VALUE;
                        i11 |= i8;
                        Unit unit2722222 = Unit.INSTANCE;
                        str87 = str88;
                        num16 = num11;
                        Long l52222222222 = l4;
                        str49 = str73;
                        i10 = i14;
                        str44 = strDecodeStringElement11;
                        str45 = strDecodeStringElement10;
                        i9 = iDecodeIntElement6;
                        bool2 = bool4;
                        str46 = str76;
                        str47 = str75;
                        str48 = str74;
                        l2 = l52222222222;
                        str29 = str70;
                        str30 = str71;
                        str32 = str77;
                        str33 = str79;
                        str34 = str80;
                        num9 = num17;
                        str35 = str81;
                        str36 = str82;
                        num7 = num18;
                        str37 = str83;
                        str38 = str84;
                        String str9122222222222 = str44;
                        i14 = i10;
                        str73 = str49;
                        l4 = l2;
                        str74 = str48;
                        str75 = str47;
                        str76 = str46;
                        bool4 = bool2;
                        iDecodeIntElement6 = i9;
                        strDecodeStringElement10 = str45;
                        strDecodeStringElement11 = str9122222222222;
                        str71 = str30;
                        str79 = str33;
                        str80 = str34;
                        num17 = num9;
                        str84 = str38;
                        str83 = str37;
                        num18 = num7;
                        str82 = str36;
                        str81 = str35;
                        str77 = str32;
                        str70 = str29;
                        break;
                    case 32:
                        num11 = num16;
                        str74 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 32, StringSerializer.INSTANCE, str74);
                        i12 |= 1;
                        Unit unit27222222 = Unit.INSTANCE;
                        str87 = str88;
                        num16 = num11;
                        Long l522222222222 = l4;
                        str49 = str73;
                        i10 = i14;
                        str44 = strDecodeStringElement11;
                        str45 = strDecodeStringElement10;
                        i9 = iDecodeIntElement6;
                        bool2 = bool4;
                        str46 = str76;
                        str47 = str75;
                        str48 = str74;
                        l2 = l522222222222;
                        str29 = str70;
                        str30 = str71;
                        str32 = str77;
                        str33 = str79;
                        str34 = str80;
                        num9 = num17;
                        str35 = str81;
                        str36 = str82;
                        num7 = num18;
                        str37 = str83;
                        str38 = str84;
                        String str91222222222222 = str44;
                        i14 = i10;
                        str73 = str49;
                        l4 = l2;
                        str74 = str48;
                        str75 = str47;
                        str76 = str46;
                        bool4 = bool2;
                        iDecodeIntElement6 = i9;
                        strDecodeStringElement10 = str45;
                        strDecodeStringElement11 = str91222222222222;
                        str71 = str30;
                        str79 = str33;
                        str80 = str34;
                        num17 = num9;
                        str84 = str38;
                        str83 = str37;
                        num18 = num7;
                        str82 = str36;
                        str81 = str35;
                        str77 = str32;
                        str70 = str29;
                        break;
                    case 33:
                        num11 = num16;
                        str72 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 33, StringSerializer.INSTANCE, str72);
                        i12 |= 2;
                        Unit unit272222222 = Unit.INSTANCE;
                        str87 = str88;
                        num16 = num11;
                        Long l5222222222222 = l4;
                        str49 = str73;
                        i10 = i14;
                        str44 = strDecodeStringElement11;
                        str45 = strDecodeStringElement10;
                        i9 = iDecodeIntElement6;
                        bool2 = bool4;
                        str46 = str76;
                        str47 = str75;
                        str48 = str74;
                        l2 = l5222222222222;
                        str29 = str70;
                        str30 = str71;
                        str32 = str77;
                        str33 = str79;
                        str34 = str80;
                        num9 = num17;
                        str35 = str81;
                        str36 = str82;
                        num7 = num18;
                        str37 = str83;
                        str38 = str84;
                        String str912222222222222 = str44;
                        i14 = i10;
                        str73 = str49;
                        l4 = l2;
                        str74 = str48;
                        str75 = str47;
                        str76 = str46;
                        bool4 = bool2;
                        iDecodeIntElement6 = i9;
                        strDecodeStringElement10 = str45;
                        strDecodeStringElement11 = str912222222222222;
                        str71 = str30;
                        str79 = str33;
                        str80 = str34;
                        num17 = num9;
                        str84 = str38;
                        str83 = str37;
                        num18 = num7;
                        str82 = str36;
                        str81 = str35;
                        str77 = str32;
                        str70 = str29;
                        break;
                    case 34:
                        num11 = num16;
                        str75 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 34, StringSerializer.INSTANCE, str75);
                        i12 |= 4;
                        Unit unit2722222222 = Unit.INSTANCE;
                        str87 = str88;
                        num16 = num11;
                        Long l52222222222222 = l4;
                        str49 = str73;
                        i10 = i14;
                        str44 = strDecodeStringElement11;
                        str45 = strDecodeStringElement10;
                        i9 = iDecodeIntElement6;
                        bool2 = bool4;
                        str46 = str76;
                        str47 = str75;
                        str48 = str74;
                        l2 = l52222222222222;
                        str29 = str70;
                        str30 = str71;
                        str32 = str77;
                        str33 = str79;
                        str34 = str80;
                        num9 = num17;
                        str35 = str81;
                        str36 = str82;
                        num7 = num18;
                        str37 = str83;
                        str38 = str84;
                        String str9122222222222222 = str44;
                        i14 = i10;
                        str73 = str49;
                        l4 = l2;
                        str74 = str48;
                        str75 = str47;
                        str76 = str46;
                        bool4 = bool2;
                        iDecodeIntElement6 = i9;
                        strDecodeStringElement10 = str45;
                        strDecodeStringElement11 = str9122222222222222;
                        str71 = str30;
                        str79 = str33;
                        str80 = str34;
                        num17 = num9;
                        str84 = str38;
                        str83 = str37;
                        num18 = num7;
                        str82 = str36;
                        str81 = str35;
                        str77 = str32;
                        str70 = str29;
                        break;
                    case 35:
                        num11 = num16;
                        str76 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 35, StringSerializer.INSTANCE, str76);
                        i12 |= 8;
                        Unit unit27222222222 = Unit.INSTANCE;
                        str87 = str88;
                        num16 = num11;
                        Long l522222222222222 = l4;
                        str49 = str73;
                        i10 = i14;
                        str44 = strDecodeStringElement11;
                        str45 = strDecodeStringElement10;
                        i9 = iDecodeIntElement6;
                        bool2 = bool4;
                        str46 = str76;
                        str47 = str75;
                        str48 = str74;
                        l2 = l522222222222222;
                        str29 = str70;
                        str30 = str71;
                        str32 = str77;
                        str33 = str79;
                        str34 = str80;
                        num9 = num17;
                        str35 = str81;
                        str36 = str82;
                        num7 = num18;
                        str37 = str83;
                        str38 = str84;
                        String str91222222222222222 = str44;
                        i14 = i10;
                        str73 = str49;
                        l4 = l2;
                        str74 = str48;
                        str75 = str47;
                        str76 = str46;
                        bool4 = bool2;
                        iDecodeIntElement6 = i9;
                        strDecodeStringElement10 = str45;
                        strDecodeStringElement11 = str91222222222222222;
                        str71 = str30;
                        str79 = str33;
                        str80 = str34;
                        num17 = num9;
                        str84 = str38;
                        str83 = str37;
                        num18 = num7;
                        str82 = str36;
                        str81 = str35;
                        str77 = str32;
                        str70 = str29;
                        break;
                    case 36:
                        num11 = num16;
                        bool4 = (Boolean) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 36, BooleanSerializer.INSTANCE, bool4);
                        i12 |= 16;
                        Unit unit272222222222 = Unit.INSTANCE;
                        str87 = str88;
                        num16 = num11;
                        Long l5222222222222222 = l4;
                        str49 = str73;
                        i10 = i14;
                        str44 = strDecodeStringElement11;
                        str45 = strDecodeStringElement10;
                        i9 = iDecodeIntElement6;
                        bool2 = bool4;
                        str46 = str76;
                        str47 = str75;
                        str48 = str74;
                        l2 = l5222222222222222;
                        str29 = str70;
                        str30 = str71;
                        str32 = str77;
                        str33 = str79;
                        str34 = str80;
                        num9 = num17;
                        str35 = str81;
                        str36 = str82;
                        num7 = num18;
                        str37 = str83;
                        str38 = str84;
                        String str912222222222222222 = str44;
                        i14 = i10;
                        str73 = str49;
                        l4 = l2;
                        str74 = str48;
                        str75 = str47;
                        str76 = str46;
                        bool4 = bool2;
                        iDecodeIntElement6 = i9;
                        strDecodeStringElement10 = str45;
                        strDecodeStringElement11 = str912222222222222222;
                        str71 = str30;
                        str79 = str33;
                        str80 = str34;
                        num17 = num9;
                        str84 = str38;
                        str83 = str37;
                        num18 = num7;
                        str82 = str36;
                        str81 = str35;
                        str77 = str32;
                        str70 = str29;
                        break;
                    case 37:
                        num11 = num16;
                        str71 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 37, StringSerializer.INSTANCE, str71);
                        i12 |= 32;
                        Unit unit2722222222222 = Unit.INSTANCE;
                        str87 = str88;
                        num16 = num11;
                        Long l52222222222222222 = l4;
                        str49 = str73;
                        i10 = i14;
                        str44 = strDecodeStringElement11;
                        str45 = strDecodeStringElement10;
                        i9 = iDecodeIntElement6;
                        bool2 = bool4;
                        str46 = str76;
                        str47 = str75;
                        str48 = str74;
                        l2 = l52222222222222222;
                        str29 = str70;
                        str30 = str71;
                        str32 = str77;
                        str33 = str79;
                        str34 = str80;
                        num9 = num17;
                        str35 = str81;
                        str36 = str82;
                        num7 = num18;
                        str37 = str83;
                        str38 = str84;
                        String str9122222222222222222 = str44;
                        i14 = i10;
                        str73 = str49;
                        l4 = l2;
                        str74 = str48;
                        str75 = str47;
                        str76 = str46;
                        bool4 = bool2;
                        iDecodeIntElement6 = i9;
                        strDecodeStringElement10 = str45;
                        strDecodeStringElement11 = str9122222222222222222;
                        str71 = str30;
                        str79 = str33;
                        str80 = str34;
                        num17 = num9;
                        str84 = str38;
                        str83 = str37;
                        num18 = num7;
                        str82 = str36;
                        str81 = str35;
                        str77 = str32;
                        str70 = str29;
                        break;
                    case 38:
                        num11 = num16;
                        str70 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 38, StringSerializer.INSTANCE, str70);
                        i12 |= 64;
                        Unit unit27222222222222 = Unit.INSTANCE;
                        str87 = str88;
                        num16 = num11;
                        Long l522222222222222222 = l4;
                        str49 = str73;
                        i10 = i14;
                        str44 = strDecodeStringElement11;
                        str45 = strDecodeStringElement10;
                        i9 = iDecodeIntElement6;
                        bool2 = bool4;
                        str46 = str76;
                        str47 = str75;
                        str48 = str74;
                        l2 = l522222222222222222;
                        str29 = str70;
                        str30 = str71;
                        str32 = str77;
                        str33 = str79;
                        str34 = str80;
                        num9 = num17;
                        str35 = str81;
                        str36 = str82;
                        num7 = num18;
                        str37 = str83;
                        str38 = str84;
                        String str91222222222222222222 = str44;
                        i14 = i10;
                        str73 = str49;
                        l4 = l2;
                        str74 = str48;
                        str75 = str47;
                        str76 = str46;
                        bool4 = bool2;
                        iDecodeIntElement6 = i9;
                        strDecodeStringElement10 = str45;
                        strDecodeStringElement11 = str91222222222222222222;
                        str71 = str30;
                        str79 = str33;
                        str80 = str34;
                        num17 = num9;
                        str84 = str38;
                        str83 = str37;
                        num18 = num7;
                        str82 = str36;
                        str81 = str35;
                        str77 = str32;
                        str70 = str29;
                        break;
                    default:
                        throw new UnknownFieldException(iDecodeElementIndex);
                }
            }
            String str93 = str77;
            String str94 = str79;
            String str95 = str80;
            String str96 = str81;
            String str97 = str82;
            Integer num23 = num18;
            str = str72;
            num = num17;
            str2 = str74;
            str3 = str76;
            bool = bool4;
            str4 = str71;
            str5 = str95;
            str6 = str84;
            str7 = str83;
            str8 = str97;
            str9 = str96;
            iDecodeIntElement = i13;
            i = i14;
            str10 = strDecodeStringElement12;
            str11 = str78;
            str12 = strDecodeStringElement14;
            str13 = strDecodeStringElement15;
            str14 = strDecodeStringElement16;
            str15 = strDecodeStringElement17;
            str16 = str86;
            i2 = iDecodeIntElement5;
            num2 = num16;
            str17 = str70;
            num3 = num19;
            l = l4;
            str18 = str94;
            i3 = iDecodeIntElement6;
            str19 = strDecodeStringElement10;
            num4 = num23;
            str20 = strDecodeStringElement11;
            str21 = str93;
            str22 = strDecodeStringElement13;
            str23 = strDecodeStringElement18;
            j = jDecodeLongElement2;
            str24 = str87;
            str25 = str75;
            str26 = str69;
            str27 = str85;
            str28 = str73;
            i4 = i12;
        }
        compositeDecoderBeginStructure.endStructure(serialDescriptor);
        return new CardReferralRewardsOrderDetailApiModel(i11, i4, str23, str15, str27, str6, str12, i2, str7, num4, str8, str9, num, str14, iDecodeIntElement, str13, str22, str10, str21, str5, str18, num3, str11, str16, str24, i3, num2, str28, str26, j, l, i, str20, str19, str2, str, str25, str3, bool, str4, str17, (SerializationConstructorMarker) null);
    }

    /* JADX DEBUG: Method merged with bridge method: serialize(Lkotlinx/serialization/encoding/Encoder;Ljava/lang/Object;)V */
    @Override // kotlinx.serialization.SerializationStrategy
    public final void serialize(@NotNull Encoder encoder, @NotNull CardReferralRewardsOrderDetailApiModel cardReferralRewardsOrderDetailApiModel) {
        Intrinsics.checkNotNullParameter(encoder, "");
        Intrinsics.checkNotNullParameter(cardReferralRewardsOrderDetailApiModel, "");
        SerialDescriptor serialDescriptor = descriptor;
        CompositeEncoder compositeEncoderBeginStructure = encoder.beginStructure(serialDescriptor);
        CardReferralRewardsOrderDetailApiModel.write$Self$OKPayCore_web3pay_lib(cardReferralRewardsOrderDetailApiModel, compositeEncoderBeginStructure, serialDescriptor);
        compositeEncoderBeginStructure.endStructure(serialDescriptor);
    }
}
