package com.okinc.business.web3pay.lib.features.transactionhistory.datasource.remote.http.model;

import com.google.api.client.googleapis.media.MediaHttpDownloader;
import kotlin.Unit;
import kotlin.jvm.internal.Intrinsics;
import kotlinx.serialization.KSerializer;
import kotlinx.serialization.UnknownFieldException;
import kotlinx.serialization.builtins.BuiltinSerializersKt;
import kotlinx.serialization.descriptors.SerialDescriptor;
import kotlinx.serialization.encoding.CompositeDecoder;
import kotlinx.serialization.encoding.CompositeEncoder;
import kotlinx.serialization.encoding.Decoder;
import kotlinx.serialization.encoding.Encoder;
import kotlinx.serialization.internal.GeneratedSerializer;
import kotlinx.serialization.internal.IntSerializer;
import kotlinx.serialization.internal.LongSerializer;
import kotlinx.serialization.internal.PluginGeneratedSerialDescriptor;
import kotlinx.serialization.internal.SerializationConstructorMarker;
import kotlinx.serialization.internal.StringSerializer;
import org.jetbrains.annotations.NotNull;

/* JADX INFO: loaded from: classes23.dex */
public final /* synthetic */ class RedPacketOrderDetailApiModel$$serializer implements GeneratedSerializer<RedPacketOrderDetailApiModel> {
    public static final int $stable;
    public static final RedPacketOrderDetailApiModel$$serializer INSTANCE;
    private static final SerialDescriptor descriptor;

    /* JADX DEBUG: Don't trust debug lines info. Lines numbers was adjusted: min line is 0 */
    private RedPacketOrderDetailApiModel$$serializer() {
    }

    /* JADX DEBUG: Don't trust debug lines info. Lines numbers was adjusted: min line is 0 */
    @Override // kotlinx.serialization.KSerializer, kotlinx.serialization.SerializationStrategy, kotlinx.serialization.DeserializationStrategy
    public final SerialDescriptor getDescriptor() {
        return descriptor;
    }

    static {
        RedPacketOrderDetailApiModel$$serializer redPacketOrderDetailApiModel$$serializer = new RedPacketOrderDetailApiModel$$serializer();
        INSTANCE = redPacketOrderDetailApiModel$$serializer;
        $stable = 8;
        PluginGeneratedSerialDescriptor pluginGeneratedSerialDescriptor = new PluginGeneratedSerialDescriptor("com.okinc.business.web3pay.lib.features.transactionhistory.datasource.remote.http.model.RedPacketOrderDetailApiModel", redPacketOrderDetailApiModel$$serializer, 38);
        pluginGeneratedSerialDescriptor.addElement("orderId", false);
        pluginGeneratedSerialDescriptor.addElement("parentOrderId", false);
        pluginGeneratedSerialDescriptor.addElement("uopHash", true);
        pluginGeneratedSerialDescriptor.addElement("txHash", true);
        pluginGeneratedSerialDescriptor.addElement("chainIndex", false);
        pluginGeneratedSerialDescriptor.addElement("orderType", false);
        pluginGeneratedSerialDescriptor.addElement("merchantId", false);
        pluginGeneratedSerialDescriptor.addElement("productCode", false);
        pluginGeneratedSerialDescriptor.addElement("from", false);
        pluginGeneratedSerialDescriptor.addElement("fromType", true);
        pluginGeneratedSerialDescriptor.addElement("to", false);
        pluginGeneratedSerialDescriptor.addElement("areaCode", true);
        pluginGeneratedSerialDescriptor.addElement("toType", true);
        pluginGeneratedSerialDescriptor.addElement("tokenAmount", false);
        pluginGeneratedSerialDescriptor.addElement("tokenDecimal", false);
        pluginGeneratedSerialDescriptor.addElement("tokenUsdAmount", false);
        pluginGeneratedSerialDescriptor.addElement("tokenLogo", false);
        pluginGeneratedSerialDescriptor.addElement("tokenSymbol", false);
        pluginGeneratedSerialDescriptor.addElement("tokenAddress", false);
        pluginGeneratedSerialDescriptor.addElement("feeTokenSymbol", false);
        pluginGeneratedSerialDescriptor.addElement("feeTokenDecimal", false);
        pluginGeneratedSerialDescriptor.addElement("feeTokenAmount", false);
        pluginGeneratedSerialDescriptor.addElement("feeTokenUsdAmount", false);
        pluginGeneratedSerialDescriptor.addElement("status", false);
        pluginGeneratedSerialDescriptor.addElement("errMsg", true);
        pluginGeneratedSerialDescriptor.addElement("failedType", true);
        pluginGeneratedSerialDescriptor.addElement("transferComment", true);
        pluginGeneratedSerialDescriptor.addElement("createTime", false);
        pluginGeneratedSerialDescriptor.addElement("timeToCancel", true);
        pluginGeneratedSerialDescriptor.addElement("gasPayType", false);
        pluginGeneratedSerialDescriptor.addElement("networkName", false);
        pluginGeneratedSerialDescriptor.addElement("networkLogo", false);
        pluginGeneratedSerialDescriptor.addElement("activationFeeTokenAmount", true);
        pluginGeneratedSerialDescriptor.addElement("activationFeeUsdAmount", true);
        pluginGeneratedSerialDescriptor.addElement("claimedUser", false);
        pluginGeneratedSerialDescriptor.addElement("claimedAmount", false);
        pluginGeneratedSerialDescriptor.addElement("remainAmount", false);
        pluginGeneratedSerialDescriptor.addElement("remainUsdAmount", false);
        descriptor = pluginGeneratedSerialDescriptor;
    }

    @Override // kotlinx.serialization.internal.GeneratedSerializer
    public final KSerializer<?>[] childSerializers() {
        StringSerializer stringSerializer = StringSerializer.INSTANCE;
        IntSerializer intSerializer = IntSerializer.INSTANCE;
        LongSerializer longSerializer = LongSerializer.INSTANCE;
        return new KSerializer[]{stringSerializer, stringSerializer, BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), stringSerializer, intSerializer, BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(intSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(intSerializer), stringSerializer, intSerializer, stringSerializer, stringSerializer, stringSerializer, BuiltinSerializersKt.getNullable(stringSerializer), stringSerializer, intSerializer, stringSerializer, stringSerializer, intSerializer, BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(intSerializer), BuiltinSerializersKt.getNullable(stringSerializer), longSerializer, BuiltinSerializersKt.getNullable(longSerializer), intSerializer, stringSerializer, stringSerializer, BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), intSerializer, stringSerializer, stringSerializer, stringSerializer};
    }

    /* JADX DEBUG: Method merged with bridge method: deserialize(Lkotlinx/serialization/encoding/Decoder;)Ljava/lang/Object; */
    @Override // kotlinx.serialization.DeserializationStrategy
    public final RedPacketOrderDetailApiModel deserialize(@NotNull Decoder decoder) {
        Integer num;
        String str;
        Integer num2;
        String str2;
        String str3;
        String str4;
        String str5;
        String str6;
        int i;
        String str7;
        String str8;
        String str9;
        String str10;
        String str11;
        String str12;
        Integer num3;
        String str13;
        String str14;
        String str15;
        int i2;
        int i3;
        int i4;
        String str16;
        int i5;
        String str17;
        String str18;
        String str19;
        String str20;
        String str21;
        String str22;
        Long l;
        int i6;
        int i7;
        String str23;
        String strDecodeStringElement;
        String str24;
        String str25;
        long j;
        String str26;
        int i8;
        Long l2;
        Integer num4;
        String str27;
        String str28;
        String str29;
        String str30;
        String str31;
        String str32;
        String str33;
        String str34;
        int i9;
        Integer num5;
        int i10;
        Long l3;
        String str35;
        String str36;
        String str37;
        int i11;
        int i12;
        Integer num6;
        int i13;
        Integer num7;
        String str38;
        Integer num8;
        String str39;
        int i14;
        Intrinsics.checkNotNullParameter(decoder, "");
        SerialDescriptor serialDescriptor = descriptor;
        CompositeDecoder compositeDecoderBeginStructure = decoder.beginStructure(serialDescriptor);
        if (compositeDecoderBeginStructure.decodeSequentially()) {
            String strDecodeStringElement2 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 0);
            String strDecodeStringElement3 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 1);
            StringSerializer stringSerializer = StringSerializer.INSTANCE;
            String str40 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 2, stringSerializer, null);
            String str41 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 3, stringSerializer, null);
            String strDecodeStringElement4 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 4);
            int iDecodeIntElement = compositeDecoderBeginStructure.decodeIntElement(serialDescriptor, 5);
            String str42 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 6, stringSerializer, null);
            String str43 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 7, stringSerializer, null);
            String str44 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 8, stringSerializer, null);
            IntSerializer intSerializer = IntSerializer.INSTANCE;
            Integer num9 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 9, intSerializer, null);
            String str45 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 10, stringSerializer, null);
            str4 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 11, stringSerializer, null);
            Integer num10 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 12, intSerializer, null);
            String strDecodeStringElement5 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 13);
            int iDecodeIntElement2 = compositeDecoderBeginStructure.decodeIntElement(serialDescriptor, 14);
            String strDecodeStringElement6 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 15);
            String strDecodeStringElement7 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 16);
            String strDecodeStringElement8 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 17);
            str3 = str41;
            String str46 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 18, stringSerializer, null);
            String strDecodeStringElement9 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 19);
            int iDecodeIntElement3 = compositeDecoderBeginStructure.decodeIntElement(serialDescriptor, 20);
            String strDecodeStringElement10 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 21);
            String strDecodeStringElement11 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 22);
            int iDecodeIntElement4 = compositeDecoderBeginStructure.decodeIntElement(serialDescriptor, 23);
            String str47 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 24, stringSerializer, null);
            Integer num11 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 25, intSerializer, null);
            String str48 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 26, stringSerializer, null);
            long jDecodeLongElement = compositeDecoderBeginStructure.decodeLongElement(serialDescriptor, 27);
            Long l4 = (Long) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 28, LongSerializer.INSTANCE, null);
            int iDecodeIntElement5 = compositeDecoderBeginStructure.decodeIntElement(serialDescriptor, 29);
            String strDecodeStringElement12 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 30);
            String strDecodeStringElement13 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 31);
            String str49 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 32, stringSerializer, null);
            String str50 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 33, stringSerializer, null);
            int iDecodeIntElement6 = compositeDecoderBeginStructure.decodeIntElement(serialDescriptor, 34);
            String strDecodeStringElement14 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 35);
            String strDecodeStringElement15 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 36);
            strDecodeStringElement = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 37);
            i = iDecodeIntElement6;
            str20 = strDecodeStringElement12;
            i5 = iDecodeIntElement5;
            str19 = strDecodeStringElement14;
            str = str49;
            l = l4;
            str18 = strDecodeStringElement13;
            str2 = str50;
            str24 = strDecodeStringElement15;
            str26 = str46;
            str8 = str48;
            str16 = str47;
            i7 = iDecodeIntElement4;
            num2 = num11;
            str17 = strDecodeStringElement5;
            str11 = strDecodeStringElement7;
            str7 = strDecodeStringElement10;
            str9 = str42;
            i4 = iDecodeIntElement2;
            str14 = strDecodeStringElement3;
            str5 = str44;
            str21 = strDecodeStringElement8;
            i2 = iDecodeIntElement;
            str23 = str40;
            str10 = strDecodeStringElement11;
            str22 = strDecodeStringElement6;
            str12 = str43;
            str15 = strDecodeStringElement2;
            num3 = num10;
            num = num9;
            i3 = 63;
            str13 = strDecodeStringElement4;
            str6 = str45;
            i8 = -1;
            j = jDecodeLongElement;
            str25 = strDecodeStringElement9;
            i6 = iDecodeIntElement3;
        } else {
            Integer num12 = null;
            Long l5 = null;
            String str51 = null;
            Integer num13 = null;
            String str52 = null;
            String str53 = null;
            String str54 = null;
            String str55 = null;
            String str56 = null;
            String str57 = null;
            String strDecodeStringElement16 = null;
            String strDecodeStringElement17 = null;
            String strDecodeStringElement18 = null;
            String strDecodeStringElement19 = null;
            String strDecodeStringElement20 = null;
            String strDecodeStringElement21 = null;
            String strDecodeStringElement22 = null;
            String strDecodeStringElement23 = null;
            String strDecodeStringElement24 = null;
            String strDecodeStringElement25 = null;
            String strDecodeStringElement26 = null;
            String str58 = null;
            String str59 = null;
            String str60 = null;
            String strDecodeStringElement27 = null;
            String strDecodeStringElement28 = null;
            String strDecodeStringElement29 = null;
            String strDecodeStringElement30 = null;
            int iDecodeIntElement7 = 0;
            int iDecodeIntElement8 = 0;
            int i15 = 0;
            int i16 = 0;
            int iDecodeIntElement9 = 0;
            int i17 = 0;
            int i18 = 0;
            boolean z = true;
            long jDecodeLongElement2 = 0;
            String str61 = null;
            String str62 = null;
            int i19 = 0;
            Integer num14 = null;
            while (z) {
                String str63 = str62;
                int iDecodeElementIndex = compositeDecoderBeginStructure.decodeElementIndex(serialDescriptor);
                switch (iDecodeElementIndex) {
                    case -1:
                        l2 = l5;
                        num4 = num12;
                        str27 = str51;
                        str28 = str58;
                        str29 = str59;
                        str30 = str60;
                        str31 = str63;
                        Unit unit = Unit.INSTANCE;
                        z = false;
                        str32 = str30;
                        str62 = str31;
                        num12 = num4;
                        str60 = str32;
                        str51 = str27;
                        str59 = str29;
                        str58 = str28;
                        l5 = l2;
                        break;
                    case 0:
                        l2 = l5;
                        num4 = num12;
                        str27 = str51;
                        str28 = str58;
                        str29 = str59;
                        str30 = str60;
                        str31 = str63;
                        strDecodeStringElement30 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 0);
                        i19 |= 1;
                        Unit unit2 = Unit.INSTANCE;
                        str32 = str30;
                        str62 = str31;
                        num12 = num4;
                        str60 = str32;
                        str51 = str27;
                        str59 = str29;
                        str58 = str28;
                        l5 = l2;
                        break;
                    case 1:
                        l2 = l5;
                        num4 = num12;
                        str27 = str51;
                        str28 = str58;
                        str29 = str59;
                        str33 = str60;
                        strDecodeStringElement29 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 1);
                        int i20 = i19 | 2;
                        Unit unit3 = Unit.INSTANCE;
                        str34 = str63;
                        i9 = i20;
                        str32 = str33;
                        str62 = str34;
                        i19 = i9;
                        num12 = num4;
                        str60 = str32;
                        str51 = str27;
                        str59 = str29;
                        str58 = str28;
                        l5 = l2;
                        break;
                    case 2:
                        l2 = l5;
                        num4 = num12;
                        str28 = str58;
                        str29 = str59;
                        str33 = str60;
                        str27 = str51;
                        String str64 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 2, StringSerializer.INSTANCE, str63);
                        i9 = i19 | 4;
                        Unit unit4 = Unit.INSTANCE;
                        str34 = str64;
                        str32 = str33;
                        str62 = str34;
                        i19 = i9;
                        num12 = num4;
                        str60 = str32;
                        str51 = str27;
                        str59 = str29;
                        str58 = str28;
                        l5 = l2;
                        break;
                    case 3:
                        Long l6 = l5;
                        num5 = num12;
                        str28 = str58;
                        str29 = str59;
                        str60 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 3, StringSerializer.INSTANCE, str60);
                        i19 |= 8;
                        Unit unit5 = Unit.INSTANCE;
                        l5 = l6;
                        i10 = i16;
                        l2 = l5;
                        str27 = str51;
                        i16 = i10;
                        num12 = num5;
                        str32 = str60;
                        str62 = str63;
                        str60 = str32;
                        str51 = str27;
                        str59 = str29;
                        str58 = str28;
                        l5 = l2;
                        break;
                    case 4:
                        l3 = l5;
                        num5 = num12;
                        str28 = str58;
                        str35 = str59;
                        strDecodeStringElement27 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 4);
                        i19 |= 16;
                        Unit unit6 = Unit.INSTANCE;
                        str59 = str35;
                        str29 = str59;
                        l5 = l3;
                        i10 = i16;
                        l2 = l5;
                        str27 = str51;
                        i16 = i10;
                        num12 = num5;
                        str32 = str60;
                        str62 = str63;
                        str60 = str32;
                        str51 = str27;
                        str59 = str29;
                        str58 = str28;
                        l5 = l2;
                        break;
                    case 5:
                        l3 = l5;
                        num5 = num12;
                        str28 = str58;
                        str35 = str59;
                        iDecodeIntElement9 = compositeDecoderBeginStructure.decodeIntElement(serialDescriptor, 5);
                        i19 |= 32;
                        Unit unit7 = Unit.INSTANCE;
                        str59 = str35;
                        str29 = str59;
                        l5 = l3;
                        i10 = i16;
                        l2 = l5;
                        str27 = str51;
                        i16 = i10;
                        num12 = num5;
                        str32 = str60;
                        str62 = str63;
                        str60 = str32;
                        str51 = str27;
                        str59 = str29;
                        str58 = str28;
                        l5 = l2;
                        break;
                    case 6:
                        l3 = l5;
                        num5 = num12;
                        str28 = str58;
                        str59 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 6, StringSerializer.INSTANCE, str59);
                        Unit unit8 = Unit.INSTANCE;
                        i19 |= 64;
                        str29 = str59;
                        l5 = l3;
                        i10 = i16;
                        l2 = l5;
                        str27 = str51;
                        i16 = i10;
                        num12 = num5;
                        str32 = str60;
                        str62 = str63;
                        str60 = str32;
                        str51 = str27;
                        str59 = str29;
                        str58 = str28;
                        l5 = l2;
                        break;
                    case 7:
                        l3 = l5;
                        num5 = num12;
                        str58 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 7, StringSerializer.INSTANCE, str58);
                        i19 |= 128;
                        Unit unit9 = Unit.INSTANCE;
                        str28 = str58;
                        str29 = str59;
                        l5 = l3;
                        i10 = i16;
                        l2 = l5;
                        str27 = str51;
                        i16 = i10;
                        num12 = num5;
                        str32 = str60;
                        str62 = str63;
                        str60 = str32;
                        str51 = str27;
                        str59 = str29;
                        str58 = str28;
                        l5 = l2;
                        break;
                    case 8:
                        l3 = l5;
                        str55 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 8, StringSerializer.INSTANCE, str55);
                        i19 |= 256;
                        Unit unit10 = Unit.INSTANCE;
                        num5 = num12;
                        str28 = str58;
                        str29 = str59;
                        l5 = l3;
                        i10 = i16;
                        l2 = l5;
                        str27 = str51;
                        i16 = i10;
                        num12 = num5;
                        str32 = str60;
                        str62 = str63;
                        str60 = str32;
                        str51 = str27;
                        str59 = str29;
                        str58 = str28;
                        l5 = l2;
                        break;
                    case 9:
                        str36 = str55;
                        num13 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 9, IntSerializer.INSTANCE, num13);
                        i19 |= 512;
                        Unit unit11 = Unit.INSTANCE;
                        str37 = str61;
                        num7 = num14;
                        str38 = str52;
                        num8 = num13;
                        str39 = str51;
                        num6 = num12;
                        i13 = i15;
                        i15 = i13;
                        num5 = num6;
                        str51 = str39;
                        num13 = num8;
                        str52 = str38;
                        num14 = num7;
                        str61 = str37;
                        str28 = str58;
                        str29 = str59;
                        i10 = i16;
                        str55 = str36;
                        l2 = l5;
                        str27 = str51;
                        i16 = i10;
                        num12 = num5;
                        str32 = str60;
                        str62 = str63;
                        str60 = str32;
                        str51 = str27;
                        str59 = str29;
                        str58 = str28;
                        l5 = l2;
                        break;
                    case 10:
                        str36 = str55;
                        str56 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 10, StringSerializer.INSTANCE, str56);
                        i19 |= 1024;
                        Unit unit12 = Unit.INSTANCE;
                        str37 = str61;
                        num7 = num14;
                        str38 = str52;
                        num8 = num13;
                        str39 = str51;
                        num6 = num12;
                        i13 = i15;
                        i15 = i13;
                        num5 = num6;
                        str51 = str39;
                        num13 = num8;
                        str52 = str38;
                        num14 = num7;
                        str61 = str37;
                        str28 = str58;
                        str29 = str59;
                        i10 = i16;
                        str55 = str36;
                        l2 = l5;
                        str27 = str51;
                        i16 = i10;
                        num12 = num5;
                        str32 = str60;
                        str62 = str63;
                        str60 = str32;
                        str51 = str27;
                        str59 = str29;
                        str58 = str28;
                        l5 = l2;
                        break;
                    case 11:
                        str36 = str55;
                        str54 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 11, StringSerializer.INSTANCE, str54);
                        i19 |= 2048;
                        Unit unit122 = Unit.INSTANCE;
                        str37 = str61;
                        num7 = num14;
                        str38 = str52;
                        num8 = num13;
                        str39 = str51;
                        num6 = num12;
                        i13 = i15;
                        i15 = i13;
                        num5 = num6;
                        str51 = str39;
                        num13 = num8;
                        str52 = str38;
                        num14 = num7;
                        str61 = str37;
                        str28 = str58;
                        str29 = str59;
                        i10 = i16;
                        str55 = str36;
                        l2 = l5;
                        str27 = str51;
                        i16 = i10;
                        num12 = num5;
                        str32 = str60;
                        str62 = str63;
                        str60 = str32;
                        str51 = str27;
                        str59 = str29;
                        str58 = str28;
                        l5 = l2;
                        break;
                    case 12:
                        str36 = str55;
                        num12 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 12, IntSerializer.INSTANCE, num12);
                        i19 |= 4096;
                        Unit unit1222 = Unit.INSTANCE;
                        str37 = str61;
                        num7 = num14;
                        str38 = str52;
                        num8 = num13;
                        str39 = str51;
                        num6 = num12;
                        i13 = i15;
                        i15 = i13;
                        num5 = num6;
                        str51 = str39;
                        num13 = num8;
                        str52 = str38;
                        num14 = num7;
                        str61 = str37;
                        str28 = str58;
                        str29 = str59;
                        i10 = i16;
                        str55 = str36;
                        l2 = l5;
                        str27 = str51;
                        i16 = i10;
                        num12 = num5;
                        str32 = str60;
                        str62 = str63;
                        str60 = str32;
                        str51 = str27;
                        str59 = str29;
                        str58 = str28;
                        l5 = l2;
                        break;
                    case 13:
                        str36 = str55;
                        strDecodeStringElement16 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 13);
                        i19 |= 8192;
                        Unit unit13 = Unit.INSTANCE;
                        str37 = str61;
                        num7 = num14;
                        str38 = str52;
                        num8 = num13;
                        str39 = str51;
                        num6 = num12;
                        i13 = i15;
                        i15 = i13;
                        num5 = num6;
                        str51 = str39;
                        num13 = num8;
                        str52 = str38;
                        num14 = num7;
                        str61 = str37;
                        str28 = str58;
                        str29 = str59;
                        i10 = i16;
                        str55 = str36;
                        l2 = l5;
                        str27 = str51;
                        i16 = i10;
                        num12 = num5;
                        str32 = str60;
                        str62 = str63;
                        str60 = str32;
                        str51 = str27;
                        str59 = str29;
                        str58 = str28;
                        l5 = l2;
                        break;
                    case 14:
                        str36 = str55;
                        int iDecodeIntElement10 = compositeDecoderBeginStructure.decodeIntElement(serialDescriptor, 14);
                        i19 |= 16384;
                        Unit unit14 = Unit.INSTANCE;
                        str37 = str61;
                        i18 = iDecodeIntElement10;
                        num7 = num14;
                        str38 = str52;
                        num8 = num13;
                        str39 = str51;
                        num6 = num12;
                        i13 = i15;
                        i15 = i13;
                        num5 = num6;
                        str51 = str39;
                        num13 = num8;
                        str52 = str38;
                        num14 = num7;
                        str61 = str37;
                        str28 = str58;
                        str29 = str59;
                        i10 = i16;
                        str55 = str36;
                        l2 = l5;
                        str27 = str51;
                        i16 = i10;
                        num12 = num5;
                        str32 = str60;
                        str62 = str63;
                        str60 = str32;
                        str51 = str27;
                        str59 = str29;
                        str58 = str28;
                        l5 = l2;
                        break;
                    case 15:
                        str36 = str55;
                        strDecodeStringElement28 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 15);
                        i11 = 32768;
                        i19 |= i11;
                        Unit unit132 = Unit.INSTANCE;
                        str37 = str61;
                        num7 = num14;
                        str38 = str52;
                        num8 = num13;
                        str39 = str51;
                        num6 = num12;
                        i13 = i15;
                        i15 = i13;
                        num5 = num6;
                        str51 = str39;
                        num13 = num8;
                        str52 = str38;
                        num14 = num7;
                        str61 = str37;
                        str28 = str58;
                        str29 = str59;
                        i10 = i16;
                        str55 = str36;
                        l2 = l5;
                        str27 = str51;
                        i16 = i10;
                        num12 = num5;
                        str32 = str60;
                        str62 = str63;
                        str60 = str32;
                        str51 = str27;
                        str59 = str29;
                        str58 = str28;
                        l5 = l2;
                        break;
                    case 16:
                        str36 = str55;
                        strDecodeStringElement26 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 16);
                        i11 = 65536;
                        i19 |= i11;
                        Unit unit1322 = Unit.INSTANCE;
                        str37 = str61;
                        num7 = num14;
                        str38 = str52;
                        num8 = num13;
                        str39 = str51;
                        num6 = num12;
                        i13 = i15;
                        i15 = i13;
                        num5 = num6;
                        str51 = str39;
                        num13 = num8;
                        str52 = str38;
                        num14 = num7;
                        str61 = str37;
                        str28 = str58;
                        str29 = str59;
                        i10 = i16;
                        str55 = str36;
                        l2 = l5;
                        str27 = str51;
                        i16 = i10;
                        num12 = num5;
                        str32 = str60;
                        str62 = str63;
                        str60 = str32;
                        str51 = str27;
                        str59 = str29;
                        str58 = str28;
                        l5 = l2;
                        break;
                    case 17:
                        str36 = str55;
                        strDecodeStringElement25 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 17);
                        i19 |= 131072;
                        Unit unit15 = Unit.INSTANCE;
                        str37 = str61;
                        num7 = num14;
                        str38 = str52;
                        num8 = num13;
                        str39 = str51;
                        num6 = num12;
                        i13 = i15;
                        i15 = i13;
                        num5 = num6;
                        str51 = str39;
                        num13 = num8;
                        str52 = str38;
                        num14 = num7;
                        str61 = str37;
                        str28 = str58;
                        str29 = str59;
                        i10 = i16;
                        str55 = str36;
                        l2 = l5;
                        str27 = str51;
                        i16 = i10;
                        num12 = num5;
                        str32 = str60;
                        str62 = str63;
                        str60 = str32;
                        str51 = str27;
                        str59 = str29;
                        str58 = str28;
                        l5 = l2;
                        break;
                    case 18:
                        str36 = str55;
                        str53 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 18, StringSerializer.INSTANCE, str53);
                        i12 = 262144;
                        i19 |= i12;
                        Unit unit12222 = Unit.INSTANCE;
                        str37 = str61;
                        num7 = num14;
                        str38 = str52;
                        num8 = num13;
                        str39 = str51;
                        num6 = num12;
                        i13 = i15;
                        i15 = i13;
                        num5 = num6;
                        str51 = str39;
                        num13 = num8;
                        str52 = str38;
                        num14 = num7;
                        str61 = str37;
                        str28 = str58;
                        str29 = str59;
                        i10 = i16;
                        str55 = str36;
                        l2 = l5;
                        str27 = str51;
                        i16 = i10;
                        num12 = num5;
                        str32 = str60;
                        str62 = str63;
                        str60 = str32;
                        str51 = str27;
                        str59 = str29;
                        str58 = str28;
                        l5 = l2;
                        break;
                    case 19:
                        str36 = str55;
                        strDecodeStringElement24 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 19);
                        i12 = 524288;
                        i19 |= i12;
                        Unit unit122222 = Unit.INSTANCE;
                        str37 = str61;
                        num7 = num14;
                        str38 = str52;
                        num8 = num13;
                        str39 = str51;
                        num6 = num12;
                        i13 = i15;
                        i15 = i13;
                        num5 = num6;
                        str51 = str39;
                        num13 = num8;
                        str52 = str38;
                        num14 = num7;
                        str61 = str37;
                        str28 = str58;
                        str29 = str59;
                        i10 = i16;
                        str55 = str36;
                        l2 = l5;
                        str27 = str51;
                        i16 = i10;
                        num12 = num5;
                        str32 = str60;
                        str62 = str63;
                        str60 = str32;
                        str51 = str27;
                        str59 = str29;
                        str58 = str28;
                        l5 = l2;
                        break;
                    case 20:
                        str36 = str55;
                        int iDecodeIntElement11 = compositeDecoderBeginStructure.decodeIntElement(serialDescriptor, 20);
                        i19 |= 1048576;
                        Unit unit16 = Unit.INSTANCE;
                        String str65 = str51;
                        num6 = num12;
                        i13 = iDecodeIntElement11;
                        str37 = str61;
                        num7 = num14;
                        str38 = str52;
                        num8 = num13;
                        str39 = str65;
                        i15 = i13;
                        num5 = num6;
                        str51 = str39;
                        num13 = num8;
                        str52 = str38;
                        num14 = num7;
                        str61 = str37;
                        str28 = str58;
                        str29 = str59;
                        i10 = i16;
                        str55 = str36;
                        l2 = l5;
                        str27 = str51;
                        i16 = i10;
                        num12 = num5;
                        str32 = str60;
                        str62 = str63;
                        str60 = str32;
                        str51 = str27;
                        str59 = str29;
                        str58 = str28;
                        l5 = l2;
                        break;
                    case 21:
                        str36 = str55;
                        strDecodeStringElement17 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 21);
                        i12 = 2097152;
                        i19 |= i12;
                        Unit unit1222222 = Unit.INSTANCE;
                        str37 = str61;
                        num7 = num14;
                        str38 = str52;
                        num8 = num13;
                        str39 = str51;
                        num6 = num12;
                        i13 = i15;
                        i15 = i13;
                        num5 = num6;
                        str51 = str39;
                        num13 = num8;
                        str52 = str38;
                        num14 = num7;
                        str61 = str37;
                        str28 = str58;
                        str29 = str59;
                        i10 = i16;
                        str55 = str36;
                        l2 = l5;
                        str27 = str51;
                        i16 = i10;
                        num12 = num5;
                        str32 = str60;
                        str62 = str63;
                        str60 = str32;
                        str51 = str27;
                        str59 = str29;
                        str58 = str28;
                        l5 = l2;
                        break;
                    case 22:
                        str36 = str55;
                        strDecodeStringElement23 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 22);
                        i12 = 4194304;
                        i19 |= i12;
                        Unit unit12222222 = Unit.INSTANCE;
                        str37 = str61;
                        num7 = num14;
                        str38 = str52;
                        num8 = num13;
                        str39 = str51;
                        num6 = num12;
                        i13 = i15;
                        i15 = i13;
                        num5 = num6;
                        str51 = str39;
                        num13 = num8;
                        str52 = str38;
                        num14 = num7;
                        str61 = str37;
                        str28 = str58;
                        str29 = str59;
                        i10 = i16;
                        str55 = str36;
                        l2 = l5;
                        str27 = str51;
                        i16 = i10;
                        num12 = num5;
                        str32 = str60;
                        str62 = str63;
                        str60 = str32;
                        str51 = str27;
                        str59 = str29;
                        str58 = str28;
                        l5 = l2;
                        break;
                    case 23:
                        str36 = str55;
                        int iDecodeIntElement12 = compositeDecoderBeginStructure.decodeIntElement(serialDescriptor, 23);
                        i19 |= 8388608;
                        Unit unit17 = Unit.INSTANCE;
                        i16 = iDecodeIntElement12;
                        str37 = str61;
                        num7 = num14;
                        str38 = str52;
                        num8 = num13;
                        str39 = str51;
                        num6 = num12;
                        i13 = i15;
                        i15 = i13;
                        num5 = num6;
                        str51 = str39;
                        num13 = num8;
                        str52 = str38;
                        num14 = num7;
                        str61 = str37;
                        str28 = str58;
                        str29 = str59;
                        i10 = i16;
                        str55 = str36;
                        l2 = l5;
                        str27 = str51;
                        i16 = i10;
                        num12 = num5;
                        str32 = str60;
                        str62 = str63;
                        str60 = str32;
                        str51 = str27;
                        str59 = str29;
                        str58 = str28;
                        l5 = l2;
                        break;
                    case 24:
                        str36 = str55;
                        str57 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 24, StringSerializer.INSTANCE, str57);
                        i12 = 16777216;
                        i19 |= i12;
                        Unit unit122222222 = Unit.INSTANCE;
                        str37 = str61;
                        num7 = num14;
                        str38 = str52;
                        num8 = num13;
                        str39 = str51;
                        num6 = num12;
                        i13 = i15;
                        i15 = i13;
                        num5 = num6;
                        str51 = str39;
                        num13 = num8;
                        str52 = str38;
                        num14 = num7;
                        str61 = str37;
                        str28 = str58;
                        str29 = str59;
                        i10 = i16;
                        str55 = str36;
                        l2 = l5;
                        str27 = str51;
                        i16 = i10;
                        num12 = num5;
                        str32 = str60;
                        str62 = str63;
                        str60 = str32;
                        str51 = str27;
                        str59 = str29;
                        str58 = str28;
                        l5 = l2;
                        break;
                    case 25:
                        str36 = str55;
                        num14 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 25, IntSerializer.INSTANCE, num14);
                        i12 = MediaHttpDownloader.MAXIMUM_CHUNK_SIZE;
                        i19 |= i12;
                        Unit unit1222222222 = Unit.INSTANCE;
                        str37 = str61;
                        num7 = num14;
                        str38 = str52;
                        num8 = num13;
                        str39 = str51;
                        num6 = num12;
                        i13 = i15;
                        i15 = i13;
                        num5 = num6;
                        str51 = str39;
                        num13 = num8;
                        str52 = str38;
                        num14 = num7;
                        str61 = str37;
                        str28 = str58;
                        str29 = str59;
                        i10 = i16;
                        str55 = str36;
                        l2 = l5;
                        str27 = str51;
                        i16 = i10;
                        num12 = num5;
                        str32 = str60;
                        str62 = str63;
                        str60 = str32;
                        str51 = str27;
                        str59 = str29;
                        str58 = str28;
                        l5 = l2;
                        break;
                    case 26:
                        str36 = str55;
                        str51 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 26, StringSerializer.INSTANCE, str51);
                        i12 = 67108864;
                        i19 |= i12;
                        Unit unit12222222222 = Unit.INSTANCE;
                        str37 = str61;
                        num7 = num14;
                        str38 = str52;
                        num8 = num13;
                        str39 = str51;
                        num6 = num12;
                        i13 = i15;
                        i15 = i13;
                        num5 = num6;
                        str51 = str39;
                        num13 = num8;
                        str52 = str38;
                        num14 = num7;
                        str61 = str37;
                        str28 = str58;
                        str29 = str59;
                        i10 = i16;
                        str55 = str36;
                        l2 = l5;
                        str27 = str51;
                        i16 = i10;
                        num12 = num5;
                        str32 = str60;
                        str62 = str63;
                        str60 = str32;
                        str51 = str27;
                        str59 = str29;
                        str58 = str28;
                        l5 = l2;
                        break;
                    case 27:
                        str36 = str55;
                        jDecodeLongElement2 = compositeDecoderBeginStructure.decodeLongElement(serialDescriptor, 27);
                        i12 = 134217728;
                        i19 |= i12;
                        Unit unit122222222222 = Unit.INSTANCE;
                        str37 = str61;
                        num7 = num14;
                        str38 = str52;
                        num8 = num13;
                        str39 = str51;
                        num6 = num12;
                        i13 = i15;
                        i15 = i13;
                        num5 = num6;
                        str51 = str39;
                        num13 = num8;
                        str52 = str38;
                        num14 = num7;
                        str61 = str37;
                        str28 = str58;
                        str29 = str59;
                        i10 = i16;
                        str55 = str36;
                        l2 = l5;
                        str27 = str51;
                        i16 = i10;
                        num12 = num5;
                        str32 = str60;
                        str62 = str63;
                        str60 = str32;
                        str51 = str27;
                        str59 = str29;
                        str58 = str28;
                        l5 = l2;
                        break;
                    case 28:
                        str36 = str55;
                        l5 = (Long) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 28, LongSerializer.INSTANCE, l5);
                        i12 = 268435456;
                        i19 |= i12;
                        Unit unit1222222222222 = Unit.INSTANCE;
                        str37 = str61;
                        num7 = num14;
                        str38 = str52;
                        num8 = num13;
                        str39 = str51;
                        num6 = num12;
                        i13 = i15;
                        i15 = i13;
                        num5 = num6;
                        str51 = str39;
                        num13 = num8;
                        str52 = str38;
                        num14 = num7;
                        str61 = str37;
                        str28 = str58;
                        str29 = str59;
                        i10 = i16;
                        str55 = str36;
                        l2 = l5;
                        str27 = str51;
                        i16 = i10;
                        num12 = num5;
                        str32 = str60;
                        str62 = str63;
                        str60 = str32;
                        str51 = str27;
                        str59 = str29;
                        str58 = str28;
                        l5 = l2;
                        break;
                    case 29:
                        str36 = str55;
                        iDecodeIntElement8 = compositeDecoderBeginStructure.decodeIntElement(serialDescriptor, 29);
                        i12 = 536870912;
                        i19 |= i12;
                        Unit unit12222222222222 = Unit.INSTANCE;
                        str37 = str61;
                        num7 = num14;
                        str38 = str52;
                        num8 = num13;
                        str39 = str51;
                        num6 = num12;
                        i13 = i15;
                        i15 = i13;
                        num5 = num6;
                        str51 = str39;
                        num13 = num8;
                        str52 = str38;
                        num14 = num7;
                        str61 = str37;
                        str28 = str58;
                        str29 = str59;
                        i10 = i16;
                        str55 = str36;
                        l2 = l5;
                        str27 = str51;
                        i16 = i10;
                        num12 = num5;
                        str32 = str60;
                        str62 = str63;
                        str60 = str32;
                        str51 = str27;
                        str59 = str29;
                        str58 = str28;
                        l5 = l2;
                        break;
                    case 30:
                        str36 = str55;
                        strDecodeStringElement22 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 30);
                        i12 = 1073741824;
                        i19 |= i12;
                        Unit unit122222222222222 = Unit.INSTANCE;
                        str37 = str61;
                        num7 = num14;
                        str38 = str52;
                        num8 = num13;
                        str39 = str51;
                        num6 = num12;
                        i13 = i15;
                        i15 = i13;
                        num5 = num6;
                        str51 = str39;
                        num13 = num8;
                        str52 = str38;
                        num14 = num7;
                        str61 = str37;
                        str28 = str58;
                        str29 = str59;
                        i10 = i16;
                        str55 = str36;
                        l2 = l5;
                        str27 = str51;
                        i16 = i10;
                        num12 = num5;
                        str32 = str60;
                        str62 = str63;
                        str60 = str32;
                        str51 = str27;
                        str59 = str29;
                        str58 = str28;
                        l5 = l2;
                        break;
                    case 31:
                        str36 = str55;
                        strDecodeStringElement18 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 31);
                        i12 = Integer.MIN_VALUE;
                        i19 |= i12;
                        Unit unit1222222222222222 = Unit.INSTANCE;
                        str37 = str61;
                        num7 = num14;
                        str38 = str52;
                        num8 = num13;
                        str39 = str51;
                        num6 = num12;
                        i13 = i15;
                        i15 = i13;
                        num5 = num6;
                        str51 = str39;
                        num13 = num8;
                        str52 = str38;
                        num14 = num7;
                        str61 = str37;
                        str28 = str58;
                        str29 = str59;
                        i10 = i16;
                        str55 = str36;
                        l2 = l5;
                        str27 = str51;
                        i16 = i10;
                        num12 = num5;
                        str32 = str60;
                        str62 = str63;
                        str60 = str32;
                        str51 = str27;
                        str59 = str29;
                        str58 = str28;
                        l5 = l2;
                        break;
                    case 32:
                        str36 = str55;
                        str52 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 32, StringSerializer.INSTANCE, str52);
                        i17 |= 1;
                        Unit unit12222222222222222 = Unit.INSTANCE;
                        str37 = str61;
                        num7 = num14;
                        str38 = str52;
                        num8 = num13;
                        str39 = str51;
                        num6 = num12;
                        i13 = i15;
                        i15 = i13;
                        num5 = num6;
                        str51 = str39;
                        num13 = num8;
                        str52 = str38;
                        num14 = num7;
                        str61 = str37;
                        str28 = str58;
                        str29 = str59;
                        i10 = i16;
                        str55 = str36;
                        l2 = l5;
                        str27 = str51;
                        i16 = i10;
                        num12 = num5;
                        str32 = str60;
                        str62 = str63;
                        str60 = str32;
                        str51 = str27;
                        str59 = str29;
                        str58 = str28;
                        l5 = l2;
                        break;
                    case 33:
                        str36 = str55;
                        str61 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 33, StringSerializer.INSTANCE, str61);
                        i17 |= 2;
                        Unit unit122222222222222222 = Unit.INSTANCE;
                        str37 = str61;
                        num7 = num14;
                        str38 = str52;
                        num8 = num13;
                        str39 = str51;
                        num6 = num12;
                        i13 = i15;
                        i15 = i13;
                        num5 = num6;
                        str51 = str39;
                        num13 = num8;
                        str52 = str38;
                        num14 = num7;
                        str61 = str37;
                        str28 = str58;
                        str29 = str59;
                        i10 = i16;
                        str55 = str36;
                        l2 = l5;
                        str27 = str51;
                        i16 = i10;
                        num12 = num5;
                        str32 = str60;
                        str62 = str63;
                        str60 = str32;
                        str51 = str27;
                        str59 = str29;
                        str58 = str28;
                        l5 = l2;
                        break;
                    case 34:
                        iDecodeIntElement7 = compositeDecoderBeginStructure.decodeIntElement(serialDescriptor, 34);
                        i14 = i17 | 4;
                        Unit unit18 = Unit.INSTANCE;
                        i17 = i14;
                        l3 = l5;
                        num5 = num12;
                        str28 = str58;
                        str29 = str59;
                        l5 = l3;
                        i10 = i16;
                        l2 = l5;
                        str27 = str51;
                        i16 = i10;
                        num12 = num5;
                        str32 = str60;
                        str62 = str63;
                        str60 = str32;
                        str51 = str27;
                        str59 = str29;
                        str58 = str28;
                        l5 = l2;
                        break;
                    case 35:
                        strDecodeStringElement21 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 35);
                        i14 = i17 | 8;
                        Unit unit182 = Unit.INSTANCE;
                        i17 = i14;
                        l3 = l5;
                        num5 = num12;
                        str28 = str58;
                        str29 = str59;
                        l5 = l3;
                        i10 = i16;
                        l2 = l5;
                        str27 = str51;
                        i16 = i10;
                        num12 = num5;
                        str32 = str60;
                        str62 = str63;
                        str60 = str32;
                        str51 = str27;
                        str59 = str29;
                        str58 = str28;
                        l5 = l2;
                        break;
                    case 36:
                        strDecodeStringElement20 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 36);
                        i14 = i17 | 16;
                        Unit unit1822 = Unit.INSTANCE;
                        i17 = i14;
                        l3 = l5;
                        num5 = num12;
                        str28 = str58;
                        str29 = str59;
                        l5 = l3;
                        i10 = i16;
                        l2 = l5;
                        str27 = str51;
                        i16 = i10;
                        num12 = num5;
                        str32 = str60;
                        str62 = str63;
                        str60 = str32;
                        str51 = str27;
                        str59 = str29;
                        str58 = str28;
                        l5 = l2;
                        break;
                    case 37:
                        strDecodeStringElement19 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 37);
                        i14 = i17 | 32;
                        Unit unit18222 = Unit.INSTANCE;
                        i17 = i14;
                        l3 = l5;
                        num5 = num12;
                        str28 = str58;
                        str29 = str59;
                        l5 = l3;
                        i10 = i16;
                        l2 = l5;
                        str27 = str51;
                        i16 = i10;
                        num12 = num5;
                        str32 = str60;
                        str62 = str63;
                        str60 = str32;
                        str51 = str27;
                        str59 = str29;
                        str58 = str28;
                        l5 = l2;
                        break;
                    default:
                        throw new UnknownFieldException(iDecodeElementIndex);
                }
            }
            String str66 = str58;
            String str67 = str59;
            num = num13;
            str = str52;
            num2 = num14;
            str2 = str61;
            str3 = str60;
            str4 = str54;
            str5 = str55;
            str6 = str56;
            i = iDecodeIntElement7;
            str7 = strDecodeStringElement17;
            str8 = str51;
            str9 = str67;
            str10 = strDecodeStringElement23;
            str11 = strDecodeStringElement26;
            str12 = str66;
            num3 = num12;
            str13 = strDecodeStringElement27;
            str14 = strDecodeStringElement29;
            str15 = strDecodeStringElement30;
            i2 = iDecodeIntElement9;
            i3 = i17;
            i4 = i18;
            str16 = str57;
            i5 = iDecodeIntElement8;
            str17 = strDecodeStringElement16;
            str18 = strDecodeStringElement18;
            str19 = strDecodeStringElement21;
            str20 = strDecodeStringElement22;
            str21 = strDecodeStringElement25;
            str22 = strDecodeStringElement28;
            l = l5;
            i6 = i15;
            i7 = i16;
            str23 = str62;
            strDecodeStringElement = strDecodeStringElement19;
            str24 = strDecodeStringElement20;
            str25 = strDecodeStringElement24;
            j = jDecodeLongElement2;
            str26 = str53;
            i8 = i19;
        }
        compositeDecoderBeginStructure.endStructure(serialDescriptor);
        return new RedPacketOrderDetailApiModel(i8, i3, str15, str14, str23, str3, str13, i2, str9, str12, str5, num, str6, str4, num3, str17, i4, str22, str11, str21, str26, str25, i6, str7, str10, i7, str16, num2, str8, j, l, i5, str20, str18, str, str2, i, str19, str24, strDecodeStringElement, (SerializationConstructorMarker) null);
    }

    /* JADX DEBUG: Method merged with bridge method: serialize(Lkotlinx/serialization/encoding/Encoder;Ljava/lang/Object;)V */
    @Override // kotlinx.serialization.SerializationStrategy
    public final void serialize(@NotNull Encoder encoder, @NotNull RedPacketOrderDetailApiModel redPacketOrderDetailApiModel) {
        Intrinsics.checkNotNullParameter(encoder, "");
        Intrinsics.checkNotNullParameter(redPacketOrderDetailApiModel, "");
        SerialDescriptor serialDescriptor = descriptor;
        CompositeEncoder compositeEncoderBeginStructure = encoder.beginStructure(serialDescriptor);
        RedPacketOrderDetailApiModel.write$Self$OKPayCore_web3pay_lib(redPacketOrderDetailApiModel, compositeEncoderBeginStructure, serialDescriptor);
        compositeEncoderBeginStructure.endStructure(serialDescriptor);
    }
}
