package com.okinc.business.dexlogic.main.limmitorder.bean;

import com.google.api.client.googleapis.media.MediaHttpDownloader;
import com.google.firebase.analytics.FirebaseAnalytics;
import com.okinc.business.dexlogic.bean.DefiPlatformInfos;
import com.okinc.business.dexlogic.bean.DefiPlatformInfos$$serializer;
import java.util.List;
import kotlin.Unit;
import kotlin.jvm.internal.Intrinsics;
import kotlinx.serialization.KSerializer;
import kotlinx.serialization.UnknownFieldException;
import kotlinx.serialization.builtins.BuiltinSerializersKt;
import kotlinx.serialization.descriptors.SerialDescriptor;
import kotlinx.serialization.encoding.CompositeDecoder;
import kotlinx.serialization.encoding.CompositeEncoder;
import kotlinx.serialization.encoding.Decoder;
import kotlinx.serialization.encoding.Encoder;
import kotlinx.serialization.internal.BooleanSerializer;
import kotlinx.serialization.internal.GeneratedSerializer;
import kotlinx.serialization.internal.IntSerializer;
import kotlinx.serialization.internal.PluginGeneratedSerialDescriptor;
import kotlinx.serialization.internal.SerializationConstructorMarker;
import kotlinx.serialization.internal.StringSerializer;
import org.jetbrains.annotations.NotNull;

/* JADX INFO: loaded from: classes18.dex */
public final /* synthetic */ class LimitState$$serializer implements GeneratedSerializer<LimitState> {
    public static final int $stable;
    public static final LimitState$$serializer INSTANCE;
    private static final SerialDescriptor descriptor;

    /* JADX DEBUG: Don't trust debug lines info. Lines numbers was adjusted: min line is 0 */
    private LimitState$$serializer() {
    }

    /* JADX DEBUG: Don't trust debug lines info. Lines numbers was adjusted: min line is 0 */
    @Override // kotlinx.serialization.KSerializer, kotlinx.serialization.SerializationStrategy, kotlinx.serialization.DeserializationStrategy
    public final SerialDescriptor getDescriptor() {
        return descriptor;
    }

    static {
        LimitState$$serializer limitState$$serializer = new LimitState$$serializer();
        INSTANCE = limitState$$serializer;
        $stable = 8;
        PluginGeneratedSerialDescriptor pluginGeneratedSerialDescriptor = new PluginGeneratedSerialDescriptor("com.okinc.business.dexlogic.main.limmitorder.bean.LimitState", limitState$$serializer, 41);
        pluginGeneratedSerialDescriptor.addElement("createTime", true);
        pluginGeneratedSerialDescriptor.addElement("expireTime", true);
        pluginGeneratedSerialDescriptor.addElement("exploreUrl", true);
        pluginGeneratedSerialDescriptor.addElement("failureReason", true);
        pluginGeneratedSerialDescriptor.addElement("defiPlatformInfo", true);
        pluginGeneratedSerialDescriptor.addElement("fromChildOrderDetailVO", true);
        pluginGeneratedSerialDescriptor.addElement("orderId", true);
        pluginGeneratedSerialDescriptor.addElement(FirebaseAnalytics.Param.PRICE, true);
        pluginGeneratedSerialDescriptor.addElement("remainTime", true);
        pluginGeneratedSerialDescriptor.addElement("status", true);
        pluginGeneratedSerialDescriptor.addElement("submitToast", true);
        pluginGeneratedSerialDescriptor.addElement("surplus", true);
        pluginGeneratedSerialDescriptor.addElement("surplusUsdValue", true);
        pluginGeneratedSerialDescriptor.addElement("swapTradeType", true);
        pluginGeneratedSerialDescriptor.addElement("totalGasFee", true);
        pluginGeneratedSerialDescriptor.addElement("totalGasFeeUsdValue", true);
        pluginGeneratedSerialDescriptor.addElement("latestTransactionHash", true);
        pluginGeneratedSerialDescriptor.addElement("transactionTime", true);
        pluginGeneratedSerialDescriptor.addElement("transactionPrice", true);
        pluginGeneratedSerialDescriptor.addElement("type", true);
        pluginGeneratedSerialDescriptor.addElement("userWalletAddress", true);
        pluginGeneratedSerialDescriptor.addElement("dealWarnTag", true);
        pluginGeneratedSerialDescriptor.addElement("timeoutToast", true);
        pluginGeneratedSerialDescriptor.addElement("canEdit", true);
        pluginGeneratedSerialDescriptor.addElement("canCancel", true);
        pluginGeneratedSerialDescriptor.addElement("slippage", true);
        pluginGeneratedSerialDescriptor.addElement("priorityFee", true);
        pluginGeneratedSerialDescriptor.addElement("feeToken", true);
        pluginGeneratedSerialDescriptor.addElement("preFailureReason", true);
        pluginGeneratedSerialDescriptor.addElement("quickRateType", true);
        pluginGeneratedSerialDescriptor.addElement("triggerCondition", true);
        pluginGeneratedSerialDescriptor.addElement("totalReceiveAmount", true);
        pluginGeneratedSerialDescriptor.addElement("serviceFeeUsd", true);
        pluginGeneratedSerialDescriptor.addElement("serviceFeeRate", true);
        pluginGeneratedSerialDescriptor.addElement("serviceFee", true);
        pluginGeneratedSerialDescriptor.addElement("serviceFeeTokenSymbol", true);
        pluginGeneratedSerialDescriptor.addElement("isDisplayServiceFee", true);
        pluginGeneratedSerialDescriptor.addElement("executionHistoryList", true);
        pluginGeneratedSerialDescriptor.addElement("executionHistoryShowMaxNum", true);
        pluginGeneratedSerialDescriptor.addElement("isShowExecutionHistoryMaxNum", true);
        pluginGeneratedSerialDescriptor.addElement("bannerMessage", true);
        descriptor = pluginGeneratedSerialDescriptor;
    }

    @Override // kotlinx.serialization.internal.GeneratedSerializer
    public final KSerializer<?>[] childSerializers() {
        KSerializer[] kSerializerArr = LimitState.$childSerializers;
        StringSerializer stringSerializer = StringSerializer.INSTANCE;
        BooleanSerializer booleanSerializer = BooleanSerializer.INSTANCE;
        IntSerializer intSerializer = IntSerializer.INSTANCE;
        return new KSerializer[]{stringSerializer, stringSerializer, stringSerializer, stringSerializer, DefiPlatformInfos$$serializer.INSTANCE, BuiltinSerializersKt.getNullable(FromChildOrderDetailVO$$serializer.INSTANCE), stringSerializer, stringSerializer, stringSerializer, stringSerializer, stringSerializer, stringSerializer, stringSerializer, stringSerializer, stringSerializer, stringSerializer, stringSerializer, stringSerializer, stringSerializer, stringSerializer, stringSerializer, booleanSerializer, booleanSerializer, intSerializer, intSerializer, stringSerializer, stringSerializer, stringSerializer, stringSerializer, BuiltinSerializersKt.getNullable(intSerializer), BuiltinSerializersKt.getNullable(intSerializer), stringSerializer, stringSerializer, stringSerializer, stringSerializer, stringSerializer, stringSerializer, BuiltinSerializersKt.getNullable(kSerializerArr[37]), BuiltinSerializersKt.getNullable(intSerializer), BuiltinSerializersKt.getNullable(intSerializer), stringSerializer};
    }

    /* JADX DEBUG: Method merged with bridge method: deserialize(Lkotlinx/serialization/encoding/Decoder;)Ljava/lang/Object; */
    @Override // kotlinx.serialization.DeserializationStrategy
    public final LimitState deserialize(@NotNull Decoder decoder) {
        String strDecodeStringElement;
        int i;
        FromChildOrderDetailVO fromChildOrderDetailVO;
        DefiPlatformInfos defiPlatformInfos;
        String str;
        String str2;
        String str3;
        String str4;
        String str5;
        String str6;
        String str7;
        String str8;
        String str9;
        String str10;
        String str11;
        String str12;
        String str13;
        String str14;
        String str15;
        String str16;
        List list;
        Integer num;
        Integer num2;
        String str17;
        String str18;
        String str19;
        String str20;
        String str21;
        Integer num3;
        int i2;
        int i3;
        boolean z;
        boolean z2;
        String str22;
        String str23;
        Integer num4;
        String strDecodeStringElement2;
        String str24;
        String str25;
        String str26;
        int i4;
        String str27;
        String str28;
        KSerializer[] kSerializerArr;
        FromChildOrderDetailVO fromChildOrderDetailVO2;
        int i5;
        int i6;
        int i7;
        Intrinsics.checkNotNullParameter(decoder, "");
        SerialDescriptor serialDescriptor = descriptor;
        CompositeDecoder compositeDecoderBeginStructure = decoder.beginStructure(serialDescriptor);
        KSerializer[] kSerializerArr2 = LimitState.$childSerializers;
        int i8 = 10;
        int i9 = 9;
        int i10 = 8;
        if (compositeDecoderBeginStructure.decodeSequentially()) {
            String strDecodeStringElement3 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 0);
            String strDecodeStringElement4 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 1);
            String strDecodeStringElement5 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 2);
            String strDecodeStringElement6 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 3);
            DefiPlatformInfos defiPlatformInfos2 = (DefiPlatformInfos) compositeDecoderBeginStructure.decodeSerializableElement(serialDescriptor, 4, DefiPlatformInfos$$serializer.INSTANCE, null);
            FromChildOrderDetailVO fromChildOrderDetailVO3 = (FromChildOrderDetailVO) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 5, FromChildOrderDetailVO$$serializer.INSTANCE, null);
            String strDecodeStringElement7 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 6);
            String strDecodeStringElement8 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 7);
            String strDecodeStringElement9 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 8);
            String strDecodeStringElement10 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 9);
            String strDecodeStringElement11 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 10);
            String strDecodeStringElement12 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 11);
            String strDecodeStringElement13 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 12);
            String strDecodeStringElement14 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 13);
            String strDecodeStringElement15 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 14);
            String strDecodeStringElement16 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 15);
            String strDecodeStringElement17 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 16);
            String strDecodeStringElement18 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 17);
            String strDecodeStringElement19 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 18);
            String strDecodeStringElement20 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 19);
            String strDecodeStringElement21 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 20);
            boolean zDecodeBooleanElement = compositeDecoderBeginStructure.decodeBooleanElement(serialDescriptor, 21);
            boolean zDecodeBooleanElement2 = compositeDecoderBeginStructure.decodeBooleanElement(serialDescriptor, 22);
            int iDecodeIntElement = compositeDecoderBeginStructure.decodeIntElement(serialDescriptor, 23);
            int iDecodeIntElement2 = compositeDecoderBeginStructure.decodeIntElement(serialDescriptor, 24);
            String strDecodeStringElement22 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 25);
            String strDecodeStringElement23 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 26);
            String strDecodeStringElement24 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 27);
            String strDecodeStringElement25 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 28);
            IntSerializer intSerializer = IntSerializer.INSTANCE;
            Integer num5 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 29, intSerializer, null);
            Integer num6 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 30, intSerializer, null);
            String strDecodeStringElement26 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 31);
            String strDecodeStringElement27 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 32);
            String strDecodeStringElement28 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 33);
            String strDecodeStringElement29 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 34);
            String strDecodeStringElement30 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 35);
            String strDecodeStringElement31 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 36);
            List list2 = (List) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 37, kSerializerArr2[37], null);
            Integer num7 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 38, intSerializer, null);
            num4 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 39, intSerializer, null);
            strDecodeStringElement2 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 40);
            num3 = num7;
            str27 = strDecodeStringElement26;
            str26 = strDecodeStringElement27;
            list = list2;
            str5 = strDecodeStringElement24;
            strDecodeStringElement = strDecodeStringElement25;
            str23 = strDecodeStringElement9;
            num2 = num5;
            num = num6;
            str20 = strDecodeStringElement28;
            str4 = strDecodeStringElement29;
            str19 = strDecodeStringElement30;
            str18 = strDecodeStringElement31;
            str24 = strDecodeStringElement18;
            str15 = strDecodeStringElement4;
            str17 = strDecodeStringElement17;
            str16 = strDecodeStringElement3;
            str2 = strDecodeStringElement20;
            str3 = strDecodeStringElement21;
            z2 = zDecodeBooleanElement;
            z = zDecodeBooleanElement2;
            i2 = iDecodeIntElement;
            i4 = iDecodeIntElement2;
            str28 = strDecodeStringElement22;
            str14 = strDecodeStringElement5;
            i = 511;
            str25 = strDecodeStringElement13;
            str7 = strDecodeStringElement11;
            str22 = strDecodeStringElement10;
            str11 = strDecodeStringElement8;
            str12 = strDecodeStringElement7;
            str21 = strDecodeStringElement12;
            str9 = strDecodeStringElement15;
            str10 = strDecodeStringElement14;
            i3 = -1;
            defiPlatformInfos = defiPlatformInfos2;
            fromChildOrderDetailVO = fromChildOrderDetailVO3;
            str6 = strDecodeStringElement23;
            str8 = strDecodeStringElement16;
            str13 = strDecodeStringElement6;
            str = strDecodeStringElement19;
        } else {
            int i11 = 0;
            int iDecodeIntElement3 = 0;
            int i12 = 0;
            boolean zDecodeBooleanElement3 = false;
            boolean zDecodeBooleanElement4 = false;
            List list3 = null;
            Integer num8 = null;
            Integer num9 = null;
            Integer num10 = null;
            String strDecodeStringElement32 = null;
            String strDecodeStringElement33 = null;
            String strDecodeStringElement34 = null;
            String strDecodeStringElement35 = null;
            String strDecodeStringElement36 = null;
            String strDecodeStringElement37 = null;
            String strDecodeStringElement38 = null;
            String strDecodeStringElement39 = null;
            String strDecodeStringElement40 = null;
            String strDecodeStringElement41 = null;
            String strDecodeStringElement42 = null;
            String strDecodeStringElement43 = null;
            strDecodeStringElement = null;
            String strDecodeStringElement44 = null;
            String strDecodeStringElement45 = null;
            String strDecodeStringElement46 = null;
            String strDecodeStringElement47 = null;
            String strDecodeStringElement48 = null;
            FromChildOrderDetailVO fromChildOrderDetailVO4 = null;
            String strDecodeStringElement49 = null;
            String strDecodeStringElement50 = null;
            String strDecodeStringElement51 = null;
            String strDecodeStringElement52 = null;
            String strDecodeStringElement53 = null;
            String strDecodeStringElement54 = null;
            String strDecodeStringElement55 = null;
            String strDecodeStringElement56 = null;
            String strDecodeStringElement57 = null;
            String strDecodeStringElement58 = null;
            String strDecodeStringElement59 = null;
            DefiPlatformInfos defiPlatformInfos3 = null;
            String str29 = null;
            boolean z3 = true;
            Integer num11 = null;
            int iDecodeIntElement4 = 0;
            while (z3) {
                int iDecodeElementIndex = compositeDecoderBeginStructure.decodeElementIndex(serialDescriptor);
                switch (iDecodeElementIndex) {
                    case -1:
                        kSerializerArr = kSerializerArr2;
                        fromChildOrderDetailVO2 = fromChildOrderDetailVO4;
                        Unit unit = Unit.INSTANCE;
                        z3 = false;
                        fromChildOrderDetailVO4 = fromChildOrderDetailVO2;
                        kSerializerArr2 = kSerializerArr;
                        i10 = 8;
                        i8 = 10;
                        i9 = 9;
                        break;
                    case 0:
                        kSerializerArr = kSerializerArr2;
                        fromChildOrderDetailVO2 = fromChildOrderDetailVO4;
                        DefiPlatformInfos defiPlatformInfos4 = defiPlatformInfos3;
                        String strDecodeStringElement60 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 0);
                        i12 |= 1;
                        Unit unit2 = Unit.INSTANCE;
                        defiPlatformInfos3 = defiPlatformInfos4;
                        str29 = strDecodeStringElement60;
                        fromChildOrderDetailVO4 = fromChildOrderDetailVO2;
                        kSerializerArr2 = kSerializerArr;
                        i10 = 8;
                        i8 = 10;
                        i9 = 9;
                        break;
                    case 1:
                        kSerializerArr = kSerializerArr2;
                        fromChildOrderDetailVO2 = fromChildOrderDetailVO4;
                        strDecodeStringElement59 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 1);
                        i12 |= 2;
                        Unit unit3 = Unit.INSTANCE;
                        fromChildOrderDetailVO4 = fromChildOrderDetailVO2;
                        kSerializerArr2 = kSerializerArr;
                        i10 = 8;
                        i8 = 10;
                        i9 = 9;
                        break;
                    case 2:
                        kSerializerArr = kSerializerArr2;
                        fromChildOrderDetailVO2 = fromChildOrderDetailVO4;
                        strDecodeStringElement58 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 2);
                        i12 |= 4;
                        Unit unit4 = Unit.INSTANCE;
                        fromChildOrderDetailVO4 = fromChildOrderDetailVO2;
                        kSerializerArr2 = kSerializerArr;
                        i10 = 8;
                        i8 = 10;
                        i9 = 9;
                        break;
                    case 3:
                        kSerializerArr = kSerializerArr2;
                        fromChildOrderDetailVO2 = fromChildOrderDetailVO4;
                        strDecodeStringElement57 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 3);
                        i12 |= 8;
                        Unit unit5 = Unit.INSTANCE;
                        fromChildOrderDetailVO4 = fromChildOrderDetailVO2;
                        kSerializerArr2 = kSerializerArr;
                        i10 = 8;
                        i8 = 10;
                        i9 = 9;
                        break;
                    case 4:
                        fromChildOrderDetailVO2 = fromChildOrderDetailVO4;
                        kSerializerArr = kSerializerArr2;
                        defiPlatformInfos3 = (DefiPlatformInfos) compositeDecoderBeginStructure.decodeSerializableElement(serialDescriptor, 4, DefiPlatformInfos$$serializer.INSTANCE, defiPlatformInfos3);
                        Unit unit6 = Unit.INSTANCE;
                        i12 |= 16;
                        fromChildOrderDetailVO4 = fromChildOrderDetailVO2;
                        kSerializerArr2 = kSerializerArr;
                        i10 = 8;
                        i8 = 10;
                        i9 = 9;
                        break;
                    case 5:
                        fromChildOrderDetailVO4 = (FromChildOrderDetailVO) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 5, FromChildOrderDetailVO$$serializer.INSTANCE, fromChildOrderDetailVO4);
                        i12 |= 32;
                        Unit unit7 = Unit.INSTANCE;
                        kSerializerArr = kSerializerArr2;
                        fromChildOrderDetailVO2 = fromChildOrderDetailVO4;
                        fromChildOrderDetailVO4 = fromChildOrderDetailVO2;
                        kSerializerArr2 = kSerializerArr;
                        i10 = 8;
                        i8 = 10;
                        i9 = 9;
                        break;
                    case 6:
                        strDecodeStringElement56 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 6);
                        i12 |= 64;
                        Unit unit8 = Unit.INSTANCE;
                        kSerializerArr = kSerializerArr2;
                        fromChildOrderDetailVO2 = fromChildOrderDetailVO4;
                        fromChildOrderDetailVO4 = fromChildOrderDetailVO2;
                        kSerializerArr2 = kSerializerArr;
                        i10 = 8;
                        i8 = 10;
                        i9 = 9;
                        break;
                    case 7:
                        strDecodeStringElement55 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 7);
                        i12 |= 128;
                        Unit unit82 = Unit.INSTANCE;
                        kSerializerArr = kSerializerArr2;
                        fromChildOrderDetailVO2 = fromChildOrderDetailVO4;
                        fromChildOrderDetailVO4 = fromChildOrderDetailVO2;
                        kSerializerArr2 = kSerializerArr;
                        i10 = 8;
                        i8 = 10;
                        i9 = 9;
                        break;
                    case 8:
                        strDecodeStringElement54 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, i10);
                        i12 |= 256;
                        Unit unit822 = Unit.INSTANCE;
                        kSerializerArr = kSerializerArr2;
                        fromChildOrderDetailVO2 = fromChildOrderDetailVO4;
                        fromChildOrderDetailVO4 = fromChildOrderDetailVO2;
                        kSerializerArr2 = kSerializerArr;
                        i10 = 8;
                        i8 = 10;
                        i9 = 9;
                        break;
                    case 9:
                        strDecodeStringElement53 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, i9);
                        i12 |= 512;
                        Unit unit8222 = Unit.INSTANCE;
                        kSerializerArr = kSerializerArr2;
                        fromChildOrderDetailVO2 = fromChildOrderDetailVO4;
                        fromChildOrderDetailVO4 = fromChildOrderDetailVO2;
                        kSerializerArr2 = kSerializerArr;
                        i10 = 8;
                        i8 = 10;
                        i9 = 9;
                        break;
                    case 10:
                        strDecodeStringElement48 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, i8);
                        i12 |= 1024;
                        Unit unit82222 = Unit.INSTANCE;
                        kSerializerArr = kSerializerArr2;
                        fromChildOrderDetailVO2 = fromChildOrderDetailVO4;
                        fromChildOrderDetailVO4 = fromChildOrderDetailVO2;
                        kSerializerArr2 = kSerializerArr;
                        i10 = 8;
                        i8 = 10;
                        i9 = 9;
                        break;
                    case 11:
                        strDecodeStringElement52 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 11);
                        i12 |= 2048;
                        Unit unit822222 = Unit.INSTANCE;
                        kSerializerArr = kSerializerArr2;
                        fromChildOrderDetailVO2 = fromChildOrderDetailVO4;
                        fromChildOrderDetailVO4 = fromChildOrderDetailVO2;
                        kSerializerArr2 = kSerializerArr;
                        i10 = 8;
                        i8 = 10;
                        i9 = 9;
                        break;
                    case 12:
                        strDecodeStringElement47 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 12);
                        i12 |= 4096;
                        Unit unit8222222 = Unit.INSTANCE;
                        kSerializerArr = kSerializerArr2;
                        fromChildOrderDetailVO2 = fromChildOrderDetailVO4;
                        fromChildOrderDetailVO4 = fromChildOrderDetailVO2;
                        kSerializerArr2 = kSerializerArr;
                        i10 = 8;
                        i8 = 10;
                        i9 = 9;
                        break;
                    case 13:
                        strDecodeStringElement51 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 13);
                        i12 |= 8192;
                        Unit unit82222222 = Unit.INSTANCE;
                        kSerializerArr = kSerializerArr2;
                        fromChildOrderDetailVO2 = fromChildOrderDetailVO4;
                        fromChildOrderDetailVO4 = fromChildOrderDetailVO2;
                        kSerializerArr2 = kSerializerArr;
                        i10 = 8;
                        i8 = 10;
                        i9 = 9;
                        break;
                    case 14:
                        strDecodeStringElement50 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 14);
                        i12 |= 16384;
                        Unit unit822222222 = Unit.INSTANCE;
                        kSerializerArr = kSerializerArr2;
                        fromChildOrderDetailVO2 = fromChildOrderDetailVO4;
                        fromChildOrderDetailVO4 = fromChildOrderDetailVO2;
                        kSerializerArr2 = kSerializerArr;
                        i10 = 8;
                        i8 = 10;
                        i9 = 9;
                        break;
                    case 15:
                        strDecodeStringElement49 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 15);
                        i5 = 32768;
                        i12 |= i5;
                        Unit unit8222222222 = Unit.INSTANCE;
                        kSerializerArr = kSerializerArr2;
                        fromChildOrderDetailVO2 = fromChildOrderDetailVO4;
                        fromChildOrderDetailVO4 = fromChildOrderDetailVO2;
                        kSerializerArr2 = kSerializerArr;
                        i10 = 8;
                        i8 = 10;
                        i9 = 9;
                        break;
                    case 16:
                        strDecodeStringElement32 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 16);
                        i5 = 65536;
                        i12 |= i5;
                        Unit unit82222222222 = Unit.INSTANCE;
                        kSerializerArr = kSerializerArr2;
                        fromChildOrderDetailVO2 = fromChildOrderDetailVO4;
                        fromChildOrderDetailVO4 = fromChildOrderDetailVO2;
                        kSerializerArr2 = kSerializerArr;
                        i10 = 8;
                        i8 = 10;
                        i9 = 9;
                        break;
                    case 17:
                        strDecodeStringElement33 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 17);
                        i5 = 131072;
                        i12 |= i5;
                        Unit unit822222222222 = Unit.INSTANCE;
                        kSerializerArr = kSerializerArr2;
                        fromChildOrderDetailVO2 = fromChildOrderDetailVO4;
                        fromChildOrderDetailVO4 = fromChildOrderDetailVO2;
                        kSerializerArr2 = kSerializerArr;
                        i10 = 8;
                        i8 = 10;
                        i9 = 9;
                        break;
                    case 18:
                        strDecodeStringElement34 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 18);
                        i12 |= 262144;
                        Unit unit9 = Unit.INSTANCE;
                        kSerializerArr = kSerializerArr2;
                        fromChildOrderDetailVO2 = fromChildOrderDetailVO4;
                        fromChildOrderDetailVO4 = fromChildOrderDetailVO2;
                        kSerializerArr2 = kSerializerArr;
                        i10 = 8;
                        i8 = 10;
                        i9 = 9;
                        break;
                    case 19:
                        strDecodeStringElement35 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 19);
                        i6 = 524288;
                        i12 |= i6;
                        Unit unit10 = Unit.INSTANCE;
                        kSerializerArr = kSerializerArr2;
                        fromChildOrderDetailVO2 = fromChildOrderDetailVO4;
                        fromChildOrderDetailVO4 = fromChildOrderDetailVO2;
                        kSerializerArr2 = kSerializerArr;
                        i10 = 8;
                        i8 = 10;
                        i9 = 9;
                        break;
                    case 20:
                        strDecodeStringElement36 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 20);
                        i6 = 1048576;
                        i12 |= i6;
                        Unit unit102 = Unit.INSTANCE;
                        kSerializerArr = kSerializerArr2;
                        fromChildOrderDetailVO2 = fromChildOrderDetailVO4;
                        fromChildOrderDetailVO4 = fromChildOrderDetailVO2;
                        kSerializerArr2 = kSerializerArr;
                        i10 = 8;
                        i8 = 10;
                        i9 = 9;
                        break;
                    case 21:
                        zDecodeBooleanElement4 = compositeDecoderBeginStructure.decodeBooleanElement(serialDescriptor, 21);
                        i7 = 2097152;
                        i12 = i7 | i12;
                        Unit unit72 = Unit.INSTANCE;
                        kSerializerArr = kSerializerArr2;
                        fromChildOrderDetailVO2 = fromChildOrderDetailVO4;
                        fromChildOrderDetailVO4 = fromChildOrderDetailVO2;
                        kSerializerArr2 = kSerializerArr;
                        i10 = 8;
                        i8 = 10;
                        i9 = 9;
                        break;
                    case 22:
                        zDecodeBooleanElement3 = compositeDecoderBeginStructure.decodeBooleanElement(serialDescriptor, 22);
                        i7 = 4194304;
                        i12 = i7 | i12;
                        Unit unit722 = Unit.INSTANCE;
                        kSerializerArr = kSerializerArr2;
                        fromChildOrderDetailVO2 = fromChildOrderDetailVO4;
                        fromChildOrderDetailVO4 = fromChildOrderDetailVO2;
                        kSerializerArr2 = kSerializerArr;
                        i10 = 8;
                        i8 = 10;
                        i9 = 9;
                        break;
                    case 23:
                        iDecodeIntElement4 = compositeDecoderBeginStructure.decodeIntElement(serialDescriptor, 23);
                        i7 = 8388608;
                        i12 = i7 | i12;
                        Unit unit7222 = Unit.INSTANCE;
                        kSerializerArr = kSerializerArr2;
                        fromChildOrderDetailVO2 = fromChildOrderDetailVO4;
                        fromChildOrderDetailVO4 = fromChildOrderDetailVO2;
                        kSerializerArr2 = kSerializerArr;
                        i10 = 8;
                        i8 = 10;
                        i9 = 9;
                        break;
                    case 24:
                        iDecodeIntElement3 = compositeDecoderBeginStructure.decodeIntElement(serialDescriptor, 24);
                        i7 = 16777216;
                        i12 = i7 | i12;
                        Unit unit72222 = Unit.INSTANCE;
                        kSerializerArr = kSerializerArr2;
                        fromChildOrderDetailVO2 = fromChildOrderDetailVO4;
                        fromChildOrderDetailVO4 = fromChildOrderDetailVO2;
                        kSerializerArr2 = kSerializerArr;
                        i10 = 8;
                        i8 = 10;
                        i9 = 9;
                        break;
                    case 25:
                        strDecodeStringElement46 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 25);
                        i6 = MediaHttpDownloader.MAXIMUM_CHUNK_SIZE;
                        i12 |= i6;
                        Unit unit1022 = Unit.INSTANCE;
                        kSerializerArr = kSerializerArr2;
                        fromChildOrderDetailVO2 = fromChildOrderDetailVO4;
                        fromChildOrderDetailVO4 = fromChildOrderDetailVO2;
                        kSerializerArr2 = kSerializerArr;
                        i10 = 8;
                        i8 = 10;
                        i9 = 9;
                        break;
                    case 26:
                        strDecodeStringElement45 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 26);
                        i6 = 67108864;
                        i12 |= i6;
                        Unit unit10222 = Unit.INSTANCE;
                        kSerializerArr = kSerializerArr2;
                        fromChildOrderDetailVO2 = fromChildOrderDetailVO4;
                        fromChildOrderDetailVO4 = fromChildOrderDetailVO2;
                        kSerializerArr2 = kSerializerArr;
                        i10 = 8;
                        i8 = 10;
                        i9 = 9;
                        break;
                    case 27:
                        strDecodeStringElement44 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 27);
                        i6 = 134217728;
                        i12 |= i6;
                        Unit unit102222 = Unit.INSTANCE;
                        kSerializerArr = kSerializerArr2;
                        fromChildOrderDetailVO2 = fromChildOrderDetailVO4;
                        fromChildOrderDetailVO4 = fromChildOrderDetailVO2;
                        kSerializerArr2 = kSerializerArr;
                        i10 = 8;
                        i8 = 10;
                        i9 = 9;
                        break;
                    case 28:
                        strDecodeStringElement = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 28);
                        i6 = 268435456;
                        i12 |= i6;
                        Unit unit1022222 = Unit.INSTANCE;
                        kSerializerArr = kSerializerArr2;
                        fromChildOrderDetailVO2 = fromChildOrderDetailVO4;
                        fromChildOrderDetailVO4 = fromChildOrderDetailVO2;
                        kSerializerArr2 = kSerializerArr;
                        i10 = 8;
                        i8 = 10;
                        i9 = 9;
                        break;
                    case 29:
                        num10 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 29, IntSerializer.INSTANCE, num10);
                        i7 = 536870912;
                        i12 = i7 | i12;
                        Unit unit722222 = Unit.INSTANCE;
                        kSerializerArr = kSerializerArr2;
                        fromChildOrderDetailVO2 = fromChildOrderDetailVO4;
                        fromChildOrderDetailVO4 = fromChildOrderDetailVO2;
                        kSerializerArr2 = kSerializerArr;
                        i10 = 8;
                        i8 = 10;
                        i9 = 9;
                        break;
                    case 30:
                        num8 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 30, IntSerializer.INSTANCE, num8);
                        i7 = 1073741824;
                        i12 = i7 | i12;
                        Unit unit7222222 = Unit.INSTANCE;
                        kSerializerArr = kSerializerArr2;
                        fromChildOrderDetailVO2 = fromChildOrderDetailVO4;
                        fromChildOrderDetailVO4 = fromChildOrderDetailVO2;
                        kSerializerArr2 = kSerializerArr;
                        i10 = 8;
                        i8 = 10;
                        i9 = 9;
                        break;
                    case 31:
                        strDecodeStringElement43 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 31);
                        i6 = Integer.MIN_VALUE;
                        i12 |= i6;
                        Unit unit10222222 = Unit.INSTANCE;
                        kSerializerArr = kSerializerArr2;
                        fromChildOrderDetailVO2 = fromChildOrderDetailVO4;
                        fromChildOrderDetailVO4 = fromChildOrderDetailVO2;
                        kSerializerArr2 = kSerializerArr;
                        i10 = 8;
                        i8 = 10;
                        i9 = 9;
                        break;
                    case 32:
                        strDecodeStringElement42 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 32);
                        i11 |= 1;
                        Unit unit11 = Unit.INSTANCE;
                        kSerializerArr = kSerializerArr2;
                        fromChildOrderDetailVO2 = fromChildOrderDetailVO4;
                        fromChildOrderDetailVO4 = fromChildOrderDetailVO2;
                        kSerializerArr2 = kSerializerArr;
                        i10 = 8;
                        i8 = 10;
                        i9 = 9;
                        break;
                    case 33:
                        strDecodeStringElement41 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 33);
                        i11 |= 2;
                        Unit unit92 = Unit.INSTANCE;
                        kSerializerArr = kSerializerArr2;
                        fromChildOrderDetailVO2 = fromChildOrderDetailVO4;
                        fromChildOrderDetailVO4 = fromChildOrderDetailVO2;
                        kSerializerArr2 = kSerializerArr;
                        i10 = 8;
                        i8 = 10;
                        i9 = 9;
                        break;
                    case 34:
                        strDecodeStringElement37 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 34);
                        i11 |= 4;
                        Unit unit922 = Unit.INSTANCE;
                        kSerializerArr = kSerializerArr2;
                        fromChildOrderDetailVO2 = fromChildOrderDetailVO4;
                        fromChildOrderDetailVO4 = fromChildOrderDetailVO2;
                        kSerializerArr2 = kSerializerArr;
                        i10 = 8;
                        i8 = 10;
                        i9 = 9;
                        break;
                    case 35:
                        strDecodeStringElement40 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 35);
                        i11 |= 8;
                        Unit unit9222 = Unit.INSTANCE;
                        kSerializerArr = kSerializerArr2;
                        fromChildOrderDetailVO2 = fromChildOrderDetailVO4;
                        fromChildOrderDetailVO4 = fromChildOrderDetailVO2;
                        kSerializerArr2 = kSerializerArr;
                        i10 = 8;
                        i8 = 10;
                        i9 = 9;
                        break;
                    case 36:
                        strDecodeStringElement39 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 36);
                        i11 |= 16;
                        Unit unit92222 = Unit.INSTANCE;
                        kSerializerArr = kSerializerArr2;
                        fromChildOrderDetailVO2 = fromChildOrderDetailVO4;
                        fromChildOrderDetailVO4 = fromChildOrderDetailVO2;
                        kSerializerArr2 = kSerializerArr;
                        i10 = 8;
                        i8 = 10;
                        i9 = 9;
                        break;
                    case 37:
                        list3 = (List) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 37, kSerializerArr2[37], list3);
                        i11 |= 32;
                        Unit unit922222 = Unit.INSTANCE;
                        kSerializerArr = kSerializerArr2;
                        fromChildOrderDetailVO2 = fromChildOrderDetailVO4;
                        fromChildOrderDetailVO4 = fromChildOrderDetailVO2;
                        kSerializerArr2 = kSerializerArr;
                        i10 = 8;
                        i8 = 10;
                        i9 = 9;
                        break;
                    case 38:
                        num9 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 38, IntSerializer.INSTANCE, num9);
                        i11 |= 64;
                        Unit unit102222222 = Unit.INSTANCE;
                        kSerializerArr = kSerializerArr2;
                        fromChildOrderDetailVO2 = fromChildOrderDetailVO4;
                        fromChildOrderDetailVO4 = fromChildOrderDetailVO2;
                        kSerializerArr2 = kSerializerArr;
                        i10 = 8;
                        i8 = 10;
                        i9 = 9;
                        break;
                    case 39:
                        num11 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 39, IntSerializer.INSTANCE, num11);
                        i11 |= 128;
                        Unit unit1022222222 = Unit.INSTANCE;
                        kSerializerArr = kSerializerArr2;
                        fromChildOrderDetailVO2 = fromChildOrderDetailVO4;
                        fromChildOrderDetailVO4 = fromChildOrderDetailVO2;
                        kSerializerArr2 = kSerializerArr;
                        i10 = 8;
                        i8 = 10;
                        i9 = 9;
                        break;
                    case 40:
                        strDecodeStringElement38 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 40);
                        i11 |= 256;
                        Unit unit9222222 = Unit.INSTANCE;
                        kSerializerArr = kSerializerArr2;
                        fromChildOrderDetailVO2 = fromChildOrderDetailVO4;
                        fromChildOrderDetailVO4 = fromChildOrderDetailVO2;
                        kSerializerArr2 = kSerializerArr;
                        i10 = 8;
                        i8 = 10;
                        i9 = 9;
                        break;
                    default:
                        throw new UnknownFieldException(iDecodeElementIndex);
                }
            }
            i = i11;
            fromChildOrderDetailVO = fromChildOrderDetailVO4;
            defiPlatformInfos = defiPlatformInfos3;
            str = strDecodeStringElement34;
            str2 = strDecodeStringElement35;
            str3 = strDecodeStringElement36;
            str4 = strDecodeStringElement37;
            str5 = strDecodeStringElement44;
            str6 = strDecodeStringElement45;
            str7 = strDecodeStringElement48;
            str8 = strDecodeStringElement49;
            str9 = strDecodeStringElement50;
            str10 = strDecodeStringElement51;
            str11 = strDecodeStringElement55;
            str12 = strDecodeStringElement56;
            str13 = strDecodeStringElement57;
            str14 = strDecodeStringElement58;
            str15 = strDecodeStringElement59;
            str16 = str29;
            list = list3;
            num = num8;
            num2 = num10;
            str17 = strDecodeStringElement32;
            str18 = strDecodeStringElement39;
            str19 = strDecodeStringElement40;
            str20 = strDecodeStringElement41;
            str21 = strDecodeStringElement52;
            num3 = num9;
            i2 = iDecodeIntElement4;
            i3 = i12;
            z = zDecodeBooleanElement3;
            z2 = zDecodeBooleanElement4;
            str22 = strDecodeStringElement53;
            str23 = strDecodeStringElement54;
            num4 = num11;
            strDecodeStringElement2 = strDecodeStringElement38;
            str24 = strDecodeStringElement33;
            str25 = strDecodeStringElement47;
            str26 = strDecodeStringElement42;
            i4 = iDecodeIntElement3;
            String str30 = strDecodeStringElement46;
            str27 = strDecodeStringElement43;
            str28 = str30;
        }
        compositeDecoderBeginStructure.endStructure(serialDescriptor);
        return new LimitState(i3, i, str16, str15, str14, str13, defiPlatformInfos, fromChildOrderDetailVO, str12, str11, str23, str22, str7, str21, str25, str10, str9, str8, str17, str24, str, str2, str3, z2, z, i2, i4, str28, str6, str5, strDecodeStringElement, num2, num, str27, str26, str20, str4, str19, str18, list, num3, num4, strDecodeStringElement2, (SerializationConstructorMarker) null);
    }

    /* JADX DEBUG: Method merged with bridge method: serialize(Lkotlinx/serialization/encoding/Encoder;Ljava/lang/Object;)V */
    @Override // kotlinx.serialization.SerializationStrategy
    public final void serialize(@NotNull Encoder encoder, @NotNull LimitState limitState) {
        Intrinsics.checkNotNullParameter(encoder, "");
        Intrinsics.checkNotNullParameter(limitState, "");
        SerialDescriptor serialDescriptor = descriptor;
        CompositeEncoder compositeEncoderBeginStructure = encoder.beginStructure(serialDescriptor);
        LimitState.write$Self$OKDex_dex_impl(limitState, compositeEncoderBeginStructure, serialDescriptor);
        compositeEncoderBeginStructure.endStructure(serialDescriptor);
    }
}
