package com.okinc.okimcore.model.remote;

import com.google.api.client.googleapis.media.MediaHttpDownloader;
import com.okinc.okimcore.model.im.group.GroupPublicType;
import com.okinc.okimcore.model.im.group.paidgroup.PaidGroupInfo;
import com.okinc.okimcore.model.im.group.paidgroup.PaidGroupInfo$$serializer;
import com.okinc.okimcore.model.im.group.voicecall.GroupVoiceCallConfig;
import com.okinc.okimcore.model.im.group.voicecall.GroupVoiceCallConfig$$serializer;
import java.util.List;
import kotlin.Unit;
import kotlin.jvm.internal.Intrinsics;
import kotlinx.serialization.KSerializer;
import kotlinx.serialization.UnknownFieldException;
import kotlinx.serialization.builtins.BuiltinSerializersKt;
import kotlinx.serialization.descriptors.SerialDescriptor;
import kotlinx.serialization.encoding.CompositeDecoder;
import kotlinx.serialization.encoding.CompositeEncoder;
import kotlinx.serialization.encoding.Decoder;
import kotlinx.serialization.encoding.Encoder;
import kotlinx.serialization.internal.BooleanSerializer;
import kotlinx.serialization.internal.GeneratedSerializer;
import kotlinx.serialization.internal.IntSerializer;
import kotlinx.serialization.internal.LongSerializer;
import kotlinx.serialization.internal.PluginGeneratedSerialDescriptor;
import kotlinx.serialization.internal.SerializationConstructorMarker;
import kotlinx.serialization.internal.StringSerializer;
import org.jetbrains.annotations.NotNull;

/* JADX INFO: loaded from: classes16.dex */
public final /* synthetic */ class InHouseIMGroupInfo$$serializer implements GeneratedSerializer<InHouseIMGroupInfo> {
    public static final int $stable;
    public static final InHouseIMGroupInfo$$serializer INSTANCE;
    private static final SerialDescriptor descriptor;

    /* JADX DEBUG: Don't trust debug lines info. Lines numbers was adjusted: min line is 0 */
    private InHouseIMGroupInfo$$serializer() {
    }

    /* JADX DEBUG: Don't trust debug lines info. Lines numbers was adjusted: min line is 0 */
    @Override // kotlinx.serialization.KSerializer, kotlinx.serialization.SerializationStrategy, kotlinx.serialization.DeserializationStrategy
    public final SerialDescriptor getDescriptor() {
        return descriptor;
    }

    static {
        InHouseIMGroupInfo$$serializer inHouseIMGroupInfo$$serializer = new InHouseIMGroupInfo$$serializer();
        INSTANCE = inHouseIMGroupInfo$$serializer;
        $stable = 8;
        PluginGeneratedSerialDescriptor pluginGeneratedSerialDescriptor = new PluginGeneratedSerialDescriptor("com.okinc.okimcore.model.remote.InHouseIMGroupInfo", inHouseIMGroupInfo$$serializer, 33);
        pluginGeneratedSerialDescriptor.addElement("groupId", true);
        pluginGeneratedSerialDescriptor.addElement("groupName", true);
        pluginGeneratedSerialDescriptor.addElement("bizGroupName", true);
        pluginGeneratedSerialDescriptor.addElement("groupAvatar", true);
        pluginGeneratedSerialDescriptor.addElement("groupDescription", true);
        pluginGeneratedSerialDescriptor.addElement("publicType", true);
        pluginGeneratedSerialDescriptor.addElement("allowSendLink", true);
        pluginGeneratedSerialDescriptor.addElement("allowPrivateChat", true);
        pluginGeneratedSerialDescriptor.addElement("allowMentionRobot", true);
        pluginGeneratedSerialDescriptor.addElement("allowMentionOthers", true);
        pluginGeneratedSerialDescriptor.addElement("allowViewHistory", true);
        pluginGeneratedSerialDescriptor.addElement("allowMembersSendMessage", false);
        pluginGeneratedSerialDescriptor.addElement("status", true);
        pluginGeneratedSerialDescriptor.addElement("ownerUid", true);
        pluginGeneratedSerialDescriptor.addElement("type", true);
        pluginGeneratedSerialDescriptor.addElement("groupOfficialInfo", true);
        pluginGeneratedSerialDescriptor.addElement("isOfficialGroup", true);
        pluginGeneratedSerialDescriptor.addElement("members", true);
        pluginGeneratedSerialDescriptor.addElement("currentUser", true);
        pluginGeneratedSerialDescriptor.addElement("latestGroupAnnouncement", true);
        pluginGeneratedSerialDescriptor.addElement("memberCount", true);
        pluginGeneratedSerialDescriptor.addElement("isCanTransferOwnership", true);
        pluginGeneratedSerialDescriptor.addElement("userGroupPermission", true);
        pluginGeneratedSerialDescriptor.addElement("groupVoiceCallConfig", true);
        pluginGeneratedSerialDescriptor.addElement("maxMemberCount", true);
        pluginGeneratedSerialDescriptor.addElement("allowMembersToAddMembers", true);
        pluginGeneratedSerialDescriptor.addElement("allowSharingInvitationQrCode", true);
        pluginGeneratedSerialDescriptor.addElement("requireAdminApprovalToJoin", true);
        pluginGeneratedSerialDescriptor.addElement("pendingJoinRequests", true);
        pluginGeneratedSerialDescriptor.addElement("paidGroupInfo", true);
        pluginGeneratedSerialDescriptor.addElement("groupCampaign", true);
        pluginGeneratedSerialDescriptor.addElement("ctas", true);
        pluginGeneratedSerialDescriptor.addElement("superGroupConfig", true);
        descriptor = pluginGeneratedSerialDescriptor;
    }

    @Override // kotlinx.serialization.internal.GeneratedSerializer
    public final KSerializer<?>[] childSerializers() {
        KSerializer<?>[] kSerializerArr = InHouseIMGroupInfo.$childSerializers;
        StringSerializer stringSerializer = StringSerializer.INSTANCE;
        IntSerializer intSerializer = IntSerializer.INSTANCE;
        return new KSerializer[]{BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(kSerializerArr[5]), BuiltinSerializersKt.getNullable(intSerializer), BuiltinSerializersKt.getNullable(intSerializer), BuiltinSerializersKt.getNullable(intSerializer), BuiltinSerializersKt.getNullable(intSerializer), BuiltinSerializersKt.getNullable(intSerializer), intSerializer, BuiltinSerializersKt.getNullable(intSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(intSerializer), BuiltinSerializersKt.getNullable(InHouseIMGroupOfficialInfo$$serializer.INSTANCE), BuiltinSerializersKt.getNullable(BooleanSerializer.INSTANCE), kSerializerArr[17], BuiltinSerializersKt.getNullable(InHouseIMGroupMemberInfo$$serializer.INSTANCE), BuiltinSerializersKt.getNullable(InHouseIMGroupAnnouncementInfo$$serializer.INSTANCE), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(intSerializer), BuiltinSerializersKt.getNullable(InHouseIMGroupPermissionInfo$$serializer.INSTANCE), BuiltinSerializersKt.getNullable(GroupVoiceCallConfig$$serializer.INSTANCE), BuiltinSerializersKt.getNullable(LongSerializer.INSTANCE), BuiltinSerializersKt.getNullable(intSerializer), BuiltinSerializersKt.getNullable(intSerializer), BuiltinSerializersKt.getNullable(intSerializer), BuiltinSerializersKt.getNullable(intSerializer), BuiltinSerializersKt.getNullable(PaidGroupInfo$$serializer.INSTANCE), BuiltinSerializersKt.getNullable(InHouseIMGroupCampaign$$serializer.INSTANCE), BuiltinSerializersKt.getNullable(kSerializerArr[31]), BuiltinSerializersKt.getNullable(InHouseIMSuperGroupConfig$$serializer.INSTANCE)};
    }

    /* JADX DEBUG: Method merged with bridge method: deserialize(Lkotlinx/serialization/encoding/Decoder;)Ljava/lang/Object; */
    @Override // kotlinx.serialization.DeserializationStrategy
    public final InHouseIMGroupInfo deserialize(@NotNull Decoder decoder) {
        int i;
        Integer num;
        Integer num2;
        Integer num3;
        InHouseIMGroupMemberInfo inHouseIMGroupMemberInfo;
        Integer num4;
        String str;
        Integer num5;
        Long l;
        GroupVoiceCallConfig groupVoiceCallConfig;
        InHouseIMGroupPermissionInfo inHouseIMGroupPermissionInfo;
        String str2;
        List list;
        String str3;
        Integer num6;
        PaidGroupInfo paidGroupInfo;
        InHouseIMGroupCampaign inHouseIMGroupCampaign;
        InHouseIMGroupAnnouncementInfo inHouseIMGroupAnnouncementInfo;
        GroupPublicType groupPublicType;
        int i2;
        String str4;
        Integer num7;
        List list2;
        String str5;
        Integer num8;
        Boolean bool;
        InHouseIMGroupOfficialInfo inHouseIMGroupOfficialInfo;
        Integer num9;
        String str6;
        InHouseIMSuperGroupConfig inHouseIMSuperGroupConfig;
        String str7;
        Integer num10;
        int i3;
        Integer num11;
        Integer num12;
        Integer num13;
        List list3;
        Integer num14;
        int i4;
        InHouseIMGroupAnnouncementInfo inHouseIMGroupAnnouncementInfo2;
        InHouseIMGroupMemberInfo inHouseIMGroupMemberInfo2;
        List list4;
        Boolean bool2;
        InHouseIMGroupOfficialInfo inHouseIMGroupOfficialInfo2;
        Integer num15;
        String str8;
        GroupPublicType groupPublicType2;
        Integer num16;
        String str9;
        String str10;
        String str11;
        String str12;
        Integer num17;
        KSerializer[] kSerializerArr;
        InHouseIMGroupPermissionInfo inHouseIMGroupPermissionInfo2;
        Integer num18;
        String str13;
        String str14;
        Integer num19;
        Integer num20;
        String str15;
        Integer num21;
        List list5;
        Integer num22;
        int i5;
        InHouseIMGroupAnnouncementInfo inHouseIMGroupAnnouncementInfo3;
        Integer num23;
        String str16;
        InHouseIMGroupPermissionInfo inHouseIMGroupPermissionInfo3;
        Integer num24;
        int i6;
        String str17;
        Integer num25;
        int i7;
        List list6;
        InHouseIMGroupAnnouncementInfo inHouseIMGroupAnnouncementInfo4;
        Integer num26;
        int i8;
        InHouseIMGroupPermissionInfo inHouseIMGroupPermissionInfo4;
        int i9;
        InHouseIMGroupPermissionInfo inHouseIMGroupPermissionInfo5;
        String str18;
        int iDecodeIntElement;
        int i10;
        int i11;
        int i12;
        List list7;
        int i13;
        int i14;
        int i15;
        Intrinsics.checkNotNullParameter(decoder, "");
        SerialDescriptor serialDescriptor = descriptor;
        CompositeDecoder compositeDecoderBeginStructure = decoder.beginStructure(serialDescriptor);
        KSerializer[] kSerializerArr2 = InHouseIMGroupInfo.$childSerializers;
        if (compositeDecoderBeginStructure.decodeSequentially()) {
            StringSerializer stringSerializer = StringSerializer.INSTANCE;
            String str19 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 0, stringSerializer, null);
            String str20 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 1, stringSerializer, null);
            String str21 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 2, stringSerializer, null);
            str2 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 3, stringSerializer, null);
            str3 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 4, stringSerializer, null);
            GroupPublicType groupPublicType3 = (GroupPublicType) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 5, kSerializerArr2[5], null);
            IntSerializer intSerializer = IntSerializer.INSTANCE;
            Integer num27 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 6, intSerializer, null);
            Integer num28 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 7, intSerializer, null);
            Integer num29 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 8, intSerializer, null);
            Integer num30 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 9, intSerializer, null);
            Integer num31 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 10, intSerializer, null);
            int iDecodeIntElement2 = compositeDecoderBeginStructure.decodeIntElement(serialDescriptor, 11);
            num2 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 12, intSerializer, null);
            String str22 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 13, stringSerializer, null);
            Integer num32 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 14, intSerializer, null);
            InHouseIMGroupOfficialInfo inHouseIMGroupOfficialInfo3 = (InHouseIMGroupOfficialInfo) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 15, InHouseIMGroupOfficialInfo$$serializer.INSTANCE, null);
            Boolean bool3 = (Boolean) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 16, BooleanSerializer.INSTANCE, null);
            List list8 = (List) compositeDecoderBeginStructure.decodeSerializableElement(serialDescriptor, 17, kSerializerArr2[17], null);
            InHouseIMGroupMemberInfo inHouseIMGroupMemberInfo3 = (InHouseIMGroupMemberInfo) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 18, InHouseIMGroupMemberInfo$$serializer.INSTANCE, null);
            InHouseIMGroupAnnouncementInfo inHouseIMGroupAnnouncementInfo5 = (InHouseIMGroupAnnouncementInfo) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 19, InHouseIMGroupAnnouncementInfo$$serializer.INSTANCE, null);
            String str23 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 20, stringSerializer, null);
            Integer num33 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 21, intSerializer, null);
            inHouseIMGroupAnnouncementInfo = inHouseIMGroupAnnouncementInfo5;
            InHouseIMGroupPermissionInfo inHouseIMGroupPermissionInfo6 = (InHouseIMGroupPermissionInfo) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 22, InHouseIMGroupPermissionInfo$$serializer.INSTANCE, null);
            GroupVoiceCallConfig groupVoiceCallConfig2 = (GroupVoiceCallConfig) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 23, GroupVoiceCallConfig$$serializer.INSTANCE, null);
            Long l2 = (Long) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 24, LongSerializer.INSTANCE, null);
            Integer num34 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 25, intSerializer, null);
            Integer num35 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 26, intSerializer, null);
            Integer num36 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 27, intSerializer, null);
            Integer num37 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 28, intSerializer, null);
            PaidGroupInfo paidGroupInfo2 = (PaidGroupInfo) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 29, PaidGroupInfo$$serializer.INSTANCE, null);
            InHouseIMGroupCampaign inHouseIMGroupCampaign2 = (InHouseIMGroupCampaign) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 30, InHouseIMGroupCampaign$$serializer.INSTANCE, null);
            list = (List) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 31, kSerializerArr2[31], null);
            inHouseIMGroupCampaign = inHouseIMGroupCampaign2;
            inHouseIMSuperGroupConfig = (InHouseIMSuperGroupConfig) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 32, InHouseIMSuperGroupConfig$$serializer.INSTANCE, null);
            i = -1;
            inHouseIMGroupOfficialInfo = inHouseIMGroupOfficialInfo3;
            num12 = num36;
            num11 = num37;
            paidGroupInfo = paidGroupInfo2;
            num7 = num34;
            num6 = num28;
            str7 = str20;
            l = l2;
            num5 = num35;
            num10 = num32;
            num9 = num29;
            inHouseIMGroupPermissionInfo = inHouseIMGroupPermissionInfo6;
            groupVoiceCallConfig = groupVoiceCallConfig2;
            num3 = num33;
            bool = bool3;
            str6 = str23;
            num8 = num27;
            inHouseIMGroupMemberInfo = inHouseIMGroupMemberInfo3;
            str5 = str21;
            groupPublicType = groupPublicType3;
            list2 = list8;
            num = num31;
            i2 = 1;
            num4 = num30;
            str4 = str19;
            str = str22;
            i3 = iDecodeIntElement2;
        } else {
            int i16 = 0;
            int i17 = 0;
            List list9 = null;
            Integer num38 = null;
            InHouseIMGroupPermissionInfo inHouseIMGroupPermissionInfo7 = null;
            PaidGroupInfo paidGroupInfo3 = null;
            InHouseIMGroupCampaign inHouseIMGroupCampaign3 = null;
            InHouseIMSuperGroupConfig inHouseIMSuperGroupConfig2 = null;
            Integer num39 = null;
            Integer num40 = null;
            Integer num41 = null;
            Integer num42 = null;
            Integer num43 = null;
            Integer num44 = null;
            Long l3 = null;
            GroupVoiceCallConfig groupVoiceCallConfig3 = null;
            String str24 = null;
            InHouseIMGroupAnnouncementInfo inHouseIMGroupAnnouncementInfo6 = null;
            InHouseIMGroupMemberInfo inHouseIMGroupMemberInfo4 = null;
            List list10 = null;
            Boolean bool4 = null;
            InHouseIMGroupOfficialInfo inHouseIMGroupOfficialInfo4 = null;
            Integer num45 = null;
            String str25 = null;
            Integer num46 = null;
            GroupPublicType groupPublicType4 = null;
            Integer num47 = null;
            String str26 = null;
            String str27 = null;
            String str28 = null;
            String str29 = null;
            Integer num48 = null;
            String str30 = null;
            boolean z = true;
            Integer num49 = null;
            i = 0;
            while (z) {
                int iDecodeElementIndex = compositeDecoderBeginStructure.decodeElementIndex(serialDescriptor);
                switch (iDecodeElementIndex) {
                    case -1:
                        num13 = num49;
                        list3 = list9;
                        num14 = num38;
                        i4 = i16;
                        inHouseIMGroupAnnouncementInfo2 = inHouseIMGroupAnnouncementInfo6;
                        inHouseIMGroupMemberInfo2 = inHouseIMGroupMemberInfo4;
                        list4 = list10;
                        bool2 = bool4;
                        inHouseIMGroupOfficialInfo2 = inHouseIMGroupOfficialInfo4;
                        num15 = num45;
                        str8 = str25;
                        groupPublicType2 = groupPublicType4;
                        num16 = num47;
                        str9 = str26;
                        str10 = str27;
                        str11 = str28;
                        str12 = str29;
                        num17 = num48;
                        kSerializerArr = kSerializerArr2;
                        inHouseIMGroupPermissionInfo2 = inHouseIMGroupPermissionInfo7;
                        num18 = num46;
                        Unit unit = Unit.INSTANCE;
                        z = false;
                        num48 = num17;
                        num38 = num14;
                        num49 = num13;
                        str13 = str12;
                        str14 = str11;
                        list9 = list3;
                        num19 = num16;
                        i16 = i4;
                        InHouseIMGroupAnnouncementInfo inHouseIMGroupAnnouncementInfo7 = inHouseIMGroupAnnouncementInfo2;
                        num20 = num18;
                        inHouseIMGroupPermissionInfo7 = inHouseIMGroupPermissionInfo2;
                        inHouseIMGroupAnnouncementInfo6 = inHouseIMGroupAnnouncementInfo7;
                        String str31 = str10;
                        str26 = str9;
                        str15 = str31;
                        bool4 = bool2;
                        num46 = num20;
                        list10 = list4;
                        inHouseIMGroupMemberInfo4 = inHouseIMGroupMemberInfo2;
                        inHouseIMGroupOfficialInfo4 = inHouseIMGroupOfficialInfo2;
                        num45 = num15;
                        str27 = str15;
                        str28 = str14;
                        groupPublicType4 = groupPublicType2;
                        str29 = str13;
                        str25 = str8;
                        kSerializerArr2 = kSerializerArr;
                        num47 = num19;
                        break;
                    case 0:
                        num13 = num49;
                        list3 = list9;
                        num14 = num38;
                        i4 = i16;
                        inHouseIMGroupAnnouncementInfo2 = inHouseIMGroupAnnouncementInfo6;
                        inHouseIMGroupMemberInfo2 = inHouseIMGroupMemberInfo4;
                        list4 = list10;
                        bool2 = bool4;
                        inHouseIMGroupOfficialInfo2 = inHouseIMGroupOfficialInfo4;
                        num15 = num45;
                        str8 = str25;
                        groupPublicType2 = groupPublicType4;
                        num16 = num47;
                        str9 = str26;
                        str10 = str27;
                        str12 = str29;
                        num17 = num48;
                        kSerializerArr = kSerializerArr2;
                        inHouseIMGroupPermissionInfo2 = inHouseIMGroupPermissionInfo7;
                        num18 = num46;
                        str11 = str28;
                        str30 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 0, StringSerializer.INSTANCE, str30);
                        i |= 1;
                        Unit unit2 = Unit.INSTANCE;
                        num48 = num17;
                        num38 = num14;
                        num49 = num13;
                        str13 = str12;
                        str14 = str11;
                        list9 = list3;
                        num19 = num16;
                        i16 = i4;
                        InHouseIMGroupAnnouncementInfo inHouseIMGroupAnnouncementInfo72 = inHouseIMGroupAnnouncementInfo2;
                        num20 = num18;
                        inHouseIMGroupPermissionInfo7 = inHouseIMGroupPermissionInfo2;
                        inHouseIMGroupAnnouncementInfo6 = inHouseIMGroupAnnouncementInfo72;
                        String str312 = str10;
                        str26 = str9;
                        str15 = str312;
                        bool4 = bool2;
                        num46 = num20;
                        list10 = list4;
                        inHouseIMGroupMemberInfo4 = inHouseIMGroupMemberInfo2;
                        inHouseIMGroupOfficialInfo4 = inHouseIMGroupOfficialInfo2;
                        num45 = num15;
                        str27 = str15;
                        str28 = str14;
                        groupPublicType4 = groupPublicType2;
                        str29 = str13;
                        str25 = str8;
                        kSerializerArr2 = kSerializerArr;
                        num47 = num19;
                        break;
                    case 1:
                        num21 = num49;
                        list5 = list9;
                        num22 = num38;
                        i5 = i16;
                        inHouseIMGroupAnnouncementInfo3 = inHouseIMGroupAnnouncementInfo6;
                        inHouseIMGroupMemberInfo2 = inHouseIMGroupMemberInfo4;
                        list4 = list10;
                        bool2 = bool4;
                        inHouseIMGroupOfficialInfo2 = inHouseIMGroupOfficialInfo4;
                        num15 = num45;
                        str8 = str25;
                        groupPublicType2 = groupPublicType4;
                        num23 = num47;
                        str16 = str29;
                        kSerializerArr = kSerializerArr2;
                        inHouseIMGroupPermissionInfo3 = inHouseIMGroupPermissionInfo7;
                        num24 = num46;
                        str28 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 1, StringSerializer.INSTANCE, str28);
                        i6 = i | 2;
                        Unit unit3 = Unit.INSTANCE;
                        str17 = str27;
                        str26 = str26;
                        i = i6;
                        str15 = str17;
                        num19 = num23;
                        num38 = num22;
                        num49 = num21;
                        str14 = str28;
                        i16 = i5;
                        str13 = str16;
                        list9 = list5;
                        InHouseIMGroupAnnouncementInfo inHouseIMGroupAnnouncementInfo8 = inHouseIMGroupAnnouncementInfo3;
                        num20 = num24;
                        inHouseIMGroupPermissionInfo7 = inHouseIMGroupPermissionInfo3;
                        inHouseIMGroupAnnouncementInfo6 = inHouseIMGroupAnnouncementInfo8;
                        bool4 = bool2;
                        num46 = num20;
                        list10 = list4;
                        inHouseIMGroupMemberInfo4 = inHouseIMGroupMemberInfo2;
                        inHouseIMGroupOfficialInfo4 = inHouseIMGroupOfficialInfo2;
                        num45 = num15;
                        str27 = str15;
                        str28 = str14;
                        groupPublicType4 = groupPublicType2;
                        str29 = str13;
                        str25 = str8;
                        kSerializerArr2 = kSerializerArr;
                        num47 = num19;
                        break;
                    case 2:
                        num21 = num49;
                        list5 = list9;
                        num22 = num38;
                        i5 = i16;
                        inHouseIMGroupAnnouncementInfo3 = inHouseIMGroupAnnouncementInfo6;
                        inHouseIMGroupMemberInfo2 = inHouseIMGroupMemberInfo4;
                        list4 = list10;
                        bool2 = bool4;
                        inHouseIMGroupOfficialInfo2 = inHouseIMGroupOfficialInfo4;
                        num15 = num45;
                        str8 = str25;
                        groupPublicType2 = groupPublicType4;
                        num23 = num47;
                        str16 = str29;
                        num25 = num48;
                        kSerializerArr = kSerializerArr2;
                        inHouseIMGroupPermissionInfo3 = inHouseIMGroupPermissionInfo7;
                        num24 = num46;
                        String str32 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 2, StringSerializer.INSTANCE, str26);
                        int i18 = i | 4;
                        Unit unit4 = Unit.INSTANCE;
                        str26 = str32;
                        i7 = i18;
                        str17 = str27;
                        i6 = i7;
                        num48 = num25;
                        i = i6;
                        str15 = str17;
                        num19 = num23;
                        num38 = num22;
                        num49 = num21;
                        str14 = str28;
                        i16 = i5;
                        str13 = str16;
                        list9 = list5;
                        InHouseIMGroupAnnouncementInfo inHouseIMGroupAnnouncementInfo82 = inHouseIMGroupAnnouncementInfo3;
                        num20 = num24;
                        inHouseIMGroupPermissionInfo7 = inHouseIMGroupPermissionInfo3;
                        inHouseIMGroupAnnouncementInfo6 = inHouseIMGroupAnnouncementInfo82;
                        bool4 = bool2;
                        num46 = num20;
                        list10 = list4;
                        inHouseIMGroupMemberInfo4 = inHouseIMGroupMemberInfo2;
                        inHouseIMGroupOfficialInfo4 = inHouseIMGroupOfficialInfo2;
                        num45 = num15;
                        str27 = str15;
                        str28 = str14;
                        groupPublicType4 = groupPublicType2;
                        str29 = str13;
                        str25 = str8;
                        kSerializerArr2 = kSerializerArr;
                        num47 = num19;
                        break;
                    case 3:
                        num21 = num49;
                        list5 = list9;
                        num22 = num38;
                        i5 = i16;
                        inHouseIMGroupAnnouncementInfo3 = inHouseIMGroupAnnouncementInfo6;
                        inHouseIMGroupMemberInfo2 = inHouseIMGroupMemberInfo4;
                        list4 = list10;
                        bool2 = bool4;
                        inHouseIMGroupOfficialInfo2 = inHouseIMGroupOfficialInfo4;
                        num15 = num45;
                        str8 = str25;
                        groupPublicType2 = groupPublicType4;
                        num23 = num47;
                        str16 = str29;
                        kSerializerArr = kSerializerArr2;
                        inHouseIMGroupPermissionInfo3 = inHouseIMGroupPermissionInfo7;
                        num24 = num46;
                        num25 = num48;
                        String str33 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 3, StringSerializer.INSTANCE, str27);
                        Unit unit5 = Unit.INSTANCE;
                        i7 = i | 8;
                        str17 = str33;
                        i6 = i7;
                        num48 = num25;
                        i = i6;
                        str15 = str17;
                        num19 = num23;
                        num38 = num22;
                        num49 = num21;
                        str14 = str28;
                        i16 = i5;
                        str13 = str16;
                        list9 = list5;
                        InHouseIMGroupAnnouncementInfo inHouseIMGroupAnnouncementInfo822 = inHouseIMGroupAnnouncementInfo3;
                        num20 = num24;
                        inHouseIMGroupPermissionInfo7 = inHouseIMGroupPermissionInfo3;
                        inHouseIMGroupAnnouncementInfo6 = inHouseIMGroupAnnouncementInfo822;
                        bool4 = bool2;
                        num46 = num20;
                        list10 = list4;
                        inHouseIMGroupMemberInfo4 = inHouseIMGroupMemberInfo2;
                        inHouseIMGroupOfficialInfo4 = inHouseIMGroupOfficialInfo2;
                        num45 = num15;
                        str27 = str15;
                        str28 = str14;
                        groupPublicType4 = groupPublicType2;
                        str29 = str13;
                        str25 = str8;
                        kSerializerArr2 = kSerializerArr;
                        num47 = num19;
                        break;
                    case 4:
                        num21 = num49;
                        list5 = list9;
                        num22 = num38;
                        i5 = i16;
                        inHouseIMGroupAnnouncementInfo3 = inHouseIMGroupAnnouncementInfo6;
                        inHouseIMGroupMemberInfo2 = inHouseIMGroupMemberInfo4;
                        list4 = list10;
                        bool2 = bool4;
                        inHouseIMGroupOfficialInfo2 = inHouseIMGroupOfficialInfo4;
                        num15 = num45;
                        str8 = str25;
                        num23 = num47;
                        kSerializerArr = kSerializerArr2;
                        inHouseIMGroupPermissionInfo3 = inHouseIMGroupPermissionInfo7;
                        num24 = num46;
                        groupPublicType2 = groupPublicType4;
                        str29 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 4, StringSerializer.INSTANCE, str29);
                        Unit unit6 = Unit.INSTANCE;
                        i6 = i | 16;
                        str17 = str27;
                        str16 = str29;
                        i = i6;
                        str15 = str17;
                        num19 = num23;
                        num38 = num22;
                        num49 = num21;
                        str14 = str28;
                        i16 = i5;
                        str13 = str16;
                        list9 = list5;
                        InHouseIMGroupAnnouncementInfo inHouseIMGroupAnnouncementInfo8222 = inHouseIMGroupAnnouncementInfo3;
                        num20 = num24;
                        inHouseIMGroupPermissionInfo7 = inHouseIMGroupPermissionInfo3;
                        inHouseIMGroupAnnouncementInfo6 = inHouseIMGroupAnnouncementInfo8222;
                        bool4 = bool2;
                        num46 = num20;
                        list10 = list4;
                        inHouseIMGroupMemberInfo4 = inHouseIMGroupMemberInfo2;
                        inHouseIMGroupOfficialInfo4 = inHouseIMGroupOfficialInfo2;
                        num45 = num15;
                        str27 = str15;
                        str28 = str14;
                        groupPublicType4 = groupPublicType2;
                        str29 = str13;
                        str25 = str8;
                        kSerializerArr2 = kSerializerArr;
                        num47 = num19;
                        break;
                    case 5:
                        num21 = num49;
                        list5 = list9;
                        num22 = num38;
                        i5 = i16;
                        inHouseIMGroupAnnouncementInfo3 = inHouseIMGroupAnnouncementInfo6;
                        inHouseIMGroupMemberInfo2 = inHouseIMGroupMemberInfo4;
                        list4 = list10;
                        bool2 = bool4;
                        inHouseIMGroupOfficialInfo2 = inHouseIMGroupOfficialInfo4;
                        num15 = num45;
                        str8 = str25;
                        num23 = num47;
                        inHouseIMGroupPermissionInfo3 = inHouseIMGroupPermissionInfo7;
                        num24 = num46;
                        kSerializerArr = kSerializerArr2;
                        groupPublicType4 = (GroupPublicType) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 5, kSerializerArr2[5], groupPublicType4);
                        i6 = i | 32;
                        Unit unit7 = Unit.INSTANCE;
                        groupPublicType2 = groupPublicType4;
                        str17 = str27;
                        str16 = str29;
                        i = i6;
                        str15 = str17;
                        num19 = num23;
                        num38 = num22;
                        num49 = num21;
                        str14 = str28;
                        i16 = i5;
                        str13 = str16;
                        list9 = list5;
                        InHouseIMGroupAnnouncementInfo inHouseIMGroupAnnouncementInfo82222 = inHouseIMGroupAnnouncementInfo3;
                        num20 = num24;
                        inHouseIMGroupPermissionInfo7 = inHouseIMGroupPermissionInfo3;
                        inHouseIMGroupAnnouncementInfo6 = inHouseIMGroupAnnouncementInfo82222;
                        bool4 = bool2;
                        num46 = num20;
                        list10 = list4;
                        inHouseIMGroupMemberInfo4 = inHouseIMGroupMemberInfo2;
                        inHouseIMGroupOfficialInfo4 = inHouseIMGroupOfficialInfo2;
                        num45 = num15;
                        str27 = str15;
                        str28 = str14;
                        groupPublicType4 = groupPublicType2;
                        str29 = str13;
                        str25 = str8;
                        kSerializerArr2 = kSerializerArr;
                        num47 = num19;
                        break;
                    case 6:
                        num21 = num49;
                        list5 = list9;
                        i5 = i16;
                        inHouseIMGroupAnnouncementInfo3 = inHouseIMGroupAnnouncementInfo6;
                        inHouseIMGroupMemberInfo2 = inHouseIMGroupMemberInfo4;
                        list4 = list10;
                        bool2 = bool4;
                        inHouseIMGroupOfficialInfo2 = inHouseIMGroupOfficialInfo4;
                        num15 = num45;
                        str8 = str25;
                        num23 = num47;
                        inHouseIMGroupPermissionInfo3 = inHouseIMGroupPermissionInfo7;
                        num24 = num46;
                        num22 = num38;
                        num48 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 6, IntSerializer.INSTANCE, num48);
                        Unit unit8 = Unit.INSTANCE;
                        kSerializerArr = kSerializerArr2;
                        i6 = i | 64;
                        groupPublicType2 = groupPublicType4;
                        str17 = str27;
                        str16 = str29;
                        i = i6;
                        str15 = str17;
                        num19 = num23;
                        num38 = num22;
                        num49 = num21;
                        str14 = str28;
                        i16 = i5;
                        str13 = str16;
                        list9 = list5;
                        InHouseIMGroupAnnouncementInfo inHouseIMGroupAnnouncementInfo822222 = inHouseIMGroupAnnouncementInfo3;
                        num20 = num24;
                        inHouseIMGroupPermissionInfo7 = inHouseIMGroupPermissionInfo3;
                        inHouseIMGroupAnnouncementInfo6 = inHouseIMGroupAnnouncementInfo822222;
                        bool4 = bool2;
                        num46 = num20;
                        list10 = list4;
                        inHouseIMGroupMemberInfo4 = inHouseIMGroupMemberInfo2;
                        inHouseIMGroupOfficialInfo4 = inHouseIMGroupOfficialInfo2;
                        num45 = num15;
                        str27 = str15;
                        str28 = str14;
                        groupPublicType4 = groupPublicType2;
                        str29 = str13;
                        str25 = str8;
                        kSerializerArr2 = kSerializerArr;
                        num47 = num19;
                        break;
                    case 7:
                        list6 = list9;
                        inHouseIMGroupAnnouncementInfo4 = inHouseIMGroupAnnouncementInfo6;
                        inHouseIMGroupMemberInfo2 = inHouseIMGroupMemberInfo4;
                        list4 = list10;
                        bool2 = bool4;
                        inHouseIMGroupOfficialInfo2 = inHouseIMGroupOfficialInfo4;
                        num15 = num45;
                        str8 = str25;
                        InHouseIMGroupPermissionInfo inHouseIMGroupPermissionInfo8 = inHouseIMGroupPermissionInfo7;
                        num26 = num49;
                        num46 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 7, IntSerializer.INSTANCE, num46);
                        Unit unit9 = Unit.INSTANCE;
                        i |= 128;
                        inHouseIMGroupPermissionInfo7 = inHouseIMGroupPermissionInfo8;
                        i16 = i16;
                        inHouseIMGroupAnnouncementInfo6 = inHouseIMGroupAnnouncementInfo4;
                        list9 = list6;
                        num49 = num26;
                        num20 = num46;
                        groupPublicType2 = groupPublicType4;
                        num19 = num47;
                        str15 = str27;
                        str14 = str28;
                        str13 = str29;
                        kSerializerArr = kSerializerArr2;
                        bool4 = bool2;
                        num46 = num20;
                        list10 = list4;
                        inHouseIMGroupMemberInfo4 = inHouseIMGroupMemberInfo2;
                        inHouseIMGroupOfficialInfo4 = inHouseIMGroupOfficialInfo2;
                        num45 = num15;
                        str27 = str15;
                        str28 = str14;
                        groupPublicType4 = groupPublicType2;
                        str29 = str13;
                        str25 = str8;
                        kSerializerArr2 = kSerializerArr;
                        num47 = num19;
                        break;
                    case 8:
                        list6 = list9;
                        i8 = i16;
                        inHouseIMGroupAnnouncementInfo4 = inHouseIMGroupAnnouncementInfo6;
                        inHouseIMGroupMemberInfo2 = inHouseIMGroupMemberInfo4;
                        list4 = list10;
                        bool2 = bool4;
                        inHouseIMGroupOfficialInfo2 = inHouseIMGroupOfficialInfo4;
                        num15 = num45;
                        str8 = str25;
                        inHouseIMGroupPermissionInfo4 = inHouseIMGroupPermissionInfo7;
                        num49 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 8, IntSerializer.INSTANCE, num49);
                        i9 = i | 256;
                        Unit unit10 = Unit.INSTANCE;
                        num26 = num49;
                        i = i9;
                        inHouseIMGroupPermissionInfo7 = inHouseIMGroupPermissionInfo4;
                        i16 = i8;
                        inHouseIMGroupAnnouncementInfo6 = inHouseIMGroupAnnouncementInfo4;
                        list9 = list6;
                        num49 = num26;
                        num20 = num46;
                        groupPublicType2 = groupPublicType4;
                        num19 = num47;
                        str15 = str27;
                        str14 = str28;
                        str13 = str29;
                        kSerializerArr = kSerializerArr2;
                        bool4 = bool2;
                        num46 = num20;
                        list10 = list4;
                        inHouseIMGroupMemberInfo4 = inHouseIMGroupMemberInfo2;
                        inHouseIMGroupOfficialInfo4 = inHouseIMGroupOfficialInfo2;
                        num45 = num15;
                        str27 = str15;
                        str28 = str14;
                        groupPublicType4 = groupPublicType2;
                        str29 = str13;
                        str25 = str8;
                        kSerializerArr2 = kSerializerArr;
                        num47 = num19;
                        break;
                    case 9:
                        list6 = list9;
                        i8 = i16;
                        inHouseIMGroupAnnouncementInfo4 = inHouseIMGroupAnnouncementInfo6;
                        inHouseIMGroupMemberInfo2 = inHouseIMGroupMemberInfo4;
                        list4 = list10;
                        bool2 = bool4;
                        inHouseIMGroupOfficialInfo2 = inHouseIMGroupOfficialInfo4;
                        num15 = num45;
                        str8 = str25;
                        inHouseIMGroupPermissionInfo4 = inHouseIMGroupPermissionInfo7;
                        num38 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 9, IntSerializer.INSTANCE, num38);
                        i9 = i | 512;
                        Unit unit102 = Unit.INSTANCE;
                        num26 = num49;
                        i = i9;
                        inHouseIMGroupPermissionInfo7 = inHouseIMGroupPermissionInfo4;
                        i16 = i8;
                        inHouseIMGroupAnnouncementInfo6 = inHouseIMGroupAnnouncementInfo4;
                        list9 = list6;
                        num49 = num26;
                        num20 = num46;
                        groupPublicType2 = groupPublicType4;
                        num19 = num47;
                        str15 = str27;
                        str14 = str28;
                        str13 = str29;
                        kSerializerArr = kSerializerArr2;
                        bool4 = bool2;
                        num46 = num20;
                        list10 = list4;
                        inHouseIMGroupMemberInfo4 = inHouseIMGroupMemberInfo2;
                        inHouseIMGroupOfficialInfo4 = inHouseIMGroupOfficialInfo2;
                        num45 = num15;
                        str27 = str15;
                        str28 = str14;
                        groupPublicType4 = groupPublicType2;
                        str29 = str13;
                        str25 = str8;
                        kSerializerArr2 = kSerializerArr;
                        num47 = num19;
                        break;
                    case 10:
                        list6 = list9;
                        i8 = i16;
                        inHouseIMGroupAnnouncementInfo4 = inHouseIMGroupAnnouncementInfo6;
                        inHouseIMGroupMemberInfo2 = inHouseIMGroupMemberInfo4;
                        list4 = list10;
                        bool2 = bool4;
                        inHouseIMGroupOfficialInfo2 = inHouseIMGroupOfficialInfo4;
                        num15 = num45;
                        inHouseIMGroupPermissionInfo4 = inHouseIMGroupPermissionInfo7;
                        str8 = str25;
                        num47 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 10, IntSerializer.INSTANCE, num47);
                        i9 = i | 1024;
                        Unit unit11 = Unit.INSTANCE;
                        num26 = num49;
                        i = i9;
                        inHouseIMGroupPermissionInfo7 = inHouseIMGroupPermissionInfo4;
                        i16 = i8;
                        inHouseIMGroupAnnouncementInfo6 = inHouseIMGroupAnnouncementInfo4;
                        list9 = list6;
                        num49 = num26;
                        num20 = num46;
                        groupPublicType2 = groupPublicType4;
                        num19 = num47;
                        str15 = str27;
                        str14 = str28;
                        str13 = str29;
                        kSerializerArr = kSerializerArr2;
                        bool4 = bool2;
                        num46 = num20;
                        list10 = list4;
                        inHouseIMGroupMemberInfo4 = inHouseIMGroupMemberInfo2;
                        inHouseIMGroupOfficialInfo4 = inHouseIMGroupOfficialInfo2;
                        num45 = num15;
                        str27 = str15;
                        str28 = str14;
                        groupPublicType4 = groupPublicType2;
                        str29 = str13;
                        str25 = str8;
                        kSerializerArr2 = kSerializerArr;
                        num47 = num19;
                        break;
                    case 11:
                        list6 = list9;
                        inHouseIMGroupAnnouncementInfo4 = inHouseIMGroupAnnouncementInfo6;
                        inHouseIMGroupMemberInfo2 = inHouseIMGroupMemberInfo4;
                        list4 = list10;
                        bool2 = bool4;
                        inHouseIMGroupOfficialInfo2 = inHouseIMGroupOfficialInfo4;
                        num15 = num45;
                        inHouseIMGroupPermissionInfo5 = inHouseIMGroupPermissionInfo7;
                        str18 = str25;
                        iDecodeIntElement = compositeDecoderBeginStructure.decodeIntElement(serialDescriptor, 11);
                        i |= 2048;
                        Unit unit12 = Unit.INSTANCE;
                        num26 = num49;
                        str8 = str18;
                        i16 = iDecodeIntElement;
                        inHouseIMGroupPermissionInfo7 = inHouseIMGroupPermissionInfo5;
                        inHouseIMGroupAnnouncementInfo6 = inHouseIMGroupAnnouncementInfo4;
                        list9 = list6;
                        num49 = num26;
                        num20 = num46;
                        groupPublicType2 = groupPublicType4;
                        num19 = num47;
                        str15 = str27;
                        str14 = str28;
                        str13 = str29;
                        kSerializerArr = kSerializerArr2;
                        bool4 = bool2;
                        num46 = num20;
                        list10 = list4;
                        inHouseIMGroupMemberInfo4 = inHouseIMGroupMemberInfo2;
                        inHouseIMGroupOfficialInfo4 = inHouseIMGroupOfficialInfo2;
                        num45 = num15;
                        str27 = str15;
                        str28 = str14;
                        groupPublicType4 = groupPublicType2;
                        str29 = str13;
                        str25 = str8;
                        kSerializerArr2 = kSerializerArr;
                        num47 = num19;
                        break;
                    case 12:
                        list6 = list9;
                        inHouseIMGroupAnnouncementInfo4 = inHouseIMGroupAnnouncementInfo6;
                        inHouseIMGroupMemberInfo2 = inHouseIMGroupMemberInfo4;
                        list4 = list10;
                        bool2 = bool4;
                        inHouseIMGroupOfficialInfo2 = inHouseIMGroupOfficialInfo4;
                        num15 = num45;
                        inHouseIMGroupPermissionInfo5 = inHouseIMGroupPermissionInfo7;
                        str18 = str25;
                        num40 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 12, IntSerializer.INSTANCE, num40);
                        int i19 = i | 4096;
                        Unit unit13 = Unit.INSTANCE;
                        i = i19;
                        iDecodeIntElement = i16;
                        num26 = num49;
                        str8 = str18;
                        i16 = iDecodeIntElement;
                        inHouseIMGroupPermissionInfo7 = inHouseIMGroupPermissionInfo5;
                        inHouseIMGroupAnnouncementInfo6 = inHouseIMGroupAnnouncementInfo4;
                        list9 = list6;
                        num49 = num26;
                        num20 = num46;
                        groupPublicType2 = groupPublicType4;
                        num19 = num47;
                        str15 = str27;
                        str14 = str28;
                        str13 = str29;
                        kSerializerArr = kSerializerArr2;
                        bool4 = bool2;
                        num46 = num20;
                        list10 = list4;
                        inHouseIMGroupMemberInfo4 = inHouseIMGroupMemberInfo2;
                        inHouseIMGroupOfficialInfo4 = inHouseIMGroupOfficialInfo2;
                        num45 = num15;
                        str27 = str15;
                        str28 = str14;
                        groupPublicType4 = groupPublicType2;
                        str29 = str13;
                        str25 = str8;
                        kSerializerArr2 = kSerializerArr;
                        num47 = num19;
                        break;
                    case 13:
                        list6 = list9;
                        i8 = i16;
                        inHouseIMGroupAnnouncementInfo4 = inHouseIMGroupAnnouncementInfo6;
                        inHouseIMGroupMemberInfo2 = inHouseIMGroupMemberInfo4;
                        list4 = list10;
                        bool2 = bool4;
                        inHouseIMGroupOfficialInfo2 = inHouseIMGroupOfficialInfo4;
                        InHouseIMGroupPermissionInfo inHouseIMGroupPermissionInfo9 = inHouseIMGroupPermissionInfo7;
                        num15 = num45;
                        str25 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 13, StringSerializer.INSTANCE, str25);
                        Unit unit14 = Unit.INSTANCE;
                        num26 = num49;
                        i |= 8192;
                        inHouseIMGroupPermissionInfo7 = inHouseIMGroupPermissionInfo9;
                        str8 = str25;
                        i16 = i8;
                        inHouseIMGroupAnnouncementInfo6 = inHouseIMGroupAnnouncementInfo4;
                        list9 = list6;
                        num49 = num26;
                        num20 = num46;
                        groupPublicType2 = groupPublicType4;
                        num19 = num47;
                        str15 = str27;
                        str14 = str28;
                        str13 = str29;
                        kSerializerArr = kSerializerArr2;
                        bool4 = bool2;
                        num46 = num20;
                        list10 = list4;
                        inHouseIMGroupMemberInfo4 = inHouseIMGroupMemberInfo2;
                        inHouseIMGroupOfficialInfo4 = inHouseIMGroupOfficialInfo2;
                        num45 = num15;
                        str27 = str15;
                        str28 = str14;
                        groupPublicType4 = groupPublicType2;
                        str29 = str13;
                        str25 = str8;
                        kSerializerArr2 = kSerializerArr;
                        num47 = num19;
                        break;
                    case 14:
                        list6 = list9;
                        i8 = i16;
                        inHouseIMGroupAnnouncementInfo4 = inHouseIMGroupAnnouncementInfo6;
                        inHouseIMGroupMemberInfo2 = inHouseIMGroupMemberInfo4;
                        list4 = list10;
                        bool2 = bool4;
                        inHouseIMGroupOfficialInfo2 = inHouseIMGroupOfficialInfo4;
                        num45 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 14, IntSerializer.INSTANCE, num45);
                        Unit unit15 = Unit.INSTANCE;
                        num26 = num49;
                        i |= 16384;
                        inHouseIMGroupPermissionInfo7 = inHouseIMGroupPermissionInfo7;
                        num15 = num45;
                        str8 = str25;
                        i16 = i8;
                        inHouseIMGroupAnnouncementInfo6 = inHouseIMGroupAnnouncementInfo4;
                        list9 = list6;
                        num49 = num26;
                        num20 = num46;
                        groupPublicType2 = groupPublicType4;
                        num19 = num47;
                        str15 = str27;
                        str14 = str28;
                        str13 = str29;
                        kSerializerArr = kSerializerArr2;
                        bool4 = bool2;
                        num46 = num20;
                        list10 = list4;
                        inHouseIMGroupMemberInfo4 = inHouseIMGroupMemberInfo2;
                        inHouseIMGroupOfficialInfo4 = inHouseIMGroupOfficialInfo2;
                        num45 = num15;
                        str27 = str15;
                        str28 = str14;
                        groupPublicType4 = groupPublicType2;
                        str29 = str13;
                        str25 = str8;
                        kSerializerArr2 = kSerializerArr;
                        num47 = num19;
                        break;
                    case 15:
                        list6 = list9;
                        i8 = i16;
                        inHouseIMGroupAnnouncementInfo4 = inHouseIMGroupAnnouncementInfo6;
                        list4 = list10;
                        bool2 = bool4;
                        InHouseIMGroupPermissionInfo inHouseIMGroupPermissionInfo10 = inHouseIMGroupPermissionInfo7;
                        inHouseIMGroupMemberInfo2 = inHouseIMGroupMemberInfo4;
                        inHouseIMGroupOfficialInfo4 = (InHouseIMGroupOfficialInfo) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 15, InHouseIMGroupOfficialInfo$$serializer.INSTANCE, inHouseIMGroupOfficialInfo4);
                        Unit unit16 = Unit.INSTANCE;
                        num26 = num49;
                        i = 32768 | i;
                        inHouseIMGroupPermissionInfo7 = inHouseIMGroupPermissionInfo10;
                        inHouseIMGroupOfficialInfo2 = inHouseIMGroupOfficialInfo4;
                        num15 = num45;
                        str8 = str25;
                        i16 = i8;
                        inHouseIMGroupAnnouncementInfo6 = inHouseIMGroupAnnouncementInfo4;
                        list9 = list6;
                        num49 = num26;
                        num20 = num46;
                        groupPublicType2 = groupPublicType4;
                        num19 = num47;
                        str15 = str27;
                        str14 = str28;
                        str13 = str29;
                        kSerializerArr = kSerializerArr2;
                        bool4 = bool2;
                        num46 = num20;
                        list10 = list4;
                        inHouseIMGroupMemberInfo4 = inHouseIMGroupMemberInfo2;
                        inHouseIMGroupOfficialInfo4 = inHouseIMGroupOfficialInfo2;
                        num45 = num15;
                        str27 = str15;
                        str28 = str14;
                        groupPublicType4 = groupPublicType2;
                        str29 = str13;
                        str25 = str8;
                        kSerializerArr2 = kSerializerArr;
                        num47 = num19;
                        break;
                    case 16:
                        list6 = list9;
                        i8 = i16;
                        inHouseIMGroupAnnouncementInfo4 = inHouseIMGroupAnnouncementInfo6;
                        list4 = list10;
                        bool4 = (Boolean) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 16, BooleanSerializer.INSTANCE, bool4);
                        Unit unit17 = Unit.INSTANCE;
                        num26 = num49;
                        i = 65536 | i;
                        inHouseIMGroupMemberInfo2 = inHouseIMGroupMemberInfo4;
                        inHouseIMGroupPermissionInfo7 = inHouseIMGroupPermissionInfo7;
                        bool2 = bool4;
                        inHouseIMGroupOfficialInfo2 = inHouseIMGroupOfficialInfo4;
                        num15 = num45;
                        str8 = str25;
                        i16 = i8;
                        inHouseIMGroupAnnouncementInfo6 = inHouseIMGroupAnnouncementInfo4;
                        list9 = list6;
                        num49 = num26;
                        num20 = num46;
                        groupPublicType2 = groupPublicType4;
                        num19 = num47;
                        str15 = str27;
                        str14 = str28;
                        str13 = str29;
                        kSerializerArr = kSerializerArr2;
                        bool4 = bool2;
                        num46 = num20;
                        list10 = list4;
                        inHouseIMGroupMemberInfo4 = inHouseIMGroupMemberInfo2;
                        inHouseIMGroupOfficialInfo4 = inHouseIMGroupOfficialInfo2;
                        num45 = num15;
                        str27 = str15;
                        str28 = str14;
                        groupPublicType4 = groupPublicType2;
                        str29 = str13;
                        str25 = str8;
                        kSerializerArr2 = kSerializerArr;
                        num47 = num19;
                        break;
                    case 17:
                        list6 = list9;
                        i8 = i16;
                        inHouseIMGroupAnnouncementInfo4 = inHouseIMGroupAnnouncementInfo6;
                        InHouseIMGroupPermissionInfo inHouseIMGroupPermissionInfo11 = inHouseIMGroupPermissionInfo7;
                        List list11 = (List) compositeDecoderBeginStructure.decodeSerializableElement(serialDescriptor, 17, kSerializerArr2[17], list10);
                        Unit unit18 = Unit.INSTANCE;
                        num26 = num49;
                        i = 131072 | i;
                        inHouseIMGroupMemberInfo2 = inHouseIMGroupMemberInfo4;
                        inHouseIMGroupPermissionInfo7 = inHouseIMGroupPermissionInfo11;
                        list4 = list11;
                        bool2 = bool4;
                        inHouseIMGroupOfficialInfo2 = inHouseIMGroupOfficialInfo4;
                        num15 = num45;
                        str8 = str25;
                        i16 = i8;
                        inHouseIMGroupAnnouncementInfo6 = inHouseIMGroupAnnouncementInfo4;
                        list9 = list6;
                        num49 = num26;
                        num20 = num46;
                        groupPublicType2 = groupPublicType4;
                        num19 = num47;
                        str15 = str27;
                        str14 = str28;
                        str13 = str29;
                        kSerializerArr = kSerializerArr2;
                        bool4 = bool2;
                        num46 = num20;
                        list10 = list4;
                        inHouseIMGroupMemberInfo4 = inHouseIMGroupMemberInfo2;
                        inHouseIMGroupOfficialInfo4 = inHouseIMGroupOfficialInfo2;
                        num45 = num15;
                        str27 = str15;
                        str28 = str14;
                        groupPublicType4 = groupPublicType2;
                        str29 = str13;
                        str25 = str8;
                        kSerializerArr2 = kSerializerArr;
                        num47 = num19;
                        break;
                    case 18:
                        list6 = list9;
                        i10 = i16;
                        inHouseIMGroupMemberInfo4 = (InHouseIMGroupMemberInfo) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 18, InHouseIMGroupMemberInfo$$serializer.INSTANCE, inHouseIMGroupMemberInfo4);
                        i11 = 262144 | i;
                        Unit unit19 = Unit.INSTANCE;
                        inHouseIMGroupAnnouncementInfo6 = inHouseIMGroupAnnouncementInfo6;
                        num26 = num49;
                        i = i11;
                        inHouseIMGroupMemberInfo2 = inHouseIMGroupMemberInfo4;
                        list4 = list10;
                        bool2 = bool4;
                        inHouseIMGroupOfficialInfo2 = inHouseIMGroupOfficialInfo4;
                        num15 = num45;
                        str8 = str25;
                        i16 = i10;
                        list9 = list6;
                        num49 = num26;
                        num20 = num46;
                        groupPublicType2 = groupPublicType4;
                        num19 = num47;
                        str15 = str27;
                        str14 = str28;
                        str13 = str29;
                        kSerializerArr = kSerializerArr2;
                        bool4 = bool2;
                        num46 = num20;
                        list10 = list4;
                        inHouseIMGroupMemberInfo4 = inHouseIMGroupMemberInfo2;
                        inHouseIMGroupOfficialInfo4 = inHouseIMGroupOfficialInfo2;
                        num45 = num15;
                        str27 = str15;
                        str28 = str14;
                        groupPublicType4 = groupPublicType2;
                        str29 = str13;
                        str25 = str8;
                        kSerializerArr2 = kSerializerArr;
                        num47 = num19;
                        break;
                    case 19:
                        list6 = list9;
                        i10 = i16;
                        inHouseIMGroupAnnouncementInfo6 = (InHouseIMGroupAnnouncementInfo) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 19, InHouseIMGroupAnnouncementInfo$$serializer.INSTANCE, inHouseIMGroupAnnouncementInfo6);
                        i12 = 524288;
                        i11 = i | i12;
                        Unit unit20 = Unit.INSTANCE;
                        num26 = num49;
                        i = i11;
                        inHouseIMGroupMemberInfo2 = inHouseIMGroupMemberInfo4;
                        list4 = list10;
                        bool2 = bool4;
                        inHouseIMGroupOfficialInfo2 = inHouseIMGroupOfficialInfo4;
                        num15 = num45;
                        str8 = str25;
                        i16 = i10;
                        list9 = list6;
                        num49 = num26;
                        num20 = num46;
                        groupPublicType2 = groupPublicType4;
                        num19 = num47;
                        str15 = str27;
                        str14 = str28;
                        str13 = str29;
                        kSerializerArr = kSerializerArr2;
                        bool4 = bool2;
                        num46 = num20;
                        list10 = list4;
                        inHouseIMGroupMemberInfo4 = inHouseIMGroupMemberInfo2;
                        inHouseIMGroupOfficialInfo4 = inHouseIMGroupOfficialInfo2;
                        num45 = num15;
                        str27 = str15;
                        str28 = str14;
                        groupPublicType4 = groupPublicType2;
                        str29 = str13;
                        str25 = str8;
                        kSerializerArr2 = kSerializerArr;
                        num47 = num19;
                        break;
                    case 20:
                        list6 = list9;
                        i10 = i16;
                        str24 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 20, StringSerializer.INSTANCE, str24);
                        i12 = 1048576;
                        i11 = i | i12;
                        Unit unit202 = Unit.INSTANCE;
                        num26 = num49;
                        i = i11;
                        inHouseIMGroupMemberInfo2 = inHouseIMGroupMemberInfo4;
                        list4 = list10;
                        bool2 = bool4;
                        inHouseIMGroupOfficialInfo2 = inHouseIMGroupOfficialInfo4;
                        num15 = num45;
                        str8 = str25;
                        i16 = i10;
                        list9 = list6;
                        num49 = num26;
                        num20 = num46;
                        groupPublicType2 = groupPublicType4;
                        num19 = num47;
                        str15 = str27;
                        str14 = str28;
                        str13 = str29;
                        kSerializerArr = kSerializerArr2;
                        bool4 = bool2;
                        num46 = num20;
                        list10 = list4;
                        inHouseIMGroupMemberInfo4 = inHouseIMGroupMemberInfo2;
                        inHouseIMGroupOfficialInfo4 = inHouseIMGroupOfficialInfo2;
                        num45 = num15;
                        str27 = str15;
                        str28 = str14;
                        groupPublicType4 = groupPublicType2;
                        str29 = str13;
                        str25 = str8;
                        kSerializerArr2 = kSerializerArr;
                        num47 = num19;
                        break;
                    case 21:
                        list6 = list9;
                        i10 = i16;
                        num41 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 21, IntSerializer.INSTANCE, num41);
                        i11 = 2097152 | i;
                        Unit unit21 = Unit.INSTANCE;
                        num26 = num49;
                        i = i11;
                        inHouseIMGroupMemberInfo2 = inHouseIMGroupMemberInfo4;
                        list4 = list10;
                        bool2 = bool4;
                        inHouseIMGroupOfficialInfo2 = inHouseIMGroupOfficialInfo4;
                        num15 = num45;
                        str8 = str25;
                        i16 = i10;
                        list9 = list6;
                        num49 = num26;
                        num20 = num46;
                        groupPublicType2 = groupPublicType4;
                        num19 = num47;
                        str15 = str27;
                        str14 = str28;
                        str13 = str29;
                        kSerializerArr = kSerializerArr2;
                        bool4 = bool2;
                        num46 = num20;
                        list10 = list4;
                        inHouseIMGroupMemberInfo4 = inHouseIMGroupMemberInfo2;
                        inHouseIMGroupOfficialInfo4 = inHouseIMGroupOfficialInfo2;
                        num45 = num15;
                        str27 = str15;
                        str28 = str14;
                        groupPublicType4 = groupPublicType2;
                        str29 = str13;
                        str25 = str8;
                        kSerializerArr2 = kSerializerArr;
                        num47 = num19;
                        break;
                    case 22:
                        list6 = list9;
                        i10 = i16;
                        inHouseIMGroupPermissionInfo7 = (InHouseIMGroupPermissionInfo) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 22, InHouseIMGroupPermissionInfo$$serializer.INSTANCE, inHouseIMGroupPermissionInfo7);
                        i11 = 4194304 | i;
                        Unit unit22 = Unit.INSTANCE;
                        num26 = num49;
                        i = i11;
                        inHouseIMGroupMemberInfo2 = inHouseIMGroupMemberInfo4;
                        list4 = list10;
                        bool2 = bool4;
                        inHouseIMGroupOfficialInfo2 = inHouseIMGroupOfficialInfo4;
                        num15 = num45;
                        str8 = str25;
                        i16 = i10;
                        list9 = list6;
                        num49 = num26;
                        num20 = num46;
                        groupPublicType2 = groupPublicType4;
                        num19 = num47;
                        str15 = str27;
                        str14 = str28;
                        str13 = str29;
                        kSerializerArr = kSerializerArr2;
                        bool4 = bool2;
                        num46 = num20;
                        list10 = list4;
                        inHouseIMGroupMemberInfo4 = inHouseIMGroupMemberInfo2;
                        inHouseIMGroupOfficialInfo4 = inHouseIMGroupOfficialInfo2;
                        num45 = num15;
                        str27 = str15;
                        str28 = str14;
                        groupPublicType4 = groupPublicType2;
                        str29 = str13;
                        str25 = str8;
                        kSerializerArr2 = kSerializerArr;
                        num47 = num19;
                        break;
                    case 23:
                        list7 = list9;
                        i13 = i16;
                        groupVoiceCallConfig3 = (GroupVoiceCallConfig) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 23, GroupVoiceCallConfig$$serializer.INSTANCE, groupVoiceCallConfig3);
                        i14 = 8388608;
                        i |= i14;
                        Unit unit23 = Unit.INSTANCE;
                        list9 = list7;
                        num26 = num49;
                        inHouseIMGroupMemberInfo2 = inHouseIMGroupMemberInfo4;
                        list4 = list10;
                        bool2 = bool4;
                        inHouseIMGroupOfficialInfo2 = inHouseIMGroupOfficialInfo4;
                        num15 = num45;
                        str8 = str25;
                        i16 = i13;
                        num49 = num26;
                        num20 = num46;
                        groupPublicType2 = groupPublicType4;
                        num19 = num47;
                        str15 = str27;
                        str14 = str28;
                        str13 = str29;
                        kSerializerArr = kSerializerArr2;
                        bool4 = bool2;
                        num46 = num20;
                        list10 = list4;
                        inHouseIMGroupMemberInfo4 = inHouseIMGroupMemberInfo2;
                        inHouseIMGroupOfficialInfo4 = inHouseIMGroupOfficialInfo2;
                        num45 = num15;
                        str27 = str15;
                        str28 = str14;
                        groupPublicType4 = groupPublicType2;
                        str29 = str13;
                        str25 = str8;
                        kSerializerArr2 = kSerializerArr;
                        num47 = num19;
                        break;
                    case 24:
                        list7 = list9;
                        i13 = i16;
                        l3 = (Long) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 24, LongSerializer.INSTANCE, l3);
                        i14 = 16777216;
                        i |= i14;
                        Unit unit232 = Unit.INSTANCE;
                        list9 = list7;
                        num26 = num49;
                        inHouseIMGroupMemberInfo2 = inHouseIMGroupMemberInfo4;
                        list4 = list10;
                        bool2 = bool4;
                        inHouseIMGroupOfficialInfo2 = inHouseIMGroupOfficialInfo4;
                        num15 = num45;
                        str8 = str25;
                        i16 = i13;
                        num49 = num26;
                        num20 = num46;
                        groupPublicType2 = groupPublicType4;
                        num19 = num47;
                        str15 = str27;
                        str14 = str28;
                        str13 = str29;
                        kSerializerArr = kSerializerArr2;
                        bool4 = bool2;
                        num46 = num20;
                        list10 = list4;
                        inHouseIMGroupMemberInfo4 = inHouseIMGroupMemberInfo2;
                        inHouseIMGroupOfficialInfo4 = inHouseIMGroupOfficialInfo2;
                        num45 = num15;
                        str27 = str15;
                        str28 = str14;
                        groupPublicType4 = groupPublicType2;
                        str29 = str13;
                        str25 = str8;
                        kSerializerArr2 = kSerializerArr;
                        num47 = num19;
                        break;
                    case 25:
                        list7 = list9;
                        i13 = i16;
                        num39 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 25, IntSerializer.INSTANCE, num39);
                        i |= MediaHttpDownloader.MAXIMUM_CHUNK_SIZE;
                        Unit unit24 = Unit.INSTANCE;
                        list9 = list7;
                        num26 = num49;
                        inHouseIMGroupMemberInfo2 = inHouseIMGroupMemberInfo4;
                        list4 = list10;
                        bool2 = bool4;
                        inHouseIMGroupOfficialInfo2 = inHouseIMGroupOfficialInfo4;
                        num15 = num45;
                        str8 = str25;
                        i16 = i13;
                        num49 = num26;
                        num20 = num46;
                        groupPublicType2 = groupPublicType4;
                        num19 = num47;
                        str15 = str27;
                        str14 = str28;
                        str13 = str29;
                        kSerializerArr = kSerializerArr2;
                        bool4 = bool2;
                        num46 = num20;
                        list10 = list4;
                        inHouseIMGroupMemberInfo4 = inHouseIMGroupMemberInfo2;
                        inHouseIMGroupOfficialInfo4 = inHouseIMGroupOfficialInfo2;
                        num45 = num15;
                        str27 = str15;
                        str28 = str14;
                        groupPublicType4 = groupPublicType2;
                        str29 = str13;
                        str25 = str8;
                        kSerializerArr2 = kSerializerArr;
                        num47 = num19;
                        break;
                    case 26:
                        list7 = list9;
                        i13 = i16;
                        num44 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 26, IntSerializer.INSTANCE, num44);
                        i14 = 67108864;
                        i |= i14;
                        Unit unit2322 = Unit.INSTANCE;
                        list9 = list7;
                        num26 = num49;
                        inHouseIMGroupMemberInfo2 = inHouseIMGroupMemberInfo4;
                        list4 = list10;
                        bool2 = bool4;
                        inHouseIMGroupOfficialInfo2 = inHouseIMGroupOfficialInfo4;
                        num15 = num45;
                        str8 = str25;
                        i16 = i13;
                        num49 = num26;
                        num20 = num46;
                        groupPublicType2 = groupPublicType4;
                        num19 = num47;
                        str15 = str27;
                        str14 = str28;
                        str13 = str29;
                        kSerializerArr = kSerializerArr2;
                        bool4 = bool2;
                        num46 = num20;
                        list10 = list4;
                        inHouseIMGroupMemberInfo4 = inHouseIMGroupMemberInfo2;
                        inHouseIMGroupOfficialInfo4 = inHouseIMGroupOfficialInfo2;
                        num45 = num15;
                        str27 = str15;
                        str28 = str14;
                        groupPublicType4 = groupPublicType2;
                        str29 = str13;
                        str25 = str8;
                        kSerializerArr2 = kSerializerArr;
                        num47 = num19;
                        break;
                    case 27:
                        list7 = list9;
                        i13 = i16;
                        num43 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 27, IntSerializer.INSTANCE, num43);
                        i14 = 134217728;
                        i |= i14;
                        Unit unit23222 = Unit.INSTANCE;
                        list9 = list7;
                        num26 = num49;
                        inHouseIMGroupMemberInfo2 = inHouseIMGroupMemberInfo4;
                        list4 = list10;
                        bool2 = bool4;
                        inHouseIMGroupOfficialInfo2 = inHouseIMGroupOfficialInfo4;
                        num15 = num45;
                        str8 = str25;
                        i16 = i13;
                        num49 = num26;
                        num20 = num46;
                        groupPublicType2 = groupPublicType4;
                        num19 = num47;
                        str15 = str27;
                        str14 = str28;
                        str13 = str29;
                        kSerializerArr = kSerializerArr2;
                        bool4 = bool2;
                        num46 = num20;
                        list10 = list4;
                        inHouseIMGroupMemberInfo4 = inHouseIMGroupMemberInfo2;
                        inHouseIMGroupOfficialInfo4 = inHouseIMGroupOfficialInfo2;
                        num45 = num15;
                        str27 = str15;
                        str28 = str14;
                        groupPublicType4 = groupPublicType2;
                        str29 = str13;
                        str25 = str8;
                        kSerializerArr2 = kSerializerArr;
                        num47 = num19;
                        break;
                    case 28:
                        i13 = i16;
                        list7 = list9;
                        num42 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 28, IntSerializer.INSTANCE, num42);
                        i14 = 268435456;
                        i |= i14;
                        Unit unit232222 = Unit.INSTANCE;
                        list9 = list7;
                        num26 = num49;
                        inHouseIMGroupMemberInfo2 = inHouseIMGroupMemberInfo4;
                        list4 = list10;
                        bool2 = bool4;
                        inHouseIMGroupOfficialInfo2 = inHouseIMGroupOfficialInfo4;
                        num15 = num45;
                        str8 = str25;
                        i16 = i13;
                        num49 = num26;
                        num20 = num46;
                        groupPublicType2 = groupPublicType4;
                        num19 = num47;
                        str15 = str27;
                        str14 = str28;
                        str13 = str29;
                        kSerializerArr = kSerializerArr2;
                        bool4 = bool2;
                        num46 = num20;
                        list10 = list4;
                        inHouseIMGroupMemberInfo4 = inHouseIMGroupMemberInfo2;
                        inHouseIMGroupOfficialInfo4 = inHouseIMGroupOfficialInfo2;
                        num45 = num15;
                        str27 = str15;
                        str28 = str14;
                        groupPublicType4 = groupPublicType2;
                        str29 = str13;
                        str25 = str8;
                        kSerializerArr2 = kSerializerArr;
                        num47 = num19;
                        break;
                    case 29:
                        i13 = i16;
                        paidGroupInfo3 = (PaidGroupInfo) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 29, PaidGroupInfo$$serializer.INSTANCE, paidGroupInfo3);
                        i15 = 536870912;
                        i |= i15;
                        Unit unit25 = Unit.INSTANCE;
                        num26 = num49;
                        inHouseIMGroupMemberInfo2 = inHouseIMGroupMemberInfo4;
                        list4 = list10;
                        bool2 = bool4;
                        inHouseIMGroupOfficialInfo2 = inHouseIMGroupOfficialInfo4;
                        num15 = num45;
                        str8 = str25;
                        i16 = i13;
                        num49 = num26;
                        num20 = num46;
                        groupPublicType2 = groupPublicType4;
                        num19 = num47;
                        str15 = str27;
                        str14 = str28;
                        str13 = str29;
                        kSerializerArr = kSerializerArr2;
                        bool4 = bool2;
                        num46 = num20;
                        list10 = list4;
                        inHouseIMGroupMemberInfo4 = inHouseIMGroupMemberInfo2;
                        inHouseIMGroupOfficialInfo4 = inHouseIMGroupOfficialInfo2;
                        num45 = num15;
                        str27 = str15;
                        str28 = str14;
                        groupPublicType4 = groupPublicType2;
                        str29 = str13;
                        str25 = str8;
                        kSerializerArr2 = kSerializerArr;
                        num47 = num19;
                        break;
                    case 30:
                        i13 = i16;
                        inHouseIMGroupCampaign3 = (InHouseIMGroupCampaign) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 30, InHouseIMGroupCampaign$$serializer.INSTANCE, inHouseIMGroupCampaign3);
                        i15 = 1073741824;
                        i |= i15;
                        Unit unit252 = Unit.INSTANCE;
                        num26 = num49;
                        inHouseIMGroupMemberInfo2 = inHouseIMGroupMemberInfo4;
                        list4 = list10;
                        bool2 = bool4;
                        inHouseIMGroupOfficialInfo2 = inHouseIMGroupOfficialInfo4;
                        num15 = num45;
                        str8 = str25;
                        i16 = i13;
                        num49 = num26;
                        num20 = num46;
                        groupPublicType2 = groupPublicType4;
                        num19 = num47;
                        str15 = str27;
                        str14 = str28;
                        str13 = str29;
                        kSerializerArr = kSerializerArr2;
                        bool4 = bool2;
                        num46 = num20;
                        list10 = list4;
                        inHouseIMGroupMemberInfo4 = inHouseIMGroupMemberInfo2;
                        inHouseIMGroupOfficialInfo4 = inHouseIMGroupOfficialInfo2;
                        num45 = num15;
                        str27 = str15;
                        str28 = str14;
                        groupPublicType4 = groupPublicType2;
                        str29 = str13;
                        str25 = str8;
                        kSerializerArr2 = kSerializerArr;
                        num47 = num19;
                        break;
                    case 31:
                        i13 = i16;
                        list9 = (List) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 31, kSerializerArr2[31], list9);
                        i |= Integer.MIN_VALUE;
                        Unit unit26 = Unit.INSTANCE;
                        num26 = num49;
                        inHouseIMGroupMemberInfo2 = inHouseIMGroupMemberInfo4;
                        list4 = list10;
                        bool2 = bool4;
                        inHouseIMGroupOfficialInfo2 = inHouseIMGroupOfficialInfo4;
                        num15 = num45;
                        str8 = str25;
                        i16 = i13;
                        num49 = num26;
                        num20 = num46;
                        groupPublicType2 = groupPublicType4;
                        num19 = num47;
                        str15 = str27;
                        str14 = str28;
                        str13 = str29;
                        kSerializerArr = kSerializerArr2;
                        bool4 = bool2;
                        num46 = num20;
                        list10 = list4;
                        inHouseIMGroupMemberInfo4 = inHouseIMGroupMemberInfo2;
                        inHouseIMGroupOfficialInfo4 = inHouseIMGroupOfficialInfo2;
                        num45 = num15;
                        str27 = str15;
                        str28 = str14;
                        groupPublicType4 = groupPublicType2;
                        str29 = str13;
                        str25 = str8;
                        kSerializerArr2 = kSerializerArr;
                        num47 = num19;
                        break;
                    case 32:
                        i13 = i16;
                        inHouseIMSuperGroupConfig2 = (InHouseIMSuperGroupConfig) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 32, InHouseIMSuperGroupConfig$$serializer.INSTANCE, inHouseIMSuperGroupConfig2);
                        Unit unit27 = Unit.INSTANCE;
                        i17 = 1;
                        num26 = num49;
                        inHouseIMGroupMemberInfo2 = inHouseIMGroupMemberInfo4;
                        list4 = list10;
                        bool2 = bool4;
                        inHouseIMGroupOfficialInfo2 = inHouseIMGroupOfficialInfo4;
                        num15 = num45;
                        str8 = str25;
                        i16 = i13;
                        num49 = num26;
                        num20 = num46;
                        groupPublicType2 = groupPublicType4;
                        num19 = num47;
                        str15 = str27;
                        str14 = str28;
                        str13 = str29;
                        kSerializerArr = kSerializerArr2;
                        bool4 = bool2;
                        num46 = num20;
                        list10 = list4;
                        inHouseIMGroupMemberInfo4 = inHouseIMGroupMemberInfo2;
                        inHouseIMGroupOfficialInfo4 = inHouseIMGroupOfficialInfo2;
                        num45 = num15;
                        str27 = str15;
                        str28 = str14;
                        groupPublicType4 = groupPublicType2;
                        str29 = str13;
                        str25 = str8;
                        kSerializerArr2 = kSerializerArr;
                        num47 = num19;
                        break;
                    default:
                        throw new UnknownFieldException(iDecodeElementIndex);
                }
            }
            num = num47;
            num2 = num40;
            num3 = num41;
            inHouseIMGroupMemberInfo = inHouseIMGroupMemberInfo4;
            num4 = num38;
            str = str25;
            num5 = num44;
            l = l3;
            groupVoiceCallConfig = groupVoiceCallConfig3;
            inHouseIMGroupPermissionInfo = inHouseIMGroupPermissionInfo7;
            str2 = str27;
            list = list9;
            str3 = str29;
            num6 = num46;
            paidGroupInfo = paidGroupInfo3;
            inHouseIMGroupCampaign = inHouseIMGroupCampaign3;
            inHouseIMGroupAnnouncementInfo = inHouseIMGroupAnnouncementInfo6;
            groupPublicType = groupPublicType4;
            i2 = i17;
            str4 = str30;
            num7 = num39;
            list2 = list10;
            str5 = str26;
            num8 = num48;
            bool = bool4;
            inHouseIMGroupOfficialInfo = inHouseIMGroupOfficialInfo4;
            num9 = num49;
            str6 = str24;
            inHouseIMSuperGroupConfig = inHouseIMSuperGroupConfig2;
            str7 = str28;
            num10 = num45;
            i3 = i16;
            Integer num50 = num43;
            num11 = num42;
            num12 = num50;
        }
        compositeDecoderBeginStructure.endStructure(serialDescriptor);
        return new InHouseIMGroupInfo(i, i2, str4, str7, str5, str2, str3, groupPublicType, num8, num6, num9, num4, num, i3, num2, str, num10, inHouseIMGroupOfficialInfo, bool, list2, inHouseIMGroupMemberInfo, inHouseIMGroupAnnouncementInfo, str6, num3, inHouseIMGroupPermissionInfo, groupVoiceCallConfig, l, num7, num5, num12, num11, paidGroupInfo, inHouseIMGroupCampaign, list, inHouseIMSuperGroupConfig, (SerializationConstructorMarker) null);
    }

    /* JADX DEBUG: Method merged with bridge method: serialize(Lkotlinx/serialization/encoding/Encoder;Ljava/lang/Object;)V */
    @Override // kotlinx.serialization.SerializationStrategy
    public final void serialize(@NotNull Encoder encoder, @NotNull InHouseIMGroupInfo inHouseIMGroupInfo) {
        Intrinsics.checkNotNullParameter(encoder, "");
        Intrinsics.checkNotNullParameter(inHouseIMGroupInfo, "");
        SerialDescriptor serialDescriptor = descriptor;
        CompositeEncoder compositeEncoderBeginStructure = encoder.beginStructure(serialDescriptor);
        InHouseIMGroupInfo.write$Self$OKIMCore_okimcore(inHouseIMGroupInfo, compositeEncoderBeginStructure, serialDescriptor);
        compositeEncoderBeginStructure.endStructure(serialDescriptor);
    }
}
