package com.okinc.okimcore.model.room.inhouseim;

import com.engagelab.privates.analysis.constants.MTAnalysisConstants;
import com.google.api.client.googleapis.media.MediaHttpDownloader;
import com.huawei.hms.push.constant.RemoteMessageConst;
import java.util.List;
import kotlin.Unit;
import kotlin.jvm.internal.Intrinsics;
import kotlinx.serialization.KSerializer;
import kotlinx.serialization.UnknownFieldException;
import kotlinx.serialization.builtins.BuiltinSerializersKt;
import kotlinx.serialization.descriptors.SerialDescriptor;
import kotlinx.serialization.encoding.CompositeDecoder;
import kotlinx.serialization.encoding.CompositeEncoder;
import kotlinx.serialization.encoding.Decoder;
import kotlinx.serialization.encoding.Encoder;
import kotlinx.serialization.internal.GeneratedSerializer;
import kotlinx.serialization.internal.IntSerializer;
import kotlinx.serialization.internal.LongSerializer;
import kotlinx.serialization.internal.PluginGeneratedSerialDescriptor;
import kotlinx.serialization.internal.SerializationConstructorMarker;
import kotlinx.serialization.internal.StringSerializer;
import kotlinx.serialization.json.JsonElement;
import kotlinx.serialization.json.JsonElementSerializer;
import org.jetbrains.annotations.NotNull;

/* JADX INFO: loaded from: classes16.dex */
public final /* synthetic */ class InHouseIMConversationEntity$$serializer implements GeneratedSerializer<InHouseIMConversationEntity> {
    public static final int $stable;
    public static final InHouseIMConversationEntity$$serializer INSTANCE;
    private static final SerialDescriptor descriptor;

    /* JADX DEBUG: Don't trust debug lines info. Lines numbers was adjusted: min line is 0 */
    private InHouseIMConversationEntity$$serializer() {
    }

    /* JADX DEBUG: Don't trust debug lines info. Lines numbers was adjusted: min line is 0 */
    @Override // kotlinx.serialization.KSerializer, kotlinx.serialization.SerializationStrategy, kotlinx.serialization.DeserializationStrategy
    public final SerialDescriptor getDescriptor() {
        return descriptor;
    }

    static {
        InHouseIMConversationEntity$$serializer inHouseIMConversationEntity$$serializer = new InHouseIMConversationEntity$$serializer();
        INSTANCE = inHouseIMConversationEntity$$serializer;
        $stable = 8;
        PluginGeneratedSerialDescriptor pluginGeneratedSerialDescriptor = new PluginGeneratedSerialDescriptor("com.okinc.okimcore.model.room.inhouseim.InHouseIMConversationEntity", inHouseIMConversationEntity$$serializer, 29);
        pluginGeneratedSerialDescriptor.addElement(RemoteMessageConst.Notification.CHANNEL_ID, true);
        pluginGeneratedSerialDescriptor.addElement("channelType", true);
        pluginGeneratedSerialDescriptor.addElement("groupAtType", true);
        pluginGeneratedSerialDescriptor.addElement("inGroupStatus", true);
        pluginGeneratedSerialDescriptor.addElement("groupStatus", true);
        pluginGeneratedSerialDescriptor.addElement("pinnedStatus", true);
        pluginGeneratedSerialDescriptor.addElement("isFlagged", true);
        pluginGeneratedSerialDescriptor.addElement("muteStatus", true);
        pluginGeneratedSerialDescriptor.addElement("role", true);
        pluginGeneratedSerialDescriptor.addElement("unreadCount", true);
        pluginGeneratedSerialDescriptor.addElement("unreadMentionedCount", true);
        pluginGeneratedSerialDescriptor.addElement("unreadMentionedType", true);
        pluginGeneratedSerialDescriptor.addElement("startMsgSeq", true);
        pluginGeneratedSerialDescriptor.addElement("lastReadMsgSeq", true);
        pluginGeneratedSerialDescriptor.addElement(MTAnalysisConstants.ACCOUNT_EXTRA_ATTR, true);
        pluginGeneratedSerialDescriptor.addElement("lastUserMessageId", true);
        pluginGeneratedSerialDescriptor.addElement("lastUserMessageSendTime", true);
        pluginGeneratedSerialDescriptor.addElement("draftMessage", true);
        pluginGeneratedSerialDescriptor.addElement("updateTime", true);
        pluginGeneratedSerialDescriptor.addElement("conversationStatus", true);
        pluginGeneratedSerialDescriptor.addElement("relatedId", true);
        pluginGeneratedSerialDescriptor.addElement("avatar", true);
        pluginGeneratedSerialDescriptor.addElement("nickname", false);
        pluginGeneratedSerialDescriptor.addElement("enNickname", false);
        pluginGeneratedSerialDescriptor.addElement("bizGroupName", true);
        pluginGeneratedSerialDescriptor.addElement("tags", true);
        pluginGeneratedSerialDescriptor.addElement("groupType", false);
        pluginGeneratedSerialDescriptor.addElement("conversationIcons", true);
        pluginGeneratedSerialDescriptor.addElement("entityInfoExtra", true);
        descriptor = pluginGeneratedSerialDescriptor;
    }

    @Override // kotlinx.serialization.internal.GeneratedSerializer
    public final KSerializer<?>[] childSerializers() {
        KSerializer[] kSerializerArr = InHouseIMConversationEntity.$childSerializers;
        StringSerializer stringSerializer = StringSerializer.INSTANCE;
        IntSerializer intSerializer = IntSerializer.INSTANCE;
        LongSerializer longSerializer = LongSerializer.INSTANCE;
        return new KSerializer[]{stringSerializer, BuiltinSerializersKt.getNullable(intSerializer), intSerializer, BuiltinSerializersKt.getNullable(intSerializer), BuiltinSerializersKt.getNullable(intSerializer), intSerializer, intSerializer, BuiltinSerializersKt.getNullable(intSerializer), intSerializer, intSerializer, intSerializer, BuiltinSerializersKt.getNullable(intSerializer), BuiltinSerializersKt.getNullable(longSerializer), BuiltinSerializersKt.getNullable(longSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), longSerializer, BuiltinSerializersKt.getNullable(DraftMessageModel$$serializer.INSTANCE), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(intSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(kSerializerArr[25]), BuiltinSerializersKt.getNullable(intSerializer), BuiltinSerializersKt.getNullable(kSerializerArr[27]), BuiltinSerializersKt.getNullable(JsonElementSerializer.INSTANCE)};
    }

    /* JADX DEBUG: Method merged with bridge method: deserialize(Lkotlinx/serialization/encoding/Decoder;)Ljava/lang/Object; */
    @Override // kotlinx.serialization.DeserializationStrategy
    public final InHouseIMConversationEntity deserialize(@NotNull Decoder decoder) {
        Long l;
        Integer num;
        String str;
        String str2;
        int i;
        List list;
        String str3;
        String str4;
        JsonElement jsonElement;
        String str5;
        Long l2;
        Integer num2;
        Integer num3;
        Integer num4;
        String str6;
        int i2;
        int i3;
        int iDecodeIntElement;
        Integer num5;
        String str7;
        String str8;
        DraftMessageModel draftMessageModel;
        String str9;
        Integer num6;
        int i4;
        int i5;
        long j;
        Integer num7;
        int i6;
        List list2;
        KSerializer[] kSerializerArr;
        JsonElement jsonElement2;
        Integer num8;
        Integer num9;
        Integer num10;
        Long l3;
        Long l4;
        String str10;
        String str11;
        Integer num11;
        String str12;
        DraftMessageModel draftMessageModel2;
        String str13;
        String str14;
        String str15;
        Integer num12;
        List list3;
        int i7;
        String str16;
        String str17;
        Integer num13;
        Long l5;
        Long l6;
        int i8;
        JsonElement jsonElement3;
        Integer num14;
        Long l7;
        int i9;
        Integer num15;
        int i10;
        JsonElement jsonElement4;
        Long l8;
        int iDecodeIntElement2;
        Integer num16;
        int i11;
        Integer num17;
        int i12;
        JsonElement jsonElement5;
        DraftMessageModel draftMessageModel3;
        int i13;
        String str18;
        int i14;
        int i15;
        int i16;
        Intrinsics.checkNotNullParameter(decoder, "");
        SerialDescriptor serialDescriptor = descriptor;
        CompositeDecoder compositeDecoderBeginStructure = decoder.beginStructure(serialDescriptor);
        KSerializer[] kSerializerArr2 = InHouseIMConversationEntity.$childSerializers;
        int i17 = 0;
        if (compositeDecoderBeginStructure.decodeSequentially()) {
            String strDecodeStringElement = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 0);
            IntSerializer intSerializer = IntSerializer.INSTANCE;
            Integer num18 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 1, intSerializer, null);
            int iDecodeIntElement3 = compositeDecoderBeginStructure.decodeIntElement(serialDescriptor, 2);
            Integer num19 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 3, intSerializer, null);
            Integer num20 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 4, intSerializer, null);
            iDecodeIntElement = compositeDecoderBeginStructure.decodeIntElement(serialDescriptor, 5);
            int iDecodeIntElement4 = compositeDecoderBeginStructure.decodeIntElement(serialDescriptor, 6);
            Integer num21 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 7, intSerializer, null);
            int iDecodeIntElement5 = compositeDecoderBeginStructure.decodeIntElement(serialDescriptor, 8);
            int iDecodeIntElement6 = compositeDecoderBeginStructure.decodeIntElement(serialDescriptor, 9);
            int iDecodeIntElement7 = compositeDecoderBeginStructure.decodeIntElement(serialDescriptor, 10);
            Integer num22 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 11, intSerializer, null);
            LongSerializer longSerializer = LongSerializer.INSTANCE;
            Long l9 = (Long) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 12, longSerializer, null);
            Long l10 = (Long) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 13, longSerializer, null);
            StringSerializer stringSerializer = StringSerializer.INSTANCE;
            String str19 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 14, stringSerializer, null);
            String str20 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 15, stringSerializer, null);
            long jDecodeLongElement = compositeDecoderBeginStructure.decodeLongElement(serialDescriptor, 16);
            DraftMessageModel draftMessageModel4 = (DraftMessageModel) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 17, DraftMessageModel$$serializer.INSTANCE, null);
            String str21 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 18, stringSerializer, null);
            Integer num23 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 19, intSerializer, null);
            String str22 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 20, stringSerializer, null);
            String str23 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 21, stringSerializer, null);
            String str24 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 22, stringSerializer, null);
            String str25 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 23, stringSerializer, null);
            String str26 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 24, stringSerializer, null);
            List list4 = (List) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 25, kSerializerArr2[25], null);
            Integer num24 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 26, intSerializer, null);
            List list5 = (List) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 27, kSerializerArr2[27], null);
            jsonElement = (JsonElement) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 28, JsonElementSerializer.INSTANCE, null);
            list = list4;
            num7 = num24;
            list2 = list5;
            str = str26;
            l2 = l9;
            num4 = num22;
            str6 = strDecodeStringElement;
            str5 = str20;
            str3 = str24;
            str2 = str25;
            draftMessageModel = draftMessageModel4;
            str9 = str19;
            l = l10;
            str4 = str22;
            str8 = str23;
            str7 = str21;
            i5 = iDecodeIntElement7;
            i2 = iDecodeIntElement6;
            num5 = num18;
            num = num23;
            i6 = iDecodeIntElement3;
            i = 536870911;
            i3 = iDecodeIntElement4;
            num2 = num20;
            i4 = iDecodeIntElement5;
            num3 = num21;
            num6 = num19;
            j = jDecodeLongElement;
        } else {
            String str27 = null;
            boolean z = true;
            JsonElement jsonElement6 = null;
            String str28 = null;
            List list6 = null;
            Integer num25 = null;
            DraftMessageModel draftMessageModel5 = null;
            String str29 = null;
            List list7 = null;
            Integer num26 = null;
            String str30 = null;
            String str31 = null;
            String str32 = null;
            Integer num27 = null;
            Integer num28 = null;
            Integer num29 = null;
            Long l11 = null;
            Long l12 = null;
            String str33 = null;
            String str34 = null;
            Integer num30 = null;
            String str35 = null;
            Integer num31 = null;
            int i18 = 0;
            int i19 = 0;
            int iDecodeIntElement8 = 0;
            int iDecodeIntElement9 = 0;
            int iDecodeIntElement10 = 0;
            int iDecodeIntElement11 = 0;
            long jDecodeLongElement2 = 0;
            while (z) {
                DraftMessageModel draftMessageModel6 = draftMessageModel5;
                int iDecodeElementIndex = compositeDecoderBeginStructure.decodeElementIndex(serialDescriptor);
                switch (iDecodeElementIndex) {
                    case -1:
                        kSerializerArr = kSerializerArr2;
                        jsonElement2 = jsonElement6;
                        num8 = num27;
                        num9 = num28;
                        num10 = num29;
                        l3 = l11;
                        l4 = l12;
                        str10 = str33;
                        str11 = str34;
                        num11 = num30;
                        Unit unit = Unit.INSTANCE;
                        z = false;
                        str28 = str28;
                        draftMessageModel5 = draftMessageModel6;
                        kSerializerArr2 = kSerializerArr;
                        jsonElement6 = jsonElement2;
                        str34 = str11;
                        str33 = str10;
                        l12 = l4;
                        l11 = l3;
                        num30 = num11;
                        num27 = num8;
                        num28 = num9;
                        num29 = num10;
                        break;
                    case 0:
                        kSerializerArr = kSerializerArr2;
                        jsonElement2 = jsonElement6;
                        num8 = num27;
                        num9 = num28;
                        num10 = num29;
                        l3 = l11;
                        l4 = l12;
                        str10 = str33;
                        str11 = str34;
                        num11 = num30;
                        String strDecodeStringElement2 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 0);
                        i17 |= 1;
                        Unit unit2 = Unit.INSTANCE;
                        str28 = str28;
                        draftMessageModel5 = draftMessageModel6;
                        str35 = strDecodeStringElement2;
                        kSerializerArr2 = kSerializerArr;
                        jsonElement6 = jsonElement2;
                        str34 = str11;
                        str33 = str10;
                        l12 = l4;
                        l11 = l3;
                        num30 = num11;
                        num27 = num8;
                        num28 = num9;
                        num29 = num10;
                        break;
                    case 1:
                        kSerializerArr = kSerializerArr2;
                        jsonElement2 = jsonElement6;
                        String str36 = str28;
                        num8 = num27;
                        num9 = num28;
                        num10 = num29;
                        l3 = l11;
                        l4 = l12;
                        str10 = str33;
                        str11 = str34;
                        num11 = num30;
                        Integer num32 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 1, IntSerializer.INSTANCE, num31);
                        i17 |= 2;
                        Unit unit3 = Unit.INSTANCE;
                        num31 = num32;
                        str28 = str36;
                        draftMessageModel5 = draftMessageModel6;
                        kSerializerArr2 = kSerializerArr;
                        jsonElement6 = jsonElement2;
                        str34 = str11;
                        str33 = str10;
                        l12 = l4;
                        l11 = l3;
                        num30 = num11;
                        num27 = num8;
                        num28 = num9;
                        num29 = num10;
                        break;
                    case 2:
                        kSerializerArr = kSerializerArr2;
                        str12 = str28;
                        num8 = num27;
                        num9 = num28;
                        num10 = num29;
                        l3 = l11;
                        str10 = str33;
                        str11 = str34;
                        draftMessageModel2 = draftMessageModel6;
                        int iDecodeIntElement12 = compositeDecoderBeginStructure.decodeIntElement(serialDescriptor, 2);
                        Unit unit4 = Unit.INSTANCE;
                        jsonElement6 = jsonElement6;
                        i19 = iDecodeIntElement12;
                        str13 = str32;
                        str14 = str31;
                        str15 = str30;
                        num12 = num26;
                        list3 = list7;
                        i7 = i17 | 4;
                        str16 = str29;
                        str17 = str27;
                        num13 = num25;
                        l5 = l12;
                        l4 = l5;
                        str28 = str12;
                        num25 = num13;
                        str27 = str17;
                        str29 = str16;
                        i17 = i7;
                        list7 = list3;
                        num26 = num12;
                        str30 = str15;
                        str31 = str14;
                        str32 = str13;
                        draftMessageModel5 = draftMessageModel2;
                        num11 = num30;
                        jsonElement2 = jsonElement6;
                        kSerializerArr2 = kSerializerArr;
                        jsonElement6 = jsonElement2;
                        str34 = str11;
                        str33 = str10;
                        l12 = l4;
                        l11 = l3;
                        num30 = num11;
                        num27 = num8;
                        num28 = num9;
                        num29 = num10;
                        break;
                    case 3:
                        kSerializerArr = kSerializerArr2;
                        JsonElement jsonElement7 = jsonElement6;
                        str12 = str28;
                        num9 = num28;
                        num10 = num29;
                        l3 = l11;
                        l6 = l12;
                        str10 = str33;
                        str11 = str34;
                        draftMessageModel2 = draftMessageModel6;
                        num8 = num27;
                        num30 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 3, IntSerializer.INSTANCE, num30);
                        i8 = i17 | 8;
                        Unit unit5 = Unit.INSTANCE;
                        str16 = str29;
                        jsonElement6 = jsonElement7;
                        str17 = str27;
                        str13 = str32;
                        num13 = num25;
                        str14 = str31;
                        l5 = l6;
                        str15 = str30;
                        num12 = num26;
                        list3 = list7;
                        i7 = i8;
                        l4 = l5;
                        str28 = str12;
                        num25 = num13;
                        str27 = str17;
                        str29 = str16;
                        i17 = i7;
                        list7 = list3;
                        num26 = num12;
                        str30 = str15;
                        str31 = str14;
                        str32 = str13;
                        draftMessageModel5 = draftMessageModel2;
                        num11 = num30;
                        jsonElement2 = jsonElement6;
                        kSerializerArr2 = kSerializerArr;
                        jsonElement6 = jsonElement2;
                        str34 = str11;
                        str33 = str10;
                        l12 = l4;
                        l11 = l3;
                        num30 = num11;
                        num27 = num8;
                        num28 = num9;
                        num29 = num10;
                        break;
                    case 4:
                        kSerializerArr = kSerializerArr2;
                        str12 = str28;
                        num10 = num29;
                        l3 = l11;
                        l6 = l12;
                        str10 = str33;
                        str11 = str34;
                        draftMessageModel2 = draftMessageModel6;
                        num9 = num28;
                        Integer num33 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 4, IntSerializer.INSTANCE, num27);
                        i8 = i17 | 16;
                        Unit unit6 = Unit.INSTANCE;
                        str16 = str29;
                        jsonElement6 = jsonElement6;
                        num8 = num33;
                        str17 = str27;
                        str13 = str32;
                        num13 = num25;
                        str14 = str31;
                        l5 = l6;
                        str15 = str30;
                        num12 = num26;
                        list3 = list7;
                        i7 = i8;
                        l4 = l5;
                        str28 = str12;
                        num25 = num13;
                        str27 = str17;
                        str29 = str16;
                        i17 = i7;
                        list7 = list3;
                        num26 = num12;
                        str30 = str15;
                        str31 = str14;
                        str32 = str13;
                        draftMessageModel5 = draftMessageModel2;
                        num11 = num30;
                        jsonElement2 = jsonElement6;
                        kSerializerArr2 = kSerializerArr;
                        jsonElement6 = jsonElement2;
                        str34 = str11;
                        str33 = str10;
                        l12 = l4;
                        l11 = l3;
                        num30 = num11;
                        num27 = num8;
                        num28 = num9;
                        num29 = num10;
                        break;
                    case 5:
                        kSerializerArr = kSerializerArr2;
                        jsonElement3 = jsonElement6;
                        str12 = str28;
                        num14 = num28;
                        num10 = num29;
                        l3 = l11;
                        l7 = l12;
                        str10 = str33;
                        str11 = str34;
                        draftMessageModel2 = draftMessageModel6;
                        iDecodeIntElement11 = compositeDecoderBeginStructure.decodeIntElement(serialDescriptor, 5);
                        i9 = i17 | 32;
                        Unit unit7 = Unit.INSTANCE;
                        int i20 = i9;
                        num15 = num14;
                        i10 = i20;
                        num9 = num15;
                        num8 = num27;
                        str16 = str29;
                        str17 = str27;
                        num13 = num25;
                        l5 = l7;
                        List list8 = list7;
                        i7 = i10;
                        jsonElement6 = jsonElement3;
                        str13 = str32;
                        str14 = str31;
                        str15 = str30;
                        num12 = num26;
                        list3 = list8;
                        l4 = l5;
                        str28 = str12;
                        num25 = num13;
                        str27 = str17;
                        str29 = str16;
                        i17 = i7;
                        list7 = list3;
                        num26 = num12;
                        str30 = str15;
                        str31 = str14;
                        str32 = str13;
                        draftMessageModel5 = draftMessageModel2;
                        num11 = num30;
                        jsonElement2 = jsonElement6;
                        kSerializerArr2 = kSerializerArr;
                        jsonElement6 = jsonElement2;
                        str34 = str11;
                        str33 = str10;
                        l12 = l4;
                        l11 = l3;
                        num30 = num11;
                        num27 = num8;
                        num28 = num9;
                        num29 = num10;
                        break;
                    case 6:
                        kSerializerArr = kSerializerArr2;
                        jsonElement3 = jsonElement6;
                        str12 = str28;
                        num14 = num28;
                        num10 = num29;
                        l3 = l11;
                        l7 = l12;
                        str10 = str33;
                        str11 = str34;
                        draftMessageModel2 = draftMessageModel6;
                        iDecodeIntElement10 = compositeDecoderBeginStructure.decodeIntElement(serialDescriptor, 6);
                        i9 = i17 | 64;
                        Unit unit8 = Unit.INSTANCE;
                        int i202 = i9;
                        num15 = num14;
                        i10 = i202;
                        num9 = num15;
                        num8 = num27;
                        str16 = str29;
                        str17 = str27;
                        num13 = num25;
                        l5 = l7;
                        List list82 = list7;
                        i7 = i10;
                        jsonElement6 = jsonElement3;
                        str13 = str32;
                        str14 = str31;
                        str15 = str30;
                        num12 = num26;
                        list3 = list82;
                        l4 = l5;
                        str28 = str12;
                        num25 = num13;
                        str27 = str17;
                        str29 = str16;
                        i17 = i7;
                        list7 = list3;
                        num26 = num12;
                        str30 = str15;
                        str31 = str14;
                        str32 = str13;
                        draftMessageModel5 = draftMessageModel2;
                        num11 = num30;
                        jsonElement2 = jsonElement6;
                        kSerializerArr2 = kSerializerArr;
                        jsonElement6 = jsonElement2;
                        str34 = str11;
                        str33 = str10;
                        l12 = l4;
                        l11 = l3;
                        num30 = num11;
                        num27 = num8;
                        num28 = num9;
                        num29 = num10;
                        break;
                    case 7:
                        kSerializerArr = kSerializerArr2;
                        jsonElement3 = jsonElement6;
                        str12 = str28;
                        l3 = l11;
                        l7 = l12;
                        str10 = str33;
                        str11 = str34;
                        draftMessageModel2 = draftMessageModel6;
                        num10 = num29;
                        Integer num34 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 7, IntSerializer.INSTANCE, num28);
                        i10 = i17 | 128;
                        Unit unit9 = Unit.INSTANCE;
                        num15 = num34;
                        num9 = num15;
                        num8 = num27;
                        str16 = str29;
                        str17 = str27;
                        num13 = num25;
                        l5 = l7;
                        List list822 = list7;
                        i7 = i10;
                        jsonElement6 = jsonElement3;
                        str13 = str32;
                        str14 = str31;
                        str15 = str30;
                        num12 = num26;
                        list3 = list822;
                        l4 = l5;
                        str28 = str12;
                        num25 = num13;
                        str27 = str17;
                        str29 = str16;
                        i17 = i7;
                        list7 = list3;
                        num26 = num12;
                        str30 = str15;
                        str31 = str14;
                        str32 = str13;
                        draftMessageModel5 = draftMessageModel2;
                        num11 = num30;
                        jsonElement2 = jsonElement6;
                        kSerializerArr2 = kSerializerArr;
                        jsonElement6 = jsonElement2;
                        str34 = str11;
                        str33 = str10;
                        l12 = l4;
                        l11 = l3;
                        num30 = num11;
                        num27 = num8;
                        num28 = num9;
                        num29 = num10;
                        break;
                    case 8:
                        kSerializerArr = kSerializerArr2;
                        jsonElement4 = jsonElement6;
                        str12 = str28;
                        l3 = l11;
                        l8 = l12;
                        str10 = str33;
                        str11 = str34;
                        draftMessageModel2 = draftMessageModel6;
                        iDecodeIntElement2 = compositeDecoderBeginStructure.decodeIntElement(serialDescriptor, 8);
                        int i21 = i17 | 256;
                        Unit unit10 = Unit.INSTANCE;
                        num16 = num29;
                        i11 = i21;
                        num10 = num16;
                        jsonElement6 = jsonElement4;
                        num8 = num27;
                        i18 = iDecodeIntElement2;
                        num9 = num28;
                        str16 = str29;
                        str13 = str32;
                        str17 = str27;
                        str14 = str31;
                        num13 = num25;
                        str15 = str30;
                        l5 = l8;
                        num12 = num26;
                        list3 = list7;
                        i7 = i11;
                        l4 = l5;
                        str28 = str12;
                        num25 = num13;
                        str27 = str17;
                        str29 = str16;
                        i17 = i7;
                        list7 = list3;
                        num26 = num12;
                        str30 = str15;
                        str31 = str14;
                        str32 = str13;
                        draftMessageModel5 = draftMessageModel2;
                        num11 = num30;
                        jsonElement2 = jsonElement6;
                        kSerializerArr2 = kSerializerArr;
                        jsonElement6 = jsonElement2;
                        str34 = str11;
                        str33 = str10;
                        l12 = l4;
                        l11 = l3;
                        num30 = num11;
                        num27 = num8;
                        num28 = num9;
                        num29 = num10;
                        break;
                    case 9:
                        kSerializerArr = kSerializerArr2;
                        jsonElement4 = jsonElement6;
                        str12 = str28;
                        num17 = num29;
                        l3 = l11;
                        l8 = l12;
                        str10 = str33;
                        str11 = str34;
                        draftMessageModel2 = draftMessageModel6;
                        iDecodeIntElement9 = compositeDecoderBeginStructure.decodeIntElement(serialDescriptor, 9);
                        i12 = i17 | 512;
                        Unit unit11 = Unit.INSTANCE;
                        int i22 = i12;
                        num16 = num17;
                        i11 = i22;
                        iDecodeIntElement2 = i18;
                        num10 = num16;
                        jsonElement6 = jsonElement4;
                        num8 = num27;
                        i18 = iDecodeIntElement2;
                        num9 = num28;
                        str16 = str29;
                        str13 = str32;
                        str17 = str27;
                        str14 = str31;
                        num13 = num25;
                        str15 = str30;
                        l5 = l8;
                        num12 = num26;
                        list3 = list7;
                        i7 = i11;
                        l4 = l5;
                        str28 = str12;
                        num25 = num13;
                        str27 = str17;
                        str29 = str16;
                        i17 = i7;
                        list7 = list3;
                        num26 = num12;
                        str30 = str15;
                        str31 = str14;
                        str32 = str13;
                        draftMessageModel5 = draftMessageModel2;
                        num11 = num30;
                        jsonElement2 = jsonElement6;
                        kSerializerArr2 = kSerializerArr;
                        jsonElement6 = jsonElement2;
                        str34 = str11;
                        str33 = str10;
                        l12 = l4;
                        l11 = l3;
                        num30 = num11;
                        num27 = num8;
                        num28 = num9;
                        num29 = num10;
                        break;
                    case 10:
                        kSerializerArr = kSerializerArr2;
                        jsonElement4 = jsonElement6;
                        str12 = str28;
                        num17 = num29;
                        l3 = l11;
                        l8 = l12;
                        str10 = str33;
                        str11 = str34;
                        draftMessageModel2 = draftMessageModel6;
                        iDecodeIntElement8 = compositeDecoderBeginStructure.decodeIntElement(serialDescriptor, 10);
                        i12 = i17 | 1024;
                        Unit unit12 = Unit.INSTANCE;
                        int i222 = i12;
                        num16 = num17;
                        i11 = i222;
                        iDecodeIntElement2 = i18;
                        num10 = num16;
                        jsonElement6 = jsonElement4;
                        num8 = num27;
                        i18 = iDecodeIntElement2;
                        num9 = num28;
                        str16 = str29;
                        str13 = str32;
                        str17 = str27;
                        str14 = str31;
                        num13 = num25;
                        str15 = str30;
                        l5 = l8;
                        num12 = num26;
                        list3 = list7;
                        i7 = i11;
                        l4 = l5;
                        str28 = str12;
                        num25 = num13;
                        str27 = str17;
                        str29 = str16;
                        i17 = i7;
                        list7 = list3;
                        num26 = num12;
                        str30 = str15;
                        str31 = str14;
                        str32 = str13;
                        draftMessageModel5 = draftMessageModel2;
                        num11 = num30;
                        jsonElement2 = jsonElement6;
                        kSerializerArr2 = kSerializerArr;
                        jsonElement6 = jsonElement2;
                        str34 = str11;
                        str33 = str10;
                        l12 = l4;
                        l11 = l3;
                        num30 = num11;
                        num27 = num8;
                        num28 = num9;
                        num29 = num10;
                        break;
                    case 11:
                        kSerializerArr = kSerializerArr2;
                        jsonElement4 = jsonElement6;
                        str12 = str28;
                        l8 = l12;
                        str10 = str33;
                        str11 = str34;
                        draftMessageModel2 = draftMessageModel6;
                        l3 = l11;
                        Integer num35 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 11, IntSerializer.INSTANCE, num29);
                        i11 = i17 | 2048;
                        Unit unit13 = Unit.INSTANCE;
                        num16 = num35;
                        iDecodeIntElement2 = i18;
                        num10 = num16;
                        jsonElement6 = jsonElement4;
                        num8 = num27;
                        i18 = iDecodeIntElement2;
                        num9 = num28;
                        str16 = str29;
                        str13 = str32;
                        str17 = str27;
                        str14 = str31;
                        num13 = num25;
                        str15 = str30;
                        l5 = l8;
                        num12 = num26;
                        list3 = list7;
                        i7 = i11;
                        l4 = l5;
                        str28 = str12;
                        num25 = num13;
                        str27 = str17;
                        str29 = str16;
                        i17 = i7;
                        list7 = list3;
                        num26 = num12;
                        str30 = str15;
                        str31 = str14;
                        str32 = str13;
                        draftMessageModel5 = draftMessageModel2;
                        num11 = num30;
                        jsonElement2 = jsonElement6;
                        kSerializerArr2 = kSerializerArr;
                        jsonElement6 = jsonElement2;
                        str34 = str11;
                        str33 = str10;
                        l12 = l4;
                        l11 = l3;
                        num30 = num11;
                        num27 = num8;
                        num28 = num9;
                        num29 = num10;
                        break;
                    case 12:
                        kSerializerArr = kSerializerArr2;
                        jsonElement3 = jsonElement6;
                        str12 = str28;
                        str10 = str33;
                        str11 = str34;
                        draftMessageModel2 = draftMessageModel6;
                        l7 = l12;
                        Long l13 = (Long) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 12, LongSerializer.INSTANCE, l11);
                        i10 = i17 | 4096;
                        Unit unit14 = Unit.INSTANCE;
                        l3 = l13;
                        str16 = str29;
                        num8 = num27;
                        num9 = num28;
                        num10 = num29;
                        str17 = str27;
                        num13 = num25;
                        l5 = l7;
                        List list8222 = list7;
                        i7 = i10;
                        jsonElement6 = jsonElement3;
                        str13 = str32;
                        str14 = str31;
                        str15 = str30;
                        num12 = num26;
                        list3 = list8222;
                        l4 = l5;
                        str28 = str12;
                        num25 = num13;
                        str27 = str17;
                        str29 = str16;
                        i17 = i7;
                        list7 = list3;
                        num26 = num12;
                        str30 = str15;
                        str31 = str14;
                        str32 = str13;
                        draftMessageModel5 = draftMessageModel2;
                        num11 = num30;
                        jsonElement2 = jsonElement6;
                        kSerializerArr2 = kSerializerArr;
                        jsonElement6 = jsonElement2;
                        str34 = str11;
                        str33 = str10;
                        l12 = l4;
                        l11 = l3;
                        num30 = num11;
                        num27 = num8;
                        num28 = num9;
                        num29 = num10;
                        break;
                    case 13:
                        kSerializerArr = kSerializerArr2;
                        JsonElement jsonElement8 = jsonElement6;
                        str12 = str28;
                        str11 = str34;
                        draftMessageModel2 = draftMessageModel6;
                        str10 = str33;
                        Long l14 = (Long) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 13, LongSerializer.INSTANCE, l12);
                        i11 = i17 | 8192;
                        Unit unit15 = Unit.INSTANCE;
                        str16 = str29;
                        num8 = num27;
                        num9 = num28;
                        num10 = num29;
                        l3 = l11;
                        str17 = str27;
                        num13 = num25;
                        l5 = l14;
                        jsonElement6 = jsonElement8;
                        str13 = str32;
                        str14 = str31;
                        str15 = str30;
                        num12 = num26;
                        list3 = list7;
                        i7 = i11;
                        l4 = l5;
                        str28 = str12;
                        num25 = num13;
                        str27 = str17;
                        str29 = str16;
                        i17 = i7;
                        list7 = list3;
                        num26 = num12;
                        str30 = str15;
                        str31 = str14;
                        str32 = str13;
                        draftMessageModel5 = draftMessageModel2;
                        num11 = num30;
                        jsonElement2 = jsonElement6;
                        kSerializerArr2 = kSerializerArr;
                        jsonElement6 = jsonElement2;
                        str34 = str11;
                        str33 = str10;
                        l12 = l4;
                        l11 = l3;
                        num30 = num11;
                        num27 = num8;
                        num28 = num9;
                        num29 = num10;
                        break;
                    case 14:
                        kSerializerArr = kSerializerArr2;
                        jsonElement3 = jsonElement6;
                        str12 = str28;
                        draftMessageModel2 = draftMessageModel6;
                        str11 = str34;
                        String str37 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 14, StringSerializer.INSTANCE, str33);
                        i10 = i17 | 16384;
                        Unit unit16 = Unit.INSTANCE;
                        str10 = str37;
                        str16 = str29;
                        num8 = num27;
                        num9 = num28;
                        num10 = num29;
                        l3 = l11;
                        str17 = str27;
                        num13 = num25;
                        l5 = l12;
                        List list82222 = list7;
                        i7 = i10;
                        jsonElement6 = jsonElement3;
                        str13 = str32;
                        str14 = str31;
                        str15 = str30;
                        num12 = num26;
                        list3 = list82222;
                        l4 = l5;
                        str28 = str12;
                        num25 = num13;
                        str27 = str17;
                        str29 = str16;
                        i17 = i7;
                        list7 = list3;
                        num26 = num12;
                        str30 = str15;
                        str31 = str14;
                        str32 = str13;
                        draftMessageModel5 = draftMessageModel2;
                        num11 = num30;
                        jsonElement2 = jsonElement6;
                        kSerializerArr2 = kSerializerArr;
                        jsonElement6 = jsonElement2;
                        str34 = str11;
                        str33 = str10;
                        l12 = l4;
                        l11 = l3;
                        num30 = num11;
                        num27 = num8;
                        num28 = num9;
                        num29 = num10;
                        break;
                    case 15:
                        kSerializerArr = kSerializerArr2;
                        jsonElement3 = jsonElement6;
                        str12 = str28;
                        draftMessageModel2 = draftMessageModel6;
                        String str38 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 15, StringSerializer.INSTANCE, str34);
                        i10 = 32768 | i17;
                        Unit unit17 = Unit.INSTANCE;
                        str16 = str29;
                        num8 = num27;
                        num9 = num28;
                        num10 = num29;
                        l3 = l11;
                        str10 = str33;
                        str11 = str38;
                        str17 = str27;
                        num13 = num25;
                        l5 = l12;
                        List list822222 = list7;
                        i7 = i10;
                        jsonElement6 = jsonElement3;
                        str13 = str32;
                        str14 = str31;
                        str15 = str30;
                        num12 = num26;
                        list3 = list822222;
                        l4 = l5;
                        str28 = str12;
                        num25 = num13;
                        str27 = str17;
                        str29 = str16;
                        i17 = i7;
                        list7 = list3;
                        num26 = num12;
                        str30 = str15;
                        str31 = str14;
                        str32 = str13;
                        draftMessageModel5 = draftMessageModel2;
                        num11 = num30;
                        jsonElement2 = jsonElement6;
                        kSerializerArr2 = kSerializerArr;
                        jsonElement6 = jsonElement2;
                        str34 = str11;
                        str33 = str10;
                        l12 = l4;
                        l11 = l3;
                        num30 = num11;
                        num27 = num8;
                        num28 = num9;
                        num29 = num10;
                        break;
                    case 16:
                        kSerializerArr = kSerializerArr2;
                        jsonElement5 = jsonElement6;
                        str12 = str28;
                        draftMessageModel3 = draftMessageModel6;
                        jDecodeLongElement2 = compositeDecoderBeginStructure.decodeLongElement(serialDescriptor, 16);
                        i13 = i17 | 65536;
                        Unit unit18 = Unit.INSTANCE;
                        draftMessageModel2 = draftMessageModel3;
                        jsonElement6 = jsonElement5;
                        num8 = num27;
                        num9 = num28;
                        num10 = num29;
                        l3 = l11;
                        str10 = str33;
                        str11 = str34;
                        str13 = str32;
                        str14 = str31;
                        str15 = str30;
                        num12 = num26;
                        list3 = list7;
                        i7 = i13;
                        str16 = str29;
                        str17 = str27;
                        num13 = num25;
                        l5 = l12;
                        l4 = l5;
                        str28 = str12;
                        num25 = num13;
                        str27 = str17;
                        str29 = str16;
                        i17 = i7;
                        list7 = list3;
                        num26 = num12;
                        str30 = str15;
                        str31 = str14;
                        str32 = str13;
                        draftMessageModel5 = draftMessageModel2;
                        num11 = num30;
                        jsonElement2 = jsonElement6;
                        kSerializerArr2 = kSerializerArr;
                        jsonElement6 = jsonElement2;
                        str34 = str11;
                        str33 = str10;
                        l12 = l4;
                        l11 = l3;
                        num30 = num11;
                        num27 = num8;
                        num28 = num9;
                        num29 = num10;
                        break;
                    case 17:
                        kSerializerArr = kSerializerArr2;
                        str12 = str28;
                        jsonElement5 = jsonElement6;
                        draftMessageModel3 = (DraftMessageModel) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 17, DraftMessageModel$$serializer.INSTANCE, draftMessageModel6);
                        int i23 = 131072 | i17;
                        Unit unit19 = Unit.INSTANCE;
                        i13 = i23;
                        draftMessageModel2 = draftMessageModel3;
                        jsonElement6 = jsonElement5;
                        num8 = num27;
                        num9 = num28;
                        num10 = num29;
                        l3 = l11;
                        str10 = str33;
                        str11 = str34;
                        str13 = str32;
                        str14 = str31;
                        str15 = str30;
                        num12 = num26;
                        list3 = list7;
                        i7 = i13;
                        str16 = str29;
                        str17 = str27;
                        num13 = num25;
                        l5 = l12;
                        l4 = l5;
                        str28 = str12;
                        num25 = num13;
                        str27 = str17;
                        str29 = str16;
                        i17 = i7;
                        list7 = list3;
                        num26 = num12;
                        str30 = str15;
                        str31 = str14;
                        str32 = str13;
                        draftMessageModel5 = draftMessageModel2;
                        num11 = num30;
                        jsonElement2 = jsonElement6;
                        kSerializerArr2 = kSerializerArr;
                        jsonElement6 = jsonElement2;
                        str34 = str11;
                        str33 = str10;
                        l12 = l4;
                        l11 = l3;
                        num30 = num11;
                        num27 = num8;
                        num28 = num9;
                        num29 = num10;
                        break;
                    case 18:
                        kSerializerArr = kSerializerArr2;
                        String str39 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 18, StringSerializer.INSTANCE, str28);
                        int i24 = 262144 | i17;
                        Unit unit20 = Unit.INSTANCE;
                        str16 = str29;
                        str13 = str32;
                        num8 = num27;
                        num9 = num28;
                        num10 = num29;
                        l3 = l11;
                        str10 = str33;
                        str11 = str34;
                        draftMessageModel2 = draftMessageModel6;
                        str17 = str27;
                        str14 = str31;
                        num13 = num25;
                        str15 = str30;
                        l5 = l12;
                        num12 = num26;
                        list3 = list7;
                        i7 = i24;
                        str12 = str39;
                        l4 = l5;
                        str28 = str12;
                        num25 = num13;
                        str27 = str17;
                        str29 = str16;
                        i17 = i7;
                        list7 = list3;
                        num26 = num12;
                        str30 = str15;
                        str31 = str14;
                        str32 = str13;
                        draftMessageModel5 = draftMessageModel2;
                        num11 = num30;
                        jsonElement2 = jsonElement6;
                        kSerializerArr2 = kSerializerArr;
                        jsonElement6 = jsonElement2;
                        str34 = str11;
                        str33 = str10;
                        l12 = l4;
                        l11 = l3;
                        num30 = num11;
                        num27 = num8;
                        num28 = num9;
                        num29 = num10;
                        break;
                    case 19:
                        str18 = str28;
                        num25 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 19, IntSerializer.INSTANCE, num25);
                        i14 = 524288;
                        i16 = i17 | i14;
                        Unit unit21 = Unit.INSTANCE;
                        kSerializerArr = kSerializerArr2;
                        str16 = str29;
                        str13 = str32;
                        num8 = num27;
                        num9 = num28;
                        num10 = num29;
                        l3 = l11;
                        str10 = str33;
                        str11 = str34;
                        draftMessageModel2 = draftMessageModel6;
                        str17 = str27;
                        str14 = str31;
                        num13 = num25;
                        str15 = str30;
                        l5 = l12;
                        num12 = num26;
                        list3 = list7;
                        i7 = i16;
                        str12 = str18;
                        l4 = l5;
                        str28 = str12;
                        num25 = num13;
                        str27 = str17;
                        str29 = str16;
                        i17 = i7;
                        list7 = list3;
                        num26 = num12;
                        str30 = str15;
                        str31 = str14;
                        str32 = str13;
                        draftMessageModel5 = draftMessageModel2;
                        num11 = num30;
                        jsonElement2 = jsonElement6;
                        kSerializerArr2 = kSerializerArr;
                        jsonElement6 = jsonElement2;
                        str34 = str11;
                        str33 = str10;
                        l12 = l4;
                        l11 = l3;
                        num30 = num11;
                        num27 = num8;
                        num28 = num9;
                        num29 = num10;
                        break;
                    case 20:
                        str18 = str28;
                        str32 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 20, StringSerializer.INSTANCE, str32);
                        i14 = 1048576;
                        i16 = i17 | i14;
                        Unit unit212 = Unit.INSTANCE;
                        kSerializerArr = kSerializerArr2;
                        str16 = str29;
                        str13 = str32;
                        num8 = num27;
                        num9 = num28;
                        num10 = num29;
                        l3 = l11;
                        str10 = str33;
                        str11 = str34;
                        draftMessageModel2 = draftMessageModel6;
                        str17 = str27;
                        str14 = str31;
                        num13 = num25;
                        str15 = str30;
                        l5 = l12;
                        num12 = num26;
                        list3 = list7;
                        i7 = i16;
                        str12 = str18;
                        l4 = l5;
                        str28 = str12;
                        num25 = num13;
                        str27 = str17;
                        str29 = str16;
                        i17 = i7;
                        list7 = list3;
                        num26 = num12;
                        str30 = str15;
                        str31 = str14;
                        str32 = str13;
                        draftMessageModel5 = draftMessageModel2;
                        num11 = num30;
                        jsonElement2 = jsonElement6;
                        kSerializerArr2 = kSerializerArr;
                        jsonElement6 = jsonElement2;
                        str34 = str11;
                        str33 = str10;
                        l12 = l4;
                        l11 = l3;
                        num30 = num11;
                        num27 = num8;
                        num28 = num9;
                        num29 = num10;
                        break;
                    case 21:
                        str18 = str28;
                        str30 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 21, StringSerializer.INSTANCE, str30);
                        i14 = 2097152;
                        i16 = i17 | i14;
                        Unit unit2122 = Unit.INSTANCE;
                        kSerializerArr = kSerializerArr2;
                        str16 = str29;
                        str13 = str32;
                        num8 = num27;
                        num9 = num28;
                        num10 = num29;
                        l3 = l11;
                        str10 = str33;
                        str11 = str34;
                        draftMessageModel2 = draftMessageModel6;
                        str17 = str27;
                        str14 = str31;
                        num13 = num25;
                        str15 = str30;
                        l5 = l12;
                        num12 = num26;
                        list3 = list7;
                        i7 = i16;
                        str12 = str18;
                        l4 = l5;
                        str28 = str12;
                        num25 = num13;
                        str27 = str17;
                        str29 = str16;
                        i17 = i7;
                        list7 = list3;
                        num26 = num12;
                        str30 = str15;
                        str31 = str14;
                        str32 = str13;
                        draftMessageModel5 = draftMessageModel2;
                        num11 = num30;
                        jsonElement2 = jsonElement6;
                        kSerializerArr2 = kSerializerArr;
                        jsonElement6 = jsonElement2;
                        str34 = str11;
                        str33 = str10;
                        l12 = l4;
                        l11 = l3;
                        num30 = num11;
                        num27 = num8;
                        num28 = num9;
                        num29 = num10;
                        break;
                    case 22:
                        str18 = str28;
                        str31 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 22, StringSerializer.INSTANCE, str31);
                        i14 = 4194304;
                        i16 = i17 | i14;
                        Unit unit21222 = Unit.INSTANCE;
                        kSerializerArr = kSerializerArr2;
                        str16 = str29;
                        str13 = str32;
                        num8 = num27;
                        num9 = num28;
                        num10 = num29;
                        l3 = l11;
                        str10 = str33;
                        str11 = str34;
                        draftMessageModel2 = draftMessageModel6;
                        str17 = str27;
                        str14 = str31;
                        num13 = num25;
                        str15 = str30;
                        l5 = l12;
                        num12 = num26;
                        list3 = list7;
                        i7 = i16;
                        str12 = str18;
                        l4 = l5;
                        str28 = str12;
                        num25 = num13;
                        str27 = str17;
                        str29 = str16;
                        i17 = i7;
                        list7 = list3;
                        num26 = num12;
                        str30 = str15;
                        str31 = str14;
                        str32 = str13;
                        draftMessageModel5 = draftMessageModel2;
                        num11 = num30;
                        jsonElement2 = jsonElement6;
                        kSerializerArr2 = kSerializerArr;
                        jsonElement6 = jsonElement2;
                        str34 = str11;
                        str33 = str10;
                        l12 = l4;
                        l11 = l3;
                        num30 = num11;
                        num27 = num8;
                        num28 = num9;
                        num29 = num10;
                        break;
                    case 23:
                        str18 = str28;
                        str29 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 23, StringSerializer.INSTANCE, str29);
                        i14 = 8388608;
                        i16 = i17 | i14;
                        Unit unit212222 = Unit.INSTANCE;
                        kSerializerArr = kSerializerArr2;
                        str16 = str29;
                        str13 = str32;
                        num8 = num27;
                        num9 = num28;
                        num10 = num29;
                        l3 = l11;
                        str10 = str33;
                        str11 = str34;
                        draftMessageModel2 = draftMessageModel6;
                        str17 = str27;
                        str14 = str31;
                        num13 = num25;
                        str15 = str30;
                        l5 = l12;
                        num12 = num26;
                        list3 = list7;
                        i7 = i16;
                        str12 = str18;
                        l4 = l5;
                        str28 = str12;
                        num25 = num13;
                        str27 = str17;
                        str29 = str16;
                        i17 = i7;
                        list7 = list3;
                        num26 = num12;
                        str30 = str15;
                        str31 = str14;
                        str32 = str13;
                        draftMessageModel5 = draftMessageModel2;
                        num11 = num30;
                        jsonElement2 = jsonElement6;
                        kSerializerArr2 = kSerializerArr;
                        jsonElement6 = jsonElement2;
                        str34 = str11;
                        str33 = str10;
                        l12 = l4;
                        l11 = l3;
                        num30 = num11;
                        num27 = num8;
                        num28 = num9;
                        num29 = num10;
                        break;
                    case 24:
                        str18 = str28;
                        str27 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 24, StringSerializer.INSTANCE, str27);
                        i14 = 16777216;
                        i16 = i17 | i14;
                        Unit unit2122222 = Unit.INSTANCE;
                        kSerializerArr = kSerializerArr2;
                        str16 = str29;
                        str13 = str32;
                        num8 = num27;
                        num9 = num28;
                        num10 = num29;
                        l3 = l11;
                        str10 = str33;
                        str11 = str34;
                        draftMessageModel2 = draftMessageModel6;
                        str17 = str27;
                        str14 = str31;
                        num13 = num25;
                        str15 = str30;
                        l5 = l12;
                        num12 = num26;
                        list3 = list7;
                        i7 = i16;
                        str12 = str18;
                        l4 = l5;
                        str28 = str12;
                        num25 = num13;
                        str27 = str17;
                        str29 = str16;
                        i17 = i7;
                        list7 = list3;
                        num26 = num12;
                        str30 = str15;
                        str31 = str14;
                        str32 = str13;
                        draftMessageModel5 = draftMessageModel2;
                        num11 = num30;
                        jsonElement2 = jsonElement6;
                        kSerializerArr2 = kSerializerArr;
                        jsonElement6 = jsonElement2;
                        str34 = str11;
                        str33 = str10;
                        l12 = l4;
                        l11 = l3;
                        num30 = num11;
                        num27 = num8;
                        num28 = num9;
                        num29 = num10;
                        break;
                    case 25:
                        str18 = str28;
                        list7 = (List) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 25, kSerializerArr2[25], list7);
                        i15 = MediaHttpDownloader.MAXIMUM_CHUNK_SIZE;
                        i16 = i15 | i17;
                        Unit unit22 = Unit.INSTANCE;
                        kSerializerArr = kSerializerArr2;
                        str16 = str29;
                        str13 = str32;
                        num8 = num27;
                        num9 = num28;
                        num10 = num29;
                        l3 = l11;
                        str10 = str33;
                        str11 = str34;
                        draftMessageModel2 = draftMessageModel6;
                        str17 = str27;
                        str14 = str31;
                        num13 = num25;
                        str15 = str30;
                        l5 = l12;
                        num12 = num26;
                        list3 = list7;
                        i7 = i16;
                        str12 = str18;
                        l4 = l5;
                        str28 = str12;
                        num25 = num13;
                        str27 = str17;
                        str29 = str16;
                        i17 = i7;
                        list7 = list3;
                        num26 = num12;
                        str30 = str15;
                        str31 = str14;
                        str32 = str13;
                        draftMessageModel5 = draftMessageModel2;
                        num11 = num30;
                        jsonElement2 = jsonElement6;
                        kSerializerArr2 = kSerializerArr;
                        jsonElement6 = jsonElement2;
                        str34 = str11;
                        str33 = str10;
                        l12 = l4;
                        l11 = l3;
                        num30 = num11;
                        num27 = num8;
                        num28 = num9;
                        num29 = num10;
                        break;
                    case 26:
                        str18 = str28;
                        num26 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 26, IntSerializer.INSTANCE, num26);
                        i14 = 67108864;
                        i16 = i17 | i14;
                        Unit unit21222222 = Unit.INSTANCE;
                        kSerializerArr = kSerializerArr2;
                        str16 = str29;
                        str13 = str32;
                        num8 = num27;
                        num9 = num28;
                        num10 = num29;
                        l3 = l11;
                        str10 = str33;
                        str11 = str34;
                        draftMessageModel2 = draftMessageModel6;
                        str17 = str27;
                        str14 = str31;
                        num13 = num25;
                        str15 = str30;
                        l5 = l12;
                        num12 = num26;
                        list3 = list7;
                        i7 = i16;
                        str12 = str18;
                        l4 = l5;
                        str28 = str12;
                        num25 = num13;
                        str27 = str17;
                        str29 = str16;
                        i17 = i7;
                        list7 = list3;
                        num26 = num12;
                        str30 = str15;
                        str31 = str14;
                        str32 = str13;
                        draftMessageModel5 = draftMessageModel2;
                        num11 = num30;
                        jsonElement2 = jsonElement6;
                        kSerializerArr2 = kSerializerArr;
                        jsonElement6 = jsonElement2;
                        str34 = str11;
                        str33 = str10;
                        l12 = l4;
                        l11 = l3;
                        num30 = num11;
                        num27 = num8;
                        num28 = num9;
                        num29 = num10;
                        break;
                    case 27:
                        str18 = str28;
                        list6 = (List) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 27, kSerializerArr2[27], list6);
                        i15 = 134217728;
                        i16 = i15 | i17;
                        Unit unit222 = Unit.INSTANCE;
                        kSerializerArr = kSerializerArr2;
                        str16 = str29;
                        str13 = str32;
                        num8 = num27;
                        num9 = num28;
                        num10 = num29;
                        l3 = l11;
                        str10 = str33;
                        str11 = str34;
                        draftMessageModel2 = draftMessageModel6;
                        str17 = str27;
                        str14 = str31;
                        num13 = num25;
                        str15 = str30;
                        l5 = l12;
                        num12 = num26;
                        list3 = list7;
                        i7 = i16;
                        str12 = str18;
                        l4 = l5;
                        str28 = str12;
                        num25 = num13;
                        str27 = str17;
                        str29 = str16;
                        i17 = i7;
                        list7 = list3;
                        num26 = num12;
                        str30 = str15;
                        str31 = str14;
                        str32 = str13;
                        draftMessageModel5 = draftMessageModel2;
                        num11 = num30;
                        jsonElement2 = jsonElement6;
                        kSerializerArr2 = kSerializerArr;
                        jsonElement6 = jsonElement2;
                        str34 = str11;
                        str33 = str10;
                        l12 = l4;
                        l11 = l3;
                        num30 = num11;
                        num27 = num8;
                        num28 = num9;
                        num29 = num10;
                        break;
                    case 28:
                        str18 = str28;
                        jsonElement6 = (JsonElement) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 28, JsonElementSerializer.INSTANCE, jsonElement6);
                        i14 = 268435456;
                        i16 = i17 | i14;
                        Unit unit212222222 = Unit.INSTANCE;
                        kSerializerArr = kSerializerArr2;
                        str16 = str29;
                        str13 = str32;
                        num8 = num27;
                        num9 = num28;
                        num10 = num29;
                        l3 = l11;
                        str10 = str33;
                        str11 = str34;
                        draftMessageModel2 = draftMessageModel6;
                        str17 = str27;
                        str14 = str31;
                        num13 = num25;
                        str15 = str30;
                        l5 = l12;
                        num12 = num26;
                        list3 = list7;
                        i7 = i16;
                        str12 = str18;
                        l4 = l5;
                        str28 = str12;
                        num25 = num13;
                        str27 = str17;
                        str29 = str16;
                        i17 = i7;
                        list7 = list3;
                        num26 = num12;
                        str30 = str15;
                        str31 = str14;
                        str32 = str13;
                        draftMessageModel5 = draftMessageModel2;
                        num11 = num30;
                        jsonElement2 = jsonElement6;
                        kSerializerArr2 = kSerializerArr;
                        jsonElement6 = jsonElement2;
                        str34 = str11;
                        str33 = str10;
                        l12 = l4;
                        l11 = l3;
                        num30 = num11;
                        num27 = num8;
                        num28 = num9;
                        num29 = num10;
                        break;
                    default:
                        throw new UnknownFieldException(iDecodeElementIndex);
                }
            }
            Integer num36 = num27;
            Integer num37 = num28;
            l = l12;
            num = num25;
            str = str27;
            str2 = str29;
            i = i17;
            list = list7;
            str3 = str31;
            str4 = str32;
            jsonElement = jsonElement6;
            str5 = str34;
            l2 = l11;
            num2 = num36;
            num3 = num37;
            num4 = num29;
            str6 = str35;
            i2 = iDecodeIntElement9;
            i3 = iDecodeIntElement10;
            iDecodeIntElement = iDecodeIntElement11;
            num5 = num31;
            str7 = str28;
            str8 = str30;
            draftMessageModel = draftMessageModel5;
            str9 = str33;
            num6 = num30;
            i4 = i18;
            i5 = iDecodeIntElement8;
            j = jDecodeLongElement2;
            num7 = num26;
            i6 = i19;
            list2 = list6;
        }
        compositeDecoderBeginStructure.endStructure(serialDescriptor);
        return new InHouseIMConversationEntity(i, str6, num5, i6, num6, num2, iDecodeIntElement, i3, num3, i4, i2, i5, num4, l2, l, str9, str5, j, draftMessageModel, str7, num, str4, str8, str3, str2, str, list, num7, list2, jsonElement, (SerializationConstructorMarker) null);
    }

    /* JADX DEBUG: Method merged with bridge method: serialize(Lkotlinx/serialization/encoding/Encoder;Ljava/lang/Object;)V */
    @Override // kotlinx.serialization.SerializationStrategy
    public final void serialize(@NotNull Encoder encoder, @NotNull InHouseIMConversationEntity inHouseIMConversationEntity) {
        Intrinsics.checkNotNullParameter(encoder, "");
        Intrinsics.checkNotNullParameter(inHouseIMConversationEntity, "");
        SerialDescriptor serialDescriptor = descriptor;
        CompositeEncoder compositeEncoderBeginStructure = encoder.beginStructure(serialDescriptor);
        InHouseIMConversationEntity.write$Self$OKIMCore_okimcore(inHouseIMConversationEntity, compositeEncoderBeginStructure, serialDescriptor);
        compositeEncoderBeginStructure.endStructure(serialDescriptor);
    }
}
