package com.okinc.business.defi.biz.core.transaction.bean;

import com.google.api.client.googleapis.media.MediaHttpDownloader;
import com.okinc.business.defi.biz.net.bean.UserOperation;
import com.okinc.business.defi.biz.net.bean.UserOperation$$serializer;
import java.util.List;
import kotlin.Unit;
import kotlin.jvm.internal.Intrinsics;
import kotlinx.serialization.KSerializer;
import kotlinx.serialization.UnknownFieldException;
import kotlinx.serialization.builtins.BuiltinSerializersKt;
import kotlinx.serialization.descriptors.SerialDescriptor;
import kotlinx.serialization.encoding.CompositeDecoder;
import kotlinx.serialization.encoding.CompositeEncoder;
import kotlinx.serialization.encoding.Decoder;
import kotlinx.serialization.encoding.Encoder;
import kotlinx.serialization.internal.BooleanSerializer;
import kotlinx.serialization.internal.GeneratedSerializer;
import kotlinx.serialization.internal.IntSerializer;
import kotlinx.serialization.internal.LongSerializer;
import kotlinx.serialization.internal.PluginGeneratedSerialDescriptor;
import kotlinx.serialization.internal.SerializationConstructorMarker;
import kotlinx.serialization.internal.StringSerializer;
import org.jetbrains.annotations.NotNull;

/* JADX INFO: loaded from: classes3.dex */
public final /* synthetic */ class BroadcastBean$$serializer implements GeneratedSerializer<BroadcastBean> {
    public static final int $stable;
    public static final BroadcastBean$$serializer INSTANCE;
    private static final SerialDescriptor descriptor;

    /* JADX DEBUG: Don't trust debug lines info. Lines numbers was adjusted: min line is 0 */
    private BroadcastBean$$serializer() {
    }

    /* JADX DEBUG: Don't trust debug lines info. Lines numbers was adjusted: min line is 0 */
    @Override // kotlinx.serialization.KSerializer, kotlinx.serialization.SerializationStrategy, kotlinx.serialization.DeserializationStrategy
    public final SerialDescriptor getDescriptor() {
        return descriptor;
    }

    static {
        BroadcastBean$$serializer broadcastBean$$serializer = new BroadcastBean$$serializer();
        INSTANCE = broadcastBean$$serializer;
        $stable = 8;
        PluginGeneratedSerialDescriptor pluginGeneratedSerialDescriptor = new PluginGeneratedSerialDescriptor("com.okinc.business.defi.biz.core.transaction.bean.BroadcastBean", broadcastBean$$serializer, 35);
        pluginGeneratedSerialDescriptor.addElement("accountId", false);
        pluginGeneratedSerialDescriptor.addElement("walletType", false);
        pluginGeneratedSerialDescriptor.addElement("signedTx", false);
        pluginGeneratedSerialDescriptor.addElement("txHash", false);
        pluginGeneratedSerialDescriptor.addElement("fromAdr", false);
        pluginGeneratedSerialDescriptor.addElement("toAdr", false);
        pluginGeneratedSerialDescriptor.addElement("coinId", false);
        pluginGeneratedSerialDescriptor.addElement("coinAmount", false);
        pluginGeneratedSerialDescriptor.addElement("serviceCharge", false);
        pluginGeneratedSerialDescriptor.addElement("txSource", false);
        pluginGeneratedSerialDescriptor.addElement("itemId", false);
        pluginGeneratedSerialDescriptor.addElement("extJson", false);
        pluginGeneratedSerialDescriptor.addElement("txType", true);
        pluginGeneratedSerialDescriptor.addElement("inputData", true);
        pluginGeneratedSerialDescriptor.addElement("domain", true);
        pluginGeneratedSerialDescriptor.addElement("memo", true);
        pluginGeneratedSerialDescriptor.addElement("dependTx", true);
        pluginGeneratedSerialDescriptor.addElement("uop", true);
        pluginGeneratedSerialDescriptor.addElement("aaFeeToken", true);
        pluginGeneratedSerialDescriptor.addElement("mevSuppliers", true);
        pluginGeneratedSerialDescriptor.addElement("feeRate", true);
        pluginGeneratedSerialDescriptor.addElement("approvalForAllList", true);
        pluginGeneratedSerialDescriptor.addElement("signRawData", true);
        pluginGeneratedSerialDescriptor.addElement("originData", true);
        pluginGeneratedSerialDescriptor.addElement("approvalAddress", true);
        pluginGeneratedSerialDescriptor.addElement("activityId", true);
        pluginGeneratedSerialDescriptor.addElement("dapp", true);
        pluginGeneratedSerialDescriptor.addElement("sendCallsParams", true);
        pluginGeneratedSerialDescriptor.addElement("nonce", true);
        pluginGeneratedSerialDescriptor.addElement("signedTxWithoutJito", true);
        pluginGeneratedSerialDescriptor.addElement("jitoHash", true);
        pluginGeneratedSerialDescriptor.addElement("jitoSignedTx", true);
        pluginGeneratedSerialDescriptor.addElement("x402transfer", true);
        pluginGeneratedSerialDescriptor.addElement("signType", true);
        pluginGeneratedSerialDescriptor.addElement("uopHash", true);
        descriptor = pluginGeneratedSerialDescriptor;
    }

    @Override // kotlinx.serialization.internal.GeneratedSerializer
    public final KSerializer<?>[] childSerializers() {
        KSerializer[] kSerializerArr = BroadcastBean.$childSerializers;
        StringSerializer stringSerializer = StringSerializer.INSTANCE;
        IntSerializer intSerializer = IntSerializer.INSTANCE;
        return new KSerializer[]{stringSerializer, intSerializer, stringSerializer, BuiltinSerializersKt.getNullable(stringSerializer), stringSerializer, stringSerializer, LongSerializer.INSTANCE, stringSerializer, stringSerializer, intSerializer, stringSerializer, stringSerializer, BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(kSerializerArr[16]), BuiltinSerializersKt.getNullable(UserOperation$$serializer.INSTANCE), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(kSerializerArr[19]), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(kSerializerArr[21]), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(intSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(EVM5792SendCallsParams$$serializer.INSTANCE), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(BooleanSerializer.INSTANCE), BuiltinSerializersKt.getNullable(intSerializer), BuiltinSerializersKt.getNullable(stringSerializer)};
    }

    /* JADX DEBUG: Method merged with bridge method: deserialize(Lkotlinx/serialization/encoding/Decoder;)Ljava/lang/Object; */
    @Override // kotlinx.serialization.DeserializationStrategy
    public final BroadcastBean deserialize(@NotNull Decoder decoder) {
        UserOperation userOperation;
        String str;
        String str2;
        String str3;
        String str4;
        List list;
        String str5;
        String str6;
        String str7;
        String str8;
        String str9;
        int i;
        String str10;
        List list2;
        List list3;
        Integer num;
        String str11;
        String str12;
        String str13;
        String str14;
        String str15;
        int i2;
        String str16;
        String str17;
        EVM5792SendCallsParams eVM5792SendCallsParams;
        int i3;
        Integer num2;
        String str18;
        String str19;
        Boolean bool;
        String str20;
        String str21;
        String str22;
        String str23;
        long j;
        int i4;
        String str24;
        String str25;
        EVM5792SendCallsParams eVM5792SendCallsParams2;
        String str26;
        String str27;
        String str28;
        List list4;
        String str29;
        String str30;
        String str31;
        String str32;
        UserOperation userOperation2;
        Integer num3;
        List list5;
        String str33;
        int i5;
        EVM5792SendCallsParams eVM5792SendCallsParams3;
        UserOperation userOperation3;
        String str34;
        int i6;
        EVM5792SendCallsParams eVM5792SendCallsParams4;
        int i7;
        Intrinsics.checkNotNullParameter(decoder, "");
        SerialDescriptor serialDescriptor = descriptor;
        CompositeDecoder compositeDecoderBeginStructure = decoder.beginStructure(serialDescriptor);
        KSerializer[] kSerializerArr = BroadcastBean.$childSerializers;
        String str35 = null;
        if (compositeDecoderBeginStructure.decodeSequentially()) {
            String strDecodeStringElement = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 0);
            int iDecodeIntElement = compositeDecoderBeginStructure.decodeIntElement(serialDescriptor, 1);
            String strDecodeStringElement2 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 2);
            StringSerializer stringSerializer = StringSerializer.INSTANCE;
            String str36 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 3, stringSerializer, null);
            String strDecodeStringElement3 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 4);
            String strDecodeStringElement4 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 5);
            long jDecodeLongElement = compositeDecoderBeginStructure.decodeLongElement(serialDescriptor, 6);
            String strDecodeStringElement5 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 7);
            String strDecodeStringElement6 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 8);
            int iDecodeIntElement2 = compositeDecoderBeginStructure.decodeIntElement(serialDescriptor, 9);
            String strDecodeStringElement7 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 10);
            String strDecodeStringElement8 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 11);
            String str37 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 12, stringSerializer, null);
            String str38 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 13, stringSerializer, null);
            String str39 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 14, stringSerializer, null);
            String str40 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 15, stringSerializer, null);
            List list6 = (List) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 16, kSerializerArr[16], null);
            UserOperation userOperation4 = (UserOperation) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 17, UserOperation$$serializer.INSTANCE, null);
            String str41 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 18, stringSerializer, null);
            List list7 = (List) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 19, kSerializerArr[19], null);
            String str42 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 20, stringSerializer, null);
            List list8 = (List) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 21, kSerializerArr[21], null);
            String str43 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 22, stringSerializer, null);
            String str44 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 23, stringSerializer, null);
            String str45 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 24, stringSerializer, null);
            IntSerializer intSerializer = IntSerializer.INSTANCE;
            Integer num4 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 25, intSerializer, null);
            String str46 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 26, stringSerializer, null);
            EVM5792SendCallsParams eVM5792SendCallsParams5 = (EVM5792SendCallsParams) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 27, EVM5792SendCallsParams$$serializer.INSTANCE, null);
            String str47 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 28, stringSerializer, null);
            String str48 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 29, stringSerializer, null);
            String str49 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 30, stringSerializer, null);
            String str50 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 31, stringSerializer, null);
            Boolean bool2 = (Boolean) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 32, BooleanSerializer.INSTANCE, null);
            Integer num5 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 33, intSerializer, null);
            String str51 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 34, stringSerializer, null);
            i3 = -1;
            num = num5;
            bool = bool2;
            str4 = str51;
            list = list6;
            str20 = str49;
            str19 = str50;
            str2 = str47;
            i4 = 7;
            userOperation = userOperation4;
            eVM5792SendCallsParams = eVM5792SendCallsParams5;
            str3 = str48;
            num2 = num4;
            str18 = str46;
            str17 = str44;
            str16 = str43;
            list2 = list8;
            list3 = list7;
            str14 = strDecodeStringElement5;
            str21 = str41;
            str23 = strDecodeStringElement2;
            str13 = strDecodeStringElement6;
            str22 = strDecodeStringElement4;
            str24 = str36;
            str12 = strDecodeStringElement3;
            i = iDecodeIntElement;
            str11 = strDecodeStringElement7;
            str15 = strDecodeStringElement;
            str8 = str38;
            i2 = iDecodeIntElement2;
            str6 = str40;
            str7 = str39;
            j = jDecodeLongElement;
            str9 = str37;
            str10 = strDecodeStringElement8;
            str = str45;
            str5 = str42;
        } else {
            long jDecodeLongElement2 = 0;
            int i8 = 0;
            int i9 = 0;
            int iDecodeIntElement3 = 0;
            int i10 = 0;
            boolean z = true;
            String str52 = null;
            EVM5792SendCallsParams eVM5792SendCallsParams6 = null;
            Integer num6 = null;
            String str53 = null;
            Integer num7 = null;
            String str54 = null;
            String str55 = null;
            String str56 = null;
            String str57 = null;
            Boolean bool3 = null;
            String str58 = null;
            String str59 = null;
            String str60 = null;
            String str61 = null;
            List list9 = null;
            List list10 = null;
            String str62 = null;
            String str63 = null;
            List list11 = null;
            String str64 = null;
            String str65 = null;
            String str66 = null;
            String strDecodeStringElement9 = null;
            String strDecodeStringElement10 = null;
            String str67 = null;
            UserOperation userOperation5 = null;
            String strDecodeStringElement11 = null;
            String strDecodeStringElement12 = null;
            String strDecodeStringElement13 = null;
            String strDecodeStringElement14 = null;
            String strDecodeStringElement15 = null;
            while (z) {
                String str68 = str53;
                int iDecodeElementIndex = compositeDecoderBeginStructure.decodeElementIndex(serialDescriptor);
                switch (iDecodeElementIndex) {
                    case -1:
                        str25 = str52;
                        eVM5792SendCallsParams2 = eVM5792SendCallsParams6;
                        str26 = str61;
                        str27 = str62;
                        str28 = str63;
                        list4 = list11;
                        str29 = str64;
                        str30 = str65;
                        str31 = str66;
                        str32 = str67;
                        userOperation2 = userOperation5;
                        num3 = num6;
                        list5 = list9;
                        Unit unit = Unit.INSTANCE;
                        z = false;
                        str33 = str32;
                        i5 = i9;
                        i9 = i5;
                        userOperation5 = userOperation2;
                        str53 = str68;
                        eVM5792SendCallsParams6 = eVM5792SendCallsParams2;
                        list11 = list4;
                        str64 = str29;
                        str65 = str30;
                        str66 = str31;
                        str67 = str33;
                        str61 = str26;
                        list9 = list5;
                        num6 = num3;
                        str52 = str25;
                        str63 = str28;
                        str62 = str27;
                        break;
                    case 0:
                        str25 = str52;
                        eVM5792SendCallsParams2 = eVM5792SendCallsParams6;
                        str26 = str61;
                        str27 = str62;
                        str28 = str63;
                        list4 = list11;
                        str29 = str64;
                        str30 = str65;
                        str31 = str66;
                        str32 = str67;
                        userOperation2 = userOperation5;
                        num3 = num6;
                        list5 = list9;
                        strDecodeStringElement15 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 0);
                        i8 |= 1;
                        Unit unit2 = Unit.INSTANCE;
                        str33 = str32;
                        i5 = i9;
                        i9 = i5;
                        userOperation5 = userOperation2;
                        str53 = str68;
                        eVM5792SendCallsParams6 = eVM5792SendCallsParams2;
                        list11 = list4;
                        str64 = str29;
                        str65 = str30;
                        str66 = str31;
                        str67 = str33;
                        str61 = str26;
                        list9 = list5;
                        num6 = num3;
                        str52 = str25;
                        str63 = str28;
                        str62 = str27;
                        break;
                    case 1:
                        str25 = str52;
                        eVM5792SendCallsParams2 = eVM5792SendCallsParams6;
                        str26 = str61;
                        str27 = str62;
                        str28 = str63;
                        list4 = list11;
                        str29 = str64;
                        str30 = str65;
                        str31 = str66;
                        userOperation2 = userOperation5;
                        num3 = num6;
                        list5 = list9;
                        int iDecodeIntElement4 = compositeDecoderBeginStructure.decodeIntElement(serialDescriptor, 1);
                        i8 |= 2;
                        Unit unit3 = Unit.INSTANCE;
                        str33 = str67;
                        i5 = iDecodeIntElement4;
                        i9 = i5;
                        userOperation5 = userOperation2;
                        str53 = str68;
                        eVM5792SendCallsParams6 = eVM5792SendCallsParams2;
                        list11 = list4;
                        str64 = str29;
                        str65 = str30;
                        str66 = str31;
                        str67 = str33;
                        str61 = str26;
                        list9 = list5;
                        num6 = num3;
                        str52 = str25;
                        str63 = str28;
                        str62 = str27;
                        break;
                    case 2:
                        str25 = str52;
                        eVM5792SendCallsParams2 = eVM5792SendCallsParams6;
                        str26 = str61;
                        str27 = str62;
                        str28 = str63;
                        list4 = list11;
                        str29 = str64;
                        str30 = str65;
                        str31 = str66;
                        userOperation2 = userOperation5;
                        num3 = num6;
                        list5 = list9;
                        strDecodeStringElement14 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 2);
                        i8 |= 4;
                        Unit unit4 = Unit.INSTANCE;
                        str33 = str67;
                        i5 = i9;
                        i9 = i5;
                        userOperation5 = userOperation2;
                        str53 = str68;
                        eVM5792SendCallsParams6 = eVM5792SendCallsParams2;
                        list11 = list4;
                        str64 = str29;
                        str65 = str30;
                        str66 = str31;
                        str67 = str33;
                        str61 = str26;
                        list9 = list5;
                        num6 = num3;
                        str52 = str25;
                        str63 = str28;
                        str62 = str27;
                        break;
                    case 3:
                        str25 = str52;
                        eVM5792SendCallsParams2 = eVM5792SendCallsParams6;
                        str27 = str62;
                        str28 = str63;
                        list4 = list11;
                        str29 = str64;
                        str30 = str65;
                        str31 = str66;
                        userOperation2 = userOperation5;
                        num3 = num6;
                        list5 = list9;
                        str26 = str61;
                        String str69 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 3, StringSerializer.INSTANCE, str67);
                        i8 |= 8;
                        Unit unit5 = Unit.INSTANCE;
                        i5 = i9;
                        str33 = str69;
                        i9 = i5;
                        userOperation5 = userOperation2;
                        str53 = str68;
                        eVM5792SendCallsParams6 = eVM5792SendCallsParams2;
                        list11 = list4;
                        str64 = str29;
                        str65 = str30;
                        str66 = str31;
                        str67 = str33;
                        str61 = str26;
                        list9 = list5;
                        num6 = num3;
                        str52 = str25;
                        str63 = str28;
                        str62 = str27;
                        break;
                    case 4:
                        str25 = str52;
                        eVM5792SendCallsParams3 = eVM5792SendCallsParams6;
                        str27 = str62;
                        str28 = str63;
                        list4 = list11;
                        str29 = str64;
                        str30 = str65;
                        str31 = str66;
                        userOperation3 = userOperation5;
                        num3 = num6;
                        str34 = str61;
                        list5 = list9;
                        strDecodeStringElement10 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 4);
                        i8 |= 16;
                        Unit unit6 = Unit.INSTANCE;
                        userOperation5 = userOperation3;
                        str26 = str34;
                        str33 = str67;
                        str53 = str68;
                        eVM5792SendCallsParams6 = eVM5792SendCallsParams3;
                        list11 = list4;
                        str64 = str29;
                        str65 = str30;
                        str66 = str31;
                        str67 = str33;
                        str61 = str26;
                        list9 = list5;
                        num6 = num3;
                        str52 = str25;
                        str63 = str28;
                        str62 = str27;
                        break;
                    case 5:
                        str25 = str52;
                        eVM5792SendCallsParams3 = eVM5792SendCallsParams6;
                        str27 = str62;
                        str28 = str63;
                        list4 = list11;
                        str29 = str64;
                        str30 = str65;
                        str31 = str66;
                        userOperation3 = userOperation5;
                        num3 = num6;
                        str34 = str61;
                        list5 = list9;
                        strDecodeStringElement13 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 5);
                        i8 |= 32;
                        Unit unit7 = Unit.INSTANCE;
                        userOperation5 = userOperation3;
                        str26 = str34;
                        str33 = str67;
                        str53 = str68;
                        eVM5792SendCallsParams6 = eVM5792SendCallsParams3;
                        list11 = list4;
                        str64 = str29;
                        str65 = str30;
                        str66 = str31;
                        str67 = str33;
                        str61 = str26;
                        list9 = list5;
                        num6 = num3;
                        str52 = str25;
                        str63 = str28;
                        str62 = str27;
                        break;
                    case 6:
                        str25 = str52;
                        eVM5792SendCallsParams3 = eVM5792SendCallsParams6;
                        str27 = str62;
                        str28 = str63;
                        list4 = list11;
                        str29 = str64;
                        str30 = str65;
                        str31 = str66;
                        userOperation3 = userOperation5;
                        num3 = num6;
                        str34 = str61;
                        list5 = list9;
                        jDecodeLongElement2 = compositeDecoderBeginStructure.decodeLongElement(serialDescriptor, 6);
                        i8 |= 64;
                        Unit unit72 = Unit.INSTANCE;
                        userOperation5 = userOperation3;
                        str26 = str34;
                        str33 = str67;
                        str53 = str68;
                        eVM5792SendCallsParams6 = eVM5792SendCallsParams3;
                        list11 = list4;
                        str64 = str29;
                        str65 = str30;
                        str66 = str31;
                        str67 = str33;
                        str61 = str26;
                        list9 = list5;
                        num6 = num3;
                        str52 = str25;
                        str63 = str28;
                        str62 = str27;
                        break;
                    case 7:
                        str25 = str52;
                        eVM5792SendCallsParams3 = eVM5792SendCallsParams6;
                        str27 = str62;
                        str28 = str63;
                        list4 = list11;
                        str29 = str64;
                        str30 = str65;
                        str31 = str66;
                        userOperation3 = userOperation5;
                        num3 = num6;
                        str34 = str61;
                        list5 = list9;
                        strDecodeStringElement12 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 7);
                        i8 |= 128;
                        Unit unit722 = Unit.INSTANCE;
                        userOperation5 = userOperation3;
                        str26 = str34;
                        str33 = str67;
                        str53 = str68;
                        eVM5792SendCallsParams6 = eVM5792SendCallsParams3;
                        list11 = list4;
                        str64 = str29;
                        str65 = str30;
                        str66 = str31;
                        str67 = str33;
                        str61 = str26;
                        list9 = list5;
                        num6 = num3;
                        str52 = str25;
                        str63 = str28;
                        str62 = str27;
                        break;
                    case 8:
                        str25 = str52;
                        eVM5792SendCallsParams3 = eVM5792SendCallsParams6;
                        str27 = str62;
                        str28 = str63;
                        list4 = list11;
                        str29 = str64;
                        str30 = str65;
                        str31 = str66;
                        userOperation3 = userOperation5;
                        num3 = num6;
                        str34 = str61;
                        list5 = list9;
                        strDecodeStringElement11 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 8);
                        i8 |= 256;
                        Unit unit7222 = Unit.INSTANCE;
                        userOperation5 = userOperation3;
                        str26 = str34;
                        str33 = str67;
                        str53 = str68;
                        eVM5792SendCallsParams6 = eVM5792SendCallsParams3;
                        list11 = list4;
                        str64 = str29;
                        str65 = str30;
                        str66 = str31;
                        str67 = str33;
                        str61 = str26;
                        list9 = list5;
                        num6 = num3;
                        str52 = str25;
                        str63 = str28;
                        str62 = str27;
                        break;
                    case 9:
                        str25 = str52;
                        eVM5792SendCallsParams3 = eVM5792SendCallsParams6;
                        str27 = str62;
                        str28 = str63;
                        list4 = list11;
                        str29 = str64;
                        str30 = str65;
                        str31 = str66;
                        userOperation3 = userOperation5;
                        num3 = num6;
                        str34 = str61;
                        list5 = list9;
                        iDecodeIntElement3 = compositeDecoderBeginStructure.decodeIntElement(serialDescriptor, 9);
                        i8 |= 512;
                        Unit unit72222 = Unit.INSTANCE;
                        userOperation5 = userOperation3;
                        str26 = str34;
                        str33 = str67;
                        str53 = str68;
                        eVM5792SendCallsParams6 = eVM5792SendCallsParams3;
                        list11 = list4;
                        str64 = str29;
                        str65 = str30;
                        str66 = str31;
                        str67 = str33;
                        str61 = str26;
                        list9 = list5;
                        num6 = num3;
                        str52 = str25;
                        str63 = str28;
                        str62 = str27;
                        break;
                    case 10:
                        str25 = str52;
                        eVM5792SendCallsParams3 = eVM5792SendCallsParams6;
                        str27 = str62;
                        str28 = str63;
                        list4 = list11;
                        str29 = str64;
                        str30 = str65;
                        str31 = str66;
                        userOperation3 = userOperation5;
                        num3 = num6;
                        str34 = str61;
                        list5 = list9;
                        strDecodeStringElement9 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 10);
                        i8 |= 1024;
                        Unit unit722222 = Unit.INSTANCE;
                        userOperation5 = userOperation3;
                        str26 = str34;
                        str33 = str67;
                        str53 = str68;
                        eVM5792SendCallsParams6 = eVM5792SendCallsParams3;
                        list11 = list4;
                        str64 = str29;
                        str65 = str30;
                        str66 = str31;
                        str67 = str33;
                        str61 = str26;
                        list9 = list5;
                        num6 = num3;
                        str52 = str25;
                        str63 = str28;
                        str62 = str27;
                        break;
                    case 11:
                        str25 = str52;
                        eVM5792SendCallsParams3 = eVM5792SendCallsParams6;
                        str27 = str62;
                        str28 = str63;
                        list4 = list11;
                        str29 = str64;
                        str30 = str65;
                        str31 = str66;
                        userOperation3 = userOperation5;
                        num3 = num6;
                        str34 = str61;
                        list5 = list9;
                        String strDecodeStringElement16 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 11);
                        i8 |= 2048;
                        Unit unit8 = Unit.INSTANCE;
                        str60 = strDecodeStringElement16;
                        userOperation5 = userOperation3;
                        str26 = str34;
                        str33 = str67;
                        str53 = str68;
                        eVM5792SendCallsParams6 = eVM5792SendCallsParams3;
                        list11 = list4;
                        str64 = str29;
                        str65 = str30;
                        str66 = str31;
                        str67 = str33;
                        str61 = str26;
                        list9 = list5;
                        num6 = num3;
                        str52 = str25;
                        str63 = str28;
                        str62 = str27;
                        break;
                    case 12:
                        str25 = str52;
                        eVM5792SendCallsParams3 = eVM5792SendCallsParams6;
                        str27 = str62;
                        str28 = str63;
                        list4 = list11;
                        str29 = str64;
                        str30 = str65;
                        userOperation3 = userOperation5;
                        num3 = num6;
                        list5 = list9;
                        str31 = str66;
                        String str70 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 12, StringSerializer.INSTANCE, str61);
                        i8 |= 4096;
                        Unit unit9 = Unit.INSTANCE;
                        str34 = str70;
                        userOperation5 = userOperation3;
                        str26 = str34;
                        str33 = str67;
                        str53 = str68;
                        eVM5792SendCallsParams6 = eVM5792SendCallsParams3;
                        list11 = list4;
                        str64 = str29;
                        str65 = str30;
                        str66 = str31;
                        str67 = str33;
                        str61 = str26;
                        list9 = list5;
                        num6 = num3;
                        str52 = str25;
                        str63 = str28;
                        str62 = str27;
                        break;
                    case 13:
                        str25 = str52;
                        eVM5792SendCallsParams3 = eVM5792SendCallsParams6;
                        str27 = str62;
                        str28 = str63;
                        list4 = list11;
                        str29 = str64;
                        num3 = num6;
                        list5 = list9;
                        str30 = str65;
                        str66 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 13, StringSerializer.INSTANCE, str66);
                        Unit unit10 = Unit.INSTANCE;
                        i8 |= 8192;
                        str34 = str61;
                        str31 = str66;
                        str26 = str34;
                        str33 = str67;
                        str53 = str68;
                        eVM5792SendCallsParams6 = eVM5792SendCallsParams3;
                        list11 = list4;
                        str64 = str29;
                        str65 = str30;
                        str66 = str31;
                        str67 = str33;
                        str61 = str26;
                        list9 = list5;
                        num6 = num3;
                        str52 = str25;
                        str63 = str28;
                        str62 = str27;
                        break;
                    case 14:
                        str25 = str52;
                        eVM5792SendCallsParams3 = eVM5792SendCallsParams6;
                        str27 = str62;
                        str28 = str63;
                        list4 = list11;
                        num3 = num6;
                        list5 = list9;
                        str29 = str64;
                        str65 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 14, StringSerializer.INSTANCE, str65);
                        int i11 = i8 | 16384;
                        Unit unit11 = Unit.INSTANCE;
                        i8 = i11;
                        str34 = str61;
                        str30 = str65;
                        str31 = str66;
                        str26 = str34;
                        str33 = str67;
                        str53 = str68;
                        eVM5792SendCallsParams6 = eVM5792SendCallsParams3;
                        list11 = list4;
                        str64 = str29;
                        str65 = str30;
                        str66 = str31;
                        str67 = str33;
                        str61 = str26;
                        list9 = list5;
                        num6 = num3;
                        str52 = str25;
                        str63 = str28;
                        str62 = str27;
                        break;
                    case 15:
                        str25 = str52;
                        eVM5792SendCallsParams3 = eVM5792SendCallsParams6;
                        str27 = str62;
                        str28 = str63;
                        num3 = num6;
                        list5 = list9;
                        list4 = list11;
                        str64 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 15, StringSerializer.INSTANCE, str64);
                        Unit unit12 = Unit.INSTANCE;
                        i8 = 32768 | i8;
                        str34 = str61;
                        str29 = str64;
                        str30 = str65;
                        str31 = str66;
                        str26 = str34;
                        str33 = str67;
                        str53 = str68;
                        eVM5792SendCallsParams6 = eVM5792SendCallsParams3;
                        list11 = list4;
                        str64 = str29;
                        str65 = str30;
                        str66 = str31;
                        str67 = str33;
                        str61 = str26;
                        list9 = list5;
                        num6 = num3;
                        str52 = str25;
                        str63 = str28;
                        str62 = str27;
                        break;
                    case 16:
                        str25 = str52;
                        eVM5792SendCallsParams3 = eVM5792SendCallsParams6;
                        str27 = str62;
                        str28 = str63;
                        list5 = list9;
                        num3 = num6;
                        List list12 = (List) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 16, kSerializerArr[16], list11);
                        int i12 = 65536 | i8;
                        Unit unit13 = Unit.INSTANCE;
                        i8 = i12;
                        str34 = str61;
                        list4 = list12;
                        str29 = str64;
                        str30 = str65;
                        str31 = str66;
                        str26 = str34;
                        str33 = str67;
                        str53 = str68;
                        eVM5792SendCallsParams6 = eVM5792SendCallsParams3;
                        list11 = list4;
                        str64 = str29;
                        str65 = str30;
                        str66 = str31;
                        str67 = str33;
                        str61 = str26;
                        list9 = list5;
                        num6 = num3;
                        str52 = str25;
                        str63 = str28;
                        str62 = str27;
                        break;
                    case 17:
                        str25 = str52;
                        eVM5792SendCallsParams3 = eVM5792SendCallsParams6;
                        str27 = str62;
                        list5 = list9;
                        userOperation5 = (UserOperation) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 17, UserOperation$$serializer.INSTANCE, userOperation5);
                        i6 = 131072 | i8;
                        Unit unit14 = Unit.INSTANCE;
                        str63 = str63;
                        i8 = i6;
                        str28 = str63;
                        list4 = list11;
                        str29 = str64;
                        str30 = str65;
                        str31 = str66;
                        num3 = num6;
                        str34 = str61;
                        str26 = str34;
                        str33 = str67;
                        str53 = str68;
                        eVM5792SendCallsParams6 = eVM5792SendCallsParams3;
                        list11 = list4;
                        str64 = str29;
                        str65 = str30;
                        str66 = str31;
                        str67 = str33;
                        str61 = str26;
                        list9 = list5;
                        num6 = num3;
                        str52 = str25;
                        str63 = str28;
                        str62 = str27;
                        break;
                    case 18:
                        str25 = str52;
                        eVM5792SendCallsParams3 = eVM5792SendCallsParams6;
                        str27 = str62;
                        list5 = list9;
                        str63 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 18, StringSerializer.INSTANCE, str63);
                        i6 = 262144 | i8;
                        Unit unit15 = Unit.INSTANCE;
                        i8 = i6;
                        str28 = str63;
                        list4 = list11;
                        str29 = str64;
                        str30 = str65;
                        str31 = str66;
                        num3 = num6;
                        str34 = str61;
                        str26 = str34;
                        str33 = str67;
                        str53 = str68;
                        eVM5792SendCallsParams6 = eVM5792SendCallsParams3;
                        list11 = list4;
                        str64 = str29;
                        str65 = str30;
                        str66 = str31;
                        str67 = str33;
                        str61 = str26;
                        list9 = list5;
                        num6 = num3;
                        str52 = str25;
                        str63 = str28;
                        str62 = str27;
                        break;
                    case 19:
                        str25 = str52;
                        eVM5792SendCallsParams3 = eVM5792SendCallsParams6;
                        str27 = str62;
                        List list13 = (List) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 19, kSerializerArr[19], list9);
                        Unit unit16 = Unit.INSTANCE;
                        list5 = list13;
                        i6 = i8 | 524288;
                        i8 = i6;
                        str28 = str63;
                        list4 = list11;
                        str29 = str64;
                        str30 = str65;
                        str31 = str66;
                        num3 = num6;
                        str34 = str61;
                        str26 = str34;
                        str33 = str67;
                        str53 = str68;
                        eVM5792SendCallsParams6 = eVM5792SendCallsParams3;
                        list11 = list4;
                        str64 = str29;
                        str65 = str30;
                        str66 = str31;
                        str67 = str33;
                        str61 = str26;
                        list9 = list5;
                        num6 = num3;
                        str52 = str25;
                        str63 = str28;
                        str62 = str27;
                        break;
                    case 20:
                        str25 = str52;
                        eVM5792SendCallsParams3 = eVM5792SendCallsParams6;
                        String str71 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 20, StringSerializer.INSTANCE, str62);
                        Unit unit17 = Unit.INSTANCE;
                        i8 = 1048576 | i8;
                        str27 = str71;
                        str28 = str63;
                        list4 = list11;
                        str29 = str64;
                        str30 = str65;
                        str31 = str66;
                        num3 = num6;
                        str34 = str61;
                        list5 = list9;
                        str26 = str34;
                        str33 = str67;
                        str53 = str68;
                        eVM5792SendCallsParams6 = eVM5792SendCallsParams3;
                        list11 = list4;
                        str64 = str29;
                        str65 = str30;
                        str66 = str31;
                        str67 = str33;
                        str61 = str26;
                        list9 = list5;
                        num6 = num3;
                        str52 = str25;
                        str63 = str28;
                        str62 = str27;
                        break;
                    case 21:
                        str25 = str52;
                        eVM5792SendCallsParams4 = eVM5792SendCallsParams6;
                        list10 = (List) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 21, kSerializerArr[21], list10);
                        int i13 = 2097152 | i8;
                        Unit unit18 = Unit.INSTANCE;
                        i8 = i13;
                        str53 = str68;
                        eVM5792SendCallsParams6 = eVM5792SendCallsParams4;
                        str26 = str61;
                        str27 = str62;
                        str28 = str63;
                        list4 = list11;
                        str29 = str64;
                        str30 = str65;
                        str31 = str66;
                        str33 = str67;
                        num3 = num6;
                        list5 = list9;
                        list11 = list4;
                        str64 = str29;
                        str65 = str30;
                        str66 = str31;
                        str67 = str33;
                        str61 = str26;
                        list9 = list5;
                        num6 = num3;
                        str52 = str25;
                        str63 = str28;
                        str62 = str27;
                        break;
                    case 22:
                        eVM5792SendCallsParams4 = eVM5792SendCallsParams6;
                        str25 = str52;
                        str53 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 22, StringSerializer.INSTANCE, str68);
                        Unit unit19 = Unit.INSTANCE;
                        i8 = 4194304 | i8;
                        eVM5792SendCallsParams6 = eVM5792SendCallsParams4;
                        str26 = str61;
                        str27 = str62;
                        str28 = str63;
                        list4 = list11;
                        str29 = str64;
                        str30 = str65;
                        str31 = str66;
                        str33 = str67;
                        num3 = num6;
                        list5 = list9;
                        list11 = list4;
                        str64 = str29;
                        str65 = str30;
                        str66 = str31;
                        str67 = str33;
                        str61 = str26;
                        list9 = list5;
                        num6 = num3;
                        str52 = str25;
                        str63 = str28;
                        str62 = str27;
                        break;
                    case 23:
                        eVM5792SendCallsParams4 = eVM5792SendCallsParams6;
                        String str72 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 23, StringSerializer.INSTANCE, str52);
                        int i14 = 8388608 | i8;
                        Unit unit20 = Unit.INSTANCE;
                        str25 = str72;
                        i8 = i14;
                        str53 = str68;
                        eVM5792SendCallsParams6 = eVM5792SendCallsParams4;
                        str26 = str61;
                        str27 = str62;
                        str28 = str63;
                        list4 = list11;
                        str29 = str64;
                        str30 = str65;
                        str31 = str66;
                        str33 = str67;
                        num3 = num6;
                        list5 = list9;
                        list11 = list4;
                        str64 = str29;
                        str65 = str30;
                        str66 = str31;
                        str67 = str33;
                        str61 = str26;
                        list9 = list5;
                        num6 = num3;
                        str52 = str25;
                        str63 = str28;
                        str62 = str27;
                        break;
                    case 24:
                        str25 = str52;
                        str54 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 24, StringSerializer.INSTANCE, str54);
                        i7 = 16777216;
                        i8 |= i7;
                        Unit unit21 = Unit.INSTANCE;
                        str53 = str68;
                        str26 = str61;
                        str27 = str62;
                        str28 = str63;
                        list4 = list11;
                        str29 = str64;
                        str30 = str65;
                        str31 = str66;
                        str33 = str67;
                        num3 = num6;
                        list5 = list9;
                        list11 = list4;
                        str64 = str29;
                        str65 = str30;
                        str66 = str31;
                        str67 = str33;
                        str61 = str26;
                        list9 = list5;
                        num6 = num3;
                        str52 = str25;
                        str63 = str28;
                        str62 = str27;
                        break;
                    case 25:
                        str25 = str52;
                        num7 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 25, IntSerializer.INSTANCE, num7);
                        i7 = MediaHttpDownloader.MAXIMUM_CHUNK_SIZE;
                        i8 |= i7;
                        Unit unit212 = Unit.INSTANCE;
                        str53 = str68;
                        str26 = str61;
                        str27 = str62;
                        str28 = str63;
                        list4 = list11;
                        str29 = str64;
                        str30 = str65;
                        str31 = str66;
                        str33 = str67;
                        num3 = num6;
                        list5 = list9;
                        list11 = list4;
                        str64 = str29;
                        str65 = str30;
                        str66 = str31;
                        str67 = str33;
                        str61 = str26;
                        list9 = list5;
                        num6 = num3;
                        str52 = str25;
                        str63 = str28;
                        str62 = str27;
                        break;
                    case 26:
                        str25 = str52;
                        str35 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 26, StringSerializer.INSTANCE, str35);
                        i7 = 67108864;
                        i8 |= i7;
                        Unit unit2122 = Unit.INSTANCE;
                        str53 = str68;
                        str26 = str61;
                        str27 = str62;
                        str28 = str63;
                        list4 = list11;
                        str29 = str64;
                        str30 = str65;
                        str31 = str66;
                        str33 = str67;
                        num3 = num6;
                        list5 = list9;
                        list11 = list4;
                        str64 = str29;
                        str65 = str30;
                        str66 = str31;
                        str67 = str33;
                        str61 = str26;
                        list9 = list5;
                        num6 = num3;
                        str52 = str25;
                        str63 = str28;
                        str62 = str27;
                        break;
                    case 27:
                        str25 = str52;
                        eVM5792SendCallsParams6 = (EVM5792SendCallsParams) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 27, EVM5792SendCallsParams$$serializer.INSTANCE, eVM5792SendCallsParams6);
                        i7 = 134217728;
                        i8 |= i7;
                        Unit unit21222 = Unit.INSTANCE;
                        str53 = str68;
                        str26 = str61;
                        str27 = str62;
                        str28 = str63;
                        list4 = list11;
                        str29 = str64;
                        str30 = str65;
                        str31 = str66;
                        str33 = str67;
                        num3 = num6;
                        list5 = list9;
                        list11 = list4;
                        str64 = str29;
                        str65 = str30;
                        str66 = str31;
                        str67 = str33;
                        str61 = str26;
                        list9 = list5;
                        num6 = num3;
                        str52 = str25;
                        str63 = str28;
                        str62 = str27;
                        break;
                    case 28:
                        str25 = str52;
                        str55 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 28, StringSerializer.INSTANCE, str55);
                        i7 = 268435456;
                        i8 |= i7;
                        Unit unit212222 = Unit.INSTANCE;
                        str53 = str68;
                        str26 = str61;
                        str27 = str62;
                        str28 = str63;
                        list4 = list11;
                        str29 = str64;
                        str30 = str65;
                        str31 = str66;
                        str33 = str67;
                        num3 = num6;
                        list5 = list9;
                        list11 = list4;
                        str64 = str29;
                        str65 = str30;
                        str66 = str31;
                        str67 = str33;
                        str61 = str26;
                        list9 = list5;
                        num6 = num3;
                        str52 = str25;
                        str63 = str28;
                        str62 = str27;
                        break;
                    case 29:
                        str25 = str52;
                        str56 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 29, StringSerializer.INSTANCE, str56);
                        i7 = 536870912;
                        i8 |= i7;
                        Unit unit2122222 = Unit.INSTANCE;
                        str53 = str68;
                        str26 = str61;
                        str27 = str62;
                        str28 = str63;
                        list4 = list11;
                        str29 = str64;
                        str30 = str65;
                        str31 = str66;
                        str33 = str67;
                        num3 = num6;
                        list5 = list9;
                        list11 = list4;
                        str64 = str29;
                        str65 = str30;
                        str66 = str31;
                        str67 = str33;
                        str61 = str26;
                        list9 = list5;
                        num6 = num3;
                        str52 = str25;
                        str63 = str28;
                        str62 = str27;
                        break;
                    case 30:
                        str25 = str52;
                        str59 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 30, StringSerializer.INSTANCE, str59);
                        i7 = 1073741824;
                        i8 |= i7;
                        Unit unit21222222 = Unit.INSTANCE;
                        str53 = str68;
                        str26 = str61;
                        str27 = str62;
                        str28 = str63;
                        list4 = list11;
                        str29 = str64;
                        str30 = str65;
                        str31 = str66;
                        str33 = str67;
                        num3 = num6;
                        list5 = list9;
                        list11 = list4;
                        str64 = str29;
                        str65 = str30;
                        str66 = str31;
                        str67 = str33;
                        str61 = str26;
                        list9 = list5;
                        num6 = num3;
                        str52 = str25;
                        str63 = str28;
                        str62 = str27;
                        break;
                    case 31:
                        str25 = str52;
                        str57 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 31, StringSerializer.INSTANCE, str57);
                        i7 = Integer.MIN_VALUE;
                        i8 |= i7;
                        Unit unit212222222 = Unit.INSTANCE;
                        str53 = str68;
                        str26 = str61;
                        str27 = str62;
                        str28 = str63;
                        list4 = list11;
                        str29 = str64;
                        str30 = str65;
                        str31 = str66;
                        str33 = str67;
                        num3 = num6;
                        list5 = list9;
                        list11 = list4;
                        str64 = str29;
                        str65 = str30;
                        str66 = str31;
                        str67 = str33;
                        str61 = str26;
                        list9 = list5;
                        num6 = num3;
                        str52 = str25;
                        str63 = str28;
                        str62 = str27;
                        break;
                    case 32:
                        str25 = str52;
                        bool3 = (Boolean) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 32, BooleanSerializer.INSTANCE, bool3);
                        i10 |= 1;
                        Unit unit2122222222 = Unit.INSTANCE;
                        str53 = str68;
                        str26 = str61;
                        str27 = str62;
                        str28 = str63;
                        list4 = list11;
                        str29 = str64;
                        str30 = str65;
                        str31 = str66;
                        str33 = str67;
                        num3 = num6;
                        list5 = list9;
                        list11 = list4;
                        str64 = str29;
                        str65 = str30;
                        str66 = str31;
                        str67 = str33;
                        str61 = str26;
                        list9 = list5;
                        num6 = num3;
                        str52 = str25;
                        str63 = str28;
                        str62 = str27;
                        break;
                    case 33:
                        str25 = str52;
                        num6 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 33, IntSerializer.INSTANCE, num6);
                        i10 |= 2;
                        Unit unit21222222222 = Unit.INSTANCE;
                        str53 = str68;
                        str26 = str61;
                        str27 = str62;
                        str28 = str63;
                        list4 = list11;
                        str29 = str64;
                        str30 = str65;
                        str31 = str66;
                        str33 = str67;
                        num3 = num6;
                        list5 = list9;
                        list11 = list4;
                        str64 = str29;
                        str65 = str30;
                        str66 = str31;
                        str67 = str33;
                        str61 = str26;
                        list9 = list5;
                        num6 = num3;
                        str52 = str25;
                        str63 = str28;
                        str62 = str27;
                        break;
                    case 34:
                        str25 = str52;
                        str58 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 34, StringSerializer.INSTANCE, str58);
                        i10 |= 4;
                        Unit unit212222222222 = Unit.INSTANCE;
                        str53 = str68;
                        str26 = str61;
                        str27 = str62;
                        str28 = str63;
                        list4 = list11;
                        str29 = str64;
                        str30 = str65;
                        str31 = str66;
                        str33 = str67;
                        num3 = num6;
                        list5 = list9;
                        list11 = list4;
                        str64 = str29;
                        str65 = str30;
                        str66 = str31;
                        str67 = str33;
                        str61 = str26;
                        list9 = list5;
                        num6 = num3;
                        str52 = str25;
                        str63 = str28;
                        str62 = str27;
                        break;
                    default:
                        throw new UnknownFieldException(iDecodeElementIndex);
                }
            }
            String str73 = str62;
            String str74 = str63;
            String str75 = str64;
            List list14 = list9;
            userOperation = userOperation5;
            str = str54;
            str2 = str55;
            str3 = str56;
            str4 = str58;
            list = list11;
            str5 = str73;
            str6 = str75;
            str7 = str65;
            str8 = str66;
            str9 = str61;
            i = i9;
            str10 = str60;
            list2 = list10;
            list3 = list14;
            num = num6;
            str11 = strDecodeStringElement9;
            str12 = strDecodeStringElement10;
            str13 = strDecodeStringElement11;
            str14 = strDecodeStringElement12;
            str15 = strDecodeStringElement15;
            i2 = iDecodeIntElement3;
            str16 = str53;
            str17 = str52;
            eVM5792SendCallsParams = eVM5792SendCallsParams6;
            i3 = i8;
            num2 = num7;
            str18 = str35;
            str19 = str57;
            bool = bool3;
            str20 = str59;
            str21 = str74;
            str22 = strDecodeStringElement13;
            str23 = strDecodeStringElement14;
            j = jDecodeLongElement2;
            i4 = i10;
            str24 = str67;
        }
        compositeDecoderBeginStructure.endStructure(serialDescriptor);
        return new BroadcastBean(i3, i4, str15, i, str23, str24, str12, str22, j, str14, str13, i2, str11, str10, str9, str8, str7, str6, list, userOperation, str21, list3, str5, list2, str16, str17, str, num2, str18, eVM5792SendCallsParams, str2, str3, str20, str19, bool, num, str4, (SerializationConstructorMarker) null);
    }

    /* JADX DEBUG: Method merged with bridge method: serialize(Lkotlinx/serialization/encoding/Encoder;Ljava/lang/Object;)V */
    @Override // kotlinx.serialization.SerializationStrategy
    public final void serialize(@NotNull Encoder encoder, @NotNull BroadcastBean broadcastBean) {
        Intrinsics.checkNotNullParameter(encoder, "");
        Intrinsics.checkNotNullParameter(broadcastBean, "");
        SerialDescriptor serialDescriptor = descriptor;
        CompositeEncoder compositeEncoderBeginStructure = encoder.beginStructure(serialDescriptor);
        BroadcastBean.write$Self$OKWallet_wallet_impl(broadcastBean, compositeEncoderBeginStructure, serialDescriptor);
        compositeEncoderBeginStructure.endStructure(serialDescriptor);
    }
}
