package com.okinc.business.web3pay.lib.core.network.ws;

import com.google.api.client.googleapis.media.MediaHttpDownloader;
import java.util.List;
import kotlin.Unit;
import kotlin.jvm.internal.Intrinsics;
import kotlinx.serialization.KSerializer;
import kotlinx.serialization.UnknownFieldException;
import kotlinx.serialization.builtins.BuiltinSerializersKt;
import kotlinx.serialization.descriptors.SerialDescriptor;
import kotlinx.serialization.encoding.CompositeDecoder;
import kotlinx.serialization.encoding.CompositeEncoder;
import kotlinx.serialization.encoding.Decoder;
import kotlinx.serialization.encoding.Encoder;
import kotlinx.serialization.internal.GeneratedSerializer;
import kotlinx.serialization.internal.IntSerializer;
import kotlinx.serialization.internal.LongSerializer;
import kotlinx.serialization.internal.PluginGeneratedSerialDescriptor;
import kotlinx.serialization.internal.SerializationConstructorMarker;
import kotlinx.serialization.internal.StringSerializer;
import kotlinx.serialization.json.JsonObject;
import kotlinx.serialization.json.JsonObjectSerializer;
import org.jetbrains.annotations.NotNull;

/* JADX INFO: loaded from: classes23.dex */
public final /* synthetic */ class TxStatusSubResponse$$serializer implements GeneratedSerializer<TxStatusSubResponse> {
    public static final int $stable;
    public static final TxStatusSubResponse$$serializer INSTANCE;
    private static final SerialDescriptor descriptor;

    /* JADX DEBUG: Don't trust debug lines info. Lines numbers was adjusted: min line is 0 */
    private TxStatusSubResponse$$serializer() {
    }

    /* JADX DEBUG: Don't trust debug lines info. Lines numbers was adjusted: min line is 0 */
    @Override // kotlinx.serialization.KSerializer, kotlinx.serialization.SerializationStrategy, kotlinx.serialization.DeserializationStrategy
    public final SerialDescriptor getDescriptor() {
        return descriptor;
    }

    static {
        TxStatusSubResponse$$serializer txStatusSubResponse$$serializer = new TxStatusSubResponse$$serializer();
        INSTANCE = txStatusSubResponse$$serializer;
        $stable = 8;
        PluginGeneratedSerialDescriptor pluginGeneratedSerialDescriptor = new PluginGeneratedSerialDescriptor("com.okinc.business.web3pay.lib.core.network.ws.TxStatusSubResponse", txStatusSubResponse$$serializer, 33);
        pluginGeneratedSerialDescriptor.addElement("orderId", false);
        pluginGeneratedSerialDescriptor.addElement("parentOrderId", false);
        pluginGeneratedSerialDescriptor.addElement("status", false);
        pluginGeneratedSerialDescriptor.addElement("uopHash", true);
        pluginGeneratedSerialDescriptor.addElement("txHash", false);
        pluginGeneratedSerialDescriptor.addElement("timeToCancel", true);
        pluginGeneratedSerialDescriptor.addElement("orderType", false);
        pluginGeneratedSerialDescriptor.addElement("productCode", true);
        pluginGeneratedSerialDescriptor.addElement("merchantId", true);
        pluginGeneratedSerialDescriptor.addElement("code", true);
        pluginGeneratedSerialDescriptor.addElement("convertStages", true);
        pluginGeneratedSerialDescriptor.addElement("failedType", true);
        pluginGeneratedSerialDescriptor.addElement("toTokenAmount", true);
        pluginGeneratedSerialDescriptor.addElement("msgType", true);
        pluginGeneratedSerialDescriptor.addElement("tokenSymbol", true);
        pluginGeneratedSerialDescriptor.addElement("tokenDecimal", true);
        pluginGeneratedSerialDescriptor.addElement("chainIndex", true);
        pluginGeneratedSerialDescriptor.addElement("tokenAddress", true);
        pluginGeneratedSerialDescriptor.addElement("tokenAmount", true);
        pluginGeneratedSerialDescriptor.addElement("tokenLogo", true);
        pluginGeneratedSerialDescriptor.addElement("currencyAmount", true);
        pluginGeneratedSerialDescriptor.addElement("from", true);
        pluginGeneratedSerialDescriptor.addElement("to", true);
        pluginGeneratedSerialDescriptor.addElement("createTime", true);
        pluginGeneratedSerialDescriptor.addElement("receiverType", true);
        pluginGeneratedSerialDescriptor.addElement("areaCode", true);
        pluginGeneratedSerialDescriptor.addElement("subStatus", true);
        pluginGeneratedSerialDescriptor.addElement("firstPackTime", true);
        pluginGeneratedSerialDescriptor.addElement("gasFeeType", true);
        pluginGeneratedSerialDescriptor.addElement("tokenCoinTypeNo", true);
        pluginGeneratedSerialDescriptor.addElement("convertInfo", true);
        pluginGeneratedSerialDescriptor.addElement("authorizeType", true);
        pluginGeneratedSerialDescriptor.addElement("extInfo", true);
        descriptor = pluginGeneratedSerialDescriptor;
    }

    @Override // kotlinx.serialization.internal.GeneratedSerializer
    public final KSerializer<?>[] childSerializers() {
        KSerializer[] kSerializerArr = TxStatusSubResponse.$childSerializers;
        StringSerializer stringSerializer = StringSerializer.INSTANCE;
        IntSerializer intSerializer = IntSerializer.INSTANCE;
        LongSerializer longSerializer = LongSerializer.INSTANCE;
        return new KSerializer[]{stringSerializer, stringSerializer, intSerializer, BuiltinSerializersKt.getNullable(stringSerializer), stringSerializer, BuiltinSerializersKt.getNullable(longSerializer), intSerializer, BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(intSerializer), BuiltinSerializersKt.getNullable(kSerializerArr[10]), BuiltinSerializersKt.getNullable(intSerializer), BuiltinSerializersKt.getNullable(stringSerializer), intSerializer, BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(intSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(longSerializer), BuiltinSerializersKt.getNullable(intSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(intSerializer), BuiltinSerializersKt.getNullable(longSerializer), BuiltinSerializersKt.getNullable(intSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(ConvertInfoWS$$serializer.INSTANCE), BuiltinSerializersKt.getNullable(intSerializer), BuiltinSerializersKt.getNullable(JsonObjectSerializer.INSTANCE)};
    }

    /* JADX DEBUG: Method merged with bridge method: deserialize(Lkotlinx/serialization/encoding/Decoder;)Ljava/lang/Object; */
    @Override // kotlinx.serialization.DeserializationStrategy
    public final TxStatusSubResponse deserialize(@NotNull Decoder decoder) {
        Integer num;
        int i;
        Integer num2;
        String str;
        Integer num3;
        JsonObject jsonObject;
        String str2;
        String str3;
        String str4;
        String str5;
        Long l;
        String str6;
        Integer num4;
        List list;
        String str7;
        String str8;
        Long l2;
        String str9;
        int i2;
        String str10;
        String str11;
        String str12;
        String str13;
        int i3;
        ConvertInfoWS convertInfoWS;
        String str14;
        Integer num5;
        String str15;
        Integer num6;
        int i4;
        String str16;
        Integer num7;
        int i5;
        Long l3;
        String str17;
        KSerializer[] kSerializerArr;
        Integer num8;
        String str18;
        String str19;
        int i6;
        String str20;
        String str21;
        String str22;
        String str23;
        String str24;
        Integer num9;
        String str25;
        String str26;
        List list2;
        String str27;
        String str28;
        Long l4;
        String str29;
        String str30;
        String str31;
        String str32;
        String str33;
        Integer num10;
        String str34;
        String str35;
        int i7;
        String str36;
        String str37;
        String str38;
        String str39;
        String str40;
        String str41;
        String str42;
        String str43;
        String str44;
        String str45;
        int i8;
        String str46;
        String str47;
        int i9;
        String str48;
        String str49;
        int i10;
        String str50;
        int i11;
        String str51;
        String str52;
        int iDecodeIntElement;
        int i12;
        String str53;
        int i13;
        int i14;
        String str54;
        int i15;
        int i16;
        int i17;
        int i18;
        Intrinsics.checkNotNullParameter(decoder, "");
        SerialDescriptor serialDescriptor = descriptor;
        CompositeDecoder compositeDecoderBeginStructure = decoder.beginStructure(serialDescriptor);
        KSerializer[] kSerializerArr2 = TxStatusSubResponse.$childSerializers;
        if (compositeDecoderBeginStructure.decodeSequentially()) {
            String strDecodeStringElement = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 0);
            String strDecodeStringElement2 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 1);
            int iDecodeIntElement2 = compositeDecoderBeginStructure.decodeIntElement(serialDescriptor, 2);
            StringSerializer stringSerializer = StringSerializer.INSTANCE;
            String str55 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 3, stringSerializer, null);
            String strDecodeStringElement3 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 4);
            LongSerializer longSerializer = LongSerializer.INSTANCE;
            Long l5 = (Long) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 5, longSerializer, null);
            int iDecodeIntElement3 = compositeDecoderBeginStructure.decodeIntElement(serialDescriptor, 6);
            String str56 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 7, stringSerializer, null);
            String str57 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 8, stringSerializer, null);
            IntSerializer intSerializer = IntSerializer.INSTANCE;
            Integer num11 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 9, intSerializer, null);
            List list3 = (List) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 10, kSerializerArr2[10], null);
            Integer num12 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 11, intSerializer, null);
            String str58 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 12, stringSerializer, null);
            int iDecodeIntElement4 = compositeDecoderBeginStructure.decodeIntElement(serialDescriptor, 13);
            String str59 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 14, stringSerializer, null);
            Integer num13 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 15, intSerializer, null);
            String str60 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 16, stringSerializer, null);
            String str61 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 17, stringSerializer, null);
            String str62 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 18, stringSerializer, null);
            String str63 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 19, stringSerializer, null);
            String str64 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 20, stringSerializer, null);
            String str65 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 21, stringSerializer, null);
            String str66 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 22, stringSerializer, null);
            Long l6 = (Long) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 23, longSerializer, null);
            Integer num14 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 24, intSerializer, null);
            String str67 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 25, stringSerializer, null);
            Integer num15 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 26, intSerializer, null);
            Long l7 = (Long) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 27, longSerializer, null);
            Integer num16 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 28, intSerializer, null);
            String str68 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 29, stringSerializer, null);
            convertInfoWS = (ConvertInfoWS) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 30, ConvertInfoWS$$serializer.INSTANCE, null);
            num3 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 31, intSerializer, null);
            str7 = strDecodeStringElement3;
            num7 = num16;
            jsonObject = (JsonObject) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 32, JsonObjectSerializer.INSTANCE, null);
            i = -1;
            str = str58;
            list = list3;
            str17 = str67;
            num = num15;
            l3 = l7;
            str10 = str68;
            num2 = num12;
            str9 = str64;
            str2 = str65;
            str12 = str66;
            l2 = l6;
            str3 = str62;
            str14 = str61;
            str4 = str60;
            i2 = iDecodeIntElement4;
            str11 = str55;
            num4 = num11;
            i4 = iDecodeIntElement3;
            l = l5;
            num5 = num13;
            str8 = strDecodeStringElement2;
            i5 = 1;
            i3 = iDecodeIntElement2;
            str6 = str56;
            str15 = strDecodeStringElement;
            num6 = num14;
            str13 = str63;
            str5 = str59;
            str16 = str57;
        } else {
            int i19 = 0;
            int iDecodeIntElement5 = 0;
            int iDecodeIntElement6 = 0;
            int i20 = 0;
            String str69 = null;
            String str70 = null;
            String str71 = null;
            Integer num17 = null;
            Integer num18 = null;
            ConvertInfoWS convertInfoWS2 = null;
            Integer num19 = null;
            JsonObject jsonObject2 = null;
            String strDecodeStringElement4 = null;
            String strDecodeStringElement5 = null;
            String strDecodeStringElement6 = null;
            Long l8 = null;
            num = null;
            String str72 = null;
            Integer num20 = null;
            Long l9 = null;
            String str73 = null;
            String str74 = null;
            String str75 = null;
            String str76 = null;
            String str77 = null;
            Integer num21 = null;
            String str78 = null;
            String str79 = null;
            List list4 = null;
            String str80 = null;
            String str81 = null;
            Long l10 = null;
            String str82 = null;
            boolean z = true;
            Integer num22 = null;
            i = 0;
            while (z) {
                int iDecodeElementIndex = compositeDecoderBeginStructure.decodeElementIndex(serialDescriptor);
                switch (iDecodeElementIndex) {
                    case -1:
                        kSerializerArr = kSerializerArr2;
                        num8 = num22;
                        str18 = str70;
                        str19 = str71;
                        i6 = i19;
                        str20 = str73;
                        str21 = str74;
                        str22 = str75;
                        str23 = str76;
                        str24 = str77;
                        num9 = num21;
                        str25 = str78;
                        str26 = str79;
                        list2 = list4;
                        str27 = str80;
                        str28 = str81;
                        l4 = l10;
                        str29 = str69;
                        Unit unit = Unit.INSTANCE;
                        z = false;
                        str30 = str26;
                        l10 = l4;
                        num22 = num8;
                        i19 = i6;
                        str31 = str27;
                        str70 = str18;
                        str32 = str21;
                        str33 = str20;
                        str71 = str19;
                        str74 = str32;
                        str79 = str30;
                        str75 = str22;
                        str76 = str23;
                        str77 = str24;
                        num21 = num9;
                        str78 = str25;
                        kSerializerArr2 = kSerializerArr;
                        str80 = str31;
                        str81 = str28;
                        list4 = list2;
                        str69 = str29;
                        str73 = str33;
                        break;
                    case 0:
                        kSerializerArr = kSerializerArr2;
                        num8 = num22;
                        str18 = str70;
                        str19 = str71;
                        i6 = i19;
                        str20 = str73;
                        str21 = str74;
                        str22 = str75;
                        str23 = str76;
                        str24 = str77;
                        num9 = num21;
                        str25 = str78;
                        str26 = str79;
                        list2 = list4;
                        str27 = str80;
                        str28 = str81;
                        l4 = l10;
                        str29 = str69;
                        strDecodeStringElement6 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 0);
                        i |= 1;
                        Unit unit2 = Unit.INSTANCE;
                        str30 = str26;
                        l10 = l4;
                        num22 = num8;
                        i19 = i6;
                        str31 = str27;
                        str70 = str18;
                        str32 = str21;
                        str33 = str20;
                        str71 = str19;
                        str74 = str32;
                        str79 = str30;
                        str75 = str22;
                        str76 = str23;
                        str77 = str24;
                        num21 = num9;
                        str78 = str25;
                        kSerializerArr2 = kSerializerArr;
                        str80 = str31;
                        str81 = str28;
                        list4 = list2;
                        str69 = str29;
                        str73 = str33;
                        break;
                    case 1:
                        kSerializerArr = kSerializerArr2;
                        num8 = num22;
                        str18 = str70;
                        str19 = str71;
                        i6 = i19;
                        str20 = str73;
                        str21 = str74;
                        str22 = str75;
                        str23 = str76;
                        str24 = str77;
                        num9 = num21;
                        str25 = str78;
                        str26 = str79;
                        list2 = list4;
                        str27 = str80;
                        str28 = str81;
                        l4 = l10;
                        str29 = str69;
                        strDecodeStringElement5 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 1);
                        i |= 2;
                        Unit unit3 = Unit.INSTANCE;
                        str30 = str26;
                        l10 = l4;
                        num22 = num8;
                        i19 = i6;
                        str31 = str27;
                        str70 = str18;
                        str32 = str21;
                        str33 = str20;
                        str71 = str19;
                        str74 = str32;
                        str79 = str30;
                        str75 = str22;
                        str76 = str23;
                        str77 = str24;
                        num21 = num9;
                        str78 = str25;
                        kSerializerArr2 = kSerializerArr;
                        str80 = str31;
                        str81 = str28;
                        list4 = list2;
                        str69 = str29;
                        str73 = str33;
                        break;
                    case 2:
                        kSerializerArr = kSerializerArr2;
                        num8 = num22;
                        str18 = str70;
                        str19 = str71;
                        i6 = i19;
                        str20 = str73;
                        str21 = str74;
                        str22 = str75;
                        str23 = str76;
                        str24 = str77;
                        num9 = num21;
                        str25 = str78;
                        str26 = str79;
                        list2 = list4;
                        str27 = str80;
                        str28 = str81;
                        l4 = l10;
                        str29 = str69;
                        iDecodeIntElement5 = compositeDecoderBeginStructure.decodeIntElement(serialDescriptor, 2);
                        i |= 4;
                        Unit unit4 = Unit.INSTANCE;
                        str30 = str26;
                        l10 = l4;
                        num22 = num8;
                        i19 = i6;
                        str31 = str27;
                        str70 = str18;
                        str32 = str21;
                        str33 = str20;
                        str71 = str19;
                        str74 = str32;
                        str79 = str30;
                        str75 = str22;
                        str76 = str23;
                        str77 = str24;
                        num21 = num9;
                        str78 = str25;
                        kSerializerArr2 = kSerializerArr;
                        str80 = str31;
                        str81 = str28;
                        list4 = list2;
                        str69 = str29;
                        str73 = str33;
                        break;
                    case 3:
                        kSerializerArr = kSerializerArr2;
                        num8 = num22;
                        str18 = str70;
                        str19 = str71;
                        i6 = i19;
                        str20 = str73;
                        str21 = str74;
                        str22 = str75;
                        str23 = str76;
                        str24 = str77;
                        num9 = num21;
                        str25 = str78;
                        str26 = str79;
                        list2 = list4;
                        str27 = str80;
                        str28 = str81;
                        str29 = str69;
                        l4 = l10;
                        str82 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 3, StringSerializer.INSTANCE, str82);
                        i |= 8;
                        Unit unit5 = Unit.INSTANCE;
                        str30 = str26;
                        l10 = l4;
                        num22 = num8;
                        i19 = i6;
                        str31 = str27;
                        str70 = str18;
                        str32 = str21;
                        str33 = str20;
                        str71 = str19;
                        str74 = str32;
                        str79 = str30;
                        str75 = str22;
                        str76 = str23;
                        str77 = str24;
                        num21 = num9;
                        str78 = str25;
                        kSerializerArr2 = kSerializerArr;
                        str80 = str31;
                        str81 = str28;
                        list4 = list2;
                        str69 = str29;
                        str73 = str33;
                        break;
                    case 4:
                        kSerializerArr = kSerializerArr2;
                        num10 = num22;
                        str34 = str70;
                        str35 = str71;
                        i7 = i19;
                        str36 = str73;
                        str37 = str74;
                        str22 = str75;
                        str23 = str76;
                        str24 = str77;
                        num9 = num21;
                        str25 = str78;
                        str38 = str79;
                        list2 = list4;
                        str39 = str80;
                        str40 = str81;
                        str41 = str69;
                        strDecodeStringElement4 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 4);
                        i |= 16;
                        Unit unit6 = Unit.INSTANCE;
                        str42 = str39;
                        str70 = str34;
                        str81 = str40;
                        str69 = str41;
                        str48 = str38;
                        i19 = i7;
                        str73 = str36;
                        str71 = str35;
                        str30 = str48;
                        str31 = str42;
                        num22 = num10;
                        str28 = str81;
                        str32 = str37;
                        str33 = str73;
                        str29 = str69;
                        str74 = str32;
                        str79 = str30;
                        str75 = str22;
                        str76 = str23;
                        str77 = str24;
                        num21 = num9;
                        str78 = str25;
                        kSerializerArr2 = kSerializerArr;
                        str80 = str31;
                        str81 = str28;
                        list4 = list2;
                        str69 = str29;
                        str73 = str33;
                        break;
                    case 5:
                        kSerializerArr = kSerializerArr2;
                        num10 = num22;
                        str34 = str70;
                        str35 = str71;
                        i7 = i19;
                        str36 = str73;
                        str37 = str74;
                        str22 = str75;
                        str23 = str76;
                        str24 = str77;
                        num9 = num21;
                        str25 = str78;
                        str38 = str79;
                        list2 = list4;
                        str39 = str80;
                        str41 = str69;
                        str40 = str81;
                        l10 = (Long) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 5, LongSerializer.INSTANCE, l10);
                        Unit unit7 = Unit.INSTANCE;
                        i |= 32;
                        str42 = str39;
                        str70 = str34;
                        str81 = str40;
                        str69 = str41;
                        str48 = str38;
                        i19 = i7;
                        str73 = str36;
                        str71 = str35;
                        str30 = str48;
                        str31 = str42;
                        num22 = num10;
                        str28 = str81;
                        str32 = str37;
                        str33 = str73;
                        str29 = str69;
                        str74 = str32;
                        str79 = str30;
                        str75 = str22;
                        str76 = str23;
                        str77 = str24;
                        num21 = num9;
                        str78 = str25;
                        kSerializerArr2 = kSerializerArr;
                        str80 = str31;
                        str81 = str28;
                        list4 = list2;
                        str69 = str29;
                        str73 = str33;
                        break;
                    case 6:
                        kSerializerArr = kSerializerArr2;
                        num10 = num22;
                        str43 = str70;
                        str35 = str71;
                        i7 = i19;
                        str36 = str73;
                        str37 = str74;
                        str22 = str75;
                        str23 = str76;
                        str24 = str77;
                        num9 = num21;
                        str25 = str78;
                        str38 = str79;
                        list2 = list4;
                        str44 = str80;
                        str45 = str69;
                        iDecodeIntElement6 = compositeDecoderBeginStructure.decodeIntElement(serialDescriptor, 6);
                        Unit unit8 = Unit.INSTANCE;
                        i8 = i | 64;
                        i = i8;
                        str42 = str44;
                        str70 = str43;
                        str69 = str45;
                        str48 = str38;
                        i19 = i7;
                        str73 = str36;
                        str71 = str35;
                        str30 = str48;
                        str31 = str42;
                        num22 = num10;
                        str28 = str81;
                        str32 = str37;
                        str33 = str73;
                        str29 = str69;
                        str74 = str32;
                        str79 = str30;
                        str75 = str22;
                        str76 = str23;
                        str77 = str24;
                        num21 = num9;
                        str78 = str25;
                        kSerializerArr2 = kSerializerArr;
                        str80 = str31;
                        str81 = str28;
                        list4 = list2;
                        str69 = str29;
                        str73 = str33;
                        break;
                    case 7:
                        kSerializerArr = kSerializerArr2;
                        str43 = str70;
                        str35 = str71;
                        i7 = i19;
                        str36 = str73;
                        str37 = str74;
                        str22 = str75;
                        str23 = str76;
                        str24 = str77;
                        num9 = num21;
                        str25 = str78;
                        str38 = str79;
                        list2 = list4;
                        str44 = str80;
                        str45 = str69;
                        num10 = num22;
                        str81 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 7, StringSerializer.INSTANCE, str81);
                        i8 = i | 128;
                        Unit unit9 = Unit.INSTANCE;
                        i = i8;
                        str42 = str44;
                        str70 = str43;
                        str69 = str45;
                        str48 = str38;
                        i19 = i7;
                        str73 = str36;
                        str71 = str35;
                        str30 = str48;
                        str31 = str42;
                        num22 = num10;
                        str28 = str81;
                        str32 = str37;
                        str33 = str73;
                        str29 = str69;
                        str74 = str32;
                        str79 = str30;
                        str75 = str22;
                        str76 = str23;
                        str77 = str24;
                        num21 = num9;
                        str78 = str25;
                        kSerializerArr2 = kSerializerArr;
                        str80 = str31;
                        str81 = str28;
                        list4 = list2;
                        str69 = str29;
                        str73 = str33;
                        break;
                    case 8:
                        kSerializerArr = kSerializerArr2;
                        str46 = str70;
                        str35 = str71;
                        i7 = i19;
                        str36 = str73;
                        str37 = str74;
                        str22 = str75;
                        str23 = str76;
                        str24 = str77;
                        num9 = num21;
                        str25 = str78;
                        str38 = str79;
                        str47 = str69;
                        list2 = list4;
                        str80 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 8, StringSerializer.INSTANCE, str80);
                        i9 = i | 256;
                        Unit unit10 = Unit.INSTANCE;
                        num10 = num22;
                        i = i9;
                        str70 = str46;
                        str69 = str47;
                        str42 = str80;
                        str48 = str38;
                        i19 = i7;
                        str73 = str36;
                        str71 = str35;
                        str30 = str48;
                        str31 = str42;
                        num22 = num10;
                        str28 = str81;
                        str32 = str37;
                        str33 = str73;
                        str29 = str69;
                        str74 = str32;
                        str79 = str30;
                        str75 = str22;
                        str76 = str23;
                        str77 = str24;
                        num21 = num9;
                        str78 = str25;
                        kSerializerArr2 = kSerializerArr;
                        str80 = str31;
                        str81 = str28;
                        list4 = list2;
                        str69 = str29;
                        str73 = str33;
                        break;
                    case 9:
                        kSerializerArr = kSerializerArr2;
                        str46 = str70;
                        str35 = str71;
                        i7 = i19;
                        str36 = str73;
                        str37 = str74;
                        str22 = str75;
                        str23 = str76;
                        str24 = str77;
                        num9 = num21;
                        str25 = str78;
                        str38 = str79;
                        str47 = str69;
                        num22 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 9, IntSerializer.INSTANCE, num22);
                        i9 = i | 512;
                        Unit unit11 = Unit.INSTANCE;
                        list2 = list4;
                        num10 = num22;
                        i = i9;
                        str70 = str46;
                        str69 = str47;
                        str42 = str80;
                        str48 = str38;
                        i19 = i7;
                        str73 = str36;
                        str71 = str35;
                        str30 = str48;
                        str31 = str42;
                        num22 = num10;
                        str28 = str81;
                        str32 = str37;
                        str33 = str73;
                        str29 = str69;
                        str74 = str32;
                        str79 = str30;
                        str75 = str22;
                        str76 = str23;
                        str77 = str24;
                        num21 = num9;
                        str78 = str25;
                        kSerializerArr2 = kSerializerArr;
                        str80 = str31;
                        str81 = str28;
                        list4 = list2;
                        str69 = str29;
                        str73 = str33;
                        break;
                    case 10:
                        str35 = str71;
                        i7 = i19;
                        str36 = str73;
                        str37 = str74;
                        str22 = str75;
                        str23 = str76;
                        str24 = str77;
                        num9 = num21;
                        str25 = str78;
                        str38 = str79;
                        String str83 = str69;
                        kSerializerArr = kSerializerArr2;
                        List list5 = (List) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 10, kSerializerArr2[10], list4);
                        Unit unit12 = Unit.INSTANCE;
                        i |= 1024;
                        num10 = num22;
                        str70 = str70;
                        str69 = str83;
                        list2 = list5;
                        str42 = str80;
                        str48 = str38;
                        i19 = i7;
                        str73 = str36;
                        str71 = str35;
                        str30 = str48;
                        str31 = str42;
                        num22 = num10;
                        str28 = str81;
                        str32 = str37;
                        str33 = str73;
                        str29 = str69;
                        str74 = str32;
                        str79 = str30;
                        str75 = str22;
                        str76 = str23;
                        str77 = str24;
                        num21 = num9;
                        str78 = str25;
                        kSerializerArr2 = kSerializerArr;
                        str80 = str31;
                        str81 = str28;
                        list4 = list2;
                        str69 = str29;
                        str73 = str33;
                        break;
                    case 11:
                        str49 = str70;
                        str35 = str71;
                        i10 = i19;
                        str36 = str73;
                        str37 = str74;
                        str22 = str75;
                        str23 = str76;
                        str24 = str77;
                        num9 = num21;
                        str25 = str78;
                        str50 = str69;
                        num17 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 11, IntSerializer.INSTANCE, num17);
                        i11 = i | 2048;
                        Unit unit13 = Unit.INSTANCE;
                        kSerializerArr = kSerializerArr2;
                        num10 = num22;
                        i = i11;
                        str70 = str49;
                        str69 = str50;
                        str48 = str79;
                        list2 = list4;
                        str42 = str80;
                        i19 = i10;
                        str73 = str36;
                        str71 = str35;
                        str30 = str48;
                        str31 = str42;
                        num22 = num10;
                        str28 = str81;
                        str32 = str37;
                        str33 = str73;
                        str29 = str69;
                        str74 = str32;
                        str79 = str30;
                        str75 = str22;
                        str76 = str23;
                        str77 = str24;
                        num21 = num9;
                        str78 = str25;
                        kSerializerArr2 = kSerializerArr;
                        str80 = str31;
                        str81 = str28;
                        list4 = list2;
                        str69 = str29;
                        str73 = str33;
                        break;
                    case 12:
                        str49 = str70;
                        str35 = str71;
                        i10 = i19;
                        str36 = str73;
                        str37 = str74;
                        str22 = str75;
                        str23 = str76;
                        str24 = str77;
                        num9 = num21;
                        str50 = str69;
                        str25 = str78;
                        str79 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 12, StringSerializer.INSTANCE, str79);
                        i11 = i | 4096;
                        Unit unit14 = Unit.INSTANCE;
                        kSerializerArr = kSerializerArr2;
                        num10 = num22;
                        i = i11;
                        str70 = str49;
                        str69 = str50;
                        str48 = str79;
                        list2 = list4;
                        str42 = str80;
                        i19 = i10;
                        str73 = str36;
                        str71 = str35;
                        str30 = str48;
                        str31 = str42;
                        num22 = num10;
                        str28 = str81;
                        str32 = str37;
                        str33 = str73;
                        str29 = str69;
                        str74 = str32;
                        str79 = str30;
                        str75 = str22;
                        str76 = str23;
                        str77 = str24;
                        num21 = num9;
                        str78 = str25;
                        kSerializerArr2 = kSerializerArr;
                        str80 = str31;
                        str81 = str28;
                        list4 = list2;
                        str69 = str29;
                        str73 = str33;
                        break;
                    case 13:
                        str51 = str70;
                        str35 = str71;
                        str36 = str73;
                        str37 = str74;
                        str22 = str75;
                        str23 = str76;
                        str24 = str77;
                        num9 = num21;
                        str52 = str69;
                        iDecodeIntElement = compositeDecoderBeginStructure.decodeIntElement(serialDescriptor, 13);
                        Unit unit15 = Unit.INSTANCE;
                        i12 = i | 8192;
                        kSerializerArr = kSerializerArr2;
                        num10 = num22;
                        i = i12;
                        str70 = str51;
                        i19 = iDecodeIntElement;
                        str69 = str52;
                        str25 = str78;
                        str48 = str79;
                        list2 = list4;
                        str42 = str80;
                        str73 = str36;
                        str71 = str35;
                        str30 = str48;
                        str31 = str42;
                        num22 = num10;
                        str28 = str81;
                        str32 = str37;
                        str33 = str73;
                        str29 = str69;
                        str74 = str32;
                        str79 = str30;
                        str75 = str22;
                        str76 = str23;
                        str77 = str24;
                        num21 = num9;
                        str78 = str25;
                        kSerializerArr2 = kSerializerArr;
                        str80 = str31;
                        str81 = str28;
                        list4 = list2;
                        str69 = str29;
                        str73 = str33;
                        break;
                    case 14:
                        str51 = str70;
                        str35 = str71;
                        int i21 = i19;
                        str36 = str73;
                        str37 = str74;
                        str22 = str75;
                        str23 = str76;
                        str24 = str77;
                        str52 = str69;
                        num9 = num21;
                        str78 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 14, StringSerializer.INSTANCE, str78);
                        i12 = i | 16384;
                        Unit unit16 = Unit.INSTANCE;
                        iDecodeIntElement = i21;
                        kSerializerArr = kSerializerArr2;
                        num10 = num22;
                        i = i12;
                        str70 = str51;
                        i19 = iDecodeIntElement;
                        str69 = str52;
                        str25 = str78;
                        str48 = str79;
                        list2 = list4;
                        str42 = str80;
                        str73 = str36;
                        str71 = str35;
                        str30 = str48;
                        str31 = str42;
                        num22 = num10;
                        str28 = str81;
                        str32 = str37;
                        str33 = str73;
                        str29 = str69;
                        str74 = str32;
                        str79 = str30;
                        str75 = str22;
                        str76 = str23;
                        str77 = str24;
                        num21 = num9;
                        str78 = str25;
                        kSerializerArr2 = kSerializerArr;
                        str80 = str31;
                        str81 = str28;
                        list4 = list2;
                        str69 = str29;
                        str73 = str33;
                        break;
                    case 15:
                        str35 = str71;
                        i10 = i19;
                        str36 = str73;
                        str37 = str74;
                        str22 = str75;
                        str23 = str76;
                        str24 = str77;
                        num21 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 15, IntSerializer.INSTANCE, num21);
                        Unit unit17 = Unit.INSTANCE;
                        kSerializerArr = kSerializerArr2;
                        num10 = num22;
                        i = 32768 | i;
                        str70 = str70;
                        str69 = str69;
                        num9 = num21;
                        str25 = str78;
                        str48 = str79;
                        list2 = list4;
                        str42 = str80;
                        i19 = i10;
                        str73 = str36;
                        str71 = str35;
                        str30 = str48;
                        str31 = str42;
                        num22 = num10;
                        str28 = str81;
                        str32 = str37;
                        str33 = str73;
                        str29 = str69;
                        str74 = str32;
                        str79 = str30;
                        str75 = str22;
                        str76 = str23;
                        str77 = str24;
                        num21 = num9;
                        str78 = str25;
                        kSerializerArr2 = kSerializerArr;
                        str80 = str31;
                        str81 = str28;
                        list4 = list2;
                        str69 = str29;
                        str73 = str33;
                        break;
                    case 16:
                        str35 = str71;
                        i10 = i19;
                        str36 = str73;
                        str37 = str74;
                        str22 = str75;
                        str23 = str76;
                        str77 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 16, StringSerializer.INSTANCE, str77);
                        Unit unit18 = Unit.INSTANCE;
                        kSerializerArr = kSerializerArr2;
                        num10 = num22;
                        i = 65536 | i;
                        str70 = str70;
                        str69 = str69;
                        str24 = str77;
                        num9 = num21;
                        str25 = str78;
                        str48 = str79;
                        list2 = list4;
                        str42 = str80;
                        i19 = i10;
                        str73 = str36;
                        str71 = str35;
                        str30 = str48;
                        str31 = str42;
                        num22 = num10;
                        str28 = str81;
                        str32 = str37;
                        str33 = str73;
                        str29 = str69;
                        str74 = str32;
                        str79 = str30;
                        str75 = str22;
                        str76 = str23;
                        str77 = str24;
                        num21 = num9;
                        str78 = str25;
                        kSerializerArr2 = kSerializerArr;
                        str80 = str31;
                        str81 = str28;
                        list4 = list2;
                        str69 = str29;
                        str73 = str33;
                        break;
                    case 17:
                        str35 = str71;
                        i10 = i19;
                        str36 = str73;
                        str37 = str74;
                        str22 = str75;
                        str76 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 17, StringSerializer.INSTANCE, str76);
                        Unit unit19 = Unit.INSTANCE;
                        kSerializerArr = kSerializerArr2;
                        num10 = num22;
                        i = 131072 | i;
                        str70 = str70;
                        str69 = str69;
                        str23 = str76;
                        str24 = str77;
                        num9 = num21;
                        str25 = str78;
                        str48 = str79;
                        list2 = list4;
                        str42 = str80;
                        i19 = i10;
                        str73 = str36;
                        str71 = str35;
                        str30 = str48;
                        str31 = str42;
                        num22 = num10;
                        str28 = str81;
                        str32 = str37;
                        str33 = str73;
                        str29 = str69;
                        str74 = str32;
                        str79 = str30;
                        str75 = str22;
                        str76 = str23;
                        str77 = str24;
                        num21 = num9;
                        str78 = str25;
                        kSerializerArr2 = kSerializerArr;
                        str80 = str31;
                        str81 = str28;
                        list4 = list2;
                        str69 = str29;
                        str73 = str33;
                        break;
                    case 18:
                        str35 = str71;
                        i10 = i19;
                        str36 = str73;
                        str37 = str74;
                        str75 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 18, StringSerializer.INSTANCE, str75);
                        Unit unit20 = Unit.INSTANCE;
                        kSerializerArr = kSerializerArr2;
                        num10 = num22;
                        i = 262144 | i;
                        str70 = str70;
                        str69 = str69;
                        str22 = str75;
                        str23 = str76;
                        str24 = str77;
                        num9 = num21;
                        str25 = str78;
                        str48 = str79;
                        list2 = list4;
                        str42 = str80;
                        i19 = i10;
                        str73 = str36;
                        str71 = str35;
                        str30 = str48;
                        str31 = str42;
                        num22 = num10;
                        str28 = str81;
                        str32 = str37;
                        str33 = str73;
                        str29 = str69;
                        str74 = str32;
                        str79 = str30;
                        str75 = str22;
                        str76 = str23;
                        str77 = str24;
                        num21 = num9;
                        str78 = str25;
                        kSerializerArr2 = kSerializerArr;
                        str80 = str31;
                        str81 = str28;
                        list4 = list2;
                        str69 = str29;
                        str73 = str33;
                        break;
                    case 19:
                        str35 = str71;
                        i10 = i19;
                        str36 = str73;
                        str53 = str69;
                        str74 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 19, StringSerializer.INSTANCE, str74);
                        i13 = 524288 | i;
                        Unit unit21 = Unit.INSTANCE;
                        kSerializerArr = kSerializerArr2;
                        num10 = num22;
                        i = i13;
                        str69 = str53;
                        str37 = str74;
                        str22 = str75;
                        str23 = str76;
                        str24 = str77;
                        num9 = num21;
                        str25 = str78;
                        str48 = str79;
                        list2 = list4;
                        str42 = str80;
                        i19 = i10;
                        str73 = str36;
                        str71 = str35;
                        str30 = str48;
                        str31 = str42;
                        num22 = num10;
                        str28 = str81;
                        str32 = str37;
                        str33 = str73;
                        str29 = str69;
                        str74 = str32;
                        str79 = str30;
                        str75 = str22;
                        str76 = str23;
                        str77 = str24;
                        num21 = num9;
                        str78 = str25;
                        kSerializerArr2 = kSerializerArr;
                        str80 = str31;
                        str81 = str28;
                        list4 = list2;
                        str69 = str29;
                        str73 = str33;
                        break;
                    case 20:
                        str35 = str71;
                        i10 = i19;
                        str36 = str73;
                        str69 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 20, StringSerializer.INSTANCE, str69);
                        i14 = 1048576;
                        i13 = i14 | i;
                        Unit unit22 = Unit.INSTANCE;
                        str53 = str69;
                        kSerializerArr = kSerializerArr2;
                        num10 = num22;
                        i = i13;
                        str69 = str53;
                        str37 = str74;
                        str22 = str75;
                        str23 = str76;
                        str24 = str77;
                        num9 = num21;
                        str25 = str78;
                        str48 = str79;
                        list2 = list4;
                        str42 = str80;
                        i19 = i10;
                        str73 = str36;
                        str71 = str35;
                        str30 = str48;
                        str31 = str42;
                        num22 = num10;
                        str28 = str81;
                        str32 = str37;
                        str33 = str73;
                        str29 = str69;
                        str74 = str32;
                        str79 = str30;
                        str75 = str22;
                        str76 = str23;
                        str77 = str24;
                        num21 = num9;
                        str78 = str25;
                        kSerializerArr2 = kSerializerArr;
                        str80 = str31;
                        str81 = str28;
                        list4 = list2;
                        str69 = str29;
                        str73 = str33;
                        break;
                    case 21:
                        str35 = str71;
                        i10 = i19;
                        str36 = str73;
                        str70 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 21, StringSerializer.INSTANCE, str70);
                        i14 = 2097152;
                        i13 = i14 | i;
                        Unit unit222 = Unit.INSTANCE;
                        str53 = str69;
                        kSerializerArr = kSerializerArr2;
                        num10 = num22;
                        i = i13;
                        str69 = str53;
                        str37 = str74;
                        str22 = str75;
                        str23 = str76;
                        str24 = str77;
                        num9 = num21;
                        str25 = str78;
                        str48 = str79;
                        list2 = list4;
                        str42 = str80;
                        i19 = i10;
                        str73 = str36;
                        str71 = str35;
                        str30 = str48;
                        str31 = str42;
                        num22 = num10;
                        str28 = str81;
                        str32 = str37;
                        str33 = str73;
                        str29 = str69;
                        str74 = str32;
                        str79 = str30;
                        str75 = str22;
                        str76 = str23;
                        str77 = str24;
                        num21 = num9;
                        str78 = str25;
                        kSerializerArr2 = kSerializerArr;
                        str80 = str31;
                        str81 = str28;
                        list4 = list2;
                        str69 = str29;
                        str73 = str33;
                        break;
                    case 22:
                        str54 = str71;
                        i15 = i19;
                        str73 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 22, StringSerializer.INSTANCE, str73);
                        i16 = 4194304;
                        i |= i16;
                        Unit unit23 = Unit.INSTANCE;
                        str71 = str54;
                        kSerializerArr = kSerializerArr2;
                        num10 = num22;
                        str37 = str74;
                        str22 = str75;
                        str23 = str76;
                        str24 = str77;
                        num9 = num21;
                        str25 = str78;
                        str48 = str79;
                        list2 = list4;
                        str42 = str80;
                        i19 = i15;
                        str30 = str48;
                        str31 = str42;
                        num22 = num10;
                        str28 = str81;
                        str32 = str37;
                        str33 = str73;
                        str29 = str69;
                        str74 = str32;
                        str79 = str30;
                        str75 = str22;
                        str76 = str23;
                        str77 = str24;
                        num21 = num9;
                        str78 = str25;
                        kSerializerArr2 = kSerializerArr;
                        str80 = str31;
                        str81 = str28;
                        list4 = list2;
                        str69 = str29;
                        str73 = str33;
                        break;
                    case 23:
                        str54 = str71;
                        i15 = i19;
                        l9 = (Long) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 23, LongSerializer.INSTANCE, l9);
                        i16 = 8388608;
                        i |= i16;
                        Unit unit232 = Unit.INSTANCE;
                        str71 = str54;
                        kSerializerArr = kSerializerArr2;
                        num10 = num22;
                        str37 = str74;
                        str22 = str75;
                        str23 = str76;
                        str24 = str77;
                        num9 = num21;
                        str25 = str78;
                        str48 = str79;
                        list2 = list4;
                        str42 = str80;
                        i19 = i15;
                        str30 = str48;
                        str31 = str42;
                        num22 = num10;
                        str28 = str81;
                        str32 = str37;
                        str33 = str73;
                        str29 = str69;
                        str74 = str32;
                        str79 = str30;
                        str75 = str22;
                        str76 = str23;
                        str77 = str24;
                        num21 = num9;
                        str78 = str25;
                        kSerializerArr2 = kSerializerArr;
                        str80 = str31;
                        str81 = str28;
                        list4 = list2;
                        str69 = str29;
                        str73 = str33;
                        break;
                    case 24:
                        str54 = str71;
                        i15 = i19;
                        num20 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 24, IntSerializer.INSTANCE, num20);
                        i17 = 16777216;
                        i |= i17;
                        Unit unit2322 = Unit.INSTANCE;
                        str71 = str54;
                        kSerializerArr = kSerializerArr2;
                        num10 = num22;
                        str37 = str74;
                        str22 = str75;
                        str23 = str76;
                        str24 = str77;
                        num9 = num21;
                        str25 = str78;
                        str48 = str79;
                        list2 = list4;
                        str42 = str80;
                        i19 = i15;
                        str30 = str48;
                        str31 = str42;
                        num22 = num10;
                        str28 = str81;
                        str32 = str37;
                        str33 = str73;
                        str29 = str69;
                        str74 = str32;
                        str79 = str30;
                        str75 = str22;
                        str76 = str23;
                        str77 = str24;
                        num21 = num9;
                        str78 = str25;
                        kSerializerArr2 = kSerializerArr;
                        str80 = str31;
                        str81 = str28;
                        list4 = list2;
                        str69 = str29;
                        str73 = str33;
                        break;
                    case 25:
                        str54 = str71;
                        i15 = i19;
                        str72 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 25, StringSerializer.INSTANCE, str72);
                        i16 = MediaHttpDownloader.MAXIMUM_CHUNK_SIZE;
                        i |= i16;
                        Unit unit23222 = Unit.INSTANCE;
                        str71 = str54;
                        kSerializerArr = kSerializerArr2;
                        num10 = num22;
                        str37 = str74;
                        str22 = str75;
                        str23 = str76;
                        str24 = str77;
                        num9 = num21;
                        str25 = str78;
                        str48 = str79;
                        list2 = list4;
                        str42 = str80;
                        i19 = i15;
                        str30 = str48;
                        str31 = str42;
                        num22 = num10;
                        str28 = str81;
                        str32 = str37;
                        str33 = str73;
                        str29 = str69;
                        str74 = str32;
                        str79 = str30;
                        str75 = str22;
                        str76 = str23;
                        str77 = str24;
                        num21 = num9;
                        str78 = str25;
                        kSerializerArr2 = kSerializerArr;
                        str80 = str31;
                        str81 = str28;
                        list4 = list2;
                        str69 = str29;
                        str73 = str33;
                        break;
                    case 26:
                        str54 = str71;
                        i15 = i19;
                        num = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 26, IntSerializer.INSTANCE, num);
                        i16 = 67108864;
                        i |= i16;
                        Unit unit232222 = Unit.INSTANCE;
                        str71 = str54;
                        kSerializerArr = kSerializerArr2;
                        num10 = num22;
                        str37 = str74;
                        str22 = str75;
                        str23 = str76;
                        str24 = str77;
                        num9 = num21;
                        str25 = str78;
                        str48 = str79;
                        list2 = list4;
                        str42 = str80;
                        i19 = i15;
                        str30 = str48;
                        str31 = str42;
                        num22 = num10;
                        str28 = str81;
                        str32 = str37;
                        str33 = str73;
                        str29 = str69;
                        str74 = str32;
                        str79 = str30;
                        str75 = str22;
                        str76 = str23;
                        str77 = str24;
                        num21 = num9;
                        str78 = str25;
                        kSerializerArr2 = kSerializerArr;
                        str80 = str31;
                        str81 = str28;
                        list4 = list2;
                        str69 = str29;
                        str73 = str33;
                        break;
                    case 27:
                        i15 = i19;
                        str54 = str71;
                        l8 = (Long) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 27, LongSerializer.INSTANCE, l8);
                        i16 = 134217728;
                        i |= i16;
                        Unit unit2322222 = Unit.INSTANCE;
                        str71 = str54;
                        kSerializerArr = kSerializerArr2;
                        num10 = num22;
                        str37 = str74;
                        str22 = str75;
                        str23 = str76;
                        str24 = str77;
                        num9 = num21;
                        str25 = str78;
                        str48 = str79;
                        list2 = list4;
                        str42 = str80;
                        i19 = i15;
                        str30 = str48;
                        str31 = str42;
                        num22 = num10;
                        str28 = str81;
                        str32 = str37;
                        str33 = str73;
                        str29 = str69;
                        str74 = str32;
                        str79 = str30;
                        str75 = str22;
                        str76 = str23;
                        str77 = str24;
                        num21 = num9;
                        str78 = str25;
                        kSerializerArr2 = kSerializerArr;
                        str80 = str31;
                        str81 = str28;
                        list4 = list2;
                        str69 = str29;
                        str73 = str33;
                        break;
                    case 28:
                        i15 = i19;
                        num18 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 28, IntSerializer.INSTANCE, num18);
                        i17 = 268435456;
                        str54 = str71;
                        i |= i17;
                        Unit unit23222222 = Unit.INSTANCE;
                        str71 = str54;
                        kSerializerArr = kSerializerArr2;
                        num10 = num22;
                        str37 = str74;
                        str22 = str75;
                        str23 = str76;
                        str24 = str77;
                        num9 = num21;
                        str25 = str78;
                        str48 = str79;
                        list2 = list4;
                        str42 = str80;
                        i19 = i15;
                        str30 = str48;
                        str31 = str42;
                        num22 = num10;
                        str28 = str81;
                        str32 = str37;
                        str33 = str73;
                        str29 = str69;
                        str74 = str32;
                        str79 = str30;
                        str75 = str22;
                        str76 = str23;
                        str77 = str24;
                        num21 = num9;
                        str78 = str25;
                        kSerializerArr2 = kSerializerArr;
                        str80 = str31;
                        str81 = str28;
                        list4 = list2;
                        str69 = str29;
                        str73 = str33;
                        break;
                    case 29:
                        i15 = i19;
                        str71 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 29, StringSerializer.INSTANCE, str71);
                        i18 = 536870912;
                        i |= i18;
                        Unit unit24 = Unit.INSTANCE;
                        kSerializerArr = kSerializerArr2;
                        num10 = num22;
                        str37 = str74;
                        str22 = str75;
                        str23 = str76;
                        str24 = str77;
                        num9 = num21;
                        str25 = str78;
                        str48 = str79;
                        list2 = list4;
                        str42 = str80;
                        i19 = i15;
                        str30 = str48;
                        str31 = str42;
                        num22 = num10;
                        str28 = str81;
                        str32 = str37;
                        str33 = str73;
                        str29 = str69;
                        str74 = str32;
                        str79 = str30;
                        str75 = str22;
                        str76 = str23;
                        str77 = str24;
                        num21 = num9;
                        str78 = str25;
                        kSerializerArr2 = kSerializerArr;
                        str80 = str31;
                        str81 = str28;
                        list4 = list2;
                        str69 = str29;
                        str73 = str33;
                        break;
                    case 30:
                        i15 = i19;
                        convertInfoWS2 = (ConvertInfoWS) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 30, ConvertInfoWS$$serializer.INSTANCE, convertInfoWS2);
                        i18 = 1073741824;
                        i |= i18;
                        Unit unit242 = Unit.INSTANCE;
                        kSerializerArr = kSerializerArr2;
                        num10 = num22;
                        str37 = str74;
                        str22 = str75;
                        str23 = str76;
                        str24 = str77;
                        num9 = num21;
                        str25 = str78;
                        str48 = str79;
                        list2 = list4;
                        str42 = str80;
                        i19 = i15;
                        str30 = str48;
                        str31 = str42;
                        num22 = num10;
                        str28 = str81;
                        str32 = str37;
                        str33 = str73;
                        str29 = str69;
                        str74 = str32;
                        str79 = str30;
                        str75 = str22;
                        str76 = str23;
                        str77 = str24;
                        num21 = num9;
                        str78 = str25;
                        kSerializerArr2 = kSerializerArr;
                        str80 = str31;
                        str81 = str28;
                        list4 = list2;
                        str69 = str29;
                        str73 = str33;
                        break;
                    case 31:
                        i15 = i19;
                        num19 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 31, IntSerializer.INSTANCE, num19);
                        i18 = Integer.MIN_VALUE;
                        i |= i18;
                        Unit unit2422 = Unit.INSTANCE;
                        kSerializerArr = kSerializerArr2;
                        num10 = num22;
                        str37 = str74;
                        str22 = str75;
                        str23 = str76;
                        str24 = str77;
                        num9 = num21;
                        str25 = str78;
                        str48 = str79;
                        list2 = list4;
                        str42 = str80;
                        i19 = i15;
                        str30 = str48;
                        str31 = str42;
                        num22 = num10;
                        str28 = str81;
                        str32 = str37;
                        str33 = str73;
                        str29 = str69;
                        str74 = str32;
                        str79 = str30;
                        str75 = str22;
                        str76 = str23;
                        str77 = str24;
                        num21 = num9;
                        str78 = str25;
                        kSerializerArr2 = kSerializerArr;
                        str80 = str31;
                        str81 = str28;
                        list4 = list2;
                        str69 = str29;
                        str73 = str33;
                        break;
                    case 32:
                        i15 = i19;
                        jsonObject2 = (JsonObject) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 32, JsonObjectSerializer.INSTANCE, jsonObject2);
                        Unit unit25 = Unit.INSTANCE;
                        i20 = 1;
                        kSerializerArr = kSerializerArr2;
                        num10 = num22;
                        str37 = str74;
                        str22 = str75;
                        str23 = str76;
                        str24 = str77;
                        num9 = num21;
                        str25 = str78;
                        str48 = str79;
                        list2 = list4;
                        str42 = str80;
                        i19 = i15;
                        str30 = str48;
                        str31 = str42;
                        num22 = num10;
                        str28 = str81;
                        str32 = str37;
                        str33 = str73;
                        str29 = str69;
                        str74 = str32;
                        str79 = str30;
                        str75 = str22;
                        str76 = str23;
                        str77 = str24;
                        num21 = num9;
                        str78 = str25;
                        kSerializerArr2 = kSerializerArr;
                        str80 = str31;
                        str81 = str28;
                        list4 = list2;
                        str69 = str29;
                        str73 = str33;
                        break;
                    default:
                        throw new UnknownFieldException(iDecodeElementIndex);
                }
            }
            String str84 = str74;
            String str85 = str75;
            num2 = num17;
            str = str79;
            num3 = num19;
            jsonObject = jsonObject2;
            str2 = str70;
            str3 = str85;
            str4 = str77;
            str5 = str78;
            l = l10;
            str6 = str81;
            num4 = num22;
            list = list4;
            str7 = strDecodeStringElement4;
            str8 = strDecodeStringElement5;
            l2 = l9;
            str9 = str69;
            i2 = i19;
            str10 = str71;
            str11 = str82;
            str12 = str73;
            str13 = str84;
            i3 = iDecodeIntElement5;
            convertInfoWS = convertInfoWS2;
            str14 = str76;
            num5 = num21;
            str15 = strDecodeStringElement6;
            num6 = num20;
            i4 = iDecodeIntElement6;
            str16 = str80;
            num7 = num18;
            i5 = i20;
            String str86 = str72;
            l3 = l8;
            str17 = str86;
        }
        compositeDecoderBeginStructure.endStructure(serialDescriptor);
        return new TxStatusSubResponse(i, i5, str15, str8, i3, str11, str7, l, i4, str6, str16, num4, list, num2, str, i2, str5, num5, str4, str14, str3, str13, str9, str2, str12, l2, num6, str17, num, l3, num7, str10, convertInfoWS, num3, jsonObject, (SerializationConstructorMarker) null);
    }

    /* JADX DEBUG: Method merged with bridge method: serialize(Lkotlinx/serialization/encoding/Encoder;Ljava/lang/Object;)V */
    @Override // kotlinx.serialization.SerializationStrategy
    public final void serialize(@NotNull Encoder encoder, @NotNull TxStatusSubResponse txStatusSubResponse) {
        Intrinsics.checkNotNullParameter(encoder, "");
        Intrinsics.checkNotNullParameter(txStatusSubResponse, "");
        SerialDescriptor serialDescriptor = descriptor;
        CompositeEncoder compositeEncoderBeginStructure = encoder.beginStructure(serialDescriptor);
        TxStatusSubResponse.write$Self$OKPayCore_web3pay_lib(txStatusSubResponse, compositeEncoderBeginStructure, serialDescriptor);
        compositeEncoderBeginStructure.endStructure(serialDescriptor);
    }
}
