package uniffi.buy_sell;

import androidx.core.app.FrameMetricsAggregator;
import com.sun.jna.Structure;
import kotlin.jvm.internal.DefaultConstructorMarker;
import kotlin.jvm.internal.Intrinsics;
import org.jetbrains.annotations.NotNull;
import uniffi.UniffiCallbackInterfaceClone;
import uniffi.UniffiCallbackInterfaceFree;

/* JADX INFO: loaded from: classes13.dex */
@Structure.FieldOrder({"uniffiFree", "uniffiClone", "formatFrequency", "formatDate", "formatFrequencyOptionDate", "getBannerTitle", "getBannerMessage", "getDepositButtonLabel", "formatBuyAmount"})
public class UniffiVTableCallbackInterfaceRecurringBuyPlanDetailLocalization extends Structure {
    public static final int $stable = 8;
    public UniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod6 formatBuyAmount;
    public UniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod1 formatDate;
    public UniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod0 formatFrequency;
    public UniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod2 formatFrequencyOptionDate;
    public UniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod4 getBannerMessage;
    public UniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod3 getBannerTitle;
    public UniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod5 getDepositButtonLabel;
    public UniffiCallbackInterfaceClone uniffiClone;
    public UniffiCallbackInterfaceFree uniffiFree;

    /* JADX DEBUG: Don't trust debug lines info. Lines numbers was adjusted: min line is 0 */
    public UniffiVTableCallbackInterfaceRecurringBuyPlanDetailLocalization() {
        this(null, null, null, null, null, null, null, null, null, FrameMetricsAggregator.EVERY_DURATION, null);
    }

    /* JADX DEBUG: Can't inline method, not implemented redirect type for insn: 0x0054: CONSTRUCTOR 
  (wrap:uniffi.UniffiCallbackInterfaceFree:?: TERNARY null = ((wrap:int:0x0002: ARITH (r20v0 int) & (1 int) A[WRAPPED]) != (0 int)) ? (null uniffi.UniffiCallbackInterfaceFree) : (r11v0 uniffi.UniffiCallbackInterfaceFree))
  (wrap:uniffi.UniffiCallbackInterfaceClone:?: TERNARY null = ((wrap:int:0x000a: ARITH (r20v0 int) & (2 int) A[WRAPPED]) != (0 int)) ? (null uniffi.UniffiCallbackInterfaceClone) : (r12v0 uniffi.UniffiCallbackInterfaceClone))
  (wrap:uniffi.buy_sell.UniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod0:?: TERNARY null = ((wrap:int:0x0011: ARITH (r20v0 int) & (4 int) A[WRAPPED]) != (0 int)) ? (null uniffi.buy_sell.UniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod0) : (r13v0 uniffi.buy_sell.UniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod0))
  (wrap:uniffi.buy_sell.UniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod1:?: TERNARY null = ((wrap:int:0x0018: ARITH (r20v0 int) & (8 int) A[WRAPPED]) != (0 int)) ? (null uniffi.buy_sell.UniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod1) : (r14v0 uniffi.buy_sell.UniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod1))
  (wrap:uniffi.buy_sell.UniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod2:?: TERNARY null = ((wrap:int:0x001f: ARITH (r20v0 int) & (16 int) A[WRAPPED]) != (0 int)) ? (null uniffi.buy_sell.UniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod2) : (r15v0 uniffi.buy_sell.UniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod2))
  (wrap:uniffi.buy_sell.UniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod3:?: TERNARY null = ((wrap:int:0x0026: ARITH (r20v0 int) & (32 int) A[WRAPPED]) != (0 int)) ? (null uniffi.buy_sell.UniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod3) : (r16v0 uniffi.buy_sell.UniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod3))
  (wrap:uniffi.buy_sell.UniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod4:?: TERNARY null = ((wrap:int:0x002e: ARITH (r20v0 int) & (64 int) A[WRAPPED]) != (0 int)) ? (null uniffi.buy_sell.UniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod4) : (r17v0 uniffi.buy_sell.UniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod4))
  (wrap:uniffi.buy_sell.UniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod5:?: TERNARY null = ((wrap:int:0x0036: ARITH (r20v0 int) & (128 int) A[WRAPPED]) != (0 int)) ? (null uniffi.buy_sell.UniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod5) : (r18v0 uniffi.buy_sell.UniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod5))
  (wrap:uniffi.buy_sell.UniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod6:?: TERNARY null = ((wrap:int:0x003e: ARITH (r20v0 int) & (256 int) A[WRAPPED]) == (0 int)) ? (r19v0 uniffi.buy_sell.UniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod6) : (null uniffi.buy_sell.UniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod6))
 A[MD:(uniffi.UniffiCallbackInterfaceFree, uniffi.UniffiCallbackInterfaceClone, uniffi.buy_sell.UniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod0, uniffi.buy_sell.UniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod1, uniffi.buy_sell.UniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod2, uniffi.buy_sell.UniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod3, uniffi.buy_sell.UniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod4, uniffi.buy_sell.UniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod5, uniffi.buy_sell.UniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod6):void (m)] (LINE:261) call: uniffi.buy_sell.UniffiVTableCallbackInterfaceRecurringBuyPlanDetailLocalization.<init>(uniffi.UniffiCallbackInterfaceFree, uniffi.UniffiCallbackInterfaceClone, uniffi.buy_sell.UniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod0, uniffi.buy_sell.UniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod1, uniffi.buy_sell.UniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod2, uniffi.buy_sell.UniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod3, uniffi.buy_sell.UniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod4, uniffi.buy_sell.UniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod5, uniffi.buy_sell.UniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod6):void type: THIS */
    public /* synthetic */ UniffiVTableCallbackInterfaceRecurringBuyPlanDetailLocalization(UniffiCallbackInterfaceFree uniffiCallbackInterfaceFree, UniffiCallbackInterfaceClone uniffiCallbackInterfaceClone, UniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod0 uniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod0, UniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod1 uniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod1, UniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod2 uniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod2, UniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod3 uniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod3, UniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod4 uniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod4, UniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod5 uniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod5, UniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod6 uniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod6, int i, DefaultConstructorMarker defaultConstructorMarker) {
        this((i & 1) != 0 ? null : uniffiCallbackInterfaceFree, (i & 2) != 0 ? null : uniffiCallbackInterfaceClone, (i & 4) != 0 ? null : uniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod0, (i & 8) != 0 ? null : uniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod1, (i & 16) != 0 ? null : uniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod2, (i & 32) != 0 ? null : uniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod3, (i & 64) != 0 ? null : uniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod4, (i & 128) != 0 ? null : uniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod5, (i & 256) == 0 ? uniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod6 : null);
    }

    public static final class UniffiByValue extends UniffiVTableCallbackInterfaceRecurringBuyPlanDetailLocalization implements Structure.ByValue {
        public static final int $stable = 0;

        /* JADX DEBUG: Don't trust debug lines info. Lines numbers was adjusted: min line is 0 */
        public UniffiByValue() {
            this(null, null, null, null, null, null, null, null, null, FrameMetricsAggregator.EVERY_DURATION, null);
        }

        /* JADX DEBUG: Can't inline method, not implemented redirect type for insn: 0x0054: CONSTRUCTOR 
  (wrap:uniffi.UniffiCallbackInterfaceFree:?: TERNARY null = ((wrap:int:0x0002: ARITH (r20v0 int) & (1 int) A[WRAPPED]) != (0 int)) ? (null uniffi.UniffiCallbackInterfaceFree) : (r11v0 uniffi.UniffiCallbackInterfaceFree))
  (wrap:uniffi.UniffiCallbackInterfaceClone:?: TERNARY null = ((wrap:int:0x000a: ARITH (r20v0 int) & (2 int) A[WRAPPED]) != (0 int)) ? (null uniffi.UniffiCallbackInterfaceClone) : (r12v0 uniffi.UniffiCallbackInterfaceClone))
  (wrap:uniffi.buy_sell.UniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod0:?: TERNARY null = ((wrap:int:0x0011: ARITH (r20v0 int) & (4 int) A[WRAPPED]) != (0 int)) ? (null uniffi.buy_sell.UniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod0) : (r13v0 uniffi.buy_sell.UniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod0))
  (wrap:uniffi.buy_sell.UniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod1:?: TERNARY null = ((wrap:int:0x0018: ARITH (r20v0 int) & (8 int) A[WRAPPED]) != (0 int)) ? (null uniffi.buy_sell.UniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod1) : (r14v0 uniffi.buy_sell.UniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod1))
  (wrap:uniffi.buy_sell.UniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod2:?: TERNARY null = ((wrap:int:0x001f: ARITH (r20v0 int) & (16 int) A[WRAPPED]) != (0 int)) ? (null uniffi.buy_sell.UniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod2) : (r15v0 uniffi.buy_sell.UniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod2))
  (wrap:uniffi.buy_sell.UniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod3:?: TERNARY null = ((wrap:int:0x0026: ARITH (r20v0 int) & (32 int) A[WRAPPED]) != (0 int)) ? (null uniffi.buy_sell.UniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod3) : (r16v0 uniffi.buy_sell.UniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod3))
  (wrap:uniffi.buy_sell.UniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod4:?: TERNARY null = ((wrap:int:0x002e: ARITH (r20v0 int) & (64 int) A[WRAPPED]) != (0 int)) ? (null uniffi.buy_sell.UniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod4) : (r17v0 uniffi.buy_sell.UniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod4))
  (wrap:uniffi.buy_sell.UniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod5:?: TERNARY null = ((wrap:int:0x0036: ARITH (r20v0 int) & (128 int) A[WRAPPED]) != (0 int)) ? (null uniffi.buy_sell.UniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod5) : (r18v0 uniffi.buy_sell.UniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod5))
  (wrap:uniffi.buy_sell.UniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod6:?: TERNARY null = ((wrap:int:0x003e: ARITH (r20v0 int) & (256 int) A[WRAPPED]) == (0 int)) ? (r19v0 uniffi.buy_sell.UniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod6) : (null uniffi.buy_sell.UniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod6))
 A[MD:(uniffi.UniffiCallbackInterfaceFree, uniffi.UniffiCallbackInterfaceClone, uniffi.buy_sell.UniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod0, uniffi.buy_sell.UniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod1, uniffi.buy_sell.UniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod2, uniffi.buy_sell.UniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod3, uniffi.buy_sell.UniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod4, uniffi.buy_sell.UniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod5, uniffi.buy_sell.UniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod6):void (m)] (LINE:272) call: uniffi.buy_sell.UniffiVTableCallbackInterfaceRecurringBuyPlanDetailLocalization.UniffiByValue.<init>(uniffi.UniffiCallbackInterfaceFree, uniffi.UniffiCallbackInterfaceClone, uniffi.buy_sell.UniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod0, uniffi.buy_sell.UniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod1, uniffi.buy_sell.UniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod2, uniffi.buy_sell.UniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod3, uniffi.buy_sell.UniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod4, uniffi.buy_sell.UniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod5, uniffi.buy_sell.UniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod6):void type: THIS */
        public /* synthetic */ UniffiByValue(UniffiCallbackInterfaceFree uniffiCallbackInterfaceFree, UniffiCallbackInterfaceClone uniffiCallbackInterfaceClone, UniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod0 uniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod0, UniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod1 uniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod1, UniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod2 uniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod2, UniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod3 uniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod3, UniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod4 uniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod4, UniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod5 uniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod5, UniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod6 uniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod6, int i, DefaultConstructorMarker defaultConstructorMarker) {
            this((i & 1) != 0 ? null : uniffiCallbackInterfaceFree, (i & 2) != 0 ? null : uniffiCallbackInterfaceClone, (i & 4) != 0 ? null : uniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod0, (i & 8) != 0 ? null : uniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod1, (i & 16) != 0 ? null : uniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod2, (i & 32) != 0 ? null : uniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod3, (i & 64) != 0 ? null : uniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod4, (i & 128) != 0 ? null : uniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod5, (i & 256) == 0 ? uniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod6 : null);
        }

        public UniffiByValue(UniffiCallbackInterfaceFree uniffiCallbackInterfaceFree, UniffiCallbackInterfaceClone uniffiCallbackInterfaceClone, UniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod0 uniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod0, UniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod1 uniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod1, UniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod2 uniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod2, UniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod3 uniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod3, UniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod4 uniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod4, UniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod5 uniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod5, UniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod6 uniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod6) {
            super(uniffiCallbackInterfaceFree, uniffiCallbackInterfaceClone, uniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod0, uniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod1, uniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod2, uniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod3, uniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod4, uniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod5, uniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod6);
        }
    }

    public UniffiVTableCallbackInterfaceRecurringBuyPlanDetailLocalization(UniffiCallbackInterfaceFree uniffiCallbackInterfaceFree, UniffiCallbackInterfaceClone uniffiCallbackInterfaceClone, UniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod0 uniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod0, UniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod1 uniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod1, UniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod2 uniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod2, UniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod3 uniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod3, UniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod4 uniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod4, UniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod5 uniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod5, UniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod6 uniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod6) {
        this.uniffiFree = uniffiCallbackInterfaceFree;
        this.uniffiClone = uniffiCallbackInterfaceClone;
        this.formatFrequency = uniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod0;
        this.formatDate = uniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod1;
        this.formatFrequencyOptionDate = uniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod2;
        this.getBannerTitle = uniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod3;
        this.getBannerMessage = uniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod4;
        this.getDepositButtonLabel = uniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod5;
        this.formatBuyAmount = uniffiCallbackInterfaceRecurringBuyPlanDetailLocalizationMethod6;
    }

    public final void uniffiSetValue$OKCore_deploy(@NotNull UniffiVTableCallbackInterfaceRecurringBuyPlanDetailLocalization uniffiVTableCallbackInterfaceRecurringBuyPlanDetailLocalization) {
        Intrinsics.checkNotNullParameter(uniffiVTableCallbackInterfaceRecurringBuyPlanDetailLocalization, "");
        this.uniffiFree = uniffiVTableCallbackInterfaceRecurringBuyPlanDetailLocalization.uniffiFree;
        this.uniffiClone = uniffiVTableCallbackInterfaceRecurringBuyPlanDetailLocalization.uniffiClone;
        this.formatFrequency = uniffiVTableCallbackInterfaceRecurringBuyPlanDetailLocalization.formatFrequency;
        this.formatDate = uniffiVTableCallbackInterfaceRecurringBuyPlanDetailLocalization.formatDate;
        this.formatFrequencyOptionDate = uniffiVTableCallbackInterfaceRecurringBuyPlanDetailLocalization.formatFrequencyOptionDate;
        this.getBannerTitle = uniffiVTableCallbackInterfaceRecurringBuyPlanDetailLocalization.getBannerTitle;
        this.getBannerMessage = uniffiVTableCallbackInterfaceRecurringBuyPlanDetailLocalization.getBannerMessage;
        this.getDepositButtonLabel = uniffiVTableCallbackInterfaceRecurringBuyPlanDetailLocalization.getDepositButtonLabel;
        this.formatBuyAmount = uniffiVTableCallbackInterfaceRecurringBuyPlanDetailLocalization.formatBuyAmount;
    }
}
