package com.okinc.business.dex.trade.core.domain.model;

import com.okinc.business.dexlogic.bean.DexMultiTokenInfoBean;
import com.okinc.business.dexlogic.bean.DexMultiTokenInfoBean$$serializer;
import com.okinc.liveness.lca.EopTrackEvent;
import kotlin.jvm.internal.Intrinsics;
import kotlinx.serialization.KSerializer;
import kotlinx.serialization.UnknownFieldException;
import kotlinx.serialization.builtins.BuiltinSerializersKt;
import kotlinx.serialization.descriptors.SerialDescriptor;
import kotlinx.serialization.encoding.CompositeDecoder;
import kotlinx.serialization.encoding.CompositeEncoder;
import kotlinx.serialization.encoding.Decoder;
import kotlinx.serialization.encoding.Encoder;
import kotlinx.serialization.internal.GeneratedSerializer;
import kotlinx.serialization.internal.PluginGeneratedSerialDescriptor;
import kotlinx.serialization.internal.SerializationConstructorMarker;
import kotlinx.serialization.internal.StringSerializer;
import org.jetbrains.annotations.NotNull;

/* JADX INFO: loaded from: classes15.dex */
public final /* synthetic */ class CommonDexInfo$$serializer implements GeneratedSerializer<CommonDexInfo> {
    public static final int $stable;
    public static final CommonDexInfo$$serializer INSTANCE;
    private static final SerialDescriptor descriptor;

    /* JADX DEBUG: Don't trust debug lines info. Lines numbers was adjusted: min line is 0 */
    private CommonDexInfo$$serializer() {
    }

    /* JADX DEBUG: Don't trust debug lines info. Lines numbers was adjusted: min line is 0 */
    @Override // kotlinx.serialization.KSerializer, kotlinx.serialization.SerializationStrategy, kotlinx.serialization.DeserializationStrategy
    public final SerialDescriptor getDescriptor() {
        return descriptor;
    }

    static {
        CommonDexInfo$$serializer commonDexInfo$$serializer = new CommonDexInfo$$serializer();
        INSTANCE = commonDexInfo$$serializer;
        $stable = 8;
        PluginGeneratedSerialDescriptor pluginGeneratedSerialDescriptor = new PluginGeneratedSerialDescriptor("com.okinc.business.dex.trade.core.domain.model.CommonDexInfo", commonDexInfo$$serializer, 21);
        pluginGeneratedSerialDescriptor.addElement("code", true);
        pluginGeneratedSerialDescriptor.addElement(EopTrackEvent.KEY_ERROR_MSG_HUMP, true);
        pluginGeneratedSerialDescriptor.addElement("fromToken", true);
        pluginGeneratedSerialDescriptor.addElement("toToken", true);
        pluginGeneratedSerialDescriptor.addElement("fromTokenValue", true);
        pluginGeneratedSerialDescriptor.addElement("fromTokenAmount", true);
        pluginGeneratedSerialDescriptor.addElement("nativeTokenPrice", true);
        pluginGeneratedSerialDescriptor.addElement("estimateReserveGasTokenFee", true);
        pluginGeneratedSerialDescriptor.addElement("fromPriceFluctuation", true);
        pluginGeneratedSerialDescriptor.addElement("toPriceFluctuation", true);
        pluginGeneratedSerialDescriptor.addElement("priceFluctuationThreshold", true);
        pluginGeneratedSerialDescriptor.addElement("priceFluctuationMonitorTime", true);
        pluginGeneratedSerialDescriptor.addElement("rateFluctuationThreshold", true);
        pluginGeneratedSerialDescriptor.addElement("rateFluctuation", true);
        pluginGeneratedSerialDescriptor.addElement("slippageFluctuationHold", true);
        pluginGeneratedSerialDescriptor.addElement("nativeTokenUnitPriceUsd", true);
        pluginGeneratedSerialDescriptor.addElement("teeSignMarketRelTs", true);
        pluginGeneratedSerialDescriptor.addElement("teeSignTpslRelTs", true);
        pluginGeneratedSerialDescriptor.addElement("nativeTokenSymbol", true);
        pluginGeneratedSerialDescriptor.addElement("tradeTaxes", true);
        pluginGeneratedSerialDescriptor.addElement("remainingQuota", true);
        descriptor = pluginGeneratedSerialDescriptor;
    }

    @Override // kotlinx.serialization.internal.GeneratedSerializer
    public final KSerializer<?>[] childSerializers() {
        StringSerializer stringSerializer = StringSerializer.INSTANCE;
        DexMultiTokenInfoBean$$serializer dexMultiTokenInfoBean$$serializer = DexMultiTokenInfoBean$$serializer.INSTANCE;
        return new KSerializer[]{BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(dexMultiTokenInfoBean$$serializer), BuiltinSerializersKt.getNullable(dexMultiTokenInfoBean$$serializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), stringSerializer, stringSerializer, stringSerializer, BuiltinSerializersKt.getNullable(stringSerializer), stringSerializer};
    }

    /* JADX DEBUG: Method merged with bridge method: deserialize(Lkotlinx/serialization/encoding/Decoder;)Ljava/lang/Object; */
    @Override // kotlinx.serialization.DeserializationStrategy
    public final CommonDexInfo deserialize(@NotNull Decoder decoder) {
        String str;
        String str2;
        String str3;
        String str4;
        String str5;
        String strDecodeStringElement;
        DexMultiTokenInfoBean dexMultiTokenInfoBean;
        DexMultiTokenInfoBean dexMultiTokenInfoBean2;
        String str6;
        String str7;
        String str8;
        String str9;
        String str10;
        String str11;
        String str12;
        String str13;
        String str14;
        String str15;
        String str16;
        String str17;
        int i;
        String str18;
        String str19;
        DexMultiTokenInfoBean dexMultiTokenInfoBean3;
        String str20;
        DexMultiTokenInfoBean dexMultiTokenInfoBean4;
        String str21;
        String str22;
        String str23;
        String str24;
        String str25;
        String str26;
        String str27;
        Intrinsics.checkNotNullParameter(decoder, "");
        SerialDescriptor serialDescriptor = descriptor;
        CompositeDecoder compositeDecoderBeginStructure = decoder.beginStructure(serialDescriptor);
        if (compositeDecoderBeginStructure.decodeSequentially()) {
            StringSerializer stringSerializer = StringSerializer.INSTANCE;
            String str28 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 0, stringSerializer, null);
            String str29 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 1, stringSerializer, null);
            DexMultiTokenInfoBean$$serializer dexMultiTokenInfoBean$$serializer = DexMultiTokenInfoBean$$serializer.INSTANCE;
            DexMultiTokenInfoBean dexMultiTokenInfoBean5 = (DexMultiTokenInfoBean) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 2, dexMultiTokenInfoBean$$serializer, null);
            DexMultiTokenInfoBean dexMultiTokenInfoBean6 = (DexMultiTokenInfoBean) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 3, dexMultiTokenInfoBean$$serializer, null);
            String str30 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 4, stringSerializer, null);
            String str31 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 5, stringSerializer, null);
            String str32 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 6, stringSerializer, null);
            String str33 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 7, stringSerializer, null);
            String str34 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 8, stringSerializer, null);
            String str35 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 9, stringSerializer, null);
            String str36 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 10, stringSerializer, null);
            String str37 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 11, stringSerializer, null);
            String str38 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 12, stringSerializer, null);
            String str39 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 13, stringSerializer, null);
            String str40 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 14, stringSerializer, null);
            String str41 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 15, stringSerializer, null);
            String strDecodeStringElement2 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 16);
            String strDecodeStringElement3 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 17);
            String strDecodeStringElement4 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 18);
            str5 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 19, stringSerializer, null);
            strDecodeStringElement = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 20);
            str13 = strDecodeStringElement2;
            str17 = str36;
            str14 = str37;
            str10 = str28;
            str16 = strDecodeStringElement4;
            str15 = strDecodeStringElement3;
            str12 = str41;
            str11 = str40;
            str8 = str39;
            str18 = str38;
            str7 = str31;
            dexMultiTokenInfoBean2 = dexMultiTokenInfoBean6;
            str6 = str30;
            str9 = str34;
            dexMultiTokenInfoBean = dexMultiTokenInfoBean5;
            str = str29;
            str3 = str32;
            str2 = str35;
            str4 = str33;
            i = 2097151;
        } else {
            int i2 = 20;
            String str42 = null;
            String str43 = null;
            String str44 = null;
            String str45 = null;
            String str46 = null;
            String strDecodeStringElement5 = null;
            String str47 = null;
            String str48 = null;
            String str49 = null;
            String strDecodeStringElement6 = null;
            String strDecodeStringElement7 = null;
            String strDecodeStringElement8 = null;
            String str50 = null;
            String str51 = null;
            DexMultiTokenInfoBean dexMultiTokenInfoBean7 = null;
            String str52 = null;
            String str53 = null;
            DexMultiTokenInfoBean dexMultiTokenInfoBean8 = null;
            String str54 = null;
            boolean z = true;
            String str55 = null;
            int i3 = 0;
            String str56 = null;
            while (z) {
                int iDecodeElementIndex = compositeDecoderBeginStructure.decodeElementIndex(serialDescriptor);
                switch (iDecodeElementIndex) {
                    case -1:
                        z = false;
                        str56 = str56;
                        str43 = str43;
                        str42 = str42;
                        break;
                    case 0:
                        str19 = str51;
                        dexMultiTokenInfoBean3 = dexMultiTokenInfoBean7;
                        i3 |= 1;
                        str43 = str43;
                        str20 = str54;
                        dexMultiTokenInfoBean4 = dexMultiTokenInfoBean8;
                        str21 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 0, StringSerializer.INSTANCE, str53);
                        str22 = str50;
                        str56 = str56;
                        str23 = str52;
                        str42 = str42;
                        str50 = str22;
                        str52 = str23;
                        str53 = str21;
                        dexMultiTokenInfoBean7 = dexMultiTokenInfoBean3;
                        str51 = str19;
                        dexMultiTokenInfoBean8 = dexMultiTokenInfoBean4;
                        str54 = str20;
                        i2 = 20;
                        break;
                    case 1:
                        str19 = str51;
                        dexMultiTokenInfoBean3 = dexMultiTokenInfoBean7;
                        i3 |= 2;
                        str43 = str43;
                        str42 = str42;
                        str20 = str54;
                        dexMultiTokenInfoBean4 = dexMultiTokenInfoBean8;
                        str21 = str53;
                        str23 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 1, StringSerializer.INSTANCE, str52);
                        str22 = str50;
                        str56 = str56;
                        str50 = str22;
                        str52 = str23;
                        str53 = str21;
                        dexMultiTokenInfoBean7 = dexMultiTokenInfoBean3;
                        str51 = str19;
                        dexMultiTokenInfoBean8 = dexMultiTokenInfoBean4;
                        str54 = str20;
                        i2 = 20;
                        break;
                    case 2:
                        str24 = str56;
                        str25 = str50;
                        str19 = str51;
                        dexMultiTokenInfoBean3 = dexMultiTokenInfoBean7;
                        i3 |= 4;
                        str43 = str43;
                        str42 = str42;
                        str21 = str53;
                        str20 = str54;
                        dexMultiTokenInfoBean4 = (DexMultiTokenInfoBean) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 2, DexMultiTokenInfoBean$$serializer.INSTANCE, dexMultiTokenInfoBean8);
                        str22 = str25;
                        str56 = str24;
                        str23 = str52;
                        str50 = str22;
                        str52 = str23;
                        str53 = str21;
                        dexMultiTokenInfoBean7 = dexMultiTokenInfoBean3;
                        str51 = str19;
                        dexMultiTokenInfoBean8 = dexMultiTokenInfoBean4;
                        str54 = str20;
                        i2 = 20;
                        break;
                    case 3:
                        str26 = str54;
                        str19 = str51;
                        dexMultiTokenInfoBean3 = (DexMultiTokenInfoBean) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 3, DexMultiTokenInfoBean$$serializer.INSTANCE, dexMultiTokenInfoBean7);
                        i3 |= 8;
                        str22 = str50;
                        str56 = str56;
                        str43 = str43;
                        str42 = str42;
                        str23 = str52;
                        str21 = str53;
                        str20 = str26;
                        dexMultiTokenInfoBean4 = dexMultiTokenInfoBean8;
                        str50 = str22;
                        str52 = str23;
                        str53 = str21;
                        dexMultiTokenInfoBean7 = dexMultiTokenInfoBean3;
                        str51 = str19;
                        dexMultiTokenInfoBean8 = dexMultiTokenInfoBean4;
                        str54 = str20;
                        i2 = 20;
                        break;
                    case 4:
                        str26 = str54;
                        str19 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 4, StringSerializer.INSTANCE, str51);
                        i3 |= 16;
                        str22 = str50;
                        str56 = str56;
                        str43 = str43;
                        str42 = str42;
                        dexMultiTokenInfoBean3 = dexMultiTokenInfoBean7;
                        str23 = str52;
                        str21 = str53;
                        str20 = str26;
                        dexMultiTokenInfoBean4 = dexMultiTokenInfoBean8;
                        str50 = str22;
                        str52 = str23;
                        str53 = str21;
                        dexMultiTokenInfoBean7 = dexMultiTokenInfoBean3;
                        str51 = str19;
                        dexMultiTokenInfoBean8 = dexMultiTokenInfoBean4;
                        str54 = str20;
                        i2 = 20;
                        break;
                    case 5:
                        str24 = str56;
                        str25 = str50;
                        i3 |= 32;
                        str43 = str43;
                        str42 = str42;
                        str19 = str51;
                        dexMultiTokenInfoBean3 = dexMultiTokenInfoBean7;
                        str21 = str53;
                        dexMultiTokenInfoBean4 = dexMultiTokenInfoBean8;
                        str20 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 5, StringSerializer.INSTANCE, str54);
                        str22 = str25;
                        str56 = str24;
                        str23 = str52;
                        str50 = str22;
                        str52 = str23;
                        str53 = str21;
                        dexMultiTokenInfoBean7 = dexMultiTokenInfoBean3;
                        str51 = str19;
                        dexMultiTokenInfoBean8 = dexMultiTokenInfoBean4;
                        str54 = str20;
                        i2 = 20;
                        break;
                    case 6:
                        str22 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 6, StringSerializer.INSTANCE, str50);
                        i3 |= 64;
                        str56 = str56;
                        str42 = str42;
                        str19 = str51;
                        dexMultiTokenInfoBean3 = dexMultiTokenInfoBean7;
                        str23 = str52;
                        str21 = str53;
                        dexMultiTokenInfoBean4 = dexMultiTokenInfoBean8;
                        str20 = str54;
                        str50 = str22;
                        str52 = str23;
                        str53 = str21;
                        dexMultiTokenInfoBean7 = dexMultiTokenInfoBean3;
                        str51 = str19;
                        dexMultiTokenInfoBean8 = dexMultiTokenInfoBean4;
                        str54 = str20;
                        i2 = 20;
                        break;
                    case 7:
                        str27 = str56;
                        i3 |= 128;
                        str49 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 7, StringSerializer.INSTANCE, str49);
                        str56 = str27;
                        str22 = str50;
                        str19 = str51;
                        dexMultiTokenInfoBean3 = dexMultiTokenInfoBean7;
                        str23 = str52;
                        str21 = str53;
                        dexMultiTokenInfoBean4 = dexMultiTokenInfoBean8;
                        str20 = str54;
                        str50 = str22;
                        str52 = str23;
                        str53 = str21;
                        dexMultiTokenInfoBean7 = dexMultiTokenInfoBean3;
                        str51 = str19;
                        dexMultiTokenInfoBean8 = dexMultiTokenInfoBean4;
                        str54 = str20;
                        i2 = 20;
                        break;
                    case 8:
                        i3 |= 256;
                        str56 = str56;
                        str19 = str51;
                        dexMultiTokenInfoBean3 = dexMultiTokenInfoBean7;
                        str23 = str52;
                        str21 = str53;
                        dexMultiTokenInfoBean4 = dexMultiTokenInfoBean8;
                        str20 = str54;
                        str42 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 8, StringSerializer.INSTANCE, str42);
                        str22 = str50;
                        str50 = str22;
                        str52 = str23;
                        str53 = str21;
                        dexMultiTokenInfoBean7 = dexMultiTokenInfoBean3;
                        str51 = str19;
                        dexMultiTokenInfoBean8 = dexMultiTokenInfoBean4;
                        str54 = str20;
                        i2 = 20;
                        break;
                    case 9:
                        i3 |= 512;
                        str56 = str56;
                        str19 = str51;
                        dexMultiTokenInfoBean3 = dexMultiTokenInfoBean7;
                        str23 = str52;
                        str21 = str53;
                        dexMultiTokenInfoBean4 = dexMultiTokenInfoBean8;
                        str20 = str54;
                        str45 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 9, StringSerializer.INSTANCE, str45);
                        str22 = str50;
                        str50 = str22;
                        str52 = str23;
                        str53 = str21;
                        dexMultiTokenInfoBean7 = dexMultiTokenInfoBean3;
                        str51 = str19;
                        dexMultiTokenInfoBean8 = dexMultiTokenInfoBean4;
                        str54 = str20;
                        i2 = 20;
                        break;
                    case 10:
                        i3 |= 1024;
                        str56 = str56;
                        str19 = str51;
                        dexMultiTokenInfoBean3 = dexMultiTokenInfoBean7;
                        str23 = str52;
                        str21 = str53;
                        dexMultiTokenInfoBean4 = dexMultiTokenInfoBean8;
                        str20 = str54;
                        str44 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 10, StringSerializer.INSTANCE, str44);
                        str22 = str50;
                        str50 = str22;
                        str52 = str23;
                        str53 = str21;
                        dexMultiTokenInfoBean7 = dexMultiTokenInfoBean3;
                        str51 = str19;
                        dexMultiTokenInfoBean8 = dexMultiTokenInfoBean4;
                        str54 = str20;
                        i2 = 20;
                        break;
                    case 11:
                        str27 = str56;
                        i3 |= 2048;
                        str48 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 11, StringSerializer.INSTANCE, str48);
                        str56 = str27;
                        str22 = str50;
                        str19 = str51;
                        dexMultiTokenInfoBean3 = dexMultiTokenInfoBean7;
                        str23 = str52;
                        str21 = str53;
                        dexMultiTokenInfoBean4 = dexMultiTokenInfoBean8;
                        str20 = str54;
                        str50 = str22;
                        str52 = str23;
                        str53 = str21;
                        dexMultiTokenInfoBean7 = dexMultiTokenInfoBean3;
                        str51 = str19;
                        dexMultiTokenInfoBean8 = dexMultiTokenInfoBean4;
                        str54 = str20;
                        i2 = 20;
                        break;
                    case 12:
                        str27 = str56;
                        i3 |= 4096;
                        str47 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 12, StringSerializer.INSTANCE, str47);
                        str56 = str27;
                        str22 = str50;
                        str19 = str51;
                        dexMultiTokenInfoBean3 = dexMultiTokenInfoBean7;
                        str23 = str52;
                        str21 = str53;
                        dexMultiTokenInfoBean4 = dexMultiTokenInfoBean8;
                        str20 = str54;
                        str50 = str22;
                        str52 = str23;
                        str53 = str21;
                        dexMultiTokenInfoBean7 = dexMultiTokenInfoBean3;
                        str51 = str19;
                        dexMultiTokenInfoBean8 = dexMultiTokenInfoBean4;
                        str54 = str20;
                        i2 = 20;
                        break;
                    case 13:
                        i3 |= 8192;
                        str56 = str56;
                        str19 = str51;
                        dexMultiTokenInfoBean3 = dexMultiTokenInfoBean7;
                        str23 = str52;
                        str21 = str53;
                        dexMultiTokenInfoBean4 = dexMultiTokenInfoBean8;
                        str20 = str54;
                        str43 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 13, StringSerializer.INSTANCE, str43);
                        str22 = str50;
                        str50 = str22;
                        str52 = str23;
                        str53 = str21;
                        dexMultiTokenInfoBean7 = dexMultiTokenInfoBean3;
                        str51 = str19;
                        dexMultiTokenInfoBean8 = dexMultiTokenInfoBean4;
                        str54 = str20;
                        i2 = 20;
                        break;
                    case 14:
                        i3 |= 16384;
                        str56 = str56;
                        str19 = str51;
                        dexMultiTokenInfoBean3 = dexMultiTokenInfoBean7;
                        str23 = str52;
                        str21 = str53;
                        dexMultiTokenInfoBean4 = dexMultiTokenInfoBean8;
                        str20 = str54;
                        str46 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 14, StringSerializer.INSTANCE, str46);
                        str22 = str50;
                        str50 = str22;
                        str52 = str23;
                        str53 = str21;
                        dexMultiTokenInfoBean7 = dexMultiTokenInfoBean3;
                        str51 = str19;
                        dexMultiTokenInfoBean8 = dexMultiTokenInfoBean4;
                        str54 = str20;
                        i2 = 20;
                        break;
                    case 15:
                        str27 = str56;
                        i3 |= 32768;
                        str55 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 15, StringSerializer.INSTANCE, str55);
                        str56 = str27;
                        str22 = str50;
                        str19 = str51;
                        dexMultiTokenInfoBean3 = dexMultiTokenInfoBean7;
                        str23 = str52;
                        str21 = str53;
                        dexMultiTokenInfoBean4 = dexMultiTokenInfoBean8;
                        str20 = str54;
                        str50 = str22;
                        str52 = str23;
                        str53 = str21;
                        dexMultiTokenInfoBean7 = dexMultiTokenInfoBean3;
                        str51 = str19;
                        dexMultiTokenInfoBean8 = dexMultiTokenInfoBean4;
                        str54 = str20;
                        i2 = 20;
                        break;
                    case 16:
                        i3 |= 65536;
                        str22 = str50;
                        str19 = str51;
                        dexMultiTokenInfoBean3 = dexMultiTokenInfoBean7;
                        str23 = str52;
                        str21 = str53;
                        dexMultiTokenInfoBean4 = dexMultiTokenInfoBean8;
                        str20 = str54;
                        strDecodeStringElement5 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 16);
                        str50 = str22;
                        str52 = str23;
                        str53 = str21;
                        dexMultiTokenInfoBean7 = dexMultiTokenInfoBean3;
                        str51 = str19;
                        dexMultiTokenInfoBean8 = dexMultiTokenInfoBean4;
                        str54 = str20;
                        i2 = 20;
                        break;
                    case 17:
                        i3 |= 131072;
                        strDecodeStringElement6 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 17);
                        str22 = str50;
                        str19 = str51;
                        dexMultiTokenInfoBean3 = dexMultiTokenInfoBean7;
                        str23 = str52;
                        str21 = str53;
                        dexMultiTokenInfoBean4 = dexMultiTokenInfoBean8;
                        str20 = str54;
                        str50 = str22;
                        str52 = str23;
                        str53 = str21;
                        dexMultiTokenInfoBean7 = dexMultiTokenInfoBean3;
                        str51 = str19;
                        dexMultiTokenInfoBean8 = dexMultiTokenInfoBean4;
                        str54 = str20;
                        i2 = 20;
                        break;
                    case 18:
                        i3 |= 262144;
                        strDecodeStringElement8 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 18);
                        str22 = str50;
                        str19 = str51;
                        dexMultiTokenInfoBean3 = dexMultiTokenInfoBean7;
                        str23 = str52;
                        str21 = str53;
                        dexMultiTokenInfoBean4 = dexMultiTokenInfoBean8;
                        str20 = str54;
                        str50 = str22;
                        str52 = str23;
                        str53 = str21;
                        dexMultiTokenInfoBean7 = dexMultiTokenInfoBean3;
                        str51 = str19;
                        dexMultiTokenInfoBean8 = dexMultiTokenInfoBean4;
                        str54 = str20;
                        i2 = 20;
                        break;
                    case 19:
                        str56 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 19, StringSerializer.INSTANCE, str56);
                        i3 |= 524288;
                        str22 = str50;
                        str19 = str51;
                        dexMultiTokenInfoBean3 = dexMultiTokenInfoBean7;
                        str23 = str52;
                        str21 = str53;
                        dexMultiTokenInfoBean4 = dexMultiTokenInfoBean8;
                        str20 = str54;
                        str50 = str22;
                        str52 = str23;
                        str53 = str21;
                        dexMultiTokenInfoBean7 = dexMultiTokenInfoBean3;
                        str51 = str19;
                        dexMultiTokenInfoBean8 = dexMultiTokenInfoBean4;
                        str54 = str20;
                        i2 = 20;
                        break;
                    case 20:
                        strDecodeStringElement7 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, i2);
                        i3 |= 1048576;
                        break;
                    default:
                        throw new UnknownFieldException(iDecodeElementIndex);
                }
            }
            String str57 = str51;
            str = str52;
            str2 = str45;
            str3 = str50;
            str4 = str49;
            str5 = str56;
            strDecodeStringElement = strDecodeStringElement7;
            dexMultiTokenInfoBean = dexMultiTokenInfoBean8;
            dexMultiTokenInfoBean2 = dexMultiTokenInfoBean7;
            str6 = str57;
            str7 = str54;
            str8 = str43;
            str9 = str42;
            str10 = str53;
            str11 = str46;
            str12 = str55;
            str13 = strDecodeStringElement5;
            str14 = str48;
            str15 = strDecodeStringElement6;
            str16 = strDecodeStringElement8;
            str17 = str44;
            i = i3;
            str18 = str47;
        }
        compositeDecoderBeginStructure.endStructure(serialDescriptor);
        return new CommonDexInfo(i, str10, str, dexMultiTokenInfoBean, dexMultiTokenInfoBean2, str6, str7, str3, str4, str9, str2, str17, str14, str18, str8, str11, str12, str13, str15, str16, str5, strDecodeStringElement, (SerializationConstructorMarker) null);
    }

    /* JADX DEBUG: Method merged with bridge method: serialize(Lkotlinx/serialization/encoding/Encoder;Ljava/lang/Object;)V */
    @Override // kotlinx.serialization.SerializationStrategy
    public final void serialize(@NotNull Encoder encoder, @NotNull CommonDexInfo commonDexInfo) {
        Intrinsics.checkNotNullParameter(encoder, "");
        Intrinsics.checkNotNullParameter(commonDexInfo, "");
        SerialDescriptor serialDescriptor = descriptor;
        CompositeEncoder compositeEncoderBeginStructure = encoder.beginStructure(serialDescriptor);
        CommonDexInfo.write$Self$OKDex_dex_impl(commonDexInfo, compositeEncoderBeginStructure, serialDescriptor);
        compositeEncoderBeginStructure.endStructure(serialDescriptor);
    }
}
